agreement/service_test.go
crypto/rand.go

`TestAgreementSlowBlockPostDeadline` and other synchronous agreement tests were failing about 0.5% of the time, and more so on Travis. This PR eliminates flakes by making sortition (within these tests) seeded and deterministic.
- ran SlowBlockPostDeadline -count 1000 with success.
- verified in logs that same weight elected each run

fix flaky agreement test: make sortition deterministic

---

util/db/dbutil.go
util/db/dbutil_test.go

We see unexpected behavior when we have 1 thread doing inserts, and 2 threads doing selects of recently-inserted rows. One of the threads doing selects will get sql.ErrNoRows even though it is querying a row that was already committed by an insert.
The issue might be that shared-cache connections provide serializability but not strict serializability; see:
http://mailinglists.sqlite.org/cgi-bin/mailman/private/sqlite-users/2019-June/084813.html
As a workaround, stop using shared caches in sqlite. The shared cache isn't that important for our workload, and I can't reproduce the ledger bug when running in a no-shared-cache configuration.
By using private caches (no shared cache), we also maintain the performance optimization of allowing concurrent reads and writes (and, specifically, …

fix ledger ErrNoEntry issue due to sqlite

---

cmd/goal/clerk.go
cmd/goal/inspect.go
cmd/goal/inspect_test.go

Actually display the checksum for multisig PKs; also display txn Sender,
Receiver, and CloseRemainderTo using the same address encoding; and fix
the counter for displaying multiple txns in a file.

goal clerk inspect: more base32+checksum fixes

---

catchup/service.go

Existing code would retry retrieving a block regardless of whether the previous block was retrieved successfully. While (functionally) it won't hurt to make the subsequent attempt, it generate excessive network traffic when the first block retrieval is being delayed.
We want to keep the happy path retrieve blocks as fast as possible, while slowing down once we ran into network failures.

[GOAL2-777] Catchup performance : avoid retrying unless previous block was retrieved

---

scripts/configure_dev.sh

Added libtool, autoconf, and automake to configure_dev.sh which are required for building libsodium.

[GOAL2-628] Updated configure_dev.sh to support building libsodium

---

util/metrics/reporter.go
util/metrics/reporter_test.go

Example from config.json:
"NodeExporterPath": "./node_exporter --collector.systemd"
This should result in the following process being launched when metrics are enabled:
./node_exporter --collector.systemd --web.listen-address=:9100 --web.telemetry-path=/metrics
As of now the changing the NodeExporterPath as above causes StartProcess to error and does not launch node_exporter.

 Enhance NodeExporterPath JSON option to pass additional node_exporter arguments

---

scripts/compute_branch_release_network.sh

Once mainnet goes public, we want installs to default to running against mainnet.  TestNet will be a manual process.

Switch default genesis.json file to mainnet

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Pull requests and issues have inconsistent formats which could lead to improper use or missing information.
After this is merged in I'll check that they work.

Add GitHub templates.

---

logging/telemetryCommon.go
logging/telemetryConfig.go
logging/telemetryConfig_test.go
logging/telemetryhook.go
test/testdata/configs/logging/logging.config.example

Support configurable telemetry server credentials.

[GOAL2-698] support configurable telemetry credentials.

---

cmd/algons/dnsCmd.go
tools/network/cloudflare/cloudflare.go
tools/network/cloudflare/zones.go

Add the following functionality to algons:
1. Export zone DNS settings in BIND format - 
usage: algons dns export -n algodev.network -z algodev.network.bind
or send the output directly to the terminal
usage: algons dns export -n algodev.network
2. List existing zones for the current account - 
usage: algons dns list zones

[GOAL2-782] Export DNS configuration

---

cmd/algod/main.go
logging/telemetryspec/event.go
network/wsNetwork.go
util/metrics/counter.go
util/metrics/gauge.go
util/metrics/registry.go
util/metrics/registryCommon.go
util/metrics/registry_test.go
util/metrics/stringGauge.go
util/metrics/stringGaugeCommon.go
util/metrics/stringGauge_test.go

The heartbeat telemetry event is sent every 10 minutes and allow a simple way to find nodes contributing telemetry data. Extend that event to include metrics.

Add metrics to heartbeat event.

---

docker/Dockerfile

Had some trouble running the dev setup scripts in the provided docker file environment. They rely on sudo. Made changes.
Run build && test

Updating the docker file to work

---

cmd/algoh/main.go

Please review this change to capture logs In case algod terminates before block watcher initializes.

[GOAL2-614] Updated algoh to capture algod logs on early termination

---

util/db/dbutil_test.go

TestDBConcurrencyRW assumes `/dev/shm` device exists.  It doesn't on Mac, so use tmp folder in that case.

Fix TestDBConcurrencyRW test to run on Macs

---

cmd/goal/commands.go
cmd/goal/completion.go

as suggested in https://github.com/algorand/go-algorand/issues/80

add bash and zsh completion support

---

daemon/algod/api/server/lib/middlewares/auth.go
scripts/promote_stable.sh

We have a metrics endpoint to provide prometheus style metrics, it also requires the `X-Algo-API-Token: <token>` header. Some tools which are able to consume this endpoint, like Telegraf, assume authorization tokens will be provided as bearer tokens, like `Authorization: Bearer <token>`. So this adds that as a fallback.
Make sure both forms still work:
```
will@will-algorand:~$ curl http://localhost:10101/v1/status -H "Authorization: Bearer $(cat ~/.algorand/algod.token)"
{"lastRound":253920,"lastConsensusVersion":"https://github.com/algorandfoundation/specs/tree/5615adc36bad610c7f165fa2967f4ecfa75125f0","nextConsensusVersion":"https://github.com/algorandfoundation/specs/tree/5615adc36bad610c7f165fa2967f4ecfa75125f0","nextConsensusVersionRound":253921,"nextConsensusVersionSupported":true," …
```

Accept API Token in Authorization Header

---

tools/network/cloudflare/cloudflare.go

Taking pointer of iteration variable caused us to return the ZoneID for the last entry if we had any matches.  Copy it instead.
Debugged and fixed with manual testing.

Fix bug retrieving zone ID

---

Makefile

We should not allow a maligned commit to go-swagger@master break our build. temporary stop gap while we figure out how to do this properly.
(go-swagger added go mod support on master five days ago, but removed a flag and changed behavior in the process)

remove swagger-dependent build

---

Makefile

temporary stop gap while we investigate how to make sure swagger does not break our build.
This is an infrastructure fix and should not be used to generate a new release.  Note the resultant binary will differ in that it won't have a swagger.json file to serve.

remove swagger-dependent build (#119)

---

Makefile
scripts/check_deps.sh
scripts/configure_dev-deps.sh
scripts/configure_dev.sh

We previously removed swagger build step due to change in swagger upstream master. Now, we pin build to specific swagger release version using brew and debian package. Reenables swagger build step.
I preferred this over go/vendoring because we use swagger as a build tool, not as an import dependency.

[GOAL2-844] Re-enable go-swagger in build

---

daemon/kmd/api/api.go
daemon/kmd/api/v1/handlers.go
daemon/kmd/lib/kmdapi/requests.go

Fixes #141 
- Eliminates the following build warnings:
```
The swagger spec at "./swagger.json" showed up some valid but possibly unwanted constructs.
2019/07/11 11:42:06 See warnings below:
2019/07/11 11:42:06 - WARNING: definition "#/definitions/APIV1RequestEnvelope" is not used anywhere
2019/07/11 11:42:06 - WARNING: definition "#/definitions/VersionsRequest" is not used anywhere
2019/07/11 11:42:06 - WARNING: definition "#/definitions/ListWalletsRequest" is not used anywhere
2019/07/11 11:42:06 - WARNING: definition "#/definitions/APIV1Request" is not used anywhere
```
- tell swagger not to generate definitions for internal struct types
- make usage of certain requests explicit (and optional)

[GOAL2-314 GH-141] Fix kmd/swagger.json build warnings

---

rpcs/wsFetcherService.go

I noticed this task in the emailed list of pre-sprint-resumption tasks: downgrade the event in question to `Info` from `Warn`.
Automated tests.

[GOAL2-761] WsFetcherService::handleNetworkMsg telemetry event becomes level Info, was level Warn

---

cmd/goal/account.go
cmd/goal/multisig.go
test/e2e-go/cli/goal/expect/goalExpectCommon.exp

A simple change: when specifying addresses to `goal`, sometimes the shorthand the argument was `addr`, and sometimes `address`. I searched for instances of `addr` and replaced them with `address`.
Automated test suite.

[GOAL2-794] In goal, change all instances of --addr to --address

---

cmd/goal/clerk.go
cmd/goal/commands.go
cmd/goal/common.go
cmd/goal/multisig.go
netdeploy/networkTemplate.go
netdeploy/remote/nodecfg/nodeConfigurator.go
test/framework/fixtures/goalFixture.go
util/process.go

Propose a solution for #83 
Notes:
- File reads and writes were abstracted to new functions. Since they're quite generic for `cmd`, they live on commands.go
- Depending on `filename`, it distinguishes using two different functions (Write vs WriteFile, ReadAll vs ReadFile). The functions WriteFile and ReadFile functions close the file (not sure would be quite right for std*, so read/wrote directly to os.Std*).
- Further checks can be added to see if stdin is being piped or attached to a prompt. Worth it?
This can be tested doing something like the following:
`./goal clerk send -a 1 -t 52ZOFGOJR7A33SIJGOCSD7LTHJGB3JW26Y44D5THR25WIN2P5VGW2IUQMQ -o - -w unsafeWallet | ./goal clerk sign -i - -o - -w unsafeWallet | ./goal clerk inspect -`
Output:
```
-[0]
{
"sig": …
```

cmd/goal: allow stdin/stdout shell pipes

---

cmd/netgoal/generate.go
cmd/nodecfg/apply.go
netdeploy/remote/deployedNetwork.go
netdeploy/remote/nodeConfig.go
netdeploy/remote/nodecfg/nodeDir.go

Simplify NodeConfig struct. IsRelay is redundant, IsRelay() = nc.NetAddress != ""
compilation plus unit tests

GOAL2-653 deprecate IsRelay field in NodeConfig

---

daemon/algod/api/server/lib/common.go
daemon/algod/api/server/router.go
daemon/algod/api/server/v1/handlers/handlers.go
node/node.go

`node.Full` is redundant with exported behavior of node.AlgorandFullNode.
If we find a reason to abstract full node behavior we can add it back. But right now it is a lot more direct to interact with `AlgorandFullNode` directly.
Also expose the `Ledger` for #155. Removing redundant wrappers will be part of that PR.

Remove `node.Full` interface

---

installer/algorand.service
installer/algorand@.service
installer/debian/postinst
installer/debian/postrm
installer/debian/prerm
installer/rpm/algorand.spec
scripts/build_deb.sh

Add algorand@.service unit template into .deb and .rpm packages.
For deb I hacked the algorand@.service file into an older install, enabled both the base algorand.service for mainnet and an algorand@... for devnet. Installed a newly build .deb and it restarted both daemons. (Tested on Ubuntu 18)
A couple rounds of installing new rpm packages on Centos7 demonstrated restarting both the main `algorand` service and an `algorand@...` instance.

Systemd service template

---

daemon/algod/api/spec/v1/model.go
test/e2e-go/features/participation/participationRewards_test.go

Also removes some extraneous account poking, clarifying the test.
This enables/qualifies PR #155 (refactor `Node.GetBalanceAndStatus`) which is in turn related to #148 (Update `goal listpartkeys` to indicate which part key is registered)

[GOAL2-770] rework an e2e rewards test to test more API functionality

---

cmd/goal/account.go

final PR in a chain of PRs for GOAL2-770
Predicated on #163. Once that is merged I will open this for review.
Fixes #148 
When offline:
```
$ goal account listpartkeys
Registered	Filename                                                                        	Parent address                                              	 First round	  Last round	   First key
unknown   	BH55E5RMBD4GYWXGX5W5PJ5JAHPGM5OXKDQH5DC4O2MGI7NW4H6Q.10000.10111.partkey        	BH55E5RMBD4GYWXGX5W5PJ5JAHPGM5OXKDQH5DC4O2MGI7NW4H6VOE4CP4  	       10000	       10111	     29323.0
unknown   	BH55E5RMBD4GYWXGX5W5PJ5JAHPGM5OXKDQH5DC4O2MGI7NW4H6VOE4CP4.666888.1000000.partkey	BH55E5RMBD4GYWXGX5W5PJ5JAHPGM5OXKDQH5DC4O2MGI7NW4H6VOE4CP4  	      666888	     1000000	     69.7765
```
When online:
```
$ goal account listpartkeys …
```

[GOAL2-770] Print registration information in `goal account listpartkeys`

---

Makefile

Avoids including the full pathname of the build directory in the resulting
binaries, which makes it more likely that users can reproduce our builds
bit-for-bit.

pass -trimpath for more deterministic builds (go 1.13+)

---

cmd/algod/main.go
cmd/algoh/main.go
logging/log.go
logging/telemetry.go
logging/telemetryCommon.go
logging/telemetryConfig.go

When telemetry is disabled connection information is incomplete when communicating with relay nodes.
Before and after the fix, started a node with telemetry disabled and see that the error is reproduced and then fixed.
Missing metadata before fix:
Metadata after fix:

Fix missing connection metadata

---

data/pools/transactionPool.go
data/pools/transactionPool_test.go

Add a benchmark for steady-state operation of the txpool (adding transactions to the pool and then committing them in the ledger).  Helpful in understanding the performance implications of PR #150.

benchmark txpool steady-state operation

---

scripts/configure_dev.sh

Fixing remaining work on #1.
I mentioned in the issue only `autoconf` was necessary in a _vanilla_ Ubuntu 18.02 desktop, but also confirmed what other used mentioned using the `golang` docker base image regarding  `sudo`.
Since the script assumed `sudo` was already installed, it basically checks if it isn't and run `apt-get` commands assuming the user is root (`id -u = 0` could be added too).
<s>Just in case, the `SUDO_INSTALLED` var is because the script is ran with `set -e`, so `dpkg` will fail if `sudo` isn't installed (this way, won't).</s> Changed this considering what @zeldovich mentioned.
Easy way to check that works on `golang:1.12` (run dev script and also compile the tree):
`docker run -v $(pwd):/usr/src/go-algorand --rm golang:1.12 /bin/sh -c …

scripts: fix configure_dev.sh for linux

---

Makefile

Instead of enumerating all of our Go packages, just build and vet ./...
This didn't quite do the right thing before, when we had godep and
vendoring, but should work just fine now that we are using Go modules.

reduce terminal spew when running "make"

---

cmd/goal/node.go

This PR proposes to fix a permissions error when using `goal node create` to copy `genesis.json` to a destination folder. Additionally, I noticed a bug in IP validation, so I fixed that along the way.
Reproduced errors, then manually tested minimal fix to make errors stop reproducing. Filing ticket to write automated tests for this.

Bugfixes relating to goal node create

---

data/pools/transactionPool.go
util/condvar/timedwait.go
util/condvar/timedwait_test.go

When a new block for round R shows up in the ledger, it may take a while
until the TransactionPool's OnNewBlock() is called.  Until that happens,
the pool rejects new transactions that are valid starting from round
R+1, because according to the pool, the next round will be R, and the
transaction isn't valid for that round yet.  However, the client that
issued the transaction may have already seen that the latest round is R
(if the client queried the ledger's Latest() round, through the REST API),
and it's just the txpool that hasn't gotten the OnNewBlock() callback yet.
This commit deals with this potential race condition, which might be
the reason for some non-deterministic test failures.

txpool: avoid rejecting transactions that race with OnNewBlock()

---

cmd/updater/update.sh

Updated script to grab version from 2nd line of updater output.
Manually tested.

Fix [GOAL2-909] - update.sh fails to expand archive

---

cmd/catchupsrv/README.md
cmd/catchupsrv/download.go
cmd/catchupsrv/download_test.go
cmd/catchupsrv/main.go

1. Support for downloading blocks in subfolders instead of downloading all the blocks in the same folder (option `-subfolders`)
2. Use of logrus for logging.

catchupsrv: Support for downloading in subfolders

---

data/transactions/keyreg.go
data/transactions/keyreg_test.go

Add a check to keyreg transactions to prevent nonparticipatory accounts like the rewards pool from going online (or offline)

Prevent nonparticipatory accounts (e.g. rewards pool) from going online

---

cmd/algocfg/datadir.go
cmd/algocfg/getCommand.go
cmd/algocfg/main.go
cmd/algocfg/messages.go
cmd/algocfg/report.go
cmd/algocfg/resetCommand.go
cmd/algocfg/setCommand.go
cmd/goal/messages.go
installer/rpm/algorand.spec
scripts/build_deb.sh
scripts/build_package.sh
util/codecs/json.go

Adds `algocfg get|set|reset` commands to manipulate config.json
in a consistent and typesafe way.
Modified config.json is persisted minimally - only non-default
values are written.  Versioning is taken into account and migration
is performed as required.
This also includes a fix to SaveNonDefaultValuesToFile() which was
writing config.json files with a trailing empty line for each default
value that was skipped.

Created algocfg to provide cli access to config.json

---

catchup/pref_test.go
catchup/service.go
catchup/service_test.go
node/impls.go
node/node.go

Other than for the benchmark, catchup test code no longer requires the
following concrete implementations:
- data.Ledger
- certificate.Authenticate(block)
The benchmark in pref_test is the sole piece of code depending on the
datatest package (and by transitivity, the agreementtest package).

Simplify catchup test code.

---

node/indexer/db.go
node/indexer/indexer_test.go

when there was more than one transaction in a block, Indexer returned duplicate results. This PR fixes the issue. 
Added a test that verifies that no duplicate blocks are returned

-- Indexer no longer returns duplicate results

---

cmd/catchupsrv/main.go

algod got stricter about requiring the X-Algorand-NodeRandom header
should fix #285

fix catchupsrv with latest algod

---

README.md

`sh` could not run script because it has a `bash` shebang
Executing script directly works OK.

shell invocation conflicts with shebang

---

scripts/upload_config.sh

When upload_config.sh is called from another build script and current directory is not go-algorand, it fails to determine version correctly and fails later on deployment.

Fix upload_config.sh

---

protocol/tags.go

Reorder the tags in protocol/tags so that they stay in lexicographic order (to prevent duplicates).

Reorder protocol network tags into lexicographic order.

---

auction/tracker.go
auction/tracker_test.go

This fixes data races when calling auction tracker methods concurrently.
This does not enforce the immutability of Auctions and AuctionKey. Thus, a better design for the Tracker may be not to expose Auctions and AuctionKey as modifiable by external code.

Serialize concurrent access to data in the auction tracker.

---

.travis.yml

Stupid typo. I used lower case instead of upper case.
The travis comparison is case sensetive.

Fix typo in travis causing nightly build failures

---

cmd/dispenser/server.go

The Let's Encrypt certificate is great, as it's very out-of-the-box solution.
However, out existing deployment is having a firewall, which needs to have a copy of the certificate. That's becoming an issue, since the firewall need a copy of the certificate every time the certificate is being renewed.
If we want to move to a permanent certificate, we need to have the dispenser running with that certificate. This code change allows to run the dispenser with a particular certificate.
I tested that locally after hacking hosts file and grabbing a certificate manually.

Add custom cert/key option to dispenser

---

docker/releases/Dockerfile-stable
docker/releases/Dockerfile-stable-testnet
docker/releases/build_stable-testnet.sh
docker/releases/build_stable.sh

Updated our trivial docker images to simply be an install of the latest rel/stable release.

Replace old simple docker images with latest rel/stable

---

cmd/goal/clerk.go
data/transactions/transaction.go
ledger/eval.go
libgoal/transactions.go

Rename TxGroup.Transactions to TxGroup.TxGroupHashes that appears to be a better name.
Rely on existing tests.

Rename TxGroup.Transactions to TxGroup.TxGroupHashes

---

cmd/algod/main.go
cmd/algoh/main.go
cmd/goal/commands.go
cmd/goal/node.go
config/version.go
test/e2e-go/cli/goal/expect/goalExpectCommon.exp
test/e2e-go/cli/goal/expect/reportTest.exp

- add goal -v
- goal report includes output of goal -v, uname -a, genesisID, and goal node status

add goal report

---

.travis.yml

* Enable macos build for PR
* Ignore empty swagger.json.validated files (artifacts addon fails to upload them)
* Set macos version to the latest available 10.14
* Enable deploy build for rel/stable

Deploy rel/stable MacOS builds

---

scripts/travis/travis_wait.sh

When being used with travis directly, the message is valid and correct.
However, when invoked from our scripts, we want to have it emit the actual timed-command, rather then the travis-invoked script.

Correct the log message entry

---

test/scripts/auctionStart.sh

When running the auction tests on arm64, the auctionStart.sh script fails due to incorrect comparison of string "[n/a]" and max balance.
The source of the issue is yet to be found, but this PR addresses the script fail use case.
It adds an explicit test for "[n/a]" which is a legit `goal account list` output.
When this happen, we want to fail the auctionStart.sh while returning a proper error string.

Better error handling for auctionStart.sh

---

data/account/participation.go
data/accountManager.go
gen/generate.go
gen/walletData.go
libgoal/participation.go
netdeploy/networkTemplate.go
scripts/travis/external_build.sh

The agreement service is using the AccountManager.Keys to acquire the currently available participation keys. When doing that, a lock is being taken to synchronize the active participation accounts. In parallel, a DeleteOldKeys might also be called ( periodically ), in an attempt to delete the old keys. When doing that, the same lock is being taken as well.
The issue is that the update during the DeleteOldKeys might take a long time since it's accessing the disk. This would prevent the agreement service of moving forward ( which is undesirable ).
To work around this, I moved the key deletion so that it would be deleted in-memory with the lock, while allowing it to persist in the background. The deletion of the keys would still need to wait for all the key deletion to persist before it …

Decouple the AccountManager.DeleteOldKeys disk persistence execution

---

scripts/buildhost/s3streamup.sh
scripts/travis/external_build.sh

Current implementation was reading the entire log files for the given task once a task has started.
The problem is that it might display the log files from the previous iteration, as they remain on the S3 bucket.
To resolve that-
1. Before creating the new task, we need to delete the *first* log file. ( if it's there )
2. Before creating any of the log files, we need to delete the *subsequent* log file. ( if there is such )

Support re-run of ARM64 builds on travis

---

scripts/configure_dev-deps.sh

Running `go get -u <package name>` won't always return a non-zero error code when an error occur ( in particular, when the compilation of the downloaded package fails ).
That behavior prevents us from providing correct handing for that error case, and as a result we would fail the build down the road.
The expected output on the success use case is always an empty string. By capturing the output and comparing it to an empty string ( in addition to existing error code testing ), we can detect build errors of downloaded components.

Validate "go get" output

---

README.md
daemon/algod/api/README.md

README.md:
Made the lines 80 characters long to make reading easier from a text editor.
Added a statment about the brew/homebrow requirement before installation.
daemon/algod/api/README.md:
Fixed two typeos: OpenAI->OpenAPI and Payloard->Payload.

Readme file changes: shorter lines, brew requirement and typo fixes.

---

scripts/build_packages.sh

`rel/stable` is still using the legacy release scripts. These scripts still push directly to `testnet-latest`, this PR re-introduces the `pending_` prefix temporarily until we can get the new mechanism released.
Ran `VARIATIONS="base" ./scripts/build_packages.sh linux/amd64` locally with a custom `GATE_PREFIX` and observed that the prefix was applied to the resulting archives.

Revive the GATE_PREFIX variable in 'rel/stable' branch

---

scripts/configure_dev.sh

On MacOS builds, the tooling chain was using the `caskroom/cask` tap. This tap is no longer available on GitHub, and was moved to `homebrew/cask`.
This change is required in order to make MacOS builds.

Update brew tap for MacOS builds

---

scripts/ddconfig.sh

ddconfig.sh depends on algocfg, which is unavailable for current stable releases, use an alternative method if needed.
Ran this test program to verify the new functions:
```bash
#!/usr/bin/env bash
set -e
function PrintEndpointAddress() {
if [[ -f "$1/algocfg" ]]; then
echo $($1/algocfg get -p EndpointAddress -d "$2")
else
echo $(cat $2/config.json|grep EndpointAddress|cut -f 4 -d\")
fi
}
function SetEndpointAddress() {
if [[ -f "$1/algocfg" ]]; then
$($1/algocfg set -p EndpointAddress -d "$2" -v "$3")
else
$(sed -i -e 's/.*EndpointAddress.*/    "EndpointAddress": "'"$3"'",/' "$2/config.json")
fi
}
SetEndpointAddress ~/ ~/.algorand "1.2.3.4:test"
ENDPOINT=$(PrintEndpointAddress ~/ ~/.algorand)
echo $ENDPOINT
SetEndpointAddress ~/go/bin ~/.algorand "127.0.0.1:10101" …
```

Allow ddconfig to work on old installations which don't have algocfg

---

cmd/updater/versionCmd.go
util/s3/s3Helper.go
util/s3/s3Helper_test.go

`updater ver check -c stable` outputs a machine readable number that can conveniently be used in scripts, like `4294967323`. It would be nice to have a human readable form as well, so this adds a `--semantic` flag for printing the semantic version. 
Added some unit tests and ran the command.
```bash
$ updater ver check -c stable
Checking for files matching: 'channel/stable/node_stable_linux-amd64' in bucket algorand-releases
4294967323
$ updater ver check -c stable -s
Checking for files matching: 'channel/stable/node_stable_linux-amd64' in bucket algorand-releases
1.0.27
```

Add semantic version output flag to updater

---

cmd/updater/update.sh
util/s3/s3Helper.go

linux/arm won't bet updated via updater tool.
The wrong package was downloaded ( arm64 instead of arm ), which prevents us from running the deployed node ( obviously ).
Deploy the fix. Iteratively attempt to update.

linux/arm won't get updated via updater tool

---

data/txHandler.go

To avoid partitioning the network between nodes that have upgraded their software (but not necessarily their protocol version) and those that have not, it is important that only canonical transactions are rebroadcast.

Reencode transactions in txhandler

---

test/e2e-go/features/participation/participationRewards_test.go

The e2e unit test for the rewards residue fix would start failing once the fix would get enabled via a protocol upgrade. To prepare for that, I've updated the unit test so that it would work correctly on either scenarios.

Fix reward residue e2e test

---

cmd/goal/clerk.go
daemon/kmd/wallet/driver/sqlite.go
data/transactions/logic/eval.go
data/transactions/logic/eval_test.go
data/transactions/logic/program.go
data/transactions/verify/txn.go
protocol/hash.go
test/e2e-go/kmd/e2e_kmd_wallet_keyops_test.go
test/e2e-go/kmd/e2e_kmd_wallet_multisig_test.go

Arguments passed to ed25519verify are now domain-separated with the
constant string "ProgData" and the hash of the running program.

Implement domain separation for LogicSig ed25519verify.

---

cmd/goal/account.go
cmd/goal/asset.go
cmd/goal/messages.go
daemon/algod/api/server/v1/handlers/handlers.go
daemon/algod/api/spec/v1/model.go
data/basics/userBalance.go
libgoal/transactions.go
test/e2e-go/features/transactions/asset_test.go

This PR adds two optional fields to an asset's parameters:
`URL` points to somewhere with more information about the asset.
`MetadataHash` is a commitment to some metadata about the asset, in some unspecified format.
Each of these fields is stored internally in `AssetParams` as a `[32]byte`.

Add extra asset description fields

---

data/transactions/transaction.go
data/transactions/verify/txn.go
ledger/eval.go

Without this I believe there are similar partition issues to #387 if a user e.g. sends a transaction with an `LSig` prior to the protocol upgrade

Reject transactions with not-yet-protocol-enabled fields more quickly

---

data/transactions/logic/eval.go
data/transactions/logic/eval_test.go

This PR contains two security fixes (Thanks @justicz!) .
* Although the size of logic sig is checked, but the way we calculate the size didn't capture the case that a malicious user putting a large number of args of empty byte array (In such case, each arg will be counted 0, but there are still bytes needed to encode them on the wire). This could cause DoS attacks. This PR implements a check that limits the number of args to logic sig to be at most 255.
* Add a check that rejects logicSig eval if the protocol version is earlier.
Added unit tests in `eval_test.go` for these two cases.

Stricter logic sig check

---

test/testdata/deployednettemplates/recipes/scenario2/net.json
test/testdata/deployednettemplates/recipes/scenario2/node.json

Remove the APIEndpoint from scenario2 node configuration.
Having the above field set prevent some of the nodes instances to start up due to port binding conflict.
Deployed & tested.

Remove the APIEndpoint from scenario2 node configuration

---

scripts/build/beta.sh
scripts/build/nightly.sh
scripts/build/stable.sh

Build scripts weren't allowing me to reset the patch version to zero

Fix buildnumber.dat initialization

---

data/transactions/asset.go

Until now, it hasn't really mattered for security if a transaction could be sent from a zero public key. It seems like our crypto library does check for low order public keys, but because asset creators always intend for e.g. `Clawback == basics.Address{}` to signify that there is no way to clawback funds, we should explicitly check for that case.
@algoradam is adding a check for zero public key sender in `WellFormed` in a separate PR.

Ensure asset transaction correctness in case of zero sender

---

cmd/goal/asset.go

Don't make `--creator` a required flag, ensure that `--creator` is set if referring to asset only by `--asset`, make `goal asset info` functional with only `--assetid`.

Improve goal asset

---

data/transactions/logic/eval.go

We will want to know if/when these panics happen. Test coverage in `eval_test.go`'s `TestPanic`.

Log check/eval panics for telemetry

---

crypto/curve25519_test.go
data/transactions/transaction.go

Also add a test to confirm we don't accept a zero signature from a zero public key.
Max noticed that some ed25519 implementations (e.g., the reference Python implementation) accept zero signatures from zero public keys on 1 in 4 messages. Add a test to confirm this isn't true for our implementation. Also explicitly reject transactions with the zero address as the sender for defense-in-depth.

Explicitly disallow txns from zero address

---

libgoal/transactions.go

The current implementation of `FillUnsignedTxTemplate` will overwrite the txn's header, this will unset some fields of txn header such as `Note`. As a result, all the setters of the `Note` will be ineffective:
* https://github.com/algorand/go-algorand/blob/master/cmd/goal/asset.go#L221
* https://github.com/algorand/go-algorand/blob/master/cmd/goal/asset.go#L281
* https://github.com/algorand/go-algorand/blob/master/cmd/goal/asset.go#L362
*  https://github.com/algorand/go-algorand/blob/master/cmd/goal/asset.go#L436
* https://github.com/algorand/go-algorand/blob/master/cmd/goal/asset.go#L493
This PR change the implementation of `FillUnsignedTxTemplate` so that it didn't overwrite the entire txn header.
All test passed.

Fix goal asset transactions 

---

data/pools/transactionPool.go

Avoid copying elements of the transaction pool.

Optimize transaction pool pending transactions retrieval

---

data/ledger.go

Avoid logging on TransactionInLedgerError, as it seems to be a normal operational usecase.
This change provide minor gains to the overall performance, especially targeting use cases when we have long transaction pool backlog.

Remove redundant logging

---

data/pools/lsigEvalCache.go
data/pools/transactionPool.go
data/pools/transactionPool_test.go
ledger/eval.go
ledger/ledger_test.go

alternative to #428 where protocol version is part of the cache key. I think this is probably simpler and more correct.

LogicSig Eval caching explicitly based on (protocol version, txid)

---

cmd/pingpong/runCmd.go
shared/pingpong/accounts.go
shared/pingpong/config.go
shared/pingpong/pingpong.go
test/commandandcontrol/cc_agent/component/pingPongComponent.go

Add asset transaction support in Pingpong:
* add `--numasset` option to pingpong. When `numasset` is assigned (1 - 1000), pingpong will create `numasset` assets and init these assets in each account. Pingpong will then send asset transactions instead of normal payment transactions.
Tested locally.

Pingpong Asset Support

---

daemon/kmd/wallet/driver/ledger.go
daemon/kmd/wallet/driver/ledger_hid.go

This allows us to add support for additional transaction features (like
note fields or new asset transaction types) without having to keep
modifying kmd.  Fallback to older format of transaction encoding if the
Ledger device is running an old version of the Algorand app.

ledger wallet API: support sending full tx msgpack to device

---

config/config.go
data/basics/userBalance.go
data/transactions/transaction.go
ledger/archival_test.go
libgoal/transactions.go

Byte arrays don't make a ton of sense for these fields since we have to trim null bytes everywhere we want to display them. @rotemh

Make asset name, URL, unit name fields variable length

---

data/ledger.go
test/e2e-go/cli/goal/expect/goalExpectCommon.exp

Fix 1:
::AlgorandGoal::Abort calls ::AlgorandGoal::StopNetwork.
::AlgorandGoal::StopNetwork calls ::AlgorandGoal::Abort when fails to close the network.
This may cause infinite recursion when the conditions are right (e.g. is failing to close the network).
Fix: StopNetwork does not call Abort. 
Fix 2:
In ::AlgorandGoal::StopNetwork, when the spawn command output does not match the "Network Stopped under*", then NETWORK_STOP_MESSAGE is not set. If the spawn command did not timeout, then the "puts $NETWORK_STOP_MESSAGE" statement is executed. This is an expect script exception.
When ::AlgorandGoal::StopNetwork is called from try/catch statement, the exception is caught, and ::AlgorandGoal::Abort is called, which calls ::AlgorandGoal::StopNetwork.
Fix: initialize the variable to empty …

Two fixes to possible infinite recursion in ::AlgorandGoal::StopNetwork

---

cmd/goal/node.go
config/config.go

Before the fix 'goal network create' generated config.json
without 'Version' field. That forces config loader to assume Version=0
and start migrations.
If BroadcastConnectionsLimit set to 0 (special value) it is overwritten by -1
that is a new parameter introduced in config v4.
BroadcastConnectionsLimit does not exist in v3 with assumed value 0 in migration.
No tests

Fix version in config file generated by goal cmd

---

data/ledger.go
data/pools/transactionPool.go
data/txHandler_test.go
ledger/cow.go
ledger/eval.go
ledger/ledger.go
ledger/txtail.go
logging/telemetryspec/metric.go

Block assembly often get executed before the transactions from the previous round are cleared from the transactions pool.
Our existing implementation does detect these transactions and excludes them from the newly assembled proposal correctly, however, it does that with some undesired overhead.
This PR eliminate most of that overhead by taking the ledger lock *once*, acquiring the list of the transactions from the previous round, and using that list to filter out pending transactions.

Optimize block assembly of previously included transactions

---

data/pools/transactionPool.go
shared/pingpong/accounts.go
shared/pingpong/pingpong.go

My previous PR #404  did a wrong change in transaction pool mechanism. The fee need to increase whenever the number of whole blocks in transaction pool increases (not only on receiving a new block). Otherwise, the transaction pool will leave DDoS opportunities.

Fix fee increase in transaction pool

---

cmd/goal/clerk.go

remove unused --round
apply --time-stamp to FirstValidTime

cleanup `goal clerk dryrun`

---

cmd/goal/asset.go
libgoal/transactions.go

`goal asset config` was currently failing with a cryptic error if `--assetid` was passed without a creator. This PR uses `creator` if it's there.
Also, `--manager` should be a required flag for `goal asset config`, so I changed that.

Make `goal asset config` work without creator, make `--manager` required

---

.travis.yml

We were building too many releases, need to make sure we only build tagged commits.

Only build/deploy a release when the commit is tagged.

---

test/e2e-go/cli/goal/expect/goalExpectCommon.exp

In `goalExpectCommon.exp`,  `AccountTransfer` will return a wrong transaction ID since the regex didn't capture the current output that `goal clerk send` emits.
Currently, `goal clerk send` output something like:
```
Sent 300000 MicroAlgos from account IFQPDFV6QDMXVU3RQDJI2BEE5IWDBA47YEMYAQQJ3624MB5AQJE3KVD66A to address OXKZL5ZWMQJJWQG57WWSBKKMQHDNQC6MNO3J54SF2B4LZ3VTUMFDKYJXQI, transaction ID: 4GU2OOBWWH4KNYL6H6D3GZD7QLYXZIMGE564JPT2QRHZKDA2AIUQ. Fee set to 1000
```
This PR fixes the regex.
Tested locally.

Fix transaction id capture in goalExpectCommon

---

data/transactions/logic/eval.go
data/transactions/logic/eval_test.go

logic.Check() stack type checking breaks with branching
so don't do type checking in logic.Check()
leave types for when we have actual values in Eval()

logic.Check() without type checking

---

data/transactions/asset.go
ledger/accountdb.go

I introduced a bug in #403 that makes it impossible to close an asset holding if the overall asset has been deleted. If an asset has been deleted, looking up its creator will fail. This is bad because now there is an unrecoverable minbalance, since the holding/account can never be closed.
This also uncovered a higher level issue: we want to allow people to close out assets to the creator, even if their asset holding is frozen. What does this mean for an asset that has been deleted, since that asset no longer has a creator? To resolve this, this PR assumes that it is OK to close out an asset holding if the amount is zero. I am sending an email to discuss this (also b/c it is protocol incompatible with current betanet).
I manually tested that this change allows closing out a zero asset …

Allow closing deleted assets

---

cmd/goal/asset.go

We should have a `-w` flag in `goal asset` to allow user to perform asset operations using non-default wallet.
will be covered in incoming e2e test of limit order.

Add wallet flag to goal asset

---

tools/teal/templates/limit-order.teal.tmpl

`global GroupIndex` is illegal now. Thus, limit order template would not compile. This PR fixes this problem.
will be end to end tested in the incoming limit order end to end test PR.

Fix limit-order template

---

test/e2e-go/features/transactions/lease_test.go

Add tests for two identical leases from the same sender (one should fail), and two identical leases from different senders (both should succeed)

Add lease e2e tests

---

test/e2e-go/features/transactions/lease_test.go

This PR tests two transactions with leases that overlap, ensuring that the one with the longer lease validity period isn't valid until after the first lease validity period ends.

Test overlapping leases

---

cmd/goal/asset.go
daemon/algod/api/server/v1/handlers/handlers.go
daemon/algod/api/spec/v1/model.go

This PR adds a new field to `v1.Transaction` called `TransactionResults`. This field is a struct containing `CreatedAssetIndex`, the index (if any) of an asset created by this transaction.
It computes the created asset index by looking up the block associated with the transaction if it was confirmed (and the correct type of transaction), computing the offset within that block, and adjusting based on `TxnCounter`.
Currently we're just returning this on a best-effort basis. If we don't have access to the block, we can't compute the created asset index based on just the transaction id.

Add created asset index to txn status

---

data/transactions/asset.go

The error message from this check is not helpful for the user.
HTTP 400 Bad Request: TransactionPool.Remember: transaction E7LZYUTGLAK6X3EK3PQ67UJLFWE7J7OXONXFQRBJSBGUD6MGIYPQ: transaction issued by 6OXBYHNBS2THHV7T7OGYYZ5SMOSLKYZC2XG2FMPHRJN633TQ4R3A7VTCMQ, manager key PKOMDVM7SPAX76O5SUSZAITBOH2NNFPPCRINSYUTPE3PW7DXJ44WJHJPWY
changing to:
HTTP 400 Bad Request: TransactionPool.Remember: transaction JQ4AVISTZQIBKGDFEIHPOJM55AGEVFS6XVENGOUL6YLK3LFQTLPQ: this transaction should be issued by the manager. It is issued by GRR4TBQF27XTTYKLYVO64MQHCMAT2FEQTCZI6RSJXNBPM5N3QD27UFYPDM, manager key 74KUZ4DS237IPOF4ZUCUU5TGCP4PKP3NXD64HEVKCXC5TMHOBIURJQUTDQ

Improve error message: sender should be the manager

---

data/pools/transactionPool.go
data/pools/transactionPool_test.go
ledger/acctupdates.go
ledger/acctupdates_test.go
ledger/archival_test.go
ledger/bulletin.go
ledger/cow.go
ledger/eval.go
ledger/ledger.go
ledger/metrics.go
ledger/notifier.go
ledger/time.go
ledger/tracker.go
ledger/txtail.go
node/node.go
node/topAccountListener.go

When OnNewBlock is called, we already know which transactions have been removed.
This PR attempted to avoid calling the "remember" function on these.
High level changes:
* On the notifier, store both the block and delta state objects.
* When sending OnNewBlock, send both block as well as the delta state
* Take advantage of the added information in the txpool's onnewblock->recomputeEvaluator by excluding transactions the we know we don't need.

Avoid revalidating confirmed transaction during block evaluator recomputation

---

config/local_defaults.go
data/pools/transactionPool.go
installer/config.json.example
test/testdata/configs/config-v4.json

Limit the size of the pending transaction groups on the transaction pool.
We've removed this limit during the evaluator integration, which could lead to slower worst-case scenario. Setting this number to 15K seems to cap the worst case scenario we've been seeing.
Setting this cap to 15K and running pingpong at full blast using regular payset transactions resulted in full blocks and block rate of 4.85

Limit the size of the pending transaction groups on the transaction pool

---

test/e2e-go/features/transactions/lease_test.go

The new lease test is flaky. I removed a check that is inherently racy with block confirmation, and increased the window for another check to reduce its flakiness.

Reduce lease test flakiness

---

test/e2e-go/features/transactions/asset_test.go

Test explicit error strings during asset testing

---

shared/pingpong/pingpong.go

Pingpong was constructing a transaction that would last 1000 rounds.
While these transaction are completely legit, they do not help us to measure the network ability to process transactions. Instead, these typically getting "stuck" in one of the intermediate transaction pools for a long time, and degrading the node's performance.
Dropping the LastValid from +1000 to +5 should help the nodes clear up their local transaction pool within 5 rounds, allowing faster iteration between testing periods.

Adjust LastValid of the pingpong transaction

---

data/pools/transactionPool.go
ledger/archival_test.go
ledger/cow.go
ledger/cow_test.go
ledger/eval.go
ledger/ledger.go
ledger/txtail.go

This is an alternative to #504.

Use a transaction's LastValid to expedite duplicate detection.

---

test/scripts/e2e_teal.sh
test/scripts/limit-swap-test.sh
test/scripts/periodic-teal-test.sh
test/scripts/teal-split-test.sh

teal testing was failing on arm64; had nothing to do with arm64. The GOPATH had to be configured.

Fix failed teal test on arm64

---

tools/teal/templates/atomic-swap.teal.tmpl
tools/teal/templates/delegate-key-registration.teal.tmpl
tools/teal/templates/limit-order.teal.tmpl
tools/teal/templates/periodic-payment-escrow.teal.tmpl
tools/teal/templates/split.teal.tmpl

I want to avoid the situation where someone sets `TMPL_FEE` equal to `MinFee` and the contract becomes unusable (because any transaction satisfying the program is necessarily invalid)

Make template fee check <= instead of <

---

ledger/acctupdates.go

I noticed that we were iterating over some unnecessary keys in `listAssets` (and incorrectly marking extra assets as deleted), so I cleaned it up

Clean up logic in listAssets

---

data/txHandler.go
ledger/ledger.go

As of the transaction pool refactor, transactionPool.Test already performs
duplicate detection and transaction liveness checks.

Remove redundant liveness and duplicate checks in txHandler.

---

data/pools/transactionPool.go
ledger/eval.go

This change reduces the minimum number of calls to pool.pendingBlockEvaluator
from 2 to 1 by skipping an extra call to TestTransactionGroup when trying to
remember a new transaction.
TransactionPool's Test() is updated to perform basic well-formedness and
duplicate detection checks but not to perform other stateful checks.

Fix checks preceding cryptographic verification in txHandler.

---

cmd/pingpong/runCmd.go

Add random lease to the ping pong command line. Previous change already added the core functionality to the pingpong execution engine.
When running the pingpong using algonet, we use the command line to drive the configuration.

Add random lease to the ping pong command line

---

test/e2e-go/cli/goal/expect/goalExpectCommon.exp

The expect was using the `w+` to parse the genesis hash. That won't work correctly since the hash is a base64 encoded string, which might include `/`.

expect test : fix incorrect genesis hash parser

---

config/local_defaults.go
installer/config.json.example
test/testdata/configs/config-v5.json

Recent catchup test shown that we're hitting the rate limit too early.
Reducing the number of parallel catchup blocks seems to be an effective way to work around that.

Update CatchupParallelBlocks to reduce the server load

---

cmd/goal/account.go
test/e2e-go/cli/goal/expect/goalCmdFlagsTest.exp
test/e2e-go/cli/goal/expect/goalTxValidityTest.exp

Make `--address` param required for  `goal account marknonparticipating command`
Now we have goalCmdFlagsTesx.exp suite for goal command line flags tests

Enforce required param  goal account marknonparticipating command

---

data/bookkeeping/block.go
data/pools/transactionPool.go

The transaction pool currently panics when an unknown protocol upgrade occurs. We would prefer for the node to simply stall in this case (apparently we want to continue to be able to hit its HTTP API?)
The panic was occurring in `bookkeeping.MakeBlock`. I factored out the upgrade processing logic from `MakeBlock` to return errors instead. `MakeBlock` will still panic, but now we can check if we know about the next consensus version in the transaction pool before calling it.
Please be on the lookout for places where `pendingBlockEvaluator == nil` could cause a panic.

Don't panic in txpool on unknown protocol upgrade

---

cmd/goal/clerk.go
data/transactions/logic/README.md
data/transactions/logic/README_in.md
data/transactions/logic/TEAL_opcodes.md
data/transactions/logic/assembler.go
data/transactions/logic/doc.go
data/transactions/logic/eval.go
data/transactions/logic/eval_test.go
ledger/eval.go
protocol/consensus.go

The ledger currently guarantees storage of the last 1000 blocks.  Reads on
blocks with rounds older than this on non-archival nodes will intermittently
fail, which may potentially cause the consensus protocol to stall (by
introducing subjectivity into block evaluation).
As a temporary fix, this commit disables the FirstValidTime txn field within
LogicSig programs.

Deprecate the FirstValidTime txn field inside LogicSig programs.

---

catchup/service.go
logging/telemetry.go
logging/telemetryCommon.go
logging/telemetryConfig.go
logging/telemetryConfig_test.go
logging/telemetryFilteredHook.go
logging/telemetry_test.go
logging/telemetryhook_test.go
tools/network/bootstrap.go
tools/network/telemetryURIUpdateService.go

This event has generally caused more harm than good. Disable it for now.

Telemetry Tweaks

---

daemon/kmd/kmd.go
daemon/kmd/wallet/driver/driver.go
daemon/kmd/wallet/driver/ledger.go
daemon/kmd/wallet/driver/ledger_hid.go
daemon/kmd/wallet/driver/sqlite.go

Ledgers have lots of different product IDs. This PR enumerates all devices that appear to be manufactured by ledger.
This PR also only makes it a warning when a device fails to open. Before, when that would happen, all of kmd would crash since the wallet driver initialization would return an error. Instead, we just log an error to the log file now.
This PR does _not_ fix the issue where a ledger shows up twice. I thought about trying to fix that by checking `info.Interface` from https://godoc.org/github.com/karalabe/hid#DeviceInfo and deduping on that, but the docs indicate that `Interface` has platform specific behavior that I can't test easily.

Enumerate all ledgers

---

logging/telemetryConfig.go
logging/telemetryConfig_test.go

Node runners are using hostnames to identify their machines, so we need to increase the size allowed by the SanitizeString method.
The unit test has been updated.

Increase size of StringSanitizer limits. Closes #579

---

data/transactions/logic/assembler.go
data/transactions/logic/assembler_test.go

for issue #604 
add test, fix dissassemble

fix Disassemble when multiple bnz have the same target label

---

docker/releases/Dockerfile-stable
docker/releases/Dockerfile-stable-testnet

Replace `apt` with `apt-get` in order to get rid of build warning message.

Eliminate docker image warning

---

config/config.go
config/local_defaults.go
installer/config.json.example
logging/telemetryspec/event.go
network/wsNetwork.go
test/testdata/configs/config-v5.json

Periodically, send a list of connected peers to the telemetry server.
That would allow us to construct a graph containing all the interconnections across our relays.
```
{
"_index": "tsachi1-tsachi1-v1",
"_type": "log",
"_id": "KwWx2m4BEU4xLqujn8Y5",
"_version": 1,
"_score": null,
"_source": {
"Host": "719db986-1341-4c14-83a6-45f586916183:R7",
"@timestamp": "2019-12-06T10:11:43.112896193Z",
"Message": "/Network/PeerConnections",
"Data": {
"details": {
"IncomingPeers": [
{
"Address": "3.14.141.255",
"HostName": "58322329-eed2-474b-82ad-f0e1376d1c4a:N14",
"InstanceName": "SoOB6Cu7vdU1c/bB",
"ConnectionDuration": 18236
},
{
"Address": "3.14.141.255",
"HostName": "58322329-eed2-474b-82ad-f0e1376d1c4a:N14",
"InstanceName": "zIdiErWwnik+Wbba",
"ConnectionDuration": 18236
},
{
"Address": …
```

Add PeerConnections to network telemetry

---

cmd/catchupsrv/download_test.go
cmd/pingpong/teal_programs.go
scripts/travis/before_build.sh
test/e2e-go/features/auction/auctionCancel_test.go
tools/network/bootstrap.go
tools/network/telemetryURIUpdateService.go
util/metrics/registry_test.go
util/metrics/stringGauge.go
util/metrics/stringGaugeCommon.go
util/metrics/stringGauge_test.go

We forgot to enable this in travis

Fix license errors, enable check_license in travis.

---

daemon/algod/api/server/v1/handlers/errors.go
daemon/algod/api/server/v1/handlers/handlers.go
rpcs/httpFetcher.go
rpcs/ledgerService.go

To endpoint `/v1/block/{N}` add `?raw=1` to return msgpack bytes with full data.
Uses the same payload preparation as catchup block fetching code.
TODO: maybe should add an end-to-end test to fetch a block from both catchup endpoint and local API endpoint and check that they're the same bytes.

Make raw block msgpack bytes available to local API

---

.travis.yml
scripts/test_release.sh
scripts/travis/test_release.sh
test/packages/install.sh
test/packages/test_release.sh

For each supported OS, this script will download the installer and install algorand in a Docker image.  It will then run `algod -v` for a sanity test.  Any image that fails will be listed to `stdout` and a return value of 1 will be returned.
The supported OS are:
centos:7
centos:8
fedora:28
ubuntu:16.04
ubuntu:18.04
This also passes the `shellcheck` linter.

Created `test_release.sh` to test centos|fedora|ubuntu images

---

test/scripts/e2e_subs/dynamic-fee-teal-test.sh
test/scripts/e2e_subs/e2e_teal.sh
test/scripts/e2e_subs/htlc-teal-test.sh
test/scripts/e2e_subs/keyreg-teal-test.sh
test/scripts/e2e_subs/limit-swap-test.sh
test/scripts/e2e_subs/periodic-teal-test.sh
test/scripts/e2e_subs/teal-split-test.sh

The TEAL e2e tests were not exporting the SHELLOPTS.
An error generated by a subshell would be not respecting the specified shell options.
This would, naturally, fix nothing other than early exit from a failing test.

Add `export SHELLOPTS` to teal tests.

---

Makefile
docker/build/Dockerfile
docker/build/Dockerfile-deploy
scripts/centos-build.Dockerfile
scripts/check_deps.sh
scripts/configure_dev-deps.sh
scripts/configure_dev.sh

Only check for the presence of the dependencies.  If one or more are missing, exit 1 and echo the install script (`./scripts/configure-dev.sh`).
https://www.shellcheck.net/
https://github.com/koalaman/shellcheck

Bring `shellcheck` into the build process

---

scripts/check_license.sh

This was failing on macOS because the output of the `wc` command was being prepended with whitespace.  Piping it then to `cut` was returning an empty string.
https://stackoverflow.com/questions/30927590/wc-on-osx-return-includes-spaces

Fix issue on macOS to make script portable

---

gen/generate.go

During our build process we were generation a very long log entries of the form:
```
Created new rootkey: gen/testnet/Wallet1.rootkey
1301Created new partkey: gen/testnet/Wallet1.0.3000000.partkey
1302Created new rootkey: gen/testnet/Wallet10.rootkey
1303Created new partkey: gen/testnet/Wallet10.0.3000000.partkey
1304Created new rootkey: gen/testnet/Wallet11.rootkey
...
```
Instead, we could reduce the verbosity and just summarize it into:
```
Created 144 new rootkeys and 44 new partkeys.
```

Reduce "Created new rootkey/partkey" verbosity

---

cmd/goal/account.go

default value should be set before if statement, not after

Fix asset unit name display in goal account list

---

test/packages/test_release.sh

- Removed a redundant `exit` statement.
- Added script name to error statement.

Minor improvements to `test_release.sh` script

---

ledger/acctupdates.go
ledger/acctupdates_test.go
ledger/archival_test.go
ledger/blockdb.go
ledger/blockdb_test.go
ledger/blockqueue.go
ledger/eval.go
ledger/ledger.go
ledger/tracker.go

Simplify ledger data storage by removing 'evalAux' field which hasn't been used since before 1.0

Cleanup evalAux

---

cmd/goal/messages.go
cmd/goal/multisig.go

This PR adds a new flag, `--no-sig` to `goal clerk multisig sign` that will fill in an `Msig` for a particular multisig preimage on a transaction, but won't actually do any signing. This is necessary if all of the keys in the multisig are ledger hardware wallets (since ledgers don't store multisig preimages).

Add --no-sig flag to goal clerk multisig sign

---

network/wsNetwork.go
tools/network/bootstrap.go
tools/network/telemetryURIUpdateService.go
tools/network/telemetryURIUpdateService_test.go

This PR add support for https telemetry servers by adding a tls entry on the SRV records for such. It also addresses the first step of migrating from SRV records that contains the schema in their host name.
Test is provided. Actual test using SRV record will be conducted manually.

Add support for https for telemetry servers

---

cmd/goal/account.go
test/e2e-go/cli/goal/expect/goalExpectCommon.exp
test/e2e-go/cli/goal/expect/listExpiredParticipationKeyTest.exp

This fixes a crash where `goal` attempts to dereference a `nil` `Participation` when attempting to display an expired participation key using `listpartkeys`. 
This adds a test `.exp` for this case.

goal listpartkeys display error

---

scripts/travis/configure_dev.sh
scripts/travis/integration_test.sh

1) python3-venv libffi-dev libssl-dev
libffi-dev (and libssl-dev) are needed by the cryptography package builder for python in e2e_basic_start_stop.
2) exporting GOPATHBIN needed to run algotmpl in template e2e tests.
Run in travis

Fixing arm64 environment issues

---

scripts/travis/after_build.sh
test/platform/test_linux_amd64_compatibility.sh

Our generated binaries are expected to work on a variety of platforms. Before doing any packaging for these, we need to perform some sanity checking to see that the binary is capable of running on these platforms.
This is where this PR comes in. It generate series of temporary docker images ( one for each platform ), and attempt to run goal and algod. If the process is capable of loading into memory and executing, it will pass the test.

Test pre-packaged executable on variety of linux platforms

---

config/config.go
test/e2e-go/features/participation/participationRewards_test.go
test/scripts/e2e_client_runner.py
test/scripts/run_integration_tests.sh

There are seven major contributors to integration tests running time
TestOnlineOfflineRewards (1248.64s)
TestAssetConfig (364.71s)
TestRewardRateRecalculation (226.78s)
TestStartAndEndAuctionTenUsersOneBidEach (196.34s)
TestNoDepositAssociatedWithBid (189.74s)
TestDeadbeatBid (188.70s)
TestStartAndCancelAuctionNoBids (183.35s)
This commit considers only first three.
1. Fixing rewards interval in config for TestRewardRateRecalculation
from 25 to 10 reduces time twice:
TestRewardRateRecalculation (119.34s)
2. Fixing initialRound in TestOnlineOfflineRewards test
from 301 to 11 reduces time 15 times:
TestOnlineOfflineRewards (73.80s)
3. TestAssetConfig looks long by design - commits and waits max allowed assets
4. Address TODO in run_integration_tests.sh.
Now e2e_client_runner calls 'goal …

Reduce e2e_go_tests execution time twice

---

.travis.yml

Running deploy_test stage is currently done only after deploy stage is completed.
This typically takes two hours, as the ARM build slowing things down.
During that time, Jenkins might have already moved some of the tarballs to the passed directory.
( which would cause the test_release.sh script to fail. )
To work around that, we want to run the scripts immediately after uploading the tarballs to the s3.

Promote test_release.sh so that it won't conflict with release testing

---

libgoal/lockedFile.go
libgoal/walletHandles.go

* In rare cases (i.e. e2e tests run in parallel on the same network)
a race cond happens when accessing goal.cache/walletHandles.json file
* Introduce advisory locking on the mentioned file
* Implementation is extendable by implementing *locker* interface
for specific platform and providing a new *newLockedFile* constructor.
Low impact, rely on existing tests.

Fix concurrent access to wallet handles cache in goal

---

config/config.go
data/bookkeeping/block.go
data/bookkeeping/block_test.go

This replaces UpgradeWaitRounds with MinUpgradeWaitRounds and
MaxUpgradeWaitRounds.  Proposers specify an upgrade's delay given
their own ApprovedUpgrades, encoding the proposed delay in
the UpgradeVote.  Verifiers check that the delay sits between
MinUpgradeWaitRounds and MaxUpgradeWaitRounds (inclusive).

Allow upgrades to specify the delay before their execution.

---

test/e2e-go/cli/goal/expect/goalExpectCommon.exp
test/e2e-go/cli/goal/expect/limitOrderTest.exp

* Should help with sporadic failures when we send and TEAL in groups
* Also fix some typos and whitespaces

Set explicit 30 sec timeout for AlgorandGoal::RawSend in expect test

---

config/config.go
data/bookkeeping/block_test.go

Also add some unit tests for variable-delay protocol upgrades.

Support variable-delay protocol upgrades in ConsensusFuture.

---

logging/log.go
logging/telemetryhook.go
tools/network/bootstrap.go
tools/network/telemetryURIUpdateService.go

We had no logging for a failed connection to the telemetry server(s). As a result, a failed telemetry connection would go silently, and no one would get notified of the issue.
This change add a warning level log entry in case we were unable to create a network connection to the telemetry server.
From a high-level perspective, the `UpdateHookURI` function now returns an error object instead of a bool. That allows the upstream caller to log the error ( if any ) to the log file via the logger.

Add logging for the telemetry server connections

---

test/e2e-go/cli/goal/expect/goalCmdFlagsTest.exp
test/e2e-go/cli/goal/expect/goal_expect_test.go

* CombinedOutput blocks on copying empty stderr stream from expect that
causes at least 60 sec timeout for most of the tests
* This implementation uses a temp time for stderr accumulation.
In this case exec.Cmd does not run goroutines for reading child's actual stderr.
* 655 sec (before) vs 205 sec (after)

Reduce execution time of expect tests

---

scripts/configure_dev.sh
scripts/travis/configure_dev.sh

Boost version has changed, causing a new python3 to be installed. While there is nothing wrong here, the python3 symbolic link was not pointing to the newly installed due to some cask installation issue.
This change pin the boost version to the one we used to have, so that we can take and figure this issue offline.

Avoid upgrading boost on travis Mac builds

---

cmd/algod/main.go

* This should prevent telemetry event loses on systems with
invalid permissions on ~/.algorand/logging.config file
* Another possible workaround is to relax default config path mask in
**cmd/goal/commands.go:ensureCacheDir** from 700 to 744.
This is not implemented because of possible security risk.

Fail on algod startup if logging.config file has bad permissions

---

cmd/goal/commands.go

Needed to debug 'Couldn't read password: inappropriate ioctl for device' error message in tests

Add error logging for getting a cached wallet handle

---

daemon/algod/api/server/lib/common.go
daemon/algod/api/server/router.go
daemon/algod/api/server/v1/handlers/errors.go
daemon/algod/api/server/v1/handlers/handlers.go
daemon/algod/server.go

Existing code would deadlocked during shutdown if the node was waiting for a round, as we're shutting the agreement service before closing the http handler.
This change is doing the following:
1. unifying the algod Stop functionality, so that there is no "race" condition there.
2. Passing the algod shutting-down signal down to the handler context, so that we can quickly abort pending operations.
typical travis failure example:
```algod(95113) : goroutine 1 [running]:
2552algod(95113) : github.com/algorand/go-algorand/daemon/algod.setupDeadlockLogger.func1()
2553algod(95113) : 	/Users/travis/gopath/src/github.com/algorand/go-algorand/daemon/algod/deadlockLogger.go:51 +0x162
2554algod(95113) : github.com/algorand/go-deadlock.lock(0xc0006081a0, 0x5534ac0, 0xc0002301e8, 0xc000122500) …
```

Make gracefull exit of a node that is waiting for WaitForBlock call

---

docker/releases/build_releases.sh
scripts/check_deps.sh
scripts/check_license.sh
test/packages/test_release.sh
test/platform/test_linux_amd64_compatibility.sh

We were using the `tput` command to generate colors on terminal output. however, when there is no terminal attached, the `tput` command doesn't know how to format these coloring sequences.
This PR drops the error strings generated by `tput` as they have no value for us. When terminal is available, it would use the correct output. when it's not available, it will get silently ignored.

Remove tput where not supported by terminal

---

daemon/algod/api/server/v1/handlers/errors.go
daemon/algod/api/server/v1/handlers/handlers.go

Currently, in WaitForBlock, we completely ignoring the protocol upgrade. The requested round might never reach, as the node might not be able to support it.

Avoid waiting for block that won't be reached due to unsupported protocol upgrade

---

test/scripts/e2e_subs/dynamic-fee-teal-test.sh
test/scripts/e2e_subs/e2e_teal.sh
test/scripts/e2e_subs/htlc-teal-test.sh
test/scripts/e2e_subs/keyreg-teal-test.sh
test/scripts/e2e_subs/limit-swap-test.sh
test/scripts/e2e_subs/periodic-teal-test.sh
test/scripts/e2e_subs/teal-split-test.sh

Undo teeing to /dev/tty as it doesn't work well in terminal free environments

Rollback teeing to terminal during teal test piping

---

.travis.yml

So far, we've had the ARM64 build optional.
Now that we've fixed (most) of the building issues around it, It's time to make it mandatory to make sure we don't break it by accident.

Make ARM64 build mandatory

---

test/e2e-go/cli/goal/expect/goalExpectCommon.exp

Some of our expect testing are failing, with what seems to be a timeout.
I suspect that the network creation wasn't detected correctly, so I'll try to relax the regex:
```goal_expect_test.go:154: err running 'ledgerTest.exp': exit status 1
1858            stdout: TEST_ALGO_DIR: /Users/travis/gopath/src/github.com/algorand/go-algorand/tmp/out/e2e/592190654/ledgerTest/algod
1859            TEST_DATA_DIR: /Users/travis/gopath/src/github.com/algorand/go-algorand/test/testdata
1860            network create test_net_expect_1578424681
1861            spawn goal network create --network test_net_expect_1578424681 --template /Users/travis/gopath/src/github.com/algorand/go-algorand/test/testdata/nettemplates/TwoNodes50Each.json --datadir /Users/travis/gopath/src/github.com/algorand/go-algorand/tmp/ …
```

relax StartNetwork regex

---

rpcs/fetcher_test.go
rpcs/ledgerService_test.go

Existing implementation of fetcher unit tests is too time-sensitive. It might work correctly on a fast machine, but could fail on another.
Relax the testing condition that are time-related.

More reliable fetcher unit tests

---

cmd/algod/main.go
cmd/algoh/main.go
logging/log.go

recent logging changes missed this

Avoid starting the Telemetry service when logging is disabled

---

test/framework/fixtures/libgoalFixture.go

When running our e2e test, the kmd process is being created with a TTL of 60 seconds. That's pretty reasonable. Unfortunately, we never ended up killing it when the test is over.
This lead to condition where we could have many copies of kmd in memory, where some conflicts around the lock file.
Given that it's not the scope of any of the non-kmd tests, I've added the killing of the KMD to the node fixture shutdown.

Shutdown kmd when test fixture is going down

---

rpcs/fetcher_test.go

Unit test was not measuring the time correctly.

Fix failing unit test TestFetchBlockTimeout

---

Makefile

Our build system is using Centos to compile the release binaries. 
Unfortunately, the static linking doesn't work there out of the box.
This change "undo" the static linking on the centos platform, which doesn't have the same cross-platform issue we've had when compiling using Ubuntu 18.04.

Update the makefile to skip the static linking when compiling on centos

---

agreement/actions.go
agreement/actor.go
agreement/agreementtest/simulate.go
agreement/fuzzer/fuzzer_test.go
agreement/gossip/network.go
agreement/gossip/networkFull_test.go
agreement/gossip/network_test.go
node/node.go

When I've been measuring votes processing performance I found usages of default `logging.Base()` near standard / preconfigured logger in some components of agreement service. This PR fixes it.

Minor: Use service-wide logger instead of logging.Base() in agreement

---

scripts/travis/run_tests.sh
test/e2e-go/features/auction/auctionErrors_test.go
test/e2e-go/features/auction/basicAuction_test.go
test/e2e-go/features/participation/participationRewards_test.go
test/e2e-go/features/transactions/sendReceive_test.go
test/scripts/e2e_go_tests.sh

Some of our e2e tests are taking a long time to execute. In favor of more rapid testing, I'm marking these are slow, so that it won't get executed on PR integration tests.
```
--- PASS: TestStartAndEndAuctionOneUserTenBids (201.27s)
--- PASS: TestStartAndPartitionAuctionTenUsersTenBidsEach (236.01s)
--- PASS: TestPartkeyOnlyRewards (1433.68s)
--- PASS: TestAccountsCanSendMoney (1106.63s)
```

Mark some of the slow e2e tests as such

---

scripts/travis/run_tests.sh
test/e2e-go/features/auction/auctionCancel_test.go
test/e2e-go/features/auction/auctionErrors_test.go
test/e2e-go/features/auction/basicAuction_test.go
test/e2e-go/features/transactions/asset_test.go

Move some more test to be "slow tests", and modify short test condition so that we will run
the long tests on nightly builds only.

Move slow test to get executed on nightly builds

---

test/e2e-go/upgrades/send_receive_upgrade_test.go

Modify the upgrade tests to run faster : 
adjust the small lambda to wait less for the upgrade rounds as well as avoid looping for 20 second, and use 2 rounds instead.

Faster upgrade e2e tests

---

test/e2e-go/features/participation/onlineOfflineParticipation_test.go

The TestNewAccountCanGoOnlineAndParticipate e2e test is failing, and causing our nightly build to fail. We need to take this offline so we can investigate and fix it separately.

Disable failing e2e test

---

cmd/algokey/main.go

Add generate-docs option to algokey, we need it for generating documentation markdown files.
It works, I tried it!

Generate docs for algokey.

---

cmd/algons/dnsCmd.go
tools/network/cloudflare/cloudflare.go

Cloudflare seems to have some issue related to setting the ttl values. Regretfully, our algons tool doesn't provide feedback about what message was sent to the server, only that the cloudflare server has returned an error.
This change extend the textual error message to include the request body that was sent to the server, so that we can figure out if the request was valid or not.

Improve algons error logging

---

agreement/proposalTracker.go
agreement/proposalTracker_test.go
config/config.go
data/committee/credential.go
protocol/consensus.go

The bug causes larger accounts to be block proposers more often than should happen based on their fraction of online stake. This patch will cause nodes to vote for a protocol upgrade that fixes the buggy behavior. After the protocol upgrade goes through, all the upgrade-related code in this commit should be removed, as it's not necessary to retain the old buggy behavior for catchup. (For convenience code to be removed is marked with a "TODO(upgrade)" comment.)

Fix a bug in Credential.lowestOutput caused by improper domain separation

---

test/scripts/e2e.sh
test/scripts/goal_subcommand_sanity.sh

ensures no conflicting subcommand options
adds less than 2 seconds to test time
tested by adding a bogus subcommand option to goal and watching test fail, then backing that out

test all `goal ... -h`

---

catchup/pref_test.go
catchup/service.go
catchup/service_test.go
node/impls.go
node/node.go
test/e2e-go/features/catchup/basicCatchup_test.go

Move EnsureDigest logic into the catchup service. That makes the fetcher logic being used by a single source ( i.e. catchup ) rather than shared between the node and catchup, and would allow us to unify the logic there.
This PR is intended to be the first in a series, which handles only the portion of "moving the ensure digest logic from node into the catchup service".
Follow up for this PR would be "move fetcher logic from rpcs into catchup" and "move fetcher service into catchup"

Move EnsureDigest logic into the catchup service

---

data/basics/address.go
data/basics/address_test.go

Just make it faster. Nothing exciting going here.
Address.String():  550 ns / op -> 350 ns / op
UnmarshalChecksumAddress():  1116 ns / op -> 1001 ns / op

Faster stringer implementation for Address

---

netdeploy/network.go

This PR was opened as a result of a result of a random e2e test failure.
The TestPartitionHalfOffline test was trying to create a TenNodesDistributedMultiWallet network, and failing to reach the first round.
When looking into the issue, it seems that both relays have substantial amount of stake, which was an indication of a message propagation issue. Looking further, it seems that we're linking the node and the relays correctly, however, failing to interconnect the relays along themselves.
This PR is expected to fix this randomly failing test, along with any other goal driven private local network deployment.

Interconnect relays on a locally deployed network

---

agreement/player_test.go

The agreement player tests now use the old buggy lowestOutput behavior when and only when ConsensusCurrentVersion says to.
This allows agreement tests to pass whether ConsensusCurrentVersion is the old V20 or the new V21

Change a player test to check ConsensusCurrentVersion

---

THANKS.md
agreement/coservice.go
agreement/proposalStore.go
agreement/proposalStore_test.go
agreement/service_test.go

When retrieving the last relevant period corresponding to a proposal-value, the
proposal store inside the agreement protocol does not properly check that the
particular period returned actually matches the passed-in proposal-value.
Instead, the proposal store returns the last period seen for *any*
proposal-value.
When the agreement state machine receives a proposal payload, the proposal store
checks whether this payload matches any proposal-value known to be relevant in
the current round.  If it does, the state machine tells the crypto verifier to
verify the new payload.
As an optimization, the proposal store in the state machine also tags the
payload with the last period in which it is relevant (and whether the matching
proposal-value is pinned).  The crypto verifier halts concurrent …

Bugfix: Fix last relevant proposal period in agreement protocol.

---

agreement/actions.go
agreement/agreementtest/simulate.go
agreement/agreementtest/simulate_test.go
agreement/common_test.go
agreement/demux.go
agreement/fuzzer/ledger_test.go
agreement/fuzzer/tests_test.go
agreement/fuzzer/validator_test.go
agreement/fuzzer/voteFilter_test.go
agreement/proposal.go
agreement/proposalManager.go
agreement/proposalStore_test.go
agreement/proposalTracker.go
agreement/proposal_test.go
agreement/pseudonode.go
agreement/selector.go
agreement/vote.go
agreement/voteAggregator.go
agreement/voteTracker.go
agreement/voteTrackerContract.go

Existing code was using `%v` to format numeric values. While that `%v` is a completely valid parameter, it could result in a recursive looping when a `fmt.Stringer` interface is being implemented on the argument.
Using `%d` eliminate this potential issue.

Format numbers using number specifier

---

ledger/eval.go
util/execpool/backlog.go

This seemed to be needed at the time, but now seems to be causing a major slowdown and removing it doesn't break any tests.

back out locking added in c78ada09f230a3c66cd934860700f93ff31a93eb

---

logging/log.go
logging/telemetry.go
logging/telemetryCommon.go
logging/telemetryhook.go

* The idea is have telemetry.hook always set.
For telemetry disabled case this is a simple noop stub.
* Prevents crashes when calling hook.Close/Flush on private networks in case of errors
Testing: manual

Implement dummy telemetry hook to safely perform operations on it

---

scripts/build/beta.sh
scripts/build/nightly.sh
scripts/build/stable.sh

We don't want to be making tags anywhere in our automation. Our release process will take care of that. There is another script that makes tags in release/ci/tag.sh, but that doesn't seem to be being used anywhere.
I will run a nightly build later today against this branch and see if any tags are made

Remove instances of tagging in our build process

---

scripts/build_package.sh

When locally installing, take the binaries from the first-gopath-bin directory.

Support `make install` for installations with GOPATH that contains multiple directories

---

config/config.go

In 0366cdaea7491a57c11021a89b0862dbd169f9d7, we added a new function PreloadConfigurableConsensusProtocols, which was expected to return the consensus protocols. The function was not doing so in the case where the consensus.json file was missing, and was returning an empty structure. This wasn't affecting the unit testing, as they do not rely on this function on its own. However, libgoal needs that in order to correctly sign transactions.
Test this change with libgoal applications, such as pingpong.

Fix regression started in 0366cdaea

---

cmd/goal/messages.go
cmd/goal/node.go
installer/system.json
libgoal/system.go
test/e2e-go/cli/goal/expect/goalExpectCommon.exp
test/e2e-go/cli/goal/expect/goalNodeSystemdTest.exp
test/e2e-go/cli/goal/expect/goalNodeTest.exp
test/testdata/configs/system-v0.json

I added a property to libgoal/system.go where we can set whether or not our algod process is managed by systemd. This adds the feature, but without automation for ensuring that the field is set to true on all systemd installs
I ran it locally on OSX and linux and it appeared to work appropriately. Making a PR to ensure all integration tests are ran

Make goal node state change commands systemd aware

---

libgoal/transactions.go

Allow creating assets while catching up by setting the asset parameters to the binary current version if the ledger hasn't caught up to that point yet.
A strange error due to the consensus parameters not yet being initialized:
```
Cannot construct transaction: asset url my.token.url is too long (max 0 bytes)
```
Made sure the command works
```
goal asset create --creator <address> --decimals 6 --asseturl "my.token.url" --unitname coin --name "my coin" --total 18446744073709551615 -o transaction.tx
```

Allow asset creation transactions to be created while catching up.

---

tools/network/cloudflare/cloudflare.go

Algons was giving feedback on failed DNS entries creation. However, that feedback was including only the returned message body. Per provider request, I'm extending this to include the entire response headers, so that we could give a concrete feedback.

improve the details of algons error messages

---

network/dialer.go
network/rateLimitingTransport.go
network/wsNetwork.go

Shant's previous implementation wasn't complete as the underlying go implementation for the http requests was re-using the same connection over and over. This implementation extend the previous one by using a http-level accounting for the various outgoing requests.

Create a rate limiting transport

---

data/transactions/logic/assembler.go
data/transactions/logic/assembler_test.go

TEAL program that contains the following string would fail to compile:
```byte base64 //GWRM+yy3BCavBDXO/FYTNZ6o2Jai5edsMCBdDEz+0=```
because the `//` is interpreted incorrectly.
found during automated testing:
```
20200204_015800 :357 starting: ['e2e_subs/dynamic-fee-teal-test.sh', 'e2e_subs/e2e_teal.sh', 'e2e_subs/htlc-teal-test.sh', 'e2e_subs/keyreg-teal-test.sh', 'e2e_subs/limit-swap-test.sh', 'e2e_subs/periodic-teal-test.sh', 'e2e_subs/teal-split-test.sh']
20200204_015825 :100 starting e2e_subs/dynamic-fee-teal-test.sh
20200204_015825 :100 starting e2e_subs/e2e_teal.sh
20200204_015825 :100 starting e2e_subs/periodic-teal-test.sh
20200204_015825 :100 starting e2e_subs/limit-swap-test.sh
20200204_015825 :100 starting e2e_subs/keyreg-teal-test.sh
20200204_015825 :100 starting …
```

bugfix : compile correctly teal program that includes a base64 string which starts with double slash

---

scripts/release/util/check_sig.sh
scripts/release/util/smoke_test.sh
scripts/release/util/test_package.sh

check_sig: Verify gpg signatures of build artifacts.
test_package: Verifies the packages were built from the correct branch
with the correct hash and verifies the test version release number.

Added utils for testing release packages

---

scripts/release/build/Jenkinsfile
scripts/release/build/stage/build/task.sh
scripts/release/build/stage/upload/run.sh
scripts/release/prod/stage/setup/run.sh
scripts/release/test/stage/setup/run.sh

Most importantly, move the `fullversion.dat` file to the $HOME directory
and use it for the name of the upload directory on s3.  It should have
been doing this before, but it was copying it to the wrong location on
the ec2 instance.

Some build fixes

---

cmd/goal/messages.go
cmd/goal/tealsign.go

This PR moves some of the `dsign` functionality into a new goal command, `goal clerk tealsign`.
Currently this command only supports signing using keyfiles as generated by `algokey`. The next thing to do is add support for signing with keys from `kmd`. I left that out of this PR, because I wanted to add a "sign data for logic" endpoint to `kmd` rather than export private keys just to make this work. That will come next.

Move `dsign` functionality to goal

---

docker/releases/build_releases.sh

Removing `ENTRYPOINT` makes the image more flexible.
```
docker run -it algorand/stable
docker run -it algorand/stable /bin/bash
docker run algorand/stable ./algod -v
docker run algorand/stable cat /etc/passwd
```
In addition, the `install` directory was cruft, and I didn't see any reason to remove any repo listings (`/var/lib/apt/lists/*`).

Update Dockerfile for our official docker image

---

config/config.go
config/consensus.go

Move all the consensus related functions/datatypes/instances into its own consensus.go file within the config library.

Split consensus from config

---

daemon/kmd/wallet/driver/ledger.go

On macOS, the names of the ledger wallets were insanely long.
Additionally, ledgers have been enumerating twice -- the second device shows up after the Algorand app is opened.
This PR:
- Normalizes the length of ledger wallet names by replacing the USB `info.Path` with its truncated hash
- Only enumerates devices that respond to the "list public key" command

Actively scan for ledgers, normalize names cross platform

---

scripts/release/build/stage/setup/run.sh
scripts/release/util/check_remote.sh

When using a wildcard (*) character to watch multiple branches when
polling in Jenkins, the GIT_BRANCH environment variable will be
"origin/rel/beta" instead of just "rel/beta".  This breaks our tooling,
but a simple fix is this util which simply strips any matched remote
repo from the env var string value.

Strip any defined remote repo from branch name when building

---

gen/generate.go

In PR 68c29d277194569ae4aee622248e34432f2ccd76 we have added concurrent wallet generation to speed up the generation of wallets.
That was working fine.. Until we start seeing travis failures.
In this PR, I have set the concurrent goroutines count to 1, so that we won't run into these issues.

Disable the concurrent wallet generation

---

scripts/release/build/Jenkinsfile
scripts/release/common/docker/setup.Dockerfile

By default, docker will use the root user, but the jenkins pipeline
docker plugin inexplicitly runs the instance under the permissions of
the user that launched the script that contains the docker command.

Force docker to use `root` as the user when running the instance

---

agreement/service_test.go
util/db/dbutil.go

Provide better handling for incorrect usage of the `Accessor` object.
In particular -  
1. The `func (db Accessor) Close()` function would now become a `func (db *Accessor) Close()`, so that the internal `Handle` variable would be cleared on the operating object.
1. In case of an initialization statement error, set the Handle to nil after closing the database object.

Better error case handling in database utils

---

cmd/updater/update.sh

When installing a node using the update script, one need to bootstrap his system with the updater tool. Currently, we suggest that the user would go to either one of the following:
* https://github.com/algorand/go-algorand-doc/tree/master/downloads/installers/darwin_amd64
* https://github.com/algorand/go-algorand-doc/tree/master/downloads/installers/linux_amd64
* https://github.com/algorand/go-algorand-doc/tree/master/downloads/installers/linux_arm
Extract the tarball, and run the update.sh bash script.
While there is nothing wrong with doing so, we could do a bit better - 
Regardless of what platform we're on, download 
* https://github.com/algorand/go-algorand-doc/tree/master/downloads/installers/update.sh
and run it.
It will automatically detect the current platform and download the …

Standalone update.sh

---

scripts/travis/external_build_printlog.sh

The external_build_printlog.sh script was working correctly, but is a slow pace.
To some degree this is cause by the aws cli. Replacing this with curl improves the speed dramatically.
This is particularly useful when monitoring existing builds, as the script iterate thoughtout large number of files.
The changes were tested manually, and seems to be working correctly.

Faster external_build_printlog by using curl instead of aws cli

---

gen/generate.go
gen/generate_test.go
util/db/dbutil.go

* SQLite init is not thread safe and mattn/go-sqlite3 does not care
* When open any db first time do it synchronously in order to make
a nested sqlite3_initialize() the first call non-concurrently
* Re-enable mutli-threaded account generation
* Closes #846

Fix concurrent SQLite initialization

---

daemon/kmd/wallet/driver/sqlite.go

There is no database URL option called `_tx_lock`, the correct name is `_txlock`. 
Closes #838

Change _tx_lock -> _txlock

---

scripts/release/build/stage/upload/task.sh

Without the `-c` switch, the file redirected into `node_pkg/` was zero bytes.

Redirect stdout of build log file to build release upload directory

---

test/e2e-go/features/transactions/asset_test.go
test/e2e-go/features/transactions/sendReceive_test.go
test/e2e-go/restAPI/restClient_test.go

* Asset tests
* Rest client test
* Send-Receive test (TestAccountsCanSendMoney) - takes 16 minutes
* Closes #805
* Closes #814
* Closes #815

Enable some test on MacOS

---

agreement/gossip/networkFull_test.go
cmd/netdummy/main.go
network/dialer.go
network/phonebook.go
network/phonebook_test.go
network/ping_test.go
network/rateLimitingTransport.go
network/requestLogger_test.go
network/requestTracker_test.go
network/wsNetwork.go
network/wsNetwork_test.go
node/node.go

This PR consolidates all phonebook implementations into a single multi-network phonebook.
No new functionality is added.
The existing tests are updated to reflect the new phonebook implementation.

Refactor are combine the phonebook implementations 

---

test/scripts/e2e_client_runner.py

The error reporting in e2e_client_runner.py writes the address of the stream instead of reading from it. 
This fixes it to report the content of the stream in the message.

Fixing python integration testing error reporting

---

libgoal/lockedFile.go
libgoal/lockedFileLinux.go
libgoal/lockedFileUnix.go
libgoal/walletHandles.go

1. Fix locking file system to support older kernels and WSL. Fixes #852 
2. Remove use of deprecated `syscall` package: https://golang.org/pkg/syscall/
3. Remove use of hardcoded system constants that may depend on the architecture.
Tested using `make test` on Ubuntu 18.04 and macOS. (But not on Ubuntu 18.04 in WSL.)
Tested that `goal account new` and `goal account list` work on Ubuntu 18.04 in WSL.

Support of older kernels for locking files

---

agreement/gossip/networkFull_test.go
cmd/algod/main.go
cmd/netdummy/main.go
daemon/algod/server.go
network/phonebook.go
network/wsNetwork.go
node/node.go
node/node_test.go

The phonebook object is removed from the node. The phonebook is now local to the network. 
The node only passes list of addresses in string type to the network upon creation. 
The node_test.go has many skipped test points relevant to this job. 
https://github.com/algorand/go-algorand/issues/892 is tracking this.

Remove the phonebook from the node

---

scripts/check_deps.sh
scripts/configure_dev.sh

When running `make`, `sqlite3` is used but was not included as a dependency in:
* `scripts/check_deps.sh`
* `scripts/configure_dev.sh`
Ran `scripts/configure_dev.sh` and `make` on macOS and Ubuntu 18.04.

Add sqlite3 as a dependency

---

scripts/release/test/Jenkinsfile
scripts/release/test/util/test_package.sh

Setting `set -e` caused the build to abort and clean itself up (delete the ec2 instance), as the script returned `exit 1`.  However, removing the `set` statement had the effect of the script running and finishing properly with a return value of `exit 0`.  I found it very odd, and played with it for a while, but then decided that it was more important to just fix it and move on.

Fix silent failure in test phase

---

logging/telemetryhook.go

When the elasticHook returns an error, asyncTelemetryHook will not change to ready state.
Consequently, the elements will get stuck in the channel and the buffer.
The waitGroup associated with these elements, will prevent the telemetry from quitting.
This PR stops waiting for these elements.

telemetryhook gets stuck during shutdown

---

catchup/service.go

The error logging that we've had at `nextRoundIsNotSupported` wasn't that great.
```
nextRoundIsNotSupported: could not retrieve last block (5372709) from the ledger.
```
In this PR, I have extended that to contain the originating error from the database.
This would hopefully give us some better idea of what went wrong and allow us to address the originating issue.
Resolves https://github.com/algorand/go-algorand/issues/911

Improve error logging on nextRoundIsNotSupported

---

util/db/dbutil.go

Ledger service was generating the following error:
```
{"file":"ledgerService.go","function":"github.com/algorand/go-algorand/rpcs.(*LedgerService).ServeHTTP","level":"warning","line":174,"msg":"ServeHTTP : failed to retrieve block 3735696 database is locked","time":"2020-03-15T16:21:05.316959Z"}
```
The root cause was the sqlite driver returning a `database is locked` when a new connection attempt was made. Existing code was already testing extensively for temporary locked database conditions on transaction creation/execution, but not on connection creation.
resolves issue https://github.com/algorand/go-algorand/issues/915

Add retry for creating a DB connection

---

catchup/fetcher_test.go
config/config.go
config/local_defaults.go
network/topics.go
network/wsNetwork.go
network/wsPeer.go
rpcs/ledgerService.go
rpcs/ledgerService_test.go
rpcs/wsFetcherService.go
test/e2e-go/features/catchup/basicCatchup_test.go
test/framework/fixtures/restClientFixture.go

* Introduce versioning: old: 1, new: 2.1
* Add keys to topics as const in topics.go
* Introduce MakeTopic to create topics without exporting the Topic fields
* Change wsPeer.Respond to accept Topics instead of OutgoingMessage
* Add methods: Version, Request, Respond to UnicastPeer interface (should rename UnicastPeer?)
* Make LedgerService handleCatchupReq support v2.1 (request/respond using topics)
* Make WsFetcherService RequestBlock support v2.1 (request/respond using topics)
Modifying TestGetBlockWS to test version 2.1
Will add e2e test to test all cases of the two version combinations.

Catchup service through gossip connections using the topics

---

test/e2e-go/features/catchup/basicCatchup_test.go

t.Parallel is getting called multiple times in the same test.  This
bug was introduced when the test was refactored so it can be called
multiple times with different configurations. t.parallel was left in
the body of the test called multiple times. It is a puzzle why it was
passing before, but now it is failing.

Fix for TestCatchupOverGossip failed in nightly

---

cmd/goal/commands.go

When investigating the random failures on the teal e2e tests, we ran into various unexplained failures. Once we implemented the file locking, these issue went away. however, we forget to remove the debug line telling us about the issue.

Roll back temporary debug printing

---

config/consensus.go
data/bookkeeping/block.go
data/bookkeeping/block_test.go
protocol/consensus.go

Enable executing protocol upgrade as implemented at 
https://github.com/algorand/go-algorand/commit/7a415e4855558e66b55785b8342f4e59cb60a2ec and approved at 
https://github.com/algorandfoundation/specs/commit/57016b942f6d97e6d4c0688b373bb0a2fc85a1a2

Enable upgrade delay tuning.

---

config/consensus.go
data/bookkeeping/block.go
data/bookkeeping/block_test.go
protocol/consensus.go

* [betanet] Enable upgrade delay tuning.
* Use official spec commit hash.
* Bump ConsensusCurrentVersion.
* Fix old failing test.

Enable upgrade delay tuning. (#902)

---

cmd/algoh/blockstats_test.go

The TestAgreementTime was testing the timing measurement performed by `blockstats::onBlock`. To do so, it was calling it twice in a row, with a predetermined delay.
Then, it would compare the resulting event time measurement by comparing it to the expected value ( i.e. the delay ).
While the idea here is correct, the implementation wasn't that great. On slower machines, the `time.Sleep(XXX)` function might take longer than the desired time. As a result, the time measured by `blockstats::onBlock` could be skewed upward. To work around this limitation, the test was modified to use dynamic delay with self-validation for expected errors. Note that the change here would work correctly for this type of tests, but might not work well on others.

Fix timing bug in TestAgreementTime

---

cmd/updater/update.sh
scripts/dev_install.sh

`make install` calls `updater.sh`, which backs up the old binaries before installing new ones. On my machine it takes 7 seconds to backup the files, which for small/no-op builds is 50% of the build time. Added `-s` option to updater.sh to skip the backup, and enable it by default in `dev_install.sh`.
Run `make install` and see that it doesn't freeze for 5-10 seconds while backing up binaries

Disable binary backup when running make install

---

scripts/build_packages.sh
scripts/release/build/deb/package.sh

This code is only needed in one place, so let's move it there.  Also, extracting it from `build_packages.sh` helps greatly when creating breaking the build pipeline up into individual operations that then become `mule` tasks.

Remove call to build_deb.sh from build_packages.sh

---

ledger/cow.go
ledger/eval.go

CPU pprof graphs here: [txid-graphs.tar.gz](https://github.com/algorand/go-algorand/files/4410682/txid-graphs.tar.gz)
The benchmark I used may be [found on the maxj/applications branch here](https://github.com/justicz/go-algorand/blob/maxj/applications/ledger/ledger_perf_test.go).
```
maxj@algog ~/P/a/g/ledger> go test -run=XXX -bench='BenchmarkPay.*5000' -benchtime=25x -cpuprofile perf-no-opt.prof
goos: linux
goarch: amd64
BenchmarkPaymentEvalPerf5000-8                25         240774911 ns/op
...
maxj@algog ~/P/a/g/ledger> git checkout maxj/txid_calc_eval_once
Switched to branch 'maxj/txid_calc_eval_once'
maxj@algog ~/P/a/g/ledger> go test -run=XXX -bench='BenchmarkPay.*5000' -benchtime=25x -cpuprofile perf-wi-opt.prof
goos: linux
goarch: …
```

Only compute TxID once during validated eval

---

data/ledger_test.go
data/pools/transactionPool.go
data/pools/transactionPool_test.go
data/transactions/aggregates.go
ledger/eval.go
ledger/eval_test.go
node/impls.go

In go, as `append` is called over and over on a slice, its capacity grows like this:
```
0xc000014180 cap 1
0xc0000200f0 cap 2
0xc00001a0c0 cap 4
0xc00009c000 cap 8
0xc00009e000 cap 16
0xc0000a0000 cap 32
0xc00001c600 cap 64
0xc0000a2000 cap 128
0xc0000a8000 cap 256
0xc0000ae000 cap 512
0xc0000b4000 cap 1024
0xc0000ba000 cap 1365
0xc0000c2000 cap 1706
0xc0000cc000 cap 2389
0xc0000da000 cap 3072
0xc0000ec000 cap 4096
0xc000104000 cap 5120
0xc000122000 cap 6485
0xc000148000 cap 8192
0xc000178000 cap 10240
```
Currently, in the `BlockEvaluator`, the block's `Payset` is growing only by successive calls to `append`. However, everywhere we are currently using a `BlockEvaluator`, we have a reasonable hint for how big the evaluated `Payset` will be.
On my `maxj/applications` branch with this PR …

Hint payset size in block evaluator

---

cmd/goal/messages.go
cmd/goal/tealsign.go

Currently if you specify neither, you'll sign with an empty key.

Require one of keyFilename or signareAcct in `goal clerk tealsign`

---

test/e2e-go/features/catchup/basicCatchup_test.go

The catchup upgrade test was not setting up the MinUpgradeWaitRounds while using an upgrade window of 0. This caused the test to use an MinUpgradeWaitRounds=10000, which failed the applyUpgradeVote test. 
Fix https://github.com/algorand/go-algorand/issues/942

Update catchup test to support adjustable upgrade window

---

config/consensus.go
data/basics/msgp_gen.go
data/basics/userBalance.go
data/pools/transactionPool.go
data/transactions/logic/eval.go
data/transactions/msgp_gen.go
data/transactions/signedtxn.go
data/transactions/transaction.go
data/transactions/verify/txn.go
ledger/acctupdates_test.go
ledger/eval.go
ledger/eval_test.go

Add backend support for rekeying: allowing transactions to change the spending key of an existing account. Such transactions will only be allowed once the protocol supports them -- this PR can be merged now without changing any behavior, and a future protocol upgrade can flip the switch to enable the feature.
This PR is the backend logic -- the ledger / block evaluator. Frontend work (goal / kmd support) will be in a subsequent PR.

Re-keying: backend

---

data/pools/transactionPool.go
data/pools/transactionPool_test.go
data/txHandler_test.go
node/node.go

The documented intended behavior for EnableAssembleStats is to
generate AssembleBlockMetrics, while for EnableProcessBlockStats it is
to generate ProcessBlockMetrics.  The current implementation reverses
these behaviors.

Bugfix: Swap EnableAssembleStats with EnableProcessBlockStats.

---

daemon/algod/api/server/router.go
go.sum

It seems that Gorilla Mux ignores trailing slashes while Echo is more strict about them. The Java SDK was appending a slash, so it isn't working properly without this fix.

Allow trailing slash in rest endpoints.

---

data/pools/transactionPool.go

`GetEncodedLength` is defined on `SignedTxn`, not `SignedTxnInBlock` (which embeds `SignedTxnWithAD` which embeds `SignedTxn`). So attempting to call it on a `SignedTxnInBlock` will produce an unexpected result since the encoding will omit e.g. `ApplyData`.
This PR matches is closer to how length is [actually computed in the block evaluator](https://github.com/algorand/go-algorand/blob/82e804e4c374876e3c8a2f45d2ce49cdbf82dc26/ledger/eval.go#L485).

Encode `SignedTxnInBlock` to measure length, not `SignedTxn`

---

daemon/kmd/api/v1/handlers.go
daemon/kmd/client/wrappers.go
daemon/kmd/lib/kmdapi/requests.go
daemon/kmd/wallet/driver/ledger.go
daemon/kmd/wallet/driver/sqlite.go
daemon/kmd/wallet/wallet.go
data/transactions/signedtxn.go
data/transactions/transaction.go
ledger/acctupdates_test.go
ledger/eval_test.go
libgoal/libgoal.go
libgoal/transactions.go

Give KMD's SignTransaction an (optional) public key argument.
If provided, KMD signs the transaction using the corresponding private key and sets the AuthAddr if necessary.
goal / libgoal will use this KMD functionality in order to sign transactions from rekeyed accounts (which will come in a separate PR)

Add optional pk argument to KMD's SignTransaction

---

ledger/acctupdates.go

This code was needlessly recomputing deltas that already existed in the cow.

Remove unnecessary call to `getChangedAssetIndices` in acctupdates.go

---

tools/network/cloudflare/cloudflare.go
tools/network/cloudflare/createRecord.go
tools/network/cloudflare/deleteRecord.go
tools/network/cloudflare/listRecords.go
tools/network/cloudflare/zones.go

Algorelay needs to have the ability to convert a previously created A DNS record into a CNAME DNS record and vice versa.
This PR adds that ability as well as improve the error logging in case of an issue.

Make algorelay handle domain names type conversions

---

config/consensus.go

To prevent a dual upgrade round, we need to jump directly from V21 to
V23. This was tested in a custom algonet and is merged to rel/stable for the 2.0.6 release.

Skip V22 consensus upgrade

---

test/e2e-go/upgrades/send_receive_upgrade_test.go

e2e test was failing due to missing package dependency.
Issue triggered due to auto-merge during the GitHub merge process.

Fix e2e test missing runtime package.

---

cmd/algokey/sign.go
cmd/goal/clerk.go
libgoal/transactions.go

Add very basic rekeying support to goal, algokey, and libgoal.
`algokey` now sets the authaddr if necessary, inferring the address from the private key used for signing and checking whether it matches the transaction sender.
`libgoal` gets a new method `kmdClient.SignTransactionWithWalletAndSigner` that's like `SignTransactionWithWallet` but takes in an extra argument, the signer address. (If the signer address is the empty string, the behavior is the same as `SignTransactionWithWallet`.)
`goal clerk spend` gets a flag to set the rekey-to address. (It should be easy to add this flag to other goal commands that create transactions.) `goal clerk sign` gets a flag to specify the signer address; it uses the new libgoal method.

Rekeying: basic frontend

---

cmd/algoh/client.go
cmd/algoh/mockClient.go
cmd/goal/commands.go
cmd/goal/node.go
daemon/algod/api/algod.oas2.json
daemon/algod/api/algod.oas3.yml
daemon/algod/api/client/restClient.go
daemon/algod/api/server/v2/generated/private/routes.go
daemon/algod/api/server/v2/generated/routes.go
daemon/kmd/client/client.go
libgoal/libgoal.go
netdeploy/network.go
test/e2e-go/perf/basic_test.go
test/e2e-go/restAPI/restClient_test.go
test/framework/fixtures/auctionFixture.go

Libgoal is currently using the v1 entry points exclusively.
This change modify the libgoal to start using the v2 status command, which will be expanded in subsequent PRs.

Modify libgoal to use v2 status instead of v1 status

---

.travis.yml

We were ignoring them before, but now that the folders have changed our artifact upload process is failing. This will ignore the new folders as well.
I ran the git command to verify that these files are no longer included

Ignore lib-sodium copies and binaries

---

daemon/algod/api/server/lib/middlewares/logger.go

The logger middleware had a wrong format verb.

Fix REST API logger middleware formatting.

---

cmd/goal/commands.go

add a goal command to dump all known protocols as json. Useful for other tools to import (Indexer).

add `goal protocols`

---

agreement/demux.go

The agreement simulator unit test fails randomly ( and rarely ), with a data race related to the `processingMonitor`. The data race is caused due to incoming message arriving before the demux initialization is complete.
specifically, the tokenizeMessages is calling UpdateEventsQueue which tests the value of processingMonitor while the makeDemux attempts to set it.
Setting the `processingMonitor` before calling tokenizeMessages completely resolves this issue.

agreement: fix simulator random data race

---

protocol/codec.go
protocol/codec_test.go

EncodeJSONStrict is like EncodeJSON but converts integer keys to strings so that the output is valid json.
Unit test ensures no integer keys and correct decoding.
Closes #1076

Implement protocol.EncodeJSONStrict

---

test/scripts/e2e_client_runner.py

e2e_client_runner.py would sometimes fail to capture stdio from failing subtasks. Fix:
If p.communicate() finishes, use returned stdio.
If p.communicate() throws exception, try p.stdout p.stderr
This **is** a test.
`(make && cd test/scripts && python3 e2e_client_runner.py e2e_subs/*.sh)`

improve e2e script runner

---

logging/telemetryhook.go

When creating an async hook with channelDepth > maxQueueDepth, we might get to a situation where the immediate processing queue isn't large enough to contains all the pulled events. When that happens, the existing code drop the event.
To account for loss of event, we have the algod_telemetry_drops_total metrics, which measures how many events we have dropped. Unfortunately, the above code does not update the algod_telemetry_drops_total, causing the wrong number of events to be reported.
Resolves issue #1086

Fix missing algod_telemetry_drops_total event

---

cmd/algod/main.go
cmd/goal/node.go
test/e2e-go/cli/goal/expect/goalCmdFlagsTest.exp

Neither algod nor goal were validating the -p parameter ( i.e. the -p parameter is used to specify a peer list to connect to ).
The -p parameter is used extensively in our testing environment, but rarely on production code. Since the automated testing was always passing the "correct" and "valid" values, it never was an issue. However, while implementing the fast catchup, I attempted to use it incorrectly and ran into various issues as a result. Having the code verify the correctness upstream would have prevented these issues.
This change is covered by an expect test.
While not strictly required for the fast catchup, it was created during the fast catchup development, so I'll leave that as the originating issue. issue #1024

Perform parameter validation on -p arguments on goal & algod

---

daemon/algod/api/server/v1/handlers/handlers.go
daemon/algod/api/server/v2/handlers.go
test/e2e-go/features/transactions/group_test.go

We should never need to decode more than `MaxTxGroupSize` transactions on transaction submission, because that group can never be valid.
Covered by an existing test that I modified in this PR. The failure just happens higher up the stack now.
https://github.com/algorand/go-algorand/issues/1090

Limit txn group size when broadcasting raw transactions

---

cmd/goal/clerk.go
data/basics/msgp_gen.go
data/basics/userBalance.go
data/transactions/transaction.go
ledger/eval.go

We're already using "spending key" to refer to private keys in various
user-facing places, so calling the rekeying-related address field a spending
key would be unnecessarily confusing.

Rename balrecord.SpendingKey to AuthAddr

---

agreement/cadaver.go

The agreement service manages the creation/deletion/updates of the cadaver files.
Currently, whenever we fail to rename a cadaver file, we generate and log an error.
This shouldn't always be the case. If the cadaver file was deleted externally, we should just log it as informational message. Also, in case of a different issue, we should log it as a warning, since it doesn't affect the functional state of the node.

Reduce cadaver failures error levels

---

scripts/release/mule/package/linux/amd64/deb/package.sh
scripts/release/mule/package/linux/amd64/rpm/package.sh

This allows the BRANCH, CHANNEL and VERSION env vars to be specified in the mule yaml file.  It is the same functionality that was added later to other mule tasks.
Add any or all of the above to the env block in any mule yaml file.

Allow env vars to be set for mule package task

---

go.mod
go.sum
protocol/codec_tester.go

Recently we added support for Raw structures in the msgp library. This PR makes the corresponding changes to the unit testing, ensuring that structures which contains Raw interfaces would not get compared to the go-codec. ( which has it's own Raw struct implementation )

Add support for Raw msgp interfaces on unit tests

---

scripts/release/forward_gpg_agent.sh

The code to find the correct Keygrip for the signing key was not correct for dev@algorand.com. This fixes it by selecting the right key.
Keygrip command tested on Ubuntu 18.04 Vagrant image.

Fix finding dev@algorand.com's Keygrip for signing

---

scripts/buildhost/linux-arm.sh

The AMI for the ARM host builder was updated in rel/beta, but not in master. This fixes that.
N/A

Update AMI for arm buildhost (#506)

---

scripts/travis/build.sh

Compiling on ARM takes a long time. As a partial workaround, we want to eliminate recreating the message-pack encoders/decoders, as these already generated by other platforms.
Execute the build on ARM and see that we're able to compile

Avoid regenerating msgp decoders/encoders dynamically on ARM

---

ledger/acctupdates.go
ledger/acctupdates_test.go

This PR address a potential data race detected by our automation testing. The data race occurs when a catchpoint label is being written to disk and a new block is added to the ledger at the same time.
Repurpose one of the accountUpdates unit test to verify the fix works as expected.

Fix datarace when writing a catchpoint label

---

ledger/acctupdates.go
node/node.go

The initializeFromDisk function is called a second ( or third..) time when we attempt to complete the fast catchup process and switch to the new accounts data. When that happen, we need to shut down the entire backend and reload it.
This PR addresses two such data races - 
The first in the account initialization, where the previously allocated communication channel with the commit goroutine need to be updated.
The second is on the node itself, where we need to preallocate the node context object prior to creating the node monitoring goroutines 
These two issues were found using the fast catchup e2e test. I have used this test in order to verify the fix as well.

Fix two more dataraces during catchup mode switch

---

scripts/compute_branch_channel.sh

While working on the indexer pipeline, `shellcheck` found an unused variable in `scripts/compute_branch_channel.sh`, which this commit removes.
Nothing to test.

Remove unused var in compute_branch_channel.sh

---

scripts/release/forward_gpg_agent.sh

There was an error in the forward GPG agent script, that caused the SSH key copying to fail.
N/A, not an easy way to test this. Script was executed manually to ensure the SSH key copying worked (which it did).

Bugfix - build_packages should be build-packages

---

cmd/updater/toolsCmd.go

Updater was almost a general purpose algorand package fetcher. Add the missing "--package" option so that we can use it to fetch other packages (I don't think the third package has been deployed yet, but it is why I want this new option):
```
~$ updater gettools -c nightly -o tools.tar.gz
~$ updater gettools -c nightly -p tools -o tools.tar.gz
~$ updater gettools -c nightly -p node -o node.tar.gz
~$ updater gettools -c nightly -p algorand-updater -o updater.tar.gz
```
Ran the above commands and made sure the correct packages are downloaded (when available).

Allow updater to request any package with 'gettools' subcommand.

---

data/transactions/asset.go
test/e2e-go/features/transactions/asset_test.go

Fix incorrect asset error message when trying to overspent an asset.
The reported value in the error message was the subtracted ( invalid ) result, instead of the pre-subtraction value.
Existing e2e test was extended to cover this change.

Fix incorrect asset error message when trying to overspent an asset

---

test/e2e-go/features/catchup/basicCatchup_test.go

The TestCatchupOverGossip was randomly failing during testing on slow machines. The culprit was that we were making few performance related assumptions, which were not correct. In this case, we started a network, and shut it right away. The assumption was that the network would not be able to make any progress since it was shut down right away. This is not guaranteed to be the case. The better way to make sure no progress is made on a node is to prevent it from running at all.

Fix sporadic TestCatchupOverGossip e2e test failure(s)

---

cmd/goal/asset.go

* The reserve address, when blank, is shown in the asset info as if it
is set to the creator's address.
* When reserve address change transaction is accepted, nothing changes
(because the blank remains blank, and shows the creator's address).
* When the reserve address is empty, but showing the creator's
address, then it does not count towards a non-empty address. So,
when all the addresses but the manager are empty, but shows as if
reserve and manager are non-empty, clearing the manager address
destroys the asset.
This change removes the lines which set the reserve address to the
creator's address when the reserve address is blank.

Blank reseve address shows creator's address.

---

scripts/configure_dev-deps.sh

Fix bug in configure_dev-deps.sh - was using output for error checking instead of last exit code.
Make sure tests pass.

Bugfix - don't use output for error detection

---

cmd/algoh/main.go

Algoh is a host process, intended to monitor the child algod process. On algoh invocation, it starts the algod with the same input argument it was called upon.
Prior to this change, the following command line options, which were supported by algod would have been blocked by algoh:
1. -p
1. -l
1. -seed
1. -g
( note that this is not a complete list. There are other non-runnable, informational command line options which are still not supported. These provides little value )

Bugfix: Better algoh parameter tunneling

---

config/consensus.go
data/basics/msgp_gen.go
data/basics/userBalance.go
data/bookkeeping/genesis.go
data/bookkeeping/msgp_gen.go
data/transactions/application.go
data/transactions/msgp_gen.go
data/transactions/transaction.go
protocol/codec_tester.go

Add a allocbound for the byte slices definition in our code that gets message-packed.
The unit testing is verifying that we didn't miss any additional instance.
Auto-generated tests were updated, and detection of missing allocbound tag testing was updated.

Update code to take advantage of byteslice allocbounding

---

catchup/catchpointService.go

When the node is in fast catchup mode, either stopping the node or aborting the catchup does not work in fashionable manner.
The stop/abort operation is expected to happen right away, whereas we had some long delays before it would complete.
Both node stopping during fast catchup as well as aborting the fast catchup were tested manually.
I was able to confirm the issue with both of them, as well as confirm that the issue was resolved after the change.

Handle stopping and aborting in catchpoint catchup service

---

.travis.yml

Travis builds are occasionally failing with the following error:
```
==21650==ERROR: ThreadSanitizer failed to allocate 0x80000 (524288) bytes of clock allocator (error code: 12)
2471FATAL: ThreadSanitizer CHECK failed: ./gotsan.cc:6976 "((0 && "unable to mmap")) != (0)" (0x0, 0x0)
2472FAIL	github.com/algorand/go-algorand/ledger	477.548s
2473Makefile:199: recipe for target 'short_test_target_github.com/algorand/go-algorand/ledger' failed
```
Error 12 above is "out of memory" error. 
If the underlying culprit is a limit of the map count, this should boost it up.
Note that the real consumer of the high-volume of mmaps is the go race detector ( or the underlaying ThreadSanitizer ).

Increase travis builtin vm.max_map_count

---

.travis.yml

Adding vm.max_map_count to travis did not helped to fix the observed issue #1175 was intended to solve. This PR rolls back the change.

rollback .travis.yml by removing the max_map_count change

---

scripts/release/mule/sign/sign.sh

This removes "./" from the beginning of some lines in the hashes files.
If the releases page generates the checksums correctly, then this works.

Fix content of hashes file(s)

---

cmd/goal/clerk.go

Fix typo in `goal clerk` option disassesmble
No tests, the change is trivial

Fix typo in goal clerk

---

scripts/release/mule/package/deb/package.sh

The deb package name wasn't corrrect.  This adds the `CHANNEL` and the `OS_TYPE` and arranges the bits in the proper order.
n/a

Fix deb package name

---

scripts/travis/run_tests.sh

Reducing the amount of parallel testing on travis is likely to reduce the memory demand stress. On travis machines, where memory is limited, this could help us avoid OOM cases.

Reduce parallel testings on travis

---

cmd/goal/asset.go
cmd/goal/clerk.go
cmd/goal/multisig.go

txFilename and outFilename variables in goal now are used consistently,
one for reading and another for writing out.
Rely on existing expect tests :
goal clerk send: test/e2e-go/cli/goal/expect/limitOrderTest.exp
goal asset * : test/e2e-go/cli/goal/expect/limitOrderTest.exp
goal clerk multisign merge: no current tests cover this change. Will open a ticket for creating these tests.
`applications` branch introduces a new common function for providing `-o`,`--fee` and so on common args. This PR fixes vars usage in existing code.

Unify txFilename and outFilename vars usage in goal

---

scripts/release/mule/deploy/rpm/deploy.sh

This won't overwrite the current repo on s3.  It will append to it.  Doing it this way ensures that the latest release is downloaded and installed via `yum`.
After running this script, go to a centos container and download the latest package to make sure it's the same one.

Only add the latest version to the rpm repo

---

config/config.go
config/local_defaults.go
daemon/algod/api/server/v2/handlers.go
daemon/algod/api/server/v2/test/handlers_test.go
daemon/algod/api/server/v2/test/helpers.go
installer/config.json.example

Add a local config to disable teal/compile in algod by default. This PR solves #1109.
The goal is to tie the TealCompile and DryRun in the algod REST endpoint with this new flag.
The DryRun functionality would be added with or after the application main PR, and this PR prepares the ground for that.
Unit test was updated to use the new construct.
This is a spinoff of the original PR https://github.com/algorand/go-algorand/pull/1163 by Shumo.

Add EnableDeveloperAPI configuration flag

---

daemon/algod/api/server/router_test.go
daemon/algod/api/server/v1/routes/routes.go

When I converted the route path from Gorilla Mux notation to Echo I missed one of the parameters.
Before:
```
$ curl "$(cat ~/.algorand/algod.net)/v1/account/invalid/transactions/pending" -H "Authorization: bearer $(cat ~/.algorand/algod.token)"
{"message":"Not Found"}
$ curl "$(cat ~/.algorand/algod.net)/v1/account/FCHLCNFIQ3L5QELMQDADI6BU2ANK2A2ICKXXG7ACJBNEAB64J7UJUPJHJE/transactions/pending" -H "Authorization: bearer $(cat ~/.algorand/algod.token)"
{"message":"Not Found"}
```
After:
```
$ curl "$(cat ~/.algorand/algod.net)/v1/account/invalid/transactions/pending" -H "Authorization: bearer $(cat ~/.algorand/algod.token)"
failed to parse the address
$ curl "$(cat ~/.algorand/algod.net)/v1/account/FCHLCNFIQ3L5QELMQDADI6BU2ANK2A2ICKXXG7ACJBNEAB64J7UJUPJHJE/transactions/pending" -H …
```

Fix route path to use echo parameter notation.

---

scripts/release/test/stage/test/task.sh

The gpg-fake script was recently moved, but the path was incorrectly updated.
Ensure test pipeline works correctly.

Fix path to gpg-fake.sh script

---

scripts/buildnumber.py
scripts/configure_dev.sh
test/scripts/timeout

`python3.7-venv` turned into `python3.8-venv` in ubuntu 20.04, use the default version instead.
Setup a new machine with the script and see `make install` and `make integration` work.
This script is also used by travis, but travis has a wrapper script that is already using `python3-venv`.

Update configure dev script to work with ubuntu 20.04

---

agreement/player_test.go
agreement/proposalTracker.go
agreement/proposalTracker_test.go
config/consensus.go
data/committee/credential.go

Now that the protocol upgrade fixing the bug has gone through, we no longer need to keep the buggy version around for compatibility.

Remove old buggy version of proposal LowestOutput

---

scripts/configure_dev-deps.sh

The script to configure dev dependencies installs various supporting golang modules. However, these versions do not take into account entries in go.mod, which means the versions can conflict.
This is a restoration of a previous pull request, with the bug fix around handling error conditions.
Successful builds in Travis.

Match go modules in dev deps to versions in go.mod

---

test/e2e-go/cli/goal/expect/catchpointCatchupTest.exp

The test was creating a proxy which delays requests execution as a way to slow down the catchpoint catchup process.
This is important so that we can monitor from the goal command that the catchup is working as intended.
However, delaying the command execution caused an issue where the node was trying to issue multiple requests for blocks 1-16, in parallel, which reached the proxy at an arbitrary order. As a result, the request for block #1 was delayed by more than 4 second, causing it it timeout.
The solution was to reconfigure the number of parallel blocks being retrieved to 2. This would ensure that we only getting two blocks at a time. Since the delay is configured to 1.5 seconds, this would also be the delay, which is well under 4 second.

Fix random catchpoint catchup expect test case

---

test/e2e-go/features/catchup/basicCatchup_test.go

TestCatchupOverGossip was using an incorrect verification and shown random failures. The expression
```
a.True(nodeStatus.LastRound >= primaryStatus.LastRound)
```
Is incorrect, since the network does move forward atomically. The primary node, even when having no accounts, might end up moving to the next round before the other node, which "told" it how to do so.

Fix random fails in TestCatchupOverGossip

---

config/config.go

This PR adds automatic detection of `betanet` genesis files and update the `DNSBootstrapID` if it has not been set by the user.
The implementation follow the same logic as with `devnet`, and would allow us to deploy `betanet` nodes without requiring the end user to provide a config.json file which sets the `DNSBootstrapID` explicitly.
I tested this change manually and confirm it's correctness.

Automatic DNSBootstrapID for betanet

---

network/connPerfMon_test.go

This change reduces the time it takes to execute the TestConnMonitorStageTiming by factor of 14.
It's expected to take about 10 seconds on travis, whereas it used to take 150 seconds.

Improve TestConnMonitorStageTiming benchmark performance

---

cmd/tealdbg/cdtSession.go
cmd/tealdbg/debugger.go
data/transactions/logic/debugger.go

This change fixes a presumed typo.

Rename AppStateChage to AppStateChange.

---

test/e2e-go/features/teal/compile_test.go

A program with no `#pragma version 2` should result in compiling a version 1 program.

Fix `TestTealCompile`

---

util/db/versioning.go
util/db/versioning_test.go

This PR implements the core functionality for database versioning support.
In this PR, I haven't used it in any particular database. It's part of the support for reencoding the accounts.

Implement database versioning support

---

daemon/algod/api/server/v2/dryrun.go
daemon/algod/api/server/v2/dryrun_test.go

StateDelta conversion in Dryrun incorrectly used pointers to in-loop variable.
Added a unit test

Fix StateDelta conversion in Dryrun

---

cmd/tealdbg/README.md
cmd/tealdbg/cdtdbg.go

Newer versions of Google Chrome dropped chrome-devtools:// schema and use devtools:// instead

Fix tealdbg CDT url

---

cmd/diagcfg/main.go

Fixes #1259 
Based on code within /cmd/goal/commands.go

Add generate-docs command to `diagcfg`

---

daemon/algod/api/server/v2/dryrun_test.go
data/basics/teal.go

* Motivation: having TealBytesType = 1 and SetBytesAction = 2
looks confusing for non-golang consumers of REST API
Namely in SDKs these types are used as raw int values.
* This change sets SetBytesAction = 1 and SetUintAction = 2
to keep things consistent
Rely on existing test suite. Tested with
```
go test ./data/transactions/... ./data/basics/...
go test ./cmd/... ./libgoal/... daemon/algod/api/...
export NODEBINDIR=~/go/bin
export TESTDATADIR=`pwd`/test/testdata
go test ./test/e2e-go/features/transactions/... -run TestAssetInformation
go test ./test/e2e-go/features/transactions/... -run TestAccountInformationV2
export TESTFILTER=Dryrun
go test ./test/e2e-go/cli/goal/... -run TestGoalWithExpect -count=1
unset TESTFILTER
unset TESTDATADIR
unset NODEBINDIR
```

Change constant values of DeltaAction

---

ledger/archival_test.go

The unit test TestArchival is randomly failing on travis linux-amd64 configuration due to random memory allocation failures.

Disable TestArchival unit test on linux-amd64

---

cmd/tealdbg/dryrunRequest.go
cmd/tealdbg/local.go
daemon/algod/api/server/v2/dryrun.go

* tealdbg now uses DryrunRequest.Sources if supplied
* Fix competing AppParams resolution
if both present in accounts and DryrunRequest.Apps: account data
take priority and only empty values are overwritten
* Document program search in both dryrun and tealdbg
Existing autotest.
Manual test with Python SDK: craft a TEAL test, save DryrunRequest, use it to run both dryrun and tealdbg.

Improve dryrun and tealdbg compatibility

---

util/db/dbutil.go

Running on travis reveled the following error messages:
```
time="2020-07-20T22:08:31.223165 +0000" level=warning msg="dbatomic: tx surpassed expected deadline by -841.720871ms" callee="github.com/algorand/go-algorand/ledger.(*blockQueue).syncer.func2" caller="/home/travis/gopath/src/github.com/algorand/go-algorand/ledger/blockqueue.go:137" file=dbutil.go function="github.com/algorand/go-algorand/util/db.(*Accessor).atomic" line=343 readonly=false
```
The time of `-841.720871ms` should clearly have been `841.720871ms`, and was caused by subtracting the two timestamps in reverse.

Fix negative "tx surpassed expected deadline" messages

---

ledger/blockqueue.go
ledger/ledger.go
ledger/ledger_test.go

The typical flow is that we add a new block, and then try to evaluate the subsequent block.
When doing so, the previous block was already flushed to disk by the `block.syncer`, and so we're reloading the block from the `blockqueue` just so we can store it's header in the `ledger.headerCache`.
From functional perspective, there is nothing wrong here, but it's not very efficient. This PR adds the block header to the blocks header cache on Ledger.AddValidatedBlock, which ensure that subsequent calls to BlockHdr would not hit the disk.
Added a unit test to verify that it's working correctly.

Add blocks header to the header cache

---

agreement/voteTracker.go
crypto/merkletrie/node.go
ledger/acctupdates.go
ledger/catchpointwriter.go
ledger/eval.go
ledger/ledger.go
scripts/travis/external_build_printlog.sh
test/e2e-go/cli/goal/expect/goalExpectCommon.exp
util/metrics/serviceCommon.go

The function `GetRoundTxIds` is no longer used by the evaluator, and not needed to be part of the `ledgerForEvaluator` interface. The backing implementation on `Ledger` was left as is for future usage. 
Note that as of this PR, there are no other places in our codebase which calls to `GetRoundTxIds`.
Also - I fixed a common typo of mine: `migth` -> `might`

Remove unused GetRoundTxIds from ledgerForEvaluator interface

---

data/transactions/logic/assembler.go
data/transactions/logic/assembler_test.go
data/transactions/logic/backwardCompat_test.go

txn with two args is assembler-level alias for txna,
and this requires some additional checks
1. Fix copy-paste error in txna disassemble routine
2. Fix assembling 'txn Accounts' without second argument
Added new unit tests for `txn/txna` and `gtxn/gtxna`

TEAL: fix txn and txna assemble and disassemble routines

---

cmd/tealdbg/local.go
cmd/tealdbg/localLedger.go
cmd/tealdbg/main.go
cmd/tealdbg/server.go

While documenting TEAL testing in Python, I found `tealdbg` does not use `Round` and `LatestTimestamp`
from dryrun request object that creates difficulties with tests debugging.
Rely on existing auto tests.
Manual test Using python SDK:
```python
accounts = [creator_data, sender_data]
req = Helper.build_dryrun_request(source, sender=sender, app=dict(
app_idx=1,
creator=creator,
args=[b"vote", "test"],
round=3,
accounts=accounts,
))
Helper.save_dryrun_request("dr.mgsp", req)
```
Then run the debugger with the command below and open the `devtools://` url in Google Chrome:
```bash
tealdbg debug --dryrun-req dr.mgsp --proto future
```

Tealdbg: use round number and latestTimestamp from dryrun-req if available

---

test/e2e-go/cli/goal/expect/goalDryrunRestTest.exp

This adds a test for goal clerk dryrun failures. Right now it just tests the failure case of not providing an application file, but it includes a method that can test any error message scenario we can expect
I ran the test and ensured that the test is checking the expected values

Add test for when the user does not provide a correct application json

---

ledger/acctupdates.go
ledger/totals_test.go

Existing code was calling `accountsUpdateBalances` for each round, applying the deltas to the trie and committing the changes to disk. However, on some of our testings, we have 1-2 changes per block, and we're pushing 2000-4000 blocks very quickly. This leads to a scenario where `commitRound` is asked to flush 500+ rounds to disk in a single batch. From
logical perspective, there is nothing wrong here.
Unfortunately, flushing 500 rounds * 2 changes =~ 1000 Merkle trie pages. ( i.e. the root page + one extra page update)
When flushing 1000 pages on slow machines such as travis, it can take a long time, and we want to avoid that.
( i.e. if a single flush takes 50ms on a NAS drive, it would take 50 seconds to complete.. )
In order to resolve that, I have moved the round iteration loop into …

Optimize accountsUpdateBalances implementation

---

cmd/algocfg/main.go
cmd/diagcfg/telemetry.go
cmd/goal/clerk.go
cmd/goal/commands.go
cmd/goal/completion.go
cmd/goal/kmd.go
cmd/goal/ledger.go
cmd/goal/logging.go
cmd/goal/network.go
cmd/goal/node.go
cmd/goal/wallet.go
cmd/netgoal/generate.go
cmd/netgoal/network.go
cmd/nodecfg/apply.go

Updates the short commands descriptions so that they would be :
1. Capitalized ( with the exception of tool names, which are case sensitive )
2. Have no "." at the end of the sentence ( just to align it with the rest of the commands. )

Reformat some of the short commands descriptions

---

data/transactions/logic/assembler.go
data/transactions/logic/assembler_test.go
data/transactions/logic/backwardCompat_test.go
data/transactions/logic/eval_test.go

* TEAL v1 does not allow such program, so make assembler compatible
* TEAL v2 permits the mentioned behavior
Added new test to validate v1 and v2 behavior
1. Fixed disassembly listing for such programs - no unknown labels anymore
2. Switched some asm tests to `t.Parallel()`

TEAL: assembler error on branching behind last instruction

---

cmd/tealdbg/dryrunRequest.go
daemon/algod/api/server/v2/account.go
daemon/algod/api/server/v2/account_test.go
daemon/algod/api/server/v2/dryrun.go
daemon/algod/api/server/v2/dryrun_test.go

- Byte keys and values should be base64 encoded when represented as json
- `EvalDeltaKeyValue` values were being base64 encoded, but their keys weren't

base64 encode binary keys/values in json `TealKeyValue`, `EvalDeltaKeyValue` model

---

ledger/archival_test.go

The unit test include a redundant call to ledger.Close.
Given that the ledger is not desiged to supports that, i'm removong this call.

Remove redundant ledger.close in TestArchivalCreatables

---

ledger/ledger_test.go

The TestLedgerBlockHdrCaching unit test was conducting the test against 2000 entries. This in turn caused unrelated testing issues, which were not needed to be covered by this unit test.
Reducing the number of iterations to 128 is sufficient to provide the needed coverage and would reduce the current generated false-positives.

Relax TestLedgerBlockHdrCaching rounds count

---

ledger/accountdb_test.go
ledger/acctupdates_test.go
ledger/catchpointwriter_test.go
ledger/cow_test.go

Add a unit test for `catchpointWriter` named `TestFullCatchpointWriter`.
The test generates a random set of accounts, and initialize a database with them.
It generates a catchpoint file, and restore the file into another in-memory database using the catchup accessor.
Then, each of the original accounts are being compared to the one ended up on the in-memory database.

Add a unit test for catchpointWriter

---

test/e2e-go/cli/goal/expect/goalDryrunRestTest.exp

goalDryrunRestTest fails time to time with "Exit code: 0, expected: 1".
This PR moves an exit code check to expect/eof block as all other tests do to avoid possible race in expect.
This is fix for the test.

Fix exit code race in dryrun expect test

---

ledger/archival_test.go
ledger/notifier.go

The deadlock detection code was giving us lots of false positives when running the TestArchivalRestart and TestArchivalCreatables unit tests. Both these test have the following attributes:
1. Both are writing large number of blocks into the ledger almost at-once.
2. Both are using on disk storage.
As a result the account update tracker is attempting to make large operations, which, in turn, perform very slowly when running on travis since it uses network disk storage.
To work around that, I have disabled the deadlock detection during the runtime of these tests. To accomplish the latter without running into race condition with the `deadlock.Opts.Disable` global variable, I added a closing WaitGroup on the notifier.
Also, the `TestArchivalRestart` was not implemented correctly: writing 2000 …

Disable deadlock detection on TestArchivalRestart and TestArchivalCreatables unit tests 

---

go.mod
go.sum

The go-deadlock library which we were using was built before go 1.11, which means it did not had go-modules support.
On a separate PR, I already added go-modules support for the library, and this PR complete the cycle by tying the go-algorand repository to the go-deadlock library.

Move the go-deadlock to use go modules

---

ledger/archival_test.go
ledger/ledger_perf_test.go

In https://github.com/algorand/go-algorand/pull/1310 I missed to update the TestArchivalCreatables unit test itself.
Instead, I updated two other unit tests ( that needed this update as well ).
This is a follow up PR, addressing what was missed in #1310  as well as applying @algobolson recommendation.

Disable the deadlock detection on TestArchivalCreatables

---

ledger/acctupdates.go
ledger/catchupaccessor.go

This PR changes the formatting of the errors reported when we run into (unexpected) merkle trie add/delete issue - 
Instead of printing the following:
```
failed to delete hash '[0 2 10 225 180 83 237 205 167 133 27 115 84 225 197 100 156 173 4 243 70 109 250 128 36 70 89 174 211 3 136 249 71 157 224 106]' from merkle trie
```
It would print
```
failed to delete hash '00020a60dc5baf1440cc6148b1a837f0091acae8514f2cb92e638db88450819c7405e6c7' from merkle trie for account address WDXD7FP3P3RLOTN3IMHDO5QX3CKBYCKLRHBNQ64GL4BJE5BN3VKCQR2RGA
```
The change is not only less noisy, but also provide us with some pointers for what we need to look for when diagnosing the issue.

Improve trie failuires warning message formatting

---

data/ledger.go
data/transactions/aggregates.go
data/transactions/aggregates_test.go
ledger/blockdb.go
ledger/blockdb_test.go
ledger/ledger.go

Back in https://github.com/algorand/go-algorand/pull/944, we started encoding nil paysets and empty paysets with the same commitment. In normal operation, blocks with no transactions create a `nil` payset. The genesis block, however, commits to a payset that is empty but not nil. I noted this in the PR at the time and didn't think it was a big deal because it didn't affect catchup, but in hindsight that was silly since it introduces version-based subjectivity into what block 0 is.
This PR computes the genesis `TxnRoot` as we originally did for the genesis block. For archival nodes, it replaces block 0 with the recomputed block 0 at startup. We should remove this code after the next protocol upgrade, when we're sure that all up-to-date archival nodes have run it once.

Fix `TxnRoot` for block 0

---

daemon/algod/api/server/v2/account.go
daemon/algod/api/server/v2/account_test.go
tools/network/dnssec/testHarness.go

REST V2 models use pointers to denote optional fields, and this a bit error prone when converting
maps or arrays of native data types to appropriate arrays of model
Added tests

Do not save loop variable addresses in conversion routines

---

test/e2e-go/features/catchup/basicCatchup_test.go
test/e2e-go/upgrades/application_support_test.go
test/e2e-go/upgrades/send_receive_upgrade_test.go
test/testdata/nettemplates/TwoNodes100SecondTestUnupgradedProtocol.json

This PR includes a new e2e test to cover the acceptable of applications creation transaction before and after an upgrade.
The test cover the REST endpoint and ensures that the node rejects application transaction before the upgrade takes place, and accept the transaction once the upgrade took place.
This is an e2e test.

Add e2e upgrade test for application over REST & Gossip

---

test/e2e-go/upgrades/application_support_test.go

Fix merge issues with TestApplicationsUpgradeOver. Due to merge orders, the underlying `libgoal.MakeUnsignedAppCreateTx`  was changed without the test being updated.

Fix merge issue with TestApplicationsUpgradeOver e2e test

---

test/e2e-go/cli/goal/expect/README.md

Added to the README explanations for the `TESTDATADIR`, `TESTDIR` and `TESTFILTER` environment variables and how to use them.
Also, removed whitespace.
n/a

Added documentation for test env vars for running the expect tests

---

.travis.yml

The `sudo` key on the .travis file is no longer supported, and completely ignored.
This PR delete this deprecated line.

Remove deprecated sudo key from travis

---

shared/pingpong/accounts.go

They were failing because the TEAL version was incorrect

Fix applications pingpong test

---

cmd/goal/accountsList.go

It's not very pretty, but it matches what we do currently for assets. Here is example output:
```
[online]	VMQAA7D43Y6SZ7SJNMA6EPFEQ3DGD575OEKV4FP5EVZWSCRHKVLXZXQFZE	VMQAA7D43Y6SZ7SJNMA6EPFEQ3DGD575OEKV4FP5EVZWSCRHKVLXZXQFZE	4999999999995000 microAlgos	[created asset IDs: 4 (1234 foo), 5 (1234 bar)]	[created app IDs: 1, 2]	[opted in app IDs: 1]
```
I manually tested this change using a private network.

Add created/opted in apps to `goal account list`

---

cmd/goal/inspect.go

`goal clerk inspect` failed to work on rekeyed transactions. This PR fixes it. 
Fixes #1300

Fix a bug where goal inspect fails to process a rekeyed transaction

---

data/transactions/logic/assembler.go
data/transactions/logic/assembler_test.go
data/transactions/logic/eval_test.go

"byte 0x" produces empty byte slice and substring also can return empty slice
so it is better to be consistent and allow empty literals as well
Added test

TEAL: allow empty string literals

---

crypto/merkletrie/cache.go
crypto/merkletrie/cache_test.go
crypto/merkletrie/trie_test.go

The `pagesPrioritizationMap` was misaligned with the `pagesPrioritizationList`, which prevented the `evict()` from correctly releasing no-longer needed nodes.
Unit tests have been added to confirm fix

Fix merketrie prioritization cache

---

agreement/abstractions.go
agreement/pseudonode.go
data/pools/transactionPool.go
node/node.go

During catchup, both the agreement and the transaction pool are being informed of new blocks. The transaction pool might be processing the blocks faster than the agreement messaging works, and as a result, the agreement might request the transaction pool to assemble a block for an older round.
Currently, the transaction pool would respond with an error, which would propagate to the agreement protocol, having the latter print a warning message. This is a benign message, as it does not indicate of a concrete issue but rather a normal system operation.
To resolve that, this PR add a special error returned by the AssembleBlock to indicate that the requested block round is too old. The agreement, in turn, would check this error code and would verify that "claim" against the ledger's round. If …

Prevent warning message for block assembly when catching up

---

Makefile

Installing python doesn't install the "python" command anymore. Switch over to "python3".

Fix Makefile to work with ubuntu 20.04

---

.travis.yml

Remove specification of go version from Travis.yaml file.  Go version is now specified using `get_go_version.sh` script.  
Using PR to test running Travis builds.

Remove go version from travis.yaml file.

---

test/scripts/e2e_subs/rekey.sh

This fix avoids the issuance of rewards by keeping the receiver account below 1 algo.
python3 e2e_client_runner.py --verbose e2e_subs/rekey.sh --keep-temps

Fix failing rekey test by keeping account total < 1 algo

---

crypto/merkletrie/cache.go
crypto/merkletrie/cache_test.go
crypto/merkletrie/committer_test.go

The Merkle trie was using the `pageToNIDsPtr` map to associate in-memory cached pages of nodes with the actual nodes.
During trie rearrangements, nodes are being deleted, which could lead to deletion of entries from this map. The map was
correctly deleting the internal list object, but left it as "nil" instead of completely eliminating it from the map. Over time, this 
could result is a memory leak.
The solution is quite straight-forward. Instead of just placing `nil` value on the map when the associated page gets empty, delete the page completely.
Unit tests added to cover the relevant changes.

Eliminate nil map entries on Merkle trie cache

---

ledger/accountdb.go

listCreatablesStmt is selecting 3 columns:
"SELECT asset, creator FROM assetcreators WHERE asset <= ? AND ctype = ? ORDER BY asset desc LIMIT ?"
but the scan is expecting just 2.
rows.Scan will fail for listCreatablesStmt with the error:
sql: expected 3 destination arguments in Scan, not 2
ctype is not relevant, since it is already specified in the WHERE claws. 
Will add a test for this in the next PR

listCreatablesStmt is selecting 3 columns instead of 2

---

ledger/accountdb.go
ledger/acctupdates.go
ledger/catchpointwriter.go
ledger/catchpointwriter_test.go

The encodedAccountsRange function was becoming too slow to be used on production systems.
It's performance degraded with size of data. ( i.e. first iteration is 1ms, after 5000 iterations you could get to 60ms ).
Instead, I replaced it with a single, long living, query which iterates over all the accounts.
In order to avoid a separate go-routine, I had to make some additional handling to the call stack.
Note that this function was used both in the rebuilding o the Merkle trie as well as during the generation of the catchpoint file. Both shown substantial performance gains.
Existing unit tests were updated.

Avoid using  encodedAccountsRange and replace with a single query

---

ledger/accountdb.go
ledger/acctupdates.go

This change adds another step to the database upgrade process by triggering the vacuuming on completion of the upgrade process.
Tested and confirmed to be working manually by reviewing the log files.

Add vacuumming to the database upgrade process

---

ledger/catchupaccessor.go

Existing code was naive: it would have created a new Merkle Trie object on each catchpoint file chunk.
This approach is correct, but inefficient - the internal trie cache need to reload all the relevant pages on each iteration.
Instead of doing so, I switched to persisted Merkle Trie object, and added the changes to it. It has the benefits of a persistent cache, and perform significantly faster.
Tested manually against betanet and mainnet, and seems to be considerably faster.

Improve client-side catchpoint catchup performance

---

ledger/blockdb.go

The current code does fix the issue of having incorrect TxnRoot on block 0, however, it also write to the log file the message `initBlocksDB replaced block 0` on every startup.
To address that, I have compared the old and new headers. If they are identical, the update is not needed. Note that the bug was in the TxnRoot field, but the test cover the entire block header.
Tested manually to ensure correctness.

Avoid redundent info message for replacing block 0

---

scripts/compute_branch_deadlock_default.sh
scripts/travis/build_test.sh
scripts/travis/integration_test.sh
scripts/travis/test_release.sh

Disable the deadlock by default on master; enable only when running travis tests or setting via ALGORAND_DEADLOCK

Disable deadlock detection on master

---

cmd/goal/node.go

While writing a script to consume fast catchup data I noticed that these values were swapped.
For your review reference...
```
$ rg infoNodeCatchpointCatchupAccounts -A 1
cmd/goal/node.go
425:			statusString = statusString + "\n" + fmt.Sprintf(infoNodeCatchpointCatchupAccounts, *stat.CatchpointTotalAccounts,
426-				*stat.CatchpointProcessedAccounts)
cmd/goal/messages.go
65:	infoNodeCatchpointCatchupAccounts = "Catchpoint total accounts: %d\nCatchpoint accounts processed: %d"
66-	infoNodeCatchpointCatchupBlocks   = "Catchpoint total blocks: %d\nCatchpoint downloaded blocks: %d"
```

Fix fast catchup processed/total account values swapped.

---

catchup/service.go
catchup/service_test.go
ledger/acctupdates.go
ledger/ledger.go

Testing the algod against mainnet shown that memory utilization during catchup could be substantial.
This PR slows down the catchup when catchpoint file is being written. This would lower the memory pressure
on the accounts updater, as no additional blocks would get added.
Note that it will make a difference only on archival nodes. Non-archival nodes would behave as they do today.

Slow down catchup while catchpoint file is being written

---

daemon/kmd/wallet/driver/sqlite.go

On some slower environments `kmd` could spend over 30s in CreateWallet while holding a mutex causing the deadlock detector to panic. This decreases the time in the critical section and puts the slow crypto operations outside.
Fixes #1402 
Tested on the slow system where the problem was found. Passes test/scrits/e2e.sh which originally found the problem.

decrease mutex critical section time in kmd CreateWallet

---

cmd/pingpong/runCmd.go
shared/pingpong/config.go
shared/pingpong/pingpong.go

Add Rekeying support to pingpoing utility
In each iteration send two txns:
- from -> to with RekeyTo=to
- to -> from with RekeyTo=from and AuthAddr=to
This preserves accounts' private keys for subsequent runs
```
pingpong run -d mynet1 --randomnote=true --numaccounts=200 --run=20 --groupsize=2 --rekey=true
pingpong run -d mynet1 --randomnote=true --numaccounts=200 --run=20 --groupsize=2
```
Report the same 2300 txns per 20 sec of run time.
S1/S2/S3 are still in pending.

Add Rekeying to pingpong

---

scripts/release/build/stage/upload/run.sh

The generate releases page python script breaks if any directories are uploaded to the staging area from which we then copy to `algorand-dev-deb-repo`.  The generate script then is ran after the sync to the aforementioned bucket.
In the `releases-page` repo, run `./generate_releases_page.py`.

Exclude "beta" dir from sync to s3

---

scripts/release/test/deb/test_algorand.sh
scripts/release/test/deb/test_apt-get.sh
scripts/release/test/rpm/run_centos.sh

The legacy pipeline isn't distinguishing between stable and beta release packages. It needs to test algorand for the former and algorand-beta for the latter.
https://ci.algorand.network/job/test-packages/

Dynamically install deb package in legacy pipeline

---

crypto/merklearray/array.go
crypto/merklearray/layer.go
crypto/merklearray/merkle.go
crypto/merklearray/merkle_test.go
crypto/merklearray/partial.go
protocol/hash.go

This adds simple support for Merkle trees over dense arrays.
This will be useful in committing to our payset (so that we can have compact proofs of transactions), and for committing to online accounts (as will be needed for compact certificates).
Nothing in this PR is using this code yet, but I figured I'd ask for feedback on this, since it's reasonably small and might be useful for other things as well.

merklearray implementation

---

installer/debian/preinst

The `preinst` maintenance script was not allowing for the indexer to be install alongside an `algorand` or `algorand-beta` package.
Build the deb package doing `mule -f package.yaml package` in the root of the project directory.  This will put the package under the `./tmp/` directory, and then run the following to install `sudo dpkg -i tmp/...*.deb`.

Allow algorand-indexer to be installed alongside other packages

---

network/msgOfInterest.go
network/wsNetwork.go
protocol/tags.go

This adds an API that callers can use to cause the wsNetwork node to send MsgOfInterest messages to its peers so that peers can send additional message types not included in `defaultSendMessageTags`.
This is intended to be used by the compact cert code, so that relays use MsgOfInterest messages to request compact cert sigs, whereas regular non-relay nodes don't see compact cert sig messages.

add an API for using MsgOfInterest messages

---

data/transactions/logic/assembler_test.go

Adding test for parseStringLiteral cases \r and \\
Note: \r does not bring the cursor to the beginning of the line.
This test completes the coverage of data/transactions/logic

Adding test for parseStringLiteral cases \r and \\

---

crypto/merkletrie/cache.go
crypto/merkletrie/cache_test.go

This PR contains two changes:
1. accounting bug fix in `merkleTrieCache::loadPage`, which could lead to incorrect `cachedNodeCount` values being used. In turn, it would cause the cache to evict pages ( or not to evict pages ) regardless of the eviction target. This could lead to excessive memory consumption.
2. modify the behavior of `merkleTrieCache::evict` so that it would re-prioritize the eviction of the root node page last. Currently, the hash calculation reloads multiple pages, which could lead to a situation where a call to `Evict(true)` would cause us to evict the root element. While this won't cause any issue on it's own, reloading the root element on the next Add/Delete operation is not desired. This change would place the root element page as the last place to consider …

Fix accounting bug in page loading

---

data/pools/transactionPool.go
node/node.go

We've seen multiple warning on telemetry indicating the `AssembleBlock: ran out of time for round XXXX`.
When this happen, the node would not make a proposal, as the block assembler failed. In turn, it has the potential of leading to a network stall.
The solution to this issue spanned across two areas - prevention and recovery.
The key issue which was observed is that a single TxnGroup processing can take ( sometimes ) more then 10, 20 or 30 milliseconds. As such, it means that the iterating loop in `recomputeBlockEvaluator` and the "aborting logic" in `addToPendingBlockEvaluatorOnce` might not be the best mean to achieve accurate measuring of allocated time.
Placing a condition that wait on that short timeframe in `AssembleBlock` would randomly fails, in particular when we don't use …

Fix - avoid "ran out of time for round"

---

installer/debian/preinst

This was failing when no other algorand* packages had yet been installed.
```
$ dpkg-query --show --showformat='${Package} ${Status}\n' 'algorand*'
algorand-beta install ok not-installed
$ echo $?
0
$ dpkg-query --show --showformat='${Package} ${Status}\n' 'algorand*' | grep "install ok installed"
$ echo $?
1
```
Scenarios:
1. Tested with no previous `algorand-*` packages installed. - ALLOWED
1. Tested with previous `algorand` installed. - NOT ALLOWED if `algorand-beta`
1. Tested with previous `algorand-beta` installed. - NOT ALLOWED  if `algorand`
1. Tested with `algorand-indexer` installed - ALLOWED

Check return code of `dpkg-query` show-format query

---

tools/teal/tealcut/main.go

tealcut is a command-line tool that accepts a compiled TEAL program
and a constant bytestring.  It outputs bytes preceding and following
the constant, along with their hashes.
tealcut also allows the replacement of this bytestring with a
bytestring representing a particular number.
The main use case of tealcut is to instantiate programs that are
parameterized by some bytestring representing an integer.  For
instance, tealcut can be used to instantiate an escrow TEAL program,
bound to a particular application ID, which is then checked by that
application's program itself.
TODO

Add tealcut, a tool for splitting a TEAL program around a constant.

---

package.yaml
scripts/release/mule/Makefile.mule

I would like an end-user (or me) to be able to define a `mule` job that simply calls the `package` make target that will then first do a build if it determines that one has not been done yet.
The intent is to support the building of packages locally, i.e. via the cli, without having to open the make file to see what needs to be done to get the packages to build correctly.
`mule -f package.yaml package`

Allow mule packaging to be done without having to first explicitly call `ci-build`

---

test/scripts/e2e_subs/sectok-app.sh
test/scripts/e2e_subs/tealprogs/sectok_approve.teal

This fixes a security vulnerability where the contract-administrator
status of an address was checked after it was set.  Any address could
cause itself to be a contract administrator, regardless of whether it
were a contract administrator already.
This bugfix checks whether an application call's sender is a contract
administrator before modifying a target user's contract-administrator
status.
Thanks to @jasonpaulos for helping to find this bug.
Added test case to e2e test.

Bugfix: Reorder permission check for setting contract administrator.

---

agreement/proposal.go
ledger/apply/payment.go

Correctly return errors in agreement/proposal.go and
ledger/apply/payment.go.
Used existing tests.

Bugfix: fix error propagation at two sites.

---

cmd/goal/clerk.go
cmd/tealdbg/main.go
daemon/algod/api/server/v2/dryrun.go
libgoal/libgoal.go
test/e2e-go/cli/goal/expect/goalDryrunRestTest.exp

* Extend clerk dryrun so it can dump dryrun state object suitable for REST, tealdbg and python tests
goal clerk dryrun -t grouptxn.msgp -o dr.mspg --dryrun-dump --dryrun-dump-format=msgp
* Fix parameter validation in tealdbg
* Fix NPE in REST dryrun when a first txn in a group non-TEAL
Extended expect test for group txn

Simplify dryrunning and debugging group txn

---

cmd/algorelay/relayCmd.go
tools/network/cloudflare/cloudflare.go

This PR adds the deletion of a non-functional SRV/DNS relay entry in the service records.
This didn't used to be an issue, since relays were always only switching from non-functional to functional state. However, since relays can now become non-functional - we need an automated tool to help us removing these entries.

Add support for algorelay deleting unused SRV and DNS entries

---

ledger/catchupaccessor_test.go
ledger/ledger_test.go

Before attempting to improve the catchpoint catchup performance, we need a way to systematically test how well we perform. Running this test, produces the following output:
```
goos: darwin
Add a benchmark to test restoring from catchpoint performance.
goarch: amd64
BenchmarkRestoringFromCatchpointFile/Restore-102400-8         	  102400	     64479 ns/op
--- BENCH: BenchmarkRestoringFromCatchpointFile/Restore-102400-8
catchupaccessor_test.go:99: Last 64K	4.949638275s
BenchmarkRestoringFromCatchpointFile/Restore-204800-8         	  204800	     86044 ns/op
--- BENCH: BenchmarkRestoringFromCatchpointFile/Restore-204800-8
catchupaccessor_test.go:99: Last 64K	7.556581895s
BenchmarkRestoringFromCatchpointFile/Restore-409600-8         	  409600 …
```

Add a benchmark to test restoring from catchpoint performance

---

daemon/algod/api/server/v1/handlers/handlers.go

The documentation says that these fields are not required, but there is a parsing error if they aren't provided.
I ran the command locally with and without the fix, this is the v1 endpoint so I didn't want to spend too much time on testing.

Allow max and assetIndex to be optional

---

crypto/merkletrie/bitset.go
crypto/merkletrie/bitset_test.go
crypto/merkletrie/cache.go
crypto/merkletrie/cache_test.go
crypto/merkletrie/committer_test.go
crypto/merkletrie/node.go
crypto/merkletrie/node_test.go
crypto/merkletrie/trie.go
crypto/merkletrie/trie_test.go

This PR improves the memory consumption used by a single node in the Merkle trie implementation.
The memory pressure is roughly half compared to not having this, while the performance is roughly the same.
Convert this 
```
type node struct {
hash         []byte
children     []storedNodeIdentifier
childrenNext []byte
firstChild   byte
leaf         bool
}
```
Into this:
```
type childEntry struct {
id    storedNodeIdentifier
index byte
}
type bitset struct {
d [4]uint64
}
type node struct {
hash         []byte
children     []childEntry
childrenMask bitset
}
```
Tested against mainnet, betanet and testnet. Plus added unit tests.

Optimize Merkle trie memory consumption

---

data/basics/teal_test.go

Added tests for `EvalDelta.Equal` and `StateDelta.Equal`
`EvalDelta.Equal` and `StateDelta.Equal` are 100% covered.

Add unit tests for equal functions in teal.go

---

test/e2e-go/cli/goal/expect/goalAppAccountAddressTest.exp

From expect man page:
Both expect and interact will detect when the current process exits
and implicitly do a close.
When eof pattern is detected, there will already be an implicit close.
Closing again will throw an error like: spawn_id: spawn id exp13 not open

Removing close from eof pattern match

---

cmd/tealdbg/cdtState.go
data/transactions/logic/eval.go
data/transactions/logic/eval_test.go

Tealdbg now can show content of txn.Accounts and txn.ApplicationArgs
Addresses now as shown as standard base32 strings rather than hex-encoded blobs

Add txn.Accounts and txn.ApplicationArgs support to tealdbg

---

ledger/acctupdates.go

Calculate the accounts normalized balance when calling accountUpdates.onlineTop using the Genesis Proto rather then the current round's consensus params, so that it would align with the current values in the table.

Calculate normalized balance using genesis proto

---

cmd/algod/main.go

When Algod exit during the startup, it should return a non-zero value to indicate that there was an error.

Exit algod with a non-zero in case of a startup error

---

daemon/algod/api/server/v1/handlers/handlers.go

Return 404 instead of 500 if the transaction isn't found.

Return 404 if v1/transaction/{txid} doesn't find the txn.

---

installer/rpm/algorand/algorand.spec

Remove devtools binaries from algorand rpm package
Jenkins job.

Remove devtools binaries from algorand package (rpm)

---

installer/rpm/algorand-devtools/algorand-devtools.spec
scripts/release/build/deb/build_deb.sh
scripts/release/build/deb/package.sh
scripts/release/build/rpm/package.sh
scripts/release/mule/package/deb/package.sh
scripts/release/mule/package/rpm/package.sh

Regardless of the channel, the installer scripts are either located at `algorand` or `algorand-devtools` and DO NOT include the channel name (hence, the package name shouldn't be used to construct the path).
Jenkins job.

Fix pathing issue to installer directory

---

scripts/release/forward_gpg_agent.sh

This script was modified to implement a suggestion from shellcheck. However, changing `egrep -A` to `grep -AE` doesn't work in Ubuntu 18.04.
Verified that forward_gpg_agent.sh worked with this modification.

Bug fix - revert change to grep recommended by shellcheck

---

agreement/abstractions.go
agreement/asyncVoteVerifier.go
agreement/common_test.go
agreement/selector.go
agreement/vote.go
agreement/voteAggregator_test.go
ledger/acctupdates.go
node/impls.go

When an extremely old vote is received, the verifier will not be able to fetch the membership and will mark it as ProposalMalformed and cause a WARN log. This change downgrades that to a DEBUG and marks it as ProposalFiltered by using the cancelled tag.
Resolves https://github.com/algorand/go-algorand/issues/914
Wrote additional unit test that simulates the described scenario to test this change

Vote validation error refactor

---

data/ledger.go
data/ledger_test.go

This PR adds a cache for the data.Ledger for the `Circulation` and `Seed` calls.
The goal of this PR is to reduce the contingency pressure on the downstream accounts update lock.
The high-level plan is to eventually eliminate this code, and make sure that the agreement service is sufficiently smart to perform a similar logic.

Cache the most recent Seed/Circulation calls to reduce pressure on ledger

---

config/consensus.go
test/e2e-go/cli/goal/expect/catchpointCatchupTest.exp
test/e2e-go/features/catchup/catchpointCatchup_test.go
test/e2e-go/features/transactions/accountv2_test.go
test/e2e-go/upgrades/application_support_test.go
test/e2e-go/upgrades/rekey_support_test.go
test/e2e-go/upgrades/send_receive_upgrade_test.go

Since we are now using AgreementFilterTimeout as a consensParam, we can remove the algolambdamsec environment variable from the codebase and eliminate that tech debt.
Run unit tests again to make sure functionality still the same

Deprecate algolambdamsec environment variable

---

cmd/goal/application.go
cmd/goal/interact.go
data/basics/address.go
test/e2e-go/cli/goal/expect/goalExpectCommon.exp

The goalAppAccountAddressTest was randomally failing. The culprit was the heuristicFormatStr which was testing to see if the string is unicode printable before printing it out. To address this issue, I made two modifications by adding steps 1 and 2 below :
1. A byte array that corresponds to a checksumed address, would be printed as address.
2. A json formatteble string, would be printed as is.
3. A byte array that corresponds to a non-checksumed address, would be printed as address
4. The string would be printed as is.
Note that the checking if the byte array was printable was misleading : it was checking if it's a valid unicode string, instead of checking if it's a json string. I think that we might want to add another option for forcing a specific bytes output formatter, but that's …

Fix heuristicFormatStr logic

---

rpcs/txService.go
util/bloom/bloom.go

The http read size limiter for the tx sync was not configured correctly, causing failures when bloom filter requests reached or were near capacity.
The allowed body buffer read size should have been 8 bytes longer.
Use the performance system, where the issue was found as a test bed.

Correctly account for bloom filter binary marshaling size

---

scripts/release/build/deb/build_deb.sh

The current debian package will incorrectly package the testnet genesis file. This fix addresses that issue.
Compile a release package and verify the genesis version.

Bug fix - use DEFAULT_RELEASE_NETWORK genesis file in debian package

---

catchup/catchpointService.go
catchup/httpFetcher.go

Prior to this PR, a failed block download during `processStageBlocksDownload` would not get logged. Instead, it would retry to download the block following the configured `cs.config.CatchupBlockDownloadRetryAttempts` limits.
This PR adds an info logging in case of such a failure. The intent of this PR is to provide the node runner with the information about the download error so that she would be able to take concrete actions around that specific failure.

Add detailed error logging in case of failed blocks download

---

network/requestLogger_test.go
network/wsNetwork.go
network/wsNetwork_test.go
network/wsPeer.go

Avoid ReadError event & log entry in case the other side gracefully closed the websocket.
This is not an error, and should not be marked as such. Instead, we'll be using a new reason called 'DisconnectRequest'.
Unit test added
This PR would provide a partial fix for #1543. Additional changes would be required.

remove expected ReadError events

---

installer/debian/algorand/postinst
installer/debian/algorand/preinst

This tests the following scenarios:
1. MainNet debian user who upgraded to 2.1.5, and was moved to TestNet accidentally
2. TestNet debian user who upgraded to 2.1.5
3. MainNet debian user who installed 2.1.5 between Monday 2:30pm and Wednesday 12:00pm, and changed their genesis.json to MainNet
4. TestNet debian user who installed 2.1.5 between Monday 2:30pm and Wednesday 12:00pm
Build package locally and run through each of the tests outlined above.

Hot fix for fixing bad genesis file on 2.1.5 install

---

installer/debian/algorand/postinst
installer/debian/algorand/preinst

1. Other
* Bug Fix - attempt to fix bad genesis file on 2.1.5 debian install
Standard release testing.
For rel/stable:
- clean install 2.1.4, upgrade 2.1.5, upgrade 2.1.6 (scenario #1)
- verify mainnet config (after 2.1.4)
- verify testnet config (after 2.1.5)
- clean install 2.1.4, testnet config, upgrade 2.1.5, upgrade 2.1.6 (scenario #2)
- verify mainnet config (after 2.1.4)
- implement testnet config
- verify testnet config (after 2.1.5)
- verify testnet config (after 2.1.6)
- clean install 2.1.5, mainnet config, upgrade 2.1.6 (scenario #3)
- verify testnet config (after 2.1.5)
- implement mainnet config
- verify mainnet config (after 2.1.6)
- clean install 2.1.5, upgrade 2.1.6 (scenario #4)
- verify testnet config (after 2.1.5)
- verify testnet config (after 2.1.6)
- clean install …

Hot fix for fixing bad genesis file on 2.1.5 install (#1553)

---

test/e2e-go/cli/goal/expect/goalExpectCommon.exp

Extend timeout for the Expect common function `WaitForAccountBalance` to wait for the account balance to reflect the expected amount.  Changed from 20 to 40 seconds.  
Ran Integration tests.

Extend expect timeout when checking account balance

---

util/bloom/bloom_test.go

In past PR, I added a new function BinaryMarshalLength without providing a unit test to confirm it's correctness. This PR adds the missing unit test.
This is a unit test

Add a unit test to confirm BinaryMarshalLength correctness

---

test/e2e-go/cli/goal/expect/goalNodeTest.exp

Expect test was closing the process connection instead of letting it end on its own. In turn, it lead to incorrect usage of CheckProcessReturnedCode, which resulted in random failure. Solution is to properly wait for process to terminate and examine the return code without calling close.
Use travis to confirm a good fix.

Fix random failure in goalNodeTest.exp

---

README.md
scripts/buildhost/README.md

A Travis token was included for a build status image, but this token is not needed for open source repositories.
Just ensure build image continues to work for README.md and is removed from buildhost/README.md.

Remove Travis token, which is not needed for open source repos

---

test/e2e-go/cli/goal/expect/goalAppAccountAddressTest.exp

The test was closing the process after receiving the expected error message. Closing the current process was causing an incorrect error code retrieval. Instead of closing it, we should just leave it alone and wait for the expected eof event.
This is a test; let travis execute that and confirm it's working.

bugfix: fix random failure in goalAppAccountAddressTest.exp

---

data/pools/transactionPool.go
data/pools/transactionPool_test.go

The checkPendingQueueSize function is called per new transaction group that is being added to the transaction pool. Unfortunately, it tests whether a single entry can be added to the transaction pool, whereas it should have checked wether all the transaction included in the incoming transaction group would be able to fit into the transaction pool.

bugfix: correct accounting of transactions in checkPendingQueueSize

---

catchup/fetcher_test.go

Remove dead test code that had buggy statements in it (that were unexecuted).

cleanup buggy dead code

---

docker/build/cicd.ubuntu.Dockerfile
package-sign.yaml
scripts/release/mule/Makefile.mule
scripts/release/mule/package/deb/package.sh
scripts/release/mule/sign/sign.sh

Simplify package signing by only having one task that signs all build artifacts instead of delineating them by type.
Note that there is some churn in `scripts/release/mule/package/deb/package.sh` because of the removal of the (unnecessary) brackets around the env vars, but it makes the script more readable (in my opinion).
`mule -f package-sign.yaml package-sign`

Simplify mule signing task

---

network/wsNetwork.go
network/wsNetwork_test.go
network/wsPeer.go

Avoid logging raw data received from network in case of an error. Instead, filter the incoming data and ensure it's ASCII before logging it.
Note that unlike what mentioned in the issue, we were not really writing raw data to the log file directly. In all cases, the data was properly encoded as json strings. This PR ensure that we don't attempt to encode a non-ASCII characters into json strings.
Unit tests added.
Resolves #1568

add ascii filtering for remote requests logged data

---

package.yaml
scripts/release/mule/README.md
scripts/release/mule/package/deb/package.sh
scripts/release/mule/package/docker/package.sh
scripts/release/mule/package/rpm/package.sh
scripts/release/mule/test/tests/post/verify_genesis_file.sh
scripts/release/mule/test/tests/post/verify_package_binaries.sh
scripts/release/mule/test/tests/post/verify_package_string.sh
scripts/release/mule/test/tests/pre/verify_control_files.sh

Update `mule` docs for the new pipeline.
The changes in the other scripts are to reflect what appears in the docs, i.e.:
- `ARCH` becomes `ARCH_TYPE`
- `VER` or `FULLVERSION` becomes `VERSION`
Also, futzed with jobs in `package.yaml`.
n/a

Update mule docs for new pipeline

---

node/node.go

Adding a new mutex to AlgorandFullNode so that OnNewBlock wouldn't be blocked by oldKeyDeletionThread during catchup.

Add syncMu to AlgorandFullNode OnNewBlock

---

daemon/algod/api/server/common/handlers.go

According to algod.oas2.json, the `/health` endpoint should return `application/json`, however that endpoint does not set the `Content-Type` header.
This became an issue when running tests for the Javascript SDK in the browser. Our HTTP request library behaves differently in the browser when the `Content-Type` is not JSON, which led to a bug there.
I don't imagine this change will break any consumers of the API, since the endpoint always returns `null`, which is valid JSON.
I'm not aware of any tests specifically for the REST endpoints. If there are, let me know and I'll add a check there.

Set content type header for health endpoint

---

daemon/algod/api/server/v1/handlers/handlers.go
daemon/algod/api/server/v2/handlers.go
ledger/acctupdates.go
ledger/acctupdates_test.go
ledger/catchpointwriter_test.go
ledger/eval.go
ledger/ledger.go

Extend the existing implementation of account updates to provide already-available information for round range validity for account data queries. The long term goal here is to take advantage of that in the agreement implementation so that the number of queries that would reach the ledger would get reduced.
The change in a nutshell:
The function `accountUpdates. Lookup` got broken into
`LookupWithRewards(rnd basics.Round, addr basics.Address) (data basics.AccountData, err error)`
and
`LookupWithoutRewards(rnd basics.Round, addr basics.Address) (basics.AccountData, basics.Round, error)`
The latter includes a validity round as the second return value.
Unit tests were extended to cover the changes.

extend account lookup to include validity range

---

cmd/goal/account.go
test/e2e-go/cli/goal/expect/goalAccountInfoTest.exp
test/e2e-go/cli/goal/expect/goalExpectCommon.exp
test/e2e-go/cli/goal/expect/limitOrderTest.exp

The description of `goal account balance` says it displays balances for algos and assets, but actually only shows algos. I have corrected the description and added a new command that shows information about an account's assets and applications, `goal account info`.
I have also removed the asset information that `goal account list` currently reports. Instead of having asset balances always listed, I have added the flag `--info` to `goal account list` to generate this same report as `goal account info` for each account in a wallet.
Examples:
```
$ goal account info -a 5K6OH2HKK3HORMIAQT7JYCUUYJTWS5KQ4AL7ITPI2SOCBKA7LMEEJYT5LA -d data
Created Assets:
ID 2678221, A-Coin, supply 1000 AC
ID 2678222, <unnamed>, supply 1000 BC
ID 2678223, C-Coin, supply 1000 units
ID 2678224, D-Coin, supply 10.00 …
```

Add goal account info command

---

cmd/netgoal/network.go
netdeploy/remote/buildConfig.go
netdeploy/remote/deployedNetwork.go

Allow `netgoal build` to more generally fill in template values.
`netgoal build ... -v SomeConfigField=foo` will replace `{{SomeConfigField}}` in template files with `foo`
I have used this to construct a test cluster that configures an experimental config.json field I hacked into a development `algod`

Netgoal general templates

---

cmd/tealdbg/cdtdbg.go
cmd/tealdbg/debugger.go
cmd/tealdbg/debugger_test.go
cmd/tealdbg/main.go
cmd/tealdbg/server.go
cmd/tealdbg/server_test.go
cmd/tealdbg/webdbg.go
test/e2e-go/cli/tealdbg/expect/tealdbgSpinoffTest.exp

Use:
$ tealdbg debug -q
$ curl -X http://localhost:9293/spinoff --data-binary @dr.msgp
The /spinoff handler returns text/plain and
- HTTP 200 and ws://abc/sessionid in case of success
- HTTP 400 and error text in case of error
An URL in response body (ws://abc/) can be used for interactive debugging
with Chrome DevTools or for scripted debugging with CDT proto 1.1
A race condition is also fixed: dbg state access in the evaluator and in debugging core go-routine.
A possible deadlock on start is fixed: attempt to resume execution before initialization completed.
Added e2e test

tealdbg: listen for upcoming spinoff connections

---

catchup/pref_test.go
catchup/service.go
catchup/service_test.go

The `catchup.Service.sync` function was incorrectly setting/resetting the `syncStartNS` in the case of the catchup was paused due to a catchpoint file being written.
The PR changes the function logic as follows :
- When the function starts, it sets the `syncStartNS` only if it's zero. That allows as to "resume" previously suspended catchup.
- When the function ends, it tests to see if the catchup termination was due to catchpoint file being written. If so, it doesn't reset the `syncStartNS`.
Also, the PR separate the handling of an agreement-derived `sync()` from a non-agreement derived `sync()`. That simplify the logic of the `sync()` function, and defer the agreement-logic to be implemented in `syncCert()`.
Resolves #1529

Ensure syncStartNS is managed correctly across catchpoint file writing

---

data/transactions/logic/assembler.go
data/transactions/logic/assembler_test.go

Modify the error messages for parseIntcblock to distinguish fro, parseBytecblock
None

Refactor parseIntcblock

---

test/muleCI/mule.yaml

Set TRAVIS_BRANCH env var in jenkins mule agents so that compute branch will be set correction. This needs to be done because the full git refs aren't pulled by the jobs. Reusing the TRAVIS_BRANCH env var so that we do not have to change any scripts, but we may want to consider revising later on.

Set TRAVIS_BRANCH env var in jenkins mule agents

---

scripts/compute_branch_network.sh

Since jenkins doesn't pull the full git tree with refs, this will have compute_branch_network use the current branch instead of the branch parent when that rev parse fails

Default to branch name when branch parent fails

---

scripts/compute_branch_network.sh
scripts/release/mule/package/deb/package.sh
scripts/release/mule/package/rpm/package.sh

The RPM packaging script wasn't pulling the right network due to hardcoding. Modified this and the deb script to use the passed branch to calculate the correct network. Also modified the compute branch network script to return betanet if passed rel/beta.
Ensure packaging pipeline selects correct networks for packages.

Fix computed network for packaging

---

cmd/goal/account.go
cmd/goal/accountsList.go
cmd/goal/asset.go
test/e2e-go/cli/goal/expect/goalAssetTest.exp

Asset names can have control characters, which will be displayed to the terminal when run commands such as `goal asset info`. This allows malicious asset names to delete terminal input and / or print arbitrary input.
Expect test

Avoid printing control characters for displaying assets

---

scripts/release/mule/package/deb/package.sh

I missed a variable that needed to be added to the loop that packages all of our linux artifacts. This change places the file in the correct directory
I ran a build/package and saw that it's not in the correct path

Fix build_status path in packaging

---

scripts/release/mule/sign/sign.sh

Improved the signing shell script in the following ways:
1. Fixed gpg warning by setting correct permissions in the docker container.
1. Instead of assuming the build status file is present, check for it first.
`mule -f package-signing package-signing`

Harden mule signing task

---

scripts/release/mule/README.md
scripts/release/mule/sign/sign.sh
scripts/release/mule/test/test.sh
scripts/release/mule/test/tests/pre/verify_control_files.sh

Change rpm package file to match rename.
`mule -f package-sign package-sign`

Change rpm package file to match rename

---

scripts/release/mule/README.md
scripts/release/mule/sign/sign.sh
scripts/release/mule/test/test.sh
scripts/release/mule/test/tests/pre/verify_control_files.sh

This reverts commit 450fd8c7984528070fc412aa322af304b54c2a65.
While we need to change the arch type for other reasons, we do not need to rename the RPM. A separate commit is reverting the name change, so this is reverting the related changes.
Standard release testing.

Revert "Change rpm package file to match rename (#1666)"

---

package-upload.yaml
scripts/release/mule/sign/sign.sh

This supports multiple OS and ARCH by downloading assets recursively from s3.  It then will determine multiple OS by inspecting the direct child directories of `tmp/node_pkgs` to determine how to proceed.
Assets are separated by ARCH as usual, i.e. tmp/node_pkgs/OS/ARCH, but when uploaded to staging they all go in the same object (flat directory structure).
`mule -f package-sign.yaml package-sign`
`mule -f package-upload.yaml package-upload`

Support multiple OS and ARCH for signing

---

ledger/acctupdates.go
ledger/cow.go
ledger/cow_test.go
ledger/error.go
ledger/eval.go
ledger/ledger.go
ledger/txtail.go
ledger/txtail_test.go
test/scripts/e2e_subs/keyreg-teal-test.sh

Convert isDup to checkDup and move error object generation into checkDup so that we can differentiate between txid duplicate and txlease collision.
Update existing unit tests and add new one.
resolves #1637

Separate the error message for duplicate txn id and lease

---

cmd/goal/messages.go
daemon/algod/api/client/restClient.go
test/e2e-go/cli/algoh/expect/algohTimeoutTest.exp
test/e2e-go/cli/goal/expect/goalNodeConnectionTest.exp

Update error message to be more informative when the libgoal is failing to connect to a node with 401 error.
New error would look like this
```
Cannot contact Algorand node: Unauthorized request to `http://127.0.0.1:5160/v2/status` when using token `d1187151e420f660573403f2068c0948659e4eb9f4c9ecc17d38e72665179d1b` : {"message":"Invalid API Token"}
```
instead of
```
Cannot contact Algorand node: HTTP 401 : {"message":"Invalid API Token"}
.
```
Update existing test and add a new one.

Update goal error message for unauthorized access

---

test/scripts/e2e_subs/e2e-app-cross-round.sh
test/scripts/e2e_subs/tealprogs/cross-round.teal

For upcoming ledger update we need to coin current TEAL behavior for key value store:
- deletion of non-existing keys is no-op
- reading non-existing keys does not fail and returns zero/empty value
- values are preserved between rounds
- opted_in works during OptIn and after
This is a test

Add e2e test for LegderForLogic

---

cmd/goal/asset.go

Fix some goal asset documentation

Better 'goal asset' help documentation.

---

ledger/acctupdates.go
ledger/acctupdates_test.go
ledger/ledger.go
rpcs/ledgerService.go

The catchpoint file serving used to have a hard-coded timeout for all catchpoint file requests. This is sub-optimal, since large catchpoint files would be served over longer period of time.
This PR dynamically adjust the timeout based on the file size, taking advantage of the sizing information we already store in the database, and passing it upstream.
Unit tests updated.

Dynamically adjust catchpoint file serving timeouts based on file size

---

Makefile

Exported environment variables are not propagated to child processes while the script is being evaluated and variables resolved. This is the normal behavior of `make`.
This causes, for e.g., `go list` execution while resolving variables like `UNIT_TEST_SOURCES` to receive the original `GOPATH` variable instead of the modified at the beginning of the script.
On the other hand, MinGW/Windows also requires to add delimiters or concat multiple command with the `&&` operator for actions executed with `$shell`
The fix ensures correct variables are passed down and also, on Windows, it prevents dependencies to be installed outside the `MSYS2` box if Go is installed outside `MSYS2` environment too.
The example makefile below shows the issue. You can observe the first `RESULT` does not include the …

Env variables while make execution list is created

---

go.mod
scripts/configure_dev-deps.sh

Fix a build problem by specifying version 0.25.0 of the go swagger module.  The latest released version is stricter and breaking the build.  
Tested with scripts/configure_dev-deps.sh to ensure that the correct version is installed.

Specify swagger version v0.25.0 to fix build.

---

Makefile
go.mod
scripts/configure_dev-deps.sh

Most of Windows binaries depends on the `MINGW` shared `pthreads` library. This addition copies it to the output directory on Windows builds.

Static linking in Windows executables

---

ledger/acctupdates_test.go
ledger/catchpointwriter.go
ledger/catchpointwriter_test.go

This PR improves the speed of the catchpoint file writer; it parallelize the gzip file writing with the account database reading.
Existing tests already cover the functional portion.
| Number of accounts   |     Before the change      |  With the change | Performance gains |
|:----------:|:-------------:|:------:|:------:|
| 6,000,000 |  22 seconds | 13 seconds | +90% |

Write the catchpoint file in parallel of reading from the database

---

shared/pingpong/accounts.go
shared/pingpong/pingpong.go

Improve apps support in pingpong:
1. Add apps min balance requirements into required balance calculation, similar to assets
2. Use SuggestedFee for accounts funding to compete with pending transactions in the pool
Checked against local network.

Add applications to min balance requirements calculation

---

test/e2e-go/cli/algoh/expect/algohTimeoutTest.exp

Fix error running algohTimeoutTest.exp by providing sufficient time for the network to start.
Ran make integration and testing on Travis with PR.

Fix intermittent  failure of algohTimeoutTest.exp 

---

data/transactions/logic/assembler.go
data/transactions/logic/assembler_test.go
data/transactions/logic/backwardCompat_test.go

Previously, we rarely reported line numbers when reporting errors
during assembly.  When we did, we reported them in a strange
way (filename, followed by two colons, then line number, then message
with no colon between line number and the message).
Now line numbers are always reported, and they use a more standard
format:
filename.teal: ##: error message
This makes it much easier to integrate `goal clerk compile` output
into other tools.  I've created an emacs TEAL mode that highlights
errors using this output, and a vscode module would probably be
similarly easy.
All existing assembler unit tests pass (two were changed because they depended on the line number following the colon).  Most were also augmented to check that the proper line number was reported.

Consistently report line numbers in TEAL error messages.

---

config/version.go

There's an extra newline at the end of `goal -v` which looks weird in one of my scripts. In general I think these sort of helper functions to leave the formatting to the caller, which it is in this case where it adds a 2nd newline.

Remove extra newline from version output.

---

daemon/algod/api/server/v2/dryrun.go
test/e2e-go/cli/goal/expect/goalDryrunRestTest.exp
test/scripts/e2e_subs/tealprogs/app_optin_put.teal

Current dryrun implementation manages `Balances` interface by itself so it also needs to process app opt-in transactions.
New e2e test added

Implement opt-in in dryrun

---

cmd/opdoc/opdoc.go
data/transactions/logic/README.md
data/transactions/logic/README_in.md
data/transactions/logic/TEAL_opcodes.md
data/transactions/logic/assembler.go
data/transactions/logic/assembler_test.go
data/transactions/logic/opcodes.go

This PR addresses inconsistency in the spec where operands pushing order is different from return values order.
There is no changes in TEAL evaluation so that no protocol upgrade is required.
Corresponding conning to the spec is https://github.com/algorandfoundation/specs/commit/21adc34b722ff365076b7e83a797190e7f99d6a2
Please note, the consensus protocol version is pointing to the not up-to-date spec https://github.com/algorandfoundation/specs/releases/tag/August2020-TEALv2 that includes only Rekey but not applications.
* app and asset getters return a pair
* order in opcode specification was "top-left"
* type check expects "bottom-left" order
New test added

TEAL: fix return type check in assembler

---

config/config.go
config/config_test.go

The `DNSBootstrapArray` function is expected to return a list of the DNS bootstrap entries. Internally, it converts the config file DNSBootstrapID using a list of DNS bootstrap entries. However, in the case of having the `DNSBootstrapID` set to an empty string, the function would also return an array containing an empty string.
The above behavior, in turn, trigger a downstream failure when searching for the telemetry SRV records.
Update a unit test to cover this use case.

Fix DNSBootstrapArray returning empty strings

---

daemon/algod/server.go
test/e2e-go/cli/algoh/expect/algohExpectCommon.exp
test/e2e-go/cli/algoh/expect/algohTimeoutTest.exp
test/e2e-go/cli/goal/expect/catchpointCatchupTest.exp

TestAlgohWithExpect constantly fails on arm64, this PR addresses it.
* Make Abort to cleanup
* Ensure cleanup is done on errors
TODO: figure out why node startup takes longer than expected.
This is a test enhancement PR

Fixes to algoh timeout e2e test

---

test/e2e-go/cli/algoh/expect/algohExpectCommon.exp
test/e2e-go/cli/algoh/expect/algohTimeoutTest.exp

Spawned algoh returns too fact, and despite the fix for `goal node start` startup code the test still fails:
```
algoh startup successful
spawn goal node wait -d /home/ubuntu/go/src/github.com/algorand/go-algorand/tmp/out/e2e/92019-1606765255748/algohTimeoutTest/algod/root/Node -w 61
Cannot contact Algorand node: open /home/ubuntu/go/src/github.com/algorand/go-algorand/tmp/out/e2e/92019-1606765255748/algohTimeoutTest/algod/root/Node/algod.token: no such file or directory
```
Added a file waiter for `algoh` startup.
This is test fix

Fix a race in arm test in algoh startup and algod.* files creation

---

test/e2e-go/cli/goal/expect/goalAssetTest.exp

The expect test had few bugs; all of the following bugs were addressed : 
* Missing wait for round 1 before sending transaction. This is required since nodes at startup might take a short while before network start making progress. We need network to make progress so that the timeout on the subsequent command would have some known value.
* The asset create should have called with expect instead of exec so that we can monitor it's output.
* The asset info calls should have been tested for negative return value.
* The network should have been stopped at the end of the test.
* In case of an error, the test was outputting "goalFormattingTest" message instead of suggesting the correct test name ( i.e. goalAssetTest )

Fix goalAsset expect test

---

scripts/release/test/deb/testDebian.exp
test/e2e-go/cli/goal/expect/basicGoalTest.exp
test/e2e-go/cli/goal/expect/doubleSpendingTest.exp
test/e2e-go/cli/goal/expect/goalExpectCommon.exp

Fix the following issues with the expect tests:
1. ::AlgorandGoal::DeleteAccount was completely bogus.
2. The doubleSpendingTest.exp was not testing for expected failure in case of double spending.
3. The following functions were not waiting for execution termination, nor testing exit code:
a. GetAccountAddress
b. GetAccountBalance
c. AccountTransfer
d. WaitForAccountBalance
e. AssetTransfer
f. CreateAssetTransfer
g. AssetFreeze
h. AssetLookup
i. TealCompile
j. TealCompileSign
These are tests. With these changes, the ARM64 tests finally [passes](https://travis-ci.com/github/algorand/go-algorand/builds/206467390).

Fix various bugs in expect tests

---

tools/network/dnssec/config.go
tools/network/dnssec/config_unix.go
tools/network/dnssec/config_unix_test.go
tools/network/dnssec/config_windows.go
tools/network/resolveController_test.go

Use GetNetworkParams to get list system DNS servers on Windows.
The main issue with the implementation it relies on the fact `GetNetworkParams` allocates list of `IP_ADDR_STRING` for `DnsServerList` field directly after the input struct. In the same time it is a part of interface - `FIXED_INFO` has a fixed size across versions (no version or size field) but the API accepts size of allocated memory region for `FIXED_INFO` and overlay.

Get system DNS on Windows

---

test/e2e-go/cli/goal/expect/catchpointCatchupTest.exp
test/e2e-go/cli/goal/expect/goalExpectCommon.exp

The test was running a go source code directly. While there is nothing wrong with that, it doesn't allow us to separate the compilation time from execution time.
This is. a test

Improve catchpoint catchup expect test

---

ledger/catchupaccessor.go

When the `CatchpointCatchupAccessorImpl.processStagingBalances` attempts to write the staged changes to disk, it's doing that in parallel : writing the accounts data, the assets and the staging hashes.
On test systems which use in-memory database, we have a shared-lock that prevents more than a single writer. This creates writing conflict which doesn't exists in disk writer.
To work around that limitation, when using an in-memory database, we'll be waiting for each of these writers to complete their work before moving to the next one.
The TestFullCatchpointWriter test covers this issue.

Fix bug revealed by TestFullCatchpointWriter

---

package-deploy.yaml
scripts/release/mule/deploy/rpm/deploy.sh

This removes uploading to a now-obsolete S3 location.  Also, `mule` needs to use a different image for doing the docker publishing, one that has docker pre-installed.
Run the respective `mule` commands.

Minimal bug fixes for latest package deployment

---

data/pools/transactionPool.go
data/transactions/verify/txn.go
data/transactions/verify/txn_test.go
ledger/eval.go
ledger/ledger_perf_test.go
ledger/ledger_test.go

Our existing code was verifying the transactions in parallel with the insertion to the evaluator, but that won't fully utilize the host computational abilities. To push it to the end, we need to break the transaction verification into subsets and parallelize the verification.
This is the first PR, which would handle the verification parallelization. The subsequent PR would ensure that we don't revalidate the same transaction coming from two different proposals, regardless if the transaction appear in the transaction pool or not.
Added unit test to verify changed code correctness.
Testing the performance gains between running `verify.TxnPool` vs using the new `verify.PaysetGroups`:
| Transaction Count | Before ( serialized ) | After ( parallelized ) |
|:--:|:--:|:--:|
|1 (amortized) …

Parallelize proposal transactions signature verification

---

catchup/service.go
network/rateLimitingTransport.go
network/wsNetwork.go

When trying to perform a catchup from a single host, the following error comes up:
```
dial tcp 127.0.0.1:8088: can't assign requested address
```
The cause of this is that GO runtime runs of out connection. When doing so, it creates new one. And the new connection that was created has a system-wide timeout. The solution for that is to increase the number of MaxIdleConnsPerHost to the expected number of concurrent requests. 
Secondly, once having that solved, the catchup started working fast. In fact, it was working so fast that the accounts update could not keep up, causing the memory utilization to grow up and the "dbatomic" to report slow flushing performance.
To resolve that, we need to hold off newly fetched block until the queue isn't too large. Once we have that, it would be safe …

Fix catchup concurrently from a single host

---

test/e2e-go/cli/goal/expect/goalExpectCommon.exp

Our expect unit tests were not waiting for the goal command to exit when starting and stopping a network.
As a result, some network starting failures were ended up reported incorrectly as non-responsive network by other commands.

Wait for EOF on StartNetwork/StopNetwork and test status correctly

---

.travis.yml

The build always seems to fail with intermittent errors. See if adding `travis_retry` helps.

Add travis_retry to build and test commands in case of random failures.

---

cmd/goal/clerk.go
cmd/goal/inspect.go
cmd/goal/multisig.go
cmd/netgoal/network.go
cmd/pingpong/runCmd.go
cmd/tealdbg/debugger_test.go
cmd/tealdbg/local.go
daemon/algod/api/server/v2/dryrun.go
daemon/algod/api/server/v2/dryrun_test.go
daemon/algod/api/server/v2/handlers.go
daemon/algod/api/server/v2/test/handlers_test.go
data/pools/transactionPool_test.go
data/transactions/logic/assembler.go
data/transactions/logic/assembler_test.go
data/transactions/logic/backwardCompat_test.go
data/transactions/logic/debugger_test.go
data/transactions/logic/eval.go
data/transactions/logic/evalStateful_test.go
data/transactions/logic/eval_test.go
data/transactions/logic/fields.go
ledger/archival_test.go
ledger/ledger_perf_test.go
shared/pingpong/accounts.go
test/e2e-go/features/transactions/accountv2_test.go
test/e2e-go/upgrades/application_support_test.go

Previously, we used the usual Go convention of returning an error to
the caller throughout assembly, as soon as they occurred.  This meant
that assembly failed, as a whole, on the first bad line.  This model
also didn't work well for warnings, because they did not have the
context to do good reporting (they did not know the filename, for
example), but had no way to pass the warning up to the caller who did
have the info (as errors did).  So this change also allows warnings to
report the file and line, for use by external tools.
The change is to accumulate errors and warnings in the OpStream
structure, rather than return immediately (or report immediately, in
the case of warnings).  After assembly the warnings and errors are
reported to stderr, and a summary error is used in Go to signal …

Show all errors, not just the first, when compiling TEAL.

---

agreement/certificate.go
ledger/acctupdates.go
ledger/acctupdates_test.go

When we run catchup, we often attempt to persist multiple rounds in a single sqlite transaction. When doing so, we were iterating throughout the rounds we were attempting to update and flushing all the deltas for each individual round.
While this work correctly, it's also not the most efficient, since we are updating the same account multiple times. To address that issue, this PR compact the deltas into a single map, which corresponds to the entire change set across the updated rounds range.
Unit test and benchmark added. Ran a test against mainnet and it seems to be working correctly with roughly 30% performance increase.

Compact accounts deltas before persisting to disk

---

ledger/accountdb.go
ledger/accountdb_test.go
ledger/acctupdates.go
ledger/acctupdates_test.go

This PR is a followup to the previous compact deltas PR. It moves the accounts & creatables flush counters into the compact deltas data structures, allowing to perform the counting in a single pass.
Unit tests were updated

Refactor account updates consistency checking 

---

ledger/acctupdates.go
ledger/acctupdates_test.go

Convert the catchpointWriting from a channel to an atomic variable. In the past, we used to have a value in having this as a channel, however, this is no longer the case. I have converted this to an atomic variable to improve code simplicity and readability.
Unit tests were updated.

Convert the catchpointWriting from a channel to an atomic variable

---

network/peersheap.go

Removing the wsPeer object pointer from the peers list would allow it to be recycled.
The original code was creating a sub-slice and not removing the entry from the underlying array.
Since the peer was left on the underlying array, it would not get GC'ed.
Existing tests confirms correct behavior.

bugfix: Network peers list memory leak

---

catchup/ledgerFetcher.go
cmd/catchpointdump/database.go
cmd/catchpointdump/file.go
cmd/catchpointdump/net.go
util/watchdogStreamReader.go

*  Update catchpointdump utility to have progress bars, which makes it more user friendly.
```
[ Done ] Downloaded http://r-sn.algorand-mainnet.network:4160/v1/mainnet-v1.0/ledger/5yc1s
[ Done ] Saved ./mainnet/r-sn/10000000.tar
[ Done ] Loaded
[ Done ] Dumped
[········▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪················] Downloading http://r-zn.algorand-mainnet.network:4160/v1/mainnet-v1.0/ledger/5yc1s ... 409 MB
```
*  Delete temporary ledger database files before and after use to ensure no leftovers from previous iterations.
*  Fix long database atomic operation warning message.
Moved the `WatchdogStreamReader` from `catchup` package to the `util` package.

Update catchpointdump utility to have progress bars

---

catchup/catchpointService.go

Incorrect block download retry accounting during fast catchup. The existing code was counting successful block retrieval as an retry attempt, which would "exhaust" the `CatchupBlockDownloadRetryAttempts` before the catchup is complete, causing the fast catchup to fail in case the `CatchupBlockDownloadRetryAttempts` was set too low.
The workaround of this is to set the `CatchupBlockDownloadRetryAttempts` to a value that is higher by 1000 than then number of desired attempts count.
Tested by running fast catchup and observing the failed attempts logs.

bugfix: incorrect block download retry accounting during fast catchup

---

cmd/goal/clerk.go

For the `goal clerk sign`, it would perform the following:
1. Group the transactions from the input file according to their Group field.
2. When using a logic signature, create a verification GroupContext and verify each transaction according to it's location within the group.
3. Retain the original ordering of the groups, based on the first transaction from each of the transaction groups.
For the `goal clerk dryrun`, it would perform the following:
1. Add GroupIndex and TxnGroup to the eval params.

Pass transaction groups correctly to logicsig evaluator

---

agreement/bundle_test.go
agreement/certificate.go
agreement/demux_test.go
agreement/fuzzer/tests_test.go
agreement/vote_test.go
crypto/merkletrie/node.go
daemon/algod/api/server/v1/handlers/handlers_test.go
data/basics/userBalance_test.go
data/bookkeeping/encoding_test.go
data/ledger.go
data/pools/transactionPool_test.go
data/transactions/logic/evalStateful_test.go
data/txHandler.go
ledger/eval.go
ledger/eval_test.go
ledger/ledger_perf_test.go
ledger/totals_test.go
network/multiplexer_test.go
network/netprio.go
network/ping.go
network/wsNetwork_test.go
test/netperf-go/puppeteer/puppeteer_test.go
util/metrics/reporter_test.go

The changes in this PR are the result of running :
```
go list ./... | xargs -I % gofmt -s -w ../../../%
```
These changes eliminates the warning appear in the vscode editor.
No tests are needed; This is only code style change.

Run gofmt against source code.

---

tools/network/dnssec/config_unix.go

Add f.Close() return code testing in SystemConfig()
There was a small bug there calling f.Close() on a erroneous return from os.Open ( which would have returned nil as the f )

Add f.Close() return code testing in SystemConfig()

---

agreement/cadaver.go
agreement/persistence.go

This PR contains few changes to improve error handling and file permissions -
1. cadaver file now being created with 0600 instead of 0666 and being modified to 0666 after creation. This allow us to make this modification symmetrically if the file is opened for appending, which ensures that when we attempt to rename the file to ".archive" the file always has the 0666 permission.
2. add handling for failure to close the cadaver file.
3. modify the reset() function so that it would log the error, in case it encountered any.
4. modify the restore() function to review the returned error code from agreeInstallDatabase and take advantage of the result.

Improve agreement cadaver & crash database error handling

---

node/node.go
node/node_test.go

This PR handles the following missing error code checking:
1. Add a test to verify the error in the creation of the genesis directory.
2. Add logging in case `node.loadParticipationKeys` returns an error
3. Add logging in case `os.Rename` has failed.
4. Remove `fmt.Println(msg)`, as the node reporting output is the log file, and not the console.

Improve node error code checking

---

ledger/acctupdates.go
ledger/acctupdates_test.go
ledger/catchpointwriter_test.go
ledger/txtail_test.go

The `roundDigest` variable in the `accountUpdates` structure was expected to be cleared out during `initializeFromDisk`, but it wasn't. As a result, a node that has caught up using the fast catchup would produce incorrect catchpoint labels.
Add a unit test to verify the correctness of the fix. The unit test is far more comprehensive than required, and would detect other potential failure cases that would end up having a different catchpoint label.

bugfix: clear roundDigest when fast catchup is switching off

---

network/wsNetwork.go
network/wsNetwork_test.go

Add a benchmark to test the performance of a local client->server transaction communication.
Benchmark results:
| Transactions Per Message  | Rate |
| ------------- | ------------- |
| 1  | 15,615 txn/sec |
| 2  | 29,868 txn/sec |
| 3 | 37,998 txn/sec|
| 4 |39,873 txn/sec |
| 5 |49,403 txn/sec |
| 6 | 53,004 txn/sec|
| 7 | 50,405 txn/sec|
| 9 | 56,094 txn/sec|
| 10 | 60,297 txn/sec|
| 12 | 63,149 txn/sec|
| 14 | 65,401 txn/sec|
| 16 |66,755 txn/sec |
| 18 | 65,710 txn/sec|
| 23 | 60,318 txn/sec|
| 29 |63,359 txn/sec |
Running parameters-
1. Transaction size 250 bytes
2. Transaction processing delay 10,000ns
This delays should impose a theoretical limit of 100,000 txn/sec.
Benchmark is a test.

Add BenchmarkVariableTransactionMessageBlockSizes

---

data/committee/sortition/sortition.go

Boost complains about non c++11 compiler, so make it happy.
Use existing test suite

Fix deprication warning on sortition compilation

---

catchup/fetcher_test.go
catchup/httpFetcher.go
catchup/ledgerFetcher.go
components/mocks/mockNetwork.go
network/wsNetwork.go
network/wsPeer.go
rpcs/httpTxSync.go
rpcs/txService_test.go
rpcs/txSyncer_test.go

The `wsPeer` doesn't provide any value in performing the GenesisID substitution; it's just reading the current value from the `wsNetwork` and calling the `strings.Replace` function. Moving this function to `wsNetwork` makes it much more encapsulated and avoid unneeded referencing.
The long-run plan is to try and de-couple the `wsPeer` from `wsNetwork` so that `wsPeer` would have a `wsNetwork` interface to work with ( not the `GossipNode`, but something more suitable for that particular "link" ). Once this is achieved, we should be able to write better testing for `wsPeer` without relying on the massive `wsNetwork` implementation.
Existing unit tests were updated.

Move peer.PrepareURL to net.SubstituteGenesisID

---

test/e2e-go/features/transactions/sendReceive_test.go

The existing TestAccountsCanSendMoney had three issues -
1. Testing ping ponging algos over 225 rounds is logically correct, but not very useful. If there is an issue, it would likely to show up within 25 rounds.
2. The test was not testing the transactions were received on both clients.
3. The test was not testing the pingBalance/pongBalance on both clients.
This is a test

Improve TestAccountsCanSendMoney e2e test

---

agreement/gossip/network.go

The number of proposals generated derives from the consensus params. At this time, we have (up to) 20 proposals.
In a rare network event, when all the relays connected to a given proposer are lagging behind, the winning proposal could be dropped out, causing a 21 second round.
This was verified by lowering the proposalBufferSize dramatically, confirming that the only dropped agreement messages were proposals, and that a 21 second rounds were introduced.
Tested by lowering the proposalBufferSize to 2, and running a deployed network. Once every few *hours*, we would have a 21-second round.

Increase pending proposals queue

---

cmd/goal/asset.go

before:
```
$ goal asset destroy --assetid 0
Cannot construct transaction: decoded bad addr:
```
after:
```
$ goal asset destroy --assetid 0
Missing required parameter [--manager] or [--creator]
```

Better missing argument error message for "goal asset destroy"

---

cmd/tealdbg/cdtState.go
cmd/tealdbg/home.html
cmd/tealdbg/homepage.go

When using tealdbg to debug a program that manipulates integers larger than `2^53 - 1` (JavaScript's max safe integer), these values are unable to be displayed accurately. This affects both the Chrome DevTools and the web frontends.
Given this example program, below are images of the current behavior on both frontends:
```
#pragma version 2
int 0xFFFFFFFFFFFFFFFF
dup
store 0
int 0xFFFFFFFFFFFFFFFE
dup
store 1
-
```
<details>
<summary>Chrome current behavior (values turned negative)</summary>
</details>
<details>
<summary>Web current behavior (values lose precision)</summary>
</details>
For the Chrome frontend, I fixed this by changing the debugging object type of TEAL integers from "number" to "bigint". (Note: I didn't change every numeric type to "bigint" because some values, like array …

Support large integers in tealdbg

---

ledger/appcow.go
ledger/appcow_test.go
ledger/applications.go
ledger/applications_test.go
ledger/cow.go

`cow.mods` was accessed by logic ledger and its tests. This PR fixes it and now all `mods` accessed done only by `cow`'s methods.
Update existing tests, add new tests for newly added methods to preserve coverage level.

Remove all cow.mods usages outside of cow type

---

data/transactions/transaction.go
data/transactions/transaction_test.go

This PR modifies the error message generated when the amount of fee is below the `MinTxnFee` from
```
transaction had fee {100}, which is less than the minimum 1000
```
to
```
transaction had fee 100, which is less than the minimum 1000
```

Fix insufficient fee error message formatting

---

cmd/loadgenerator/config.go
cmd/loadgenerator/loadgenerator.config.example
cmd/loadgenerator/main.go
daemon/algod/api/client/restClient.go

In order to implement the "max attained throughput" on the mainnet metrics dashboard we need to generate at least a single block that would contain as many transactions as we can. The utility implemented here could assist us doing so.
Config file should be provided based on the example config file.
A mnemonic can be generated using 
```
algokey generate | grep "Private key mnemonic:"
```

implement a transaction load generator

---

logging/telemetryConfig.go
logging/telemetryConfig_test.go
test/testdata/configs/logging/logging.config.test1

As part of a refactoring effort in https://github.com/algorand/go-algorand/pull/1709, a small bug was introduced that changed the intended behavior of `loadTelemetryConfig`. This PR restores the previous behavior and adds a unit test for that.

Fix regression to loadTelemetryConfig introduced in 2.3.0

---

scripts/travis/deploy_packages.sh

The call to `check_golang_version.sh` is causing the travis run to fail when deploying:
https://travis-ci.com/github/algorand/go-algorand/jobs/470973034#L142
I believe that removing this check is safe.  We're installing the version of go that may be needed immediately after this check using `gimme`, so any subsequent operations will be sure to succeed because it will be installing the build version (1.14.7).
Also, the `check_golang_version` script is intended as a safeguard for dev and building and I don't believe is needed in this deploy script.
Hope and pray.

Remove check_golang_version check when deploying in travis

---

ledger/accountdb_test.go

The benchmark BenchmarkReadingAllBalancesRAM and BenchmarkReadingAllBalancesDisk started failing after BenchmarkWritingRandomBalancesDisk was introduced (8ea0fb1555a4e8dea46405f2bccb4ca33a3bddd6).
The culprit was setting up the accounts data structure with too much algos, causing the total amount of algos to overflow the uint64.

testing: fix regression in BenchmarkReadingAllBalancesRAM and BenchmarkReadingAllBalancesDisk

---

cmd/diagcfg/telemetry.go
logging/telemetry.go
logging/telemetry_test.go

When a datadir is not provided, this will have diagcfg read from the default logging config in the global config path. It will then generate a default config if that file does not exist
I ran this locally and was able to produce correctly configured default logging configs

diagcfg : Read from global logging config if data dir not provided

---

test/scripts/e2e_subs/tealprogs/globcheck.teal
test/scripts/e2e_subs/tealprogs/globwrite.teal
test/scripts/e2e_subs/tealprogs/xappreads.teal

Replace some app value keys "foo" with a non-utf8 string to test binary cleanness.
This is a test. It should pass.

non-utf8 app value keys for test

---

test/scripts/e2e_client_runner.py

This PR improves the existing e2e client runner in two different ways:
1. It extends the time the kmd would remain in memory from 200 seconds to 3600 seconds.
Given that some of our tests have a timeout of 300 seconds, it only make sense to align it with *at least* the duration of the longest test. Since we don't don't when each of the tests start running, we need to ensure it would be sufficiently large.
2. The existing wallet initialization bootstrapping code was polling for up to 5 seconds for the funds to be moved to the wallet. The changes here would ensure that:
- The funds were moved successfully.
- The operation is completed within a known number of rounds.
- Instead of polling, it would wait for a new round. That sounds reduce the cpu load when running many e2e tests …

testing: make e2e_client_runner more robust

---

test/scripts/e2e_subs/assets-app.sh
test/scripts/e2e_subs/sectok-app.sh

* goal waits for txn submitted at round x till x+2
if submitting at the beginning of the round it is full 3 * 4.5 seconds per txn
* assets-app.sh has 23 txns that is 23 * 3 * 4.5 = 311 seconds
* sectok-app.sh has 27 txns that is 27 * 3 * 4.5 = 365 seconds
This is fix for tests

Adjust timeouts in assets-app.sh/sectok-app.sh tests

---

config/consensus.go
ledger/compactcert.go
test/e2e-go/features/compactcert/compactcert_test.go

Two related changes to how CompactCertWeightThreshold works:
1. For precision, treat it as a fraction of (1/2^32)ths, instead of a
fraction of (1/100)ths.  This also makes the integer math easier to
implement for other verifiers.
2. The decaying threshold of acceptable cert weights now goes from full
(all signatures required) to CompactCertWeightThreshold, instead of
going down to 0.  The 0 was meaningless anyway, because if a compact
cert has less than CompactCertWeightThreshold of signatures, it would
be rejected elsewhere.

more precise CompactCertWeightThreshold

---

go.mod
go.sum

update go.mod/sum to use msgp 46, which is a prerequisite to subsequent PR.
This new version of msgp supports including embedded structures from different packages.
Tests included in msgp library
The changes made in the msgp are not expected to make any changes before the subsequent PR is added.

update go.mod/sum to use msgp 46

---

test/scripts/e2e_subs/rekey.sh

To better test the binary-clean-ness of the tools at every stage, add a non-utf8 Note field
This is a test. It should pass. Downstream tests (Indxer) will also benefit.

add a non-utf8 Note

---

compactcert/abstractions.go
compactcert/builder.go
compactcert/db_test.go
compactcert/signer.go
compactcert/worker.go
compactcert/worker_test.go
test/e2e-go/features/compactcert/compactcert_test.go

This PR adds unit tests to the compactcert package, as suggested by Pavel.
As part of introducing these unit tests, this PR refactors the worker threads to be more predictable when the test harness is quickly advancing rounds in the simulated ledger.

tests for the compactcert package

---

test/scripts/e2e_subs/rekey.sh

This is primarily test data for Indexer. Close an account that has been rekeyed. Indexer should not present the rekeyed address after the close.
This test passes go-algorand and produces useful test data for Indexer.

close after rekey

---

cmd/tealdbg/cdtState.go

Currently the `Accounts` array is not displayed properly in tealdbg. The debugger does not account for the special case that index 0 of the `Accounts` array is always the sender. This means that if the ForeignAccounts txn field contains `n` accounts, the `Accounts` array in tealdbg contains the sender's account followed by `n-1` of the ForeignAccounts. The last account never gets displayed.
This PR fixes this problem by making tealdbg aware that the `Accounts` array has 1 more member (the sender's account) than `len(txn.Accounts)`. As a consequence of this, the sender's account will always appear at index 0 of the `Accounts` array in the debugger, even when the transaction's ForeignAccounts array is empty. This aligns with the behavior of the TEAL op `txna Accounts 0` always returning the …

Fix tealdbg Accounts array

---

.travis.yml
scripts/check_golang_version.sh

A change to use go tooling to get go version from go.mod used jq to parse the results. This breaks on platforms that don't have jq. This change just removes the dependency (and replaces it with the more accessible awk).
Set travis to run the deploy jobs with the change, and verify they succeed.

Remove jq from check golang version script to fix deploy jobs in Travis

---

data/pools/transactionPool.go
data/transactions/signedtxn.go
data/transactions/transaction.go
ledger/eval.go
protocol/codec.go

This change optimizes ID() and GetEncodedLength() for Transaction, SignedTxn, and SignedTxnInBlock.  There are two sources of overhead that this change avoids: interface conversions (to msgp.Marshaler) and memory allocations (for temporary slices to hold the encoding).
To avoid interface conversions, the code invokes the msgp-generated MarshalMsg() method directly.
To avoid memory allocation overhead, the code uses a sync.Pool to track existing dirty slices that can be used for encoding.  This seems to be more efficient than letting the Go GC manage slices, probably because the encoder is OK with dirty (non-zero) slices.
This significantly improves performance according to BenchmarkEncoding (in data/transactions).  Before this change:
BenchmarkEncoding/EncodeLen-32          276892 …

faster computation of transaction ID and length

---

crypto/compactcert/builder.go
crypto/compactcert/builder_test.go
crypto/merklearray/array.go
crypto/merklearray/layer.go
crypto/merklearray/layer_test.go
crypto/merklearray/merkle.go
crypto/merklearray/merkle_test.go
crypto/merklearray/partial.go
crypto/merklearray/worker.go
ledger/voters.go

This PR speeds up merklearray, both with some small absolute performance wins (avoiding crypto.HashObj overheads), as well as parallelism in hashing the leaves and the internal nodes.
For tiny trees (10 elements where each element is something like 10-100 bytes), the parallelism adds a slight overhead (about 30-40 microseconds on my test machine, on top of a total runtime of 25-80 microseconds).  But for anything larger (either more elements or more complex-to-hash elements), this ends up being an improvement.
This might have some benefit for the current use of merklearray (namely, compact certificates), but should be even more useful for the upcoming use of merklearray for hashing all transactions in a block.

speed up merklearray

---

daemon/algod/api/spec/v1/model.go
ledger/apply/mockBalances_test.go

As a fix to #1886, now API v1 omits the `closetoamount` in case of the 0 value.

Fix omitempty for AssetCloseAmount

---

config/consensus.go
netdeploy/network.go
netdeploy/network_test.go

Using `goal network create` would create a network directories containing a `consensus.json` file. That file would contain the `null` string.
The above file should not have been created. In case no consensus protocol changes are needed for a given network, the expected behavior is of no `consensus.json` file being generated.
Add a unit test.

goal: avoid creating invalid consensus.json file

---

agreement/service.go
agreement/service_test.go

The agreement mainLoop function was bootstrapping the Deadline with the parameters based on the `protocol.ConsensusCurrentVersion`. This might be incorrect when the binary supports protocols that haven't (yet) been adopted by the network.
Added unit test.

agreement: FilterTimeout is using binary ConsensusCurrentVersion instead of current protocol version

---

network/wsNetwork.go
network/wsNetwork_test.go
node/node.go

The broadcastThread implementation was sub-optimal, and this PR addresses the issues we had there -
1. The broadcastThread is now using a single broadcasting go-routine rather than 4.
2. The broadcastThread/innerBroadcast used to drop queued messages just because there are no current peers. Instead, it will hold off until there is an available peer before queuing up the messages to the peers.
3. The peers array is being updated only if there is enough "wait time" between consecutive messages. In case of a high message burst, the peers would not get updated to avoid taking the peers lock.
4. The node's broadcast call was replaced with non-blocking to align with previous behavior.
5. The single thread implementation would ensure that queued messages would also be sent to the underlying …

network: refactor broadcastThread

---

data/basics/units.go
data/bookkeeping/block.go
data/ledger.go
data/ledger_test.go

The agreement was printing out the following error message:
```
(1) unable to retrieve consensus version for round 8764517, defaulting to binary consensus version
```
The culprit was a recent change to the [agreement initialization code](https://github.com/algorand/go-algorand/pull/1896) that would try to use the consensus version of the next round in order to find out some of the agreement runtime parameters.
This PR improves the data.Ledger.ConsensusVersion logic, allowing it to "predict" future protocol versions, based on known and previously agreed upon block headers.

bugfix: prevent misleading agreement error message

---

scripts/release/test/deb/testDebian.exp
test/e2e-go/cli/goal/expect/basicGoalTest.exp
test/e2e-go/cli/goal/expect/corsTest.exp
test/e2e-go/cli/goal/expect/createWalletTest.exp
test/e2e-go/cli/goal/expect/doubleSpendingTest.exp
test/e2e-go/cli/goal/expect/goalAccountInfoTest.exp
test/e2e-go/cli/goal/expect/goalAccountTest.exp
test/e2e-go/cli/goal/expect/goalAppAccountAddressTest.exp
test/e2e-go/cli/goal/expect/goalAssetTest.exp
test/e2e-go/cli/goal/expect/goalClerkGroupTest.exp
test/e2e-go/cli/goal/expect/goalDryrunRestTest.exp
test/e2e-go/cli/goal/expect/goalExpectCommon.exp
test/e2e-go/cli/goal/expect/goalNodeStatusTest.exp
test/e2e-go/cli/goal/expect/goalNodeTest.exp
test/e2e-go/cli/goal/expect/goalTxValidityTest.exp
test/e2e-go/cli/goal/expect/ledgerTest.exp
test/e2e-go/cli/goal/expect/limitOrderTest.exp
test/e2e-go/cli/goal/expect/listExpiredParticipationKeyTest.exp
test/e2e-go/cli/goal/expect/multisigCreationDeletionTest.exp
test/e2e-go/cli/goal/expect/pingpongTest.exp
test/e2e-go/cli/goal/expect/reportTest.exp
test/e2e-go/cli/goal/expect/statefulTealAppInfoTest.exp
test/e2e-go/cli/goal/expect/statefulTealAppReadTest.exp
test/e2e-go/cli/goal/expect/statefulTealCreateAppTest.exp
test/e2e-go/cli/goal/expect/tealAndStatefulTealTest.exp

The expect tests were calling `goal network start -r <root dir> -d <data dir>` and `goal network stop -r <root dir> -d <data dir>`. While this is not harmful in any way, the neither of these commands is doing anything with the extra data directory parameter.
Given that this parameter is completely ignored, the is no point in passing it in. ( as it would only mislead the reader of these tests )

Remove data direcory from start/stop network expect tests

---

catchup/fetcher_test.go
cmd/catchupsrv/main.go
network/wsNetwork.go
rpcs/blockService.go
rpcs/wsFetcherService.go
test/e2e-go/features/catchup/basicCatchup_test.go

Remove the network v1 fetcher service via websocket connections.
This is only removing unused code. The existing tests should be sufficient.

Remove the network v1 fetcher via websocket connections.

---

test/scripts/e2e.sh
test/scripts/e2e_client_runner.py
test/scripts/e2e_subs/dynamic-fee-teal-test.sh
test/scripts/e2e_subs/e2e-teal.sh
test/scripts/e2e_subs/htlc-teal-test.sh
test/scripts/e2e_subs/keyreg-teal-test.sh
test/scripts/e2e_subs/limit-swap-test.sh
test/scripts/e2e_subs/periodic-teal-test.sh
test/scripts/e2e_subs/teal-split-test.sh

This allows running integration tests without a repo under GOPATH.
Tests had been using GOPATH, but mostly just to find the top of the repo to
refer to tests.  This breaks if doing module oriented stuff outside of
GOPATH. These changes make it so that e2e.sh uses the full name of the
e2e test files, and e2e_client_runner executes the e2e scripts with
cwd set to top of repo.  That allowed removing the few places those
scripts used GOPATH, in favor of relative filenames.
It *is* the tests.  Was able to run integration tests in my local development environment,
which was impossible without these changes, as I don't work under GOPATH.  That is the way
forward with Go, so we should get ready.  I will be checking if CI broke in any way by watching
it!

Remove GOPATH dependencies in integration tests

---

data/basics/userBalance.go

Clarify account status meaning in code-comment.
No test needed for comment-only changes.

Clarify account status meaning in code-comment

---

data/transactions/transaction.go
txnsync/bloomFilter.go
txnsync/emulatorTimer_test.go
txnsync/outgoing.go

Comments to help understand the code better. Rename 'compare' to 'sameParams' to be more descriptive.
Add a lock to a test to prevent rare race crash.
Ran tests many times, race crash hasn't happened since adding lock.

comments. add lock to test to prevent rare race

---

txnsync/emulatorLogger_test.go
txnsync/emulatorNode_test.go
txnsync/incoming.go
txnsync/interfaces.go
txnsync/mainloop.go
txnsync/outgoing.go
txnsync/peer.go

This PR handles two separate issues:
1. On the non-relay, it sends a message every time the offset for the node changes. ( i.e. ~4 times a second).
This helps to reduce the amount of redundant transactions are sent to the non-relay.
2. Added a destination to the logged message so that we can see on the emulation the name of the destination node.
Unit tests were updated.

Improve emulator logging & send request on offset change.

---

network/wsPeer.go
util/metrics/tagcounter.go
util/metrics/tagcounter_test.go

Expand /metrics to show per-message-tag stats on number of messages and amount of bytes moved.
e.g.
```
algod_network_message_received_AV 4431
algod_network_message_received_MI 1
algod_network_message_received_MS 137
algod_network_message_received_PP 1082
algod_network_message_received_TX 303
algod_network_message_received_UE 17
algod_network_message_received_total{} 5971
algod_network_message_sent_AV 2243
algod_network_message_sent_CS 9
algod_network_message_sent_NP 1
algod_network_message_sent_PP 583
algod_network_message_sent_TS 17
algod_network_message_sent_TX 187647
algod_network_message_sent_queue_micros_total{} 6774576
algod_network_message_sent_total{} 190500
algod_network_received_bytes_AV 2784680
algod_network_received_bytes_MI 47
algod_network_received_bytes_MS 4658 …
```

Net tag stats

---

cmd/tealdbg/localLedger.go
daemon/algod/api/server/v2/dryrun.go
ledger/acctupdates.go
ledger/acctupdates_test.go
ledger/appcow.go
ledger/appdbg.go
ledger/eval.go
ledger/ledger.go

Introduce `ApplicationDbgLedger` interface to use in tealdbg and dryrun. This is to properly isolate internal `legderForCowBase` and allow its extension.

1k+ assets (part 2)

---

test/e2e-go/cli/goal/expect/goalExpectCommon.exp

When a test fails and the abort routine is called, some variables used there may not be defined. This causes the script to report error about that. This is not related to the test failure and is a test environment error that should not be there. 
This change first checks if the variable is defined. 
This is on an exception path that does not get exercised. I tested it by forcing a failure to verify this fixes the problem.

Fix parameter check in abort procedure

---

cmd/algofix/deadlock.go
cmd/algofix/deadlock_test.go
test/e2e-go/features/catchup/basicCatchup_test.go
txnsync/emulatorNode_test.go

use comments to locally allow sync.Mutex instead of rewriting it to the much slower deadlock.Mutex
```go
// algofix allow sync
// algofix require deadlock
```
Added unit test of deadlock replacement, normal and with new comment directives

locally allow sync.Mutex

---

txnsync/emulatorNode_test.go
txnsync/emulatorTimer_test.go
txnsync/incoming.go
txnsync/outgoing.go

Avoid using the `deadlock.Mutex` in the emulator, and use a channel instead.
The `deadlock.Mutex` was consuming considerable amount of memory, due to it's internally allocated timer.
edit: following on rare data races found on travis, I avoided using the main state's clock in the async methods. The clock is being updated once every round, so we can't really control that unless we add a synchronization primitive or find a better way.

Improve txnsync emulator performance and memory profile

---

cmd/algofix/deadlock.go
cmd/algofix/deadlock_test.go

Allow struct field to be sync.Mutex if tagged `algofix:"allow sync.Mutex"`
deadlock.Mutex can be much slower and some code (in progress on another branch) needs to be specified to use standard library sync.Mutex
Includes new unit test for algofix of code with sync.Mutex, both replacing with deadlock.Mutex and tagged to remain as sync.Mutex

allow struct field to be sync.Mutex if tagged

---

ledger/acctupdates.go
ledger/acctupdates_test.go

During the accounts update initialization, we call the initializeCaches method to preload the most recent 320 rounds.
These 320 rounds are the difference between where the accounts database round and the latest blocks database round.
If (from any reason), the difference is more than 320 rounds, then all the rounds in that range are being loaded into memory. This, in turn, creates an issue when we have to recover from a large gap, as it would run out of memory.
To address this issue, this PR reconstruct the accounts database in "chunks" of 1000 rounds. This method prevent the node from going into a situation where it needs to handle large quantity of rounds sitting in memory.
Unit test added. Verified manually that recovered account database end up generating the same catchpoints as on …

Reconstruct balances database from blocks

---

cmd/tealdbg/cdtState.go
data/transactions/logic/assembler.go
data/transactions/logic/assembler_test.go

Most of the new TEAL 3 features already work with the debugger, but a few changes were needed to make the new array fields display properly on the Chrome frontend.
Also, I noticed the disassembly for `pushbytes` was missing a trailing newline, which made the disassembled program for debugging look strange.
Added a unit test for `pushbytes` and `pushint` disassembly.

TEAL 3 changes for tealdbg

---

cmd/tealdbg/main.go
cmd/tealdbg/server.go
cmd/tealdbg/server_test.go
test/e2e-go/cli/tealdbg/expect/tealdbgTest.exp

Fix for #1809
Updated tealdbg e2e test

tealdbg: listen on specified address

---

test/scripts/e2e_client_runner.py

script prints logs for all test cases that has non-zero return code. When the process got killed it  has a return code 15, so this caused verbose logging.

skip printing the logs when program is in terminated state.

---

daemon/algod/api/server/v2/handlers.go
daemon/algod/api/server/v2/test/handlers_test.go
daemon/algod/api/server/v2/test/helpers.go

I discovered that #1004 accidentally changed the `total-transactions` field in the `getPendingTransactions` handler function. That value is supposed to be the total number of pending transactions, but currently it is only the number of transactions returned by the current API call. I've fixed this and improved the names of local variables to make this easier to see.
While testing this, I also discovered a bug with the `max` parameter. When set to 0, `getPendingTransactions` should return all pending transactions. The current behavior is correct when there is no `max` query param in the API request, but when explicitly setting `max` to 0 (i.e.`/v2/transactions/pending?max=0`) the endpoint always returns 0 transactions.
Since the documentation states `If max=0, returns all pending txns`, I …

Fixes for pending transaction endpoint

---

cmd/algoh/main.go

When algoh spawns an algod instance and the algod panics, algoh simply exits without logging the panic. This change logs the algod panic before the algoh exits.
Started an algoh with algod, hardcoded a panic when it hits round 10, sees that `algod-err.log` contains the panic message

Report algod panic in algoh

---

network/wsNetwork.go
network/wsNetwork_test.go
network/wsPeer.go

Add GetPeerData()/SetPeerData() to network interface for data to be associated with a peer by other parts of the system so that data gets garbage collected when peer goes away.
Trivial feature. No testing yet.

copy GetPeerData()/SetPeerData() from txnsync branch

---

data/transactions/logic/eval.go
data/transactions/logic/eval_test.go

setbyte and setbit could mistakenly modify other teal values (on stack, in constant blocks, etc) because slices shared backing store.  This copies them.
Better tests were added.  The previous test failed to find the issue because the constant being used to check against was, itself, modified by the bug!

copy byteslices that will be modified by opcode

---

daemon/algod/deadlockLogger.go
daemon/algod/deadlock_test.go

The deadlock logger we've used was not thread-safe. That was fine until the point where a deadlock would be detected, at which there was a chance of creating a subsequent failure while reporting the first one.
This PR re-implement the logger in a safe-way : it inherently prevent concurrent calls to `onPotentialDeadlock` as well as ensures that all the writes using the `Writer` interface are synchronized.
Existing unit test was updated. New unit test was added.

make deadlockLogger thread-safe

---

scripts/release/mule/deploy/releases_page/generate_releases_page.py

The releases page script could use a little explanation, so added comments for consideration.
This is a comments / line formatting fix.

Add comments to releases page script.

---

scripts/release/mule/deploy/docker/docker.sh

The betanet docker image was not getting tagged. Added tagging for betanet.
Try to deploy 2.5.2-beta to docker hub again using mule.

Add pushing docker tag to betanet

---

network/wsNetwork.go

Initial implementation of this code was using the worst-case single round message count as the number of pending outgoing messages. This was found to be more then just wasteful, but also problematic when it being used on relays.
From practical perspective, the agreement protocol for a node is only at a single step on any given moment. Therefore, creating a buffer that is big enough for that step should be enough. An exception for that are the late committees, which can run in parallel to the above step.
Accounting for both of the above reduces the practical outgoing buffer size from 38,000 to 11,000 - which in turns reduces the pending queues size from 3M -> 880K.
Use existing unit test to verify functionality.

Adjust the network outgoing buffer sizes

---

data/pools/transactionPool.go
ledger/appcow.go
ledger/appcow_test.go
ledger/cow.go
ledger/cow_test.go
ledger/eval.go
ledger/ledgercore/statedelta.go

* Exclude committed count from pending count and calculate paysetHint precisely.
* Provide correct hint for child cow.
* Do not preallocate Creatable map since app/asset creation are relatively rare operations.
Use existing test suite

Precise calculation of paysetHint for block eval

---

.travis.yml

To get around Docker Hub pull limits, we can try to explicitly cache docker images between builds. This seems like a safer approach than #2009.
Verify docker images are saved by running this, then re-running and seeing if it's cached.

Cache docker images in Travis and re-load them

---

agreement/demux.go
network/connPerfMon.go
network/wsNetwork_test.go
test/commandandcontrol/cc_agent/component/agent.go
test/commandandcontrol/cc_service/main.go
util/metrics/counter_test.go
util/metrics/gauge_test.go
util/metrics/segment_test.go

The word `received` was misspelled multiple times in our codebase as `recieved`. This PR replaces all the typos with it's correct spelling.
No tests are need for fixing in-code comments.

Fix few typos in comments

---

test/e2e-go/features/compactcert/compactcert_test.go

Analyzing a random failure in an unrelated branch, I ran into the following:
```
compactcert_test.go:85: 
8350        	Error Trace:	compactcert_test.go:85
8351        	Error:      	Received unexpected error:
8352        	            	HTTP 500 Internal Server Error: failed to retrieve information from the ledger
8353        	Test:       	TestCompactCerts
8354        	Messages:   	failed to retrieve block from algod on round 15
```
While I still don't know why this happen, the testing code was ignoring the return code from
```
fixture.WaitForRound(rnd, 30*time.Second)
```
which would lead to the above error, instead of reporting the real underlying issue.

Improve TestCompactCerts error testing

---

test/e2e-go/cli/goal/expect/goalExpectCommon.exp

the expect `::AlgorandGoal::Abort` procedure was attempting to stop the wrong node directory, leading to consistent fails:
```
spawn go install ./catchpointCatchupWebProxy
8738        Aborting with Error: timed out compiling catchpointCatchupWebProxy
8739        GLOBAL_TEST_ROOT_DIR /Users/travis/gopath/src/github.com/algorand/go-algorand/tmp/out/e2e/104023-1617148239464/catchpointCatchupTest/algod/root
8740        GLOBAL_NETWORK_NAME test_net_expect_1617149479
8741        Stopping network: test_net_expect_1617149479
8742        spawn goal network stop -r /Users/travis/gopath/src/github.com/algorand/go-algorand/tmp/out/e2e/104023-1617148239464/catchpointCatchupTest/algod/root
8743        Network Stopped under /Users/travis/gopath/src/github.com/algorand/go-algorand/tmp/out/e2e/104023-16171 …
```

testing: fix node shutdown on error

---

data/transactions/logic/TEAL_opcodes.md
data/transactions/logic/doc.go

Mention that the args to ops pushbytes and pushint do not get added to the bytecblock or intcblock.
This replaces another PR with docs generated using Makefile since it was created with the edit feature.

adding extra docs for pushbytes and pushint

---

nodecontrol/NodeController.go
nodecontrol/algodControl.go
nodecontrol/kmdControl.go

Existing code wait 30 seconds between sending SIGTERM and SIGKILL. When sending the SIGKILL, the process is deleted, but the pid file remains on disk.
Leaving the pid file on disk could cause subsequent failures - and we could easily avoid them by clearing this file if we SIGKILL'ed the process.

node controller: delete pid file on process killing

---

ledger/appcow.go
ledger/apply/application.go
ledger/apply/application_test.go
ledger/ledgercore/error.go
test/scripts/e2e_subs/e2e-app-simple.sh

* Apps logic needs to ignore result and error from logic evaluator but but fail on other errors
* The bug happened in app refactor PR
* Added unit and e2e test
Added e2e test that ensures success with clear state programs that always fail or err.
Added unit test that check clear state error does not lead to `apply.ApplicationCall` error

Fix ClearState program applying when it errs

---

ledger/appcow.go
ledger/applications_test.go

* Opting in does not allocate key value map
* State delta merging code assumed the map in old AD was allocated
* Added that missed allocation, and a test verifying combinations
* Inspected and removed TODOs from applyStorageDelta
Added a test for
1. checking serialization against before app-refactor
2. combinations of `allocAction` and `remainAllocAction` for opting in and writing local state

Fix for empty local state key value map assignment

---

node/node.go

During catchup testing, the following panic was captured:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xc55173]
goroutine 10141 [running]:
database/sql.(*DB).conn(0x0, 0x1b25020, 0xc000036080, 0xc000891401, 0x45f8cb, 0x1be912743e8, 0x757daf0)
database/sql/sql.go:1134 +0x43
database/sql.(*DB).Conn(0x0, 0x1b25020, 0xc000036080, 0x3b9aca00, 0xc012f61d4757daf0, 0x149ffc08bc)
database/sql/sql.go:1739 +0x84
github.com/algorand/go-algorand/util/db.(*Accessor).atomic(0xc00015e3d0, 0xc003fb00c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
github.com/algorand/go-algorand/util/db/dbutil.go:269 +0x139
github.com/algorand/go-algorand/util/db.(*Accessor).Atomic(...)
github.com/algorand/go-algorand/util/db/dbutil.go:207 …
```

Fix node panicing during shutdown

---

crypto/merkletrie/cache.go
crypto/merkletrie/cache_test.go
ledger/accountdb.go

When using the MerkleTrie, the trie avoid making loads from disk for pages that aren't needed. In particular, it won't load the latest page ( known as the deferred page ) until it needs to commit it.
The implementation had a bug in the `loadPage` method, where it would reset the loading page flag incorrectly.
1. Unit test added.
2. Tested against mainnet and testnet.

bugfix: ensure loading of a merkle trie deferred page during commit

---

network/wsPeer.go
network/wsPeer_test.go

On ARM32, all 64 bit atomic operations need to be using a 64-bit aligned address.
This PR moves the requestNonce to a 64 bit aligned address.

Fix requestNonce alignment on arm32

---

Makefile

The message pack generator is very noisy. It tends to emit lot of messages that aren't being used.
This PR cache the output of the message pack so that it would only present these in case of an error.
Tested on travis.

make the msgp less verbosed on the success case

---

cmd/goal/account.go
libgoal/participation.go

Ensure the participation key database is being correctly closed after being installed.
Use existing testing for coverage.

ensure the participation key database is being correctly closed after being installed.

---

txnsync/bloomFilter.go
txnsync/mainloop.go
txnsync/outgoing.go
txnsync/peer.go

This PR improves the generation of bloom filters :
- on relays, it ensures that we reuse the same bloom filter ( when applicable ) for multiple peers.
- on non-relays, it attempts to reuse the previous bloom filter *before* building the new one.
Separately, it optimizes the case of a non-relay connected to a single relay, where it would send the bloom filter
only once rather than with every 2*beta messages.
Last, it corrects a miscalculation in the `getNextScheduleOffset` method, causing us to send more data than the available bandwidth allows.
Tested using the emulator and performance validated by algonet network.

txnsync: Avoid regenerating bloom filters when not needed

---

debug/logfilter/example7.in
debug/logfilter/example7.out.expected
debug/logfilter/main.go

logfilter had a bug, not handling cases where the `go test` was run without `-v`, which eliminated the `-- RUN` message.

debug tooling: logfilter bug when running test without -v

---

cmd/genesis/newgenesis.go
gen/generate.go
gen/generate_test.go
netdeploy/networkTemplate.go
netdeploy/remote/deployedNetwork.go

Genesis blocks (now usually for test networks) initial stake must add up to exactly the total money, but the network description is in float64 and there can be small roundoff to fixup.
Added unit test that has 5 out of 10,000,000,000,000,000 micro-Algos roundoff in naive wallet generation.

netgoal: fixup small amounts of float64 roundoff

---

cmd/tealdbg/local.go
cmd/tealdbg/local_test.go
cmd/tealdbg/main.go
test/e2e-go/cli/tealdbg/expect/tealdbgSpinoffTest.exp
test/e2e-go/cli/tealdbg/expect/tealdbgTest.exp

Currently the TEAL debugger always compiles programs with the latest TEAL version. This means that programs using prior versions are unable to be properly debugged. This PR fixes this issue.
I've added a regression test case to `tealdbgTest.exp` that uses a version lower than the maximum version the protocol supports.

Tealdbg don't assume program version

---

cmd/goal/account.go
cmd/goal/application.go
cmd/goal/asset.go
cmd/goal/clerk.go
cmd/goal/interact.go
cmd/goal/messages.go
test/e2e-go/cli/goal/expect/goalAccountTest.exp
test/e2e-go/cli/goal/expect/goalExpectCommon.exp

The existing implementation of `waitForCommit` had two deficiencies:
- It was waiting for two rounds at the time, instead of waiting for a single round before re-testing the pending transactions.
- It wasn't limiting it's execution time to the transaction's last valid ( on the client side ).
- Note that there is a server side handling for that, which returns an error "kicked out of local node pool".
- This would ensure we have a proper working client in case the server-side restarts.
Existing unit tests provide good coverage. I've added an e2e test to verify the transaction timeout.

goal: improve waitForCommit logic

---

catchup/peerSelector.go
catchup/peerSelector_test.go
catchup/service.go
catchup/universalFetcher.go
ledger/ledger.go

The peer selector has the following goals:
1. Block malicious hosts that return invalid blocks
2. Pick hosts that perform better than others
3. Adapt to changes to the performance of hosts
4. Avoid hosts that download fails
The current implementation of the peer selector meets all these goals, but it is not flexible to random failures.
- It will rank the peers by the first download time. When a good performing peer returns a bad value in the first download, it will have a low rank and may never be selected. 
- When the download fails from a good performing peer, that peer may never be considered again (until it runs out of all other peers)
- The top performing peer is selected all the time, until it's performance degrades. It will never consider other peers as long as the top peer's rank …

Fine tune catchup peer selection logic

---

cmd/goal/account.go
cmd/goal/application.go
cmd/goal/asset.go
cmd/goal/clerk.go
cmd/goal/interact.go

refactor waitForCommit to return the output of PendingTransactionInformation. This PR should eliminate a redundant call to PendingTransactionInformation.
Use existing unit tests and e2e tests.

goal: refactor waitForCommit

---

cmd/goal/messages.go
cmd/goal/node.go
test/e2e-go/cli/goal/expect/goalNodeTest.exp

When starting a node which is already started, two messages are show: already started and successfully started:
$ goal node start
Algorand node was already started!
Algorand node successfully started!
Only the already started message should be shown.
Also, when node restart command is given, there is a check in the code if the node was already running. 
This check comes after the node was stopped, so should never return as the node is still running. But in case it does, a message is added to notify the user. 
Added a test to make sure no other output is printed.

goal node restart message when node already started

---

agreement/player.go

Rollback https://github.com/algorand/go-algorand/pull/1756, as it was determined to cause proposal propagation issues.
This rollback would take the original work back onto the research stage, and would allow us to provide better testing before re-applying it.
Tested on s1 platform to ensure regression in the above PR was eliminated as expected.

agreement: rollback early proposal propagation changes

---

catchup/service.go
node/node.go
util/db/dbutil.go

This PR reduces the severity of two benign logged errors/warnings:
1. On the catchup service, the following warning was extremely common:
```
fetchAndWrite: block retrieval exceeded retry limit
```
This PR moves this to be a info messages rather than a warning message ( in most cases ), and extend it to include the round number.
2. On the AlgorandFullNode struct, we used to log a message like this:
```
AlgorandFullNode.loadParticipationKeys: cannot load db XXX.part: database is locked
```
This was caused by concurrent database access to the same part key database. This is a benign error : if we already updating the file, then we don't need to re-evaluate it's content.
Logged level changes were tested manually.

reduce verbosity of logged messages

---

ledger/appcow.go
ledger/appcow_test.go
ledger/applications_test.go

Fix for empty accounts stored in DB after app clear state or app removal
New tests added

Prevent storing empty accounts in DB after opting out from an app

---

cmd/tealdbg/local.go
ledger/accountdb_test.go
ledger/applications_test.go
ledger/catchupaccessor_test.go
ledger/ledger_test.go

Some tests compare data against old released behavior and increasing initial balance breaks hard-coded records
This is a test

Fix initial balances in ledger tests

---

ledger/acctupdates.go
ledger/acctupdates_test.go

Make sure to release mutex in commitRound.
provide correct handling for zero-offset changes.

ledger: fix consensus version flushes incorrectly

---

debug/logfilter/main.go
debug/logfilter/main_test.go

Exit from the logfilter process with non-zero output when "FAIL" was detected on input stream.
This allows us to pipe the input of the test without using `-o pipefail`.
Unit test updated.

logfilter: exit with non-zero when test fails

---

crypto/merklearray/worker.go

Fix accessing int64 atomic variables on arm32, by aligning variables on 64-bit aligned address.

Fix accessing int64 atomic variables on arm32

---

data/transactions/logic/eval.go
data/transactions/logic/evalStateful_test.go
ledger/appcow.go
ledger/appcow_test.go
ledger/applications.go
ledger/applications_test.go
ledger/cow.go
ledger/cow_test.go
ledger/eval.go

* roundCowState now has compatibility mode
* accountIdx param is propagated from logic to GetKey/SetKey/DelKey
* Logic:
- store account index for used in GetKey for this app
- in SetKey/DelKey use store either the index from GetKey if exist or a current account index
- if in compatibility mode, BuildEvalDelta uses indices mentioned above
- otherwise it calculates account index using txn.Accounts
New tests added

ledger: compatibility mode for account index calculation in eval delta

---

cmd/catchpointdump/database.go
cmd/catchpointdump/file.go
cmd/catchpointdump/net.go

Dump utility have not truncated output dump file so it might have some unexpected data.
Manually tested

catchpoint: truncate output file

---

agreement/fuzzer/fuzzer_test.go
config/config.go
config/local_defaults.go
data/account/participation.go
installer/config.json.example
libgoal/transactions.go
netdeploy/network.go
node/node.go
test/testdata/configs/config-v17.json

This PR adds a ParticipationKeysRefreshInterval config option that would replace the hard-coded 60-second value used.
No testing provided in this PR. Subsequent PR ( https://github.com/algorand/go-algorand/pull/2125 ) will be using these config option in it's e2e test.

Add ParticipationKeysRefreshInterval to the node config

---

cmd/netgoal/network.go

netgoal was failing to build network when the bootstrap files was missing.
test manually.

bugfix: netgoal errors when bootstrap files was missing

---

debug/logfilter/example8.in
debug/logfilter/example8.out.expected
debug/logfilter/main.go

The logfilter utility was not handling unit test panics correctly - the panic result was omitted from the output. 
Add a test case to verify the output is correct.

logfilter: provide proper handling for panicing unit tests

---

ledger/accountdb.go
ledger/accountdb_test.go
ledger/acctupdates.go
ledger/acctupdates_test.go
ledger/appcow.go
ledger/appcow_test.go
ledger/appdbg.go
ledger/apply/application.go
ledger/apply/application_test.go
ledger/apply/apply.go
ledger/apply/asset.go
ledger/apply/keyreg_test.go
ledger/apply/mockBalances_test.go
ledger/cow.go
ledger/cow_test.go
ledger/creatablecow.go
ledger/eval.go
ledger/ledger.go
ledger/ledgercore/persistedacctdata.go
ledger/ledgercore/persistedacctdata_test.go
ledger/ledgercore/statedelta.go
ledger/ledgercore/statedelta_test.go

1. Extend `apply.Balances` interface with `GetEx` methods. 
2. Use `Allocate`/`Deallocate` for asset holdings adding/removing.
3. Implement ledger.LookupFull that loads all the assets.

1k+ assets (part 5)

---

README.md
scripts/configure_dev.sh
scripts/install_linux_deps.sh

`scripts/configure_dev.sh` can now install dependencies for Arch Linux. This PR builds on #1850.
Tested on Arch Linux.

Add support for Arch Linux

---

logging/telemetryspec/metric.go
txnsync/mainloop.go
txnsync/outgoing.go
txnsync/profiler.go

This PR adds a lightweight profiler to the transaction sync. The profiler measures the execution time of the various internal components in the transaction sync and provide feedback for their relative CPU consumption.
Test output on Kibana

txsync: transaction sync profiler

---

txnsync/incoming.go
txnsync/mainloop.go

When running the branch on a scenario-1 network that has pingpong, the following message appear in the log file:
```
unable to enqueue incoming message from a peer with txsync allocated data; incoming messages queue is full. disconnecting from peer.
```
As a result of the above disconnection, the network experiences poor performance as the nodes keeps re-establishing connections.
The node's incomingMessageCh was 1024 entries long. That channel included every single incoming message, including (potentially) multiple messages from a single peer.
The solution here was to better scale the solution so that the "main" incoming message channel would contain only a single message for each peer. The peer itself already contains a heap of all it's incoming messages ( which is required in order to …

txsync: add synced incoming message handler
