node/txnSyncConn.go, txnsync/emulatorNode_test.go, txnsync/interfaces.go, txnsync/outgoing.go
Add error handling for outgoing messages:
1. If we fail to send a message to a peer, disconnect the peer ( it's probably already disconnected. But we can't tell that for sure ).
2. If the txnsync internally unable to enqueue the response for the successfully sent message, disconnect from peer. ( we could probably do better here, but that's an issue for future PR ).
3. In the emulator, detect txnsync error and panic on it.
1. Emulator
2. Performance testing
3. Reviewing log files under load.
=> txnsync: improve outgoing message error handling

data/pools/transactionPool.go
When the recomputeBlockEvaluator runs, it tests all the pending transactions against the ledger to detect duplicate transactions ( which happen all the time; these aren't an issue ).
The block evaluator reports the error by returning `*ledgercore.TransactionInLedgerError` and not `ledgercore.TransactionInLedgerError` as the code was testing against.
Yet another one character bug fix.
The bug would only affect the reported block assembly stats, and therefore the issue was validated against the telemetry.
=> txpool: Fix incorrect datatype checking in recomputeBlockEvaluator

ledger/eval.go
This is needed for indexer that doesn't store `AccountData.TotalSchema` that allows computing account's minimum balance.
The change is trivial.
=> ledger: disable minimum balance check when not validating or generating

cmd/updater/systemd-setup.sh, cmd/updater/update.sh, installer/algorand@.service.template
A change in 2.5.4 broke the upgrade behavior. When a node is upgraded with the new scripts, the algod -v updates, but the node doesn't update properly when you check `curl http://$(cat data/node1/algod.net)/versions`.
I tested on AWS ubuntu machines with the go-algorand source code and building the binaries with the installer/algorand@.service.template change. I ran one with the change and one without the change for 2.5.4.
```
sudo snap install go --classic
sudo apt-get install build-essential
sudo apt install make
git clone https://github.com/algorand/go-algorand.git
cd ~/go-algorand && git checkout tags/v2.5.4-stable -b feature/fixupdate
cd ~/go-algorand && ./scripts/configure_dev.sh
make install
cd /home/ubuntu/go/bin
export ALGORAND_DATA=~/.algorand
./goal node start -d ~/.algorand …
```
=> Fix Update Script

cmd/updater/update.sh
Fix systemctl condition so that it will restart with systemd
```
cd ~/go-algorand && ./scripts/configure_dev.sh
make install
cd /home/ubuntu/go/bin
sudo ./systemd-setup.sh ubuntu ubuntu
sudo systemctl daemon-reload
export ALGORAND_DATA=~/.algorand
sudo systemctl start algorand@$(systemd-escape $ALGORAND_DATA)
sudo systemctl status algorand@$(systemd-escape $ALGORAND_DATA)
curl http://$(cat ~/.algorand/algod.net)/versions # 2.5.4
./algod -v # 2.5.4
./update.sh -u -c stable-tmp -p . -d ~/.algorand
./algod -v # becomes latest 2.5.6 
curl http://$(cat ~/.algorand/algod.net)/versions # remains 2.5.4 without the execstart change but updates to 2.5.6 with the new change
sudo systemctl status algorand@$(systemd-escape $ALGORAND_DATA)
```
=> fix the systemctl conditional so it restarts with systemd

nodecontrol/NodeController.go, test/e2e-go/cli/goal/expect/goalNodeTest.exp
Existing implementation was not stopping the KMD in case we have failed to stop `algod`. This is wrong. A call to `NodeController.FullStop` should stop both of them, and return an error if it's unable to do so.
The concrete use case here was that algod has crashed while kmd remained in memory. Calling the above `FullStop()` failed since the `algod` was already gone, and therefore would not attempt to stop `kmd`.
This issue was uncovered by the expect node test.
=> bugfix: ensure stopping a node always stops kmd

network/wsNetwork_test.go
Go 1.15 introduced a new check in the vet tool for `string(int)` conversion that is enabled by default when running `go test`, causing the TestWebsocketNetworkCancel test to fail. This replaces int-to-string conversion with the first recommended solution from the [Go 1.15 release notes](https://golang.org/doc/go1.15#vet):
> Experience with Go has shown that many conversions of this form erroneously assume that `string(x)` evaluates to the string representation of the integer x. It actually evaluates to a string containing the UTF-8 encoding of the value of x. ...
>
> Code that is using `string(x)` correctly can be rewritten to `string(rune(x))`. Or, in some cases, calling `utf8.EncodeRune(buf, x)` with a suitable byte slice `buf` may be the right solution. Other code should most likely …
=> Fix go vet error for string(int) conversion in TestWebsocketNetworkCancel

config/consensus.go, test/scripts/e2e_subs/asset-misc.sh, test/scripts/e2e_subs/v26/short-asset-url-only.sh, test/scripts/e2e_subs/v26/teal-v3-only.sh
Increase the ASA URL size from a limiting 32 bytes to 96 bytes to support NFTs with longer IPFS URLs. 
Closes algorand/go-algorand-internal#1179.
Integration tests for before and after the change.
=> Increase ASA URL size 

test/e2e-go/upgrades/send_receive_upgrade_test.go
This PR addresses a bug in the protocol upgrade tests where the `AgreementFilterTimeout` was not set correctly.
In addition, this test removes `SendPaymentFromUnencryptedWallet()` and replaces it with separate `SendPaymentFromWallet()` and `GetUnencryptedWalletHandle()` calls for higher efficiency.
Last, this change *disables* the tests parallelism. Running the upgrade tests in parallel seems to be slower overall. This is still pending investigation, but can be decoupled from these changes for now.
=> testing: improve e2e protocol upgrade tests

test/e2e-go/upgrades/rekey_support_test.go
The existing rekey test was starting a network without rekeying support, making sure that rekeying transaction would fail there, and then waiting for the network to upgrade. Once the upgrade is complete, it would ensure that rekeying transactions works as expected.
The fail case in the above use case was that the upgrade would be asynchronous from the test itself, which was not taken into consideration. This change accounts for that and allow for slow execution of this test to take place and still pass, even if the network was advancing ahead of the test.
Test was fixed.
=> tests: fix rekey upgrade test

node/node.go
The various services used to register to the network callbacks as soon as they started. This was working mostly fine - but allowed a potential window where a connection could be established, and a message slip through. That message would not have a registered handler associated ( yet ), and therefore would be dropped.
The solution here is to flip the order : instead of starting the network first, and then starting all the rest of the component, we will start each of the components first, followed by starting the network. The current network implementation already knows how to provide buffering, and these would be more then adequate for the short period of time between the components starting and the network establishing it's connections.
Existing tests already cover these scenarios. …
=> network: start network only after handlers registration is complete

test/e2e-go/cli/goal/expect/goal_expect_test.go
Temporarily disable expect tests, as the failures there are blocking out testing.
n/a
=> tests: disable goal expect tests

test/e2e-go/upgrades/rekey_support_test.go
The previous fix for this test (#2178) was incomplete. It did not included proper handling for the case of round 0.
This PR addresses this corner case.
=> testing: fix TestRekeyUpgrade when round=0

catchup/fetcher_test.go, catchup/universalFetcher.go, catchup/universalFetcher_test.go
Adding missing test for universalFetcher.go
Code coverage increased from 74%->96%
Tests added.
=> Adding missing test for universalFetcher.go

network/requestTracker.go, network/wsNetwork.go
Fix race [reported here](https://github.com/algorand/go-algorand-internal/issues/1268):
```
Read at 0x00c00675ed48 by goroutine 210:
github.com/algorand/go-algorand/network.(*WebsocketNetwork).ServeHTTP()
/home/travis/gopath/src/github.com/algorand/go-algorand/network/wsNetwork.go:1114 +0x19ad
github.com/gorilla/mux.(*Router).ServeHTTP()
/home/travis/gopath/pkg/mod/github.com/gorilla/mux@v1.6.2/mux.go:162 +0x193
github.com/algorand/go-algorand/network.(*RequestTracker).ServeHTTP()
/home/travis/gopath/src/github.com/algorand/go-algorand/network/requestTracker.go:474 +0x77b
net/http.serverHandler.ServeHTTP()
/home/travis/.gimme/versions/go1.14.7.linux.amd64/src/net/http/server.go:2836 +0xce
net/http.(*conn).serve()
/home/travis/.gimme/versions/go1.14.7.linux.amd64/src/net/http/server.go:1924 …
```
=> testing: fix data race accessing messagesOfInterest during network shutdown

README.md
Recently the build tooling was updated in #2108 which split out the installation of Go tools golint, stringer, swagger, msgp into a separate script `install_buildtools.sh`. This updates the README to reflect that in the environment setup instructions.
=> Add mention of install_buildtools.sh to README

ledger/accountdb.go, ledger/accountdb_test.go, ledger/creatablecow.go, ledger/ledgercore/msgp_gen.go, ledger/ledgercore/persistedacctdata.go, ledger/ledgercore/persistedacctdata_test.go, ledger/ledgercore/statedelta.go
**Load All** benchmark
1. All accounts have large holdings
Num holdings | master  | challenger | challenger (in mem db)
--------------|---------|------------|-----------------------
1               | 3564 (12050398 ns/op) | 3547 (11755549 ns/op) | 3606 (12008160 ns/op)
512          | 393 (11650118 ns/op) | 380 (10823573 ns/op)    | 403 (11898689 ns/op)
2,000      | - | 100 (15267542 ns/op) | 100 (15748125 ns/op)
3,000      | - | 100 (25761635 ns/op) | 100 (26671236 ns/op)
5,000      | - | 100 (40956548 ns/op) | 100 (38489401 ns/op)
10,000    | - | 100 (86983336 ns/op) | 100(81456949 ns/op) 
100,000  | - | 80 (736586721 ns/op) | 100 (834930061 ns/op)
2. 10% of accounts have large holdings
Num holdings | challenger |
--------------|------------|
2,000      | 530 (9857459 ns/op)
3,000      | …
=> 1k+ assets benchmarks and groups merging

test/scripts/e2e_subs/assets-app-b.sh, test/scripts/e2e_subs/assets-app.sh
speedup
one 240s test -> two 120s tests that run in parallel
This is a test, it should still pass.
=> testing: e2e sub assets-app speedup

test/e2e-go/upgrades/application_support_test.go
The TestApplicationsUpgradeOverREST e2e had a bug in the testing code -
if the upgrade takes place before the broadcast takes place, the broadcast result could be non-err.
This PR ensures that if we get a non-error, we have already upgraded.
=> testing: fix bug in TestApplicationsUpgradeOverREST

test/e2e-go/features/participation/participationRewards_test.go
The e2e test TestRewardUnitThreshold was failing on this statement:
```golang
r.Truef(latestBalanceNewAccount.PendingRewards >= (initialBalanceNewAccount+amountRichAccountPokesWith)/rewardUnit, "new account should have pending rewards (e2e)")
```
I replaces the `r.Truef` with `r.GreaterOrEqualf` to get the values off when it fails.
( I wan't able to reproduce it, so I figured getting some extra info for the next time would be helpful )
No test plan.
=> testing: improve TestRewardUnitThreshold predicate

catchup/fetcher_test.go, catchup/peerSelector.go, catchup/service_test.go, catchup/universalFetcher.go, catchup/universalFetcher_test.go, data/transactions/logic/eval_test.go, network/requestTracker.go, scripts/travis/codegen_verification.sh, util/process_windows.go
While talking to @tsachiherman we noticed stray fmt'd files in my repo after running `make sanity`, and he suggested submitting a fix PR. I discovered this shell line generated a list of `gofiles` that is always empty, probably because the way we set up builds for branches (and vendoring) has changed since it was written.
This re-enables gofmt checking in TravisCI builds.
=> Re-enable gofmt check during travis build

data/transactions/logic/eval_test.go
Two small improvements recommended during CR of teal4-math
=> A test recommended by Pavel, an improvement rec'd by Brian

cmd/goal/clerk.go, config/consensus.go, data/transactions/transaction.go, data/transactions/verify/txn.go, ledger/apply/payment_test.go, test/e2e-go/cli/goal/clerk_test.go, test/scripts/e2e_subs/single-payer-swap.sh
A fair amount of complexity is introduced in transaction groups when the goal is to let some entity perform an action at the expense of another.  For example, a contract account might be willing to perform an exchange, but expects the caller to compensate it to replace the fee that the contract account must pay.
This changes fee accounting to simplify these situations.  Rather than check that *each* txn in a txn group meets the min fee, the txgroup is checked as a whole to ensure the total fee exceeds n*min_fee for an n member txgroup.
Topic for discussion: This change allows an *explicit* --fee=0 or --fee=1 on a goal command to create a no, or low, fee transaction.  Previously it would have silently raised the fee to min fee. If fee is completely left off command-line, it is set to …
=> pool fees in a txgroup

network/wsNetwork.go, network/wsNetwork_test.go, network/wsPeer.go
Increase the threshold of the filtered message digest size, so that we still keep most of the proposal messages, but eliminate the transaction sync messages.
Tested by deploying a S1 network and analyzing its MS message counts and overall bandwidth consumption.
=> txnsync: recalibrate the MsgDigestSkip threshold

catchup/service_test.go, ledger/eval.go
TestOnSwitchToUnSupportedProtocol had multiple segments. This test is separated into multiple tests.
This PR fixes two issues:
1. Fix for a bug in eval: in the event of an error and early termination of the eval, the loading of accounts in a separate go routine was not terminated. loadAccounts will be terminated when eval returns. 
2. TestOnSwitchToUnSupportedProtocol1 had a bug in setting the blocks for protocol switch. The first block was not getting the NextProtocolSwitchOn set to 1. Despite the bug, the test was passing most of the time, and failing some of the time. 
3. TestOnSwitchToUnSupportedProtocol3 had a bug in setting the blocks for protocol switch. AddBlocks starts adding from the next round of the passed block. NextProtocolSwitchOn was getting set one round late.
Fix 1 has …
=> Fixing a bug in eval and TestOnSwitchToUnSupportedProtocol

test/e2e-go/features/catchup/catchpointCatchup_test.go
Extend catchpoint test next round timeout from 10 to 60 seconds to avoid test failure.
Tested locally.
=> Extend catchpoint wait for round timeout from 10 to 60 seconds.

data/transactions/logic/eval.go, data/transactions/logic/eval_test.go
We were checking the against the length with > instead of >=.  That's
wrong, so we could cause a panic instead of clean error when trying to
set the byte 1 past the array length.  Fortunately, both have the same
effect: the txn fails. But we should do this properly.  Thanks to
@amityadav0 for the report in #2221.
New unit test to detect regression:
```
testPanics(t, `global ZeroAddress; dup; concat; int 64; int 7; setbyte; int 1; return`, 3)
testAccepts(t, `global ZeroAddress; dup; concat; int 63; int 7; setbyte; int 1; return`, 3)
```
=> Check setbyte length properly.

.travis.yml, scripts/travis/codegen_verification.sh
Since we manage go ourselves I want to see if our build works without running the travis go setup step.
=> Use minimal travis container since we install go ourselves.

.travis.yml
This pulls in the cleanups we've made to other testing into the rel/ tests. Additionally, the ARM Deploy builder has not successfully built in a while, so we'll remove it altogether.
Merge to master and re-try the nightly trigger.
=> Modify build_release to match build_pr and remove ARM Deploy.

test/e2e-go/features/catchup/catchpointCatchup_test.go
Fix catchpoint unit test by extending timeout from 10 to 60 seconds.
Tested locally.
=> Fix rel nightly test by extending catchpoint round timeout

docker/build/Dockerfile, docker/build/Dockerfile-deploy
Fix the two docker files - avoid make deps step, which is no longer needed.
The compilation of go-algorand no longer requires the installation ( and therefore the validation ) of the dependencies.
=> fix docker builds: skip the `make deps`

catchup/service.go
Ensures that the catchup service have the network library load the DNS records before attempting the first sync - 
Current code was attempting to sync without any DNS records available, failing, and trying again later on. Since the DNS records were being refreshed every 60 seconds, the third or fourth attempt would be successful. This PR attempt to give the catchup service a good chance of succeeding on the first attempt.
=> catchup: speedup initial node DNS bootstrap time

config/consensus.go, data/transactions/logic/README_in.md, data/transactions/transaction.go, data/transactions/transaction_test.go, test/scripts/e2e_client_runner.py
Apps have been able to use 1k space for each of their programs since apps were introduced in v24.  But clear state programs are quite small.  It is more useful to provide 2k of space, divided however the app prefers.  This PR does that, including giving 2k extra space for each unit of "extra pages" requested at app creation time.
Tests considering before and after consensus updates.
=> Combine Clear and Approval Program size limits

docker/build/Dockerfile, docker/build/Dockerfile-deploy, docker/build/cicd.alpine.Dockerfile, docker/build/cicd.centos.Dockerfile, docker/build/cicd.ubuntu.Dockerfile, scripts/release/mule/Makefile.mule
Recent refactoring has changed dependency installation. ci-deps did not appear to be used in a meaningful way, so it was removed from the Makefile and Dockerfiles. Additionally, downloading from go has become unstable, so updating the GOPROXY options should help.
Run build pipeline against branch and verify this works.
=> Remove ci-deps and update GOPROXY in Dockerfiles

test/e2e-go/features/auction/auctionCancel_test.go, test/e2e-go/features/auction/auctionErrors_test.go, test/e2e-go/features/auction/basicAuction_test.go, test/e2e-go/features/compactcert/compactcert_test.go
They need work and shouldn't block our releases since they features aren't currently in use/enabled
I ran these tests locally and saw that they all got skipped
=> Disable compact certs and auction tests

scripts/release/mule/common/get_channel.sh
The way that the new pipeline scripts computed channel did not account for the rel/nightly branch, which should set the channel to nightly. This was preventing rpm and deb binaries from being built. This change identifies if the TRAVIS_BRANCH env is set to rel/nightly, and if so, will set the channel to nightly.
Verified with: `TRAVIS_BRANCH=rel/nightly ./scripts/release/mule/common/get_channel.sh devnet` which returned nightly. Specifying 'betanet', 'testnet', and 'mainnet' remain the same. 
Should verify with a nightly build using the new pipeline.
=> If the branch is rel/nightly set channel to nightly

config/consensus.go, daemon/algod/api/server/v2/dryrun_test.go, data/basics/teal.go, data/basics/teal_test.go, data/basics/userBalance_test.go, data/transactions/logic/evalStateful_test.go, ledger/accountdb_test.go, ledger/appcow.go, ledger/appcow_test.go, ledger/catchpointwriter_test.go, test/scripts/e2e_subs/app-key-value-128.sh, test/scripts/e2e_subs/tealprogs/approve-all.teal, test/scripts/e2e_subs/tealprogs/state-rw.teal, test/scripts/e2e_subs/v26/app-value-under-64.sh
Combine the limits enforced on keys and values in Teal such that there is a 128 byte limit on a key/value pair, rather than a 64 byte limit on each.  The previous method meant app creators/users were essentially paying for ("renting") space that might be used by keys, but rarely was, and even if it was,  could serve little purpose.
=> combine app state key/value size limits

txnsync/exchange.go, txnsync/incoming.go, txnsync/msgp_gen.go, txnsync/outgoing.go, txnsync/txngroups.go, txnsync/txngroups_test.go
Use the cgo library in `util/compress` for txnsync msg compression
Rerun unit tests
=> Use cgo deflate compression for txnsync msgs

util/compress/deflate.go
This code change is pretty trivial, ensuring to use C.size_t instead of C.ulong, which is cross-platform compatible.
Unit tests for these already exists.
=> txnsync: fix building on windows

config/consensus.go, data/transactions/transaction.go, data/transactions/transaction_test.go
Along the lines of similar "combine" PRs, this allows AVM code to access a *total* number of "foreign" references, as opposed to limiting each one individually.
=> Allow AVM code to access a max number of foreign refs.

test/e2e-go/features/catchup/catchpointCatchup_test.go
Temporarily disabled TestBasicCatchpointCatchup and reset test timeouts from 60 to 10 seconds.
Disabled TestBasicCatchpointCatchup test until the failure is resolved to keep this from blocking the rel/nightly build. 
Tested locally to ensure that the test file runs successfully.
=> Temporarily disabled TestBasicCatchpointCatchup test

node/node.go, node/txnSyncConn.go, txnsync/emulatorCore_test.go, txnsync/incoming.go, txnsync/mainloop.go, txnsync/peer.go, txnsync/service.go
This PR follow the original design, establishing low and high watermarks for the transaction pool levels. The transaction sync would stop requesting transactions once the transactions count is above the high watermark, and would resume accepting messages once the transactions count drops below the low watermark.
1. Manual S1 testing and reviewing of log files.
2. Use bandwidth tests to observe differences.
=> txnsync: add support for transaction pool saturation

daemon/algod/api/server/v2/account.go, daemon/algod/api/server/v2/account_test.go
The JSON return value of the `/v2/accounts/{addr}` endpoint represents an account with several arrays which are populated from Go maps (such as held assets, created apps, etc.). Currently these arrays are unordered, meaning every time you query this endpoint, you'll likely receive a response with a different ordering of these arrays. This makes SDK testing more difficult than it needs to be, since different responses cannot be directly compared to each other.
This PR sorts the slices in `generated.Account` so that the `/v2/accounts/{addr}` endpoint will always produce arrays with deterministic order.
I don't believe any change to our API spec is necessary, since the object being returned still adheres to the spec, but now the implementation does not randomize the order of arrays on every …
=> Make account endpoint produce deterministic JSON

data/transactions/logic/assembler.go, data/transactions/logic/eval_test.go
Fixes crash that should be a clean error report for using `substring` wrong.
Unit tests added to confirm and prevent regression.
=> report substring missing immediates properly

logging/telemetryspec/metric.go, node/node.go, node/txnSyncConn.go, txnsync/bloomFilter.go, txnsync/bloomFilter_test.go, txnsync/emulatorCore_test.go, txnsync/emulatorNode_test.go, txnsync/emulator_test.go, txnsync/incoming.go, txnsync/mainloop.go, txnsync/msgbuffers.go, txnsync/msgorderingheap.go, txnsync/outgoing.go, txnsync/peer.go, txnsync/profiler.go, txnsync/service.go, txnsync/txngroups.go
This PR optimize the message encoding and decoding by - 
1. For decoding, it moves the decoding to be executed within the incoming message call from the network stack. This would  give the mainloop thread more CPU time, and allow us to perform the incoming message decoding in parallel.
2. For encoding, we use the execution pool to asynchronously encode the message and send it to the network.
3. Use message buffers ( sync.Pool ) in order to avoid allocating memory for message data. This is particularly valuable for relays, which keeps allocating/releasing memory.
=> txnsync: optimize message encoding & decoding queue

config/consensus.go, data/transactions/transaction_test.go, ledger/apply/keyreg_test.go, ledger/apply/payment_test.go, node/node.go, protocol/consensus.go, test/e2e-go/features/participation/overlappingParticipationKeys_test.go, test/testdata/nettemplates/ShortParticipationKeys.json
* TEAL v4
* Larger programs
* Larger app/asset lookup limits
* Longer asset URL
* Fee pooling within a group
* Keyreg txn additional checks
Removed InitialRewardsRateCalculation and PaysetCommit from vFuture since it is already in v26
Fixed some tests after exposing zero fees and strict keyreg as current consensus
=> Introduce V28 consensus version

ledger/applications_test.go, ledger/ledger_test.go
The test had two unrelated bugs:
1. We need to call `WaitForCommit` before `reloadLedger` to ensure the block is being written to disk before the blockQ getting reinitialized ( and loose its content ).
2. The calculation of the total rewards unit in `makeNewEmptyBlock` was wrong. I corrected it. For tests that run only one or two rounds, this might be good enough, but for long-running tests, it would start fail pretty quickly.
Run using travis to confirm fix.
I was able to repro this locally by running 500 times consecutively. After the fix, I was no longer able to reproduce the failure.
=> testing: fix random failure in TestAppEmptyAccountsLocal

agreement/player_permutation_test.go
This made it easier for me to understand the different 7 initial player states * 14 simulated events when reading through each permutation's expected actions. I hope the enum names I picked are accurate — would appreciate any feedback on better names.
This updates an existing test.
=> Add enums to player permutation tests

txnsync/bloomFilter.go, txnsync/incoming.go, txnsync/msgp_gen.go, txnsync/peer.go
The txsync profiler shown that the selectPendingTransactions takes longer-then-desired computation time. To improve that, this PR adds the following:
1. add tracking of the lastTransactionGroupCounter per each set of request params and bloom filter. Together, these would prevent redundant scanning of the pending transactions, and would allow controlled number of iterations when scanning for previously-missed-transactions.
2. extract the loop over the bloom filters outside of the pending transactions loop, so that we need to iterate on these only once, and extract only the bloom filter indices that are relevant.
3. fix a bug in the `decodeBloomFilter` which failed to update the encoding params.
=> txnsync: optimize selectPendingTransactions loop

ledger/lruaccts_test.go
lruAccounts write function benchmark
=> added benchmark to lruAccounts write function

catchup/catchpointService.go, catchup/peerSelector.go, catchup/peerSelector_test.go, catchup/service.go, test/e2e-go/features/catchup/catchpointCatchup_test.go
peerSelector.go: various bug fixes
- introduce peerSelectorPeer to wrap the network.Peer and add peerClass information, to be able to distinguish between peers of the same address but different classes.
- keep track of download failures to be able to exponentially increase the cost of each failure when failing more than succeeding. This is to evict the peer faster when constantly failing to download.
- initialize rankSum and rankSamples to initialRank of the class. Otherwise, the peer rank will have a very long warmup time before relfecting the correct rank.
- let resetRequestPenalty bound the rank within the class bounds. Otherwise, the penalty calculation pushes the rank out of the class bounds (bug).
- getNextPeer, rankPeer, and peerDownloadDurationToRank are local to the package, …
=> Fixes to peer selector and TestBasicCatchpointCatchup

data/transactions/logic/README.md, data/transactions/logic/TEAL_opcodes.md, data/transactions/logic/doc.go
Specify that the truncated division is used (https://en.wikipedia.org/wiki/Modulo_operation#Variants_of_the_definition)
Just a minor change in documentation.
=> Specify truncated division is used in TEAL

daemon/algod/api/server/v2/account.go, daemon/algod/api/server/v2/account_test.go, daemon/algod/api/server/v2/test/helpers.go
Make extra-program-pages and apps-total-extra-pages optional in order to do not exposing them before the protocol switch.
Existing tests updated
=> REST API: make extra-program-pages and apps-total-extra-pages optional

network/wsNetwork.go
Existing `messageHandlerThread` was checking that all the connected peers are properly communicating by examining their recent message timings. This implementation served us well - however, it was executed redundantly. How much redundantly ? 19 times too many every 3 minutes ( and all of them at the **exact** same time.. ).
This PR ensures that all the `messageHandlerThread` shares the same ticker for testing the `checkPeersConnectivity`. This is expected to reduce the pressure on the internal `peersLock`.
=> network: reduce unneeded contention around checking the peers connectivity

util/metrics/segment_test.go
Improve TestMetricSegment test reliability by repeating the test with incrementing time delays.
This implementation would allow faster execution on faster platforms, and allow fallback for slower platforms.
Tested locally as well as on travis CI.
=> Improve TestMetricSegment test reliability

catchup/service_test.go, test/e2e-go/features/catchup/catchpointCatchup_test.go
These tests were temporarily disabled while we were troubleshooting the pipeline. As we are actively fixing these, we should re-enable these tests.
N/A, these are tests, and are expected to fail. I don't think they run during a standard PR test, however.
=> Restore TestPeriodicSync and TestBasicCatchpointCatchup tests.

scripts/buildtools/install_buildtools.sh, scripts/travis/test.sh
I forgot the "-o" option for specifying one package to install. Added the missing flag and made the install_buildtools.sh command stricter about extra positional arguments.
Check the CI output and ensure the extra packages are not installed.
=> testing: fix gotestsum install

.travis.yml, scripts/travis/build_test.sh, scripts/travis/run_tests.sh, scripts/travis/travis_retry.sh, scripts/travis/travis_wait.sh
Remove the top-level retry command. This will allow build / lint failures to terminate the build with no retry, and may speed up test failure retries.
CI
=> testing: move travis_retry to skip rebuilding

logging/telemetryhook.go, logging/telemetryhook_test.go
Fix and re-enable async telemetry unit test TestAsyncTelemetryHook_CloseDrop.
Manual, use travis-CI to validate.
=> testing: fix telemetry unit tests

scripts/install_linux_deps.sh
Add Fedora deps into `install_linux_deps.sh`
`./scripts/configure_dev.sh` runs well now
=> Add Fedora support into install_linux_deps.sh

data/transactions/logic/fields.go, data/transactions/logic/fields_test.go
We [exposed](https://github.com/algorandfoundation/specs/pull/37/files#diff-9b783466d1b1961a07008f11e6537b45242a2fdb9679612cf0576191641c19f1R237) `Assets` and `Applications` in TEAL v3 but did not update doc/langspec. This commit fixes it.
Added a test checking `TxnaFieldNames` (used only in doc) against `txnaFieldSpecByField` (used in code)
=> Add missing txna allowed args to doc and langspec

data/bookkeeping/genesis.go, data/bookkeeping/msgp_gen.go, data/pools/transactionPool.go, gen/generate.go, gen/walletData.go, netdeploy/network.go, node/node.go, test/e2e-go/features/transactions/sendReceive_test.go, test/testdata/nettemplates/DevModeNetwork.json, util/timers/frozen.go
Add new local private network mode - devmode. devMode allows the developer to deploy a single node network, where every transaction being sent to the node automatically generates a new block.
This feature is focused primarily around 3rd parties that want to test their solution on the Algorand platform, without waiting for the network to make progress.
Add e2e test to test changes.
=> Add initial devMode support

catchup/catchpointService.go, catchup/service.go
The handing for returned peer was incorrect in case the `getPeerErr` is non-nil, as we would attempt to dereference the nil pointer.
Issue was found on travis-ci, and fix was confirmed by travis-ci.
=> catchup: fix potential nil dereferencing

docker/build/Dockerfile-deploy
The deploy_linux_version.sh script currently creates a linux version of the current project tree with the same architecture as the hosting environment.
When we attempt to builds on M1 Macs, it default to arm64 base images and as a result - makes a linux/arm64 compatible binaries. These resulting binaries, however, would not work correctly on an algonet deployed network, since the hosts there are amd64.
To rectify that situation, we'll be changing the docker file to ensure linux/amd64 binaries are generated. This would ensure that the existing functionality works as intended. In the future, when we would add arm64 support for algonet, we could accompany that by creating corresponding images on docker as well.
Tested manually that amd64 compatible binaries were built.
=> testing: ensure deploy_linux_version generates a linux/amd64 binaries for algonet usage

test/e2e-go/features/multisig/multisig_test.go, test/e2e-go/features/participation/onlineOfflineParticipation_test.go, test/e2e-go/features/participation/participationRewards_test.go, test/framework/fixtures/restClientFixture.go, test/testdata/nettemplates/OneNode.json, test/testdata/nettemplates/TwoNodesOneOnline.json
TestNewAccountCanGoOnlineAndParticipate was failing because the test was not waiting enough to get to the round where the newly funded account's funds will be considered for proposing purposes.
- Fixed the calculation of the round when the refunded account can propose. 
- Fixed the way the rounds were considered for deciding when the account is funded, which was prone to race conditions.
- The test was using WaitForRoundWithTimeout which may be very slow if the current round is already ahead. Instead, replaced it with ClientWaitForRound, which does not care if an individual round is delayed.
- Changed the configuration parameters so that the refunded account proposes sooner than the default config values. This is to avoid waiting to round 320. 
=> Fix and enable TestNewAccountCanGoOnlineAndParticipate

docker/releases/build_releases.sh, scripts/release/mule/deploy/docker/docker.sh
The scripts to update the docker repository do not do a full rebuild, and the submitted Dockerfile does not change. This means that if you run the docker image/repo update, it'll re-use the old image. To fix this, we call docker build with --no-cache. Other refactoring helps simplify the code.
We add a new `--cached` flag to the `docker/releases/build_releases.sh` script to explicitly cache. Otherwise the testnet update would issue a full rebuild. We additionally automatically handle the 'latest' tagging in build_releases.sh as well.
Ran the update for betanet and mainnet/testnet, which seemed to update the container appropriately.
=> Fix docker repo update

daemon/algod/api/server/v2/dryrun.go, daemon/algod/api/server/v2/dryrun_test.go
This PR fixes a typo in the dryrun code that caused certain dryrun requests containing multiple transactions to fail.
- A dryrun test containing multiple transactions to show that the bug is now fixed.
=> Initialize past side effects with correct length during dryrun requests

test/e2e-go/features/participation/participationRewards_test.go
TestPartkeyOnlyRewards was disabled on darwin. 
It is no longer failing on darwin (5/5 runs passed). 
This is an existing test which was disabled on macos. Enabling here. 
I ran locally 5 times and it never failed.
=> enable TestPartkeyOnlyRewards on macos

.travis.yml, scripts/travis/build_test.sh, scripts/travis/run_tests.sh
We started seeing the 10-minute timeout error on travis after the recent changes to where travis_retry gets called.
This means travis_wait is still needed. travis_wait and travis_retry don't play well together on the ephemeral build machine, so we basically need to rollback the entire change in #2324 
Note: while making this change I noticed that we don't use travis_retry for all of the build_test.sh / integration_test.sh entries. Not sure why but I left them as they were before #2324 
CI
=> Fix 10 minute timeout in travis. (Revert parts of #2324)

network/wsNetwork.go, network/wsNetwork_test.go
Allow parsing of ipv6 localhost -colon- port address.
"[::]:4601" was failing to parse. This and other forms pass ParseHostOrURL() now. 
Added unit test for previously uncovered `ParseHostOrURL()`
=> allow to parse ipv6 localhost "[::]:4601"

agreement/service_test.go
The test TestAgreementSynchronous10 is failing. We should be fixing it, but until we do that, I'm going to disable it so it won't mask other issues.
Disable the test.
=> testing: avoid running TestAgreementSynchronous10 on nightly build

ledger/accountdb_test.go
The `randomFullAccountData` method was dividing by `lastCreatableID` which could be zero.
The probability for that is pretty slim, but given that it was found during a travis run, we should fix it.
=> testing: avoid division by zero during TestBasicCatchpointWriter

data/transactions/logic/assembler.go, data/transactions/logic/eval_test.go
Adds a Teal pseudo-op `selector` that assembles as if it were the `byte` pseudo-op, but stores 4 bytes of hash.
This allows Teal, like:
```
txn ApplicationArgs 0
selector "add(uint64,uint64)uint128"
==
bnz add
```
and avoid the need to embed the actual hash in a .teal file (which would also require calculating it)
Unlike `byte`, the argument *must* be a quoted string - no base64 or hex allowed, as the argument should be a method signature.
=> selector pseudo-op in support of ABI

network/wsNetwork.go, network/wsNetwork_test.go
A regex was trying to match valid DNS names but missed the '-' char. Fix.
Added unit test case.
=> fix regex for matching charset of valid DNS hosts, add test

network/netprio.go, network/wsNetwork_test.go
The peers array is modified when adding/removing entries from it. When that does happen, we increase the `peersChangeCounter`, so that the broadcast method would know that it's peers list need to be refreshed.
The said update was missing from `prioTracker.setPriority`, which was causing the issue.
The existing test provide sufficient coverage ( as it was able to detect the issue ).
=> testing: Fix random failure in TestWebsocketNetworkPrioLimit

catchup/peerSelector_test.go
Both the `TestPeersDownloadFailed` as well as `TestHistoricData` were randomly failing, as they were depending on a "genuine" random distribution of the random function in order to succeed. When that doesn't happen, they were failing.
This PR make sure to "bake-in" the random seed so that the tests are repeatable and a success is repeatable as well.
These are testings.
=> testing: make TestPeersDownloadFailed and TestHistoricData predictable

protocol/codec_tester.go
This PR improves the `checkBoundsLimitingTag` method of the message pack random generated object tester.
With this change, we're no longer ignoring data types that has no struct tags, but rather looking for corresponding msgp directives.
This is the same change applied to the feature/txnsync branch. This change is expected to be nop on the master branch, but would be required on the feature branch.
=> testing: improve msgp codec testing

catchup/service_test.go
The waiting period wasn't long enough. Allow much longer wait period before giving up.
Also - omit unneeded log entries.
=> testing: Fix random failures in TestPeriodicSync

catchup/service_test.go
Use periodicSyncLogger in a test to avoid unnecessary log outputs. 
This is a change to a test.
=> use periodicSyncLogger for cleaner test runs

scripts/travis/build_test.sh
Travis nightly build failed due to no-output for over 10m from build process.
Run on travis.
=> build: fix travis nightly build failure

data/transactions/logic/eval.go
Changes a helper function name from opExtractNBits to opExtractNBytes to reflect actual behavior.
=> Minor change to rename helper function in Extract ops

catchup/service.go
In current logic, the agreement is sending a notification to the catchup whenever it sees a cert vote
threshold without a corresponding block. When this happens on a round that is no longer supported
by the current binary, it would lead to continues requests for the said block. This PR addresses the issue
by testing if the coming block is expected to be supported or not. In case we know that it won't be supported,
we avoid downloading it entirely.
Use existing testing.
=> Avoid requesting unsupported blocks by the ensure digest catchup path

protocol/codec_tester.go
lookup in no-GOPATH locations for packages in gocodec testing; The existing code is trying to use the GOPATH as the base for the packages directories, however, this might not be the case when tests are being executed on travis.
=> testing: lookup in no-GOPATH locations for packages in gocodec testing

config/config.go, config/local_defaults.go, installer/config.json.example, test/testdata/configs/config-v17.json, txnsync/incoming.go, txnsync/logger.go, txnsync/outgoing.go, txnsync/service.go, txnsync/service_test.go, txnsync/txngroups.go
Add a new config option `EnableVerbosedTransactionSyncLogging` ( defaults to false ), to allow us to control whether we want to log incoming/outgoing messages. These messages are being sent at a high frequency ( especially on relays ), and would bloat the `node.log` file very quickly.
Unit tests updated.
=> txnsync: reduce the amount of logging

data/transactions/logic/assembler.go, data/transactions/logic/assembler_test.go, data/transactions/logic/eval.go, data/transactions/logic/evalStateful_test.go, data/transactions/logic/eval_test.go, data/transactions/logic/opcodes.go
This PR changes the way we check our understanding of the stack during
assembly.  We try to give errors as we assemble, based on the types
that we believe are on the stack when we assemble an opcode that has
stack expectations.  Previously, we *only* check the very top of the
stack, since almost all opcodes only looked at or modified the top. In
addition, we were very conservative with opcodes that manipulated the
stack.  For example, once we assembled a `swap` we only knew that the
top of the stack was [any, any]. If the top was [int, bytes], we lost
track.  Now we know the stack after that is [bytes, int].
Several opcodes still need this enhancement. "dig" and "swap" are
done, and serve as examples.  The following should be done next:
`dup`, `dup2`, `cover`, `uncover`.
Slightly …
=> Infrastructure to check AVM stack manipulation opcodes better

txnsync/exchange.go, txnsync/incoming.go, txnsync/msgp_gen.go, txnsync/msgp_gen_test.go
These changes add fields to the txnsync msgs in order to support sending proposals using the txnsync. For now, the txnsync message handler ignores all messages of this type.
=> txnsync: Add fields to txnsync msgs for proposal sending

data/transactions/logic/assembler.go, data/transactions/logic/assembler_test.go
I'm probably doing something wrong in my code somewhere* but started getting no response from remote compile.  Tracked it down to one of the bytec functions that does check the slice it accesses is long enough but doesn't bail, so it panics.
Took the liberty of adding returns to the other functions in the area but I don't feel confident enough to add them elsewhere. 
*had a pushbytes with no arg
I didn't
=> Addressing panic in assembler

agreement/asyncVoteVerifier.go, agreement/cryptoVerifier.go, agreement/pseudonode.go, agreement/pseudonode_test.go
While running a longevity tests on the transaction sync feature branch, the following issue showed up on some of the participating nodes : 
```json
{"file":"actions.go","function":"github.com/algorand/go-algorand/agreement.pseudonodeAction.do","level":"error","line":386,"msg":"pseudonode.MakeVotes call failed(attest) pseudonode input channel is full","time":"2021-07-19T13:28:35.078410Z"}
```
Digging further, it seems that both `pseudonodeVotesTask.execute` as well as `pseudonodeProposalsTask.execute` could lead to this situation ( same issue ). There are two distinct issues in the current implementation that have been addressed in this PR:
1. The call to `verifyVote` might silently fail. In that case, the caller ( i.e. the `execute` method ) would still expect to find the result in the …
=> txnsync: avoid pseudonode execution goroutine hang

scripts/release/mule/package/rpm/package.sh
A recent update broke the path to the spec file for rpm building.
Verify with a rel/beta build.
=> Fix path to spec file for rpm builds

scripts/release/mule/test/test.sh
In rpm package testing, dnf is not always installed. Check to see if it's available; otherwise fall back to yum.
Tried it on current rel/beta branch and it worked.
=> Install with dnf if present, otherwise fallback to yum

network/wsPeer.go, node/txnSyncConn.go
This PR address a deadlock between the `SendPeerMessage` and network package in the following scenario:
1. The `SendPeerMessage` is calling the peer `Unicast` method, passing a custom callback method.
2. The `Unicast` method returns nil, and the `SendPeerMessage` returns.
3. The network peer is failing to enqueue the message, making the call to the custom method specified in `SendPeerMessage`.
4. The custom method makes a call to the txsync, and concludes that the network connection need to be disconnected.
5. The custom method calls network's `Disconnect`, passing the peer.
At that point, the network package would block the `Disconnect` until the peer is disconnected. However, since the sending loop call is blocked due to the call to the callback method, the peer's `CloseAndWait` would …
=> txnsync: avoid deadlock when disconnecting from network peer

node/node.go
The current code would not pass the `DisableNetworking` flag to the network package. This could be worked around by adding the `DisableNetworking` to the `config.json` file, or with this fix.
=> bug: disable networking on devmode

.golangci.yml, agreement/proposal.go, catchup/service.go, cmd/goal/account.go, cmd/tealdbg/cdtState.go, cmd/tealdbg/localLedger.go, debug/doberman/main.go, ledger/acctupdates.go, logging/log.go, logging/telemetry.go, rpcs/blockService.go, rpcs/ledgerService.go, shared/pingpong/accounts.go, shared/pingpong/pingpong.go, test/e2e-go/cli/tealdbg/cdtmock/main.go, test/framework/fixtures/libgoalFixture.go
The [ineffassign](https://github.com/gordonklaus/ineffassign) linter is in the default set of linters enabled by golangci-lint but wasn't added in #2523 because it was reporting issues.
It's also one of the least objectionable linters; ineffectual assignments are rarely intentional and can point out bugs related to assumptions that a variable assignment had some effect.
There were various fixes here but I'm not sure if all the changes to remove or fix ineffectual assignments were the right ones.
Existing tests should ideally pass.
=> Enable ineffassign linter and resolve its errors

.circleci/config.yml, scripts/configure_dev.sh, scripts/travis/configure_dev.sh
CircleCI VMs come pre-installed with homebrew and some of the taps and packages we need already set up, so skipping running update and tap and install for those pre-existing assets reduces each job by ~6 minutes each (x 4 jobs).
Should not impact tests, just make them run quicker
=> Use pre-existing homebrew state on CircleCI VMs

txnsync/peer.go, txnsync/transactionCache.go
The current code was rolling the `ackPendingTxids` slice by using append. This works correctly from functional standpoint, but require an additional allocation + copy. Given that this allocation appeared in the memory profiler, I'm going to defer to doing a plain copy and avoid the allocation completely.
=> txnsync: avoid reallocating pending transaction ids slice

go.sum, scripts/buildtools/go.mod, scripts/buildtools/go.sum
These shouldn't be there anymore after upgrading to msgp 1.1.48
=> Remove msgp 1.1.47 from go.mod/go.sum files

daemon/algod/api/server/v2/handlers.go, daemon/algod/api/server/v2/test/handlers_test.go, daemon/algod/api/server/v2/test/helpers.go, daemon/algod/api/server/v2/utils.go, protocol/codec_test.go, test/scripts/e2e_subs/serial/rest-proof-endpoint.sh
As #1699 demonstrates, api v2 uses `JSONHandle` that incorrectly encodes maps with numeric fields. Switching to `JSONStrictHandle` fixes the issue since it was specially created for this purpose.
A test added
=> Use strict json encoder in REST API v2 endpoints

package-deploy.yaml, package-test.yaml, package.yaml, scripts/release/build/rpm/docker.sh, scripts/release/build/stage/build/task.sh, scripts/release/build/stage/package/task.sh, scripts/release/prod/rpm/run_centos.sh, scripts/release/test/rpm/run_centos.sh
Remove old references to centos8 rpm packaging.  There is now a single package for both centos 7 & 8.
make clean, make install, make test.  Validate PR testing completes successfully.
=> Remove references to centos8 rpm packaging

.circleci/config.yml
Parameterize no_output_timeout and -short in the general commands on the circle config file to reduce duplicate code.
I did also increase the size of integration tests to large as I saw that we had errors in mac_amd64_integration, arm64_integration and arm64_integration recently but would run after manually rerunning from failure.
Tested it on a Pull request that would run the nightly and then tested the regular short tests once.
=> CircleCI: parameterizing no_output_timeout and -short

cmd/goal/messages.go, cmd/goal/node.go, installer/algorand@.service.template
Right now a system.json file is not created when setting up systemd through the setup-systemd.sh script. Therefore, users aren't letting their nodes know that the algod process will be managed with systemd. This change has the setup-systemd.sh script download the systemd system.json file and lets the user know they need to copy that into any systemd managed data directory.
I ran the script on a raspberry pi and saw that it worked.
=> Update systemd-setup.sh to install system.json

ledger/eval.go
Add a public `Eval()` function in ledger that Indexer can use. The function accepts a custom protocol config so that Indexer can override it to always get asset close amounts, as opposed to only when the protocol supports it.
Closes https://github.com/algorand/go-algorand-internal/issues/1211.
What kind of test can I write?
=> Add a public `Eval()` function for indexer

ledger/appcow.go, ledger/appcow_test.go, ledger/apply/application.go, ledger/apply/application_test.go, ledger/apply/apply.go, ledger/apply/asset.go, ledger/apply/keyreg_test.go, ledger/apply/mockBalances_test.go, ledger/assetcow.go, ledger/cow.go, ledger/cow_test.go, ledger/eval.go
Delete `Balances.PutWithCreatable()` and add new functions that notify the COW that a creatable was created or deleted. Coming up next is similar two functions for asset/application local state, needed by indexer.
=> Replace `Balances.PutWithCreatable()`

shared/pingpong/accounts.go, shared/pingpong/pingpong.go
Removes signing calls to KMD by creating internal hashmap and signing transactions locally.
Resolves #2644 
Tested using performance system.
=> replace the KMD usage in pingpong with direct signing

txnsync/mainloop.go, txnsync/mainloop_test.go
The condition to check if the `beta` parameter should be updated was incorrect causing beta parameter to not update even with increasing transaction rate. This PR fixes the condition.
=> txnsync: fix beta updation condition

test/scripts/e2e_subs/teal-app-params.sh, test/scripts/e2e_subs/tealprogs/quine.teal
I made a TEAL [quine](https://en.wikipedia.org/wiki/Quine_(computing)) to test the output of `app_params_get AppApprovalProgram` for the current program. It's mostly for fun but this does strengthen the tests for `app_params_get`.
That's all this is.
=> Create a quine to test `app_params_get AppApprovalProgram`

ledger/appcow.go, ledger/apply/asset.go, ledger/assetcow.go, ledger/cow.go, ledger/eval_test.go, ledger/ledgercore/statedelta.go
Indexer needs the list of deleted local creatable states. This PR adds this information in ledger's state delta.
Added unit tests.
=> Record modified local creatable states in state delta.

shared/pingpong/accounts.go, shared/pingpong/pingpong.go
algorand/go-algorand#2653 created some undesired performance regressions reported on the perf monitoring system. I'm rolling this change back so we can take it offline.
=> Revert "replace the KMD usage in pingpong with direct signing"

daemon/algod/api/client/restClient.go, libgoal/libgoal.go, test/e2e-go/features/transactions/txnsync_test.go, test/testdata/nettemplates/TwoNodes50EachWithTwoRelays.json, txnsync/incoming_test.go, txnsync/logger.go, txnsync/txngroups.go
This test sets up a network with 2 nodes and 2 relays. 
The two nodes send payment transactions.
For each transaction, the test checks if the relays and the nodes (including the node that originated the transaction) have the transaction in the pool (i.e. the transactionInfo.ConfirmedRound == 0).
The tests needs to check for the transactions in the pool fast enough before they get evicted from the pool to the block.
To achieve this, it sends transactions during the first half of the round period, to give the test enough time to check for the transactions. 
TxHandler processDecodedArray and syncState evaluateIncomingMessage
may execute at the same time.
When this happens, evaluateIncomingMessage reads transactionGroups to
count the number if transactions there. At the same time, …
=> txnsync: correctness e2e test

test/e2e-go/features/transactions/txnsync_test.go, txnsync/incoming.go, txnsync/incoming_test.go
This is a test for the totalAccumulatedTransactionsCount computation.
The code was added in https://github.com/algorand/go-algorand/pull/2686
Fix for a typo.
TestTxnSync failed randomly on CirlceCi.
Increasing the timeout to avoid that failure in txnsync_test.go
=> testing: Add a test for totalAccumulatedTransactionsCount computation

config/consensus.go, daemon/algod/api/client/restClient.go, data/basics/overflow.go, data/basics/units_test.go, ledger/apply/application.go, ledger/apply/application_test.go, libgoal/libgoal.go, protocol/consensus.go, test/e2e-go/features/transactions/app_pages_test.go
* Make sure there is no overflow on TotalExtraAppPages calculation + test
One new test for overflow check on subtract
=> Consensus upgrade for ExtraProgramPages fix

ledger/apply/application.go, ledger/apply/application_test.go
updateApplication does not enforce individual program length but looks like it should. This PR enforces that.
Added tests
=> Add individual program length checks into updateApplication

shared/pingpong/accounts.go, shared/pingpong/pingpong.go
The changes here replaces the KMD signing with direct signing, which improves the performance.
It also add a unique note to every transaction in order to avoid duplicate transactions.
Pingpong was manually tested.
=> testing: replace the KMD usage in pingpong with direct signing

ledger/acctupdates.go, ledger/applications_test.go
The problem was in `commitSyncer` goroutine that triggered `commitRound` in additional to controlled `commitRound` calls.
Fixed by closing deferred commits channel and waiting `commitSyncer` to exit.
Checked with -count 1000
=> Fix flaky ledger app tests that use commitRound directly

libgoal/libgoal.go
Passing a foreign app id to the `goal app create` cmd with dryrun tries to use ApplicationId (0) instead of the foreign app id.
=> using the appIdx instead of txn app id

test/e2e-go/features/transactions/messageRate_test.go, test/testdata/nettemplates/OneNodeTwoRelays.json, txnsync/mainloop.go
An end-to-end test to confirm that the txnsync message rate increases with the txn rate.
=> E2E test: txnsync message rate increases with txn rate

crypto/batchverifier_test.go, crypto/cryptoerror.go, crypto/multisig_test.go
update crypto library to use partitiontest
=> testing: update crypto library to use partitiontest

.circleci/config.yml, test/scripts/e2e.sh
Replaced SKIP_E2E_SUBS var and E2E_SUBS_ONLY var with E2E_SUBS var that has values of "ONLY" and "SKIP" as well as not set at all. We might need to add another value to this var in the future for another option.
Check if tests work correctly still.
=> Consolidate SKIP_E2E_SUBS and E2E_SUBS_ONLY

test/e2e-go/upgrades/rekey_support_test.go
* The test checks rekeying before and after upgrade but nodes running
as separate processes might upgrade earlier than the test advances
* This fix takes this into account similarly to the app upgrade tests
This is a test
=> Fix TestRekeyUpgrade test

config/consensus.go, data/transactions/logic/backwardCompat_test.go, data/transactions/logic/eval.go, data/transactions/logic/eval_test.go
* Commented some constants in teal evaluator and added a test
enforcing their values and directing on how to change them if/when needed.
Existing tests
=> Make config.MaxLogCalls dependant on some consensus param

test/scripts/e2e.sh
Fixing typo of one equal sign instead of two for integration tests
CircleCI Tests
=> testing: fixing a typo in e2e.sh for integration tests

cmd/goal/account.go, cmd/goal/accountsList.go, cmd/goal/application.go, test/e2e-go/cli/goal/expect/goalAccountInfoTest.exp, test/scripts/e2e_subs/e2e-app-extra-pages.sh
With this PR, the commands `goal app info`, `goal account info`, and `goal account list --info` now display the number of extra pages an application has.
For example, the following were executed on a private network where apps 1, 2, 3, 4 have 1, 2, 3, 0 extra pages, respectively.
```
$ goal app info --app-id 3 -d DATA_DIR
Application ID:        3
Creator:               U4SKWGT6KYRA3DCMVPJLMMMNCP35UOYBFMQLEHLYDHO4C4N7GU7LLNQUHU
Approval hash:         Q7ODX32ILHMGO6KPSELVTO7RCVOUZ37RWYHISAWER7GVARJGKTWEWD37AM
Clear hash:            P7GEWDXXW5IONRW6XRIRVPJCT2XXEQGOBGG65VJPBUOYZEJCBZWTPHS3VQ
Extra program pages:   3
Max global byteslices: 2
Max global integers:   1
Max local byteslices:  4
Max local integers:    3
```
```
$ goal account info -a …
```
=> Display extra pages in goal info commands

cmd/updater/update.sh
A user reported a strange and not very helpful error message. This was due to incomplete error handling in the bash script relating to a truncated `updater` binary.
The current workaround for this is to delete the `updater` binary and trigger `update.sh` to re-download it, but this is not obvious and I wouldn't expect any user to reach that conclusion.
This fix adds error handling in case `updater` fails and should fix this particular failure.
Here is the error message:
```
Current Version = 8590458880
Latest Version =
./update.sh: line 250: [: 8590458880: unary operator expected
New version found
Update Downloaded to /tmp/tmp.QlV71NLGFr/.tar.gz
Expanding update...
tar (child): /tmp/tmp.QlV71NLGFr/.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: …
```
=> Improve error message in update.sh when updater is corrupt.

.travis.yml
Codegen verification step is now being run by CircleCI, so it's no longer necessary to run it on Travis, especially since we recently got a `toomanyrequests: You have reached your pull rate limit.` docker error. We want to reduce unnecessary docker requests.
Will check the PR tests to make sure codegen is no longer run on Travis tests.
=> Remove codegen from travis file

cmd/netgoal/generate.go, netdeploy/remote/bootstrappedNetwork.go, netdeploy/remote/deployedNetwork.go, test/testdata/deployednettemplates/recipes/bootstrappedScenario/Makefile, test/testdata/deployednettemplates/recipes/bootstrappedScenario/boostrappedFile.json, test/testdata/deployednettemplates/recipes/bootstrappedScenario/genesis.json
parametrize account balance range for bootstrapping testing scenario.
=> add account balance range

network/wsNetwork.go, network/wsNetwork_test.go, test/e2e-go/cli/goal/expect/goalCmdFlagsTest.exp, test/e2e-go/cli/goal/expect/goalExpectCommon.exp, test/e2e-go/cli/goal/expect/goal_expect_test.go, test/e2e-go/cli/goal/expect/tealConsensusTest.exp, test/framework/fixtures/expectFixture.go
* ParseHostOrURL does not accepts ":xxx:123" anymore
* pingpongTest.exp is still disabled
Added new test cases for ParseHostOrURL: disallow ":xxx:123" and allow "::11.22.33.44:123"
=> Fix ParseHostOrURL and enable expect tests

data/transactions/verify/verifiedTxnCache.go, data/transactions/verify/verifiedTxnCache_test.go
The number of buckets in `verifiedTransactionCache` can be arbitrarily large depending on the requested cache size, and each lookup in the cache does that many map lookups. This PR limits the number of buckets to 3. Now, the lookup takes at most 3 lookups and the size overhead is 1.5.
Modified existing unit tests.
=> Limit the number of buckets in `verifiedTransactionCache` to 3

cmd/netgoal/commands.go
When creating large networks with bootstrapped databases ( 60m accounts ), the netgoal was failing due to a false-positive deadlock detection. Given that the netgoal is a testing utility, it would be better to turn off these false-positives testing off netgoal.
=> testing: disable deadlock for netgoal

test/e2e-go/cli/goal/expect/goalAccountTest.exp, test/e2e-go/cli/goal/expect/goalClerkGroupTest.exp, test/e2e-go/cli/goal/expect/goalNodeTest.exp, test/framework/fixtures/expectFixture.go
Status code differs on CircleCI. Relaxed the status code value check.
Change the skipped expect tests to be defined as "t.Skip" so we can track these as such on the log file.
=> Fix goalNodeTest.exp

rpcs/txSyncer_test.go
This fixes and enabled the test TestStartAndStop.
=> testing: fix TestStartAndStop

data/transactions/logic/assembler.go, data/transactions/logic/assembler_test.go, data/transactions/logic/debugger.go, data/transactions/logic/eval.go, data/transactions/logic/evalStateful_test.go, data/transactions/logic/fields.go, data/transactions/logic/fields_test.go
This also unifies a lot of field handling so that the code is less
susceptible to copy-paste errors, but it has a ways to go.  Hard to
both unify the handling of the different fields and use separate
types for each field index.  Lots and lots of interfaces could do. Or
generics in 6 months?  For the moment, each field type is a pile of
arrays and maps working together.
It's unclear what we gain from those separate index types, since
we *always* cast into the type just before using them, as we are
getting the indexes from reading a byte in bytecode.
New tests will catch this mistake if we make it again.
=> Ensure that AssetCreator is not used before proto.LogicSigVersion=5

test/e2e-go/cli/goal/expect/goal_expect_test.go
* After re-enabling we started seeing failures on other e2e-go tests
due to unsufficient resources to allow algod making new rounds
* Possible solution is to run expect tests as a separate stage on CI
go test ./test/e2e-go/cli/goal/expect/... -run TestGoalWithExpect
=> Disable expect tests again

data/transactions/logic/assembler.go, data/transactions/logic/assembler_test.go, data/transactions/logic/debugger.go, data/transactions/logic/eval_test.go
Disassemble was omitting labels if they were only used as targets of backjumps.
This fixes that, but making a second pass to find labels if any such labels exist in a program.  It also changes testProg, which is used extensively to test programs in the logic package, so that every such test is a Disassemble/Reassemble test to ensure the same program is produced.
=> Ensure disassemble/reassemble cycle works in testProg.

cmd/goal/account.go, cmd/goal/commands.go, test/heapwatch/client_ram_report.py, test/heapwatch/heapWatch.py, test/heapwatch/metrics_delta.py, test/heapwatch/nodeHostTarget.py, test/heapwatch/runNodeHost.py
new scripts runNodeHost.py and nodeHostTarget.py manage starting a new ec2 node with `algod` (or several) pointed at a specific relay so that we can test per-client usage on that one relay.
improve goal: don't crash if kmd isn't present when we don't need it
tweaks to other heapWatch scripts for measuring this data.
This is manual testing code. I used it to run test clusters.
=> per-client RAM measurement scripts

network/wsNetwork_test.go
TestSlowOutboundPeer was disabled after https://github.com/algorand/go-algorand/commit/ea855418b0b928435c0f883e3847456b938ab293
Changing the test to confirm to the new behavior and enabling it.
=> Fix and enable TestSlowOutboundPeer

ledger/eval.go
The current code creates an impression that the evaluator can be used for round 0 which is not true. This PR simplifies the code, so this is more evident.
Relying on existing tests.
=> Simplify `startEvaluator()`

ledger/appcow.go, ledger/appcow_test.go, ledger/cow.go, ledger/cow_test.go, ledger/eval.go, ledger/eval_test.go
We failed to override the consensus parameters in COW. This PR fixes it. Background: overriding of consensus parameters is used by Indexer to retrieve the asset close amount of a transaction even when the protocol doesn't support it.
Add a unit test.
=> Fix overriding consensus parameters in evaluator.

config/consensus.go, data/basics/userBalance.go, ledger/accountdb_test.go, ledger/apply/application_test.go, ledger/eval_test.go, ledger/ledger_perf_test.go, ledger/perf_test.go
As a temporary relief increase max number of opt ins to 50.
Also found and fixed an error check in new ledger testing harness.
* Unit tested ledger.apply and ledger.eval
Benchmark 1: create 100k accounts, 500 apps (no local data) and opt-in 10k accounts to max number of apps. Restart ledgers, measure a single block validation time of 50k pay transactions on random opted-in accounts.
| 10 opt ins | 50 opt ins | 100 opt ins |
|-----------|-----------|------------|
| 644 ms | 660 ms | 683 ms |
Benchmark 2: same as 2 but with full local data (16 keys each 64 bytes long with 64 bytes of value data)
| 10 opt ins | 50 opt ins | 100 opt ins |
|-----------|-----------|------------|
| 1.4 - 2.2 s |  9-16 s | ~20-25 s |
Benchmark 3: same as 2 but 5k txns per block
| 50 opt ins | 30 opt ins | 20 opt …
=> Increase max app opt ins to 50

data/transactions/logic/eval.go, data/transactions/logic/eval_test.go
Removes some code, but more importantly speeds up mulw considerably.
We have always charged 1 unit of cost for mulw, but it was actually
more expensive.  This fixes that.
A nice side-effect is that opPlus/opAddw and opMul/opMulw are
simplified and easier to follow.  Benchmarks confirm nothing is
slower (and mulw is ~5 times faster).
All tests of opAddwImpl and opMulwImpl have been retained by
conducting the same test with actual teal, instead of directly testing
those (now non-existent) functions.
=> Use math.bits intrinsics to simplify addw/mulw opcodes

data/transactions/logic/README.md, data/transactions/logic/TEAL_opcodes.md, data/transactions/logic/assembler_test.go, data/transactions/logic/doc.go, data/transactions/logic/eval.go, data/transactions/logic/eval_test.go, data/transactions/logic/fields.go, data/transactions/logic/fields_string.go
Add GroupID as an accessible global field in AVM.
Co-authored-by: Zach Langley <zachary.langley@algorand.com>
=> global GroupID

test/e2e-go/features/partitionRecovery/partitionRecovery_test.go
The expected round number is captured before the node stops. However,
it is likely that the node advances to the next round before it is
stopped. When this happens, the test will fail.
This change gets the most up-to-date round number after the node is
stopped, but before inducePartitionTime timeout is waited.
inducePartitionTime is the wait to make sure the expected behavior is
obtained. The round number is captured before this wait.
However, I could not identify in this PR why `TestBasicPartitionRecovery` has failed. Could not find anything in the test, and the failure logs have nothing. 
I suspect that the failure in the other tests triggered the failure, and fixed the other tests, but cannot be sure. 
As for the data race, it is fixed in #2844.
Fixes #2384 and #2545 
This is a fix for …
=> Fix partition recovery tests

txnsync/bloomFilter.go, txnsync/bloomFilter_test.go, txnsync/exchange.go, txnsync/incoming.go, txnsync/incoming_test.go, txnsync/msgorderingheap_test.go, txnsync/msgp_gen.go, txnsync/outgoing.go, txnsync/peer.go, txnsync/peer_test.go, txnsync/txngroups_test.go
Refactor the bloom filter implementation to have two "implementations" : `testableBloomFilter` and `bloomFilter`.
`testableBloomFilter` is used exclusively when being received from the network; it does not contain any encoded
fields, nor does it include `transactionsRange` which is used for generating new bloom filters.
`bloomFilter` on the flip side is used only for outgoing bloom filters. It doesn't support `testing`, and it contains only the encoded bloom filter ( and not the underlying bloom filter needed for testing, for instance ).
This separation allows us to ensure we don't store bloom filter object beyond the required scope, improving the memory utilization.
This PR does not introduce any new functionality. The existing unit tests were updated to use the updated constructs.
=> txnsync: bloom filter refactoring

data/transactions/logic/eval.go, data/transactions/logic/evalAppTxn_test.go, data/transactions/logic/eval_test.go
Intended to just increase coverage in AVM, but doing so found a
bug. (Go figure.)  tx_field should only allow actual addresses for
address fields, rather than low integers as references from the
Account array.
Lots more tests that increase coverage, especially for tx_field.
=> Increase coverage in AVM code. Bug fix in account fields of tx_field

txnsync/transactionCache.go, txnsync/transactionCache_test.go
Existing short term cache in the transaction sync was not supporting promoting updated cache entries.
In this PR, I have replaced the circulating buffer with a dual linked list to allow promoting cached entries.
Extend existing unit test
=> txnsync: Add linked list based short term lru cache

test/scripts/e2e_go_tests.sh
@algoidan noticed we were not running some non-expect e2e-go tests and we spotted this issue in the test script when checking the value of RUN_EXPECT.
Check to ensure non-expect e2e-go tests are run as expected.
=> fix issue with checking RUN_EXPECT when listing packages

txnsync/bloomFilter.go, txnsync/bloomFilter_test.go, txnsync/outgoing.go, txnsync/outgoing_test.go, txnsync/peer.go, txnsync/peer_test.go
On non-relays, exclude txid that were sent from the relay from the bloom filter sent to the relay.
This is expected to reduce the size of the bloom filters by 25%.
Unit tests updated.
=> txnsync: remove known txid from bloom filter

ledger/eval.go
Indexer needs to know all accounts referenced in a block to be able to read all of them in one batch. This PR creates a function that returns all such account addresses.
=> Add ledger.GetBlockAddresses()

cmd/tealdbg/localLedger.go, daemon/algod/api/server/v2/account.go, daemon/algod/api/server/v2/dryrun.go, daemon/algod/api/server/v2/dryrun_test.go
dryrun/tealdbg ledgers do not have block info so cannot provide correct value of `rewardLevel` used in balance calculation for `balance` opcode. Fixed by clearing `RewardBase` field in account data returned by dryrun/tealdbg ledgers.
The crash was [reported](https://forum.algorand.org/t/teal-rejection-error-panic-in-evaluation-overflowed-account-balance-when-applying-rewards/4294) at the community forum.
Test added
=> Fix dryrun crash on rewards calculation

cmd/tealdbg/local.go, cmd/tealdbg/local_test.go, daemon/algod/api/server/v2/dryrun.go, daemon/algod/api/server/v2/dryrun_test.go, test/e2e-go/cli/tealdbg/expect/tealdbgTest.exp
Set special addressed in EvalParams when evaluating from tealdbg/dryrun
Tests added
=> Enable debugging itxn programs

txnsync/bloomFilter_test.go, txnsync/incoming_test.go, txnsync/mainloop.go, txnsync/outgoing_test.go, txnsync/peerscheduler.go, txnsync/peerscheduler_test.go, txnsync/service.go
In `onTransactionPoolChangedEvent`, there is an action taken on every peer which is both in `s.interruptablePeers` and in `s.scheduler.peers`.
This is accomplished in the loop:
```
for _, peer := range peers {
peerNext := s.scheduler.peerDuration(peer)
```
where for each peer, the list of `s.scheduler.peers` is traversed when `peerDuration` is called. 
This is `len(peers) * len(s.scheduler.peers)` complexity. 
The task here is to make this operation linear instead of potentially a quadratic operation. 
A test is added.
=> Improve peerScheduler.peerDuration performance

network/phonebook_test.go
TestWaitAndAddConnectionTimeLongtWindow is randomly failing when the execution of time sensitive statements is separated by more than the expected time gap.
This issue is fixed by replacing the sleep with simulated time passing by changing the recorded time, thus giving the impression that the event happened timeout time ago. 
=> Fix random failures TestWaitAndAddConnectionTimeLongtWindow    

compactcert/worker_test.go
The unit test `TestLatestSigsFromThisNode` was data racing. The fix is trivial.
=> testing: fix unit test data race

ledger/acctupdates.go, ledger/acctupdates_test.go, ledger/appcow.go, ledger/appcow_test.go, ledger/catchpointwriter_test.go, ledger/cow.go, ledger/cow_test.go, ledger/eval.go, ledger/evalIndexer.go, ledger/eval_test.go, ledger/ledgercore/statedelta.go, ledger/txtail_test.go
The account totals are being tested once every round to ensure that the total amount of money in the system doesn't change. Prior to this PR, the accounts update newBlock method was responsible for testing that : this would ensure that we're not writing a new round to disk that violates the totals predicate.
While this was working correctly, conducting this test at the time we're writing this information to the disk is too late. By that time, we've already agreed upon applying this (problematic) block to disk. Ideally, we could detect this situation ahead of time, and avoid agreeing on a block which would violate the totals predicate.
In this PR, we've moving the totals calculation as the last step of the delta state calculation. Few thoughts:
- From security perspective, it's just as …
=> ledger: move account totals calculation to StateDelta

scripts/archtype.sh, scripts/ostype.sh, test/muleCI/Jenkinsfile, test/muleCI/mule.yaml
This PR is to take advantage of arm64's ability to run arm32 binaries. Using this, we are able to build for arm32 on arm64 hosts by running containers with arm32 OS's on them. This is much faster than our qemu set up because it doesn't rely on emulations. The binaries produced with this process work and the arm64/arm32 build times are as fast as the intel builds, reducing our build time by about an hour.
I ran our build pipeline against this branch using arm64 hosts and tested the produced artifacts using emulated cpu's to make sure they still work on their native architectures.
=> Support arm cross compile

catchup/universalFetcher.go, catchup/universalFetcher_test.go, ledger/ledger.go, rpcs/blockService.go
The test TestRequestBlockBytesErrors has failed, and the reason is unidentifiable.
Various fixes are here, including more verbose error reporting to identify the issue when it occurs again.
- Add waitgrop to ledger to wait before closing the ledger and blockQ when goroutines are using them.
- In universalFetcher, return the error immediately in case of an error.
- Proper closing of objects in TestRequestBlockBytesErrors, and more verbose error reporting.
The waitGroup is needed for the following situation:
in blockService.go listenForCatchupReq
When, immediately after calling `bq.handleCatchupReq`, `BlockService.Stop()` is called, `blockQueue` will be `nil` by the time `blockQueue.getEncodedBlockCert` is called. 
```
0  0x0000000004e16846 in …
```
=> TestRequestBlockBytesErrors: Various fixes

README.md
Creating my first PR of many others: there'll be other unsolicited grammar changes.
=> readme grammar change

ledger/evalIndexer.go
In the EvalForIndexer, we don't want to call finalValidation(). This would
skip the calculation of the account totals in the state delta, which is a serious
issue if it were to be used by algod, but it's perfectly fine for the indexer since
it doesn't track any totals and therefore cannot calculate the new totals.
Test against the indexer.
=> ledger: update EvalForIndexer to avoid totals computation

ledger/appcow.go, ledger/eval.go, ledger/evalIndexer.go, ledger/eval_test.go
The evaluator shouldn't ask the ledger who is the creator of an asset multiple times. This PR adds a cache for ledger's responses in cow base.
Added a test. Is there a better way to write a mock test?
=> Cache creators in cow base

compactcert/worker_test.go
Timing issues between writing to and reading from the database cause the test to occasionally fail.
Make the test more tolerant to such timing issues by polling.
This is a fix for a test.
=> testing: fix TestLatestSigsFromThisNode

test/e2e-go/restAPI/restClient_test.go, test/scripts/e2e_subs/e2e-logs.sh, test/scripts/e2e_subs/tealprogs/logs.teal
This PR moves the log e2e tests to scripts/e2e_subs. This dir is used by the indexer to build blocks and queries.
=> e2e tests for log

cmd/goal/application.go, cmd/goal/clerk.go, cmd/goal/commands.go, cmd/goal/common.go, libgoal/libgoal.go
* AVM 1.0 introduces application accounts
* `goal clerk` needs to consider this account when creates dryrun request object
* Added a new option `--dryrun-accounts` for adding accounts that were rekeyed to an app account (or any other accounts).
Tested manually. I'll add example from Jason W into sub-e2e tests in subseq PRs (need inner txns for indexer as well)
=> Add application account into a dryrun req created by goal

test/scripts/e2e_subs/app-assets.sh, test/scripts/e2e_subs/tealprogs/assets-escrow.teal
This PR adds e2e tests for axfer, acfg, and afrz inner txns.
=> e2e tests for axfer, acfg, and afrz inner txns

cmd/tealdbg/local.go, cmd/tealdbg/local_test.go
Enable cost and fee pooling in tealdbg
Tests added
=> Enable cost and fee pooling in tealdbg

test/heapwatch/metrics_delta.py
Fixes found during recent cluster bandwidth testing
This is test code for manual tests.
=> testing: metrics_delta.py fixes

data/transactions/logic/eval.go, data/transactions/logic/eval_test.go, ledger/appcow.go, ledger/ledgercore/error.go
Return a bit more details on eval failure for app calls.
Added `EvalContext.PcDetails()` method and tests.
=> Extended logic eval error

test/e2e-go/features/partitionRecovery/partitionRecovery_test.go
Disable the participation key refresh on the TestPartitionHalfOffline test. The test was failing with the following threads running:
```
algod(20739) : github.com/algorand/go-algorand/agreement.(*asyncPseudonode).loadRoundParticipationKeys(0xc0033dad20, 0x2, 0xc0039c8180, 0xc000530000, 0xc000dcb0d0)
```
```
algod(20739) : github.com/algorand/go-algorand/data/account.PersistedParticipation.DeleteOldKeys(0x92c6b21bbd8fefac, 0xed2d99ce769768ea, 0xac85a3b9466cead1, 0xc32937d7e4c532f9, 0xc000043260, 0xc0002b04b0, 0x0, 0x2dc6c0, 0x2710, 0xc0001892c0, ...)
```
```
algod(20739) : github.com/algorand/go-algorand/data.(*AccountManager).AddParticipation(0xc0001191a0, 0xd175b5d042fa1c39, 0x2140fe15c6a19653, 0xc66f7b9c58cf5ed1, 0x107d657815b44d49, 0xc0037a4d20, 0xc0002b0690, 0x0, 0x2dc6c0, 0x2710, …
```
=> testing: Disable the participation key refresh on the TestPartitionHalfOffline test

.circleci/config.yml
For CircleCI testing, increase machine size from medium to large and set parallelism to 4.
Testing by running nightly builds on the branch.
=> Increase machine size to large and use consistent parallelism for circleci nightly testing.

test/framework/fixtures/fixture.go
In testing.T, Error, Errorf, and Fail do not terminate the test.
Error and Errorf call Fail.
There will be another call to FailNow to terminate the test. (FailNow also calls Fail.)
When dontReportFailures is set in Error, Errorf, and Fail, the test will not be terminated.
Moreover, the subsequent call to FailNow will be ignored because of the set dontReportFailures flag.
In this change, dontReportFailures will not be set for Error, Errorf, and Fail so that the subsequent FailNow will terminate the test.
This issue is a fallout from https://github.com/algorand/go-algorand/pull/2844
Fixes #3020
This is a fix to the testing infrastructure.
=> Adjust the application of dontReportFailures in syncTest

data/pools/transactionPool.go
This PR addresses a regression introduced in https://github.com/algorand/go-algorand/pull/2983. 
The culprit is that an interface might contain a nil pointer, which makes it insufficient to test the interface pointer itself.
Fail cases: https://app.circleci.com/pipelines/github/algorand/go-algorand/2451/workflows/8807ced7-89ae-4b6b-96b0-1bc5bdf9d84c/jobs/27259/tests#failed-test-0
Use existing unit testing. In particular TestCatchupOverGossip.
=> ledger: fix regression in transaction pool

data/transactions/logic/assembler.go, data/transactions/logic/assembler_test.go
This type checking bug was discovered while using the TEAL debugger. A correction to typedDig() + improved unit tests were added.
Added new unit test and corrected existing one.
=> Fixed off-by-one error in the assembler's typeDig()

.circleci/config.yml
Fixing deploy pipeline in circleci
- including 2 required tests
- making sure environment variable for branch is correct
This should name the binaries correctly and put them in correct bucket
=> Fixing CircleCI deploy for Betanet and Stablenet (#3077)

ledger/accountdb_test.go, test/e2e-go/upgrades/stateproof_test.go, test/testdata/nettemplates/TwoNodesWithoutStateProofPartkeys.json
The test TestKeysWithoutStateProofKeyCannotRegister lets the nodes make progress until changes the consensus version.
The test passes when the consensus version changes to Future. However, the test starts from V29, and quickly gets to Future, passing through V30. Sometimes, the node progress is halted at V30, in which case the test fails. 
Also, in this change, reusing the client handle instead of regenerating one every time. 
TestAccountStorageWithBlockProofID broke after the merge with changes to the Master. 
This fixes it.
=> Fix for TestKeysWithoutStateProofKeyCannotRegister and TestAccountStorageWithBlockProofID

data/txHandler.go, network/wsNetwork.go, test/e2e-go/features/transactions/sendReceive_test.go
When a 2.1 (i.e. no txsync) client connects to a 3.0 relay (i.e. txsync), the relay needs to request the client to keep sending it a TX messages - otherwise, these transactions would not get propagated.
The 2.1 and 3.0 above are network protocol versions, not a algod release version.
e2e test added.
=> Fix missing TX registration

catchup/service.go
avoid requesting blocks that aren't needed by the ledger.
This isn't done for the sake of optimization - it's done so we won't have misleading warning messages in the log file due to frequently canceled contexts.
tested manually.
=> catchup: avoid requesting blocks that aren't needed by the ledger

data/txHandler.go
I noticed log messages like this:
```
{"file":"txHandler.go","function":"github.com/algorand/go-algorand/data.(*solicitedAsyncTxHandler).loop","level":"info","line":541,"msg":"solicitedAsyncTxHandler was unable to relay transaction message : %!v(MISSING)","time":"2021-10-20T23:18:40.220089Z"}
{"file":"txHandler.go","function":"github.com/algorand/go-algorand/data.(*solicitedAsyncTxHandler).loop","level":"info","line":541,"msg":"solicitedAsyncTxHandler was unable to relay transaction message : %!v(MISSING)","time":"2021-10-20T23:18:40.220226Z"}
{"file":"txHandler.go","function":"github.com/algorand/go-algorand/data.(*solicitedAsyncTxHandler).loop","level":"info","line":541,"msg":"solicitedAsyncTxHandler was unable to relay transaction message : …
```
=> Add err to solicitedAsyncTxHandler.loop log message

data/account/participationRegistry.go, data/accountManager.go, node/node.go, util/db/initialize_test.go
Minor cleanup for PKI branch merge into master.
N/A
=> PKI TODO comments + fix import order.

ledger/internal/eval.go, ledger/internal/evalindexer.go
1. It doesn't make sense to calculate new totals in `finalValidation()`
2. `endOfBlock()` already does some validation
Moving the content of `finalValidation()` to `endOfBlock()` makes things more reasonable.
=> ledger: do final validation in `endOfBlock()`

txnsync/encodedgroups_test.go, txnsync/encodedgroupstypes.go, txnsync/exchange.go, txnsync/incoming.go, txnsync/service.go, txnsync/txngroups.go, txnsync/txngroups_test.go
Change constants in the txnsync around message size limits into variables based on maxTxPoolSize. This will allow for support of larger message sizes when dealing with larger load.
Reran existing tests
=> txnsync: Use dynamic maxEncodedTransactionGroups

data/account/participation.go, libgoal/participation.go, node/node_test.go, test/e2e-go/features/transactions/onlineStatusChange_test.go
FillDBWithParticipationKeys will return empty PersistedParticipation when lastValid is less than firstValid.
When this happens, newPart will not have partdb in newPart.Store, instead, will have an empty object.
Calling Close on the empty object will call close on nil Accessor pointer and panic.
This change avoids using the returned object with non-nil error, and properly closes the db with the valid object.
Added test to verify the proper handling of the different errors returned from FillDBWithParticipationKeys and handled by GenParticipationKeysTo.
=> Fix panic on closing nil db 

crypto/batchverifier.go
"on" -> "one" in ErrBatchVerificationFailed
CI checks succeeded, should be enough for a small change
=> Fix typo in batchverifier.go

ledger/internal/eval.go
Going to ledger directly prevents caching of accounts.
I'm looking into poor indexer import performance on testnet at rounds > 17M, and I noticed that one account is looked up a lot of times in same round.
=> `roundCowBase`: use `lookup()` instead of going to ledger directly

cmd/goal/clerk.go, cmd/goal/multisig.go, cmd/pingpong/runCmd.go, daemon/algod/api/server/v2/handlers.go, data/transactions/logic/assembler.go
This PR adds the assembly error strings so developers can see which errors were present in the program when calling the API. Prior to this change, the API only reported the number of errors in the program.
Closes #3082 .
Tested on sandbox.
Example program:
``` 
#pragma version 7
int v
```
Example response:
```
algosdk.error.AlgodHTTPError: 1: unsupported version: 7
2: strconv.ParseUint: parsing "v": invalid syntax
```
=> Report assembly error strings for compile API endpoint 

.circleci/config.yml
The dilithium branch has added tests that sometimes hits the no_output_default 30m timeout for test jobs. This lets those jobs complete so we can better understand their performance impacts. Otherwise we don't get much information to work with.
It also adds a change to gotestsum to print the name of the test before running it, so if your test does not finish, you will see its name rather than wait for it to complete (and be timed out before you see it).
No change to tests, just more patience waiting for them to finish.
=> Change test output format, turn up timeout from 30m to 60m for dilithium branch

cmd/goal/account.go
Add a simple compatibility mode to give a buffer for migration to new REST APIs.
Manual testing:
```
~$ goal account listpartkeys -d /tmp/private_network/Node/
Registered  Account      ParticipationID   Last Used  First round  Last round
yes         MWGK...HZ4M  PCGXDSAH...               6            0     3000000
~$ goal account listpartkeys -d /tmp/private_network/Node/ -c
Registered	Filename                                                                        	Parent address                                              	 First round	  Last round	   First key
yes       	Wallet2.0.3000000.partkey                                                       	MWGKAWMI2BWYPXVWXKO5FBJVIXE6L4FCMCMBUSNXWCH3JXUOAHOUPSHZ4M  	           0	     3000000	         1.8
```
=> Add compatibility mode for listpartkeys goal command.

.circleci/config.yml
Integration tests (specifically, e2e-go tests) seem to be having resource issues lately, so this returns integration tests to using large instances (4 cores, ~16GB RAM) after they were downsized to medium (2 cores ~8GB RAM) in #3095. Nightly integration tests are already using large VMs.
Hopefully this will improve integration test performance and reduce flakiness by giving E2E go tests (which typically involve spinning up multiple algod processes) more CPU and RAM.
=> use large VMs for integration tests

ledger/catchpointtracker.go, ledger/catchpointtracker_test.go
When implementing the catchpoint tracker, I missed the re-initilization location for some of the local variables.
This would generate incorrect catchpoint labels after a node completes a fast-catchup.
https://github.com/algorand/go-algorand/pull/3085
=> ledger refactoring: fix catchpoint tracker

cmd/goal/application.go
Check if the `outFilename` argument is passed and write to the path specified as other commands
=> goal abi method outfile checking

cmd/goal/application.go, test/scripts/e2e_subs/e2e-app-abi-add.sh, test/scripts/e2e_subs/tealprogs/app-abi-add-example.teal
Fix the `--on-completion` flag for `goal app method`, introduced in #3088.
Added test to `test/scripts/e2e_subs/e2e-app-abi-add.sh`
=> Fix OnCompletion flag for `goal app method`

scripts/install_linux_deps.sh
Small change: libboost-math-dev requires just 4 packages to install, while libboost-all-dev requires > 100. Only Debian/Ubuntu distributions provide fine-grained boost packages like this, but should shave a little time off the CI builds. (Our only boost include is boost/math/distributions/binomial.hpp.)
Builds should pass as before. Now that we are no longer using Travis for Linux builds, the side effect of libboost-all-dev installing make and other missing build tools on Travis encountered in #2717 is no longer a concern.
=> CI: use libboost-math-dev instead of libboost-all-dev

data/basics/userBalance.go
extract the logic of NormalizedOnlineBalance into NormalizedOnlineAccountBalance.
The change is quite benign, but would allow future PRs to complete the calculation of the normalized balance without having an AccountData object.
=> ledger refactoring: refactor NormalizedOnlineBalance

test/scripts/e2e_subs/rest-participation-key.sh
- Test to make sure RES has the right input before counting line numbers for result size.
- Rest RES to empty so that the same output is not recycled in case of an error.
- exit 1 in case of an error
- Reduce LAST_ROUND from 1200000 to 120
- "Get List of Keys" before getting NUM_IDS_3 otherwise it will recycle old RES value.
This is a fix to a test.
=> testing: fixes to rest-participation-key e2e test

test/README.md, test/scripts/e2e.sh
Some e2e tests require a python environment for testing.
Unfortunately, setting up that environment adequately similar to the testing environment may not be trivial.
This change introduces an interactive mode to the e2e.sh script which stops at the point of running the tests, and allows the user to run the tests from the same testing environment.
No tests needed. Tested the script locally.
=> interactive mode for e2e testing

data/transactions/logic/README.md, data/transactions/logic/TEAL_opcodes.md, data/transactions/logic/assembler_test.go, data/transactions/logic/doc.go, data/transactions/logic/eval.go, data/transactions/logic/evalAppTxn_test.go, data/transactions/logic/evalStateful_test.go, data/transactions/logic/eval_test.go, data/transactions/logic/fields.go, data/transactions/logic/fields_string.go, ledger/internal/apptxn_test.go
Globals for opcode budget remaining, and info about calling application.
=> Three new globals for to help contract-to-contract usability

test/e2e-go/features/devmode/devmode_test.go, test/e2e-go/features/participation/accountParticipationTransitions_test.go
Fix a couple flaws in the new go-e2e tests built ontop of DevMode:
* Shutdown the fixture when finished.
* Don't run in parallel.
* Longer delays / better algorithms to wait for data flushing to complete.
* Check for "out of order" keys.
N/A, this is a test.
=> Make dev-mode tests less flaky.

scripts/install_linux_deps.sh
The sandbox is not building with dev config using master branch https://github.com/algorand/sandbox/issues/85, complains about libtool not being installed
Guessing from this change https://github.com/algorand/go-algorand/pull/3223 
Adding libtool to UBUNTU_DEPS in install scripts
Set config in sandbox to my branch
`sandbox up dev`
It built
=> Adding libtool to ubuntu deps

ledger/internal/eval.go
Error from account preloading was shadowed by returning a wrong err variable. This caused subsequent problems in account updates and masked the original failure.
=> Fix error shadowing in Eval

test/e2e-go/features/participation/accountParticipationTransitions_test.go
This test doesn't work properly, disable it until #3255 addresses any underlying problems.
=> Disable flaky test.

ledger/applications_test.go
A test helper function `commitRound` accessed `l.trackers.lastFlushTime` without taking a lock. Fixed.
```
go test ./ledger -run TestAppEmpty -race -count=50
ok      github.com/algorand/go-algorand/ledger  4.078s
```
=> testing: fix a data race in app tests

test/scripts/e2e.sh
Fix e2e.sh mixed indent characters.
=> testing: fix e2e.sh mixed indent characters

.circleci/config.yml, test/scripts/e2e_go_tests.sh
This sets `-p 1` for the e2e-go tests, intended to make them more deterministic when running on a VM with relatively constrained resources. Since each e2e-go test might spin up a few nodes, it seems like it would help to avoid resource contention.
Tests should run as before. Desired effect can be verified by looking at the test output where the value of PARALLEL_FLAG is printed out before tests are run.
=> Disable parallelism for e2e-go tests

README.md
Previous formatting was broken due to HTML tags. This fixes it. Also removed centering to align with indexer's format.
Checked badges in branch.
=> Fix formatting for CircleCI badges

data/account/participationRegistry.go, data/account/participationRegistryBench_test.go, data/account/participationRegistry_test.go, go.mod, go.sum
Add ParticipationRegistry methods for setting and retrieving state proof keys. Since they aren't in master yet there is a `type StateProofKey []byte` stub which will need to be updated later.
New unit tests.
=> ParticipationRegistry - StateProof loading methods

cmd/goal/account.go
Compatibility for `partkeyinfo` was also needed by some users. In addition to the different format, the old command also allows printing key information when the node is not running
Workarounds:
1) use an older `goal` binary.
2) use `algokey part info --keyfile <file>`
Tested manually:
```
~$ goal account partkeyinfo -d /tmp/private_network/Node/
Dumping participation key info from /tmp/private_network/Node/...
Participation ID:          CPLHRU3WEY3PE7XTPPSIE7BGJYWAIFPS7DL3HZNC4OKQRQ5YAYUA
Parent address:            DGS6VNX2BRMKGKVAS2LTREMYG33TOCYPFLPCQ3DUTJULQU6P6S7KJCDNTU
Last vote round:           1
Last block proposal round: 2
Effective first round:     1
Effective last round:      3000000
First round:               0
Last round:                3000000
Key dilution:              10000 …
```
=> Compatibility mode for partkeyinfo.

data/transactions/logic/evalCrypto_test.go
This test (TestEcdsa) tests the ecdsa_pk_decompress opcode and intentionally "tampers" with the public key by setting the first byte to zero. Occasionally this test is failing, likely because the first byte was already zero. (The test failures are for the cases where failure is expected, `pass=false`)
Existing test should pass, occasional flakiness should go away.
=> TestEcdsa: fix flaky "tampering" of public key

cmd/goal/application.go, data/abi/abi_encode.go, data/abi/abi_encode_test.go, data/abi/abi_type.go, test/scripts/e2e_subs/e2e-app-abi-method.sh, test/scripts/e2e_subs/tealprogs/app-abi-method-example.teal
Add support for the reference types `account`, `application`, and `asset` to the `goal app method` command.
The way I implemented it, the foreign arrays populated by the `--app-account`, `--foreign-app`, and `--foreign-asset` flags are extended with additional objects from the method arguments. The objects are added in a "compressed" way, meaning an object won't be added to the array if it's already present; rather, the same index will be used for the duplicate object. Additionally, if an `account` matches the transaction sender or an `application` matches the current app ID, it is not added to the foreign array and the index 0 is used as the index.
Consider this example from the e2e test:
```bash
goal app method --method "referenceTest(account,application,account,asset,account,asset,asset …
```
=> Support reference types in `goal app method`

protocol/hash.go
This is to allow ARCs (github.com/algorandfoundation/ARCs)
to have their own hash prefix without risk of collision.
It is purely informational. There is no real code change.
=> Add a hash prefix for ARCs-related hashes

catchup/service.go
The catchup service stops when it is complete, i.e. it has reached up to the round which is being agreed on.
The catchup service knows it is complete and should stop, when it finds that a block is in the ledger before it adds it.
In other words, apart from the catchup, only the agreement adds blocks to the ledger. And when the agreement adds a block to the ledger before the catchup, it means the agreement is ahead, and the catchup is complete.
When `fetchAndWrite` detects the block is already in the ledger, it returns. The return value of `false` stops the catchup syncing. 
In previous releases, `fetchAndWrite` was only checking if the block is already in the ledger after attempting to fetch it. 
Since it fails to fetch a block not yet agreed on, the fetch fails after multiple attempts, …
=> Fix: stop the completed catchup service

catchup/service.go
The fetchAndWrite function contains some complex logic to ultimately determine if we should continue trying to catch up.  The conditions that might cause it to return false should be more explicitly enumerated.
Just comments
=> enumerate conditions that might cause this fetchAndWrite to return false

ledger/applications_test.go, ledger/ledgercore/statedelta.go, ledger/ledgercore/totals_test.go
MergeInMatchingAccounts requires addresses per resource but storing addresses there makes the code much slower.
Lets see if MergeInMatchingAccounts can be eliminated altogether on the schema switch.
Added new test for triggering missed base account data in StateDelta for some application resources modification.
=> ledger refactoring: Ordered resource deltas - part 1

rpcs/blockService.go, rpcs/blockService_test.go
The block service was attempting to serve block via the http handler even after it has been stopped.
This lead to undesired downstream failures in the ledger, which was shutdown as well.
unit test added.
=> blocks service: avoid serving blocks past service shutdown

netdeploy/networkTemplate.go
Avoid creating algod process for the sole purpose of retrieving the genesis-id.
Existing code was calling `algod -G -d <data dir>` in order to obtain the genesis version string.
The genesis version string can be easily retrieved by loading the genesis file.
Use existing e2e tests.
=> testing: improve new networks spawning performance

ledger/applications_test.go
When running TestAppAccountDataStorage, we would randomly have a data race:
```golang
Failed
=== RUN   TestAppAccountDataStorage
==================
WARNING: DATA RACE
Write at 0x00c02966cad8 by goroutine 43:
internal/race.Write()
/opt/cibuild/.gimme/versions/go1.16.11.darwin.amd64/src/internal/race/race.go:41 +0x125
sync.(*WaitGroup).Wait()
/opt/cibuild/.gimme/versions/go1.16.11.darwin.amd64/src/sync/waitgroup.go:128 +0x126
github.com/algorand/go-algorand/ledger.(*trackerRegistry).waitAccountsWriting()
/opt/cibuild/project/ledger/tracker.go:346 +0x58
github.com/algorand/go-algorand/ledger.commitRound()
/opt/cibuild/project/ledger/applications_test.go:42 +0x118
github.com/algorand/go-algorand/ledger.TestAppAccountDataStorage()
/opt/cibuild/project/ledger/applications_test.go:191 +0x14f6 …
```
=> testing: fix random data race in TestAppAccountDataStorage

ledger/acctupdates.go, ledger/bulletin.go, ledger/catchpointtracker.go, ledger/catchpointtracker_test.go, ledger/metrics.go, ledger/notifier.go, ledger/tracker.go, ledger/txtail.go
This PR moves the catchpoint file writing to be performed outside of the trackers lock. This resolves the issue where a long catchpoint file writing blocks the agreement from validating and propagating votes.
=> ledger: perform the catchpoint writing outside the trackers lock.

cmd/goal/account.go
Always use currentRound+proto.MaxTxnLife as last valid round for the transaction when renewing instead of using the partkey validity period. The partkey validity period can therefore now be more than proto.MaxTxnLife rounds long.
This fixes #3283
Should the txn validity period also be configurable via command line options instead? I am not sure about proper naming then, to not have users confuse txn and key validity periods.
=> Separate Txn and PartKey validity for `goal account renewpartkey`

test/scripts/e2e.sh
Minor improvements to e2e.sh interactive mode:
* add to -h output
* do not run start stop test in interactive mode
* support fish shell
Manual testing:
```
~$ ./e2e.sh -i
...
lots of output removed
...
********** READY **********
The test environment is now set. You can now run tests in another terminal.
Configure the environment:
set -g VIRTUAL_ENV "/home/will/go/src/github.com/algorand/go-algorand/tmp/out/e2e/130013-1639576513257/ve"
set -g PATH "$VIRTUAL_ENV/bin:$PATH"
python3 "/home/will/go/src/github.com/algorand/go-algorand/test/scripts"/e2e_client_runner.py  "/home/will/go/src/github.com/algorand/go-algorand/test/scripts"/e2e_subs/SCRIPT_FILE_NAME
Press enter to shut down the test environment...
```
=> Add help and fish mode to e2e interactive mode.

cmd/tealdbg/server.go
Some large teal source files cause the tealdbg/cdt session to choke.  Upping the buffer size to allow for larger source files.
closes #3100 
Run tealdbg with a large source teal file, ensure the source file makes it to cdt without choking.
=> tealdbg: increase intermediate reading/writing buffers

data/transactions/logic/README.md, data/transactions/logic/README_in.md
Added pseudo op description for `method`
docs only, no tests necessary
=> Adding method pseudo op to readme

data/abi/abi_encode_test.go
Previously @cce noticed that there's a flaky test in ABI encoding.
> Chris Erway: just encountered a PR of mine failing due to what looks like a new flaky test related to encoding randomly generated values? https://app.circleci.com/pipelines/github/algorand/go-algorand/3937/workflows/7bd0914e-57f8-4d7e-9fa9-026f74c831bf/jobs/58162
> ![](https://user-images.githubusercontent.com/291133/147157643-b7593f49-f5d8-41c2-9afa-910d545ebbb0.png)
The reason for the flaky test is that we randomly generate variables to test ABI encoding, and it turns out that the generated ABI-encoding bytes is larger than `uint16` limit. The encoder would just throw an error complaining `encode length exceeds uint16 maximum`.
The solution is to scale down the parameters for generating random variables, to decrease …
=> Fix flaky test in randomized ABI encoding test

ledger/accountdb.go, ledger/accountdb_test.go, ledger/acctupdates.go, ledger/catchpointtracker.go
1. remove `addresses` slice from `compactAccountDeltas ` and add `address` field to `accountDelta`.
2. avoid passing {address, aidx} to `compactResourcesDeltas .insert/insertMissing` and extract these from `resourceDelta`.
3. avoid passing {address} to to `compactAccountDeltas.insert/insertMissing` and extract these from `accountDelta`
4. move `upsert` into test code.
Use existing unit tests & update them.
=> ledger refactoring: update compactResourcesDeltas / compactAccountDeltas

cmd/goal/application.go, data/abi/abi_encode.go, data/abi/abi_encode_test.go, test/scripts/e2e_subs/e2e-app-abi-method.sh
This PR changes how `goal app method` handles args and return values in order to address the latest ARC-4 changes and a bug fix. Specifically:
1. Only compresses trailing arguments into a tuple if the number of arguments exceeds 15, per https://github.com/algorandfoundation/ARCs/pull/53
2. Fix a bug when compressing trailing arguments into a tuple, described here: https://github.com/algorand/go-algorand-sdk/pull/273#discussion_r773478473
3. Only inspects the final logged value to find a method's return value, per https://github.com/algorandfoundation/ARCs/pull/57
Unit test added, and added an e2e test for the `empty()void` method call.
=> Update `goal app method` handling of args and return values

cmd/goal/application.go, test/scripts/e2e_subs/e2e-app-abi-method.sh, test/scripts/e2e_subs/tealprogs/app-abi-method-example.teal
Supports app creation in `goal app method`. To create an app, the `--create` flag must be passed instead of the `--app-id` flag. Additionally flags for schema sizes, extra pages, and programs should be passed. After the transaction is confirmed, `goal` will print out the created app ID in addition to the ABI return value.
Here's an example:
```bash
$ goal app method --method "create(uint64)uint64" --arg "1234" --create --approval-prog $APPROVALPROG --clear-prog $CLEARPROG --global-byteslices 0 --global-ints 0 --local-byteslices 1 --local-ints 0 --extra-pages 0 --from WF3PXLVCDHILATGW6P7BOLC7TJE7TOLZM2BQCS24KKX2B4FGMG5Y2NDHWA
Attempting to create app (approval size 500, hash EZD2SJS7UJI45CGG4GEVMCTPZCJ7GQNDUG74GU74C6WKOD2TEFAA; clear size 5, hash …
```
=> Support app creation in `goal app method`

ledger/accountdb.go, ledger/acctupdates.go, ledger/catchpointtracker_test.go, ledger/evalindexer_test.go
Storing `resourceData` in `baseResources` cache for non-existing resources breaks addr to addrid resolution in makeCompactResourcesDelta. Improved the code by skipping empty addrids. This was discovered by TestAppAccountDataStorage.
Fixed some additional tests
=> ledger refactoring: addrid lookup fix

cmd/tealdbg/localLedger.go, daemon/algod/api/server/v2/dryrun.go, daemon/algod/api/server/v2/handlers.go, ledger/accountdb.go, ledger/acctupdates.go, ledger/evalindexer.go, ledger/internal/eval.go, ledger/internal/eval_test.go, ledger/ledgercore/accountresource.go, ledger/ledgercore/statedelta.go
Fix tealdbg and dryrun tests by implementing `LookupResource`.
Rename  `AccountResource.AssetParam` to `AccountResource.AssetParams` for consistency
=> ledger refactoring: tealdbg + dryrun tests fixes

ledger/acctupdates_test.go, ledger/ledgercore/accountdata.go, ledger/ledgercore/statedelta.go, ledger/testing/randomAccounts.go
Implement `ledgercore.AccumulateDeltas` for in-place partial deltas applying into base accounts.
This reduces memory usage by `TestAcctUpdates` for a single round verification when all fresh data are loaded from disk and only used for one round data comparison.
=> ledger refactoring: make TestAcctUpdates faster by ~10s

ledger/archival_test.go
TestArchivalFromNonArchival was sporadically failing, particularly on the feature/dilithium-scheme-integration branch. 
The most likely reason for the slowdown is narrowed down to system trashing. 
This fix seems to fix the issue by invoking GC before the test to have maximum amount of memory available, and after the test to minimize the memory impact on subsequent tests.
This fix is also necessary to confirm the memory hypothesis. 
The memory consumption is high because of the existing ledger design, which is skewed in this test by creating a large number of asset creation transactions. This behavior is changing with the upcoming ledger refactoring project. 
Resolves https://github.com/algorand/go-algorand/issues/3334
=> Use gc to avoid trashing.

network/wsNetwork.go
Replace the standard limit listener with the new rejecting limit listener in `WebsocketNetwork`. This will let the dialing node know that connection is impossible faster.
Probably not necessary.
=> Use rejecting limit listener in `WebsocketNetwork`

txnsync/incoming.go, txnsync/msgorderingheap.go, txnsync/msgorderingheap_test.go
Whenever the msgOrderingHeap gets full, we would like to compress the messages inside of it instead of disconnecting from the corresponding peer.
Wrote additional unit tests.
=> txsync: compress msgOrderingHeap

catchup/service.go, test/e2e-go/features/catchup/basicCatchup_test.go
Adding a test for the fix in #3299
This is a test
=> Test for catchup stop on completion

util/db/dbutil.go
This PR deletes unused `AtomicCommitWriteLock()` and simplifies code.
None.
=> Delete unused `AtomicCommitWriteLock()`

agreement/demux.go, agreement/vote.go, agreement/voteAggregator.go, config/consensus.go, test/testdata/consensus/catchpointtestingprotocol.json
This PR removes `FastPartitionRecovery` option from consensus parameters. The code now acts as if this value is set to true.
Closes https://github.com/algorand/go-algorand-internal/issues/1830.
None.
=> Deprecate `FastPartitionRecovery` from `ConsensusParams`

cmd/catchpointdump/file.go, ledger/accountdb.go
Fixes to `processAllResources` and `processAllBaseAccountRecords` related to a case when an account does not have resource records and a pending row needs to be carried over next account or a batch reading iteration.
Use `processAllBaseAccountRecords` in `encodedAccountsBatchIter.Next()`. This allows us to the same code for all scenarios where we read entire base account and resources tables.
=> ledger refactoring: catchpoint fixes

cmd/goal/asset.go, test/scripts/e2e_subs/asset-misc.sh
Allow setting manager, reserve, freeze, and clawback at goal asset create
Did not test it.
I built the binaries, ran `${GOPATH}/bin/goal node start -d ~/.algorand`, used goal to create a new wallet, but I don't know how to fund the wallet to continue :(
Closes #3361
=> Allow setting manager, reserve, freeze, and clawback at goal asset create

cmd/goal/asset.go, test/scripts/e2e_subs/asset-misc.sh
Please see https://github.com/algorand/go-algorand/pull/3369
=> Remaking a PR for CI

ledger/accountdb.go, ledger/accountdb_test.go, ledger/acctupdates.go, ledger/acctupdates_test.go, ledger/ledgercore/statedelta.go
* TestAcctUpdates used to compare acct updates content every round
but this is slow due to amount of data needed to be compared.
* This fix suggest making comparison at first, end and approx every
10 iterations.
=> Make TestAcctUpdates faster

test/testdata/consensus/catchpointtestingprotocol.json
The old values were incorrectly replaced by 4s default valus in #3195
=> ledger refactoring: restore fast rounds for catchpoint e2e test

agreement/cryptoVerifier_test.go, agreement/vote.go, crypto/onetimesig.go, node/netprio.go
crypto package need not depend on config.
There is an unnecessary dependency on config.
signer.KeyDilution takes the `config.ConsensusParams` as argument to pick the DefaultKeyDilution from it. 
This introduces dependency from the crypto package to config package. 
Instead, only the DefaultKeyDilution value can be passed to signer.KeyDilution.
No impact on testing.
=> signer.KeyDilution need not depend on config package

data/abi/abi_encode.go, data/abi/abi_encode_test.go, data/abi/abi_json.go, data/abi/abi_json_test.go, data/abi/abi_type.go, data/basics/address.go
We want to remove C/crypto dependencies from `data/abi` package, because the previous commit https://github.com/algorand/go-algorand/commit/d3bbe62caa11a2608c318919122457d4512045c5 introduced dependencies to crypto package with C dependencies (`SHA512/256` needed). This led to go-algorand-sdk cannot  easily update go-algorand past that commit.
The current solution is: "rewrite" the checksum function for address in `data/abi` package, which removes dependencies to `data/basics` and `algorand/crypto`, and sets dependency to `crypto` (golang).
Refactor the `data/abi` package to avoid referencing `data/basics`, closes #3355.
=> Removing C/crypto dependencies from `data/abi` package

agreement/demux.go, agreement/listener.go, agreement/persistence.go, agreement/persistence_test.go, agreement/proposalManager.go, agreement/proposalStore.go, agreement/proposalTracker.go, agreement/pseudonode.go, agreement/service.go, agreement/trace.go, agreement/voteAggregator.go, agreement/voteAuxiliary.go, agreement/voteTracker.go
Current agreement code only writes a `context : agreement` to a subset of the logged messages.
This change extends the said entry, which would make it easier to pre-process logs entries by their corresponding component. The change in this PR is focused on:
1. make sure that the "root" agreement logger always injects the `context : agreement` argument.
2. change the various locations in the agreement code to use the root agreement logger instead of referring to the application-global instance (`logging.Base()`).
Test the output logs manually.
=> add context to (most) agreement logged writes

network/wsNetwork.go, network/wsPeer.go
During the node shutdown, all the current outgoing connections are being disconnected.
Since these connections are web sockets, they require a close connection message to be sent.
However, sending this message can take a while, and in situations where the other party has already shut down, we might never get a response. That, in turn, would lead the node waiting until the deadline is reached.
The current deadline was 5 seconds. This PR changes the deadline during shutdown to be 50ms.
=> network: faster node shutdown

ledger/accountdb.go, ledger/accountdb_test.go, ledger/catchpointtracker.go, protocol/codec_tester.go
Avoid copying during baseAccountData.IsEmpty.
Unit test written to cover the IsEmpty functionality.
=> Avoid copying during baseAccountData.IsEmpty

ledger/accountdb.go, ledger/acctupdates_test.go, ledger/catchpointtracker.go, ledger/catchpointtracker_test.go, ledger/tracker.go, ledger/tracker_test.go
If accountdb accumulates a large backlog, it is possible catchpoint tracker would attempt to commit a wider range than account updates tracker expects.
Added a test simulating said behavior.
=> Fix a potential problem of committing non-uniform consensus versions

agreement/persistence.go
When crash state is found but could not be restored, noCrashState variable is used to report a warning.
However, this variable was set to false in a case where there was no crash state, and the wrong warning was reported.
=> Fix warning message on restore crash db

test/muleCI/mule.yaml
Updating golang version, introducing new features to goal and algod, cleaning up code, and adding State Proof loading methods. NOTE: we upgraded to golang 1.16.11 and arm32v7 (for arm32 builds)
* Changing golang version to 1.16.11 in go-algorand (#2825)
* Goal: Support reference types in `goal app method` (#3275)
* ParticipationRegistry - StateProof loading methods (#3261)
1. AVM (Algorand Virtual Machine)
* vFuture
* base64 decode opcode (#3220, #3288)
1. Algod
* New Feature
* ParticipationRegistry - StateProof loading methods (#3261)
* PKI State Proof Incremental Key Loading (#3281)
* Enhancement
* Update Algod's `/Accounts/ACCOUNTID` endpoint to return **Minimum Balance** information (#3287)
* enumerate conditions that might cause this fetchAndWrite to return false (#3301)
* add …
=> Update reference to arm32 build for 3.3.0 release

docker/build/cicd.ubuntu.Dockerfile, test/muleCI/mule.yaml
Specify the arch file name for the golang download.
Tested locally with `mule -f test/muleCI/mule.yaml build-linux-arm32 `
and got `2022-01-20 17:04:11,504 - INFO - Built docker image algorand/go-algorand-ci-linux:arm32v7-65af9d7d196a44479ec08e951bbc8e989dbb3a24 from docker/build/cicd.ubuntu.Dockerfile`
=> Specify GOARCH for golang download in Dockerfile

catchup/catchpointService.go, ledger/catchupaccessor.go
During the fast catchup process, the node's reported status presents information similar to the following:
```
Last committed block: 8059
Sync Time: 929.6s
Catchpoint: 18630001#V4CQ2LXRIKL5XKTBE33ZDGBP23G4U2ENZQURY2XS75IHRBWHYJEQ
Catchpoint total accounts: 8357134
Catchpoint accounts processed: 8357134
Catchpoint accounts verified: 29869214
Genesis ID: mainnet-v1.0
Genesis hash: wGHE2Pwdvd7S12BL5FaOP20EGYesN73ktiC1qzkkit8=
```
The reported "Catchpoint accounts verified" is above the "Catchpoint total accounts", which is clearly wrong.
The sounds for this conflict is that with the resources separation, the merkle trie contains more entries. The reported number is the number of added merkle trie entries.
This is a user-interface only issue. To work around that, this PR normalize the added …
=> ledger refactoring: normalize verified accounts

ledger/accountdb.go, ledger/accountdb_test.go, ledger/catchpointtracker.go
Few simple tweaks to try and squeeze some additional cycles out of the merkle trie regeneration logic:
- avoid using "append" and add directly to a preallocated array.
- load the value directly to their preallocated array positions.
- avoid using explicating address in temporary table. use the addid instead, and perform the translation
only in case of an error.
Merkle trie hashes writing time:
before: 20m:48s
after: 16m:11s
Note that the data size here is 32M.
tested manually.
=> ledger refactoring: improve merkle trie regeneration

ledger/accountdb.go, ledger/applications_test.go
The lookupResources had a small bug: it wasn't returning the correct persistedResourcesData in case the requested account did not had any holding of the requested asset. That, in turn got stored into the resources cache, triggering
issues down the road.
Existing unit tests were updated.
=> ledger refactoring: fix lookupResources

ledger/accountdb.go
During the catchpoint catchup, we create temporary tables.
These tables becomes the production table at the end of the catchup.
The current generated table `accountbase` was not using the correct schema.
tested manually.
=> ledger refactoring: fix incorrect schema during catchpoint catchup

data/abi/abi_encode.go, data/abi/abi_encode_test.go, data/abi/abi_json_test.go
We are probably not going to higher golang version (1.15+) at this point, while `fillBytes` from `big.Int` is introduced in 1.15.
Changing all the `fillBytes` in `ABI` to self-made `bigIntToBytes` in favor of lower go version.
=> Revert `fillBytes` method to `bigIntToBytes` for lower golang version

ledger/accountdb.go
This index was in the migration schema but not the catchpoint restore schema.
=> ledger refactoring: add unique index on address to catchpointbalances

.circleci/config.yml, .github/workflows/reviewdog.yml, Makefile, go.mod, go.sum, scripts/buildtools/go.mod, scripts/buildtools/install_buildtools.sh, scripts/get_golang_version.sh, scripts/travis/before_build.sh
Reverts algorand/go-algorand#2825 to back out 1.16 golang update
=> Revert "Changing golang version to 1.16.11 in go-algorand"

test/heapwatch/heapWatch.py, test/heapwatch/metrics_delta.py, test/testdata/deployednettemplates/recipes/hello-world/genesis.json, test/testdata/deployednettemplates/recipes/hello-world/net.json, test/testdata/deployednettemplates/recipes/hello-world/topology.json
To support performance testing with bandwidth collection, updated Hello World recipe so that it works, and specify UTF-8 encoding when processing metrics files.
Tested using pipeline https://ci.algorand.network/job/cicd-perf-pprof/87/
=> Add bandwidth testing

ledger/accountdb.go
The `resources` table needs to be dropped during `accountsReset`. Without that, the entries there would not be eliminated during the reset process.
=> ledger refactoring: delete resources table on accountsReset

ledger/accountdb.go, ledger/accountdb_test.go
Compact accounts and resources delta might be out of sync order. To cope with this fact and rowids reusage by SQLite, resources writing was split into two phases: detecting reused rowids, updating rows with reused rowids, and deleting non-reused.
The original accountsNewRound replaced by accountsNewRoundImpl that takes accountWriter interface as the first argument instead of sql.Tx object.
accountsNewRound is preserved as a convenience wrapper for accountsNewRoundImpl with SQLWriter.
This change allowed to implement a fake writer that reuses all rowids and simulate the bug we found by running on real data.
This replaces #3510 and #3515
=> ledger refactoring: acct new round fix + test

cmd/tealdbg/localLedger.go, daemon/algod/api/server/v2/dryrun.go, ledger/accountdb.go, ledger/accountdb_test.go, ledger/acctupdates.go, ledger/acctupdates_test.go, ledger/evalindexer.go, ledger/ledgercore/accountresource.go, ledger/ledgercore/statedelta.go
The ledger for evaluator interface's `LookupResource()` returns creatable index and type inside `ledgercore.AccountResource` even though the caller knows what they are. This PR removes these redundant fields.
This is just refactoring.
=> ledger refactoring: remove index and type from `ledgercore.AccountResource`

data/basics/userBalance.go, ledger/ledgercore/accountdata.go
* Added a new basics.WithUpdatedRewards free functions for rewards calculation
* basics.AccountData.WithUpdatedRewards became a simple wrapper for it
=> Avoid exceed copying when calling WithUpdatedRewards

data/transactions/logic/eval.go, data/transactions/logic/evalStateful_test.go, data/transactions/logic/eval_test.go, data/transactions/logic/fields_test.go
txn opcodes should not be able to look at the current or future "effects" fields
=> Only allow access to txn effects for previous transactions

catchup/catchpointService.go, catchup/ledgerFetcher.go, ledger/catchupaccessor.go
Add logs in catchpoint service measuring the time it takes to
- write catchpoint balances to disk
- write catchpoint creatables to disk
- write catchpoint hashes to disk
- write all catchpoint data to disk
- download the catchpoint + write all catchpoint data to disk
- build the merkle trie
I ran fast catchup and verified that logs are printed.
=> ledger refactoring: measure and log performance during fast catchup

ledger/README.md
Updates ledger README reference to tracker source code.
Since `trackers.go` does _not_ exist, I _assume_ the appropriate reference is `tracker.go`.
Since the change _only_ impacts docs, I visually confirmed Markdown rendering.
=> Update ledger README reference to trackers

agreement/pseudonode.go
Add a warning in case the VotingKeys method surpasses the expected execution time limits.
=> agreement: verify VotingKeys run time

cmd/catchpointdump/file.go, cmd/catchpointdump/net.go
* Do not load everything into memory but write directly in into a file
This creates extremely high number of reallocation and CPU and RAM wasting.
* Add cmd options for downloading only (no loading), and for downloading
from a single relay
| param       | current | new      |
|-----------|--------|---------|
| RAM          | 5 GB    | 200 MB |
| Total time | 823 s   | 441 s    |
Downloading time went down from minutes to tens of seconds.
=> Optimize catchpointdump utility

.circleci/config.yml, scripts/release/README.md, scripts/release/test/util/test_package.sh, test/packages/test_release.sh, test/platform/test_linux_amd64_compatibility.sh
our nightly pipeline broke because of centos:8 reaching end of life and deprecating their package repo AppStream. Switching to official new version Centos Stream 8.
Tested it here: https://app.circleci.com/pipelines/github/algorand/go-algorand/4716/workflows/e32173a7-e08b-47f0-a098-c2c32fb0c1ee/jobs/73893
More info: https://www.centos.org/centos-linux-eol/
Break that was fixed by this: https://app.circleci.com/pipelines/github/algorand/go-algorand/4699/workflows/8ebe3bc6-c029-49e1-8bb2-45d6061226c5/jobs/73675
=> Moving to centos stream 8

data/committee/sortition/sortition.go
Remove a hardcoded constant in sortition.go which was
used as the denominator in determining the selection ratio.
This clarifies what the maximum possible output size is of
the output VRF based on the SHA algorithm used to generate it.
This is simply a code quality change to make it easier to read and
understand without any focus on new functionality or performance.
It is unlikely that the VRF SHA length used by Algorand will changed,
so the generalization to a dynamic length based on the length of the
Crypto digest is only for the reader.
The use of an `init` function to initialize the `maxFloat` once rather than
anytime `sortition` runs is a minor optimization, but likely to be neglibile
in the grand scheme of things.
Due to the usage of C src code, a simple `go test -v …
=> Removed hard-coded constant in `sortition.go`.

cmd/catchpointdump/database.go, cmd/catchpointdump/file.go, cmd/catchpointdump/net.go, cmd/goal/common.go, cmd/tealdbg/main.go, cmd/util/cmd.go
Added a new option `--exclude-fields` to `file` subcommand.
This simplifies large dumps comparison by excluding all exclude some header fields.
Also moved some shared cmd code into a new cmdutil package.
=> catchpointdump: allow print filters

config/consensus.go, data/transactions/logic/eval.go, data/transactions/logic/evalAppTxn_test.go, data/transactions/logic/evalStateful_test.go, data/transactions/logic/ledger_test.go, data/transactions/logic/opcodes.go, data/transactions/teal_test.go, data/transactions/transaction.go, data/transactions/transaction_test.go, data/txntest/txn.go, ledger/apply/application.go, ledger/internal/appcow.go, ledger/internal/apptxn_test.go, ledger/internal/eval_blackbox_test.go, test/scripts/e2e_subs/e2e-app-extra-pages.sh, test/scripts/e2e_subs/goal/goal.py
Prevents inner txns and bad opcode budget use in clear state programs.
=> Inner clearstate

data/txntest/txn.go
Adds commentary based on context found in https://github.com/algorand/go-algorand/pull/2730.  For developers new to _go-algorand_, the context helps to explain _how_ `txntest.Txn` simplifies testing.
N/A - Only changes comments.
=> Add comment to help explain txntest.Txn rationale

data/transactions/logic/eval.go, data/transactions/logic/evalStateful_test.go, ledger/internal/eval_blackbox_test.go
Deleting keys that don't exist should not go into EvalDelta
=> Match old BuildEvalDelta behaviour - no delete missing keys

cmd/catchpointdump/commands.go, cmd/catchpointdump/file.go, cmd/catchpointdump/net.go
Catchpointdump does not have access to a ledger and it does not know
which consensus params is to use as genesis state on rewards calculation
that can lead to division by zero panic.
This PR sets a hardcoded value to `ConsensusCurrentVersion`.
Additionally, let `net` subcommand to return non-zero exit code
to indicate nothing was downloaded.
To do that I converted it to `cobra.RunE`-style method in order  to use
a standard cobra's error reporting and exit code setter.
=> catchpointdump: set genesis proto version

.dockerignore, scripts/build_package.sh, scripts/create_and_deploy_recipe.sh
Having `catchpointdump` in tools looks as not a bad idea in general.
In particular I need a linux build of `catchpointdump` on my Mac machine in order
to plug it into algonet linux network. The only way to make such a cross build is calling
`deploy_linux_version.sh` that builds and upload packages in a docker container.
Modified `create_and_deploy_recipe.sh` to support multicomponent `GOPATH`
Tested manually and it works as expected:
1. catchpointdump is in tools package
2. Multicomponent GOPATH supported well
3. Content of tmp/go-cache is not sent into docker
=> Add catchpointdump into tools package

cmd/catchpointdump/net.go
Add the same filters to `net` command as `file` has.
=> Add filter fields to catchpointdump net command

data/account/participationRegistry.go
fix reviewdog linter error : rename function receiver name :
```golang
func (part ParticipationRecord) OverlapsInterval(first, last basics.Round) -> 
func (r ParticipationRecord) OverlapsInterval(first, last basics.Round)
```
Use existing tests.
=> fix reviewdog linter error

crypto/merklesignature/persistentMerkleSignatureScheme.go
Few touchups for Secrets.Persist:
- Move unneeded tests outside of the `Atomic` call.
- Improve encoding buffer alloc/release
- Call rows.Close
=> Few touchups for Secrets.Persist

data/bookkeeping/txn_merkle.go, data/bookkeeping/txn_merkle_test.go, test/e2e-go/features/transactions/proof_test.go
My previous PR was causing a minor regression. Thanks to @jannotti comment, I think that I was able to fix the regression, and added a proper testing for that.
New benchmark result ( no inner method anymore )
```
goos: darwin
goarch: amd64
pkg: github.com/algorand/go-algorand/data/bookkeeping
cpu: Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
BenchmarkTxnMerkleToRaw/copy-8         	1000000000	         1.129 ns/op	       0 B/op	       0 allocs/op
BenchmarkTxnMerkleToRaw/append-8       	243079730	         4.886 ns/op	       0 B/op	       0 allocs/op
PASS
ok  	github.com/algorand/go-algorand/data/bookkeeping	3.183s
```
=> fix minor regression in txnMerkleToRaw

.circleci/config.yml, test/e2e-go/features/participation/participationExpiration_test.go
The state proof branch contained a change to `testExpirationAccounts`, changing the `partKeyValidityPeriod` from 10 to 150. This increase the duration of the test substantially, and (apparently) also causing the test to fail.
This PR rolls back that change.
=> testing: rollback changes to ParticipationExpirationTest

docker/build/cicd.ubuntu.Dockerfile, test/muleCI/mule.yaml
Reverts changes made in arm32 build to support golang1.16. 
Tested it locally.
=> revert golang1.16 arm32 changes

scripts/release/mule/Makefile.mule
The new key generation causes this process to take a long time. We should just remove it for now and re-evaluate.
Tested `make ci-build` locally with it removed.
=> Remove `make gen` from ci-build

test/e2e-go/features/participation/participationExpiration_test.go
This test had a bug, where it was sending a transaction to one node2, waiting for the transaction to be included in a block on node1, and then pulling the account data from node2.
Since the test failed to wait for node2 to be at the same round as node1, there is no guarantee that the account data fetched from node2 is the same as the account data that was just updated in the block.
Separately from that, the `fixture.WaitForTxnConfirmation` call was not tested for its return value.
Use Circle-CI.
=> testing: fix bug in TestParticipationAccountsExpirationFuture/TestParticipationAccountsExpirationNonFuture

crypto/merklesignature/persistentMerkleSignatureScheme.go, crypto/merklesignature/persistentMerkleSignatureScheme_test.go, data/account/account.go, data/account/participation.go, data/account/participation_test.go, node/node.go, test/e2e-go/upgrades/stateproof_test.go
Restoring participation has failed in the nightly build, since it was trying to query for StateProofKeys table which doesn't exist yet.
Made sure to call the migration in the correct places to fix this issue.
Unit tests added.
=> add a fallback for missing state proof keys in participation file

test/e2e-go/features/transactions/accountv2_test.go
The TestAccountInformationV2 test was making the assumption that a transaction would get included into a block with 5 rounds. This assumption might not hold true.
In this PR, we're waiting for the transaction to be included, and then using the PendingTransactionInformation to determine on which round it was included.
=> testing: improve TestAccountInformationV2

test/e2e-go/features/transactions/proof_test.go, test/e2e-go/restAPI/restClient_test.go
Fix a bug in the REST API testing.
Run via CircleCI.
=> remove Parallel from txnproofs and fix timeout bug

test/e2e-go/features/transactions/asset_test.go
Fix a bug in TestAssetGroupCreateSendDestroy. The test uses two nodes, sending transaction to one and checking the state on the other. Before checking, the test need to verify that both nodes successfully reached the same round number.
=> testing: fix bug in TestAssetGroupCreateSendDestroy

test/testdata/deployednettemplates/recipes/custom/configs/node.json, test/testdata/deployednettemplates/recipes/custom/configs/nonPartNode.json, test/testdata/deployednettemplates/recipes/scenario2/node.json, test/testdata/deployednettemplates/recipes/scenario2/nonPartNode.json
Fixed problem running bandwidth performance testing with the custom and scenario2 recipes by enabling the API endpoints for nodes and nonparticipating nodes.
Allow bandwidth testing with custom and scenario 2 recipes. 
Tested using the updated custom recipe.  The performance pipeline was completed successfully and the datadog bandwidth chart was updated.
=> DevOps: Fix bandwidth testing

.circleci/config.yml
This changes gotestsum to print out the names of tests before they run, and print test output while tests are running. More verbose, but is the only way to catch unexpected slow tests that trigger the no output timeout (without pushing a commit, rerunning and hoping to spot it again).
=> Set gotestsum format to standard-verbose

data/basics/userBalance.go, ledger/internal/eval_test.go
Clear out AccountData.StateProofID when ClearOnlineState() is called, by resetExpiredOnlineAccountsParticipationKeys (as part of #2924)
Updated TestExpiredAccountGeneration to generate random online account data, so that it fails without this change.
=> add StateProofID to AccountData.ClearOnlineState()

ledger/acctupdates_test.go, ledger/catchpointtracker.go, ledger/catchpointtracker_test.go
This PR addresses 3 linter detected issues:
1. unneeded commented out import
2. missing `partitiontest.PartitionTest` call on unit test
3. the `accountsUpdateBalances` wasn't returning error correctly in some cases.
=> ledger refactoring: fix linter detected issues

agreement/asyncVoteVerifier_test.go
Fix for a strange assert found by JJ
=> testing: Fix a typo in agreement test

ledger/apply/apply.go, ledger/apply/mockBalances_test.go, ledger/internal/cow_creatables.go
I had been meaning to remove this bit of dead code — unused CountX methods in apply.Balances.
=> remove dead code from apply.Balances

daemon/algod/api/server/v2/dryrun_test.go
Add test to close #3244
This is a test
=> dryrun: add gloads test

test/testdata/deployednettemplates/recipes/feature-networks/genesis.json
Make keys valid for 3million rounds. With the rework to part keys, our pipeline was running out of disk space
I used this to spin up a feature network
=> Decrease partkey rounds to 3mil for feature networks

crypto/merklearray/proof.go, crypto/merklearray/proof_test.go, daemon/algod/api/server/v2/handlers.go, test/e2e-go/features/transactions/proof_test.go
This PR fixes a bug on algod's API. When a tree contains a missing child (not a full tree), the api handler omits this from the proof response and leads to a root mismatch 
Add unit tests as well as convert the e2e to test this edge case.
=> API: Fix prove bug on API

ledger/metrics.go, ledger/metrics_test.go, util/metrics/counter.go, util/metrics/registry.go, util/metrics/service.go
Metrics counters where not cleared on close and lead to duplicate entries in metering report.
Added unit test. Tested manually.
Closes #3354
=> algod : deregister metrics tracker on close

ledger/accountdb.go, ledger/accountdb_test.go, ledger/acctupdates.go
Pass the `ledgercore.AccountData` to the `accountDataToOnline` as a pointer rather then copy of the actual data.
Update tests
=> ledger refactoring: make changes per CR

test/testdata/deployednettemplates/recipes/custom/configs/node.json, test/testdata/deployednettemplates/recipes/custom/configs/nonPartNode.json, test/testdata/deployednettemplates/recipes/scenario2/net.json, test/testdata/deployednettemplates/recipes/scenario2/node.json, test/testdata/deployednettemplates/recipes/scenario2/nonPartNode.json
Regen scenario 2 net.json file to include API endpoints for nodes.
Testing with scenario2 recipe with cicd perf pipeline.
=> DevOps: Regen net.json for scenario2 test to include api endpoints for nodes.

agreement/pseudonode_test.go
The TestPseudonodeFailedEnqueuedTasks test wasn't accounting correctly for errPseudonodeBacklogFull errors.
Run 1000 times localy. I was able to reproduce it consistently.
=> testing: fix randomly failing TestPseudonodeFailedEnqueuedTasks 

crypto/compactcert/structs.go, ledger/internal/compactcert.go
Nodes create the compact cert using falcon keys so the batch verification flag (related to the ed25519 scheme) is no longer necessary.
=> Algod: remove batch verification flag from the compact certs struct

go.mod, go.sum
Update the sum hash library.
Use existing tests.
=> Algod: use updated sumhash lib

cmd/algokey/keyreg.go, cmd/algokey/part.go, test/scripts/e2e_subs/keyreg.sh
New algokey subcommand to generate transactions for bringing an account online or offline.
Usage:
```
~$ algokey part keyreg -h
Make key registration transaction
Usage:
algokey part keyreg [flags]
Flags:
--account string      account address to bring offline, mutually exclusive with keyfile
--fee uint            transaction fee (default 1000)
--firstvalid uint     first round where the transaction may be committed to the ledger
-h, --help                help for keyreg
--keyfile string      participation keys to register, file is opened to fetch metadata for the transaction, mutually exclusive with account
--lastvalid uint      last round where the generated transaction may be committed to the ledger, defaults to firstvalid + 1000
--network string      the network where the provided keys …
```
=> Tools: Add 'algokey part keyreg'

daemon/algod/api/server/v2/handlers.go
AccountApplicationInformation was calling `ledger.LookupResource` with `basics.AssetCreatable` instead of `basics.AppCreatable`, resulting in a consistent failure.
Unit test will follow on a subsequent PR.
=> unlimited assets : fix bug in AccountApplicationInformation handler

test/README.md
Provides a pointer to instructions added in https://github.com/algorand/indexer/pull/906 for updating Indexer E2E test input.
N/A - Changes docs.  Though I expect to trial the instructions as discussed in https://github.com/algorand/indexer/pull/906.
=> Enhancement: Document instructions for updating Indexer E2E test input

daemon/algod/api/server/v2/handlers.go, daemon/algod/api/server/v2/test/handlers_resources_test.go
Follow-on to #3702, the copy-pasted code in AccountApplicationInformation was checking the wrong value before returning AppParams.
=> REST API: fix check for record.AppParams in AccountApplicationInformation

agreement/actions.go, agreement/agreementtest/simulate.go, agreement/demux.go, agreement/demux_test.go, agreement/events.go, agreement/msgp_gen.go, agreement/proposal.go, agreement/service_test.go, logging/telemetryspec/event.go, util/timers/frozen.go, util/timers/interface.go, util/timers/monotonic.go
This pulls a bit of code from the the [pipelining branch](https://github.com/algorand/go-algorand/tree/feature/pipeline) to add a "validatedAt" duration field to the agreement.proposal type. This is used to provide an extra field in the BlockAcceptedEventDetails message describing how soon into the round each block was validated.
Existing tests should pass, and a new test might be helpful to show that the value is getting filled in correctly.
=> agreement: Add validatedAt to proposal type and BlockAcceptedEventDetails message

catchup/catchpointService.go
The existing code was failing the fast catchup on node startup if the peers could not be retrieved from the network package.
Unfortunately, this is almost always the case. This change allow the node to retry fetching the peers list from the network package multiple times, while having a short delay between the iterations.
This issue was reported by a Algorand Forum member.
Test the change manually.
=> fast catchup: retry peers fetching

test/e2e-go/features/transactions/asset_test.go
The TestAssetConfig was not updated correctly to support unlimited assets.
This PR brings it up to date, as well as improve the runtime of the test.
Use Circle-CI.
=> testing: fix TestAssetConfig test to support unlimited assets

cmd/tealdbg/localLedger.go, daemon/algod/api/server/v1/handlers/handlers.go, daemon/algod/api/server/v2/dryrun.go, daemon/algod/api/server/v2/handlers.go, daemon/algod/api/server/v2/test/handlers_resources_test.go, daemon/algod/api/spec/v2/model.go, ledger/acctupdates.go, ledger/applications_test.go, ledger/evalindexer.go, ledger/evalindexer_test.go, ledger/internal/appcow_test.go, ledger/internal/eval.go, ledger/internal/eval_test.go, ledger/internal/evalprefetcher.go, ledger/internal/evalprefetcher_test.go, ledger/ledger.go, ledger/ledger_test.go, ledger/ledgercore/accountresource.go
This replaces the various Ledger interfaces' `LookupResource` method with two more specific `LookupApplication` and `LookupAsset` methods. Following up on code review feedback from #3652.
Existing tests should pass, including the ones that implement their own mock ledger.
=> ledger: replace Ledger.LookupResource with Lookup{Application,Asset}

agreement/fuzzer/networkFacade_test.go
There was one Clock implementation not updated in #3703 in the agreement fuzzer testing package's NetworkFacade type. This updates it to fully implement the Clock interface.
=> agreement: fix fuzzer test NetworkFacade Clock implementation

logging/telemetry.go, logging/telemetryhook_test.go
In #3341 I neglected to notice there are two places that generate telemetry configuration, ReadTelemetryConfigOrDefault and EnsureTelemetryConfigCreated. This updates the latter.
Updated tests to check and handle new default.
=> telemetry: Fix version configuration

ledger/internal/eval.go, ledger/internal/evalprefetcher.go, ledger/internal/evalprefetcher_alignment_test.go, ledger/internal/evalprefetcher_test.go
Tests for eval prefetcher checking that the prefetcher loads the same data (with some exceptions) that the evaluator requests.
Closes https://github.com/algorand/go-algorand-internal/issues/1922.
This is tests.
=> prefetcher: add Eval vs prefetcher alignment tests

ledger/internal/prefetcher/prefetcher.go, ledger/internal/prefetcher/prefetcher_whitebox_test.go
prefetcher: ensure the groupTask.incompleteCount is allocated on a 64-bit aligned address.
This is required in order to avoid the following on a ARM32:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb541efb0]
goroutine 4220 [running]:
runtime/internal/atomic.goLoad64(0x8ae33be4, 0xb67e0fec, 0x8cf54500)
runtime/internal/atomic/atomic_arm.go:131 +0x1c
github.com/algorand/go-algorand/ledger/internal.(*accountPrefetcher).prefetch(0x8cf54500, 0xb68023f0, 0x8cf532c0)
github.com/algorand/go-algorand/ledger/internal/evalprefetcher.go:384 +0x1268
created by github.com/algorand/go-algorand/ledger/internal.prefetchAccounts
github.com/algorand/go-algorand/ledger/internal/evalprefetcher.go:87 +0x128
```
Test …
=> prefetcher: ensure the groupTask.incompleteCount is allocated on a 64-bit aligned address

test/e2e-go/features/accountPerf/sixMillion_test.go
This PR replaces the usage of the LibGoal with the direct RestClient. The change could have performance implications when running against large sets of data.
=> testing: improve 6M asset testing performance

test/e2e-go/features/accountPerf/sixMillion_test.go
This PR improves the test in the following ways:
1. The checkPoint method is no longer timer-based; instead, it's using the WaitForBlock which moves the blocking operation to the node.
2. The generated accounts secret keys are now deterministic. This would allows repeated runs to have the same set of keys.
3. More testing was added for return variables across the test.
=> testing: update Test5MAssetsScenario e2e test

crypto/onetimesig.go, crypto/onetimesig_test.go
The ed25519 batch verification implementation in https://github.com/algorand/go-algorand/pull/3031 provides a performance improvement for validating multiple signatures (such as multiple transaction signatures). Since each OneTimeSignature used by agreement votes is actually 3 ed25519 signatures, this hooks up the verifier to the batch verification implementation, yielding a ~12% performance improvement in the included benchmark on my computer.
Added benchmark, existing tests should pass.
=> crypto: call batchVerificationImpl from OneTimeSignatureVerifier.Verify

daemon/algod/api/server/v2/dryrun.go, daemon/algod/api/server/v2/dryrun_test.go
When performing a dryrun, if the program uses scratch space there is some logic to determine which slots are active and if inactive the type is set to 0.  
There seems to be an off-by-one bug where the types are offset by one element in the scratch slot array. This was causing output like:
```json
"scratch": [
{
"bytes": "",
"type": 0,
"uint": 0
},
{
"bytes": "",
"type": 0,
"uint": 0
},
{
"bytes": "",
"type": 0,
"uint": 0
},
{
"bytes": "",
"type": 0,
"uint": 0
},
{
"bytes": "SW4gYXBwIGlkIDIzIHdoaWNoIHdhcyBjYWxsZWQgd2l0aCBhc3NldCBuYW1lIG9rYXk=",
"type": 0,
"uint": 0
},
{
"bytes": "SW4gYXBwIGlkIDIzIHdoaWNoIHdhcyBjYWxsZWQgd2l0aCBhc3NldCBuYW1lIG9rYXk=",
"type": 1,
"uint": 0
}
],
```
Note that the N-1 element has its type set to 0.
Modified existing test, without the change in the dryrun.go …
=> REST API: dryrun scratch slot type fix

components/mocks/mockParticipationRegistry.go, data/account/participationRegistry.go, data/account/participationRegistry_test.go, data/account/participation_test.go, data/accountManager.go, data/accountManager_test.go, node/node.go, util/db/dbpair.go, util/db/dbutil.go
This PR completes the previous started efforts and ensure all the requests are tunneled directly to the participation registry for optimal performance.
Unit tests added.
=> participation key registry : complete cleanup

daemon/algod/deadlockLogger.go
The TestDeadlockLogging was generating large amount of "junk" on top of the expected stack trace.
This PR addresses that by dropping the redundant data.
Example: https://circleci.com/api/v1.1/project/github/algorand/go-algorand/92568/output/106/0?file=true&allocation-id=622fb105959ff4390b6b098f-0-build%2F5VSI2HBA
Unit test exists.
=> testing: avoid generating large output on TestDeadlockLogging

data/transactions/logic/assembler.go, data/transactions/logic/debugger.go, data/transactions/logic/eval.go, data/transactions/logic/evalStateful_test.go, data/transactions/logic/eval_test.go, data/transactions/logic/fields.go, data/transactions/logic/ledger_test.go, data/transactions/logic/opcodes.go, ledger/internal/eval_blackbox_test.go, ledger/internal/txnbench_test.go
This reworks the opcode function interface to return errors directly instead of setting cx.err which was error-prone.
It also makes a couple small optimizations.
=> AVM: Improve error handling and execution time

cmd/goal/clerk.go
When trying to sign a transaction file with goal, if the sender is a normal address but the signer is a logic program, the call fails with an error message like:
`send.txn: txn[0] error LogicNot signed and not a Logic-only account`
The error message comes from https://github.com/algorand/go-algorand/blob/33b87c432065d3be0ce1fdad682604f416676133/data/transactions/verify/txn.go#L314
It notes that a valid case is when Auth is set to the hash of the program but we aren't setting the auth on the transaction even if the -S flag is passed
Made a txn where sender is a regular account and signed it with
```sh
goal clerk sign -i tmp.txn -o tmp.txn -S BJATCHES5YJZJ7JITYMVLSSIQAVAWBQRVGPQUDT5AZ2QSLDSXWWM46THOY -p tmp.teal
```
I borked the git history on the last one #3459 so just nuked it and …
=> Goal: Add check for signer passed in the case of logic sig rekeyed account

compactcert/abstractions.go, compactcert/builder.go, compactcert/worker_test.go, node/node.go
In DevMode, do not create a block for internal events (i.e. compact-cert creation).
This is to assure reproducibility and eliminate the random shifts in round numbers.
=> DevMode: create a block for external txns only

ledger/acctupdates.go, ledger/acctupdates_test.go, ledger/catchpointtracker_test.go, ledger/ledger.go
The existing Ledger.OnlineTotals is going ( at the end of the 320 project ), be using the onlineAccountsTracker to get its information from.
But unlike the existing l.accts.Totals(rnd) call, it won't get the totals, but only the amount of online totals ( i.e. basics.MicroAlgos ).
Prepare the Ledger implementation for that change by deprecating the accountUpdates.Totals and naming it OnlineTotals. As such, it would return just the online portion of that structure ( i.e. totals.Online.Money ).
Ran existing tests on Ledger.OnlineTotals
=> Ledger: Refactor online totals

data/basics/userBalance.go, ledger/accountdb.go, ledger/accountdb_test.go, ledger/acctonline.go, ledger/acctupdates.go, ledger/acctupdates_test.go, ledger/catchpointtracker_test.go, ledger/ledger.go, ledger/ledgercore/accountdata.go, ledger/tracker.go, ledger/tracker_test.go, ledger/trackerdb.go, ledger/voters.go, scripts/dump_genesis.sh, test/framework/fixtures/expectFixture.go
At the moment the new tracker has the same logic as account updates
but has own onlineacctbase round and own committing logic
Because of trackers' initialization logic
the new onlineacctbase and old acctbase must be synchronized.
This is done at the end of onlineAccounts.produceCommittingTask
Disclaimer: eventually most of this code will be removed
but this PR allows independent work on removing 320 rounds from account updates
and implementing the history storing in online accounts tracker
=> 320 rounds: make a separate online accounts tracker

ledger/acctupdates_test.go
The changes in #3770 didn't include the changes in #3769 and so tests don't compile on master currently — this updates another test that uses `Totals` to use `LatestTotals` instead.
Fixes tests.
=> tests: fix TestAcctUpdateslookupLatestCacheRetry

.circleci/config.yml, .github/workflows/build.yml, .github/workflows/reviewdog.yml, Makefile, go.mod, network/dialer.go, network/rateLimitingTransport.go, network/wsNetwork.go, scripts/buildtools/go.mod, scripts/buildtools/install_buildtools.sh, scripts/get_golang_version.sh, scripts/travis/before_build.sh, shared/pingpong/accounts.go, shared/pingpong/pingpong.go, test/e2e-go/features/participation/participationRewards_test.go, test/scripts/e2e_go_tests.sh, util/condvar/timedwait.go, util/sleep.go, util/sleep_linux.go
This PR upgrade the go-algorand repository to use go 1.16 while adding workarounds for https://github.com/golang/go/issues/44343.
Use performance testing to verify no regressions.
=> build: compile with golang 1.16

cmd/tealdbg/local.go, cmd/tealdbg/local_test.go, go.mod, go.sum
Removes `LocalRunner.Run` in favor of `LocalRunner.RunAll` to ensure tests follow the same debugging logic as `tealdbg` execution.
* While reviewing https://github.com/algorand/go-algorand/pull/3653 (https://github.com/algorand/go-algorand/pull/3653#discussion_r828332450), I realized `LocalRunner.Run` exists _only_ for testing purposes.   Since there's no (known) reason to retain 2 paths for the same logic, I opted to remove `Run`.
* The majority of changes focus on updating tests to reflect `RunAll`'s different method signature.  I made attempts to introduce testing facilities that I felt simplify test writing and may later be useful in other tests.  As a nascent Go programmer, it's unclear to me if I defined helper functions in _reasonable_ places.   I welcome reviewer feedback.     
* …
=> tealdbg:  Replace LocalRunner.Run with LocalRunner.RunAll

data/abi/abi_encode_test.go
A follow-up PR from #3823, adding one moar testcase to test `inferToSlice` will error when passing a `nil` with unexpected type (i.e., type other than slice or array).
=> Bug-Fix: ABI inferToSlice nil testcases

daemon/algod/api/client/restClient.go, libgoal/libgoal.go
Small tweak, this sets the "exclude" parameter for both all/none cases used by the algod RestClient.AccountInformationV2 method, rather than an empty string for one of the cases.
=> REST client: always set Exclude value in accountInformationParams

data/ledger_test.go, ledger/ledger_test.go, ledger/ledgercore/accountdata.go
* This is a prerequisite test before retiring AccountData.OnlineAccountData()
that is used only in tests agreement and committee tests.
* Historically all these tests depends on genesis data that is basic.AccountData.
* Our GA genesis files have stake, status and voting data and never had resources
basic.AccountData can be reduced to the original stake + voting data state and
a new basic.AccountDataEx can be introduced for using in REST API
* Ledger tests and test network generation tools need to be updated to
accept a new reduced (original) basic.AccountData as genesis and resource records
for assets and apps needed for tests after the ledger initialization.
This is a test PR
=> ledger: test OnlineAccountData

data/abi/abi_encode.go, data/abi/abi_encode_test.go, data/abi/abi_json_test.go, data/transactions/logic/eval.go, data/transactions/logic/evalCrypto_test.go
The current go-algorand build is over golang 1.16, which means we can revert #3498.
#3498 is introduced for the sake of downgrading golang for perf issues, now we should lift back to earlier implementation.
We also re-enable `FillBytes` in `leadingZero` implementation, and update `elliptic.(un)marshalCompressed` for #2852 .
=> Enhancement: Re-enable `fillBytes` method in ABI and eval.go implementation

daemon/algod/api/server/v2/dryrun.go, daemon/algod/api/server/v2/dryrun_test.go
This is the second issue with making a slice of a given length but then appending to it instead of setting elements by index. 
We probably should look through to see where/if this is done elsewhere.
Result of this bug prior to the fix, note txns[0]['local-deltas'][0] here:
https://raw.githubusercontent.com/algorand/algorand-sdk-testing/131b0d90f5a1c4c93b43b7f5b4126c568dc29613/features/resources/v2algodclient_responsejsons/largeDryrunResponse.json
=> Algod: Fix issue with nil accounts in local-deltas array

crypto/secp256k1/secp256_test.go, data/transactions/logic/assembler_test.go, data/transactions/logic/evalCrypto_test.go, data/transactions/logic/evalStateful_test.go, data/transactions/logic/eval_test.go, data/transactions/logic/opcodes_test.go, ledger/internal/eval_blackbox_test.go, test/e2e-go/cli/goal/account_test.go, test/e2e-go/cli/goal/clerk_test.go, test/e2e-go/cli/goal/node_cleanup_test.go, test/e2e-go/features/transactions/sendReceive_test.go
We have a test partitioning system that uses calls to partitiontest.PartitionTest(t) to shard tests. There is also a verification job to check for accidentally skipped or unnecessarily multiply-run tests. This cleans up some of the "RAN MULTIPLE TIMES" warnings of unnecessarily multiply-run tests from output like https://app.circleci.com/pipelines/github/algorand/go-algorand/5910/workflows/d5620b33-8dd4-4211-a1b1-1780a792126a/jobs/99253 and https://app.circleci.com/pipelines/github/algorand/go-algorand/5907/workflows/ee653582-9329-43f2-87fc-51dc047d2e3d/jobs/99171
Existing tests should pass, and there should be fewer "RAN MULTIPLE TIMES" warnings in the verification job output. There should be no "UNINTENTIONALLY SKIPPED" errors in the output (this would trigger a CI error).
=> CI: add test partitioning based on partition test verifier output

data/transactions/logic/opcodes.go
Extracts `divideCeilUnsafely` function to help document opcode costing rationale.  Stems from discussion in https://github.com/algorand/go-algorand/pull/3857#discussion_r844091506.
Analysis below shows `divideCellUnsafely` is inlined.  Implies there's _no_ overhead for adding the function.  The logs show `divideCell` because I renamed the method after an initial pass.
```
~/dev/go-algorand/data/transactions/logic divide_ceil !1 ?2 ───────────────────────────────────────────────────────────────────── 04:06:17 PM
❯ go build -gcflags=-m=2 . 2>&1  | grep opcodes.go | grep 'divideCeil'
./opcodes.go:73:6: can inline divideCeil with cost 8 as: func(int, int) int { return (numerator + denominator - 1) / denominator }
./opcodes.go:77:6: can inline (*linearCost).compute with cost 43 as: …
```
=> AVM:  Extract divideCeilUnsafely to help document opcode costing rationale

crypto/msgp_gen.go, data/basics/userBalance.go, ledger/accountdb.go, ledger/accountdb_test.go, ledger/acctonline.go, ledger/acctupdates.go, ledger/acctupdates_test.go, ledger/catchpointwriter_test.go, ledger/ledger.go, ledger/ledgercore/accountdata.go, ledger/msgp_gen.go, ledger/msgp_gen_test.go, ledger/testing/initState.go, ledger/testing/randomAccounts.go, ledger/tracker.go, ledger/tracker_test.go
* migration accountbase -> onlineaccounts
* online account deltas, compact deltas, new round implementation
* baseOnlineAccountData new storage data structure
* deletion logic
Adjusted some tests, added tests for new online accounts table queries.
Added expiration/deletion tests
1. Totals as a table
2. Remove lookback param
=> 320 rounds: online accounts DB support

.circleci/config.yml, test/README.md, test/scripts/e2e.sh
Every night, the e2e test results should be uploaded to the s3 bucket so that indexer tests can be run against the latest test results.
=> Enhancement: Nightly e2e test upload

agreement/cryptoVerifier.go, agreement/pseudonode.go
In #2741 we added some additional logging for cases where the pseudonode tasks queues (used by MakeVotes and MakeProposals) were full, or if the cryptoVerifier response queue was full, or if it was taking more than 2s to wait for a verifier task to return. This adds counters to accompany those log messages.
=> agreement: add counters for dropped tasks and slow responses

test/testdata/deployednettemplates/recipes/txnsync/Makefile, test/testdata/deployednettemplates/recipes/txnsync/gen_topology.py, test/testdata/deployednettemplates/recipes/txnsync/genesis.json, test/testdata/deployednettemplates/recipes/txnsync/net.json, test/testdata/deployednettemplates/recipes/txnsync/node.json, test/testdata/deployednettemplates/recipes/txnsync/nonPartNode.json, test/testdata/deployednettemplates/recipes/txnsync/recipe.json, test/testdata/deployednettemplates/recipes/txnsync/relay.json, test/testdata/deployednettemplates/recipes/txnsync/topology.json
Added "txnsync" recipe matching configuration requirements for txn sync testing on Betanet. 
Tested recipe by using algonet to launch a network.  Verified that the rounds were progressing.
=> DevOps: Added recipe for transaction sync testing.

.circleci/config.yml
Remove old CI analysis upload step.
=> CI: remove buildpulse upload step

ledger/accountdb.go, ledger/accountdb_test.go, ledger/acctonline.go, ledger/acctonline_test.go, ledger/lruonlineaccts.go, ledger/lruonlineaccts_test.go, ledger/persistedonlineaccts_list.go, ledger/persistedonlineaccts_list_test.go, ledger/testing/randomAccounts.go, ledger/tracker.go
* Added LRU cache to track the most recent updates into onlineaccounts table
* TODO: add another cache for looking up since accounts can change
and we need answers about specific round, not the most recent write round
* Added online accounts tests for updates and expirations
=> 320 rounds: Add LRU cache into online accounts tracker

node/node.go
More efficient check for pending transactions. In most cases, the check will be done right away, so it would be in a recent round. The check starts at the oldest round, which is the opposite of what would normally happen.
Existing unit tests.
=> REST API: Check for pending transactions in most recent rounds first.

cmd/algokey/part.go, cmd/goal/account.go, libgoal/participation.go
@algonoah and I noticed that `algokey part generate` sets the default key dilution parameter to the square root of the round range, but `goal account addpartkey` sets the default key dilution parameter to 10000. This updates goal to use the same formula as algokey.
This is also used by `goal account renewpartkey` and `renewallpartkeys`.
from algokey part generate:
https://github.com/algorand/go-algorand/blob/6b7dfb635d100d20c67259f091f0390e4498d9c3/cmd/algokey/part.go#L59-L61
=> goal: Set default key dilution to be the same as algokey

cmd/goal/clerk.go, test/scripts/e2e_subs/e2e-teal.sh
Follow up to #3726 - renamed source map file to match the output file rather than the input file to follow [existing conventions ](https://sourcemaps.info/spec.html) more closely. Thanks to @jasonpaulos for the catch!
Changed an existing `e2e` test to match the new file path.
=> goal: Rename source map output file

cmd/algokey/keyreg.go
While using the new algokey subcommand I noticed some of the error messages were not correct.
=> Algokey: clarify some error messages.

cmd/goal/network.go, netdeploy/network.go, netdeploy/networkTemplate.go, test/framework/fixtures/libgoalFixture.go
Thinking out loud a little bit with this PR.
Rather than requiring a separate network configuration, this flag lets you run an existing single node network template in dev mode. This would allow tools like sandbox to ship with a single template instead of two.
Ran manually with `OneNodeFuture.json` template.
=> netdeploy: Add override to enable devmode for a network template.

cmd/algod/main.go, cmd/algod/main_test.go, config/localTemplate.go, daemon/algod/server.go
Add an implicit option to write log to stdout by setting LogSizeLimit to 0.
=> algod: Write to stdout when config.LogSizeLimit is 0 or -o is passed to algod.

cmd/algocfg/getCommand.go, cmd/algocfg/getCommand_test.go
algocfg was returning values like `%!s(uint64=16)` and `%!s(bool=true)`, with this change those are fixed to return `16` and `true`.
Seemed silly to unit test a built in function, but  I went ahead and did it anyway.
=> algocfg: Fix algocfg get for non-string parameters.

ledger/applications_test.go, ledger/tracker.go, ledger/tracker_test.go
There is an issue with `trackerRegistry.dbRound` value and cached dbRound values stored in trackers.
Although they are updated under the same lock, `produceCommittingTask` might use non-updated `dbRound` and give it to trackers with updated state.
The fix is simple: have `dbRound` usage and `produceCommittingTask` invocation under the same lock.
Added a new test that dances with locks and simulates the race. Unfortunately after the wider locking it looks like impossible to recreate it.
=> ledger: fix possible dbRound unsynchronization for trackers and registry

logging/telemetry.go
When running diagcfg as a user without a home directory, the missing global default directory prevents diagcfg from writing `logging.config`. With this change, the error is cleared out so that the file can be created as usual.
The only risk is if the global logging file was being used, and is for some reason temporarily inaccessible, those defaults would not be copied into the new file.
Manual testing.
Run diagcfg with ALGORAND_DATA and -d, the file is created in the data directory.
Run diagcfg without ALGORAND_DATA or -d, the file is created in the default global directory.
Also tested on a docker environment where the user did not have a home directory (or default global directory), the logging file is created in the data directory.
=> diagcfg: Allow diagcfg to create logging.config in data directory.

cmd/goal/messages.go, cmd/goal/network.go, netdeploy/networkTemplate.go, util/io.go, util/io_test.go
In order to run private networks in docker, it is convenient to mount
the data directory. By disallowing the network directory to exist it is
not possible to mount the node directory ahead of time.
Unit test for new utility function.
=> netdeploy: Allow empty private network directory.

util/sleep.go, util/sleep_linux_32.go, util/sleep_linux_64.go
arm32 has int32 field members in Timespec struct, but Nanoseconds() returns int64.
The arm32-specific implementation of NanoSleep casts it to int32 as Timespec expects.
Existing tests
=> utils: add arm32-specific NanoSleep implementation

agreement/actions.go, logging/telemetryspec/event.go
This adds to the BlockAccepted telemetry event the size of the rawVotes and rawProposals buffered channels. This provides a snapshot in time of how many unprocessed votes and proposals had not been handled yet by agreement at the end of a round (when a block is certified and validated).
=> agreement: report proposal and vote message buffer sizes at end of round

docker/build/cicd.ubuntu.Dockerfile, test/muleCI/mule.yaml
There's an issue with DNS resolution with the arm32v6/golang1.16.15-alpine image. It isn't able to resolve `apk update` on the cluster. Instead, we'll switch to building the arm32 image with arm32v7/ubuntu:18.04 image instead.
We will lose arm32v6 support for Raspberry Pi 1 with this change.
Tested both locally and on the build pipeline with [pull/3930](https://github.com/algorand/go-algorand/pull/3930) changes and the results looks good.
=> Build: Update build image from arm32v6 to arm32v7

test/muleCI/mule.yaml
Replace the centos7 container with centos8 for awscli.
This is a quick fix. A better fix would replace this container with
something more lightweight, as it's doing too much for this step.
Ran a local build.
=> Devops: Replace awscli container for upload

ledger/acctupdates.go, ledger/acctupdates_test.go, ledger/ledgercore/accountresource.go
* In some situations the method might incorrectly count
deleted items towards total items
* This might result not returning all the resources to
REST API clients
Test added
=> ledger: fix lookupLatest usage of the resources cache

ledger/catchpointtracker.go
While upgrading to golang 1.17.9 I've run into a couple of race conditions which have been detected during E2E tests. This fixes one of them during which a write happens at https://github.com/algorand/go-algorand/blob/master/ledger/catchpointtracker.go#L417 and a read happens at https://github.com/algorand/go-algorand/blob/master/ledger/catchpointtracker.go#L173
e2e tests
=> race condition: Add lock around catchpointsMu to avoid race condition

scripts/check_deps.sh
Adds `scripts/buildtools/install_buildtools.sh` to the list of suggested remediations when `check_deps.sh` fails.
`golint`, `stringer`, and `msgp` are checked via this script, but are installed by `install_buildtools.sh` and not `configure_dev.sh`.
=> build: Add install_buildtools.sh to check_deps.sh error message

cmd/goal/account.go, libgoal/libgoal.go, libgoal/participation.go, libgoal/transactions.go, node/node.go, test/e2e-go/features/participation/accountParticipationTransitions_test.go, test/e2e-go/features/participation/onlineOfflineParticipation_test.go, test/e2e-go/features/participation/participationExpiration_test.go, test/e2e-go/features/transactions/onlineStatusChange_test.go, test/e2e-go/stress/transactions/createManyAndGoOnline_test.go, test/scripts/e2e_subs/goal-partkey-commands.sh
Resolves #2594
Goal account commands now use the REST API
=> Enhancement: Migrate goal account commands to REST API

test/scripts/e2e.sh, test/scripts/e2e_client_runner.py
A couple of small quality of life fixes for e2e tests that I've run into issues with.
1. In `e2e.sh` when we fail to set the `E2E_PLATFORM` variable, the shell will complain that we are using a binary operator (`==`) on a single argument. Setting the left side of the test statement to a string with variable interpolation fixes this.
2. The e2e python client runner does not initialize the `stdout` and `stderr` variables which causes an exception in `reportcomms(p, stdout, stderr)` when the except block runs after `p.communicate` raises an exception. Initializing to None fixes this.
Found and fixed while running e2e tests in failure scenarios.
=> e2e tests: Fixes for e2e test runs

test/framework/fixtures/baseFixture.go, test/framework/fixtures/expectFixture.go
Running e2e go tests fails when the repo is not cloned inside the GOPATH. This change looks up the current directory using `runtime.Caller` as an alternative to hard coding the GOPATH location.
note: the Makefile also solves this problem by setting the `TESTDATADIR` environment variable, but that doesn't work when running tests from an IDE.
Existing tests cover this code path. Additionally I manually verified by running a number of e2e-go/expect tests locally
=> Tests: Support e2e-go tests when repo is not installed in GOPATH.

config/consensus.go, ledger/accountdb.go, ledger/accountdb_test.go, ledger/ledger.go, ledger/ledger_test.go, ledger/msgp_gen.go, ledger/tracker.go, ledger/trackerdb.go, ledger/txtail.go, ledger/txtail_test.go
1. Make block header accessible from txtail with BlockHdrCached method
2. Some fixes to in-memory data representation
3. Added new consensus parameter to increase blocks lookback size
4. More comments and test
=> 320 rounds: expose block header from txtail

cmd/goal/clerk.go, data/transactions/transaction.go, data/transactions/transaction_test.go, data/txntest/txn.go, ledger/internal/eval.go, libgoal/transactions.go
For clarity, always use Transaction.ID() when generating the txid hash of a Transaction. `crypto.HashObj(txn)` is equivalent but less commonly used and can lead one on a wild goose chase to determine, "wait, is that equivalent?"
No functional change should be in this change. No new features. Should just pass existing tests.
=> cleanup: replace crypto.HashObj(Transaction) with Transaction.ID()

libgoal/libgoal.go, node/node.go, test/e2e-go/features/participation/overlappingParticipationKeys_test.go
Resolves #2596
Removes function which calls loadParticipationKeys() every 60 seconds
since MakeFull() for the FullNode does the same thing
Resolves #3924
Installs state proof keys inside of algod after getting the binary blob
Resolves #3106 
Removes the ability to create temporary files from the REST interface.
=> PKI: 3924 handle stateproof in rest api goal

.codecov.yml
Since the codecov app was enabled, it is showing up in PR status checks. This adds a quick configuration based on https://docs.codecov.com/docs/commit-status that we can refine more later.
Status check should pick up changes.
=> CI: add simple codecov config

crypto/stateproof/coinGenerator.go, crypto/stateproof/coinGenerator_test.go, crypto/stateproof/const.go
In order to support changes in the stateproof verifier, we need to add a version number to the coinChoiceSeed structure so that Fiat-Shamir could be used safely in the future.
=> add version to coin-generator

cmd/algokey/main.go
Algokey was missing a way to tell what version it's using. One should be able to run `algokey -v` and get the same output as `goal -v`.
`algokey -v` gives the same output as `goal -v`
=> Algokey: Add -v flag to get the version

scripts/compute_branch.sh
This addresses a problem when building a release based on checking out a tagged commits. I noticed the problem when automating some docker container builds, I'd check out each tagged commit and the channel was being set to `dev`.
Our build channel scripts were unable to determine the correct channel. With this change, the script will check if the tag ends with one of the known tags and set the "BRANCH" variable such that the other scripts will properly detect the channel.
Manual tested by checking out different tags / commits and making sure things look correct.
=> ci: use tag to determine channel if possible

data/transactions/logic/eval.go, data/transactions/logic/eval_test.go
base64 decoding now operates on padded or unpadded encodings.  Since \r and \n are ignored while decoding, the approach we take is to look for padding, and use the padded encoding if we find any, or raw if we don't. (This contrasts with how we (I?) expected to do it - by checking if the padding was correct and stripping it off.  But that would require scanning the string, not just checking the length.)
=> AVM: base64_decode can decode padded or unpadded encodings

ledger/accountdb.go, ledger/accountdb_test.go, ledger/acctonline.go
This will allow to write a migration unit test - the old schema uses accountbase and its queries, and the new - the new queries from a separate class and without the "onlineaccounts table does not exist" error.
=> Move online queries into onlineAccountsDbQueries

cmd/updater/update.sh
Fixes #2581 
While downloading and installing the `updater`, the commands were not specific about which directories to download and unarchive. Because of this, if `update.sh` was in `$PATH` and was executed from a different directory, the `updater` archive would be installed in the `$PWD` causing the script to not function as expected (download remaining tools), and would not error out.
This solves that by creating a temporary directory and modifying the commands around installing the `updater` more explicit to make sure that `updater` is in the same directory as `update.sh`.
This also adds a `-verify` command line flag (defaults to `false`). If set, `update.sh` will check if GPG and checksum validation is possible on linux systems, if so, the signature, public key, and checksum file will …
=>  fix: place updater in same directory as update.sh

ledger/catchpointtracker_test.go
Similar to https://github.com/algorand/go-algorand/pull/4042.
Test code is changed.
=> 320 rounds: fix more data races in catchpoint tracker tests.

daemon/algod/api/server/v2/handlers.go, daemon/algod/api/server/v2/test/handlers_test.go
=> StateProofs: fix GetProof endpoint response

agreement/fuzzer/bandwidthFilter_test.go
Fixed typo.
```
reseting -> resetting
```
=> agreement: fix typo in bandwidthFilter_test

scripts/install_linux_deps.sh
Close #3894.
Fix install dependencies on manjaro linux.
Please check it! Thanks <3
On my local machine.
=> Developer Tools: Add manjaro support to build script

cmd/pingpong/runCmd.go, shared/pingpong/accounts.go, shared/pingpong/config.go, shared/pingpong/pingpong.go
Currently the transaction scheduling logic in pingpong is lots of complicated sleep calls. Some sleeps were definitely extra and were hurting tps; this PR deprecates them. The whole scheduling logic is replaced with a much simpler one. Let timestamp sequence `{t}_{i >= 0} = {currenttime + 1 / tps * i}`. Then transaction `i` is sent at time `t_i` with best effort.
In my tests `./pingpong run --tps 115 --rest 0 --refresh 1800 --numaccounts 500` produced 440 txns per block. Now `./pingpong run --tps 115 --refresh 1800 --numaccounts 500` produces 475 txns per block. (`--rest` was deprecated)
Related to https://github.com/algorand/go-algorand-internal/issues/1833.
I ran it.
=> pingpong: improve transaction scheduling

ledger/accountdb_test.go, ledger/acctupdates_test.go, ledger/catchpointtracker_test.go, ledger/testing/randomAccounts.go
`TestReproducibleCatchpointLabels` gets stuck sometimes. The problem is in https://github.com/algorand/go-algorand/blob/feature/320-rounds/ledger/testing/randomAccounts.go#L241-L247 and https://github.com/algorand/go-algorand/blob/feature/320-rounds/ledger/testing/randomAccounts.go#L273-L279. If there are no assets / apps, the loops never terminate.
Ran `TestReproducibleCatchpointLabels` 1000 times.
=> 320 rounds: fix another flakiness in `TestReproducibleCatchpointLabels`

ledger/accountdb.go, ledger/acctonline.go, ledger/acctupdates.go, ledger/catchpointtracker.go, ledger/catchpointtracker_test.go, ledger/catchpointwriter.go, ledger/catchpointwriter_test.go, ledger/ledger_test.go, ledger/msgp_gen.go, ledger/tracker.go
List of tweaks:
1. Do not gzip catchpoint data file
2. Preallocate chunks buffer for catchpoint repacking
3. Fix sql.Rows leak in encodedAccountsBatchIter
4. Move resourcesData variable out of accounts reading loop
5. Clear au and ao deltas before slicing
6. Get rid of dcc.deltas
=> 320 rounds: memory optimizations

ledger/accountdb_test.go, ledger/acctupdates_test.go, ledger/catchpointtracker_test.go, ledger/testing/randomAccounts.go
Similar to https://github.com/algorand/go-algorand/pull/4068.
Ran `TestReproducibleCatchpointLabels`.
=> ledger: fix flakiness in `TestReproducibleCatchpointLabels`

libgoal/transactions.go, test/e2e-go/features/participation/participationExpiration_test.go
Resolves [#2088](https://github.com/algorand/go-algorand-internal/issues/2088)
Currently these tests are failing:
TestParticipationAccountsExpirationFuture
TestParticipationAccountsExpirationNonFuture
Add validity round checks so that rounds are appropriately set when generating the registration transaction.
=> Bug Fix: Adds validity round check for failing tests

config/consensus.go, ledger/internal/apptxn_test.go
Added test for protocol version before inners were introduced to ensure downgrading is allowed then.
=> AVM: Allow app downgrades in old protocol versions

ledger/accountdb.go, ledger/catchupaccessor.go, ledger/trackerdb.go
Restore catchpoints into a V6 database and let the migration update the database.
Manually ran fast catchup.
=> 320 rounds: fix restoring from a catchpoint

data/transactions/logic/TEAL_opcodes.md, data/transactions/logic/doc.go, data/transactions/logic/eval.go, data/transactions/logic/eval_test.go, data/transactions/logic/jsonspec.md, data/transactions/logic/jsonspec_test.go, data/transactions/logic/opcodes.go
Made from Jacob's branch to fix a lint error while he's out.
=> AVM: Set proper costs for json_ref

catchup/catchpointService.go
Download `DeeperBlockHeaderHistory` more blocks in fast catchup.
Closes https://github.com/algorand/go-algorand/issues/3467.
There are currently no tests for this code. But the change is trivial.
=> 320 rounds: download `DeeperBlockHeaderHistory` more blocks in fast catchup

ledger/accountdb.go, ledger/accountdb_test.go
Mainnet testing revealed some offline accounts with non-empty StateProofPK.
This would prevent us from running tests so I temporary disabled the check.
To enable:
1. Clear StateProofPK in apply: https://github.com/algorand/go-algorand/pull/4092
2. Migrate existing offline accounts with non-empty StateProofPK
3. Disable catchpoints until the next consensus version
4. Rollback this PR
=> Temporary disable empty voting data check

ledger/catchpointtracker.go
Use `removeSingleCatchpointFileFromDisk()` that deletes a catchpoint file and all empty parent directories up to `dbDirectory`.
Will test manually after code freeze.
=> Use a utility function to delete catchpoint (data) files

daemon/algod/server.go, logging/log.go, logging/telemetryConfig.go, logging/telemetryhook.go, logging/telemetryspec/event.go, network/requestTracker.go, network/wsNetwork.go
This adds the telemetry hostname and instanceName to the labels passed to the MetricService, along with the other session label. They end up getting exported in Prometheus format as metric labels.
=> metrics: specify telemetry hostname and instance name as prometheus labels

ledger/catchpointtracker.go
The current code generates
```
{"file":"catchpointtracker.go","function":"github.com/algorand/go-algorand/ledger.(*catchpointTracker).generateCatchpointData.func1","level":"warning","line":1065,"msg":"catchpointTracker: generateCatchpoint: failed to reset transaction warn deadline : the provided tx does not have a valid txExecutionContext object in it's context","name":"","time":"2022-06-09T16:25:34.781302-04:00"}
```
None.
=> Revert a small change related to contexts in catchpoint tracker

cmd/buildtools/genesis.go, data/bookkeeping/genesis.go, data/bookkeeping/genesis_test.go, netdeploy/remote/deployedNetwork.go, node/node.go, test/e2e-go/features/participation/overlappingParticipationKeys_test.go
While working on Indexer we found some of the genesis operations to require duplicate or awkward code. Adding these methods to the genesis object simplifies things.
New unit test and existing regression tests.
=> Misc: Add helper functions to genesis.

network/wsNetwork.go, network/wsNetwork_test.go
Cond.Broadcast() can be missed if it comes before we .Wait() again, use channel instead. This _probably_ only actually mattered in test situations.
Test was flaky but usually worked, but sometimes expressed after many repeated runs of:
```
go test -race -count 10 -timeout 5m -run TestWebsocketNetworkMessageOfInterest -v
go test -race -count 10 -timeout 5m -run TestWebsocketNetworkTXMessage -v
```
=> network: message-of-interest tiny bugfix

ledger/ledgercore/error.go
=> ledger: fix typo in error.go

test/muleCI/mule.yaml
- updates the build pipeline to incorporate darwin `amd64` builds into the internal build pipeline
=> CICD: update build pipeline for darwin-amd64

logging/log.go
Indexer is using algod objects and we need a way to pass a regular logrus object into algod. This adds a simple way to initialize an algorand logger.
=> logging: Add a way to inject an external logger.

cmd/goal/network.go, netdeploy/network.go
`goal network create` required a `-n` flag to specify the network
name.  But the name can be set in the template file.  Now we error
only if neither place specifies a network name.
=> goal: Make the -n flag (network name) optional. Get it from template file

stateproof/worker_test.go
Test that relays forward signatures from other nodes only after half of the period.
=> Test: signature not fromThisNode broadcast in the second half

crypto/curve25519.go
Almost trivial optimization. No new tests.
=> Metrics: Don't allocate when invoking the Inc() fastpath

ledger/accountdb.go, ledger/acctonline.go
Was reviewing onlineAccounts.lookupOnlineAccountData and onlineTop with @algoidan and @algorandskiy and made some changes for comments and clarity.
=> ledger: Update onlineAccounts lookup methods for slightly easier reading

installer/genesis/alphanet/genesis.json, installer/rpm/algorand/algorand.spec, scripts/build_deb.sh, scripts/build_package.sh, scripts/compute_branch_channel.sh, scripts/compute_branch_network.sh, scripts/release/build/deb/build_deb.sh, scripts/release/mule/common/get_channel.sh, scripts/release/mule/deploy/docker/docker.sh, scripts/release/mule/package/deb/package.sh, scripts/release/mule/test/test.sh
Added support for building alpha channel for alphanet network.  
Tested using go-algorand.muleci-full-pipeline.  
Successful build here: https://jenkins.algodev.network/job/go-algorand.muleci-full-pipeline/357/
=> DevOps: Build Alphanet

test/muleCI/mule.yaml
- removes the `installer/` genesis files from the stash steps because it was determined that they were used for integration tests, and those tests are no longer being done in that pipeline
=> CICD: remove unused genesis in stash

.circleci/config.yml, test/e2e-go/cli/goal/expect/testInfraTest.exp
- upgrades `xcode` to `13.4.1` since CircleCI is planning to deprecate the version we are using
- removes `s` from `sleep` commands in `testInfraTest.exp` expect tests b/c newer versions of macos do not allow that syntax anymore
- [CircleCI Forum Discussion on Xcode Deprecation](https://discuss.circleci.com/t/xcode-image-deprecation/44294/1?mkt_tok=NDg1LVpNSC02MjYAAAGFSZXgsHTICuosKRkrrxHGCK-SAogChAwfy_DisiqWPFLTeSMU4WlPOQrLjO_-Fn94GHt46tYVydmYIgleXEorwXwTcGaJJxciUXabDaUHGxqW2A)
- see circleci tests
=> CICD: upgrade xcode on circleci macos executors

ledger/ledgercore/statedelta.go
Leases are almost never used but the map get preserved in txtail.
=> Fix exceed mem allocation in state deltas

data/basics/overflow.go, data/basics/units_test.go
go test -run ^NOTHING -bench 'BenchmarkOldMulDiv|BenchmarkNewMulDiv'
goos: darwin
goarch: amd64
pkg: github.com/algorand/go-algorand/data/basics
cpu: Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
BenchmarkOldMulDiv-8   	 2501655	       479.3 ns/op
BenchmarkNewMulDiv-8   	653492884	         1.801 ns/op
=> Optimization: Use bits package for Muldiv. 266x speedup

.circleci/config.yml
- adds new `mac_arm64` executor
- updates the nightly jobs to include the `mac_arm64` platform, this is because of the restrictions of self-hosted runners and the fact that they take longer to execute
- adds a step to `prepare_build` so that `/opt/cibuild` is cleaned up before the workspace/cache is pulled in, this isn't necessary on ephemeral instances, but runs into conflicts on non-ephemeral ones
- removes superfluous branch filters in `test_*` jobs since they can rely on the filters of their required jobs. This also required that a separate `build_nightly` and `test_verification_nightly` be created so that we get notified of those failures
- see _all_ circleci runs, I've disabled the branch filters during testing and re-enabled them one last time before review. So the last run may not …
=> CICD: add m1 to integration tests

ledger/accountdb.go, ledger/catchpointtracker.go, ledger/tracker.go, test/e2e-go/cli/goal/expect/catchpointCatchupTest.exp, test/e2e-go/cli/goal/expect/catchpointCatchupWebProxy/webproxy.go, test/framework/fixtures/expectFixture.go, test/testdata/consensus/catchpointtestingprotocol.json
Adjust new catchpoint-related parameters to let the test run properly:
1. Set `CatchpointLookback` to the same value as `MaxBalLookback`
2. Set `MaxAcctLookback` to a small value to allow second stage of the catchpoint generation complete fast.
=> Re-enable catchpoint expect test

config/config.go, config/localTemplate.go
If network is alphanet, then set DNS BootStrapId to "alphanet.algodev.network".
Built and tested locally.  Verified that node was increasing rounds.
=> Adjust the DNS Bootstrap Id for Alphanet

config/consensus.go, protocol/consensus.go
This defines a vAlpha2 consensus protocol, with 3.5s filter timeout and 5MiB block size.
=> alphanet: define vAlpha2 consensus parameters

ledger/accountdb.go, ledger/accountdb_test.go, ledger/ledgercore/accountdata.go
In #4003 some pointer receivers and pointer arguments were changed to pass by value and value receivers, which could lead to a performance regression. This changes them back.
There is a small discussion, including a benchmark, in https://github.com/algorand/go-algorand/pull/4003/files#r894844990 (a comment thread on ledger/accountdb.go line 1438)
=> ledger: restore pointer receivers and args from #4003

data/transactions/logic/README.md, data/transactions/logic/TEAL_opcodes.md, data/transactions/logic/fields.go
doc change only (table has been moved, so pointer to it was wrong) better to describe the field anyway
=> AVM: Document what the field _is_ rather than pointer to table

daemon/algod/api/client/restClient.go, libgoal/libgoal.go, test/e2e-go/restAPI/restClient_test.go
The discussion for passing in max box-names exists in here: https://github.com/algorand/go-algorand/pull/4165#discussion_r922398029
The goal of this PR is to extend restClient method `ApplicationBoxes` to accept argument `maxBoxNum` (if `maxBoxNum == 0`, then return all box names).
=> Allow algod client to pass in max box-names number

node/node.go, node/node_test.go
Resolves #2060
Resolves all scenarios described below:
Scenario 1 (S1): Address is closed, but has a participation key that is still registered and valid given the current round number.
Scenario 2 (S2): Address is offline. Could imply no registration txn or an expired one.
Scenario 3 (S3): Address is online, with a valid participation key.
The breakdown of the scenarios by count is as follows:
S1: 7 addresses
S2: 43 addresses
S3: 2 addresses
The following actions are recommended for each scenario:
S1
Check that account is closed for the on-chain data. If account is closed, silently ignore since this account has been officially closed.
S2
Check that account is offline. If account is offline, return error indicating that no registration transaction has been issued or that previous …
=> Enhancement: Detect when valid partkeys represent an offline or closed account

node/node_test.go
Fixes the following test compile errors:
```
~/dev/go-algorand master ⇡65 ?13 ───────────────────────────────────────────────────────────────────────────────────── 02:17:34 PM
❯ gotestsum -- ./node
node/node_test.go:559:41: cannot use promoted field VotingData.VoteFirstValid in struct literal of type basics.OnlineAccountData
node/node_test.go:559:60: cannot use promoted field VotingData.VoteLastValid in struct literal of type basics.OnlineAccountData
node/node_test.go:560:41: cannot use promoted field VotingData.VoteFirstValid in struct literal of type basics.OnlineAccountData
node/node_test.go:560:60: cannot use promoted field VotingData.VoteLastValid in struct literal of type basics.OnlineAccountData
node/node_test.go:561:53: cannot use promoted field VotingData.VoteFirstValid in struct …
```
=> Broken build:  Fix struct initialization with promoted field

scripts/dump_genesis.sh
Make sure that CI fails when something goes wrong in dump_genesis.sh
Previously, `dump_genesis.sh` did not check the exit status of the call to sqlite3. Now it checks all subprocess executions by using `set -e`.
=> Test: Fail codegen_verification if dump_genesis.sh is bad

.circleci/config.yml, test/scripts/e2e.sh
Specify e2e archive in CI to allow building them for multiple branches.
This should let us build test artifacts for integration branches via web triggers (or setting up nightly jobs for the integration branches):
https://circleci.com/docs/triggers-overview#run-a-pipeline-from-the-circleci-web-app
=> testing: Support multiple e2e test archives.

test/e2e-go/features/catchup/catchpointCatchup_test.go, test/framework/fixtures/restClientFixture.go
Attempts to address `TestBasicCatchpointCatchup` failures by making test invocation more deterministic.
I'm generally unfamiliar with the problem space, so take the PR with a grain of salt.  I tested via `gotestsum -- ./test/e2e-go/features/catchup -count=1  -run "TestBasicCatchpointCatchup"`.
I do _not_ think the PR resolves all issues though I hope it's an improvement.  And I'm trying to gauge if others have seen the class of issue described in _notes_.
Notes:
* Example build failure:  https://app.circleci.com/pipelines/github/algorand/go-algorand/8092/workflows/8f01bcf4-8ff0-4474-9eb8-56e0416eb1d3/jobs/145450.  For reasons unclear to me, the issue appears to _only_ impact arm64 processor builds.
* Changes made:
* During my inspection, I observed failed catchups targeting a round > 37. …
=> Tests:  Attempt to make TestBasicCatchpointCatchup more deterministic

.circleci/config.yml, test/scripts/e2e.sh
We want to easily run nightly test on any branch in the main repo.
Nightly tests remove the `-short` flag from tests. They are longer and more thorough. These tests are important especially for large feature branches.
With these changes, algorand devs can Trigger a pipeline on a branch in the go-algorand repo with:
1. Go to CircleCI and specify Project and Branch
2. Select "Trigger Pipeline"
3. Add Parameter: `valid_nightly_branch: {current_branch_name}`, e.g. `valid_nightly_branch: test/master-copy2`
4. During the amd_build_nightly test, it will upload to algorand-testdata/indexer/e2e4/fb2bec22/test-master-copy2.tar.bz2 
Triggered the CircleCI job manually and provided the parameter. Made sure the filename is uploaded.
https://app.circleci.com/pipelines/github/algorand/go-algorand?branch= …
=> CI: Add parameter to run Nightly Test

config/consensus.go, protocol/consensus.go
This defines vAlpha3, which sets the period 0 filter timeout to 3.4s.
=> alphanet: define consensus version vAlpha3

ledger/acctupdates_test.go
The `TestAcctUpdatesFastUpdates` test calls `committedUpTo` and `newBlock` asynchronously with no locking, which causes a data race in the txtail. Since under normal operation these calls are protected by the tracker mutex, we can simply remove the txtail in this test to avoid test failure.
This is a test
=> Ledger: remove txtail from data race test

data/transactions/logic/assembler_test.go, data/transactions/logic/evalCrypto_test.go
This does not activate fido opcodes, but it makes it so that they _can_ be activated by moving LogicVersion=7 in a new consensus version.
=> AVM: Allow fido into a release with v7 on

cmd/loadgenerator/config.go, cmd/loadgenerator/main.go
This allows a list of accounts to be provided, rather than just one, when generating transactions.
=> loadgenerator: add multiple accounts config option

scripts/travis/codegen_verification.sh
Since we commit some products of the `make`, but our goal is to ensure those products are exactly what would be generated, we have to force the generation to actually happen.
=> Test: touch fields_string.go so everything is rebuilt in codegen verification

test/testdata/deployednettemplates/hosttemplates/hosttemplates.json, test/testdata/deployednettemplates/recipes/scenario1s/Makefile, test/testdata/deployednettemplates/recipes/scenario1s/gen_topology.py, test/testdata/deployednettemplates/recipes/scenario1s/genesis.json, test/testdata/deployednettemplates/recipes/scenario1s/net.json, test/testdata/deployednettemplates/recipes/scenario1s/node.json, test/testdata/deployednettemplates/recipes/scenario1s/nonPartNode.json, test/testdata/deployednettemplates/recipes/scenario1s/recipe.json, test/testdata/deployednettemplates/recipes/scenario1s/relay.json, test/testdata/deployednettemplates/recipes/scenario1s/topology.json, test/testdata/deployednettemplates/recipes/scenario3s/Makefile, test/testdata/deployednettemplates/recipes/scenario3s/gen_topology.py, test/testdata/deployednettemplates/recipes/scenario3s/genesis.json, test/testdata/deployednettemplates/recipes/scenario3s/net.json, test/testdata/deployednettemplates/recipes/scenario3s/node.json, test/testdata/deployednettemplates/recipes/scenario3s/nonPartNode.json, test/testdata/deployednettemplates/recipes/scenario3s/recipe.json, test/testdata/deployednettemplates/recipes/scenario3s/relay.json, test/testdata/deployednettemplates/recipes/scenario3s/topology.json
scenario 1 and 3, but a little smaller, single-algod-per-ec2-instance, more like current advised usage
This has been used extensively in recent manual cluster testing
=> test: cluster scenarios for 2022-07

config/localTemplate.go, config/local_defaults.go, installer/config.json.example, ledger/acctonline_test.go, ledger/acctupdates_test.go, test/testdata/configs/config-v23.json
Sets MaxAcctLookback to 4, from 8. MaxAcctLookback was introduced in #4003 and controls the minimum number of in-memory rounds to buffer between the latest block and the state of the account DB that is committed to disk.
Existing tests should pass, with no performance impacts.
=> config: set MaxAcctLookback to 4

stateproof/worker_test.go
The test is randomly failing. The test expects the message decoding to fail. The message is random bytes, but occasionally, the random bytes are accepted by the decoder, causing the test to fail.
The fix is setting the buffer to an arbitrary number instead of generating random bytes each time.
=> test: Fix TestWorkerHandleSigCorrupt

network/wsNetwork_test.go
two calls to `RegisterMessageInterest()` was just a little too hard to synchronize and addedd a rare race bug to the test
Ran test several thousand times and old race condition did not recur (previously reproduced in ~400 runs)
=> test: simplify TestWebsocketNetworkMessageOfInterest

cmd/goal/examples/boxes.teal, data/transactions/logic/README.md, data/transactions/logic/TEAL_opcodes.md, data/transactions/logic/box.go, data/transactions/logic/box_test.go, data/transactions/logic/doc.go, data/transactions/logic/eval.go, data/transactions/logic/langspec.json, data/transactions/logic/ledger_test.go, data/transactions/logic/opcodes.go, ledger/internal/applications.go, ledger/internal/boxtxn_test.go, test/e2e-go/restAPI/restClient_test.go, test/scripts/e2e_subs/tealprogs/boxes.teal
Cleanup some box opcodes to unify their behavior and start documenting it better.
=> More details on spec (and unifiy the box opcodes a bit)

Makefile, data/transactions/logic/assembler_test.go, data/transactions/logic/evalCrypto_test.go, data/transactions/logic/eval_test.go
We don't run benchmarks in CI, so we didn't notice that some of them failed.
=> AVM: Fix crypto benchmarks from bitrot

test/e2e-go/cli/goal/expect/goalExpectCommon.exp
Moved logs printing from `WaitForRound` to `Abort` method.
Sometimes expect tests fail with messages like this that do not help at all.
```
** Error getting status: Get "http://127.0.0.1:45095/v1/status": dial tcp 127.0.0.1:45095: connect: connection refused **
Aborting with Error: error getting network status: 
```
Now test output has more details.
=> tests: extended logging on expect test abort

catchup/service_test.go
Tests that open up a ledger sometime cause a panic since not all the goroutines are closed after the `TestCatchupUnmatchedCertificate` test and the goroutines print more logging messages. This pr closes the ledger after finishing the test to fix this issue.
Reran test 100 times, observed no failures. Before there would consistently be failures within 10 runs.
=> tests: close ledger after TestCatchupUnmatchedCertificate

catchup/catchpointService.go, catchup/service_test.go
=> StateProofs: fix fast catchup bug

ledger/acctonline_test.go, ledger/acctupdates_test.go, ledger/catchpointwriter_test.go
Makes these changes to `newAcctUpdates`:
* Remove unused parameter:  `dbPathPrefix`.  Since the method is test-only and all usages rely on `"."`, I'm _guessing_ customization is _not_ needed.  If the preference is to use the parameter, let me know.
* Require no error during `l.trackers.initialize`.  It seemed prudent to check the returned error.
I considered these changes while reviewing https://github.com/algorand/go-algorand/pull/4275.  Consider the PR optional.  If folks don't think it's worth pulling in, I'll happily close it.
`gotestsum -- ./ledger`
=> Tests:  Remove unused newAcctUpdates parameter:  dbPathPrefix

test/e2e-go/features/transactions/sendReceive_test.go
The TestAccountsCanSendMoney test flakes and sometimes returns that an account has a different balance than expected. This happens because we don't wait for all txns to confirm, only a set of them. Fix it such that we wait for all txns to confirm.
=> test: fix TestAccountsCanSendMoney

cmd/opdoc/opdoc.go, cmd/opdoc/tmLanguage.go
This will keep the generated specs on v7 even if logic.LogicVersion goes to 8.
=> Docs: Control the specs generated seperately from logic.LogicVersion

data/transactions/verify/txn.go
Following discussion in https://github.com/algorand/go-algorand/pull/4322#discussion_r938212627, removes unused `batchVerifier` parameter in `logicSigBatchVerify`.
`gotestsum -- ./data/transactions/verify`
=> Refactoring:  Remove unused logicSigBatchVerify parameter:  batchVerifier

crypto/stateproof/const.go, crypto/stateproof/structs.go, crypto/stateproof/weights_test.go, ledger/internal/eval_test.go, ledger/voters.go, stateproof/builder.go, stateproof/signer.go, stateproof/worker_test.go, test/e2e-go/features/stateproofs/stateproofs_test.go
=> Stateproofs: Reduce num reveals

test/e2e-go/features/stateproofs/stateproofs_test.go
Occasionally the bad SP take over the valid SP and prevent  the node from creating the SP. The test fails.
Giving the test more time and enhance the odds of passing.
=> TestSPWithCounterReset make it more tolerant 

test/e2e-go/features/stateproofs/stateproofs_test.go
Divide the test into two tests, one without load, and one with load. 
Skip the SP in block check for the latter.
=> stateproofs: reorganize the full pool tests

daemon/algod/api/server/v2/errors.go, daemon/algod/api/server/v2/handlers.go
While collecting sample data for SDK tests I noticed this error message which could be improved. There was an extra period because I copy/pasted from goal... so the transaction ID is not valid but was specified:
```
~$ curl "localhost:4001/v2/blocks/1502/transactions/PBFTEOO4PFV2RR6KFD2JD5VSUTNVPB2F2GG5F63N4RD52PX47FOQ./proof?pretty" -H "X-Algo-API-Token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
{
"message": "no transaction ID was specified"
}
```
=> Better error message for when an invalid txid is specified.

test/e2e-go/features/transactions/sendReceive_test.go
The TestAccountsCanSendMoney test is still flaky and this pr aims to fix it. Another problem observed was that the test aims to check the balances of both accounts are correct on both ping and pong nodes by calling the `fixture.GetBalanceAndRound` function. However this function always calls the ping node and never the pong node. Thus we have logic which first ensures that the txns are confirmed on the pong node, then incorrectly checks the balances on the ping node instead of the pong node. The ping node may be out of sync and return the wrong balances.
This pr corrects this by checking the balance on the pong node instead of the ping node.
=> test: fix TestAccountsCanSendMoney #2

cmd/goal/account.go, cmd/goal/application.go, cmd/goal/asset.go, cmd/goal/clerk.go, cmd/goal/interact.go, libgoal/libgoal.go, test/e2e-go/cli/goal/expect/goalExpectCommon.exp, test/e2e-go/features/transactions/application_test.go, test/e2e-go/features/transactions/asset_test.go, test/e2e-go/features/transactions/onlineStatusChange_test.go, test/e2e-go/features/transactions/sendReceive_test.go
* The test validates first/last valid against possible expired value of lastRound.
Make ComputeValidityRounds returning lastValid to check validity range against it.
* Fix some linter warnings
* Modify all usages of ComputeValidityRounds
This is a test
=> tests: fix TestAssetValidRounds

cmd/loadgenerator/main.go
I am sad that `go vet` didn't have a warning about this shadowing of a variable name.
Manual test tool was tested manually.
=> test: un-shadow loadgen privateKeys var

test/e2e-go/features/transactions/sendReceive_test.go
The TestAccountsCanSendMoney test does not throw an error when not all txns are confirmed within the allotted time. This pr fixes that so we can have better understanding of why the test fails.
=> test: fix TestAccountsCanSendMoney #3

data/txHandler.go
Make a channel length `txBacklogSize` responsive to up coming changes in block size. Hold approximately one block of txns in channel. Manual testing has shown that `txBacklogSize` needs to be increased from its original size of 1000.
Manually experimented and verified in cluster tests.
=> network: make txBacklogSize responsive to block size

ledger/internal/eval_blackbox_test.go
By https://github.com/algorand/go-algorand/issues/4349, we noticed a datarace in `testMaxInnerTxnSingleAppCall`. This PR waits the ledger to commit every new blocks in `blockQueue` to be committed in function `endBlock`.
=> test: wait until new block is committed to `BlockQueue`

catchup/catchpointService.go, catchup/service_test.go
A fast-catchuped node should be able to be part of state proofs creation. In order to do that, it must download all necessary blocks. Currently, if the state proof chain is lagging the node download `lowestStateProofRound - stateproofInterval` rounds back on fast catchup. This is not accurate since the balances comes from `lowestStateProofRound - stateproofInterval - StateProofVotersLookback`
Manual fast catchup test.
=> Bugfix: download more block to recover old state proofs

test/scripts/e2e_basic_start_stop.sh
e2e_basic_start_stop fails time to time as we want to know why
=> tests: add debug output to e2e_basic_start_stop

catchup/catchpointService.go, test/e2e-go/cli/goal/expect/catchpointCatchupWebProxy/webproxy.go, test/e2e-go/features/catchup/catchpointCatchup_test.go, test/framework/fixtures/webProxyFixture.go
* After the protocol upgrade nodes required to have MaxTxnLife + DeeperBlockHeaderHistory
blocks that violated the test's expectations.
* Fixed a rare case when a block exists in a local ledger but peer's stat is still updated
even if no communications were made.
Run the test multiple times
=> tests: fix TestBasicCatchpointCatchup

.circleci/config.yml
Disabling Mac builds from our default triggered runs on Circle.
Run build from within the PR - Circle _should_ respect its config file on this branch.
=> Build: Remove mac_amd64 from our default triggered builds.

data/transactions/logic/README.md, data/transactions/logic/TEAL_opcodes.md, data/transactions/logic/assembler_test.go, data/transactions/logic/doc.go, data/transactions/logic/evalCrypto_test.go, data/transactions/logic/evalStateful_test.go, data/transactions/logic/eval_test.go, data/transactions/logic/langspec.json
We were missing some partitiontest calls. I don't know why the checking didn't fail. It DID see the problem
It seems to me that a) The linter was supposed to complain. and b) the test checker should have failed.
=> CI: Four missing partiontest calls. And minor doc update.

test/framework/fixtures/libgoalFixture.go, test/framework/fixtures/restClientFixture.go
When a test running the libgoal fixture, flakes, it is difficult for us to diagnose the problem. Print out node.log to the test console so we can analyze the problem.
Purposely failed test to check whether logs were dumped.
=> tests: Add logging to libgoal fixture on failure

test/e2e-go/features/transactions/asset_test.go, test/framework/fixtures/restClientFixture.go
* Ensure manager account is funded before running any operations with it
* Shave 2 minutes from TestAssetCreateWaitBalLookbackDelete
by introducing faster rounds on a custom proto that is already in place
=> tests: stabilize TestAssetCreateWaitRestartDelete

test/e2e-go/features/stateproofs/stateproofs_test.go, test/testdata/nettemplates/RichAccountStateProofSmall.json, test/testdata/nettemplates/StateProofSmall.json
Rarely, SP e2e tests may fail on ARM. This is because the tests spins around 7 nodes, which may overwhelm the ARM. 
Making some of the tests run on smaller network, others not run on ARM.
=> stateproofs: Make SP e2e tests easier for arm.

test/scripts/e2e_client_runner.py
CI false negative seemed to be, actually, a false false negative, caused when the `gotestsum` command was unable to parse the json file created by `e2e_client_runner` That is likely because it was being written to by concurrent threads.
=> Test: Acquire locks when logging start and stop.

node/node_test.go
Remove the TestAsyncRecord test, as per discussion with @winder. The goal of this test was supposed to ensure that recording participation keys properly updates the db. The test does not test functionality that we wish to test and is also flaking on circle ci. Additionally, all the behavior we wish to verify is tested within `test/scripts/e2e_subs/goal-partkey-commands.sh`.
this is a test
=> test: deprecate TestAsyncRecord

config/consensus.go
Performance testing and analysis indicated memory consumption concerns with the current value of `BytesPerBoxReference` of 8096. The proposed 1024 value, along with the reduction of the `MaxAcctLookback` parameter from 8 to 4, brings the theoretical memory usage well into acceptable territory.
Existing Unit Tests.
=> Reduce BytesPerBoxReference

.circleci/config.yml, .github/workflows/codegen_verification.yml
This moves the codegen_verification task to Github Actions, as it is similar to the other types of static checks and linting jobs already in GHA.
=> CI: use GHA for codegen_verification

test/e2e-go/cli/algod/expect/algod_expect_test.go
The PR fixes a partitioning configuration error in `test/e2e-go/cli/algod/expect/algod_expect_test.go`.  The parent test runner should _not_ partition itself because its subtests perform partitioning.
* In a forthcoming PR, I'm tweaking CircleCI parallelism for E2E expect tests.  During experimentation, I realized the configuration is broken when the build failed:  https://app.circleci.com/pipelines/github/algorand/go-algorand/8782/workflows/3136b236-4a2a-4f63-a5df-f014b57880c7/jobs/158744?invite=true#step-103-22.  Reproduced below for convenience:
```
============= UNINTENTIONALLY SKIPPED ============
1 tests were skipped unintentionally
github.com/algorand/go-algorand/test/e2e-go/cli/algod/expect TestAlgodWithExpect/algodTelemetryLocationTest.exp -- skipped unintentionally. (due to …
```
=> CI:  Ensure algod_expect_test.go tests run by avoiding double partitioning

.circleci/config.yml, scripts/buildtools/check_tests.py
Extends `scripts/buildtools/check_tests.py` to customize tests to ignore via `--ignored-tests`.  The motivation is to acquiesce `check_tests.py` warnings about E2E expect tests run multiple times.
In another branch, I saw warnings in https://app.circleci.com/pipelines/github/algorand/go-algorand/8787/workflows/a566ab26-42ad-48de-940d-08d504ce1c15/jobs/158801?invite=true#step-103-7.  Reproduced below for convenience:
```
=========== RAN MULTIPLE TIMES ===================
The above 4 tests ran multiple times:
github.com/algorand/go-algorand/test/e2e-go/cli/algod/expect TestAlgodWithExpect -- ran 10 times. (Can probably be fixed by adding "partitiontest.PartitionTest()")
github.com/algorand/go-algorand/test/e2e-go/cli/algoh/expect TestAlgohWithExpect -- ran 10 times. (Can probably be fixed …
```
=> CI:  Expose configuration to ignore parent E2E expect test runner invocations

ledger/acctupdates.go
DB lookup might fail and acctupdates' lookup method return not original error but overwritten by another one.
This makes debugging a bit harder.
Existing tests
=> ledger: do not shadow db error in account lookup

test/e2e-go/cli/goal/expect/goalExpectCommon.exp
Test random failures debugging: retrieve logs after stopping the network to ensure all messages were flushed.
=> tests: stop network before reading logs

cmd/algokey/multisig.go, cmd/algokey/sign.go, cmd/goal/clerk.go, cmd/goal/multisig.go, cmd/tealdbg/local.go, data/txHandler.go, data/txHandler_test.go, protocol/codec.go, protocol/codec_test.go, protocol/codec_tester.go, test/e2e-go/cli/goal/expect/goalFormattingTest.exp, tools/debug/algodump/main.go
Use msgp marshaller instead of reflect in TxHandler
```
BenchmarkTxHandlerDecoder-8       	      68	  17116004 ns/op	 3335105 B/op	   51105 allocs/op
BenchmarkTxHandlerDecoderMsgp-8   	     122	  10213123 ns/op	 1189860 B/op	     614 allocs/op
```
```
BenchmarkTxHandlerProcessDecoded-8   	   62826	     19184 ns/op	    8956 B/op	      57 allocs/op
vs old
BenchmarkTxHandlerProcessDecoded-8   	   47414	     21560 ns/op	    8957 B/op	      57 allocs/op
```
TODO: write tests
=> codec: new TxHandler byte decoder

.circleci/config.yml
Proposes to speed up CircleCI builds by consolidating `build` workflow steps into downstream workflows.
By _only_ changing the CI architecture without modifying resource class + parallelism, we see the following change:
<google-sheets-html-origin>
  | Before | After | Change %
-- | -- | -- | --
Duration (min) | 35 | 27.4 | -22%
$ annually | $17,971 | $10,998 | -39%
Feels like a win-win.  The change saves money + saves time.   
Details:
* Result notes:
* The sample size here is small (< 5), so it's prudent to assume _some_ variation.
* The _$ annually_ cost assumes a flat credit rate ($ per credit = $0.0006) and uses a 90 day average CI invocation rate.  
* There's a spread sheet with more detail for those interested:  https://docs.google.com/spreadsheets/d/13JM3vqOWFpzWrtI2hT02OpvojP2tdYm8 …
=> CI:  Speed up CircleCI by folding build workflow downstream

.github/workflows/reviewdog.yml, .golangci.yml, scripts/buildtools/versions, scripts/travis/codegen_verification.sh
Following on #4418 and #4241 this upgrades the version of golangci-lint to match the lint-cleanliness achieved in #4241. (Older versions of golangci-lint were producing false positives)
All tests should pass.
=> lint: Update linter version

ledger/voters_test.go
The unit tests for the voterTracker didn't correctly calculate the account's total stake. This lead to an error message on logs.
=> Testing: Fix voterTracker tests

ledger/acctupdates_test.go, ledger/archival_test.go, ledger/ledger_test.go
Forked ledgers have not preserved protocol so that we logged errors from voters tracker.
Set logging level=info in tests that produce to much debug output while adding thousands of blocks.
Fixed onlineTotals call in checkUpdates for non-sense input values
=> tests: fix logged panics in reproducible labels test

.golangci.yml, CONTRIBUTING.md, Makefile, scripts/buildtools/install_buildtools.sh, scripts/check_deps.sh, scripts/travis/codegen_verification.sh
golangci-lint subsumes both of these tools
=> Test: Get rid of references and uses of `go lint` and `go vet`

rpcs/txSyncer_test.go
Putting random data into a bloom filter would sometimes fail the test. Set the random seed so that we have deterministic psuedo-random data.
Ran this for a while with no errors. Used to fail within a few dozen tries.
`go test -c -race -o rpcs.test && while logwrapq ./rpcs.test -test.count 50 -test.timeout 5m -test.v -test.run TestSync; do date; done`
=> testing: deterministic rand seed for stable unit test

ledger/testing/randomAccounts.go
TestAcctUpdatesCachesInitialization generates online/offline deltas and sets VoteLastValid=1000.
Since the tests goes beyond 1000 rounds, most of the accounts became expired for stateproof and TopOnlineAccounts renders a warning.
This is a test
=> tests: fix top online warning in TestAcctUpdatesCachesInitialization

cmd/loadgenerator/main.go
Fix bug in loadgenerator when handling AccountMnemonicList.
=> loadgenerator: correctly handle AccountMnemonicList

ledger/evalbench_test.go
=> ledger: fix typo in evalbench_test.go

network/wsNetwork_test.go
sleeping 1ms can still starve other processes sometimes.
sleep 10ms to let the test run.
test used to fail about 1/200; haven't seen a failure in several thousand now.
This is a test. It should be less flakey now.
=> test: TestSlowPeerDisconnect less flakey

ledger/internal/apptxn_test.go, ledger/internal/double_test.go, ledger/ledger.go, ledger/tracker.go
This fixes the purestake issue on betanet and includes an easy way to test for similar bugs.
=> Ledger: Initialize the accountUpdatesLedgerEvaluator properly

.circleci/config.yml
Attempts to fix a regression in the nightly build introduced in https://github.com/algorand/go-algorand/pull/4426/.
Notes:
* Example failure:  https://app.circleci.com/pipelines/github/algorand/go-algorand/8989/workflows/bca22a16-2fa2-4cda-b487-0b1fad6f42f4/jobs/161778
* Since #4426 no longer persists build artifacts to the workspace, the downstream `upload_binaries` workflow fails to find artifacts to upload.
* The PR re-introduces a version of `build_nightly` workflow that builds + persists artifacts to the workspace.  The approach mirrors the prior behavior (https://github.com/algorand/go-algorand/blob/0b9580b3cca20753f89956bd295910209163a025/.circleci/config.yml#L263-L269).  The PR deliberately avoids branching in favor of a unique set of steps under the assumption that it's easier to …
=> CI:  Re-introduce build_nightly workflow to persist artifacts for upload_binaries

config/consensus.go, ledger/acctonline.go, ledger/acctonline_test.go, ledger/internal/eval_blackbox_test.go, ledger/ledgercore/votersForRound.go, protocol/consensus.go, test/e2e-go/features/stateproofs/stateproofs_test.go, test/e2e-go/upgrades/send_receive_upgrade_test.go, test/testdata/nettemplates/TwoNodes50EachV32Upgrade.json
Update the total weight to subtract rewards from accounts who have expired or have keys that do not match the weight commitment round.
New tests needed
=> state proofs: update state proof totals calculation

ledger/accountdb.go, ledger/ledger_test.go
* Catchpoints only have minimal data, and online accounts/txtail derive it
when applying catchpoint
* Deriving code is reused from migration the migration only assumed
MaxTxnLife worth of block history
* In fact, it need to restore MaxTxnLife + DeeperBlockHeaderHistory
when used as part of catchpoint apply code path
Added new test: fails before the fix, works with the fix.
=> ledger: fix txtail restoring from catchpoints

.circleci/config.yml
making that variable be in all nightly steps.
Doc on how to use that var (by Barbara):
https://algorand.atlassian.net/wiki/spaces/DEVOPS/pages/2459893761/How+to+Run+Nightly+Tests+on+go-algorand
tested with custom branch:
https://app.circleci.com/pipelines/github/algorand/go-algorand/9011/workflows/72c36c87-93ab-466b-b932-6f9b7c886b9f
=> build: adding valid_nightly_branch var to upload_binaries step

catchup/catchpointService.go
* replaying transactions after catchpoint requires 1001 blocks
from the very first replayed block
Tested manually. e2e test planned as a separate PR
=> ledger: extend catchpoint blocks lookback

ledger/catchpointwriter_test.go
Fixed the TestCatchpointReadDatabaseOverflowAccounts test. It was failing because multiple resources were being created with the same id, since the test first creates resources with id's as a random slice between 0 and 512, and then counting up from 100. This pr changes the latter set of resources to count up from 1000 to avoid the conflict.
This is a test
=> ledger: fix catchpoint test

test/scripts/e2e.sh
This is for resolving [#1174](https://github.com/algorand/indexer/issues/1174).  Another copy of rel/nightly e2e artifact is uploaded to file path algorand-testdata/indexer/e2e4/\<commit_hash\>/.  This way, indexer's e2e test can use data generated from a specific version of go-algorand.  
check that data is created in s3 with correct file path.
=> e2e tests: tag e2e test data with commit hash 

test/e2e-go/features/participation/participationRewards_test.go, test/framework/fixtures/restClientFixture.go
Many tests that use the restClientFixture flake for the following reason: The test spins up 2 nodes, Node A and Node B. Node A observes it is currently round r, but node B is still on round r-1. Node A then sends a tx with validity range (r, r+1000). Node B then discards the tx since r-1 is outside of the tx’s validity range. Then the test fails because the tx's are never processed if the proposer of each round happens to be Node B.
This test fixes the issue by changing the validity window.
=> test: Fix restClientFixture test flaking

data/pools/transactionPool.go, data/pools/transactionPool_test.go
Set the StateProofNextRound to metric stats when the block payset is empty.
Added a check for this in the logging test.
=> stateproof: always set StateProofNextRound in metric

.golangci-warnings.yml, .golangci.yml, ledger/internal/apptxn_test.go, ledger/internal/eval_blackbox_test.go, scripts/buildtools/versions, scripts/travis/codegen_verification.sh
* fixing golangci-lint command
* fixing github action failing if it fails to run
* adding linters for tests per @cce 
* @cce fixing some linter errors from before
* removing golangci-lint and gofmt from codegen_verification.sh since it runs in reviewdog
=> CICD: Fixing golangci-lint and github action

data/transactions/logic/assembler.go, data/transactions/logic/assembler_test.go, data/transactions/logic/eval_test.go
This PR fixes #4034, by forcing the use of "push*" when mixing manual
constant blocks with the int/byte/addr/method pseudo-ops. (And a
related disassembly bug).
However, to avoid this "deoptimization" when manual blocks are used to
add program metadata, deadcode constant blocks are ignored for this
check.
Tests for the problems in #4034 and additional tests for the deadcode were added.
=> AVM: Handle Teal programs with manual constant blocks better

daemon/algod/api/server/v2/handlers.go, daemon/algod/api/server/v2/test/handlers_test.go
Return a 404 instead of 500 when /v2/blocks/{round} fails due to a missing block.
Update handler test
=> enhancement: Return a 404 when a block is not found.

.circleci/config.yml, .github/workflows/build.yml, .github/workflows/codegen_verification.yml, .github/workflows/reviewdog.yml
This updates the CircleCI and Github Actions caches to make it possible to find cache hits more often, by tweaking the key scheme for Go mod source and build caches. 
For Github Actions, adding CI for merges to master, will ensure we are doing the same testing as on PRs, and also provide cached data on master that ensures the GHA cache will serve a hit from the master build for the first commit on a new branch PR.
>A workflow can access and restore a cache created in the current branch, the base branch (including base branches of forked repositories), or the default branch (usually main). For example, a cache created on the default branch would be accessible from any pull request. 
https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-fo …
=> CI: optimize caches used by CircleCI and GHA

test/e2e-go/features/stateproofs/stateproofs_test.go
TestAttestorsChange tries to compare account's balance with the state proof's total online stake.
The test sample the balance on a stateproof round (where the onlineStake field appears), However the balances should be sampled StateProofVotersLookback rounds before.
=> Testing: fix TestAttestorsChange

cmd/updater/update.sh
when providing the `-verify` flag to `update.sh`, the public GPG key is downloaded into the directory in which the script is called (PWD) and is never cleaned up. this makes it so that when the key is downloaded, it is placed in the temporary directory that gets cleaned up. otherwise, after execution, it's just hanging around. 
I've been testing this with the following script
<details>
<summary>setup-algo-node.sh</summary>
```bash
#!/usr/bin/env bash
set -e
declare UPDATER_SCRIPT_URL="${UPDATER_SCRIPT_URL:-"https://raw.githubusercontent.com/algorand/go-algorand/master/cmd/updater/update.sh"}"
declare NETWORK="${NETWORK:-"mainnet"}"
declare CHANNEL="${CHANNEL:-"stable"}"
while getopts "c:n:u:" opt; do
case "$opt" in
c)
CHANNEL="$OPTARG"
;;
n)
NETWORK="$OPTARG"
;;
u) …
```
=> updater: cleanup key.pub

network/wsPeer.go
This ensures the tag list is passed to the filtered TagCounters.
=> metrics: create filtered TagCounters from init

network/wsPeer_test.go
The test fails before #4524 and passes after.
=> metrics: network tag filtering test

network/wsPeer_test.go, util/metrics/tagcounter.go
There was a race condition between `TagCounter.Add` and `TagCounter.WriteMetric` when accessing the counter.
The issue discovered by a new test, no new tests needed.
=> tests: fix network metrics race condition in tests

test/scripts/e2e.sh
Bumps py-algorand-sdk E2E dependency to the latest release:  https://github.com/algorand/py-algorand-sdk/releases/tag/v1.17.0.
The request arose in https://github.com/algorand/go-algorand/pull/4149#discussion_r966249783.  To help isolate debugging should a failure arise, I prefer to make the change against `master` and merge back into the feature branch.
=> Tests:  Bump py-algorand-sdk to v1.17.0

daemon/algod/api/server/v2/handlers.go, daemon/algod/api/server/v2/handlers_test.go
Attempts to address https://github.com/algorand/go-algorand/pull/4149#discussion_r968624423 by linearizing invocation of `ledger.LookupKeysByPrefix`.
=> Refactor to linearize ledger lookup in GetApplicationBoxes

data/bookkeeping/txn_merkle_test.go, data/txHandler_test.go
* update BenchmarkTxHandlerProcessDecoded to use bigger blocks and also measure verify.TxnGroup 
* update BenchmarkTxnRoots to also call paysetCommitSHA256
No impact to code besides benchmark test changes.
=> performance: Update two transaction verification benchmarks

shared/pingpong/accounts.go
nil-hash-write bug fix
Found in testing. Later manual testing is better.
=> tools: pingpong nil fix

data/txHandler_test.go
=> tests: fix method name after typo correction

data/account/participationRegistry.go, data/account/participationRegistry_test.go, data/accountManager.go, data/accountManager_test.go
=> Algod: fix nil deref while fetching stateproof secrets

cmd/algod/main.go, config/config_test.go, config/migrate.go, logging/telemetryspec/event.go
For nodes with telemetry enabled, this adds some additional information at startup time about performance-sensitive configuration defaults that have been overridden.
Added unit test.
=> telemetry: add StartupEventDetails.Overrides

ledger/acctupdates.go
Branched off of #4296. This PR reduces the LRU resource cache + buffer channel size to 10k from 100k. This change was informed by an investigation into the current value that determined it was higher than necessary for mainnet, where the number of live apps is ~60k, as per metrica. The introduction of box storage also requires extra memory usage so freeing up resources is an added bonus. Note: that the maximum size of the cache may be slightly larger depending on the quantity of resources in the in-memory state deltas. 
Performance tests are currently being executed to identify any performance degradation. The PR will be updated when the results are available.
=> config: Resource Cache Size Reduction

catchup/universalFetcher.go
When we grew the block size we did not adjust `fetcherMaxBlockBytes` to match, and it looks like we are running into this given errors like: `response too large: 5265295 > 5242880`.
=> catchup: increase HTTPFetcher fetcherMaxBlockBytes for larger block size

util/db/dbutil_test.go
Some of the `dbutil` tests run for a long time and simulate some specific edge cases on the databases infrastructure.  it is safe to run those tests only on nightly jobs.
=> Tests: skip db concurrent Read/Write tests if test.short is set

ledger/catchpointwriter_test.go
Fixed the TestCatchpointReadDatabaseOverflowSingleAccount test. It was failing due to the same reason as the TestCatchpointReadDatabaseOverflowAccounts test. The fix is exactly the same as https://github.com/algorand/go-algorand/pull/4480.
=> ledger: fix TestCatchpointReadDatabaseOverflowSingleAccount

test/testdata/deployednettemplates/hosttemplates/hosttemplates.json, test/testdata/deployednettemplates/recipes/betanet-model-2/Makefile, test/testdata/deployednettemplates/recipes/betanet-model-2/gen_topology.py, test/testdata/deployednettemplates/recipes/betanet-model-2/genesis.json, test/testdata/deployednettemplates/recipes/betanet-model-2/net.json, test/testdata/deployednettemplates/recipes/betanet-model-2/node.json, test/testdata/deployednettemplates/recipes/betanet-model-2/nonPartNode.json, test/testdata/deployednettemplates/recipes/betanet-model-2/recipe.json, test/testdata/deployednettemplates/recipes/betanet-model-2/relay.json, test/testdata/deployednettemplates/recipes/betanet-model-2/topology.json
Another Betanet recipe with participating nodes distributed to individual hosts.
Use algonet to deploy a network.
=> Tests: betanet-2 extended recipe

ledger/accountdb_test.go
Using `b.N` to rerun the benchmark test, such that the benchmark number looks more reasonable and consistent.
The benchmark result is more reasonable now:
```
go test -benchmem -run=^$ -bench ^BenchmarkLookupKeyByPrefix$ github.com/algorand/go-algorand/ledger
goos: darwin
goarch: arm64
BenchmarkLookupKeyByPrefix/lookupKVByPrefix-DBsize4-10         	  295464	      4067 ns/op	     992 B/op	      42 allocs/op
BenchmarkLookupKeyByPrefix/lookupKVByPrefix-DBsize16-10        	  245655	      4754 ns/op	     992 B/op	      42 allocs/op
BenchmarkLookupKeyByPrefix/lookupKVByPrefix-DBsize64-10        	  158940	      7450 ns/op	     992 B/op	      42 allocs/op
BenchmarkLookupKeyByPrefix/lookupKVByPrefix-DBsize256-10       	   66130	     18040 ns/op	     992 …
```
=> Better Benchmarking DB query in avm-box

ledger/catchpointwriter_test.go
Reworks `TestCatchpointAfterTxns` to assert on account balance.  Intent is to marginally increase correctness confidence about state written to a catchpoint.
`go test ./ledger -run "TestCatchpointAfterTxns"`
=> Rework TestCatchpointAfterTxns to assert balance

ledger/accountdb_test.go
Adds test partitioning for recently added tests to distribute load during CI runs.  Also adds `t.Parallel()` under the assumption that these tests can safely run in parallel.
`go test ./ledger`
=> Partition tests to spread load in CI

ledger/accountdb.go, ledger/acctonline_test.go
There was a copy-paste error in account in `persistedOnlineAccountData.before` used by online accounts LRU cache. `persistedOnlineAccountData.updRound` must be used for ordering since online accounts entries are not squashed together in a commit range but every entry generates a new row in onlineaccounts table. Having that, the `persistedOnlineAccountData.round` field set to the trackerDB round and used in accounts LRU cache ordering prevent entries of the same address being added into the cache. As a result this is a cache miss and additional lookups.
Added a unit test
=> ledger: fix accounts cache ordering

tools/debug/dumpblocks/main.go
This adds a small program that helps you write out a range or random set of blocks from a provided SQLite blockdb to a directory.
=> testing: tool to dump blocks to directory

catchup/universalFetcher.go, crypto/batchverifier.go, crypto/batchverifier_test.go, crypto/multisig.go, crypto/multisig_test.go, data/transactions/verify/txn.go, data/transactions/verify/txn_test.go, test/e2e-go/kmd/e2e_kmd_wallet_multisig_test.go, test/e2e-go/upgrades/rekey_support_test.go
Rename and make local functions which are internal to the package. 
The purpose is to enhance the code readability. 
Also removing a function which is not used.
=> BatchVerifier: Rename and unexport local functions in verify/txn

agreement/proposalStore.go, logging/telemetryspec/event.go, network/wsNetwork.go, network/wsPeer.go, util/metrics/metrics.go
Message filtering is used to reduce the number of duplicate large messages (>5000 bytes) sent between peers. After a large message is received, the node sends a filter message (protocol tag `MsgDigestSkipTag`) containing the message's hash to all its peers, telling them not to send them any messages with this hash. However this does not prevent a node from receiving the same large message concurrently from several peers, since it must fully receive the first large message before broadcasting the filter message.
This counts the number of duplicate filter messages received by a peer. Nodes do not track their outgoing filter messages, but receiving nodes must track the hashes, and so this wires up a counter to `messageFilter.CheckDigest` which "checks if the given digest already in the …
=> telemetry: Count and report the number of duplicate proposals and MsgDigestSkipTag messages received

test/testdata/deployednettemplates/recipes/mmnet/genesis.json
- this changes the `LastParKeyRound` of the `mmnet` recipe to 50,000 instead of 3,000,000.  this should speed up network bootstrapping.
=> CICD: reduce mmnet LastPartKeyRound to 50k

data/transactions/verify/txn_test.go
Add several unit tests for verifying types of signatures on transactions. including: regular signature, multisignature and logicsignature
=> testing: extend transactions signature verification testing

ledger/metrics.go, network/wsNetwork.go, node/node.go, util/metrics/gauge.go, util/metrics/gauge_test.go
Gauges have optional, currently unused, arguments allowing user to set labels on multiple values per single gauge struct. This has potential to leak memory if unbound datasets were used as labels.
Closes #3040 
Current tests pass as well as the new modified one. The format of a line of output from `WriteMetric` is the same except for the labels added by the test:
old:
`metric_test_name1{pid="5824",host="algo-suvak-mbp.lan",host_name="host_one",session_id="AFX-229",pid="123",data_host="host0"}:150`
new
`gauge_0{host_name="host_one",session_id="AFX-229",pid="5229",host="algo-suvak-mbp.lan"}:606`
=> metrics: Remove labels from gauge metrics

agreement/player.go, agreement/service.go, data/pools/transactionPool_test.go, ledger/ledger_test.go
Add a unit testing that speculative assembly does not cause race conditions by running speculative assembly in parallel with adding new txns to the pool.
Also fixed some typos.
This is a test
=> spec asm: Add race unit test

go.mod, go.sum, network/msgCompressor.go, network/msgCompressor_test.go, network/wsNetwork.go, network/wsNetwork_test.go, network/wsPeer.go, network/wsPeer_test.go
Inproduce proposal payload compression in protocol version 2.2.
Acceptance:
1. Unit tests incl 2.1 and 2.2 peers mix
2. All e2e tests pass
3. Manual test master and feature nodes on TwoNodes50Each template
If all peers support compressed proposals, do not allocate memory for non-compressed data batch. Possibly in another PR.
=> network: proposal payload compression

network/msgCompressor.go, network/wsNetwork.go
* Better comment for max compressed proposal message
* Use `AddUint64` instead of `Add` for integer metric
Rely on existing tests
=> network: compression followup fixes

daemon/algod/api/server/v2/handlers_test.go
Refactors `TestApplicationBoxesMaxKeys` based on feedback provided in https://github.com/algorand/go-algorand/pull/4149#discussion_r996174047.
=> Refactor TestApplicationBoxesMaxKeys to reduce test length

cmd/pingpong/runCmd.go
In #4628 I added a configuration check on the list of account mnemonics without conditionalizing it on whether you were using that feature. This fixes that check.
=> pingpong: fix config check for GeneratedAccountsMnemonics

ledger/accountdb.go, ledger/catchpointwriter_test.go, ledger/catchupaccessor.go, ledger/catchupaccessor_test.go
When an account is split over multiple catchpoint file chunks, we attempt to add its account hash to the catchpoint merkle trie twice, yielding a database error when processing the catchpoint. This is an alternate method to #4666 for fixing this issue, that stops the duplicate merkle trie hash issue at the source, rather than later at insert time.
New tests added to exercise accounts split over multiple catchpoint records/chunks.
=> catchpoints: don't make duplicate account hashes in prepareNormalizedBalances

crypto/batchverifier.go, crypto/batchverifier_test.go
In batchVerificationImpl, the signatures, messages and publicKeys are not copied. The memory from the Go slice is used by the C code, by creating C pointers to these memory location. However, Go is not aware of this usage, and can recover the memory used by these, since no Go variable is referencing them. This may happen when the C code is evaluating them, resulting is accessing corrupted memory. 
This fix tells Go to keep alive these references.
=> batchverifier: preserve the memory until the end

config/localTemplate.go, config/local_defaults.go, test/testdata/configs/config-v24.json
Turn off the 'cadaver' trace file by default. It was used extensively in debugging years ago but hasn't been used much recently, and it significantly decreases performance. It can be re-enabled for debug clusters.
Many test clusters have been run with this disabled.
=> algod: turn off cadaver trace file by default

ledger/accountdb.go, ledger/ledger.go, ledger/ledger_test.go, ledger/ledgercore/msgp_gen.go, ledger/ledgercore/stateproofverification.go, ledger/stateproofverificationtracker.go, ledger/stateproofverificationtracker_test.go, ledger/tracker.go, ledger/trackerdb.go, scripts/dump_genesis.sh
Created a tracker to track the data required for state proof verification, until such a time as the expected state proof is agreed upon. 
Includes unit tests and a sanity ledger test.
=> State Proof Recoverability: state proof verification tracking

daemon/algod/api/server/v2/handlers.go
=> API: bump max size of teal source and dryrun

data/txHandler.go, data/txHandler_test.go
Performance test for incoming transaction group handling/verifying.
Prepares transaction groups of random sizes, sends them to the handler, which verifies and returns the results.
The transaction group sizes are random. Introduces 10% invalid signatures and makes sure they are properly reported.
=> Perf test: Transaction group handle/verify

data/transactions/logic/eval_test.go
Addresses https://github.com/algorand/go-algorand/pull/4149#discussion_r997207560 by renaming `isFull` to a more intent-revealing name (`supportsAppEval`).
=> Rename isFull to supportsAppEval

data/transactions/logic/evalStateful_test.go
Attempts to address https://github.com/algorand/go-algorand/pull/4149#discussion_r997164706 by adding unit tests covering `app_global_put` and `app_local_put` error cases.
=> Add test coverage for app local/global put errors

data/account/participationRegistry.go, data/accountManager.go, data/accountManager_test.go, stateproof/abstractions.go, stateproof/builder.go, stateproof/signer.go, stateproof/stateproofMessageGenerator_test.go, stateproof/worker.go, stateproof/worker_test.go
Due to StateProof keys' lifetime, the signer might delete the key while not all signatures are present in the DB. 
This critical error might occur when the DB fails to record a signature and a new signature arrives from the same key.
=> Algod: state-proof key deletion safety

data/transactions/logic/parsing_test.go, test/e2e-go/restAPI/restClient_test.go
Addresses https://github.com/algorand/go-algorand/pull/4149#discussion_r997224776 by adding basic unit tests for `AppCallBytes` to confirm existing code paths are exercised.
=> Add sanity check tests for AppCallBytes

logging/telemetryspec/event.go, network/wsPeer.go, network/wsPeer_test.go
This fixes #4631 by aligning a 64-bit counter when used on 32-bit platforms. 
Updated TestAtomicVariablesAlignment.
=> network: align duplicateFilterCount to prevent panic on 32-bit platforms

daemon/algod/api/server/common/handlers.go, daemon/algod/api/swagger.go
Resolves #3698
Changes swagger endpoint to use algod.oas2.json content as output
=> Bug-fix: return v2 spec from swagger endpoint

ledger/internal/eval.go
TestTransactionGroup is used by the transaction message handler to see if a transaction is already in the pool. It makes a child cow, which allocates a fair amount of objects, only to look up the transaction ID later from an empty map (and afterwards looking up the ID in the parent's map). This skips those allocations in TestTransactionGroup.
Existing tests should pass, new tests could be written to assert that TestTransactionGroup does not modify the parent cow.
=> performance: don't create child cow in TestTransactionGroup

util/db/dbutil.go
Addresses https://github.com/algorand/go-algorand/pull/4149#discussion_r1009657663 by switching from stdout to stderr.
=> Util:  Print dbutil.go error in stderr

ledger/internal/eval.go, ledger/internal/prefetcher/prefetcher.go, ledger/internal/prefetcher/prefetcher_alignment_test.go, ledger/internal/prefetcher/prefetcher_test.go, test/e2e-go/features/transactions/accountv2_test.go
Enable prefetcher for asset and app transactions except the foreign fields.
1. Modified all prefetcher error tests to ensure all transaction groups returned by the prefetecher even in case errors.
2. Checked prefetcher_alignment_test that validates prefetcher's behavior againsy `apply` logic.
=> prefetcher: enable prefetcher for assets and apps

ledger/internal/eval.go, test/e2e-go/features/transactions/accountv2_test.go
#4149 changed test client API
#4352 used old API
##
This is a test
=> test: fix after boxes and prefetcher remerge

daemon/algod/api/swagger.go
=> Bug-Fix: Blank Import Needs Commenting for Indexer's Lint

config/consensus.go, data/transactions/logic/eval_test.go, data/transactions/logic/frames_test.go, data/transactions/logic/langspec.json, data/transactions/logic/opcodes.go, ledger/apply/application_test.go, ledger/boxtxn_test.go, ledger/testing/consensusRange.go, ledger/testing/consensusRange_test.go, protocol/consensus.go
Allows upgrade to v36, with boxes.
=> Consensus: v36 upgrade

cmd/dispenser/index.html.tpl, cmd/dispenser/server.go
- adds some input validation to dispenser, 
- by first sanitizing the string to encode HTML tags
- then a quick regular expression test to make sure it's at least something that resembles a wallet/address
- moves the template to a separate file and embeds it instead
- does some encoding on the server side to strip out any HTML tags
- updates onload to use `text()` instead of `html()`
- https://stackoverflow.com/a/12034334
- https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html#output-encoding
=> dispenser: add input validation

ledger/catchpointtracker.go, util/db/dbutil.go
Atomic() doesn't accept a context, but always passes context.Background() to the callback fn.
This PR adds AtomicContext() that does accept a context and passes it to its callback.
Replaces #4104
=> db: add AtomicContext
