algorand/go-algorand

cmd/catchpointdump/file.go
Catchpoint dump utility now supports both catchpoints packed as .tar files and catchpoints compressed as .tar.gz files, like those created by e2e tests.
=> Catchpoint Dump Utility: catchpointdump now supports tar.gz

cmd/goal/box.go, test/e2e-go/features/transactions/accountv2_test.go
This PR changes some existing tests that call the GetPendingTransactions endpoint to use the v2 model instead of the v1 model. Also changes the `goal box` command to account for client-side error string handling. 
Integration tests.
=> tests: Fix account tests for calling pending txn endpoint and box tests

cmd/goal/asset.go, test/scripts/e2e_subs/app-assets.sh
Add missing URL property, remove extra newlines
New e2e test.
=> goal: Add URL to goal asset info.

ledger/acctupdates.go, ledger/evalindexer.go, ledger/internal/eval.go, ledger/internal/eval_test.go, ledger/internal/prefetcher/prefetcher_alignment_test.go, ledger/ledger.go, ledger/lruaccts.go, ledger/lruresources.go, shared/pingpong/config.go, shared/pingpong/pingpong.go
```
Scenario:
1. Node accepts txns into tx pool
2. Node receives a proposal with the same txns and validates it
At 1, accounts are read and saved to LRU as pending
At 2, prefetcher loads accounts. Need to ensure LRU is hit.
```
The problem statement applies both to accounts and resources. 
Additionally, we taught the LRU to track accounts and resources that were not found in the DB. 
Thus avoiding repeated DB queries on objects that do not exist. 
- Pass existing tests. 
- Run load scenarios and compare performance.  
We run the scenario-1s with the default script and using a random destination (max200k) both on master and this branch.
The transactions per second (TPS) results are shown in figure 1.
> figure 1: TPS comparison between this branch and master.
=> performance: turn cache misses during assembly into cache hits during eval

.golangci.yml, data/transactions/logic/assembler_test.go, data/transactions/logic/evalAppTxn_test.go
This PR starts the process of improving unit test parallelization by enabling the [paralleltest linter](https://golangci-lint.run/usage/linters/#paralleltest) within golang ci. Fixing missing `t.Parallel`'s will require careful consideration and so, in this initial PR, packages currently failing the paralleltest linter are excluded.
Future PRs will incrementally add the `t.Parallel()` flag to tests in existing packages and disable that package's exclusion within `.golangci.yml`. As a result, tests added to that package in the future will fail the linter if the parallel signal is not present and a reason is not given as to why it is missing. For more information regarding the process of finding and fixing incorrect tests within a particular package, refer to the additional information …
=> Testing: Lint for unparallelized tests without explicit reason

daemon/algod/api/server/v2/handlers.go
Transaction pools might store failed transactions for quite a long time on its StatusCache.
When someone requests a pending transaction and it gets retrieved from the StatusCache,
there is no indication it actually failed. A user might have an impression the txn is fine but stuck.
In order to give a correct feedback, report any errors from the StatusCache via REST API.
=> daemon: pool error messages and old txn expiration

test/e2e-go/features/participation/participationExpiration_test.go, test/framework/fixtures/restClientFixture.go
This PR casts the `CurrentProtocol` to a string before asserting equality with another string in the tests, and changes the REST fixture tests to use the libgoal client to get parsed `PendingTransaction` information.
This should fix the nightly builds.
=> Tests: Fix types in assertions and change to using libgoal client when getting `PendingTransaction` information

cmd/tealdbg/localLedger.go, config/consensus.go, daemon/algod/api/server/v2/dryrun.go, ledger/acctupdates.go, ledger/apply/apply.go, ledger/apply/stateproof.go, ledger/evalindexer.go, ledger/internal/appcow_test.go, ledger/internal/cow.go, ledger/internal/cow_test.go, ledger/internal/eval.go, ledger/internal/eval_test.go, ledger/internal/prefetcher/prefetcher_alignment_test.go, ledger/ledger_test.go, ledger/ledgercore/msgp_gen.go, ledger/ledgercore/stateproofverification.go, ledger/stateproofverificationtracker.go, stateproof/verify/stateproof.go, stateproof/verify/stateproof_test.go, test/e2e-go/features/stateproofs/stateproofs_test.go
=> StateProofs: Use stateproof tracker

cmd/goal/asset.go, libgoal/libgoal.go, libgoal/transactions.go, test/scripts/e2e_subs/asset-misc.sh
This PR addresses some open comments made in https://github.com/algorand/go-algorand/pull/4684
Addresses three things:
* Change `EncodedBlockCert` decoding to use `Decode` instead of `DecodeReflect`
* Use `AccountAssetInformation` API in `goal asset info`. This changes behavior in `goal asset info` that looked like a bug regarding reserve addresses: the command now returns an error if a reserve asset is not opted into the asset, whereas previously, the command returned zero-ed values without failing. One test was changed to reflect this behavior.
* Refactor `libgoal` to use `AccountAssetInformation` instead of `AccountInformationV2`
CI tests.
=> goal: Change asset commands to use AccountAssetInformation

netdeploy/remote/deployedNetwork.go
- bumps the constant when calculating required storage for instances using `netgoal` to `20`
- for instance, with a single NPN and no relays, the return value changes from `20` to `30`
- this was highlighted when spinning up `mainnet` NPNs and running fast-catchup, the data directories are approaching, if not exceeding, 20GB
- load generator pipeline
=> netgoal: start with at least 20GB RootStorage

tools/network/resolver_test.go
`resolver_test.go` is failing because gmail's jabber SRV records seem not to exist anymore. I've updated the test to point to our own telemetry SRV records for devnet.
Unit test passes.
=> tests: Fix resolver test endpoint

data/basics/units.go, stateproof/builder.go, stateproof/db.go, stateproof/db_test.go, stateproof/signer.go, stateproof/worker.go, stateproof/worker_test.go
Maybe implement `handleSigs` for the signer?
=> StateProofs: Limit builders memory usage and reduce StateProofs signatures spam

.github/workflows/benchmarks.yml, .github/workflows/build.yml, .github/workflows/codegen_verification.yml, .github/workflows/reviewdog.yml
Accompanies https://github.com/algorand/go-algorand/pull/4789 to add Slack notifications for failed Github Action (GHA) workflows in `master`.  Like #4789, the rationale is to be aware of a failed build in our development branch as soon as possible.
Notes:
* In practice, I expect the workflows modified by the PR to rarely, if ever, fail in `master`.  
* There might be a way to streamline the notification definition through plugin usage.  For the PR's purpose, I copy-pasted the approach in .github/workflows/build.yml.  For a more thorough treatment, I'd prefer to create a ticket out-of-band to the PR.
=> CI:  Notify when GHA workflow fails on master

.circleci/config.yml
Suggests the following build notification failure policy modifications:  Notify when release + `master` branches fail.  
Rationale:
* Merges to `master` sometimes fail the build.  The failure is silent until the nightly build happens.
* Prior to the PR, ad-hoc full builds triggered by a user result in a failure notification.  The PR deliberately precludes custom branches from generating failure notifications.
* If we wish to retain notifications here, I propose adding a secondary channel out-of-band to the PR.
Notes:
* PR bumps `cricleci/slack` orb.  The associated commits and releases seem harmless:  https://github.com/CircleCI-Public/slack-orb/compare/v4.4.2...v4.10.1.  
* PR moves notification into post-steps (https://circleci.com/docs/configuration-reference/#pre-steps-and-post-steps). …
=> CI:  Notify when CircleCI build failures for master and rel branches only

test/e2e-go/features/transactions/accountv2_test.go, test/e2e-go/upgrades/application_support_test.go
This PR fixes the [build](https://app.circleci.com/pipelines/github/algorand/go-algorand/10565/workflows/68dd4267-ed96-46e6-b4c2-8df49a5dfaa9/jobs/182847) where there was a type mismatch in an assertion between the TxID bytes and string. One [existing test failed](https://app.circleci.com/pipelines/github/algorand/go-algorand/10565/workflows/68dd4267-ed96-46e6-b4c2-8df49a5dfaa9/jobs/182843) if the transaction was not committed in the next 2 rounds, so this PR adds a loop to wait if that is the case.
Re-run tests.
=> Tests: Fix txid-string comparison

network/topics.go
Includes the [check for large Topics length](https://github.com/algorand/go-algorand/commit/8151c81c1c9d49b0ccb289844203735320ad61f5) commit but does not update config/version.go (because this is a patch release, the VersionMinor does not need to be updated.)
=> mergeback: Relstable3.11.3 remerge

data/pools/transactionPool.go, ledger/ledgercore/error.go, logging/telemetryspec/metric.go
This splits out reasons for removing transactions from the pool during `AssembleBlock` with more granularity. The main reason is to provide visibility into the number of expired transactions across the network. 
=> metrics: split out /Transaction/AssembleBlock metrics

ledger/catchpointtracker.go
When building the catchpoint merkle trie from scratch, need to include the kv hashes too.
=> Catchpoints: Add the kv hashes into the trie

.github/workflows/benchmarks.yml, .github/workflows/build.yml, .github/workflows/codegen_verification.yml, .github/workflows/reviewdog.yml
Amends the trigger condition for Github Action (GHA) failure notification so that it _only_ reaches out when the branch being built matches `master` or a release branch.
From the docs in https://docs.github.com/en/actions/learn-github-actions/contexts:
Property name | Type | Description
-- | -- | --
github.base_ref | string | The base_ref or target branch of the pull request in a workflow run. This property is only available when the event that triggers a workflow run is either pull_request or pull_request_target.
github.ref_name | string | The short ref name of the branch or tag that triggered the workflow run. This value matches the branch or tag name shown on GitHub. For example, feature-branch-1.
Details:
* I'm not sure of the original intent in …
=> CI:  Fix GHA failure notification trigger condition

catchup/fetcher_test.go, rpcs/txService_test.go, util/metrics/counter_test.go, util/metrics/gauge_test.go
Running unit tests on macOS results in several firewall-related accept/deny prompts asking:  _Do you want the application X to accept incoming network connections?_  The PR prevents these pop-ups by applying https://apple.stackexchange.com/a/405967 to affected tests.
=> Tests:  Squelch macOS accept incoming network connections notifications

ledger/accountdb.go, ledger/catchupaccessor.go, ledger/ledger_test.go, ledger/trackerdb.go
Following on #4804 and #4812, this migration rebuilds the accounthashes table for betanet nodes.
Existing tests should pass, manual tests can confirm table is rebuilt.
=> accountdb: add migration 8 for resetting accounthashes on betanet

ledger/accountdb.go, ledger/accountdb_test.go, ledger/catchpointtracker.go, ledger/catchpointtracker_test.go, ledger/catchupaccessor.go, ledger/msgp_gen.go, ledger/store/catchpoint.go, ledger/store/interface.go, ledger/store/msgp_gen.go, ledger/trackerdb.go
Moving some of the catchpoint sql queries into the store package. 
**Previous parts of this refactor:**
- part 1 - #4776
=> ledger: move catchpoint sql code into storage package

ledger/catchupaccessor.go
While working on #4818, I landed in an intermediate state where it was helpful to add context to a `VerifyCatchpoint` error message.  I present the PR optionally - I don't feel strongly about retaining the minor change.
=> Catchpoint:  Add context to block mismatch error in VerifyCatchpoint

crypto/batchverifier.go, data/transactions/verify/txn.go, data/txHandler.go, util/metrics/metrics.go
Add more metrics to better understand traffic.
Existing tests
=> metrics: count large txn groups and msigs

network/wsNetwork.go, node/node_test.go
These node tests look like they've been disabled for a very long time--some of them since the initial commit.
I've fixed these tests with some caveats.  
* They take a long time to run so I've allowed us to opt into skipping them with `-short`
* I had to add phonebook's `ExtendPeerList` method to the `GossipNode`. The tests originally required this which wasn't an issue because the phonebook was located in the mode, but when it got moved out we lost the ability to update the phonebook peers manually.
Unit tests.
=> node: Fix disabled node tests

ledger/accountdb.go, ledger/catchpointwriter_test.go
Extends catchpoint tests to help catch regressions:
* Enriches `testNewLedgerFromCatchpoint` to confirm the writer and reader merkle tries match by comparing merkle trie stats.
* Adds a test case to `TestCatchpointAfterTxns` isolating a scenario that fails _prior to_ https://github.com/algorand/go-algorand/pull/4804.
Notes:
* If folks prefer to _not_ have an isolated test case, I can revert to the initial commit (https://github.com/algorand/go-algorand/commit/a7766298dd6a32a341cea4e1b6d630ce46d2fc0f).
* I ran out of time to convert existing test usage from mocks to `DoubleLedger`.  As is, the PR contains a kludgey if-statement (`Skip invariant check for tests using mocks`).   Even as is, I _think_ the PR presents a value add.
=> Tests: Extend TestCatchpointAfterTxns to catch catchpoint write corruption

ledger/catchpointwriter_test.go
Fixes broken merge between #4818 and #4835. 
Prior to the PR, `master` fails compilation with: `ledger/catchpointwriter_test.go:585:22: undefined: MakeMerkleCommitter`.
=> Catchpoint:  Fix broken merge between #4818 and #4835

cmd/updater/update.sh
- this updates `UPDATER_MIN_VERSION` to use a more recent version of the install package. `3.12.2` is important b/c it's the release where we recently renewed the signing keys.
=> updater: use more-recent installer package

cmd/goal/account.go, daemon/algod/api/client/restClient.go, libgoal/libgoal.go, test/e2e-go/features/participation/deletePartKeys_test.go
Resolves #3796
Adds delete part keys helper function
New integration test.
=> goal: account deletepartkey subcomand

test/scripts/e2e_subs/e2e-app-abi-method.sh, test/scripts/e2e_subs/tealprogs/app-abi-method-example.teal
This PR adds a new e2e test to cover calling an ABI method with reference types during an application creation.
Due to the bug pointed out in https://github.com/algorand/py-algorand-sdk/pull/406, we want increase coverage for that scenario in goal and the SDKs.
As part of this work, I also updated the PyTeal contract at https://gist.github.com/jasonpaulos/99e4f8a75f2fc2ec9b8073c064530359 to use the ABI router, since the prior contract did not perfectly follow ARC-4 routing rules. This caused the changes in `test/scripts/e2e_subs/tealprogs/app-abi-method-example.teal`.
New test added
=> Goal: Test ABI reference arguments during creation

ledger/accountdb.go, ledger/store/accountsV2.go
This PR creates a few more methods needed by the deltas.
**Previous parts of this refactor:**
- part 1 - #4776
- part 2 - #4813
- part 3 - #4830
- part 4 - #4835
- part 5 - #4836 
- part 6 - #4841 
- part 7 - #4846 
- part 8 - #4860 
**What remains to be moved out:**
=> refactor: accountdb.go into a store package (9 of N)

Dockerfile, docker/README.md, docker/files/build/install.sh, docker/files/build/kmd_config.json.example, docker/files/run/devmode_template.json, docker/files/run/future_template.json, docker/files/run/run.sh, docker/files/run/template.json
Port of the docker container here:  https://github.com/winder/docker
Some of the decisions made in this container might not make sense with the Dockerfile bundled with the source. The most glaring is that the container downloads source from S3 (if the CHANNEL build-arg is used), or from GitHub (if the URL/BRANCH/SHA build-args are used).
This container incorporates features and suggestions from many places, the biggest influences are:
* [sandbox](https://github.com/algorand/sandbox)
* [MakerX docker containers](https://github.com/MakerXStudio/algorand-sandbox-dev)
* [Hackathon docker containers](https://github.com/algorand/docker-scripts/)
* [Public docker container document](https://docs.google.com/document/d/1SHP5YD1OI9jRYl47WypiZp2Rzc3T8SBoPSzK1A3nz2g/edit)
* [Docker best …
=> docker: General purpose docker container.

config/config_test.go, config/localTemplate.go, config/local_defaults.go, data/txHandler_test.go, installer/config.json.example, test/testdata/configs/config-v26.json
Disabled the second level check after performance concerns and TX vs agreement messages processing competition.
Existing tests
=> txHandler: disable canonical hashmap by default

util/metrics/counter_test.go
TestGetValue registers a new metric that breaks other tests expectations on number of metrics. This might not be caught be CI because of sharding.
=> metrics: fix TestGetValue

data/txHandler.go, data/txHandler_test.go, ledger/internal/cow.go, ledger/internal/eval.go, ledger/internal/eval_test.go, ledger/ledgercore/error.go, ledger/txtail.go, ledger/txtail_test.go
Following on #4839 this adds metrics for different errors returned by checkAlreadyCommitted, which calls TestTransactionGroup. It also adds information to the LeaseInLedger and TransactionInLedger errors to split separate counters for whether a txn/lease was already seen on-chain, or in the pending block evaluator.
Extended TestTxHandlerRememberReportErrorsWithTxPool to use the new counters.
=> metrics: add counters for checkAlreadyCommitted, split "InLedger" counters by reason

ledger/catchpointtracker.go
Promotes log levels from warning to error for failed `balancesTrie` modifications.  Since we've previously noted concerns here, the rationale is:
* It'll be easier to isolate these these scenarios as errors.
* These scenarios unambiguously represent an _error_.  There's an invariant that's been broken.
If we accept the PR, I suspect there are other places we'll want a similar change.  The PR makes no attempt to scan beyond `accountsUpdateBalances`.
Existing tests pass.
=> Catchpoint:  Promote trie-related log warnings to error

data/transactions/verify/artifact_test.go, data/txntest/defi.go, ledger/artifact_test.go
Add a relatively large txn group benchmark with seen in the wild data
TODO: plug into txHandler testing infrastructure
=> testing: defi txn group benchmark

data/pools/transactionPool.go, data/transactions/error.go, data/transactions/transaction.go, data/txHandler.go, data/txHandler_test.go
This splits the "dead" txhandler counters between "early" and "dead" to track them separately.
Update existing counter tests.
=> metrics: split alive check counter between early/dead

daemon/algod/api/algod.oas2.json, daemon/algod/api/algod.oas3.yml, daemon/algod/api/server/v2/generated/data/data_routes.yml, daemon/algod/api/server/v2/generated/data/routes.go
We want the data endpoints to be available in the SDKs, so they are being marked "public". This means the regular API token will be able to use these endpoints when they are enabled. Node API providers, Relays and participation nodes would not have this enabled, so there should be no security concern.
N/A
=> API: Make the data endpoints public.

data/txHandler_test.go
Sometimes on CI block listener is not triggered or triggered before the waiter. Fixed by
1) adding more than one blocks
2) having a waiting timeout
=> tests: fix flaky TestTxHandlerRememberReportErrorsWithTxPool

ledger/catchpointtracker.go, ledger/catchpointwriter.go, ledger/store/kvsIter.go
Handles the last remaining queries left in `ledger` used in production code.
A few sql statements remain in specific tests.
**Previous parts of this refactor:**
- part 1 - #4776
- part 2 - #4813
- part 3 - #4830
- part 4 - #4835
- part 5 - #4836 
- part 6 - #4841 
- part 7 - #4846 
- part 8 - #4860 
- part 9 - #4864 
- part 10 - #4874 
**What remains to be moved out:**
=> refactor: accountdb.go into a store package (11 of N) 

agreement/agreementtest/simulate_test.go, daemon/algod/api/server/v2/test/helpers.go, data/basics/testing/userBalance.go, data/basics/userBalance.go, data/common_test.go, data/ledger_test.go, ledger/acctonline.go, ledger/archival_test.go, ledger/fullblock_perf_test.go, ledger/ledger_perf_test.go, ledger/testing/initState.go
Some tests use `MakeAccountData` for accounts creation for ledger init state, and then ledger fails to persist it b/c they are not complete (online accounts do not have voting fields set, leading to hundreds of warning messages and longer run time.
This PR makes `MakeAccountData` test-only method (since it is only used in tests) and producing ledger-expected data.
Also removed couple warning messages from online accounts tracker since they were there only as initial eye-catchers during development and testing.
Existing tests
=> testing: make MakeAccountData as testing only method

daemon/algod/api/algod.oas2.json, daemon/algod/api/algod.oas3.yml, daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
WaitForBlock waits for r+1 so updated the method summary.
Resolves https://github.com/algorand/go-algorand-internal/issues/1361
Existing tests
=> rest api: update WaitForBlock summary

data/txHandler_test.go
While running benchmarks found they do not produce invalid groups anymore. Fixed.
This is a test/bench harness fix.
=> bench: fix benchmarking after remerges

logging/telemetryhook.go, logging/telemetryhook_test.go
The asyncTelemetryHook implementation (in telemetryhook.go) uses logging in a single place, when it encounters an error reporting an event. This should ensure the asyncTelemetryHook drops any events reported inside its own implementation, so it does not re-wrap and re-report events unnecessarily.
Added TestAsyncTelemetryHook_SelfReporting
=> telemetry: don't report let asyncTelemetryHook wrap and log its own errors

logging/cyclicWriter.go
There is a possibility someone might log very large error messages, and they are lost if exceed the log rotation file size.
To prevent this, dump part of the message into stderr as well as callstack to see the caller. 
Existing tests
=> log: stderr offending large log messages

.golangci.yml, data/transactions/logic/assembler_test.go, data/transactions/logic/backwardCompat_test.go, data/transactions/logic/blackbox_test.go, data/transactions/logic/box_test.go, data/transactions/logic/debugger_test.go, data/transactions/logic/doc_test.go, data/transactions/logic/evalAppTxn_test.go, data/transactions/logic/evalCrypto_test.go, data/transactions/logic/evalStateful_test.go, data/transactions/logic/eval_test.go, data/transactions/logic/jsonspec_test.go, data/transactions/logic/opcodes_test.go, data/transactions/logic/parsing_test.go, data/transactions/logic/sourcemap_test.go
This PR parallelizes existing tests within the logic package. Tests that could be parallelized and were missing the `t.Parallel()` demarcation have been fixed and tests that are unable to be parallelized were labelled accordingly.
This is the first PR of several that will reduce test times by parallelizing existing tests within the repository. These changes will be distributed across several smaller PRs so that benefits can be seen immediately, fewer changes need reviewing, and it is less likely that new tests are introduced while waiting for these PRs to be merged.
All existing logic package tests passed locally and the golangci-lint paralleltest linter showed no paralleltest errors within the logic package since the initial commit.
<details>
<summary>
<b>Confirming This Locally</b> …
=> Tests: Fix `t.Parallel()` errors in `data/transactions/logic` package

data/transactions/logic/evalAppTxn_test.go
Extends https://github.com/algorand/go-algorand/pull/4931 to remove `nolint:paralleltest` in several cases where I think it's safe.
During my inspection, I didn't see the mentioned shared usage. As a sanity check, I ran each changed test numerous times to check for non-determinism (e.g. `go test ./data/transactions/logic -run "TestInnerTxIDCaching" -count=1000`).
=> Tests: Enable more parallel tests in data/transactions/logic/evalAppTxn_test.go

test/scripts/e2e.sh, test/scripts/e2e_basic_start_stop.sh, tools/network/resolver_test.go
Extends #4941 to switch `e2e_basic_start_stop.sh` network from devnet to private network.
Using a private network ameliorates a CircleCI-specific DNS connectivity issue.  Additionally, we may wish to retain private network usage as a way to minimize dependencies for the basic start/stop sanity check.
=> Tests: Switch e2e_basic_start_stop from devnet to private network

test/scripts/e2e.sh
Removes an unused e2e_subs Python dependency:  https://pypi.org/project/cryptography.
=> e2e_subs:  Remove unused Python cryptography package

logging/telemetryhook.go
Following on https://github.com/algorand/go-algorand/pull/4932 this also keeps ES client warnings and error logs from being reported back to telemetry.
=> telemetry: don't report ES client errors

ledger/bulletin.go, ledger/ledger_test.go
Fixes potential leak of ledger waiters.
Unit test that triggers leak in ledger_test.go.
=> Ledger: bulletin leaking waiters fix

node/node.go
[This commit](https://github.com/algorand/go-algorand/commit/a3e90ad357dab65c8796d7070662333ecf8b423a#diff-375d57e386f20eaa5f09f02bb9d28bfc48ac3dca18d0325f59492208219e5618R388) runs a goroutine without adding it to the monitoring wg.
=> node: Add logging thread to node monitoring wg

util/s3/s3Helper.go, util/s3/s3Helper_test.go
_this will not be `live` until `update.sh` is updated to use the version this updater is released with, e.g._
https://github.com/algorand/go-algorand/blob/026f0aac15d4f0ec1b63acd53bb8c6cf103487e7/cmd/updater/update.sh#L4
- updates the s3Helper to allow more credential providers. now AWS_ environment variables, config files, and EC2 metadata are supported credential providers when using tools like `updater` and `goal logging send`.
- removes error if AWS_ environment variables are not set
- removes the ability to configure credentials with a `s3.json` file
- forces use of Anonymous credentials when communicating with `algorand-releases`
- if no credentials are found, it uses Anonymous credentials
- ci
- internal performance testing
=> util/s3: enable more credential providers

.github/workflows/container.yml, Dockerfile, docker/README.md, docker/files/build/install.sh, docker/files/run/run.sh, scripts/compute_branch.sh
Adds a GitHub Actions container workflow and other updates.
- linux/amd64
- linux/arm64
- feature/\*, rel/\*, and master branches (e.g. feature/testing -> feature-testing)
- tag (e.g. v3.13.1-stable)
- long commit SHA (e.g. f06c4816d0e7c5ec1a67744373268719d012e628)
- removed the use of `./scripts/dev_install.sh`. 
- coming after `make build` this was another build.
- this forced the CHANNEL to always be `dev` even when building other branches like `rel/stable`.
- this also removed the creation of `dataTemplate`. the functionality was replaced by instead copying config.json.example to the correct location in `run.sh` in `start_new_public_network`
- switched builder to use `ubuntu:18.04` instead of `golang:$GO_VERSION-slim`
- creates and uses the `algorand` user inside the container.
- …
=> CICD: add container build

data/transactions/verify/txn_test.go
The test expects to have the stream verifier shut down after the EnqueueBacklog returns an error. 
To induce an error from EnqueueBacklog, the tests cancels the task ctx while the task is in the exec pool queue. 
However, the task ctx canceled is the same as the stream verifier ctx, and occasionally, the stream verifier shuts down because of the ctx before it gets the change to enqueue the task to EnqueueBacklog. When this happens, the tests fails, because the expected message does not get logged. 
To fix this,  never shut down the stream verifier ctx, instead, shut down the verification pool ctx to make sure the batch is rejected from the exec pool and not the batch ctx.
=> Test fix: flaky TestStreamVerifierCtxCancelPoolQueue

.golangci.yml, data/account/participationRegistry_test.go, data/account/participation_test.go, data/accountManager_test.go, data/basics/address_test.go, data/basics/fields_test.go, data/basics/teal_test.go, data/basics/units_test.go, data/basics/userBalance_test.go, data/bookkeeping/block_test.go, data/bookkeeping/encoding_test.go, data/bookkeeping/lightBlockHeader_test.go, data/bookkeeping/txn_merkle_test.go, data/committee/credential_test.go, data/committee/encoding_test.go, data/committee/sortition/sortition_test.go, data/pools/transactionPool_test.go, data/transactions/application_test.go, data/transactions/json_test.go, data/transactions/payment_test.go, data/transactions/payset_test.go, data/transactions/signedtxn_test.go, data/transactions/teal_test.go, data/transactions/transaction_test.go, data/transactions/verify/txn_test.go, data/transactions/verify/verifiedTxnCache_test.go, data/txHandler_test.go
This PR parallelizes existing tests within the data package. Tests that could be parallelized and were missing the t.Parallel() demarcation have been fixed and tests that are unable to be parallelized were labelled accordingly.
This is the second PR of several that will reduce test times by parallelizing existing tests within the repository. My initial, basic benchmarking shows an average decrease in data package test times of at least 20%.
All existing data package tests passed locally and the golangci-lint paralleltest linter showed no paralleltest errors within the data package since the initial commit.
<details>
<summary>
<b>Confirming This Locally</b>
</summary>
<br />
First, remove the revision configuration:
```
...
-        new-from-rev: eb019291beed556ec6ac1ceb4a15114ce4df0c57~25 …
```
=> Tests: Fix `t.Parallel()` errors in `data` package

data/transactions/logic/eval.go
This reverts commit 19fa6c2471181d494245b0a36d7d8d57ca18ddab.
For maximum safety, we're going with a different appraoch.
=> AVM: Revert 'AVM: Catch any panic in edcsa verifying (#4368)'

data/txHandler.go, network/wsPeer.go, util/rateLimit.go, util/rateLimit_test.go
Addresses a flaky Unit Test by not overloading the component under test (previously, 5k messages were driven as-fast-as-possible. Now, 10k messages are driven in batches of 500 with a 100ms delay). The new behavior is more accurate to a realistic usage pattern, as well.
This also addresses some deletable code and adds comments where requested from some post-merge requests on pull #4797.
Reproduced instability by running
```
x=0; while [[ $x -lt 12 ]]; do go test ./util -run TestREDCongestionManagerShouldntDrop -count=100 & sleep 1; x=`expr $x + 1` done
```
Then made my edits and reran. None of the results failed after making my changes.
Additionally,
```
make build
make fmt
make lint
go test ./util --race
```
=> tests: fix unstable TestREDCongestionManagerShouldntDrop

scripts/compute_branch.sh
_this was introduced in https://github.com/algorand/go-algorand/pull/4927_
- updates the conditional in compute_branch.sh to use the `-z` operator, otherwise it works opposite as it was intended. 
- ci 
- locally (see below)
Executing `make build` you should see the `-X github.com/algorand/go-algorand/config.Branch=fix/compute-branch-condition`
this is what we see on `rel/nightly` (it's empty)
=> scripts(compute_branch): fix incorrect conditional

cmd/algod/main.go, config/localTemplate.go, config/local_defaults.go, installer/config.json.example, test/testdata/configs/config-v26.json, test/testdata/configs/config-v27.json
Adds a configurable HeartbeatUpdateInterval to control how often the heartbeat telemetry event is sent, when telemetry is enabled.
=> config: add HeartbeatUpdateInterval

cmd/updater/update.sh
With the removal of S3 credential requirements, the updater script has an additional output line to indicate it's using anonymous credentials. This breaks the parsing of version. This changes the sed from counting lines to just taking the last line with tail.
Verify that nightly integration works properly.
=> Updater: fix update.sh parsing of latest version

data/account/participationRegistry_test.go, data/account/participation_test.go, data/bookkeeping/block_test.go, data/transactions/json_test.go, data/transactions/verify/txn_test.go, data/txHandler_test.go
Retain improvements made in #4981 PR that had been reverted due to instability. The changes here should net improve test reliability and rationale for why several are not marked parallel.
Ran impacted tests locally several times.
=> Tests: Fixes saved from 4981 revert

.golangci.yml
Splits paralleltest lint excludes into multiple entries to minimize merge conflicts.  Functionally, makes _no_ change.  
Since the existing `path` definition is on a single line, it's liable to create merge conflicts when there's concurrent PRs updating paralleltest usage.
I attempted to provide the definition as a multiline yml string via `>-`, but it didn't work.  I found no other workarounds and I'd like to avoid merge conflicts in PRs like #4991, #4992, #4993.
=> CI: Split paralleltest lint excludes to minimize merge conflicts

data/transactions/logic/eval.go, data/transactions/logic/evalCrypto_test.go, data/transactions/logic/eval_test.go
Cleans up benchmarks in a way that should let us assign costs more easily, especially for costs that differ based on input size.
One such benchmark showed that "byte math compares" were all significantly improved by avoiding the use of big.Int, so that change is included.
=> AVM: Clearer cost benchmarks, and a nice optimization of b== and b<

stateproof/builder.go, stateproof/db.go, stateproof/signer.go, stateproof/worker_test.go
- Change insertSigToBuilder from Worker method to builder method
- Reuse insertSig in handleSig as well, with the newly defined custom errors
- Implement getMessage to fetch stateproof message from DB instead of using getBuilder
=> Refactor insertSigToBuilder and handleSig, avoid unused allocations

tools/boxkey/convertBoxKey.go
Fix `MakeBoxKey` location after #4979
=> build: fix build after #4979

logging/telemetryspec/metric.go, logging/telemetryspec/metric_test.go
Support for parsing and printing the transaction processing time histogram buckets in an easier-to-read format.
Updated tests in metrics_test
=> debug: unmarshal and print transaction distribution

cmd/goal/messages.go
=> bugfix: Remove accidental devtesting output.

ledger/applications_test.go, ledger/store/sql.go
Re-merge of v3.13.3-stable to master
=> Mergeback: relstable3.13.3

config/localTemplate.go, config/local_defaults.go, installer/config.json.example, test/testdata/configs/config-v27.json
According to the latest measurement a single connection consumes about 1 MiB of RAM (calculated 600 KiB measured lower bound is 800 KiB, upper bound is 1.5 MiB).
Setting `IncomingConnectionsLimit` to 2400 should have a total memory footprint of 3.6 GiB.
Also decreased `MaxConnectionsPerIP` to 15 as a best guess based on a fact only fraction of nodes report hitting this limit.
Existing tests
=> network: increase max incoming connections limit

cmd/algocfg/getCommand.go, cmd/algocfg/resetCommand.go, cmd/algocfg/setCommand.go
This error was being triggered by the new docker container. The working theory is that a newer config file is sometimes used with an older version of algocfg. This error message would clarify what is going wrong.
=> algocfg: Clarify config file loading error.

agreement/events.go, agreement/msgp_gen.go, agreement/player_test.go, agreement/proposal.go, agreement/proposalStore.go
In #4583 I tried to add a receivedAt proposal timing, following the pattern in #3703 for adding the validatedAt timing, but didn't correctly account for the receivedAt time needing to be attached to the `unauthenticatedProposal` while the validatedAt time is attached to the validated `proposal` type. So the receivedAt timing when reported at `ensureAction` time was 0.
The receivedAt and validatedAt timings are only used for telemetry reporting of performance information in the BlockAcceptedEventDetails message.
Added a test `TestPlayerRetainsReceivedValidatedAt` to reproduce this behavior, then fixed it.
=> agreement: fix receivedAt proposal performance timing

data/txDupCache.go
Add a check in the cache without rehashing before writing and  returning to avoid the race condition that allows close to simultaneous received transactions to miss the cache due to a race condition. 
Currently checks both caches but could reasonably only check the current cache if we wanted to trade some time cost for slightly lower hit rate.
Benchmark results:
Old:
```
BenchmarkDigestCaches/data.digestCacheMaker/threads=1-10         	 1620752	       773.7 ns/op	     200 B/op	       2 allocs/op
BenchmarkDigestCaches/data.saltedCacheMaker/threads=1-10         	 1000000	      1030 ns/op	     220 B/op	       4 allocs/op
BenchmarkDigestCaches/data.digestCacheMaker/threads=4-10         	 2157205	       591.4 ns/op	     165 B/op	       2 allocs/op …
```
=> Txhandler: Improve dedupe hit rate

data/transactions/logic/eval.go, data/transactions/logic/eval_test.go
Added test for old failing case.
=> AVM: Fix opBytesLt for len(rhs) < len(lhs)

node/node_test.go
TestInitialSync creates 10 full nodes that is too much for CI builder.
This is a test
=> tests: disable TestInitialSync on CI

data/committee/sortition/sortition.go
A recent release to the Mac C/C++ build tools have caused warnings about sprintf to appear when building the data/committee/sortition package while parsing a Boost header that uses sprintf. This silences those warnings, as our usage of Boost's boost::math::binomial_distribution should not invoke these sprintf calls.
=> build: update C++ flags for recent Mac compiler warnings

daemon/algod/api/server/v2/delta.go, daemon/algod/api/server/v2/delta_test.go, daemon/algod/api/server/v2/handlers.go, tools/debug/vbconvert/README.md, tools/debug/vbconvert/main.go
Helper command to assist with converting files during development.
=> development: tool to convert validated blocks.

test/framework/fixtures/restClientFixture.go
Time to time some e2e tests fails on waiting for txn go get included into a block. This change adds more logging for such failures to ensure txns are at least propagated to all nodes.
This is a test fixture change.
=> e2e tests: log pending transactions in case of failure

cmd/goal/commands.go, cmd/goal/commands_test.go
Allow relative data-dir, as described within #589
existent tests pass, added some more tests
```sh
go test -v ./cmd/goal
```
=> goal: allow for relative dataDir via -d cmd option

cmd/goal/network.go
Added --start flag to "goal network create" that will cause the network to be run after creation.
Manually run.
=> Goal: --start option for network create command

ledger/acctdeltas_test.go, ledger/acctonline.go, ledger/acctonline_test.go, ledger/acctupdates.go, ledger/acctupdates_test.go, ledger/archival_test.go, ledger/catchpointtracker.go, ledger/catchpointtracker_test.go, ledger/catchpointwriter_test.go, ledger/catchupaccessor.go, ledger/ledger.go, ledger/ledger_test.go, ledger/store/interface.go, ledger/store/store.go, ledger/store/testing.go, ledger/tracker.go, ledger/trackerdb.go, ledger/txtail.go, ledger/txtail_test.go
- this adds a top level store and three root functions for operating with the db
- direct usage of `db.Pair` and/or `db.Accessor` for the trackerdb/catchpoints has been removed.
- `Transaction` (atomic read+write), `Snapshot` (isolated reads), `Batch` (all or nothing writes) 
Upcoming PRs:
=> refactor: abstract store and remove all `db.Atomic` usage

ledger/catchpointtracker.go, ledger/catchpointwriter_test.go, ledger/catchupaccessor.go, ledger/store/interface.go, ledger/store/merkle_commiter.go, ledger/store/store.go, ledger/txtail_test.go
- removed the `sql.Tx` from the `.Transaction(..)` callback.  
- abstract merkle commiter creation
- abstract account iter creation
This PR is part of a series:
- 1/n #5021 
Existing tests
=> refactor: remove `sql.Tx` from the transaction callback 

netdeploy/networkTemplate.go, test/e2e-go/cli/goal/expect/goalExpectCommon.exp
More kmd logging in expect test runner to diagnose sporadic expect test failures.
Added "goal account import key" logging in net template code to diagnose "Error creating private network: exit status 1" errors.
This is test-related code
=> tests: add more logging to expect test

netdeploy/networkTemplate.go, netdeploy/networkTemplates_test.go, netdeploy/remote/nodeConfig.go, test/testdata/nettemplates/perf/mkconf.py
Allow ConfigJSONOverride in `goal network create` templates similarly to `netgoal`.
=> goal: allow ConfigJSONOverride in local network templates

config/config_test.go, config/localTemplate.go, daemon/algod/server.go, network/wsNetwork.go, util/util.go, util/util_windows.go
algod sets RLIMIT_NOFILE to max possible value on startup. This might result the node failure on startup especially if it is a non-relaying node and does not need to listen for thousands of incoming connections.
Additionally enhanced config test since I opened the file:
* Replace shared "tempdir" by t.TempDir
* Make them parallel
* Make test naming consistent
New test for `IsGossipServer` config helper. Existing tests for everything else.
=> algod: split SetFdSoftLimit calls for relay and non-relay nodes

ledger/acctonline.go, ledger/acctonline_test.go, ledger/acctupdates.go, ledger/acctupdates_test.go, ledger/catchpointtracker.go, ledger/tracker.go, ledger/txtail.go, ledger/txtail_test.go
Based on observations from #4419 it seems like deferredCommitContext.newBase is always set to the value of oldBase + offset, and is only stored on the DCC struct for code deduplication / convenience reasons. To enforce the invariant that newBase is always oldBase+offset and guard against bugs if this were not true, this turns it into a function rather than an assigned struct field.
Existing tests updated and should pass.
=> ledger: turn deferredCommitContext.newBase into a function

daemon/algod/api/server/v2/delta.go, daemon/algod/api/server/v2/delta_test.go
=> API: Incorrect KvDelta in StateDeltaToLedgerDelta 

daemon/algod/api/server/v2/handlers.go
Avoid extra call to `ledger.BlockHdr`. It is unnecessary and seemed to lead to a crash in some edge cases.
=> goal: fix for goal node status crash - no longer getting block

.github/workflows/container.yml
disables `update-repo-description` job until DockerHub supports tokens for API auth.
=> fix(gha): disable update-repo-description

ledger/README.md, ledger/bulletin.go, ledger/bulletin_test.go, ledger/ledger.go, ledger/ledger_test.go, ledger/tracker.go, ledger/voters.go, stateproof/abstractions.go, stateproof/builder.go, stateproof/stateproofMessageGenerator_test.go, stateproof/worker_test.go
Current `loadFromDisk` expectation it reconstructs a brand new tracker. `bulletin` and `voters` break this by allowing some state remain between reloads.
This PR documents this behavior and adds `eternalData` concept.
Existing tests
=> ledger: eternalData trackers concept

daemon/algod/api/server/v2/delta_test.go
https://github.com/algorand/go-algorand/commit/e544fc8f6131c924d5ef56bbda9eba98bedf335a introduced additional test cases for the output of a `model.LedgerStateDelta` conversion from `ledgercore.StateDelta`, but it assumes that the output order of KvMods in the result will be equal to the input order.
In other words `[{"box1"},{"box2"},{"box3"}]` may convert to `[{"box2"},{"box1"},{"box3"}]` so we need to sort the output to get deterministic results.
=> tests: Fix test by sorting results

node/follower_node.go, node/node.go, test/scripts/e2e_subs/time.sh
We  started skipping the last round timestamp and synced since timestamp with a recent change.
New e2e test.
=> node: Fix time since last block.

test/e2e-go/cli/goal/expect/catchpointCatchupTest.exp, test/e2e-go/cli/goal/expect/goalExpectCommon.exp
Catchpoint test exists like algod process was killed, so added `top` invocation to monitor algod processes presence as well as machine memory usage.
Additionally fixed a wrong hardcoded wait round number in this test - it would not cause a failure but still a small inconsistency. 
This is test-related code
=> tests: debug flaky expect test

cmd/algorelay/relayCmd.go
=> algorelay: Fix typo in relayCmd.go

.github/ISSUE_TEMPLATE/enhancement.md
The `Enhancement` label is there, and clearly the dev-processes here distinguish between `New-Feature` and `Enhancement` (see additionally the PR processing).
So there is no reason to not provide an issue-template, thus users can pick it right from the beginning:
https://github.com/algorand/go-algorand/issues/new/choose
a little bit on own repo, but is trivial
(please feel free to close this PR and create the template with your requirements from the github UI - should be here:
* https://github.com/algorand/go-algorand/issues/templates/edit)
=> repo: add an Enhancement issue-template

.circleci/config.yml
We were seeing an issue where the validation tests were sometimes showing tests that were running on other branches in our self-hosted CircleCI runners.
1. Make the results path unique with the circleci's unique pipeline id. This will prevent collision of test validation results
2. Removed the stored_artifacts line on the combined results because the artifact is not used anywhere afterwards.
The files will stay in `/tmp` on the self-hosted runner for 3 days until it gets cleaned up.
There's an issue with trying to clean up afterwards on the mac machines. I tried adding `rm -rf << parameters.result_path >>/<< parameters.result_subdir >>` but it didn't actually clean up the subfolder. Adding `sudo rm -rf << parameters.result_path >>/<< parameters.result_subdir >>` would return errors on not …
=> CircleCI: Fix cached Results issue in self-hosted runner

ledger/bulletin.go, ledger/ledger.go, ledger/ledger_test.go, ledger/voters.go, node/node.go, stateproof/abstractions.go, stateproof/builder.go, stateproof/db.go, stateproof/stateproofMessageGenerator_test.go, stateproof/worker.go, stateproof/worker_test.go
Revert changes to bulletin keeping round notifiers in memory at reloadLedger.
=> Stop stateproof worker on catchpoint cathcup and restart when done.

network/netidentity.go, network/wsNetwork.go, network/wsNetwork_test.go
Following up on feedback from #4695, this adds an unexported disconnectReason field to the OutgoingMessage field for use with tracking internal network handlers' reasons for disconnecting.
Extended TestWebsocketDisconnection to use this new feature and assert the correct reason was reported.
=> network: add OutgoingMessage disconnectReason field

network/wsNetwork_test.go
Use `assert.Eventually` in three places where we need to wait for an asynchronous test value.
Explanation:
Let netA be the "initiating" peer who calls tryConnect
Let netB be the "receiving" peer who calls serveHTTP
In identity peering (and all peering), if netA disconnects from netB at any point after netB has sent the first httpResponse, netB continues on to addPeer. This is acceptable, since the underlying connection on the peer is closed, and the readloop on the peer will discover this and clean up the peering.
However, in testing, we initiate a peering and then check that the incoming/outgoing peer quantities are correct. This check can sometimes fail if the assert happens before the peer has been cleaned up. This was observed once in PR, where it was resolved with slightly longer …
=> Enhancement: use assert.Eventually to wait for peering to settle

.circleci/config.yml
This increases the test_nightly build resource class from medium (2 cores) to large (4 cores) as an alternative to #5053.
Existing tests should pass, nightly tests should also perform better.
=> CI: upgrade test_nightly infra to large

test/e2e-go/cli/goal/expect/goalExpectCommon.exp
The original implementation had scoping issue with `tcp_platform` global var as[ this build](https://app.circleci.com/pipelines/github/algorand/go-algorand/12833/workflows/df76b559-ebef-48a9-a76e-48c03c7eebfa/jobs/211941) indicated.
Additionally added stdout redirect for `exec` since its behavior in a script differs from REPL where I tested the original code.
This is a test harness change.
=> tests: fix debug output in expect test harness

netdeploy/networkTemplate.go, netdeploy/networkTemplates_test.go, node/follower_node.go, node/follower_node_test.go, node/node.go
Allow multi-node devmode private networks with one DevMode relay and one or more FollowMode followers.
This is required to support Indexer running against a DevMode network.
Note: added `DisallowUnknownFields` to the JSON decoder so that we would fail to create a private network if one of the configurations is unknown.
New unit tests.
In the future Sandbox would continuously integration test this configuration.
Manual test with the following configuration:
```
{
"Genesis": {
"LastPartKeyRound": 3000,
"NetworkName": "tbd",
"Wallets": [
{
"Name": "Wallet1",
"Stake": 100,
"Online": true
}
],
"DevMode": true
},
"Nodes": [
{
"Name": "Primary",
"IsRelay": true,
"Wallets": [
{
"Name": "Wallet1",
"ParticipationOnly": false
}
]
},
{
"Name": "Follower",
"Wallets": [],
"ConfigJSONOverride": …
```
=> devmode: Allow DevMode + FollowMode configurations.

test/testdata/nettemplates/TwoNodesFollower100Second.json
Fix a regression relating to stricter private network config validation. Follower configurations may no longer be marked as a relay.
Existing integration test. I think this change is compatible with the intent of the test that regressed.
=> fix(follower): update test that defines a follower relay.

daemon/algod/api/algod.oas2.json, daemon/algod/api/algod.oas3.yml, daemon/algod/api/server/v2/generated/data/data_routes.yml, daemon/algod/api/server/v2/generated/data/routes.go
The deltas endpoint is currently intended for internal use by Conduit. This PR adds the experimental tag to the endpoint in order to avoid including it in generated SDK code.
No functional changes.
=> fix(follower): add experimental tag to deltas endpoint.

cmd/goal/messages.go, cmd/goal/node.go
Current `goal node catchup` without args command starts a fast catchup process without making sure user understands that happens.
This might give an illusion about security guarantees by assuming it is the same as downloading blocks and validating them.
`goal node catchup` without args prompts user about possible security risk by using possible untrusted catchpoint and/or peers.
`goal node catchup -y` bypasses the prompt.
No changes to `goal node catchup catchpoint-label`
=> goal: catchup without args prompts to continue

node/node.go, stateproof/worker.go, test/e2e-go/features/catchup/stateproofsCatchup_test.go
Moved stateproof service stopping to be on pair with other services in case of fast catchup.
1. Tested manually
2. Extended e2e test to stop the usageNode entering a fast catchup mode. Unfortunately, this test does not asserts on panics in stderr because this is a bit non-deterministic - the catchpoint appy is very fast and could happen faster than stopping the node. The only real fix is to prepopulate accounts and have at least couple of thousands of accounts there.
=> Do not stop stateproof service in fast catchup mode

daemon/algod/server.go
We only require an API token in the header, so a much lower default for MaxHeaderBytes can be used. The gossip network port already uses 4096 as the default.
=> api: lower default for MaxHeaderBytes.

config/consensus.go, data/transactions/logic/eval.go
Go 1.19 has changed the semantics of ecdsa.Verify to panic if the public key is not on the appropriate curve.  This change prepares for supporting Go 1.19 by first establishing a new rule for the AVM opcode ecdsa_verify. By doing this in a consensus upgrade while still using Go 1.17, we force the change to occur across all nodes at once, and we ensure no changes occur in evaluating old blocks.
=> AVM: Go19 curve check

test/testdata/deployednettemplates/generate-recipe/generate_network_tpl.py
Default 5 npn appears too small to produce enough load for max TPS tests so set to 10
Manual test
=> deploy templates: increase default npn number for mmnet-model

ledger/acctdeltas_test.go, ledger/acctonline_test.go, ledger/acctupdates_test.go, ledger/ledger_test.go, ledger/store/trackerdb/interface.go, ledger/store/trackerdb/sqlitedriver/accountsV2.go, ledger/store/trackerdb/sqlitedriver/store_sqlite_impl.go, ledger/store/trackerdb/sqlitedriver/testing.go, ledger/store/trackerdb/store.go, ledger/store/trackerdb/testinterface.go, ledger/txtail_test.go
* Moves test-only interface definitions to a `testinterface.go` file
* Adds ".Testing()" to any interface with extra Testing functionality. The implementation will return itself as a test-interface. If the interface isn't satisfied, that will be caught as a compilation error (in your IDE), so no typeCasting at play here :)
* Restores the "TestAcctOnlineTopDBBehindMemRound" test. in doing so I added one new test function to abstract away the SQL in the test.
* Marked any test-only functions with a note that they implement the testing interface.
testing implementations still live in their original files, which I decided looked cleaner now that the `Testing()` function is able to enforce interface satisfaction -- if you need to add a test method, but don't supply an implementation, you'll …
=> Refactor: Push test-only functionality of storage interfaces into test-interface.

docs/messagepack.md
Was having a discussion about message pack and learned a couple things. Writing them down for posterity.
N/A
=> docs: Message pack information.

agreement/demux.go, agreement/events.go, agreement/msgp_gen.go, agreement/player_test.go, agreement/proposal.go
PP messages in the first period are compound messages, containing both a vote and a proposal, which are converted into a special `messageEvent` by `setupCompoundMessage()` with a structure like this:
```
messageEvent{
T: votePresent, 
Input: voteMsg, 
Tail: &messageEvent{
T: payloadPresent, 
Input: proposalMsg}}
```
In TestPlayerRetainsReceivedValidatedAt in #5041 I was only testing sending in two separate vote and proposal `messageEvent`s, not a single compound `messageEvent` like this, and so I missed this important case when attaching receivedAt timings.
=> agreement: update AttachReceivedAt to handle compound (PP) messages

docs/follower_node.md
Some general information about follower nodes.
N/A
=> Docs: add follower node documentation.

node/node.go
Skip network broadcast of transactions if the node is in devMode.
This fixes a regression that was introduced by https://github.com/algorand/go-algorand/commit/51d592515f03ea46b942b97c85b540c79b73defa#diff-375d57e386f20eaa5f09f02bb9d28bfc48ac3dca18d0325f59492208219e5618L188
Sdk tests (formerly failing with `broadcast queue full` see https://app.circleci.com/pipelines/github/algorand/go-algorand-sdk/771/workflows/d69fed8b-61bd-451b-9315-4f1900af7fdb/jobs/2124 ) all pass locally w/ this commit.
=> devmode: Fix devmode networking

data/transactions/logic/eval.go, data/transactions/logic/evalAppTxn_test.go, data/transactions/logic/evalStateful_test.go, data/transactions/logic/eval_test.go, ledger/acctdeltas.go, ledger/acctdeltas_test.go, ledger/acctonline.go, ledger/internal/appcow.go
Fix `err` shadowing introduced in https://github.com/algorand/go-algorand/pull/5177
Also add a small refactoring around Ledger and SigLedger initialization
Added new test
=> ledger: fix error shadowing in onlineAccountsNewRoundImpl

cmd/algocfg/profileCommand.go
The new profile uses `4160` for the `NetAddress` field, but this needs to specify a port. Changed this to `:4160`.
It'll fail to start catchup with the relay profile when set as is.
Set config profile to relay and started a node, verified that it was catching up.
=> algocfg: Bug fix - Add colon to indicate port specification

.github/workflows/reviewdog.yml, .golangci.yml, ledger/internal/appcow.go, logging/telemetryspec/metric.go
The reviewdog runs for golangci-lint have recently been crashing with the error `panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt` and it seems pinning the Go version fixes it.
This also fixes two lint errors that snuck through recently.
Reviewdog golangci-lint should run without crashing
=> CI: set reviewdog golangci-lint go version

nodecontrol/algodControl.go
Related to https://github.com/algorand/go-algorand/issues/2904
I use this patch to connect to a remote node
for example, connecting to https://algonode.io/api/
```sh
$ echo https://mainnet-api.algonode.cloud > algod.net
$ echo 0000000000000000000000000000000000000000000000000000000000000000 > algod.token
$ goal -d $PWD account info -a ZW3ISEHZUHPO7OZGMKLKIIMKVICOUDRCERI454I3DB2BH52HGLSO67W754
Created Assets:
ID 473073010, PW:GOV1, supply 3198752 PW_GOV1, https://bit.ly/3FouyUR
ID 815226506, PW:GOV2, supply 10855648 PW_GOV2, https://www.planetwatch.io/governance-vote-type-2-rewards/
ID 850324927, PW:GOV3, supply 10101621 PW_GOV3, https://www.planetwatch.io/governance-vote-recycle-bins-data-streams-recording
ID 864913853, PW:GOV4, supply 9865201 PW_GOV4, …
```
=> goal: user defined scheme to connect to remote host

util/rateLimit.go, util/rateLimit_test.go
Fix ERL when `CapacityPerReservation` set to 0.
Added a unit test
=> ERL: Support zero-size reservations

config/config.go, data/txHandler.go, data/txHandler_test.go, ledger/catchpointtracker_test.go
Fine tuning ERL might affect the dedup working set size in a negative way. This PR fixes that.
Additionally, make dedup creation optional (only if enabled). This is not important but looks a right thing to do.
Plus couple non-related small comment/assert noted along the way.
Existing tests
=> txHandler: make dedup working set independent from ERL

daemon/algod/api/algod.oas2.json, daemon/algod/api/algod.oas3.yml, daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
As I was reading https://github.com/algorand/go-algorand/pull/5159/, I noticed an addition of 404 response to `/v2/transactions/simulate`, while `handler.go` impl does not have `notFound` return.
So I remove the 404 response, as it is unused here.
=> Algod: Remove unused 404 resp in simulate endpoint

cmd/catchpointdump/file.go
Fix a regression introduced in #4743. Accumulated (read so far) size might exceed the file size that causes the progress printer to crash.
=> catchpointdump: fix panic when processing gzip files

ledger/store/trackerdb/sqlitedriver/accountsV2.go, network/wsNetwork.go, network/wsNetwork_test.go
* Rename "auto" to "testing" in wsNetwork for clarity
* Rewrite OnlineAccountsDelete comment for correctness
=> Fix: Tech Debt (wsNetwork "auto" and OnlineAccountsDelete comment)

cmd/updater/version_test.go, util/s3/s3Helper.go, util/s3/s3Helper_test.go
Local builds could produce packages with higher than build number than the comparator in `updater` can handle.
This affects both updater and nodecfg.
Added unit test
=> util/s3: improve patch number capacity in version comparison

daemon/algod/server.go, scripts/algorand_node_log.json, scripts/configure_dev.sh
- Install lnav (Logfile Navigator) dependency and add custom format for logrus
- Reformat "Logging Starting" messages to be JSON instead of strings
Usage:
1. Install dependency and custom format by running `./scripts/configure_dev.sh`
2. Open logfile by running `lnav node.log`
=> Dev Tools: Integrate Logfile Navigator (lnav)

test/testdata/deployednettemplates/recipes/custom/configs/nonPartNode.json, test/testdata/deployednettemplates/recipes/custom/configs/relay.json
Set `EnableRuntimeMetrics` to true in for custom templates (this includes mainnet model. This would provide more data about nodes performance when running large tests.
=> test: enable runtime metrics in custom templates

docker/README.md, docker/files/run/followermode_template.json, docker/files/run/run.sh, docker/files/run/template.json
updating dockerfile to support devmode + followermode container
- supporting private network topology override.  
- adding a new env var `PEER_ADDRESS` for running multiple containers. A follower node container can connect to the relay node container by setting the host:port in`PEER_ADDRESS` .
=> docker container: dockerfile update 

cmd/algod/main.go
Currently phonebook.json is only searched in bin directory that might not be very convenient.
Changed to check data dir as well.
=> algod: search phonebook in data directory as well

tools/debug/chopper/main.go
I'm running go1.18 locally and the lint check fails because `strings.Title` is deprecated in go1.18.
```
tools/debug/chopper/main.go:134:46: SA1019: strings.Title has been deprecated since Go 1.18 and an alternative has been available since Go 1.0: The rule Title uses for word boundaries does not handle Unicode punctuation properly. Use golang.org/x/text/cases instead. (staticcheck)
fmt.Printf("%s in first: %d, second: %d\n", strings.Title(rd.what), rd.size1, rd.size2)
```
Replaced it with `cases.Title` for English which looks to have the same behavior.
Ran a basic test and it looks correct from what I can tell.
```
go run ./tools/debug/chopper/main.go ./log_copy.log ~/.algorand/node.
log 
Roots in first: 45, second: 45
Matched roots: 45
Mismatched roots: 0
Other roots in first: 0, …
```
=> tools: Don't use strings.Title in chopper

test/e2e-go/cli/goal/expect/goalExpectCommon.exp
Fix for the failure seen in this [job](https://app.circleci.com/pipelines/github/algorand/go-algorand/13364/workflows/690d2fc9-2c9e-47e4-8cf1-f5107c309315/jobs/220405/parallel-runs/7?invite=true#step-114-719):
1. do not use \r\n in regex
2. use `top -b` on Linux to prevent `top: failed tty get` error
Tested in expect REPL: `expect1.10> ::AlgorandGoal::VerifyMultisigInfoForOneOfTwoMultisig ...`
=> tests: fix expect test regex and logger

.gitignore, tools/block-generator/README.md, tools/block-generator/core/commands.go, tools/block-generator/generator/daemon.go, tools/block-generator/generator/generate.go, tools/block-generator/generator/generate_test.go, tools/block-generator/generator/make_transactions.go, tools/block-generator/generator/server.go, tools/block-generator/generator/server_test.go, tools/block-generator/generator/utils.go, tools/block-generator/generator/utils_test.go, tools/block-generator/main.go, tools/block-generator/metrics/metrics.go, tools/block-generator/run_generator.sh, tools/block-generator/run_postgres.sh, tools/block-generator/run_runner.sh, tools/block-generator/run_tests.sh, tools/block-generator/runner/metrics_collector.go, tools/block-generator/runner/run.go, tools/block-generator/runner/runner.go, tools/block-generator/scenarios/config.asset.close.yml, tools/block-generator/scenarios/config.asset.destroy.yml, tools/block-generator/scenarios/config.asset.xfer.yml, tools/block-generator/scenarios/config.mixed.jumbo.yml, tools/block-generator/scenarios/config.mixed.yml, tools/block-generator/scenarios/config.payment.full.yml, tools/block-generator/scenarios/config.payment.jumbo.yml, tools/block-generator/scenarios/config.payment.small.yml, tools/block-generator/test_config.yml, tools/block-generator/util/util.go
adding block generator to `/tools`.  the code is copied from an internal tools repo. Some fixes were needed to pass the CI.
=> tools: block generator

data/transactions/logic/assembler.go, data/transactions/logic/assembler_test.go
Although it is not a security problem, it's poor form to panic rather than return a nice error when disassembling bad programs.  The disassembler was unconditionally trying to decode the labels of branching opcodes without checking to see if the program was long enough to hold them.
=> AVM: Avoid panics in disassembly when branch instructions are short

test/scripts/e2e_subs/e2e-app-simulate.sh
This PR changes use of `truncate` to `dd` when create large zero-ed files. This was due to a breaking nightly build in `mac_amd64`, since the `truncate` command was not available there. 
Also adds all simulate test artifacts to the tempdir so they can be cleaned up at the end of the test. Locally checked that test files were being cleaned up by running `./test/scripts/e2e.sh`
=> tests: Change truncate to dd for mac amd tests

daemon/algod/api/client/restClient.go, data/transactions/logic/sourcemap.go, libgoal/teal.go, test/e2e-go/features/teal/compile_test.go
The motivation of this PR is that, we want to allow for algod to simulate with option of `unlimit-log`: see #5230.
We need to send transaction with auxiliary query parameters. The current implementation in `restClient` disallowed us for such feasibility, while https://github.com/algorand/go-algorand-sdk/pull/335 contain relevant modification, and this PR mimic the changes, by separating `request` into `params` and `body`.
We expect to use this for `simulation`, where `/v2/transactions/simulate` has query parameter `unlimit-log: bool`, with raw body of txn(-group). The simulation request body resembles the one in compilation, where `/v2/teal/compile` has query parameter `sourcemap: bool` and raw body of program source bytes.
Implement `Compile` with sourcemap option, and check existence of …
=> Algod: Minor refactoring REST client `submitForm` from go-sdk PR #335

cmd/algocfg/profileCommand.go
Add additional information when prompting to overwrite a config.json file. This should help in the event that `algocfg profile set conduit -d ""` falls back to the `ALGORAND_DATA` environment variable. This case is probably not very common for a normal installation, but could occur with testing scripts where a parameterized data directory is not properly set.
Manual testing.
=> algocfg(profile): Add file name to config file conflict message.

cmd/goal/clerk.go, daemon/algod/api/client/restClient.go, daemon/algod/api/server/v2/handlers.go, daemon/algod/api/server/v2/handlers_test.go, daemon/algod/api/server/v2/utils.go, libgoal/libgoal.go, test/e2e-go/restAPI/restClient_test.go
This PR uses the new REST client feature from #5253 to allow the client to get msgpack simulation responses. With this, the client can decode to the more precise `v2.PreEncodedSimulateResponse` instead of `model.SimulateResponse`.
The only difference between these two types is that `model.SimulateResponse` uses `map[string]interface{}` to represent transactions, while `v2.PreEncodedSimulateResponse` uses `transactions.SignedTxn`. This results in a minor problem, since our JSON decoder will decode integers as float64 by default, and this makes responses look strange when `goal clerk simulate` re-encodes the JSON response.
For example, this response from `goal clerk simulate` adds `.0` after integers in the signed transaction:
```json
{
"last-round": 921,
"txn-groups": [
{ …
```
=> goal: Better formatting in `goal clerk simulate`

test/scripts/e2e_subs/e2e-app-simulate.sh
Changes `dd`'s `bs` argument to a bytes value to work on both macOS (specifically, CircleCI's macOS 11) and linux. Also added a comment above the line to justify this:
```
```
Nightly integration tests seem to pass now: https://app.circleci.com/pipelines/github/algorand/go-algorand/13522/workflows/2cca47be-d835-48c3-897e-7f713e521534
=> tests: Change `dd` argument to use a bytes value

data/transactions/logic/assembler.go, data/transactions/logic/assembler_test.go
Added tests for immediate bounds
Fixes #5217
=> AVM: Avoid panics while type checking bad immediates

docker/files/run/devmode_template.json
Disables rewards pool in the default devmode template. I imagine this is what most expect when running devmode, especially since it's disabled in the devmode template for sandbox.  
1. Run network with devmode enabled
2. Verify rewards are disabled
=> docker: disable rewards in devmode template

CONTRIBUTING.md, README.md
Update `CONTRIBUTING.md` to be more focused on code contributions to `go-algorand`. The catch-all nature of the previous version was useful for cross-documentation, but made it less useful for it's main purpose of guiding potential core contributors.
Some specific themes to this PR:
* Remove content about other repositories. It was out of date and a distraction for `go-algorand` contributors.
* More information about what should be done when preparing a PR.
* More information about what to expect during peer review, and an attempt to set expectations.
Not applicable.
=> chore: Focus CONTRIBUTING.md on code contributions.

CONTRIBUTING.md
fix broken links introduced with #5294
=> Fix: broken links (correct md link syntax) in contributing.md

ledger/tracker.go
If `MaxAcctLookback` is set to a large number, the tracker fails during replay. The failure is an arbitrary "this doesn't seem quite right" sort of check. This change adds consideration for the `MaxAcctLookback` variable to allow a longer replay range.
Another side effect of this change is that you can now fetch blocks from further than 1000 rounds ago. This has been requested many times.
Configured a node with `"MaxAcctLookback": 2048` to reproduce the replay error. After updating the condition the replay error has gone away.
=> ledger: Check MaxAcctLookback in tracker.

ledger/apply/stateproof_test.go, ledger/eval/cow.go, ledger/ledger_test.go, ledger/ledgercore/statedelta.go, ledger/ledgercore/statedelta_test.go, ledger/spverificationtracker.go, ledger/spverificationtracker_test.go
Remove `Mod` prefix because `ModStateProofNextRound` is an absolute round rather than some sort of mod/delta/offset.
Non functional change, existing regression tests.
=> chore: Rename ModStateProofNextRound to StateProofNext.

scripts/upload_config.sh
* Adds `trap`
* Prevents `tar` from directing stderr to null
* Clarifies and corrects tmp directory creation
Made these changes while I worked on getting a config uploaded which silently failed due to tar errors.
=> scripts: enhance upload_config.sh

ledger/acctdeltas.go, ledger/acctdeltas_test.go
Fixed err shadowing in accountsNewRound and rewrote accountsNewRound and onlineAccountsNewRound to return immediately. This is a slight behavior change: all the updated* return values are now empty on error
Added new test. Existing tests passed.
=> ledger: fix error shadowing in accountsNewRound

Dockerfile, docker/README.md, docker/files/run/run.sh
Set UID and GID to 999 consistently.
Start as root user for init then drop to algorand user.
Build the container locally
```
docker build \
-t algod_test \
--build-arg CHANNEL=stable \
--build-arg TARGETARCH=amd64 --no-cache \
.
```
Without these changes, mounting a directory fails with a permission denied error.
```
docker run --rm -it \
-p 4190:4190 \
--name algod-test-run \
-e TOKEN=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa \
-v (pwd)/docker_data_dir:/algod/data \
algod_test
```
Also had some help from Patrick testing in kubernetes.
=> docker: Updated user and data dir handling.

agreement/README.md
the mentioned `proposalCommittableEvent` does not exist in this form within the source code.
The correct event is `committableEvent`
https://github.com/algorand/go-algorand/blob/30acd707819fc9bc2b59036902d8b453ffbd4e10/agreement/events.go#L494-L500
=> docs: update agreement README with committableEvent

agreement/README.md
(1st part of invalidly closed #5280)
trivial
=> docs: increase heading levels, thus only one h1 is used

docker/README.md, docker/files/run/run.sh
Final feature from #5197 
These changes make the docker container easier to use without providing a `config.json` file, and make the behavior more expected when a `config.json` file is provided.
1. Move the endpoint address setting down. This ensures that the API is available at port 8080. Users who override the `config.json` file via `/etc/algorand/config.json` or the `PROFILE` environment variable would be likely to miss this option and be unable to access the REST API.
2. New `PROFILE` environment variable. When set algocfg is used to initialize the `config.json` file.
Manual testing. By mounting a data directory in different scenarios observe that the config.json file is set as expected.
Mount a config.json file
```
~$ cat algod_config.json
{
"CatchupParallelBlocks": 32, …
```
=> docker: add profile support and improved endpoint access.

data/transactions/logic/box.go, data/transactions/logic/box_test.go, data/transactions/logic/ledger_test.go, ledger/boxtxn_test.go, ledger/eval/applications.go
See issue #5229, the box key representation is essentially a byte slice wrapped under `string`. This representation does not necessarily fall under ASCII symbol set, and printing with `%v` or `%#v` will be hard to decode and debug.
We decide to print with hex, i.e., `%#x` format.
=> Algod: Better Box Reference Error Message

cmd/algocfg/profileCommand_test.go
Testing in `algocfg` gets flaky for non-deterministic string concatenation order from `profileNames`.
Improve testing by checking existence of each profile name in error string.
=> Test: Improve flaky test from non-deterministic order string

config/consensus.go, data/transactions/logic/backwardCompat_test.go, data/transactions/logic/eval.go, data/transactions/logic/eval_test.go, data/transactions/verify/txn.go, ledger/apply/application.go, ledger/apply/application_test.go, ledger/boxtxn_test.go, ledger/eval/appcow.go, ledger/eval/cow.go, ledger/ledgercore/error.go
Users find the extra info about the previous opcodes to be a helpful addition when debugging an app failure.  This extends the support to LogicSigs.
=> AVM: Show opcode context for logicsigs (not just apps)

scripts/build_package.sh
Adding the block-generator into tools bundle.
Accepting suggestions regarding how to test. Once it's on `master` and the nightly channel has finished building, we can verify that this worked with the following commands:
```sh
❯ LATEST_TOOLS_TAR_BALL=$(aws s3 ls algorand-releases/channel/nightly/ | sort | tail -n 1 | awk '{print $NF}')
❯ echo $LATEST_TOOLS_TAR_BALL
tools_nightly_linux-arm64_3.16.1601.tar.gz
❯ aws s3 cp s3://algorand-releases/channel/nightly/$LATEST_TOOLS_TAR_BALL .
download: s3://algorand-releases/channel/nightly/tools_nightly_linux-arm64_3.16.1601.tar.gz to ./tools_nightly_linux-arm64_3.16.1601.tar.gz
❯ tar -tzf $LATEST_TOOLS_TAR_BALL
algons
catchpointdump
cc_agent
cc_client
cc_service
COPYING
coroner
dispenser
dsign
loadgenerator
netgoal
nodecfg
pingpong
sysctl-all.sh …
```
=> tools: add block-generator into published build

.github/workflows/pr-type-category.yml, CODEOWNERS
For slightly better security we want to add a CODEOWNERS file to restrict workflow editing.
N/A - try to edit workflow after merge.
=> DevOps: Add CODEOWNERS to restrict workflow edits

cmd/goal/README.md, cmd/goal/application.go, config/consensus.go, data/transactions/transaction.go, data/transactions/transaction_test.go, test/scripts/e2e_subs/access-previous-scratch.sh, test/scripts/e2e_subs/box-search.sh, test/scripts/e2e_subs/e2e-app-abi-arg.sh, test/scripts/e2e_subs/e2e-app-abi-method.sh, test/scripts/e2e_subs/e2e-app-bootloader.sh, test/scripts/e2e_subs/e2e-app-delete-clear.sh, test/scripts/e2e_subs/e2e-app-extra-pages.sh, test/scripts/e2e_subs/goal-app-create-state-defaults.sh, test/scripts/e2e_subs/teal-creatable-id.sh
Follow up from #4946, this PR makes the goal app flags `--global-byteslices`, `--global-ints`, `--local-byteslices`, and `--local-ints` optional. Also errors earlier for invalid box names.
Added `test/scripts/e2e_subs/goal-app-create-state-defaults.sh` to ensure that omitting the flags has the same effect as setting them to 0.
Also modified existing tests to prefer omitting the state schema flags instead of setting them to 0.
=> goal: Make goal state schema optional

catchup/service.go, daemon/algod/api/server/v2/handlers.go, daemon/algod/api/server/v2/test/handlers_test.go, node/error.go, node/follower_node.go, node/follower_node_test.go
Automatically set the sync round after running fast catchup on a follower node.
New unit test.
=> follow mode: set sync round after fast catchup.

daemon/algod/server.go
Fixes the `Logging to` print statement to indicate stdout if a file is not being used.
Manually ran `algod` and `algod -o` to see the different log statements.
=> logging: fix logging to line.

daemon/algod/api/server/v2/test/handlers_test.go, daemon/algod/api/server/v2/test/helpers.go, ledger/applications_test.go, ledger/simulation/simulation_eval_test.go, ledger/simulation/testing/utils.go, ledger/testing/initState.go
#5328 changed the initial txn counter from 0 to 1000, and simulate tests relied on this starting at 0 to predict app and asset IDs. Since we were testing with the current consensus version, not future, we didn't see any problems.
Since it's best to fix tests at development time instead of release time, I changed the relevant testing infrastructure to use consensus future instead of current. I've also fixed the simulate tests to work with a higher initial txn counter.
Note: this PR is not exhaustive. There seem to be quite a lot of tests which use the current consensus version, so it's possible more issues like this are present.
Tests modified.
=> Algod: Use future consensus version to test with no low resources

ledger/acctonline_test.go, ledger/acctupdates_test.go, ledger/catchpointtracker_test.go, ledger/voters_test.go
Some of the ledger unit test does not add the block to the mock block queue and only invokes `newBlock` on all trackers. This causes the voters tracker to fail since it relays on data from the block queue.
In order to fix it, just need to make sure that blocks are added to the mock block queue
=> Tests: Fix error messages in ledger tests

docker/README.md
Include tagging information on the Algorand Docker Container documentation
N/A, just documentation update
=> Documentation: Add container image tagging information

daemon/algod/api/server/v2/test/handlers_test.go, ledger/eval/eval_test.go, ledger/eval/txntracer.go, ledger/eval/txntracer_test.go
The KvMods (and other fields in the StateDelta which are maps) have their values deleted when the roundCoW gets recycled. Because we're not copying this data out of the delta in the txn tracer, this affects the results returned by the tracer.
I've now copied all of the fields out of the maps in the StateDelta (for those that we care about returning).
Adding full unit tests for kvmods--other data should function similarly. This required adding some functionality to the eval test ledger which was not initially implemented during the Boxes PR.
=> txngroup-deltas: Fix pointer bug copying deltas for txngroups

tools/debug/dumpblocks/main.go
Without this opening blockdb.sqlite fails errors.
Manual test
=> tools: allow dumpblocks work with wal-enabled dbs

go.mod, go.sum
Update codec dependency from 1.1.8 to 1.1.9.
I was running into checksum dependency errors on my server:
```
verifying github.com/algorand/go-codec/codec@v1.1.8: checksum mismatch
downloaded: h1:RyokOQSEnNCxrngGqC5yrPNoQAGh5osBIKiaeKOe5fg=
go.sum:     h1:lsFuhcOH2LiEhpBH3BVUUkdevVmwCRyvb7FCAAPeY6U=
SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
```
After the change, I was able to build as expected.
=> Dependency: Update codec version to 1.1.9

daemon/algod/api/algod.oas2.json, daemon/algod/api/algod.oas3.yml, daemon/algod/api/server/v2/generated/data/routes.go, daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
In order to generate code for the SDKs we need these to be non-experimental APIs. We also want them to be enabled independent of users having to turn on follow mode.
Move the delta APIs to be default enabled on algod. This won't affect any production code paths--the EvalTracer for txn group deltas still needs to be turned on via a separate config option.
No functional changes--existing tests cover.
=> algod: Move delta API tags

netdeploy/remote/nodecfg/nodeConfigurator.go
I mucked up my git space and need to reproduce my previous PR:
https://github.com/algorand/go-algorand/pull/5347
=> netdeploy: Copy ledger directory for kv tracker database

data/transactions/logic/assembler.go, data/transactions/logic/assembler_test.go, data/txntest/txn.go, ledger/simulation/simulation_eval_test.go, netdeploy/remote/deployedNetwork.go, test/e2e-go/restAPI/restClient_test.go
One might think these programs are equivalent:
```
#pragma version 5; int 1
```
```
#pragma version 5
int 1
```
However, they are not. Pragma lines are "greedy" in that they consume all tokens in a line, but only look at the first 3.
I've ran into this a few times, so I thought it would be a good idea to at least error if you try to assemble with extra stuff after a pragma.
A better solution would be to treat semicolons as newlines and make those example programs actually equal, but I've not gone that far in this PR. (And it deserves some extra thought, since it's currently illegal to start a directive unless it's the first thing in a line. Plus `#define` is greedy because it actually consumes the whole line.)
Unit test added, existing tests fixed.
=> assembler: Error if extra args are present in pragmas

agreement/abstractions.go, agreement/agreementtest/simulate_test.go, agreement/common_test.go, agreement/demux_test.go, agreement/fuzzer/ledger_test.go, agreement/selector.go, catchup/service_test.go, config/consensus.go, data/datatest/impls.go, data/ledger.go, data/ledger_test.go, ledger/acctonline.go, ledger/acctonline_expired_test.go, ledger/acctonline_test.go, ledger/acctupdates.go, ledger/acctupdates_test.go, ledger/catchpointtracker_test.go, ledger/double_test.go, ledger/ledger.go, ledger/ledger_test.go, ledger/simple_test.go, ledger/store/trackerdb/interface.go, ledger/store/trackerdb/sqlitedriver/accountsV2.go, ledger/store/trackerdb/sqlitedriver/schema.go, ledger/store/trackerdb/sqlitedriver/trackerdbV2.go, ledger/testing/testGenesis.go
This adds a DB method to calculate the total expired stake registered at rnd that is expired by voteRnd.
It adds a consensus check to the ledger implementation of the Circulation(rnd) call that agreement makes, which in turn calls onlineAccounts.onlineTotals. If ExcludeExpiredCirculation is set, it subtracts expired stake at rnd+320 from the total online stake at rnd.
Details:
* when the next round is going to be round R, a proposal/vote will come in for round R (or some other trigger we could add)
* query the DB's onlineaccounts table looking for accounts online at R that are expired in any round before R+320 (this using the "updated as of rnd" and "expired by rnd" indexes)
* sum up the expired online stake for these accounts
* subtract expired stake from total online stake and put in …
=> ledger: Exclude stake at R-320 that is expired by R

logging/telemetryspec/event.go
=> typo: fix typo in event.go

docker/files/run/run.sh
Add PROFILE to script output. This should help with debugging and parameter discoverability.
N/A
=> docker: Fix ADMIN_TOKEN and add missing variables to echo statements.

ledger/acctonline.go, ledger/acctupdates.go, ledger/bulletin.go, ledger/catchpointtracker.go, ledger/catchpointtracker_test.go, ledger/ledger.go, ledger/metrics.go, ledger/notifier.go, ledger/spverificationtracker.go, ledger/tracker.go, ledger/tracker_test.go, ledger/txtail.go
The original implementation was setting this flag in task producer, that created a gap between setting it and actual writing catchpoint in commitSyncer.
Later, #5214 introduced ability to skip tasks if the queue is full. This caused an issue with catchup service that was reading the flag with IsWritingCatchpointDataFile() and stopping the catchup. Because of that ledger was not receiving new blocks and was unable to schedule a new commit task but had the catchpoint writing flag set from the previous discarded task.
Manual catchup with catchpoints enabled up to round 170k.
=> ledger: report catchpoint writing only when it actually started

cmd/goal/clerk.go, test/scripts/e2e_subs/e2e-app-simulate.sh
For the sake of uniformity, we rename `--allow-extra-opcode-budget` to `--allow-more-opcode-budget`, to align with `--allow-more-logging`.
=> Goal: rename `--allow-extra-opcode-budget` to `--allow-more-opcode-budget`

cmd/goal/clerk.go, docker/files/run/run.sh, ledger/acctonline.go, ledger/acctupdates.go, ledger/bulletin.go, ledger/catchpointtracker.go, ledger/catchpointtracker_test.go, ledger/ledger.go, ledger/metrics.go, ledger/notifier.go, ledger/spverificationtracker.go, ledger/tracker.go, ledger/tracker_test.go, ledger/txtail.go, node/follower_node_test.go, test/scripts/e2e_subs/e2e-app-simulate.sh, tools/block-generator/generator/generate.go, tools/block-generator/generator/generate_test.go, tools/block-generator/generator/server.go, tools/block-generator/run_runner.sh, tools/block-generator/runner/run.go, tools/block-generator/runner/runner.go
| **IMPORTANT**<br /> **This release requires a protocol upgrade.** <br /> This release contains a consensus protocol upgrade, which implements the following spec:  https://github.com/algorandfoundation/specs/tree/abd3d4823c6f77349fc04c3af7b1e99fe4df699f |
|---|
This update includes a drop in round time of ~0.4 seconds, a robustness improvement to State Proofs, and several developer-oriented features in the AVM, simulate, and devmode.
⚠️ In order to avoid opcode ambiguity, access to assets or applications with an ID less than 256 within a contract will fail immediately. For new networks, asset and application IDs will now start at 1000 to avoid any potential issues due to this change.
- 🚀 Round times are reduced by 400 milliseconds. See [here](placeholder) for details.
- 👥 Group resource …
=> go-algorand 3.16.0-beta Release PR

config/consensus.go, config/migrate.go
Running `golangci-lint run config/` (removing the commit hash gate in golangci.yml) generates the following lint error:
```
config/consensus.go:682:12: S1033: unnecessary guard around call to delete (gosimple)
} else if _, has := cParam.ApprovedUpgrades[consensusVersion]; has {
config/migrate.go:131:5: SA4003: no value of type uint32 is less than 0 (staticcheck)
if version < 0 {
```
This PR fixes this lint error by removing the guard around the delete call (the code is functionally the same, since deleting nil map key/value is a no op) and removing the negative check for `uint` values.
=> lint: Fix lint errors in `config/`

data/transactions/logic/debugger.go, data/transactions/logic/debugger_test.go, data/transactions/logic/eval.go
Static analysis tools noted that:
```
for i, sv := range cx.stack {
stack[i] = stackValueToTealValue(&sv)
}
```
was a potential problem because `sv` is always the same variable in a for loop, so this code was passing the same address on each call. That was fine, since stackValueToTealValue is single-threaded, and does not store the address. It's just a simple conversion.
But, noting that the conversion was more complicated than it needed to be, and probably allocated more than it needed to, this PR simplifies it and makes it work on stackValue values instead of pointers.
Also removes the unused function: valueDeltaToValueDelta and associated test.
Existing tests
=> AVM: Simplify conversion and fix a spurious complaint from static analysis

.golangci.yml, cmd/opdoc/opdoc.go, data/transactions/logic/assembler.go, data/transactions/logic/assembler_test.go, data/transactions/logic/backwardCompat_test.go, data/transactions/logic/box_test.go, data/transactions/logic/evalAppTxn_test.go, data/transactions/logic/evalStateful_test.go, data/transactions/logic/eval_test.go, data/transactions/logic/export_test.go, data/transactions/logic/fields_test.go, data/transactions/logic/frames_test.go, data/transactions/logic/resources_test.go
This should let IDE integrations or lsp-like programs use the assembly output to direct the cursor the exact spot of many problems. It also allowed some error improvements and simplifications because tokens from the assembly process now know their line number.
The changes in terms of line count are big, but mostly boring. The signatures of the asm* and type* functions changed to take tokens instead of strings, which caused a lot of churn.  Also, in order to minimize the work to change existing tests, I converted `testProg` calls so that they called `exp` instead of constructing an `Expect`. That allowed me to make the column checking optional by making the column an optional final argument to `exp`. I extended a bunch of tests to check columns, but many of the tests were mechanically …
=> TEAL: Add columns to assembly error messages.

data/transactions/logic/eval.go, data/transactions/logic/resources.go, ledger/apptxn_test.go, ledger/double_test.go
Starting in the same consensus version that allows resource sharing, this PR makes apps and app accounts of "pending" app creates available while their inners are executing.
This was the intent all along, but the new app was only added to `cx.createdApps` at the conclusion of its execution, rather than at the start.
Existing tests, plus some new ones that test that that holdings of the app account, and globals are accessible in inners of the create.
=> AVM: Make apps and app accounts available while creation is "pending"

scripts/release/mule/Makefile.mule
A build target was added that is missing from the ci-build dependencies.
N/A
=> CICD: fix ci-build target for buildsrc-special support

ledger/ledger_test.go
The title says it all. Related to #5432, reduce flakiness in CI testing.
=> test: skip flaky test `TestVotersReloadFromDiskPassRecoveryPeriod`

data/transactions/logic/eval.go, data/transactions/logic/evalAppTxn_test.go, data/transactions/logic/evalStateful_test.go
Title says it all. Delete dead code. Add some tests for coverage.
=> AVM: Increase coverage by deleting a dead function and adding limit tests

data/transactions/logic/eval_test.go, go.mod, go.sum
These tests are very simple, but a couple other PRs are also integrating `rapid` but are pending the other intent of those PRs. This is intended to be mergable easily.
=> Testing: Get rapid into the codebase

tools/debug/transplanter/main.go
The debugging tool allows to catchup to a certain round and either stop or start applying transaction(s) from a file, directory, txlog files or directory.
It uses `ledger.OpenLedger` + `pools.TransactionPool` while adding new data into ledger, and `node.follower_node` for catchup.
=> tools: txn replayer

data/bookkeeping/block.go
Updates commentary in the `BlockHeader` to support `TxCounter`s starting at nonzero numbers in genesis blocks (in support of banning low asset/app resources)
=> Bookkeeping:  improve block documentation since no-low-resources

ledger/acctdeltas.go, ledger/acctdeltas_test.go, ledger/acctupdates_test.go, ledger/store/trackerdb/data_test.go, ledger/store/trackerdb/interface.go, ledger/store/trackerdb/sqlitedriver/accountsV2.go, ledger/store/trackerdb/sqlitedriver/sql.go, ledger/store/trackerdb/store.go, ledger/store/trackerdb/testinterface.go
`LookupAccountDataByAddress` was only used in one place and was repeating the same logic as in `LookupAccount`. 
The difference between the two was that `LookupAccountDataByAddress` returned raw bytes instead  of decoding the account data. 
- `LookupAccountDataByAddress` was removed from the interface and the call site was  changed to used `LookupAccount` instead. 
=> cleanup: remove redundant method LookupAccountDataByAddress

data/transactions/logic/assembler.go, data/transactions/logic/assembler_test.go, data/transactions/logic/eval.go, data/transactions/logic/evalAppTxn_test.go, data/transactions/logic/eval_test.go, data/transactions/logic/opcodes.go, data/transactions/logic/resources_test.go, ledger/apptxn_test.go
Added some tests to get more coverage, deleted some dead code for the same reason.
Also regularized an error message about "Unavailable account"
Ran coverage locally. Better.
=> AVM: Some error cleanup, and added coverage

config/version.go, config/version_test.go, util/s3/s3Helper_test.go
PR https://github.com/algorand/go-algorand/pull/5224 changed version encoding for s3 artifacts to be 16 bit major, 16 bit minor and 24 bit build number. It found out there was another method in algod that makes the same calculation and uses the old 16+16+16 bit encoding.
Added tests to have s3 and algod calculations in sync
=> algod: adjust numeric version encoding

cmd/incorporate/incorporate.go, data/bookkeeping/genesis.go, data/bookkeeping/genesis_test.go, data/bookkeeping/msgp_gen.go, data/bookkeeping/msgp_gen_test.go, gen/generate.go, netdeploy/remote/deployedNetwork.go, node/follower_node_test.go, tools/block-generator/generator/generate.go
Alternate for #5447 that specifies the narrow set of fields allowed in the GenesisAllocation (the `"alloc"` part of the genesis.json file).
Existing tests updated, should pass
=> genesis: add GenesisAccountData type for use in GenesisAllocation

data/transactions/logic/eval.go, data/transactions/logic/evalStateful_test.go, data/transactions/logic/resources_test.go
Test: construct app that tries to modify a local state for which it only has access to the account, not the local state
=> AVM: proper cross product check for app put and del

cmd/updater/update.sh
Unhelpfully silent on where exactly the binary has been installed after running `make install`.
=> cmd/updater: add install directory to logging

go.mod, go.sum, tools/block-generator/go.mod, tools/block-generator/go.sum
Update go-codec to latest version. Mainly for consistency, the upstream change has extremely limited (or no) functional impact to go-algorand code at the API layer.
Existing unit tests.
=> encoding: Update go-codec version.

network/msgOfInterest.go, network/wsNetwork_test.go, network/wsPeer.go, network/wsPeer_test.go, protocol/tags.go, protocol/tags_test.go
Provides improved handling of MsgOfInterest websockets messages.
New tests added and old network tests updated.
=> network: improve MsgOfInterest message handling

.circleci/config.yml
For reducing build times, improving developer workflows and some optimizations, we are moving ARM64 builds to be solely nightly jobs. As a part of this PR, we separated the nightly runs into their own dedicated workflow for easier identification/cost management.
Run nightly builds - check running of triggered builds.
=> Build: Split nightly job into its own workflow. Remove ARM64 platform builds from our triggered/on commit builds.

daemon/algod/api/server/router.go, daemon/algod/api/server/router_test.go, daemon/algod/api/server/v2/test/handlers_test.go, daemon/algod/api/server/v2/test/helpers.go
Disable body limit middleware for admin endpoints.
Unit test.
=> api: Disable body limit middleware for admin endpoints.

Makefile, data/ledger_test.go, tools/network/dnssec/sort_test.go
1. Fix libsodium copying when re-running libsodium build. This caused `libsodium-fork/libsodium-fork` nested directory for example in this path: `./crypto/copies/darwin/amd64/libsodium-fork/libsodium-fork/src/libsodium/crypto_sign/ed25519/ref10`. This prevents from making changes in libsodium sources and compiling it with make like `make crypto/libs/darwin/amd64/lib/libsodium.a`.
2. Fix TestLedgerErrorValidate that fails when ledger flushes accounts between EnsureValidatedBlock and EnsureBlock for the same round. This causes very specific lookup error that comes from evaluator. Fix handles this specific error.
3. Fix TestSrvSort. Sometimes random generator draws values 0, 1 for uniform between [0, 204] and breaks test assumption. Retry up to 3 times in this case.
1. Tested manually - no …
=> tests: flaky tests fixes

.github/workflows/benchmarks.yml
I noticed that our benchmark job also runs all unit tests in the logic package.
Not only is this unnecessary, it also causes the benchmark job to fail if there are unrelated test failures in that package, which I found confusing during development. See here for an example: https://github.com/algorand/go-algorand/actions/runs/5340633710/jobs/9680667023
The solution is pretty simple, we just need to filter out all tests, which I've done by adding the `-run=^$` flag.
n/a
=> CI: Don't run tests during benchmark

ledger/ledger_test.go, rpcs/blockService_test.go
* In TestLedgerSPTrackerAfterReplay and TestVotersReloadFromDiskPassRecoveryPeriod got rid of calling a flusher that adds blocks on each flush. Sometimes it adds too much blocks and the trackers state changes beyond the test expectation.
* TestRedirectOnFullCapacity flaked because crypto.RandUint64() % 100 gave the same value twice in a row.
Passed locally. Unfortunately I was not able to repro these failures locally. [One](https://app.circleci.com/pipelines/github/algorand/go-algorand/15188/workflows/1a309f9e-471c-4907-b234-96cb80555519/jobs/243141) and [two](https://app.circleci.com/pipelines/github/algorand/go-algorand/15173/workflows/8a5cf2df-fe3d-44ae-a7d8-f41e3dd29063/jobs/243042/parallel-runs/19?filterBy=FAILED).
=> tests: fix flaky ledger stateproof and rpcs tests

cmd/algocfg/profileCommand.go
Update `algocfg` development profile to set:
```
MaxAcctLookback = 256
EnableTxnEvalTracer = true
```
Run `algocfg profile set development -d .` and confirm the expected config file is created.
=> algocfg: Add EnableTxnEvalTracer to algocfg development profile.

cmd/goal/clerk.go, test/scripts/e2e_subs/rawsend.sh
This PR should fix #4963, where `goal clerk rawsend` prints ptr to pending round rather than actual pending round.
An e2e-sh test for rawsend testing pending rounds + committed round should always be in ascending order.
=> Fix: goal clerk rawsend print pending round rather than ptr to round

cmd/algocfg/profileCommand.go
The default `CatchupBlockValidationMode` value is sufficient for participation.
=> algocfg: Remove block validation override from participation profile.

test/e2e-go/features/catchup/catchpointCatchup_test.go
Fixes nightly test failures for these tests. They are all running the same copy/pasted code so the fix is identical.
They were previously trying to use catchpoint catchup where the two nodes in the network were generating catchpoints, but the relay was not. This won't ever work since the ledger request always uses relays as its peer list and cycles through those.
It previously passed because the catchpoint service returned 200 on starting up, but with https://github.com/algorand/go-algorand/commit/e96d10497d04ff0b7472c209722f4d449985a71d we now do validation via a HEAD request before returning success on catchpoint service startup.
Tests pass locally--Nightly run is https://app.circleci.com/pipelines/github/algorand/go-algorand/15279/workflows/03a01ff7-4437-46c8-a723-3a4957966f94
=> tests: Fix catchpoint catchup tests to use relay for catchup

Dockerfile
Algod container v3.16.2-stable is taking 30s longer to start up than v3.15.1. This issue occurs when running the container as a root user. This PR sets the container to use a non-root user as in v3.15.1. 
A test has been ran from a forked branch with this change. 
`docker build -t algod-local --no-cache --build-arg BRANCH=v3.16.2 --build-arg URL=https://github.com/shiqizng/go-algorand.git .`
and the warm up time is down to 7s after the change. 
```
Starting algod-local:latest
Waiting for /v2/status ......
Took 7s
```
```
#!/bin/bash
export TOKEN=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
wait_for_status() {
echo -n "Waiting for /v2/status "
for i in {1..60}; do
curl --fail http://localhost:8080/v2/status --header "X-Algo-API-Token: $TOKEN" &>/dev/null
if [ $? -eq 0 …
```
=> enhancement: fix slow docker container start up

daemon/algod/api/server/lib/middlewares/cors.go
The algod REST API has some methods that require DELETE calls. In particular, I want to [delete a participation key](https://developer.algorand.org/docs/rest-apis/algod/#delete-v2participationparticipation-id). Making a DELETE call currently gives the following error:
```
Access to fetch at 'http://localhost:8080/v2/participation/{participation-id}' from origin 'http://localhost:3000' has been blocked by CORS policy: Method DELETE is not allowed by Access-Control-Allow-Methods in preflight response.
```
This PR adds the DELETE method to the the Access-Control-Allow-Methods so the DELETE endpoints will work.
I started the node, generated a key, and then deleted the key via the API to make sure it worked.
=> API: Allow DELETE calls

catchup/service.go
Importing blocks from a follower node lags behind in sandbox due to frequent timeouts when trying to sync the ledger. This PR changes the `syncNow` channel to a buffered channel to trigger resyncs properly in sandbox.
https://github.com/algorand/conduit/issues/102
Existing tests should suffice and checked on sandbox that conduit syncs quickly.
=> Fix: Use Buffered syncNow channel to correctly trigger sync in private networks

test/scripts/e2e_subs/rawsend.sh
Sorry, screwed up the e2e test for `rawsend.sh`:
- use `sort -nuC` then `$?` to check pending rounds in ascending order
- `echo "$PENDING_ROUNDS"` to keep breaklines, such that we can `tail -1` for last pending round
=> Bugfix: rawsend.sh nightly test failure fix

Dockerfile, docker/files/run/run.sh
The user is left out intentionally, see #5464 
This doesn't fix the root issue where it takes 30 seconds for kmd to start, but should allow it to startup without delay.
Test against rel/stable and this PR branch:
```
docker build \
-t wwinder/algod:exec \
--build-arg CHANNEL=stable \
--build-arg TARGETARCH=amd64 --no-cache \
.
```
```
docker run --rm -it \
-e START_KMD=1 \
--name algod-test-run \
-v (pwd)/docker_data_dir:/algod/data \
wwinder/algod:exec
```
on rel/stable it takes 30 seconds to startup due to kmd locking the pidfile, which is due to the user being managed incorrectly with exec and runuser.
With this branch it starts in less than 5 seconds.
=> docker: Start kmd in the background.

network/wsPeer.go
@cce caught an issue with a #5472 after it was merged. Here is the fix to ensure clean shutdown of the server since before we weren't checking that `OnRelease` callback isn't nil. 
Existing tests
=> bugfix: ensure blockservice callbacks are not nil

ledger/acctonline.go, ledger/ledger_test.go, ledger/spverificationtracker.go
The test failure caused by at least one additional block added into the ledger by `triggerTrackerFlush` that the test does not expect. Replaced `triggerTrackerFlush` by a version that triggers tracker flush without adding new blocks.
Failure [sample](https://app.circleci.com/pipelines/github/algorand/go-algorand/15299/workflows/d14dc96b-6a2c-4919-8b7b-f7ad2f6f8d4f/jobs/243989/parallel-runs/1?filterBy=FAILED):
```
spverificationtracker_test.go:169: 
Error Trace:	/opt/cibuild/project/ledger/spverificationtracker_test.go:169
/opt/cibuild/project/ledger/ledger_test.go:3152
Error:      	Received unexpected error:
requested state proof verification context not found for round 1024: memory lookup failed
Test:       	TestLedgerReloadStateProofVerificationTracker
```
Additionally fixed a data race …
=> tests: fix TestLedgerReloadStateProofVerificationTracker

network/wsNetwork_test.go
`TestSendMessageCallbacks` was trying to test both methods of draining but was probabilistic and would fail if a testPeer processed all of incoming messages before the 
```
require.NotZero(t, len(peer.sendBufferBulk))
```
got called. 
Since the drain functionality is tested explicitly already in `TestSendMessageCallbackDrain`. This makes `TestSendMessageCallbacks` only test the send functionality and explicitly ensures that messages did get processed and didn't accidentally get drained by the connection getting killed for a miscellaneous reason. 
Fixing an existing test to make it deterministic.
=> tests: make TestSendMessageCallbacks deterministic

daemon/algod/api/client/restClient.go, ledger/ledger.go, test/e2e-go/features/devmode/devmode_test.go, test/e2e-go/restAPI/restClient_test.go, test/testdata/nettemplates/DevModeTxnTracerNetwork.json
Addresses #5483 by assigning the Block Evaluator's tracer to be the tracer associated with the ledger on creation if there is no tracer passed in.
This lets devmode and private networks accumulate txn group deltas when the tracer is enabled on the ledger.
Added e2e test which retrieves txn group deltas while in dev mode.
=> tracer: Default to ledger tracer when starting new evaluator

Dockerfile, docker/README.md, docker/files/run/run.sh
Add support for configuring a private network with networking enabled, and for adding peers to a non-standard relay.
This is done by adding the following options:
* `GENESIS_ADDRESS` - allows a peer node to resolve `genesis.json` through the REST API.
* `GOSSIP_PORT` - sets the `NetAddress`, ensures `DisableNetworking` is false, and sets `IncomingConnectionsLimit` to 1000.
Additional tweaks:
* Add `ALGORAND_DATA` value sanity check. It should not be overridden.
* Switch from `runuser` to `gosu` to more closely follow conventions in other high quality docker images.
Manual testing:
1. Same tests used previously for kmd startup delay #5514.
2. The following docker-compose:
```
version: '3'
services:
algod-private:
#image: "algorand/algod:stable"
image: "wwinder/algod:peertest"
ports:
- …
```
=> docker: Additional private network options and container tweaks.

crypto/multisig.go, data/transactions/logic/backwardCompat_test.go, data/transactions/logic/debugger.go, data/transactions/logic/eval.go, data/transactions/logic/evalStateful_test.go, data/transactions/verify/txn.go, data/transactions/verify/txnBatch.go
I'm doing a larger bit of work to enable logicsig cost pooling and I found myself making these changes along the way. It's easier to review by extracting them into their own PR.  This does four things.
1. Introduces and uses:
```
func (msig MultisigSig) Signatures() int
```
for the several places we need to examine a MultiSig to count the number of sub signatures present.
2. Uses the pre-existing `func (s *Signature) Blank() bool` in many places.
3. Renames `EvalContext.runModeFlags` to simply `EvalContext.runMode` because it takes on a single value, it can't be, for example: `ModeSig | ModeApp`, it must be one or the other.
4. Improves tests by making it so that sample transactions created for versions below `rekeyingEnabledVerion` don't have their `RekeyAddress` set.
=> Chore: Small cleanups for clarity

cmd/goal/clerk.go, data/transactions/verify/txn.go, data/transactions/verify/txn_test.go
This eliminates an initial *SIgnedTransaction argument that is redundant with the later combination of group index and groupCtx argument. That way, callers can't mess it up.
=> Chore: remove a redundant argument to maintain single source of truth

ledger/catchupaccessor.go, ledger/store/trackerdb/sqlitedriver/sqlitedriver.go, ledger/store/trackerdb/store.go
#5451 introduced a bug, the catchpoint merkle tree generation needs to be kept on a separate readonly connection for it to make forward progress. 
This PR add the required method to the `Reader` interface for the store, so it becomes available via the `Snapshot` scope. 
There is an implicit contract that the snapshot is going through a separate read-only handle to the sqlite db. 
If this were ever to change, this will break again.
=> fix: catchpoint pending hashes locking

test/e2e-go/features/catchup/catchpointCatchup_test.go, test/e2e-go/features/catchup/stateproofsCatchup_test.go
Enhance the wait for catchpoint by looping instead of the timer to avoid timer runout without looping under stressed environments.
=> test: Replace timer with counter loop in TestNodeTxHandlerRestart

protocol/codec_tester.go
Fix for codec tester that disregard TxType allocbound declaration in `protocol/txntype.go` when called on `data/transactions`'s `Transaction` type.
```
--- FAIL: TestRandomizedEncodingTransaction (0.09s)
codec_tester.go:480: 
Error Trace:	/go-algorand/data/transactions/codec_tester.go:480
/go-algorand/data/transactions/msgp_gen_test.go:999
Error:      	Received unexpected error:
msgp: length overflow: 60 > 7 at Type
Test:       	TestRandomizedEncodingTransaction
FAIL
FAIL	github.com/algorand/go-algorand/data/transactions	0.318s
```
Existing tests passing now
=> tests: fix coder tester for TxType bound

installer/debian/algorand-devtools/conffiles
We updated the Ubuntu image we use to build the debian package, and it has tighter tolerances. As a result, debian packaging now fails because of an extraneous newline in the algorand-devtools conffile.
Successfully ran packaging with the newline removed.
=> CICD: Fix debian package error

.circleci/config.yml
Update the build image and orbs in CircleCI. 
The update to the ubuntu image also will update the docker installation. This will fix the amd64_upload_binaries step in CircleCI's nightly_build_and_test workflow. We had observed failures in `apt-get update` in rel/beta and rel/nightly workflows recently (after #5529 ubuntu build upgrades) and we believe it is related to the docker version installed in the CircleCi ubuntu image.
- https://app.circleci.com/pipelines/github/algorand/go-algorand/15444/workflows/c38634af-054b-4a98-b938-3abdcd9022a2
- https://app.circleci.com/pipelines/github/algorand/go-algorand/15447/workflows/ea9fb152-1868-4e8a-bbf4-137bc1b529b5
Tested on a separate workflow here (to run nightly): https://app.circleci.com/pipelines/github/algorand/go-algorand/15462/workflows/69 …
=> CICD: Update ubuntu circleci image and orbs

shared/pingpong/pingpong.go, test/heapwatch/client_ram_report.py, test/heapwatch/plot_crr_csv.py
Current heapwatch tooling uses only pprof heap profile for memory usage charts and reports although there are runtime metrics collected and available.
1. client_ram_report.py uses both heap and metrics
2. plot_crr_csv.py renders charts using all the data from (1)
3. additionally excluded account lookups in pinpong for pure payment tests
Tested locally, chart sample attached. The solid line is the old pprof data, all non-solid lines are new from runtime metrics.
=> perf tests: use metrics for memory usage charts

.circleci/config.yml, .github/workflows/pr-type-category.yml, Dockerfile, Makefile, README.md, docker/build/Dockerfile, docker/build/Dockerfile-deploy, docker/build/aptly.Dockerfile, docker/build/cicd.ubuntu.Dockerfile, docker/build/docker.ubuntu.Dockerfile, docker/build/releases-page.Dockerfile, scripts/release/README.md, scripts/release/common/docker/setup.Dockerfile
With dynamic libraries, building on older OSes would be supported, but not vice versa. As we were updating OSes, ARM64 builds started failing due to dynamic builds on newer platforms. I.e., if you built a binary on ubuntu. 22.04, it would not run on 20.04, due to lack of static linking in ARM64.
This fix does three things:
- Expand static builds outside of CentOS
- Revert build environments to 20.04
- Cherry-pick in the orb/container upgrade for CI
Ubuntu 22.04 showed some downstream incompatibilities when building RPMs, so is rolled back for now.
An additional change is to bump the required labels github action version, but this is separate from the above fixes.
Built command line, to verify it would build a static binary.
=> CICD: downgrade ubuntu to 20.04 and ensure ARM64 binaries are built static

catchup/catchpointService_test.go, cmd/catchpointdump/file.go, components/mocks/mockCatchpointCatchupAccessor.go, ledger/catchupaccessor.go, rpcs/ledgerService.go
1. catchpointdump now prints balances root and spver hashes
2. Improved logging in LedgerService.ServeHTTP
=> tools: let catchpointdump to calculate and print data hashes

ledger/catchpointtracker.go, ledger/catchpointtracker_test.go, ledger/catchpointwriter.go, ledger/catchpointwriter_test.go
From #5574:
1. stateproof verification snapshot logic does not handle `CatchpointTracking=1` properly - its hash calculation is a side effect of writing spver data chunk into catchpoint file. Fixed that by calculating hash similarly to balance hash on demand.
1. Modified unit test `TestCatchpointReproducibleLabels` for CatchpointTracking=1
2. Tested locally
=> ledger: use single SP verification hash/data query for catchpoint tracking & generation

cmd/goal/clerk.go, test/scripts/e2e_client_runner.py, test/scripts/e2e_subs/e2e-app-simulate.sh, test/scripts/e2e_subs/tealprogs/stack-scratch.teal
#5563 forgot to add support for goal to return scratch slot changes in exec trace, this is an enhancement.
e2e script test for goal to return stack and scratch changes in exec trace.
=> goal: support simulate scratch in exec trace

catchup/service.go, crypto/curve25519_test.go
hello Algorand team
I replaced string concatenation with a builder, that's faster and more efficient, concatenation with `+` is also too expensive.
=> chore: use string builder instead of string concatenation in catchup service

docker/Dockerfile, docker/build/Dockerfile, docker/build/Dockerfile-deploy, docker/build/cicd.alpine.Dockerfile, docker/build/cicd.centos.Dockerfile, docker/build/cicd.centos8.Dockerfile, docker/build/cicd.ubuntu.Dockerfile, scripts/check_deps.sh, scripts/release/common/docker/centos.Dockerfile, scripts/release/common/docker/centos8.Dockerfile, scripts/release/common/setup.sh
I was just talking with @onetechnical about how our build containers install sqlite3 unnecessarily, since the go-sqlite3 package contains its own version-tracked distribution of sqlite's source code. The only reason we add it to scripts like configure_dev.sh is for usage in the CLI for development and debugging, but it is not a release or build-time dependency, so I am removing it in this PR.
Existing tests and builds should succeed as before.
=> build: remove sqlite from release configurations

ledger/catchpointtracker.go
#5579 was merged a few minutes before I had a chance to push this commit to address @AlgoAxel's PR feedback in https://github.com/algorand/go-algorand/pull/5579#discussion_r1269790619 about using read vs write scopes for getting the SP verification context. This is that change
=> catchpoint: use read connection for data retrieval for spver hash calculation

ledger/catchpointtracker.go, ledger/catchpointwriter.go, ledger/store/trackerdb/sqlitedriver/catchpoint.go, ledger/store/trackerdb/sqlitedriver/sqlitedriver.go, ledger/store/trackerdb/store.go
#5451 introduced a bug, catchpoint reads need to be kept on a separate readonly connection for the node to make forward progress.
This PR adds the required method to the Reader interface for the store, so it becomes available via the Snapshot scope.
There is an implicit contract that the snapshot is going through a separate read-only handle to the sqlite db.
If this were ever to change, this will break again.
=> ledger: move MakeCatchpointReader back to the Reader interface

ledger/store/trackerdb/generickv/catchpoint.go, ledger/store/trackerdb/generickv/msgp_gen.go, ledger/store/trackerdb/generickv/onlineaccounts_reader.go, ledger/store/trackerdb/generickv/reader.go, ledger/store/trackerdb/testsuite/accounts_kv_test.go, ledger/store/trackerdb/testsuite/onlineaccounts_kv_test.go, ledger/store/trackerdb/testsuite/utils_test.go
Quick fix of some missing interface changes that were in master but not on PR #5488 
=> ledger: fixes to store interface after kv merge

cmd/goal/clerk.go, test/scripts/e2e_subs/e2e-app-simulate.sh
In a discussion, we found it helpful to define a handy "activate all" option for exec trace in `goal clerk simulate`, this PR provides a straight-forward implementation.
modified a line in e2e test with the new option, should go through with stack changes and scratch slot changes.
=> goal: `--all-trace-options` keeps track of everything in exec trace

tools/block-generator/generator/generate.go, tools/block-generator/runner/run.go, tools/block-generator/runner/runner.go
Optimizing for usage patterns. It is sometimes useful to run the same suite multiple times to account for transient DB behavior.
I'm using several scripts to run this tool. There may be other features from those scripts that should be migrated, but this seemed like a good start.
There are also some minor changes to logging to remove constant debug output and optimize for general usage.
1) Start a postgres container.
2) Run the command:
```
./block-generator runner \
--conduit-binary /home/will/algorand/conduit/cmd/conduit/conduit \
--report-directory reports \
--test-duration 5s \
--conduit-log-level trace \
--postgres-connection-string "host=localhost user=algorand password=algorand dbname=generator_db port=15432 sslmode=disable" \
--scenario generator/test_scenario.yml \
--reset-db …
```
=> tools: option to run test multiple times.

netdeploy/network.go, netdeploy/networkTemplate.go, netdeploy/networkTemplates_test.go, netdeploy/network_test.go, netdeploy/remote/nodeConfig.go, test/testdata/nettemplates/FiveNodesTwoRelays.json
Changes to netdeploy to control local net topologies. Motivation is allow some networking tests on a local machine without spinning up a cluster.
Implementation Notes:
1. Added `PeerList` property into local net templates
2. Replaced `TemplateFile` with actual `Template` in deployed template `network.json` since the former was not used.
3. Supported `PeerList` in network template start (`goal network -r xxx start`)
Added some unit test. Tested manually with `FiveNodesTwoRelays.json` templates that forces NPN to connect a single relay, and one of part nodes to connect to another single relay.
```sh
$ ps | grep algod
30090 ttys001    0:02.75 ~/go/bin/algod -d ~/networks/five-test/Relay1
30091 ttys001    0:02.91 ~/go/bin/algod -d ~/networks/five-test/Relay2 -p http://127.0.0.1:63606
30092 …
```
=> netdeploy: allow simple local net topologies

.circleci/config.yml, scripts/configure_dev.sh
CircleCI's amd64 machine are missing certain packages when we upgraded to 14.2.0. This change removes the conditional and will install and upgrade when we run the jobs on mac os machines each time.
During the mac_amd64 upgrade from xcode 13.2.1 to 14.2.0 (#5590 ), we had installed all of the packages by removing this conditional and running it once before reverting back the change. It seems to have cached the installed packages for a few days (7 days). However after a week we see this error `automake is required, but wasn't found on this system` again in our nightly builds.
The behavior seen in #2608 no longer seems to be true for CircleCI's xcode 14.2.0 machine.
Test that mac_amd64 build succeeds:
https://app.circleci.com/pipelines/github/algorand/go-algorand/15737/workflows/ea33bcc1-7654 …
=> CICD: Macos dependencies

node/msgp_gen.go, node/netprio.go, node/netprio_test.go, protocol/tags.go
The `netprioResponse.Nonce` field is a base64 encoded string instead of a byte array/slice and therefore we have to use the correct base64 encoded max size of 44. 
=> node: use correct allocbound on netprioResponse Nonce field

ledger/acctupdates.go
1. Take a state snapshot for a single iteration (the first part of the for {} loop in lookupWithoutRewards) - dbRound, deltas, offset, rewards, inDeltas check. 
2. make the nested loop over deltas lock free.
say au.deltas has 10 elements that is backed by some array underneath. e make local `deltas = au.deltas[0:len(au.deltas)]`, pointing to the same backing array. Then there are two options:
1. when receiving a new block => add element
- if backing array has space, it is not reallocated, just appended, our `deltas` keeps pointing on it
- if not enough space, then realloc for au.deltas but our `deltas` keeps pointing to the old backing array
2. when committing => remove elements
- removal op is slicing, so `au.deltas` keeps pointing to the same backing array but to the right subset, our …
=> ledger: increase locks granularity in lookupWithoutRewards

.github/workflows/tools.yml, tools/block-generator/go.mod, tools/x-repo-types/Makefile, tools/x-repo-types/go.mod, tools/x-repo-types/xrt.go
The workflow file for the GA tools job was too narrow. It ought to run on every PR against `master`.
Now that it's running it can detect problems on changes to ConsensusParams [as here](https://github.com/algorand/go-algorand/actions/runs/5719301732/job/15496902979#step:8:332).
After the SDK's ConsensusParams were fixed the [test is passing](https://github.com/algorand/go-algorand/actions/runs/5720880973/job/15501567219?pr=5621) as well.
=> tools: test on CI regardless of modded file

tools/block-generator/runner/run.go, tools/block-generator/runner/template/conduit.yml.tmpl
Generator seemed to hang for a test I was running. The report appears to have been created but for some reason the next job did not start. The goal of this additional lifecycle logging is to provide more information to the user about what is happening.
=> tools: additional generator lifecycle logging.

node/node.go, util/metrics/metrics.go
Signed transactions intended for broadcast from a node (via the REST API) go through this broadcastSignedTxGroup method for validation first. This adds counters to track how often they succeed vs fail.
=> metrics: add counters to broadcastSignedTxGroup

libgoal/libgoal.go, libgoal/libgoal_test.go, test/e2e-go/features/transactions/asset_test.go, test/e2e-go/features/transactions/lease_test.go, test/scripts/e2e_subs/e2e-teal.sh, test/scripts/e2e_subs/limit-swap-test.sh
Pingpong testing on large network discovered an issue when a node sends transactions that are too early to its neighbors. This happens when a node is few milliseconds ahead and immediately sends transactions.
There are some logs from NPN running pingpong and its sibling relays. Note the `EnsureBlock` timestamp and transaction sending timestamp.
NPN:
>{"Context":"Agreement","Hash":"M6PF4TJ3USEN2DT5VNORHIQX23DBF53QQS5YZNAVBRBQMNJMDNQA","ObjectPeriod":0,"ObjectRound":0,"ObjectStep":0,"Period":0,"Round":652,"S
ender":"PPFBOHV7JM3VKBJGXCLNFD6LIDQG3GRF6WCKS3TZ3L4D5CEP2AUNCC7SEU","Step":0,"Type":"RoundStart","Weight":0,"WeightTotal":0,"file":"actions.go","function":"gi
thub.com/algorand/go-algorand/agreement.ensureAction.do","level":"info","line":262,"msg":"finished round …
=> libgoal: set FirstValid to LastRound to prevent early tnxs

test/e2e-go/features/transactions/asset_test.go
[Nightly build](https://app.circleci.com/pipelines/github/algorand/go-algorand/15852/workflows/d6ac20a3-051a-4b9b-9c70-74c4597b5c70/jobs/248321?invite=true#step-114-1184) discovered one missing condition after libgoal  fixes in https://github.com/algorand/go-algorand/pull/5622
This is a test fix after libgoal's FirstValid calculation adjustment.
=> tests: fix e2e TestAssetValidRounds after libgoal adjustment

agreement/fuzzer/networkFacade_test.go, agreement/gossip/network_test.go, network/msgCompressor.go, network/multiplexer.go, network/multiplexer_test.go, network/netidentity.go, network/netidentity_test.go, network/wsNetwork.go, network/wsNetwork_test.go, network/wsPeer.go
This removes some unused interface methods on GossipNode, and extracts some functionality from WebsocketNetwork into two new types (msgHandler, msgBroadcaster) to make them more available for re-use.
=> network: make GossipNode more independent from wsNetwork implementation

tools/block-generator/runner/run.go
I was noticing that the conduit process was not always being terminated. This makes the termination more reliable by:
1) Using a `CommandContext` to do the heavy lifting.
2) Setting a `WaitDelay` which should cause wait to timeout and trigger a `Kill` if a graceful shutdown takes too long.
Also added a couple more lifecycle log messages.
=> tools: use CommandContext to cancel conduit process.

network/phonebook.go, network/phonebook_test.go, network/wsNetwork.go, network/wsNetwork_test.go
We never actually call ExtendPeerList anywhere. When we refresh the SRV list periodically it just fully replaces the peer list.
grep'ing ExtendPeerList shows nothing. Also existing tests should pass.
=> phonebook: Persist initial phonebook peers; remove unused ExtendPeerList

ledger/acctupdates.go, ledger/acctupdates_test.go, ledger/tracker.go, ledger/tracker_test.go
`accountUpdatesLedgerEvaluator` used to only implement a couple lookup methods from `accountUpdates` but now it uses txtail and online accounts trackers. Moved to tracker.go where it is used.
=> ledger: move accountUpdatesLedgerEvaluator to tracker.go

Makefile
This change avoids running (and printing) the `mkdir` and `touch` commands for creating `$GOCACHE` every time `make` is run.  This makes the output less noisy and easier to read.
=> build: slightly more readable "make" output

tools/block-generator/generator/daemon.go, tools/block-generator/generator/generate.go, tools/block-generator/generator/make_transactions.go, tools/block-generator/generator/server.go
Observed that the block generator was taking 3-10 seconds to generate app-heavy scenarios. After inspecting the code I found that the teal program was being compiled over and over again.
Added timing instrumentation to measure the performance impact with the `stress.50000.yml` benchmark scenario.
The generation time was reduced from 7 seconds to 250ms.
Code review video: https://youtu.be/JlYhksWUBKU
=> tools: precompile block-generator teal code

ledger/acctonline_test.go, ledger/acctupdates_test.go, ledger/catchpointfilewriter_test.go, ledger/voters_test.go
Fixed data race from [this build](https://app.circleci.com/pipelines/github/algorand/go-algorand/15760/workflows/0e2eb8cb-cee7-4c76-9bc9-2ff3a244d6ec/jobs/247635?invite=true#step-114-6326):
```
WARNING: DATA RACE
Read at 0x00c000144900 by goroutine 3010:
runtime.mapaccess1()
/opt/cibuild/.gimme/versions/go1.20.5.linux.amd64/src/runtime/map.go:395 +0x0
github.com/algorand/go-algorand/ledger.(*lruAccounts).read()
/opt/cibuild/project/ledger/lruaccts.go:66 +0x97
github.com/algorand/go-algorand/ledger.makeCompactAccountDeltas()
/opt/cibuild/project/ledger/acctdeltas.go:453 +0x878
github.com/algorand/go-algorand/ledger.(*accountUpdates).prepareCommit()
/opt/cibuild/project/ledger/acctupdates.go:1555 +0x688
github.com/algorand/go-algorand/ledger.(*trackerRegistry).commitRound() …
```
=> tests: fix close - commit data race in tracker tests

.circleci/config.yml, .github/workflows/reviewdog.yml, Dockerfile, Makefile, scripts/get_golang_version.sh
1. use go1.20.6
2. revert go-expermiments disabling
Local runs showed no perf difference.
=> build: upgrade to go1.20.6

network/wsNetwork_test.go
Potential quick fix for instability on MergePrimarySecondaryDNS PartialOverlap test.
Ran test several times.
=> Build: Remove n-algorand from wsnetwork partial overlap test.

catchup/fetcher_test.go, catchup/service.go, catchup/service_test.go, ledger/bulletin.go, ledger/ledger.go
This PR simplifies the catchup code for managing a pipeline of block-fetching workers.  Catchup should work in more-or-less the same way as before, but the code itself should be easier to read and modify.
=> catchup: cleanup pipelinedFetch

network/wsNetwork_test.go
This test is flaky (see failed nightly run in https://app.circleci.com/pipelines/github/algorand/go-algorand/16122/workflows/feaae371-cb4f-49a5-becc-f46f2ef422d5/jobs/250292). 
I've removed the assertion that the generated lists would have no duplicates--clearly the rapid test framework can and will generate some duplicates and it really doesn't matter to the logic of the test if it does.
Tests pass--haven't seen other parts of the test be flaky as far as I know.
=> chore: Remove faulty assertion

catchup/service.go, catchup/service_test.go
The catchup code had a race where, upon seeing an unsupported block in the future, the catchup logic would cancel the current pipeline of block fetches.  Depending on the timing, this might either make some progress or not fetch any blocks at all.
The new logic is more deterministic: it tries to always fetch all blocks up until the last supported block, and when the ledger reaches the last supported block, the catchup service stops.
=> catchup: make unsupported block handling more deterministic

ledger/acctdeltas.go
Pulling a error checking bugfix from #5677 introduced #5451 by me.
Existing tests
=> ledger: fix error condition leaked from KV-related refactoring

test/framework/fixtures/libgoalFixture.go
Looking into these e2e tests failures ([one](https://app.circleci.com/pipelines/github/algorand/go-algorand/16209/workflows/a2f4b57c-3d92-4f01-978a-f974162fa554/jobs/250872), [two](https://app.circleci.com/pipelines/github/algorand/go-algorand/16209/workflows/a2f4b57c-3d92-4f01-978a-f974162fa554/jobs/250872), [three](https://app.circleci.com/pipelines/github/algorand/go-algorand/16209/workflows/a2f4b57c-3d92-4f01-978a-f974162fa554/jobs/250869/parallel-runs/1?filterBy=FAILED)) made me think we have some race condition on node termination caught by race detector. These changes allows to see panic stacktrace and fix. 
This is a test harness fix.
=> tests: log algod-err and algod-out on e2e failure

ledger/store/trackerdb/pebbledbdriver/pebbledriver.go, ledger/store/trackerdb/pebbledbdriver/pebbledriver_arm.go
pebble is known not compiling on 32-bit systems - see https://github.com/cockroachdb/pebble/pull/2120
This PR disables pebble driver on arm32
Build at arm32 docker, the algod compilation errors gone.
=> build: disable pebbledb on arm32

config/localTemplate.go, config/local_defaults.go, data/txHandler_test.go, installer/config.json.example, test/testdata/configs/config-v30.json
Enable elastic rate limiter by default in go-algorand configuration.
Existing tests run and pass.
=> txHandler: Enable ERL by default in configuration.

tools/block-generator/generator/generate.go, tools/block-generator/generator/generator_types.go, tools/block-generator/runner/reporting_test.go, tools/block-generator/runner/run.go
Adding the initial round to the block generator so that the conduit benchmark can take that into consideration when loading data from a snapshot.
Update unit test.
=> tools: add block-generator initial round to report.

tools/block-generator/runner/run.go, tools/block-generator/runner/runner.go
New block generator option to delay the start of a test. After noticing large variation in snapshot test performance results, we wonder if there could be some postgres processes from earlier tests effecting latter tests. This option gives us a simple way to test that by putting a delay between runs.
=> tools: block-generator option to delay before running scenario.

test/scripts/e2e_go_tests.sh
It appears this [PR](https://github.com/algorand/go-algorand/pull/5625/files#diff-e0af12871616aaca898813b50e2521dc9dac6938c150fbd9f371c971f893f203R50) incidentally disabled `expect` tests.
Fixed bash condition to restore.
[Bash ref](https://www.gnu.org/software/bash/manual/html_node/Bash-Conditional-Expressions.html):
```
-n string
string
True if the length of string is non-zero.
-z string
True if the length of string is zero.
```
Checked condition in a shell. `RUN_EXPECT` is set to `FALSE` when empty, and not modified when `TRUE`.
=> build: resume/fix ci expect tests

agreement/actions.go, agreement/msgp_gen.go, agreement/player.go
Following on #5691, this adds the dynamicFilterTimeout value for the round to the BlockAcceptedEvent.
=> telemetry: add dynamicFilterTimeout to BlockAcceptedEvent

.circleci/config.yml, node/node.go
Reverts algorand/go-algorand#5668
Tests are occasionally failing, and we theorize that the test succeeds, but the shutdown is timing out. Via Pavel:
"It could the following based on the termination sequence in server.go
```
s.node.Stop()
err := server.Shutdown(context.Background())
```
node.Stop stops all services first but there could be some active network connections that handled later by server.Shutdown so I suspect some network requests do not allow ledger to be closed or, another way around, server.Shutdown waits longer than 30s after ledger shutdown."
Ran nightly tests to verify.
https://app.circleci.com/pipelines/github/algorand/go-algorand/16377/workflows/0e0fceb7-111a-492d-9fa0-b0df27285afe
=> Revert "Ledger: Close the ledger at node shutdown"

crypto/merklesignature/persistentMerkleSignatureScheme.go, data/transactions/signedtxn.go, data/transactions/teal.go, data/transactions/transaction.go, protocol/codec.go
While working on reducing memory requirements I found about 12% of allocations come from `protocol.PutEncodingBuf`( see the picture below). This happens when a slice object (pointer to data, len, cap) gets reallocated to the heap.
Fix is to wrap a byte slice in struct and make `pool.New()` to return a pointer to it. In this case the wrapping struct is allocated on heap, so returning pointer into a pool fixes the issue.
I also noticed that majority of the calls come from `Transaction.ID` and made a separate pool for it (commit 1).
As a result total number of allocations decreased by **10%** 673713259 (master) vs 609152614 (feature)
Run bunch of local tests (2 nodes, target tps=3000) for master vs commit 1 (separate pool for transaction id) vs the entire PR (global `protocol.PutEncodingBuf` …
=> encoding: eliminate unnecessary allocations

catchup/universalFetcher_test.go, config/localTemplate.go, config/local_defaults.go, installer/config.json.example, network/wsNetwork_test.go, rpcs/blockService_test.go, test/testdata/configs/config-v31.json
Given there are no archival server records on mainnet/testnet, repeatedly doing queries for them (and adding warn messages to logs) makes little sense at the moment.
Existing tests pass.
=> Feature: Disable EnableBlockServiceFallbackToArchiver by default.

crypto/merklearray/proof.go, crypto/merklearray/proof_test.go, daemon/algod/api/server/v2/test/handlers_test.go, test/framework/fixtures/libgoalFixture.go
No need to explicitly specify tree depth for merklearray proofs of a single leaf node, because the tree depth is exactly the number of sibling hashes in the proof.
This allows simplifying the format for sending single-leaf merklearray proofs, sending just the proofBytes []byte, and not having to send along an extra treeDepth.
The current algod API for fetching a proof still sends the tree depth along, for any clients that might care about it, but future APIs won't need to pass treeDepth.
=> merklearray: simplify single-leaf proofs

network/p2p/p2p.go, network/p2p/p2p_test.go
Make P2P listenAddress and more importantly the port configurable via `config.NetAddress`. This is required for algonet functioning to make sure that the services start using expected ports. 
Added a new test and existing tests should pass
=> p2p: Make p2p listen address configurable via config.NetAddress

test/e2e-go/features/catchup/basicCatchup_test.go
This test creates 4 networks while it is running, so removing the call to t.Parallel should help it finish quicker, and splitting up the subtests with t.Run makes it easier to see which test network is running.
Existing test should pass
=> tests: update TestCatchupOverGossip to be less parallel and use sub-tests

test/e2e-go/features/p2p/p2p_basic_test.go
~~Currently the `TestP2PThreeNodesEvenDist` fails pretty regularly. The theory here is that part of the problem is that P2P stream connections take longer to setup than the wsNetwork and that because of that nodes get into a bad state with consensus trying to move too quickly. The errors on the CI runs for these tests indicate that nodes are trying to catchup via gossip protocol but these attempts fail on timeouts.~~
After further investigation it looks like this behavior is not specific to P2P but happens on the websocket network as well. 50~60% of the time the test takes significantly longer locally but still succeeds. The failure on the CircleCI side is likely just different resourcing leading to slower execution and slower recovery from the bad state that nodes get into. Removing the …
=> p2p: remove TestP2PThreeNodesEvenDist

ledger/acctonline_test.go, ledger/acctupdates_test.go, ledger/catchpointtracker_test.go
Fix data race seen in [this build](https://app.circleci.com/pipelines/github/algorand/go-algorand/16714/workflows/3b31ab65-73d5-4982-a2aa-48d458399bf3/jobs/254613)
Existing ledger unit tests passed
=> tests: fix a rare data race in staling tracker tests

test/e2e-go/restAPI/simulate/simulateRestAPI_test.go
TestSimulateStartRound [flaked](https://circleci.com/api/v1.1/project/github/algorand/go-algorand/254584/output/114/3?file=true&allocation-id=64fe692aeac3ce51df71bf1a-3-build%2FABCDEFGH) because it expects txn simulated execution failed at round 1 after catching up to round 7 but time to time ledger is delayed flushing most recent deltas and it has all the state at round 1 needed for simulated execution so the simulate succeeds.
Use `Eventually` to retry few times and give the ledger change to flush.
=> tests: fix flaky simulate test

scripts/release/mule/deploy/releases_page/html.tpl
We've added a new GPG key for CI build binaries, so adding mention of this. Also removed message about old binary.
Executed and updated releases page.
=> DevOps: update releases page GPG key mentions

cmd/goal/network.go, docker/README.md, docker/files/run/run.sh
Docker changes:
* Detect participation keys at the /etc/algorand/keys directory.
* If a private network is going to be started, use that directory if there are keys.
* README updates describing how the feature is used.
https://github.com/algorand/go-algorand/issues/5699
Pregenerate keys with `goal`:
`goal network pregen -t some_template.json -p pregen`
Pregenerate keys with `docker`:
```bash
docker run --rm -it \
-v /path/to/your/template.json:/etc/algorand/template.json \
-v $(pwd)/pregen:/algod/pregen \
--entrypoint "/node/bin/goal" \
algorand/algod:nightly network pregen -t /etc/algorand/template.json -p /algod/pregen
```
Build the image (from root dir):
```bash
docker build \
-t wwinder/algod:pregen-test  \
--build-arg CHANNEL=nightly \
--build-arg TARGETARCH=amd64 --no-cache \
. 
``` …
=> docker: Support pregenerated keys in docker private networks

scripts/release/mule/deploy/releases_page/generate_releases_page.py, scripts/release/mule/deploy/rpm/deploy.sh
Links on the releases page are meant to pull from the main repository. However, due to pagination, files were not getting assigned.
This PR fixes this by adding pagination to the file listing from S3. It also syncs signatures for RPMs to the repository.
Ran release page generator and verified it would update links properly.
=> DevOps: fix releases page links

tools/network/dnssec/config_windows.go
Fixes garbage collection on Windows by removing calls to SetGCPercent and replacing the GC stop with a native buffer allocation (LocalAlloc / LocalFree) for fixedInfoWithOverlay.
The previously used code didn't work well on Windows, causing the GC to stop from collecting. The SetGCPercent(pct) didn't restore the GC.
A minimal program that can be used to reproduce the issue with SetGCPercent on Windows:
```go
package main
import "runtime/debug"
func test() {
pct := debug.SetGCPercent(-1)
defer debug.SetGCPercent(pct)
var r [][]byte
for i := 0; i < 10; i++ {
r = append(r, make([]byte, 1024))
}
}
func main() {
for {
test()
}
}
```
=> windows: Fix GC

data/transactions/logic/Makefile
This just changes the way we update a sibling repo when specs here change.
The codegen test will confirm nothing was changed in our generated files.
=> Specs: Change spec generation for Foundation to handle _v*.md

config/localTemplate.go
Updating comments on `config.Local` so that they can be used to generate the [node configuration page](https://developer.algorand.org/docs/run-a-node/reference/config/#algod-configuration-settings). Here I've mainly chosen the best content from the developer portal and the existing comments.
Followup PRs should be made:
* Better and more consistent formatting. Especially in cases where multiple options are listed.
* Remove unused settings. I noticed at least 5 which don't seem to be used. I only marked the ones which had minimal or missing documentation.
* Generally going through the entire list to clarify and update documentation as needed.
Manually ran the [config_json_gen](https://github.com/algorand/docs/tree/staging/scripts/config_json_gen) and verified that the generated markdown …
=> docs: Update node config comments so that they can be used for doc generation.

cmd/goal/node.go, daemon/algod/api/client/restClient.go, libgoal/libgoal.go, test/e2e-go/cli/goal/expect/goalExpectCommon.exp, test/e2e-go/features/catchup/catchpointCatchup_test.go, test/e2e-go/features/catchup/stateproofsCatchup_test.go
Add new parameter from #5752 to `goal node catchup`.
Minor refactoring to command to try and simplify the operations. In particular things I didn't like:
* referencing `args[0]` without saying anywhere that it was an optional positional argument.
* the `catchup` function references global abort flag, which is also referenced in the cobra function.
* multiple client objects created.
Manually tested a bunch of permutations:
```
goal node catchup
goal node catchup -x
goal node catchup --force
goal node catchup --force -i 100000000
goal node catchup -i 100000000
goal node catchup -i 1000
goal node catchup -i 1000 --force
goal node catchup --force 
goal node catchup 29900000#K35DLY2QEMR6LPL6GOM5XR4ZVDYBNQ34TOWZVOPPL6PHSQGJJXHA
goal node catchup -i 100000000 …
```
=> goal: Add initialize option to 'goal node catchup'.

network/wsNetwork_test.go, tools/network/dnssec/config_windows.go
TestMergePrimarySecondaryRelayAddressListsPartialOverlap inconsistently passes on the build server - it seems there are some random DNS combos that are not compatible with our filtering. Given we have control over the SRV record naming convention, rather than debug these corner cases the test has been modified to better reflect patterns we actively support.
Ran TestMergePrimarySecondaryRelayAddressListsPartialOverlap several consecutive times locally - Rapid has been removed for this test so it also runs much faster.
=> Tests: Address flakiness with TestMergePrimarySecondaryRelayAddressListsPartialOverlap 

go.mod, go.sum, tools/block-generator/go.mod, tools/block-generator/go.sum
Apply performance fix from https://github.com/algorand/go-deadlock/pull/2
TL;DR: no noticeable TPS improvement but for sure better memory utilization.
Run s1s with `--numapp 10 --appprogops 200  --refresh 1800 --numaccounts 500 --quiet` (the same as apps medium periodic).
Master
```
relay summary: 4850.01 TPS, 3.23s/block, tx 26.4MB/s, rx 17.6MB/s
```
| single | all |
| ---- | ---- |
| ![image](https://github.com/algorand/go-algorand/assets/65323360/87046efb-58eb-48d7-93c0-adaa1d53d900) | ![image](https://github.com/algorand/go-algorand/assets/65323360/7ff5b650-ab2d-4d32-bf56-3aa37e6d5429) |
Feature
```
relay summary: 4888.18 TPS, 3.23s/block, tx 26.7MB/s, rx 17.8MB/s
```
| single | all |
| ---- | ---- |
| ![image](https://github.com/algorand/go-algorand/assets/65323360/70c0fd56-a8d7-4d92- …
=> perf: upgrade go-deadlock

test/heapwatch/client_ram_report.py, test/heapwatch/plot_crr_csv.py
heapWatch's metric renderer does not work well for multiple nodes. This slightly improves heap chart rendering.
Also fixed IP to nicknames resolution.
Not super great but better.
| Before | After |
| ------  | ----- |
| ![image](https://github.com/algorand/go-algorand/assets/65323360/49072c6f-bf64-45a0-b967-44e9deb82453) | ![image](https://github.com/algorand/go-algorand/assets/65323360/3fe4bb54-a6b6-4e9d-a694-1a02f7566870) |
=> tools: better heap data rendering

config/localTemplate.go, config/local_defaults.go, installer/config.json.example, ledger/ledger.go, ledger/ledger_test.go, test/testdata/configs/config-v31.json
There is no way to request a node to store more blocks if it is not archival. This adds a MaxBlockHistoryLookback similar to MaxAcctLookback config option.
No tests yet
=> config: Add MaxBlockHistoryLookback option

docker/files/run/run.sh
Fixes #5732 
The default node exporter path is `./node_exporter`. The docker container puts binaries on the path instead of using a fixed location, so this change simply fills in the absolute path.
Using the following `config.json`:
```
{
"EnableMetricReporting": true
}
```
1. Control test:
```
docker run --rm -it \
-p 9100:9100 \
-v (pwd)/config.json:/etc/algorand/config.json \
-e NETWORK=betanet \
algorand/algod:3.18.0-stable
```
2. The metric endpoint does not work:
```
curl localhost:9100/metrics
```
3. Build container with this branch:
```
docker build \
-t wwinder/algod:metrics-fix \
--build-arg CHANNEL=nightly \
--build-arg TARGETARCH=amd64 --no-cache \
.
```
4. Run the container like above:
```
docker run --rm -it \
-p 9100:9100 \
-v (pwd)/config.json:/etc/algorand/config.json \ …
```
=> docker: Update docker config with node_exporter path.

docker/build/Dockerfile-deploy, scripts/upload_config.sh
Fix binaries build for local cluster deployment with docker.
Some errors seen are:
```
> [9/9] RUN scripts/configure_dev-deps.sh && make clean && find tmp && tmp/pavel-5rel-arch/deploy_linux_version_exec.sh:
0.255 /bin/sh: 1: make: not found
...
37.18 /usr/bin/env: 'python3': No such file or directory
37.52 + '[' 3.19. = '' ']'
37.54 + export BUILDNUMBER=
37.54 + BUILDNUMBER=
37.54 + '[' '' = '' ']'
37.54 FULLVERSION does not appear to be valid: 3.19.
37.54 + echo 'FULLVERSION does not appear to be valid: 3.19.'
37.54 + exit 1
```
Additionally, fix `._Wallet` hidden files in tar archive with `export COPYFILE_DISABLE=true` as per this [post](https://stackoverflow.com/questions/8766730/tar-command-in-mac-os-x-adding-hidden-files-why)
Otherwise algod is trying to load these metadata files …
=> ci: fix scripts/create_and_deploy_recipe.sh build

network/wsNetwork_test.go
Remove flaky persistent peers test from wsNetwork (TestUpdatePhonebookAddresses covers this).
=> tests: Remove flaky persistent peers test from wsNetwork

cmd/tealdbg/server_test.go
Our arm64 nightly build shows a test failure of `TestServerLocal` and several others from the package `cmd/tealdbg`: https://app.circleci.com/pipelines/github/algorand/go-algorand/16882/workflows/78daf42e-bd47-4f33-8ac2-b210eaf0b2bb/jobs/256093/tests
I can't say why the others failed (in fact I'm suspicious this is a reporting error), but the failure from `TestServerLocal` indicates that it couldn't find a free port to use for its server. I've fixed this by using port 0, which should assign it any randomly-chosen available port.
Test-only fix
=> tests: Fix flaky tealdbg unit test

docker/files/run/run.sh
The docker image proactively disables telemetry if `TELEMETRY_NAME` is not set. Presumably this was to allow turning telemetry on and off for an existing container. This has a side effect of disabling telemetry enabled by a `logging.config` override.
We have two options:
1) this is desirable behavior even when providing `logging.config`. No change is necessary.
2) (this PR) If `logging.config` is provided and no `TELEMETRY_NAME` is provided, skip disabling telemetry.
Manually tested the bash script and ran it through shellcheck.
=> docker: Do not disable telemetry if logging.config is present.

cmd/goal/clerk.go, cmd/goal/clerk_test.go, cmd/tealdbg/debugger.go, cmd/tealdbg/debugger_test.go, cmd/tealdbg/local.go, daemon/algod/api/server/v2/handlers.go, daemon/algod/api/server/v2/test/handlers_test.go, data/transactions/logic/assembler.go, data/transactions/logic/assembler_test.go, data/transactions/logic/sourcemap.go, data/transactions/logic/sourcemap_test.go, test/scripts/e2e_subs/e2e-teal.sh, test/scripts/e2e_subs/tealprogs/quine.map, test/scripts/e2e_subs/tealprogs/sourcemap-test.map, test/scripts/e2e_subs/tealprogs/sourcemap-test.teal
Prior to this, TEAL source maps would only map PCs to line numbers, always assuming the column was 0. Since multiple opcodes can now be placed on a single line, separated by `;`, it makes sense to also report the source column as well.
Additionally, I also made the path to the source file relative to the source map file, which is what the specification requires (see [Resolving Sources](https://sourcemaps.info/spec.html#h.75yo6yoyk7x5)). Prior to this PR, we were just using whatever the user input as the source program path.
Existing unit tests updated and added an additional e2e test to expand coverage of more complicated cases.
=> TEAL: Report columns in TEAL source maps

data/transactions/logic/assembler.go, data/transactions/logic/eval.go, data/transactions/logic/eval_test.go
Previously, AVM panic'd while checking a malformed switch/match that was missing the byte encoding the number of cases. This meant the check failed, which is correct, but we endeavor to avoid panics.
=> AVM: Cleanly handle broken switch/match programs

catchup/catchpointService.go
The `ledgerFetcher` is used by the `catchpointService` to download the catchpoint file (ledger snapshot) and uses a `peerSelector` that only connects to relays. This change updates it to use the same `makePeerSelector` arguments as used when downloading blocks as part of fast catchup, where `EnableCatchupFromArchiveServers` is checked.
Fixes #5765.
=> catchpoints: check EnableCatchupFromArchiveServers for ledgerFetcher

daemon/algod/api/server/v2/handlers.go
Feedback in #5781
Covered by existing unit tests.
=> API: minor style improvements in keygen code.

config/localTemplate.go
Related to #5766, this corrects the language used in the description to explain that `IncomingConnectionsLimit` is the node's incoming connection limit for `NetAddress`.
No code changes.
=> config: Update description for IncomingConnectionsLimit

data/committee/common_test.go, data/committee/credential_test.go
Go 1.20 [introduced a change](https://go.dev/doc/go1.20#math/rand) to math/rand that seeds the global RNG with a random value. This test `TestAccountSelected` was previously relying on the fixed-seed global RNG for deterministic behavior. There was already a non-global random generator [used for this test in testingEnvMoreKeys](https://github.com/algorand/go-algorand/blob/6c482ab1286bfc2b1b09b80cb55f8c52817fcc96/data/committee/common_test.go#L65), but it was not used for two usages of the global RNG to so different values would be produced for multiple iterations calling `testingEnv`.
Running with `GODEBUG=randautoseed=0` and extra logging revealed the difference between the old and new behavior.
Existing tests should pass, and the number of leaders chosen in this test is unchanged, the …
=> tests: Fix flaky TestAccountSelected test

docker/build/cicd.centos8.Dockerfile, package-deploy.yaml, scripts/release/mule/deploy/rpm/deploy.sh
This was broken because of adding an S3 sync of signatures, but there were other issues uncovered.
- Fixed centos 8 base image, which needed to update RPM
- Updated repository updater to use centos 8 base image
- Updated RPM signing and removed python script dependency
Note that the beta channel RPM repository has been non-functional to date, due to lack of a repo definition file, which was fixed as part of this testing.
The purpose of this was to narrowly fix the repository issue, However a closer look at simplifying this process is recommended in the future.
Re-ran the update for the beta release. Verified signatures validated with RPM key.
These changes should be cherry-picked into the next stable release as well.
=> CICD: Fix RPM repository updating

config/consensus.go
Small comment to `initConsensusProtocols`. What it is and what it isn't.
N/A
=> docs: Add comment to initConsensusProtocols.

node/follower_node.go
The feature was renamed from `sync` to `follower` and this error message was not updated along with it.
There is a possibility that user code could be checking for this message, so this could be considered a breaking change. This error message also indicates a configuration issue, so error handling would be unable to resolve it.
My recommendation is to make the breaking change.
=> follower: update follower node error messages.

ledger/eval/eval.go, ledger/eval/eval_test.go
We had a brief period where a handful of rounds had stake miniscully mismatching in some cases based on delta corruption in some nodes. This pull request ensures catchup cannot stall while removing the stake dilution factor (underlying cause/corrections were addressed in the last consensus upgrade).
Added a new `TestEval_EndOfBlockStake` (thanks @algorandskiy ) to exercise various cases being handled as expected.
=> Feature: Catchup Eval Stake Exception Round Handling

data/transactions/logic/assembler.go, data/transactions/logic/assembler_test.go
Modified OpStream Warnings from []error to []sourceError to preserve line and column information so it can be used by TEAL language servers to display a location of warnings.
Added unit tests for warnings with zero and non-zero lines/columns
=> avm: preserve line/column for assembler warnings

catchup/catchpointService.go, components/mocks/mockCatchpointCatchupAccessor.go, ledger/catchupaccessor.go, ledger/catchupaccessor_test.go, ledger/store/blockdb/blockdb.go, test/e2e-go/features/catchup/catchpointCatchup_test.go
Each block certificate is downloaded but thrown away during catchpoint restore, leading to errors like #5352 when trying to retrieve blocks with their certificates later. Since we always store blocks and certs together this keeps the certificates from being thrown away so `certdata` ends up in the block db with the `blkdata`
Closes #5352.
Updated TestBasicCatchpointCatchup to request a msgpack block at the end.
=> catchpoint: store certs with blocks during catchpoint restore

test/framework/fixtures/fixture.go, test/heapwatch/metrics_viz.py, test/heapwatch/plot_crr_csv.py, test/heapwatch/requirements.txt
* plot_crr_csv: use round numbers for x axis scaling
* metrics_viz: allow drawing difference of two metrics
Additionally fixed e2e logger to report actual invocation file:line and not fixture.go:171 from syncTest implementation wrapper
This is test/tools fix, tested manually. Rendered charts in this PR https://github.com/algorand/go-algorand/pull/5794 description.
=> tools: improve heapwatch chart drawing scripts

catchup/service.go, catchup/service_test.go, ledger/acctupdates.go, ledger/catchpointtracker_test.go, ledger/ledger.go, ledger/tracker.go, ledger/tracker_test.go
It is possible catchup downloads blocks faster than ledger commits it slow disks. This could cause OOM because of too many pending deltas.
1. Defined max deltas number = 256 used to slow down catchup via a new `Ledger.Available()` method.
2. If `MaxAcctLookback` is manually set greater than 256, use `MaxAcctLookback+1` as a new max.
3. Added a new boolean flag for checking if the ledger is committing right now. If both deltas exceeded and committing then ledger is unavailable.
4. When unavailable, catchup service stops blocks fetching similarly to what happens with catchpoint file writing.
Additionally moved `trackerRegistry.dbRound` initialization from `initialize` to `loadFromDisk` to 1) simplify testing 2) it seems naturally belongs to `loadFromDisk`.
1. It is possible to use max …
=> catchup: pause catchup if ledger lagging behind

catchup/peerSelector.go, catchup/peerSelector_test.go
Added a missed unit test, made tests parallel and prefixed with `TestPeerSelector_` to simplify isolated runs, and fixed some linter warnings.
This is tests update.
=> tests: add refreshAvailablePeers catchup unit test

daemon/algod/api/server/v2/handlers.go, daemon/algod/api/server/v2/test/handlers_resources_test.go, ledger/bulletin.go, ledger/bulletin_test.go, ledger/ledger.go
The REST API WaitForBlockAfter call creates a notifier for each unique round requested, which remains present even if the HTTP request times out. This adds the ability to cancel and delete notifiers if no one wants them.
Needs new tests
=> ledger: support WaitWithCancel for unsuccessful WaitForBlock API calls

catchup/universalFetcher.go, catchup/universalFetcher_test.go, rpcs/blockService.go
When a node requests a block that is outside the range that a node contains, it returns a 404 (for HTTP catchup) or an `{ErrorKey: blockNotAvailableErrMsg}` value (for websockets catchup). This provides more information to the client so it can more effectively request and poll for new blocks. 
Updated TestUGetBlockWs and TestUGetBlockHTTP.
=> catchup: Provide more information to client when requested block not available

cmd/algocfg/profileCommand.go, cmd/algocfg/resetCommand.go, cmd/algocfg/setCommand.go, config/localTemplate.go, util/codecs/json.go, util/codecs/json_test.go
I frequently want to tell people a default configuration according to algocfg, but the only way to use it involves updating/creating a file in the data directory.
This PR adds a new `algocfg profile print <profile>` subcommand that writes configuration to stdout instead of to a regular file.
Manual testing:
```
$ algocfg profile print relay
{
"Archival": true,
"NetAddress": ":4160",
"EnableLedgerService": true,
"EnableBlockService": true
}
$ algocfg profile print conduit
{
"CatchupParallelBlocks": 64,
"MaxAcctLookback": 64,
"EnableFollowMode": true
}
$ algocfg profile print participation
{
}
$ algocfg profile print development
{
"EnableDeveloperAPI": true,
"MaxAcctLookback": 256,
"EnableExperimentalAPI": true,
"EnableTxnEvalTracer": true,
"DisableAPIAuth": true
}
```
=> algocfg: Add print option to algocfg.

network/p2p/p2p.go
Fix post-merge compilation error
=> p2p: fix dht-hybrid merge

ledger/eval/eval.go, ledger/eval/eval_test.go
1. Rolled back the #5795
2. Changed the `stakeDiffusionFactor` to 1 from 5.
1. Existing unit tests
2. TODO: Manual catchup on the affected range
=> ledger: rollback vetting historical stateproof blocks

README.md, cmd/algocfg/profileCommand.go, cmd/algocfg/resetCommand.go, cmd/algocfg/setCommand.go, config/config_test.go, config/localTemplate.go, data/transactions/logic/README.md, data/transactions/logic/README_in.md, data/transactions/logic/jsonspec.md, docs/follower_node.md, ledger/eval/eval.go, ledger/eval/eval_test.go, node/follower_node.go, node/node.go, node/node_test.go, scripts/windows/instructions.md, util/codecs/json.go, util/codecs/json_test.go
An endpoint to generate participation keys, network optimization, and other enhancements around catchpoints and catchup are included in this release.
Both the crash and state proof databases now default to the 'hot' data directory.
* Participation key generation endpoint: a requested feature to allow the ability to generate API keys from the REST endpoint, provided you have the admin token.
* API: Add participation key generation endpoint to algod API ([#5781](https://github.com/algorand/go-algorand/pull/5781))
* Txhandler: applications rate limiter ([#5734](https://github.com/algorand/go-algorand/pull/5734))
* Algocfg: Add print option to algocfg. ([#5824](https://github.com/algorand/go-algorand/pull/5824))
* API: minor style improvements in keygen code. …
=> go-algorand 3.20.0-beta Release PR

catchup/service.go
This introduces polling delay between 404 responses for blocks when running in follow mode, which uses catchup to continuously poll for new blocks, rather than using agreement. In follow mode, aborting the catchup process causes unnecessary latency in observing the latest blocks.
On the contrary, in regular catchup, it is desirable to abort catchup right away when you reach the latest round, so that agreement can take over.
Existing tests should pass — @algorandskiy found in #5809 that many tests depend on the desired no-backoff-and-quit-fast behavior in regular catchup.
=> catchup: use specialized backoff behavior for follower mode

crypto/statetrie/nibbles/nibbles.go, crypto/statetrie/nibbles/nibbles_test.go
This PR adds types and utility functions for manipulating nibbles (4-bit value arrays). It is specifically to support a new package, statetrie, which will use Nibbles and their associated utility functions.
The statetrie is designed to have keys with sequences of 4-bit bytes. A statetrie with 16-ary branch nodes has smaller proofs than a full byte (256-ary).
=> statetrie: nibbles

catchup/service.go
=> catchup: increase followLatestBackoff to 100ms

config/consensus.go, test/e2e-go/features/stateproofs/stateproofs_test.go
Fix test [failures](https://app.circleci.com/pipelines/github/algorand/go-algorand/17268/workflows/6ba0e710-2391-43bc-97f2-c5fcc045a0a6/jobs/259789) after merging https://github.com/algorand/go-algorand/pull/5663
The `TestStateProofMessageCommitmentVerification` reset a global var `config.Consensus` and `TestStateProofRecovery` was not able to find its consensus there.
Tests passed locally
```
% export NODEBINDIR=~/go/bin
% export TESTDATADIR=`pwd`/test/testdata
% export TESTDIR=/tmp
% make
% go test ./test/e2e-go/features/stateproofs -run '(TestStateProofMessageCommitmentVerification)|(TestStateProofRecovery)$'
=> tests: fix state proof e2e test failures

crypto/hashes.go, crypto/merklearray/layer.go, crypto/merklearray/merkle_test.go, crypto/merklearray/partial.go
Decrease around 10% in allocations for construction and verifying.
Less in absolute speedup.
```
> benchstat bench-old.txt bench-new.txt
goos: darwin
goarch: arm64
pkg: github.com/algorand/go-algorand/crypto/merklearray
│ bench-old.txt │            bench-new.txt            │
│    sec/op     │    sec/op     vs base               │
MerkleCommit/sha512_256/Item10/Count10-10            13.45µ ± ∞ ¹   12.80µ ± ∞ ¹   -4.82% (p=0.008 n=5)
MerkleCommit/sha512_256/Item10/Count100-10           51.97µ ± ∞ ¹   49.54µ ± ∞ ¹        ~ (p=0.095 n=5)
MerkleCommit/sha512_256/Item10/Count1000-10          277.8µ ± ∞ ¹   257.0µ ± ∞ ¹   -7.50% (p=0.008 n=5)
MerkleCommit/sha512_256/Item10/Count10000-10         1.563m ± ∞ ¹   1.439m ± ∞ ¹   -7.90% (p=0.008 n=5)
MerkleCommit/sha512_256/Item10/Count100000-10 …
```
=> chore: Cut out some useless allocations when computing payset commitments

catchup/catchpointService.go, catchup/catchpointService_test.go, ledger/catchupaccessor.go
This fixes nil pointer dereference in StoreBlock/StoreFirstBlock discovered by e2e catchup test.
```
algod(22258) : github.com/algorand/go-algorand/ledger.(*catchpointCatchupAccessorImpl).StoreBlock(0xc00836e480, {0x2ee95c8652e0cbe8?, 0xad49081e76d4ff29?}, 0xc009b79880, 0x0)
algod(22258) : 	github.com/algorand/go-algorand/ledger/catchupaccessor.go:1078 +0x1a0
```
It was introduced in https://github.com/algorand/go-algorand/pull/5798 and very similar to the `psp` fix in https://github.com/algorand/go-algorand/pull/4390
=> catchup: Fix empty cert if ledger already has a block

test/framework/fixtures/libgoalFixture.go
Time to time some catchup nightly e2e tests [fail](https://app.circleci.com/pipelines/github/algorand/go-algorand/17357/workflows/1871bddc-e37e-457c-aca7-f5dc3866b56b/jobs/260944) with a node non-zero exit status after the test completion. No luck reproducing it locally/branches/etc so adding extra logging to master.
This is test fixture modification.
=> tests: dump logs if e2e test node exited with an error

agreement/dynamicFilterTimeoutParams.go, agreement/router.go
Set minimum dynamic filter timeout to 2500ms. Additionally, set minimum credential round lag to 8 (helping stabilize for voteValidatedAt lookups in telemetry).
Existing tests pass.
=> Round Times: Set minimum dynamic filter timeout to 2500ms. 

agreement/actions.go, agreement/player.go, agreement/service_test.go, agreement/types.go, catchup/service.go, catchup/service_test.go, config/consensus.go, daemon/algod/api/server/common/handlers.go
This PR introduces a consensus parameter `AgreementDeadlineTimeoutPeriod0`, that as the name implies is used for setting a common period 0 deadline timeout. References to the deadline timeout in the codebase have been updated to reflect whether they need the existing default or to resolve a timeout based on a current period of consensus (and the active consensus version).
Existing tests should all pass (several pass in period 0 or period 1  in agreement/service_test.go).
=> Round Times: Period 0 deadline timeout

test/scripts/e2e.sh, test/scripts/e2e_client_runner.py, test/scripts/e2e_subs/example.py, test/scripts/e2e_subs/goal/goal.py, test/scripts/e2e_subs/min_balance.py, test/scripts/e2e_subs/shared-resources.py
Changed our pinning strategy to only care about major versions, as minor versions aren't supposed to break things, and updates can be useful. Don't want a PR here every time we go from 2.4.11 to 2.4.12.
Existing e2e sub tests are the only thing this affects.
=> Chore: Update testing to use current python SDK.

data/transactions/logic/eval_test.go
This adds a test for `global GenesisHash` and a test to ensure such tests must be added when new globals are added.
=> AVM: Require every global field to get tested

cmd/opdoc/opdoc.go, data/transactions/logic/TEAL_opcodes_v1.md, data/transactions/logic/TEAL_opcodes_v10.md, data/transactions/logic/TEAL_opcodes_v2.md, data/transactions/logic/TEAL_opcodes_v3.md, data/transactions/logic/TEAL_opcodes_v4.md, data/transactions/logic/TEAL_opcodes_v5.md, data/transactions/logic/TEAL_opcodes_v6.md, data/transactions/logic/TEAL_opcodes_v7.md, data/transactions/logic/TEAL_opcodes_v8.md, data/transactions/logic/TEAL_opcodes_v9.md
In the specs repo we generate pdf from md, and it can't handle the unicode character we were using to mean "where".
=> Docs: Eliminate a unicode character that causes trouble in doc generation

test/testdata/deployednettemplates/generate-recipe/generate_network.py, test/testdata/deployednettemplates/recipes/custom/configs/node.json
* Part nodes apply alt config at 10% rate (vs 1%) to let smaller networs reporting more telemetry
* Set LastPartKeyRound to 100k instead of 3M to speedup parts key generation
Checked locally
=> tests: custom recipe tweaks

data/txHandler.go
While evaluating ARL after deployment I noticed the combo ERL=off ARL=on actually disables ARL as well. This fixes the configuration.
Manually tested
=> txHandler: fix ARL triggering without ERL

network/wsNetwork_test.go
[wsNetwork refactoring](https://github.com/algorand/go-algorand/pull/5634/files#diff-c19b4d9a8a60432019fd844b78b1cf5c332cd63f7841736907b7badc04f18a50R809) changed the `slowWritingPeerMonitorInterval` value in `TestSlowPeerDisconnection`: it got overwritten in `wn.setup` by 5s default value that caused test fail time to time when the wait time as a bit greater than 5s.
Failure examples: [one](https://app.circleci.com/pipelines/github/algorand/go-algorand/17413/workflows/2592bfee-5164-4b9e-8e96-4f69d89cb464/jobs/261408), [two](https://app.circleci.com/pipelines/github/algorand/go-algorand/17447/workflows/53dbd82a-e9df-438e-8650-8d4739bb9fa9/jobs/261732)
=> network: fix TestSlowPeerDisconnection regression after #5634

netdeploy/network.go, test/framework/fixtures/libgoalFixture.go
Expose new `RelayDataDirs` method to save relays logs on e2e test failure.
This is tests-related change.
=> tests: log all relay logs on e2e failure

agreement/demux.go, agreement/fuzzer/fuzzer_test.go, agreement/fuzzer/networkFacade_test.go, agreement/fuzzer/validator_test.go, agreement/service.go
Enabled dumping actual demux queues sizes for debugging agreement fuzzer failures ([one](https://app.circleci.com/pipelines/github/algorand/go-algorand/17491/workflows/44af3387-56ec-41f7-a2d7-660afcab702a/jobs/262181/parallel-runs/2), [two](https://app.circleci.com/pipelines/github/algorand/go-algorand/17491/workflows/a5cd776f-8cff-4390-bbed-42ff14cb16cb/jobs/262177/tests)) where processing monitor logs indicate there is one unprocessed message `Queue cryptoVerifierVote has 1 items`.
This is testing only change.
=> agreement: dump demux queues on fuzzer test failure

data/transactions/logic/assembler.go, data/transactions/logic/assembler_test.go, data/transactions/logic/eval.go
When deciding how to propagate type into in `loads` and `stores` we sometimes thought we had a constant index to work with even when we didn't.
Regression unit test added.
=> AVM: Don't treat `any` as constant int in `loads`, `stores`

data/txHandler.go, data/txHandler_test.go
While checking ARL after deployment I found out ARL can be more aggressive. The original settings kicked in it at 1/2 of the adjusted to ERL capacity (defaults are 26k + 2.4k*20 = 74k, so it kicks in at 36k backlogged messages).
Logs showed these settings are fine for extreme traffic with full txn groups but not enough for high traffic where the backlog stays at ~20k messages. Given the fact 20k messages is kind of enough to make almost full blocks, we have not observed _committed_ 20k txns per block during these time periods. So that most of these txns are junk and can be discarded earlier.
Adjusted unit test to ensure the new kick-in condition.
=> txHandler: kick in ARL at 1/2 of a base backlog capacity

agreement/fuzzer/networkFacade_test.go, agreement/gossip/network_test.go, components/mocks/mockNetwork.go, daemon/algod/server.go, network/gossipNode.go, network/hybridNetwork.go, network/p2p/capabilities.go, network/p2p/capabilities_test.go, network/p2p/dht/dht.go, network/p2p/dht/dht_test.go, network/p2p/p2p.go, network/p2pNetwork.go, network/p2pNetwork_test.go, network/wsNetwork.go, network/wsNetwork_test.go, node/follower_node.go, node/node.go, tools/debug/algodump/main.go, tools/debug/transplanter/main.go
1. Made code changes required to follow the algod's Services architecture: make + start as separate stages.
This is done by using `NoListenAddr` for p2p.Host and by providing an empty bootstrap callback to DHT.
When `net.Start()` is being called, manually calling `Listen` on p2p host, and unblock the `bootstrap callback` to return phonebook or DNS addresses for peering.
2. Also moved DHT init to netowork/p2p from node.
3. Changed `GossipNode.Start()` signature to return an error (and possibly explicitly abort node startup).
1. Existing tests passed
2. Added DHT tests as part of p2p network
=> p2p: start p2p networking and DHT ops when starting services, not when instantiating them

ledger/catchpointtracker.go, ledger/ledger_test.go
Our trackers committing code uses `sync.WaitGroup` in a slightly incorrect way: `wg.Add` and `wg.Wait` are called from different goroutines that could cause a rare data races like in this [TestLedgerCatchpointSPVerificationTracker](https://circleci.com/api/v1.1/project/github/algorand/go-algorand/261030/output/114/9?file=true&allocation-id=6570d9b67629ec29e721a83b-9-build%2FABCDEFGH) test. Fortunately this happens only in test that immediate start waiting after triggering a commit event.
This PR addresses this by rewriting `triggerTrackerFlush` test helper by executing the commit flow in a current goroutine.
Some background on `waitAccountWriting` function. There are two uses of it: 1) replay 2) close. Technically both can be re-written (probably in a separate PR since it would be a bit …
=> tests: rewrite triggerTrackerFlush test helper

daemon/algod/api/server/v2/dryrun.go, daemon/algod/api/server/v2/dryrun_test.go
I know this code is not necessarily in heavy use anymore, but I had a frustrating experience debugging a pyteal integration test that uses dryrun.
If there's more than one assembler error in a TEAL dryrun source, dryrun returns the error directly from `logic.AssembleString`, which unhelpfully only tells you the number of errors: https://github.com/algorand/go-algorand/blob/3a80a406f7b94161ce031bec00b5a82bdf9becba/data/transactions/logic/assembler.go#L2154
I fixed this by using the `ReportMultipleErrors` function to build a more informative string, like other callsites do.
Unit test added
=> Dryrun: Improve assembler error reporting

cmd/algocfg/profileCommand.go, cmd/algocfg/profileCommand_test.go
Introduce new archival node algocfg profile. Explicitly disable the gossip service in configuration override.
Added new simple unit test, also exercised create/override on command line.
=> Algocfg: Introduce new archival node algocfg profile.

scripts/release/mule/deploy/releases_page/generate_releases_page.py, scripts/release/mule/deploy/releases_page/html.tpl
The old calculation for this was deprecated, and was showing outdated indexer entries. Removed these and am pointing direct to Github Releases.
Ran `generate_releases_page.py` locally to verify it built a new page.
=> Releases Page: remove indexer and point to github

data/pools/statusCache.go
Should be a tiny gain. It bothered me that we knew the size and didn't use it.
=> API: Make maps the right size from the start

ledger/ledger.go, ledger/txtail.go, ledger/txtail_test.go, node/node.go
* Use txtail data to find txid in memory (only txns with LastValid > current round) in addition to iterating blocks
* RPS: before: 10, after: 450
* Another optimization possible with caching blocks that would bump RPS to 30k
* It is possible to completely get rid of blocks iteration by one of the following:
- Extend txtail to have MaxTxnLife old rounds. Requires lots of memory.
- Make a new cache in AlgorandFullNode for txids: 26k txns/block * 1000 rounds => need 25 bits for all combos => 4 bytes (32bits) of txid instead of 32 bytes of a full txid would require 26M*4b = 100MB of RAM.
* Estimated extra memory footprint is 52MB = 26k txns/block * 1000 rounds * 2 bytes per round delta.
Added unit test for new txtail logic
=> api: optimize /transactions/pending/{txid} endpoint

network/messageFilter.go
Don't allocate all the maps ahead of time, when we do allocate them, allocate them fullsize, and use `struct{}` instead of `bool`.
I'm a little unsure how well this is exercised in tests, since `messageFilter_test.go` is just a hash benchmark. But I did intentionally do it wrong at first, saw failures, them did it right.
First noted by @pao-beep
=> Network: Like #5906, but for messageFilter, optimize cache mem and speed

netdeploy/networkTemplate.go, test/e2e-go/features/catchup/catchpointCatchup_test.go
Adjust catchup e2e tests for no longer default enabling archival with netAddress.
=> Tests: Adjust catchup e2e tests for non-archival relays

cmd/algocfg/profileCommand.go
Set relay profile's MaxBalanceHistoryLookback to 22000 to better support catchup from the two latest catchpoints.
Existing tests pass.
=> Config: Set relay profile's MaxBalanceHistoryLookback to 22000

ledger/blockqueue.go, ledger/blockqueue_test.go, ledger/ledger.go, ledger/ledger_test.go
If a node switches from Archival to non-archival then the blockdb cleanup can take a long time blocking the blockdb in a write tx. This PR addresses this by scoping max blocks deleted per sync op.
```
Earliest                       MinToSave         Latest
|                               |                 |
+-------------------------------+-----------------+
^            ^                  ^                 ^
|            |                  +-----------------+
+------------+
| maxDeletionBatchSize          ^     MaxBlockHistoryLookback
+-------------------------------+
Deletion Range (Old)
```
Added a unit test.
Additionally fixed [a data race](https://app.circleci.com/pipelines/github/algorand/go-algorand/17645/workflows/f92bed2b-2e64-4164-85e6-3074b575803c/jobs/263918) seen in …
=> blockdb: bound max deleted blocks per blockdb sync

cmd/netgoal/generate.go
Whenever I've generated a goalnet template using `netgoal` I have to manually modify the `LastPartKeyRound` value from 3000000 to something like 10000, depsite using the `--last-part-key-round` argument in the command.
Example:
```sh
netgoal generate -n 1 -R 0 -w 4 --last-part-key-round 10000 -t goalnet -r tmpnet -o tmpnet.json
goal network create -t tmpnet.json -n tmpnet --start -r tmpnet
```
This fix works in the same way generating a genesis template works. I've no idea how many people use this, but it's a nice quick QOL update for me.
=> netgoal: Use --last-part-key-round when generating a goalnet template

components/mocks/mockNetwork.go, network/addr_test.go, network/gossipNode.go, network/hybridNetwork.go, network/p2p/capabilities_test.go, network/p2p/http.go, network/p2p/p2p.go, network/p2p/streams.go, network/p2p/testing/httpNode.go, network/p2pNetwork.go, network/p2pNetwork_test.go, network/wsNetwork.go, network/wsPeer.go, rpcs/httpTxSync.go, rpcs/txService_test.go, rpcs/txSyncer_test.go
* Add multiaddr support to txsync
* Replace `GossipNode.GetRoundTripper` with `GossipNode.GetHTTPClient` as higher level alternative. (only txsync used GetRoundTripper outside of the `network` package.
Added a new unit test to txSync to test p2p flow.
=> p2p: enable p2p http txsync

network/p2p/dnsaddr/resolve.go, network/p2p/dnsaddr/resolve_test.go
`dnsaddr.Iterate()` is not tolerate to cycles. Added max attempts to prevent infinite looping.
Added a unit test.
=> p2p: fix infinite loop in dnsaddr resolution

rpcs/blockService.go, rpcs/blockService_test.go
Support p2p addresses (multiaddr) in block service redirect code.
Added unit test.
=> p2p: support block request redirects for p2p addresses

ledger/ledger.go, ledger/ledger_test.go
Support minimum number of rounds saved that takes the being able to catchup from a recent catchpoint into account.
Added a new unit test that exercises the impact of enabling/disabling catchpoint support on ledger's `minToSave` calculation.
=> Blocks: Bump min to save based on catchpoint support

catchup/ledgerFetcher.go, catchup/universalFetcher.go, cmd/algod/main.go, cmd/goal/node.go, network/addr.go, network/addr/addr.go, network/addr/addr_test.go, network/dialer.go, network/limitcaller/dialer.go, network/limitcaller/rateLimitingTransport.go, network/p2p/http.go, network/p2p/peerstore/peerstore.go, network/p2p/peerstore/peerstore_test.go, network/p2p/peerstore/utils.go, network/p2pNetwork.go, network/p2pNetwork_test.go, network/phonebook/phonebook.go, network/phonebook/phonebook_test.go, network/rateLimitingTransport.go, network/requestLogger_test.go, network/requestTracker.go, network/requestTracker_test.go, network/websocketProxy_test.go, network/wsNetwork.go, network/wsNetwork_test.go, node/node_test.go, rpcs/blockService.go, rpcs/blockService_test.go, rpcs/httpTxSync.go
Make `P2PNetwork` to produce rate limiting outgoing HTTP clients. There are some some movements into subpackages to allow both `network`, `p2p`, `peerstore` to use some utilities/functionality.
* addr.go -> `network/addr`
* phonebook -> `network/phonebook` (to make peerstore's interface compatible with phonebook)
* dialer, ratelimit transport -> `network/limitcaller`
Had to modify phonebook interface to accept both string and `p2p.peer.AddrInfo` (alternative is to marshal `AddrInfo` to bytes, cast and unmarshal but it is kind of the same). Plus, the current peerstore's implementation of `Phonebook` interface uses "host:port" as peerID and works only with "host:port" addresses and not with any kind of p2p addresses  so it requires some change anyway. This is a first step.
Added a unit …
=> p2p: rate limit outgoing p2p http connections

package-deploy.yaml, scripts/release/mule/common/ensure_centos8_image.sh, scripts/release/mule/deploy/deb/deploy.sh, scripts/release/mule/deploy/docker/docker.sh, scripts/release/mule/deploy/releases_page/generate_releases_page.sh, scripts/release/mule/deploy/rpm/deploy.sh, scripts/release/mule/sign/sign.sh, test/muleCI/Jenkinsfile, test/muleCI/mule.yaml
Issues in some of the pipelines was preventing a clean end to end build. This PR makes the following changes:
- Fix issues in debian and rpm package building pipelines
- Shift rpm signing to build instead of rpm repository update step
- Explicitly enable ARM64 and disable ARM32
- Cleanup of some parameters passed to build stages
- Removed alphanet from some build processes
Manual testing around building and signing
=> CICD: fix package signing issues

cmd/catchpointdump/net.go, network/wsNetwork.go, network/wsNetwork_test.go, tools/network/bootstrap.go, tools/network/bootstrap_test.go, tools/network/telemetryURIUpdateService.go
* Pending DNS operations might cause delay on node shutdown
* Providing a cancellable context to underlying resolver would about operations that could stuck in timeout otherwise
I narrowed down the e2e_basic_start_stop.sh sporadic failures to `wsNetwork.meshThread` that makes me think DNS lookup timeouts might be responsible for that.
=> network: use network context for DNS operations in readFromSRV

catchup/catchpointService.go, catchup/classBasedPeerSelector.go, catchup/classBasedPeerSelector_test.go, catchup/peerSelector.go, catchup/peerSelector_test.go, catchup/service.go, catchup/service_test.go
Introduce a class-based peer selector for explicitly ranking peer groups based on type and download performance. The intent is to be able to quickly move from one class of peers to the next in cases such as where a client needs older blocks that may only be present on archival nodes.
Introduce new unit tests for class-based peer selector, existing tests should be updated/pass.
=> Network: Class-based Peer Selector

network/p2p/capabilities.go, network/p2p/capabilities_test.go, network/p2p/dnsaddr/resolve_test.go, network/p2p/p2p.go, network/p2p/p2p_test.go, network/p2p/peerstore/peerstore.go, network/p2p/peerstore/peerstore_test.go, network/p2p/pubsub.go, network/p2pNetwork.go, network/p2pNetwork_test.go, node/node.go, node/node_test.go
This PR enables p2p relays by introducing a new gossip capability and preferring such peers for connection.
* Unit tests for `relayMessages`
* Unit tests for `wantTXGossip` and gossip sub.
* Unit test for gossip capability
=> p2p: introduce Gossip peer capability

catchup/peerSelector.go, config/localTemplate.go, network/gossipNode.go, network/phonebook.go, network/phonebook_test.go, network/wsNetwork.go, network/wsNetwork_test.go
Support resolving archival nodes from the archive dns entry. Phonebook queries for archival nodes have been updated to resolve to addresses discovered from the archive dns entry (these queries previously mapped to relay addresses).
Deduplication of addresses resolved from primary/secondary DNS bootstrap services for archival nodes is now supported as well.
Remaining mentions of 'archivers' were removed to avoid future confusion.
Existing tests were updated/should pass. Also ran algod manually to ensure proper DNS queries taking place.
=> Network: Archival node DNS Resolution

node/follower_node.go, node/node.go, rpcs/healthService.go, rpcs/healthService_test.go
This PR adds a simple /status http endpoint on the gossip server port, enough to ensure it is open. Continue to use the /ready endpoint on the API port for readiness checks (i.e. is the node caught up?).
closes #5208 
Added new health check tests, existing tests should pass without issue. In addition, started node up locally with NetAddress set, confirmed can reach `/status` on the specified port.
=> Network: Support simple liveness check via http on gossip server port.

Dockerfile, scripts/get_golang_version.sh
This updates the builds to use the latest version of Go 1.20.
No code changes, relying on existing tests.
=> build: upgrade to go 1.20.14

Dockerfile
Bump the debian version of the official algod container.
Verify container builds and runs.
=> Docker: Bump debian version in algod container

catchup/catchpointService.go, catchup/peerSelector.go
Penalize peer/class rankings during catchpoint catchup initialization when they do not have a catchpoint. This is critical to ensure that the class based peer selector falls back to the next class of peers when too many peers in the first priority class do not have a catchpoint (in turn to prevent blocking the node from doing a fast catchup).
Reproduced catchup against older catchpoints on Betanet getting failing locally, then working properly once the ranking was included. Existing automated tests should all pass.
=> Network: Penalize peer/class rankings when peer does not have catchpoint

ledger/catchpointtracker.go, ledger/catchpointtracker_test.go
Fixed bug with data files deletion when catchpoint tracker configured with hot / cold directories.
1. Extended `TestCatchpointFirstStageInfoPruning` to repro and fix
2. Checked all `MakeCatchpointFilePath` and `makeCatchpointDataFilePath` to ensure they are used with `ct.dbDirectory` and `ct.tmpDir` correspondingly.
=> catchpoint: fix data files deletion in hot/cold dirs scenario

agreement/service_test.go
Same tests, nicer output, and we can see multiple failures, since we don't panic.
Ran into tests that were hard to understand because they panic'ed while doing incentive work.  This PR breaks out the very repetitive changes to use `require.
=> Tests: Thread testing.T through so we panic less

test/framework/fixtures/libgoalFixture.go
There are some random TestCatchupOverGossip failures like [this](https://circleci.com/api/v1.1/project/github/algorand/go-algorand/267035/output/114/3?file=true&allocation-id=65eb44dd6e155f4592d8f6a1-3-build%2FABCDEFGH) , and the panic itself is caused by the fact controller's `StartAlgod` inner goroutine calls asserts after the test itself is terminated. For some reason we do not get any log output in case of panic and my current suggestion it is because of STDOUT buffering and panic just flushes STDERR with its own message.
This PR does not prevent the race itself but makes it much less probable by deferring logs dumping to after asserting.
A proper fix is somewhat complicated because the controller object copying/modifying, and `StartAlgod` is called on a different object than …
=> tests: dump logs at the end of exit callback

.github/workflows/codegen_verification.yml, daemon/algod/api/Makefile, daemon/algod/api/README.md
This updates the Makefile in daemon/algod/api to support setting a different SWAGGER_CONVERTER_API, and starts up a Github workflow service container for `swaggerapi/swagger-converter` when running the codegen_verification job.
Check codegen_verification Github job to make sure it works.
=> build: support SWAGGER_CONVERTER_API override

config/localTemplate.go, logging/cyclicWriter.go, logging/cyclicWriter_test.go, util/io.go, util/io_test.go
This PR contains a bugfix for renaming files across devices.
Unit tests added
=> Utils: Renaming files across devices

network/p2pNetwork.go, network/p2pNetwork_test.go, network/wsNetwork_test.go
There was a bug in wantTXGossip setting [here](https://github.com/algorand/go-algorand/pull/5935/files#diff-4e519aba1b9b7f153328113f57806378cef2b400953324e9de025130c2eaabd4R669), forcing relays to unsubscribe from TX traffic.
Additionally added a missing `gossipSubPeer.OnClose` needed in txHandler.
Updated wantTXGossip unit test.
=> p2p: fix wantTXGossip modifications

test/e2e-go/features/incentives/payouts_test.go, test/e2e-go/features/incentives/suspension_test.go
Trying to make incentives tests less flakey.
Test change
=> Tests: Fix flakey incentive e2e tests

ledger/acctdeltas_test.go, ledger/acctonline.go, ledger/acctonline_test.go, ledger/acctupdates_test.go, ledger/ledger.go, ledger/ledgercore/accountdata.go, ledger/store/trackerdb/data.go, ledger/store/trackerdb/dualdriver/accounts_reader_ext.go, ledger/store/trackerdb/generickv/accounts_ext_reader.go, ledger/store/trackerdb/interface.go, ledger/store/trackerdb/sqlitedriver/accountsV2.go
Use `basics.OnlineAccountData` instead since they are exact duplicates.
Merge after https://github.com/algorand/go-algorand/pull/5757 due to conflicts
=> refactor: remove ledgercore.OnlineAccountData

test/e2e-go/features/incentives/payouts_test.go, test/e2e-go/features/incentives/suspension_test.go
Don't try to use such a fast consensus in nightly tests
=> Tests: Stabilize nightly tests.

data/transactions/payment.go, data/transactions/payment_test.go, data/transactions/transaction.go, ledger/apply/payment_test.go
While discussing https://github.com/algorand/go-algorand/pull/5757 we found there is a duplicate `checkSpender` in `ledger/apply` and `data/transactions`. The duplicate was fixed in #5757 and this PR moved `TestCheckSpender` to `data/transactions` to where `checkSpender` is defined.
=> tests: move TestCheckSpender to transactions package

crypto/batchverifier.go, crypto/batchverifier_test.go, crypto/multisig.go, crypto/onetimesig.go, data/transactions/verify/txn.go, data/transactions/verify/txnBatch.go
This changes the BatchVerifier to be an interface type, with a cgoBatchVerifier implementation, with a goal towards enabling an alternate pure Go implementation later in a future PR.
=> crypto: convert BatchVerifier to interface

scripts/buildnumber.py
Running `make` will get this deprecation warning for newer versions of python:
```
./scripts/buildnumber.py:13: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
d1 = datetime.utcnow()
```
This is because utcnow is timezone-aware, and the earlier datetime call is naive. To make this consistent, we just mark all to UTC, to make consistent with the comment for setting the epoch.
Verified that `./scripts/buildnumber.py` returned output without deprecation warnings.
Verified on 3.12.2 and 3.8.10 (version shipped with Ubuntu 20.04).
=> Scripts: update buildnumber to use timezone-aware datetime

ledger/catchpointfilewriter_test.go
`TestExactAccountChunk` compares MT stats on different components of a `DoubleLeger`. Sometimes these two might flush different number of rounds to disk causing different MTs (and catchpoint).
Force flushing and waiting should after should minimize such discrepancy.
This is a fix to unstable `TestExactAccountChunk` that should pass.
Run multiple times locally and on CI.
=> tests: fix TestExactAccountChunk

test/e2e-go/features/incentives/suspension_test.go
Failure:
```
fixture.go:120: 
Error Trace:	/opt/cibuild/project/test/e2e-go/features/incentives/suspension_test.go:122
Error:      	Not equal: 
expected: 0x0
actual  : 0x1
Test:       	TestBasicSuspension
```
Fix is to sync all test clients before proceeding, the same idea as #5986
=> tests: make e2e TestBasicSuspension less flaky

test/e2e-go/features/incentives/payouts_test.go
Similarly to #5995 sync fixture and test client.
Flaky test fix
=> tests: make TestBasicPayouts less flaky

components/mocks/mockNetwork.go, data/txHandler.go, network/gossipNode.go, network/hybridNetwork.go, network/multiplexer.go, network/p2pNetwork.go, network/p2pNetwork_test.go, network/wsNetwork.go
* Added `MessageProcessor` similar to `MessageHandler` but working in two stages: validate and handle
* Split `processIncomingTxn` txhandler method into two validate + handle
* This allowed to use gossipsub's validate and handing framework as intended.
* Existing tests should work
=> p2p: refactor gossipsub to validation and handling

logging/log.go
Fix for the following data race seen in [tests](https://app.circleci.com/pipelines/github/algorand/go-algorand/18323/workflows/b4bc8ccb-dc50-4c08-9a3d-50ba0e7f32cb/jobs/271397/tests):
```
=== RUN   TestVoteAggregatorFiltersBundlePresent
==================
WARNING: DATA RACE
Read at 0x00c0005e3260 by goroutine 483304:
github.com/sirupsen/logrus.(*Entry).write()
/opt/cibuild/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:286 +0x23e
github.com/sirupsen/logrus.(*Entry).log()
/opt/cibuild/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:251 +0x964
github.com/sirupsen/logrus.(*Entry).Log()
/opt/cibuild/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:293 +0x8b
github.com/sirupsen/logrus.(*Entry).Logf()
/opt/cibuild/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:338 +0xd8 …
```
=> logger: fix data race in tests

cmd/netgoal/network.go, netdeploy/remote/deployedNetwork.go, test/testdata/deployednettemplates/recipes/bootstrappedScenario/Makefile, test/testdata/deployednettemplates/recipes/bootstrappedScenario/recipe.json, test/testdata/deployednettemplates/recipes/scenario1s/Makefile
=> Typos: Correct some spelling mistakes

agreement/proposalManager.go, catchup/catchpointService.go, catchup/universalFetcher.go, cmd/goal/application.go
=> chore: fix non-exported function names in comments

data/transactions/logic/crypto_test.go
Fix flakey ECDSA testing, where a signature component had a leading zero byte, so `big.Int.Bytes()` produced a 31 byte slice.
The failing job: https://app.circleci.com/pipelines/github/algorand/go-algorand/18380/workflows/1d84e0b5-2ad9-4ac7-94cf-5c6315ac7138/jobs/272246
Test only fix
=> Tests: Fix flakey ECDSA testing

.circleci/config.yml, CODEOWNERS
We occasionally see memory issues with e2e tests, so let's switch from medium (2 CPU, 7.5 GB) to large (4 CPU, 15 GB). This is at the cost of more credits usage, obviously. This is for e2e_expect and e2e_expect_nightly.
Unrelated: also remove CODEOWNERS file, which is deprecated.
See if nightlies succeed.
=> CICD: Update to switch e2e_expect to large

test/packages/test_release.sh
The script to test releases was breaking due to the recent deprecation of CentOS Stream 8. In here, we update the list of supported OSes. We also do not try to install curl on Fedora and CentOS, because they are deprecated.
Verify this fixes nightly uploads.
=> CICD: update OS support in test release script

test/scripts/e2e_client_runner.py
Fix e2e KMD timeout in tests, introduced by the latest Python SDK release, 2.6.0, which included https://github.com/algorand/py-algorand-sdk/pull/527
Tests should pass
=> Tests: Fix e2e kmd timeout

network/wsNetwork.go, network/wsPeer.go
This adds additional performance metrics split by tag for message handler calls, for calculating average duration per call per tag.
=> metrics: Add TagCounterFiltered metrics for handler calls

test/scripts/e2e_subs/htlc-teal-test.sh
Fix for flakey htlc test, which is comparing exact account balance. I believe sometimes rewards are applied, so it's off by a small amount. Fixed this by comparing to the minimum expected amount of algos.
Example of a failure: https://app.circleci.com/pipelines/github/algorand/go-algorand/18425/workflows/259ccdba-c6c1-4093-abd9-e0c59e22a0d3/jobs/272733
=> Tests: Fix flakey htlc test

data/txHandler.go, data/txHandler_test.go
ERL's capguard was not disposed properly in some scenarios that leaded to under or over provisioned capacity.
Added a unit test.
=> txHandler: fixes to ERL resources management

agreement/pseudonode.go
While debugging some delayed consensus on network startup I noticed `VoteBroadcast` and `ProposalBroadcast` do not log player state like other events ({Vote|Proposal}Accepted, VoteAttest, ProposalAccepted etc do).
This PR adds player's Round, Period, Step logging for these events.
Local run
=> agreement: log current player state for VoteBroadcast and ProposalBroadcast events

test/scripts/e2e_subs/goal/goal.py
e2e subs fix similar to https://github.com/algorand/go-algorand/pull/6016
e2e subs must pass
=> tests: set communication timeout in kmd.init_wallet_handle

tools/network/cloudflare/createRecord.go, tools/network/cloudflare/updateRecord.go
Cloudflare deprecated a few data fields on SRV records, relying on a name field incorporating them. This PR updates the Cloudflare library utility to remove the deprecated data fields and add a Name field. See also:
https://developers.cloudflare.com/fundamentals/api/reference/deprecations/#name-related-data-fields-on-srv-dns-records
Tested using internal tooling to verify functionality.
=> Tools: Fix Cloudflare SRV update utility after API change

ledger/ledger_test.go, ledger/tracker.go, ledger/tracker_test.go
`TestVotersReloadFromDiskAfterOneStateProofCommitted` had two issues:
1. Deadlock when assertion failed with lock taken, this prevented ledger to close. Fixed by scoping `Lock()` and `defer Unlock()`
2. Two parallel commit scheduling and handling (one is a normal via `newBlock` + `commitSyncer` and a manual one via `triggerDeleteVoters`) led to the `unable to advance tracker db snapshot (775-778): UNIQUE constraint failed: onlineroundparamstail.rnd` error when two `commitRound` are called concurrently. Usually `commitRound` tolerates such issues by adjusting the commit ranges on retries, but if there is no new blocks or manual sync it is never re-attempted so that committing machinery does not advance voters so the test expectation fail (that lead to the deadlock from (1)).
To reproduce …
=> tests: fix TestVotersReloadFromDiskAfterOneStateProofCommitted

test/framework/fixtures/libgoalFixture.go
LibGoalFixture sometimes [detects](https://circleci.com/api/v1.1/project/github/algorand/go-algorand/273140/output/114/3?file=true&allocation-id=6667a362d7abf560ca960194-3-build%2FABCDEFGH) node termination error but it panics since test assert is called after test's main goroutine termination:
```
panic: Fail in goroutine after TestCatchupOverGossip/ledger=,fetcher=2.1 has completed
```
So that we observe this panic message instead an actual debug output with error code and node.log content. This PR changes the sequence - log all available info first and only then assert and fail.
This is a test harness change.
=> tests: debug output on LibGoalFixture failure

data/transactions/logic/assembler_test.go, data/transactions/logic/eval.go, data/transactions/logic/eval_test.go, data/transactions/logic/fields.go, data/transactions/logic/fields_string.go
Create global constants for some of the protocol constants introduced with the block incentive mechanism.
Resolves https://github.com/algorand/go-algorand/issues/5998
=> AVM: Expose relevant incentive constants

test/framework/fixtures/libgoalFixture.go
The test [failed again](https://app.circleci.com/pipelines/github/algorand/go-algorand/18495/workflows/19523b0e-596a-478a-b1b6-ebcf5f649eaa/jobs/273286) and again there is no debug info, probably because either test logger gone or some flushing issue.
Using `fmt.Fprintf(os.Stderr, ...)` should take take about both about possibilities.
This is a test harness change.
=> libgoal: output debug info on failure to stderr

docker/releases/build_releases.sh
Due to dependency changes, the latest Ubuntu version will break in the legacy docker build. This change pins to Ubuntu 22.04, and specifies the specific build platform (linux/amd64).
Manually executed.
=> Legacy Docker: pin ubuntu version

daemon/algod/server.go
Log warning if EndpointAddress and NetAddress has identical ports.
This can happen in a scenario where NetAddress is set to listen to port 0.0.0.0:8080, and where no EndpointAddress is defined. In that case NetAddress is set to listen to 127.0.0.1:0 (port 0 being random OS assigned port in a specific range), however the `makeListener` func in `daemon/algod/server.go` has logic that sets the port to be port 8080 in case port 0 is provided (https://github.com/algorand/go-algorand/blob/master/daemon/algod/server.go#L256).
This will result in the following:
* REST API will be accepting incoming connections on 127.0.0.1:8080
* Gossip protocol will be accepting incoming connections on 0.0.0.0:8080, which will result in it binding to port 8080 for all IP's but 127.0.0.0.1
If you are like me this …
=> config: Add warning if EndpointAddress and NetAddress ports are equal

agreement/service.go, catchup/catchpointService.go, catchup/service.go, data/txHandler.go, netdeploy/network.go, network/wsNetwork.go, node/impls.go, node/node.go, nodecontrol/algodControl.go, rpcs/blockService.go, rpcs/ledgerService.go, rpcs/txSyncer.go, stateproof/worker.go, test/e2e-go/features/catchup/basicCatchup_test.go, test/framework/fixtures/libgoalFixture.go
With extra logging the most [recent failure](https://circleci.com/api/v1.1/project/github/algorand/go-algorand/273414/output/114/3?file=true&allocation-id=666a47e1298ab20d75fcf5c4-3-build%2FABCDEFGH) showed node cannot stop properly but by the time of detecting this all data dirs (and logs) are gone since the test itself competed OK.
This PR propagates facts about how a node was terminated (term vs kill) so LibGoalFuxture can know it and preserve node.log for future analysis.
Also added debugging logs into `node.Stop` since it appears to be blocked by some service, and corrected missing new lines in LibGoalFixture stderr logging.
Tested manually: made algod not reacting to SIGTERM, node controller used SIGKILL. This was logged and data dirs with logs remained preserved.
=> tests: preserve logs on LibGoalFixture failure

data/txHandler.go, network/gossipNode.go, network/multiplexer.go, network/p2pNetwork_test.go
Based on review comment in https://github.com/algorand/go-algorand/pull/5939#discussion_r1643340427 a small tweak to multiplexer to deduplicate RegisterProcessors/RegisterHandlers with generic implementation, making everything generic in that file. Also changes name to avoid conflict with builtin `clear` function.
=> p2p: convert additional Multiplexer method to use generic implementation

catchup/service.go, test/e2e-go/features/catchup/basicCatchup_test.go
* Add context cancellation check to fetchRound peers retrieval loop
* This prevented some e2e tests to finish when a other nodes quit but the last node fell into catchup mode
* Revert debug logging in `TestCatchupOverGossip` from https://github.com/algorand/go-algorand/pull/6030
Diagnosed with debug logging in `TestCatchupOverGossip`: catchup service attempted to stop but never finished while keep logging entries below until it got killed.
```json
{
"Context": "sync",
"file": "service.go",
"function": "github.com/algorand/go-algorand/catchup.(*Service).fetchRound",
"level": "debug",
"line": 762,
"msg": "fetchRound: was unable to obtain a peer to retrieve the block from",
"name": "127.0.0.1:0",
"time": "2024-06-20T01:23:49.586961Z"
}
```
Existing tests
=> catchup: do not loop forever if there is no peers

.circleci/config.yml
As per [CircleCI's announced deprecation](https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718) the Mac AMD64 resource class is being deprecated. As a result we should disable these tests.
This PR also switches to using CircleCI's mac resources, instead of a self-hosted runner.
There is a larger question of how much support we should provide to Intel architecture in general. The last Intel mac was discontinued a year ago. A universal build like in #6023 would obviate the need for AMD64 build platforms and dealing with XCode deprecations, but would lead to insecurity about validity of tests.
Force nightly tests to execute against this branch.
*Note:* the test failure is from running the nightly execution, and the failure is unrelated to this change. It can …
=> CICD: remove mac AMD64 support from circleci

agreement/fuzzer/networkFacade_test.go, agreement/gossip/network_test.go, components/mocks/mockNetwork.go, config/localTemplate.go, config/local_defaults.go, daemon/algod/server.go, data/txHandler.go, installer/config.json.example, logging/log.go, netdeploy/remote/nodecfg/nodeDir.go, network/connPerfMon_test.go, network/gossipNode.go, network/hybridNetwork.go, network/limitcaller/rateLimitingTransport.go, network/p2p/dnsaddr/resolve.go, network/p2p/http.go, network/p2p/logger.go, network/p2p/peerstore/peerstore.go, network/p2p/peerstore/peerstore_test.go, network/p2p/pubsub.go, network/p2pNetwork.go, network/p2pNetwork_test.go, network/phonebook/phonebook.go, network/wsNetwork.go, node/node.go, node/node_test.go, test/testdata/configs/config-v34.json, util/metrics/opencensus_test.go
Addressed most code review items from https://github.com/algorand/go-algorand/pull/5939
Additionally fixed two data races: 
1. peerstore data race seen in [this build](https://app.circleci.com/pipelines/github/algorand/go-algorand/18574/workflows/aacb840e-dceb-4455-ad89-f2530ac35df7/jobs/274104)
2. logrus.Formatter concurrent access seen locally
Also fixed node.ledger descriptors leak that prevented `./nodetest -race` to pass due to extra connection opened by libp2p
Remaining items:
=> p2p feature PR: CR fixes

data/pools/transactionPool.go, ledger/notifier.go, node/node.go
* node_test runs multiple nodes in a single process that leads to file descriptors leak (see #5057 for more details).
* just closing ledger is not enough because of concurrent operations evaluation operations done by transaction pool.
* made transaction pool shutdown-able and stop it before ledger termination.
<details><summary>Deadlock example as seen in <a href="https://app.circleci.com/pipelines/github/algorand/go-algorand/18590/workflows/351f0ff3-6c92-42bb-8b66-afe7072d3435/jobs/274266">this p2p build</a></summary>
<pre>
POTENTIAL DEADLOCK:
Previous place where the lock was grabbed
goroutine 412 lock 0xc0006fe300
node.go:446 node.(*AlgorandFullNode).Stop { node.mu.Lock() } <<<<<
node_test.go:938 node.TestNodeHybridTopology { } }
Have been trying to lock it again for more than 30s …
=> node: close ledger and part keys on node shutdown

data/txHandler.go, network/p2p/capabilities.go, network/p2p/capabilities_test.go, network/p2pNetwork.go
1. Do not run ERL in p2pNet tx handler - libp2p has own congestion control mechanism, plus we are using pubsub.
2. Log `dht.Close()` errors if any.
Existing tests
=> p2p: more CR fixes: ERL and DHT err logging

config/version.go, daemon/algod/server.go
This PR adds algod version information to metrics exported. This will allow querying relay servers to see if they have updated to required / requested versions, and potentially be used to enforce SLA's around patching.
This PR does introduce a new namespace 'environment' for metrics, with reasoning being that this namespace is for exposing app-level runtime environment information, which currently is not exposed (outside of what Prometheus's node_exporter may provide at an OS level).
One label is used (version). I was thinking of splitting this up into labels with version (major.minor.patch), build, OS, arch, etc - however without having a clear use-case as to why this would be required I opted for simplicity. Happy to adjust as designated labels would be a more stable interface for …
=> Metrics: Add algod version to metrics

catchup/fetcher_test.go, catchup/pref_test.go, daemon/algod/api/server/v2/test/helpers.go, data/common_test.go, data/datatest/fabricateLedger.go, data/ledger.go, data/txHandler_test.go, ledger/ledger.go, ledger/ledger_test.go, ledger/notifier.go, node/assemble_test.go, node/follower_node.go, node/node.go, node/node_test.go, rpcs/blockService_test.go
* #6039 [discovered](https://circleci.com/api/v1.1/project/github/algorand/go-algorand/274376/output/114/2?file=true&allocation-id=667b6a1ffc7c6545c0d31136-2-build%2FABCDEFGH) blockNotifier preserves state between ledger reloads that breaks assumptions on how trackers work
* Made ledger to explicitly preserve block listeners in `reloadLedger`
* Also removed unused blockListeners argument from data.Ledger
Existing tests including `TestNodeTxHandlerRestart` and `TestNodeTxSyncRestart` passed locally.
=> ledger: restore block listeners on reloadLedger

agreement/gossip/network_test.go, components/mocks/mockNetwork.go, network/gossipNode.go, network/hybridNetwork.go, network/p2p/p2p.go, network/p2p/p2p_test.go, network/p2p/streams.go, network/p2pNetwork.go, network/p2pNetwork_test.go, network/requestTracker.go, network/requestTracker_test.go, network/wsNetwork.go, rpcs/ledgerService.go
Mentioned in #6042, the network interface has since #1390 required a method `GetHTTPRequestConnection` so that an HTTP handler could call SetWriteDeadline to set a request-specific write deadline. (It is used for setting a longer write deadline when serving large catchpoint snapshot files.)
In Go 1.20 per-request deadlines were added to the builtin HTTP library using [http.ResponseController](https://go.dev/doc/go1.20#http_responsecontroller), which makes it very easy to do from inside a HTTP handler. This makes the connection-tracking middleware in #1390 and #5924 to implement `GossipNode.GetHTTPRequestConnection` obsolete.
For reviewers: the deleted lines all come from #1390 and #5924, so if you open up those side-by-side you should be able to see what is being removed vs. what is being …
=> network: use http.ResponseController instead of GetHTTPRequestConnection

network/p2pNetwork_test.go
TestP2PRelay appears to be [flakey](https://circleci.com/api/v1.1/project/github/algorand/go-algorand/274717/output/114/0?file=true&allocation-id=66820196d08f7008069ba97e-0-build%2FABCDEFGH). Adding some more logging to see what's going on.
=> tests: extend TestP2PRelay logging

.circleci/config.yml
While uploads usually take on the order of minutes, for Mac ARM64 for some reason it's taking longer than 10 minutes. It's not clear if it's stalled or just needs more time.
This PR increases the default from 10m to 20m.
Should merge and see if it resolves nightly issues, as well as length of time for successful uploads.
=> CI: increase artifact upload timeout

network/p2pNetwork_test.go
`TestP2PRelay` failures ([one](https://app.circleci.com/pipelines/github/algorand/go-algorand/18671/workflows/c4558f67-3c74-431b-a7ca-12ea7e5b6503/jobs/274943), [two](https://app.circleci.com/pipelines/github/algorand/go-algorand/18675/workflows/870a58dc-aa1c-4abc-833e-a1980672c95b/jobs/275029)) indicate netC messages get lost. Most likely it is not enough time for pubsub to establish its mesh so increased wait time to stabilize the test.
=> tests: increase ListPeersForTopic wait time in TestP2PRelay

.github/workflows/reviewdog.yml
Reviewdog v.19+ started checking files not modified in PR and failing PR builds. This pins its version to the last known working.
Build should pass
=> ci: pin reviewdog version to v0.18.1

cmd/algod/main.go
In rare case of using phonebook only addresses AND enabling telemetry, telemetry DNS lookup would be skipped due to empty DNSBootstrapID.
Existing tests
=> algod: fix telemetry lookup if phonebook is used

ledger/ledger_test.go
`TestLedgerVerifiesOldStateProofs` uses manual account commit scheduling with automatic one that rarely brings tracker into invalid state as seen in this [build](https://app.circleci.com/pipelines/github/algorand/go-algorand/18689/workflows/e9507a50-9f65-4850-91f1-ed72477d7514/jobs/275110):
```
produceCommittingTask: block 3328 too far in the future, lookback 4, dbRound 3277 (cached 3320), deltas 8
2024-07-09T01:35:21.030105 +0000 level=error msg=[Stack] goroutine 346823 [running]:
runtime/debug.Stack()
/opt/cibuild/.gimme/versions/go1.21.10.linux.arm64/src/runtime/debug/stack.go:24 +0x6c
github.com/algorand/go-algorand/logging.logger.Panicf({0xc0000f42a0?, 0xc0008660a8?}, {0x2495c48, 0x65}, {0xc0041c29b0, 0x5, 0x5})
/opt/cibuild/project/logging/log.go:282 +0xb0 …
```
=> tests: fix concurrent accout commits in TestLedgerVerifiesOldStateProofs

network/p2p/p2p.go
This PR simply disables circuit relaying via libp2p.NoListenAddrs in either p2p or hybrid operating modes. More information on circuit relaying can be found at [https://docs.libp2p.io/concepts/nat/circuit-relay/](https://docs.libp2p.io/concepts/nat/circuit-relay/).
=> P2P: Disable circuit relaying via libp2p.NoListenAddrs

daemon/algod/api/server/router.go, test/e2e-go/restAPI/other/misc_test.go, test/framework/fixtures/libgoalFixture.go
Fix to #5625 where incorrect test with a client always using an adminToken lead to incorrect actual implementation.
Fixed an existing e2e test
=> rest api: Fix to Disable API authentication

cmd/algocfg/profileCommand.go, cmd/algocfg/profileCommand_test.go, config/config.go, network/p2p/p2p.go, network/p2pNetwork.go, network/p2pNetwork_test.go
Introduce configuration profiles for hybrid (WS+P2P support) relays, archival nodes, and part/non-participating role nodes. 
Unit tests were added in `profileCommand_test.go` for each new profile. All 3 configurations were tested being generated via algocfg CLI, with each also used on a running local node.
=> P2P: Introduce profiles for hybridRelay, hybridArchival, and hybridClient.

Makefile, go.mod, go.sum
This removes two messages seen when building on Macs with newer Xcode versions. It upgrades a dependency to fix the deprecation warning about C17 making ATOMIC_VAR_INT no longer necessary when initializing atomic integers. It also suppresses the benign message "warning: ignoring duplicate libraries" introduced by changes to the linker that Xcode 15 uses ([1](https://mjtsai.com/blog/2023/10/09/xcode-15-duplicate-library-linker-warnings/), [2](https://indiestack.com/2023/10/xcode-15-duplicate-library-linker-warnings/)).
=> build: quiet duplicate libraries and ATOMIC_VAR_INT messages

catchup/service.go
Should logging err value here as we have no access to the original cause for abort.
=> catchup: skip logging err for catchup cancellation

network/p2pNetwork.go, network/p2pNetwork_test.go
Some [TestHybridNetwork_DuplicateConn](https://app.circleci.com/pipelines/github/algorand/go-algorand/18782/workflows/9534087f-79ee-483a-aa3d-448bb2517267/jobs/275920) failures indicate deduplication does not work when a node first connects via wsnet and then via p2p. In this case p2p correctly determines duplicate but does not exit the handler as it should.
Added a unit test checking the stream handler processes duplication correctly.
=> p2p: fix connection deduplication in hybrid mode

data/appRateLimiter.go, data/appRateLimiter_test.go, data/txHandler_test.go
As discovered in https://github.com/algorand/go-algorand/issues/5972 the TestTxHandlerAppRateLimiter had a typo.
This PR fixed it by crafting workload to make sure ARL in txHandler is getting actually called.
While debugging I noticed that `maxBucketSize` is set to 1 if `TxBacklogAppTxRateLimiterMaxSize` is less than 128 (number of buckets). Although this was not an issue in production due to `TxBacklogAppTxRateLimiterMaxSize=1048576` it would trigger eviction on each insert that makes ARL noop. Setting `maxBucketSize` to 2 as its min value makes it working in such extreme configuration.
Closes #5972
=> txHandler: fix TestTxHandlerAppRateLimiter

node/node_test.go
It appeared the test struggled from two problems:
1. Node 0 has not discovered node 2 in time.
2. Node 1 was falling [behind](https://app.circleci.com/pipelines/github/algorand/go-algorand/18795/workflows/d34ef684-18a9-4092-9a5d-0c6dc63aa736/jobs/276036)
To fix (1) increased by test timeout. libp2p-kad-dht has non-configurable timeout of 2m for peers refresh in runFixLowPeersLoop. It looks like sometimes because of topology DHT does not have right peers in its routing table and max test wait time is not enough to update the routing table. My theory node0 discovers node2 very late and only have chance to download couple blocks. 1.5x wait time should allow DHT to rebuild routing second time (first is on a node startup) and give enough time node0 to catchup.
To fix (2) made node 1 and nod 2 …
=> tests: fix TestNodeHybridTopology

scripts/travis/build.sh, scripts/travis/deploy_packages.sh
Introduced a bug in #6071 because build deps are not in that stage.
Because we rebuild for the universal target for nightlies on darwin, we need build dependencies. This modifies deploy packages to call the build script to install for this case.
(Also removed a small case for linux-arm, since that's deprecated.)
Ran manually to ensure it triggered properly.
=> CI: fix mac universal rebuild for nightlies

catchup/universalFetcher_test.go, network/p2pNetwork.go
There was a possible race condition between starting a new wsPeer (that starts reading/writing goroutines), and registering this peer in `wsPeers` map. `wsNetwork.addPeer` had such check but `p2pNetwork.wsStreamHandler` missed it. See [failed test](https://app.circleci.com/pipelines/github/algorand/go-algorand/18825/workflows/e0dee9df-2676-4dd2-b5b7-1e1d6b520bb9/jobs/276234) logs for demo.
Additionally fixed asserts in catchup tests - on an error they were logging incorrect error object.
Discovered by a test added in https://github.com/algorand/go-algorand/pull/6082
=> p2p: do not register closing peer

scripts/release/mule/Makefile.mule
In #6071 the `build` dependency was removed from the `ci-build` target. This meant that it would not build the binary before trying to package up the files.
Ran ci-build from a containerized environment to verify.
=> CICD: fix broken ci-build target

ledger/acctupdates_test.go, ledger/blockqueue_test.go, ledger/ledger.go, ledger/ledger_test.go, ledger/tracker.go
Recent test failures ([one](https://app.circleci.com/pipelines/github/algorand/go-algorand/18713/workflows/3f6cd5f8-2ec2-4a8b-b6f5-0f9185f4eef6/jobs/275334/parallel-runs/29), [two](https://app.circleci.com/pipelines/github/algorand/go-algorand/18841/workflows/0a07a814-5acc-489a-9a5f-7e6f5645c37f/jobs/276383)) indicates `TestVotersReloadFromDiskAfterOneStateProofCommitted` it can hang on waiting tracker registry to close. Added debug logging to confirm or rule out this.
This is an extra debug log statements for `TestVotersReloadFromDiskAfterOneStateProofCommitted` investigation.
This is the same as https://github.com/algorand/go-algorand/pull/6066 that for some reason cannot be reopened.
=> tests: debug logging for TestVotersReloadFromDiskAfterOneStateProofCommitted

ledger/ledger_test.go
The test in question uses a combination of automatic commits and a manual commit triggering. Stopping commitSyncer in the middle of the test creates a race condition between enqueueing and consuming - it is likely a task enqueued after commitSyncer is done draining and exiting. This leaves us with one element in deferredCommits (that is OK) and one extra accountsWriting wait group element (not OK on close if commitSyncer is active). Given a later reloadLedger call leads to restarting commitSyncer, re-initalization the queue but preserving accountsWriting value that is one off and drives infinite wait on closing.
The fix is just updates the test to prevent the race above. It is also possible to reset accountsWriting in trackerRegistry.initialize but it looks useful to catch closing errors …
=> tests: fix flushing in TestVotersReloadFromDiskAfterOneStateProofCommitted

cmd/netgoal/network.go, netdeploy/remote/deployedNetwork.go
Add a new option `-i/--ignore` to `netgoal build` to suppress errors like `error building network files: error loading Network Config file 'net.json': config file contains unrecognized token: {{.Year}}` when using `LogArchiveName` templating in `ConfigJSONOverride`
Also renamed `ErrDeployedNetworkTemplate` error type to `deployedNetworkTemplateError` to match err val vs err type convention used in other parts of the code base (err- prefix for values, -Error suffix for types).
Tested locally
=> netgoal: allow unknown template tokens

test/heapwatch/agreement-log.py, test/heapwatch/topology-extract-ws-e2e.py, test/heapwatch/topology-extract-ws.py
1. Fix `agreement-log.py` to support e2e test output without `libgoalFixture.go` string prefix
2. Add `topology-extract-ws-e2e.py` similar to `topology-extract-[ws|p2p].py` for e2e test network mapping
These are debugging tools, tested manually on [this](https://circleci.com/api/v1.1/project/github/algorand/go-algorand/276592/output/114/1?file=true&allocation-id=66ac318d9631ca240dd7088b-1-build%2FABCDEFGH) `TestTotalWeightChanges` log
=> tests: fixes to e2e test logs parsers

test/scripts/e2e.sh, test/scripts/e2e_subs/goal-partkey-commands.sh
goal-partkey-commands was extremely buggy:
1. Uses non-initialized gcmd and INITIAL_ACCOUNT
2. Does not check if cmd fails (no `set -e`)
3. Part key command output parsing was invalid.
4. Sometimes it raced with some other test and failed to correctly compare part keys. This was fixed by binding goal cmd to a wallet (the runner creates unique wallets for each test).
Also added `TESTFILTER` handling to e2e-subs so it can run a single test now (similarly to expect tests).
This is a test fix, passed locally
=> tests: fix e2e subs goal-partkey-commands

network/hybridNetwork_test.go, network/p2p/p2p.go, network/p2p/p2p_test.go, node/node_test.go
When p2p net listens on all interfaces ("0.0.0.0:0", ":0", ":N"), it advertises everything including loopback and private interface addresses. The solution is to handle this specification and apply libp2p's AddressFactory filter.
Note, when some specific address is set like loopback or a private interface, it recognized as intentional action and no filters applied. This allows to all unit tests starting network on "127.0.0.1:0" to continue to operate, as well allows private nets to run if `NetAddress` is set appropriate (say to "10.1.0.101:0").
During algonet testing I found EC2 instances only have loopback and a private 172.31.x.x addresses so that filtered.
libp2p has address observation facility (part of netidentity) that reports addresses seen at least [4 …
=> p2p: do not advertise private and non-routable addresses

components/mocks/mockNetwork.go, data/transactions/verify/txnBatch.go, data/transactions/verify/txnBatch_test.go, data/txHandler.go, data/txHandler_test.go, network/gossipNode.go, network/hybridNetwork.go, network/multiplexer.go, network/p2p/pubsub.go, network/p2p/pubsubTracer.go, network/p2pNetwork.go, network/p2pNetwork_test.go, network/wsNetwork.go, test/e2e-go/features/p2p/p2p_basic_test.go, util/metrics/metrics.go
This is a draft implementation on how txHandler logic would look like if fully implemented in pubsub validator.
It loses batch verification part so could be a large performance drawback.
Tried an alternative approach where pubsub validator always returns `Ignore` and then tx handler calls `Relay`. This does not work since pubsub discards the second submission as a duplicate.
Extended e2e p2p test to send transactions
Run scenario1s-p2p: 6781.17 TPS
Resolves #6052
=> p2p: handle txns in pubsub validator

network/msgCompressor.go, network/msgCompressor_test.go, network/wsNetwork.go, network/wsNetwork_test.go, network/wsPeer.go, network/wsPeer_test.go
Remove wsnet proto=2.1 and optional compression since the entire network supports 2.2 and compressed PP messages.
I left couple commented out lines showing how to set and check features.
Existing tests
=> network: remove ws net proto 2.1

catchup/ledgerFetcher.go, catchup/universalFetcher.go, network/README-P2P.md, network/limitcaller/rateLimitingTransport.go, network/p2p/README.md, network/p2p/capabilities.go, network/p2p/capabilities_test.go, network/p2p/p2p.go, network/p2pNetwork.go, network/p2pNetwork_test.go, network/p2pPeer.go, node/node.go
1. Update `network/p2p/README.md`
2. Add `network/README-P2P.md`
While writing this doc found and fixed the following:
* Make some methods package-private since there is no clients for them.
* Handle `peer.GetHTTPClient()` returning nil since `MakeHTTPClient` for p2p net can err.
* Enable capabilities only if node is configured to listen.
=> docs: p2p package overview

network/p2p/capabilities_test.go, network/p2p/p2p.go, network/p2p/peerstore/peerstore.go, network/p2p/peerstore/peerstore_test.go, network/p2pNetwork.go, network/p2pNetwork_test.go, network/phonebook/phonebook.go
At some point `PeerStore` was though to implement `Phonebook` interface, and as part of this some methods had `interface{}` in signature to accommodate both `string` and `peer.AddrInfo`. It ended up exact interface match not needed so I'm reverting this `interface{}` workaround.
Actually it is possible to keep `addr []string` in `AddPersistentPeers` and `ReplacePeerList` since they operate on single-address `AddrInfo` so string to `AddrInfo` conversion is possible.
In the same time `GetAddresses` returns slice of either strings (`Phonebook`) or generic learned `peer.AddrInfo` from the underlying peerstore, and no multiple addr to string conversion possible.
Existing tests to pass
=> p2p: get rid of interface{} from PeerStore methods

cmd/updater/systemd-setup-user.sh, cmd/updater/systemd-setup.sh
The systemd setup right now does not support `algoh` installs, which can be useful for additional diagnostic information. This PR will replace launching algod with algoh.
Usage (e.g.):
```
./systemd-setup.sh -H ubuntu ubuntu
```
The `-H` option has to come first. This will replace occurences of algod with algoh in the systemd file.
Note that because of this, output from algod would no longer be recorded to syslog. This should be fine, because `algoh` usage is typically for servers that have enabled telemetry, and `node.log` remains in use.
Verified installation works both with and without `-H`. Verified killing `algoh` or `algod` restores service.
=> Installer: add support for algoh to systemd installs

network/netidentity.go
Fix [data race](https://app.circleci.com/pipelines/github/algorand/go-algorand/18972/workflows/2c7f7521-c114-43de-bd39-2686df64e607/jobs/277632) in hybrid mode when a shared `publicKeyIdentTracker.peersByID` is accessed from both p2p and ws net instances - added a mutex to `publicKeyIdentTracker`. Since net identity is called only on connect/disconnect (i.e. not very frequent), mutex is OK to use.
Existing tests
=> network: fix publicKeyIdentTracker data race in hybrid mode

config/consensus.go, protocol/consensus.go
Hardcoding the current `future` protocol as `fnet1` to prevent inconsistent views of the protocol in AF FNet
Experimental / Not to be merged to main
=> FNet: named current future protocol as "fnet1"

network/p2p/capabilities_test.go, network/p2pNetwork_test.go
There were [couple](https://app.circleci.com/pipelines/github/algorand/go-algorand/18996/workflows/11fa1b4b-d5d8-4447-b3c0-846d2e428be6/jobs/277884) [failures](https://app.circleci.com/pipelines/github/algorand/go-algorand/19002/workflows/45e8afeb-ca4a-4efd-b722-1ef8b5e5e32f/jobs/277925) in TestP2PwsStreamHandlerDedup caused by too early check on the second node - before it had a chance to handle connection closure and remove unsuccessful peer.
Additionally, there is also an attempt to fix `TestCapabilities_Discovery` that works on non-connected p2p hosts, manually adds peers to DHT routing table and then compares the table expected size.
Not sure what exactly it was testing (adding to routing table and checking its size looks unusual) but there is a race between `capD.dht.ForceRefresh()` …
=> tests: fix a race in TestP2PwsStreamHandlerDedup

.github/workflows/reviewdog.yml, scripts/travis/codegen_verification.sh, test/scripts/e2e_subs/goal-partkey-commands.sh
Since #6095 fixed issues with this test, it seems to fail occasionally with long goal outputs. This attempts to fix the issue like seen in https://app.circleci.com/pipelines/github/algorand/go-algorand/18982/workflows/7b9dc41e-1521-436c-afe2-6d365c07fb57/jobs/277753
Hopes to reduce occasional E2E test failures.
Adds a shellcheck in e2e_subs to CI that would have caught the bug found in #6095 where `${gcmd}` was being called without being defined.
=> tests: use temp file for capturing e2e goal-partkey-commands output

network/p2p/peerID.go
Before: p2p private key is stored raw in *.pem file. It is misleading since it does not contain an expected PEM content.
After: ED25519 key encoded as PKCS#8 ASN.1 DER and stored in PEM format, block type "PRIVATE KEY" in a *.key file.
Note: this implementation relies `libp2p/crypto`'s implementation details that it uses golang's standard `crypto.ed25519.PrivateKey` underlying representation. It looks OK since we already have the same assumption in `PeerIDChallengeSigner` implementation.
Existing tests passed
Checked `openssl` understand this key
```
goal node -d . generate-p2pid
[Data Directory: /data]
PeerID: 12D3KooWLwzibGo6GkGVnyasbfQxxcjng3QJEAqXgMTPm7VtG9TG
Private key saved to /data/peerIDPrivKey.key
goal node -d . generate-p2pid
[Data Directory: /data]
PeerID: …
```
=> p2p: store private keys as PKCS#8 ASN.1 DER PEM

network/limitcaller/rateLimitingTransport.go, network/limitcaller/rateLimitingTransport_test.go, network/p2p/http.go, network/p2pNetwork.go, network/p2pNetwork_test.go, network/wsNetwork.go, network/wsNetwork_test.go
While working on rate limiting functionality for libp2p HTTP clients in #5939 the existing WS net functionality was broken and never caught. This PR restores the functionality by making the `RateLimitingTransport` `RateLimitingBoundTransport` - i.e. requiring and enforcing the target peer address (either host:port or peerID). This makes sense since HTTP clients constructed as part of `wsPeerCore` are intended to be used against only this peer. This also means there is no shared `wn.transport` and `RateLimitingBoundTransport` objectare constructed on demand for http clients.
Fixes #6117
1. Added `RoundTrip` and `GetHTTPClient` unit tests
2. Checked devnet catchup
=> network: fix outgoing HTTP rate limiting

cmd/algons/dnsaddrCmd.go
For troubleshooting it's helpful to print the error in this algons subcommand.
Built and ran and found an error in invocation. :)
=> algons: expose error for dnsaddr command

Makefile, scripts/travis/codegen_verification.sh, test/e2e-go/cli/goal/expect/basicExpectTest.exp, test/e2e-go/cli/goal/expect/corsTest.exp, test/e2e-go/cli/goal/expect/expect_linter.py, test/e2e-go/cli/goal/expect/goalCmdFlagsTest.exp, test/e2e-go/cli/goal/expect/goalDryrunRestTest.exp, test/e2e-go/cli/goal/expect/goalExpectCommon.exp, test/e2e-go/cli/goal/expect/goalTxValidityTest.exp, test/e2e-go/cli/goal/expect/limitOrderTest.exp, test/e2e-go/cli/goal/expect/tealAndStatefulTealTest.exp, test/e2e-go/cli/goal/expect/tealConsensusTest.exp, test/e2e-go/cli/goal/expect/testInfraTest.exp
While looking why https://github.com/algorand/go-algorand/pull/6089 expect test did not work as expected, I found it copied the `expect` statement from the `CheckNetworkAddressForCors` function, and it does not perform check correctly ignoring the fact of missing expected output. 
I fixed that by added `eof` sub statement which is hit when no other statement executed previously and when there is no `exp_continue`. After that the test started failing since it was checking KMD headers without setting `allowed_origins` configuration option.
@cce also discovered the same issue in some other tests and added a linter.
=> tests: fix expect tests and add EOF linter

node/node_test.go, protocol/tags.go, protocol/tags_test.go
Better checks on max txn size that will work better as we make changes.
=> AVM: Derive looser, but more principled, checks of txn max size

network/p2p/http.go, network/p2p/p2p.go, network/p2pNetwork.go, network/p2pNetwork_test.go
libp2phttp server rejects to run when no listen addresses can be determined and no `ListenAddrs` provided. After filtering out all non-routable and private addresses via address factory in `host.Addrs()`, our http server failed to start since `host.Addrs()` returned empty.
Fixed by handling this situation explicitly in `MakeHTTPServer` and providing `0.0.0.0` via `ListenAddrs`.
Note, if `NetAddress` is set to some specific address, all this new logic is not executed - http server will start on the `NetAddress` interface as before this change.
Added an explicit unit test for this `NetAddress = ":0"` case
=> p2p: make sure p2p http server runs on all interfaces

config/config_test.go, config/localTemplate.go, network/hybridNetwork.go, network/hybridNetwork_test.go
Setting `NetAddress` and leaving `P2PHybridNetAddress` empty (and another way around) in hybrid mode might start a node with dual server-client mode that is not what operators expect.
Fixed by checking `NetAddress` and `P2PHybridNetAddress` for consistency if `EnableP2PHybridMode` is set.
Added new unit tests.
=> config: ensure both ws and p2p net running the same mode in hybrid

data/txHandler.go, network/gossipNode.go, network/hybridNetwork.go, network/p2p/http.go, network/p2pNetwork.go, network/p2pNetwork_test.go, network/wsNetwork.go, node/node.go, node/node_test.go
1. Fast catchup testing showed node did not clear p2p net handlers on fast catchup. Fixed.
2. Renamed `ClearProcessors` -> `ClearValidatorHandlers` to have consistent naming with `RegisterValidatorHandlers`
3. As a followup to a streaming HTTP server workaround #6123 - change aux listening on localhost only.
1. Added a new unit test to exercise `SetCatchpointCatchupMode`
=> node: clear new p2p net handlers on fast catchup

network/p2p/http.go, network/p2p/p2p.go, network/p2p/testing/httpNode.go, network/p2pNetwork.go, network/p2pNetwork_test.go
In some scenarios `GetPeers` for archival role gets called too often, and each time new libp2p.Host gets created that causes high memory usage.
Although this fix is good as is, the underlying issue with high `GetPeers` invocation rate is under investigation.
Tested manually against devnet.
=> p2p: reuse existing libp2p.Host for http clients

installer/rpm/algorand-devtools/algorand-devtools.spec, installer/rpm/algorand/algorand.spec
For ARM64, the agent will not run rpmbuild unless you remove the strip option.
Ran manually and verified it worked.
=> CI: fix rpmbuild call for cross-platform execution

.circleci/config.yml, scripts/configure_dev.sh
Nightly tests have been failing due to homebrew installation. We're attempting to fix this by not disabling homebrew upgrades.
The error we were getting was this:
```
Error: Failure while executing; `/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.3\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --fail --progress-bar --retry 3 --location --remote-time --output /Users/distiller/Library/Caches/Homebrew/Formula/libarchive.rb https://raw.githubusercontent.com/Homebrew/homebrew-core/da26dd20d93fea974312a0177989178f0a28d211/Formula/libarchive.rb` exited with 22. Here's the output:
curl: (22) The requested URL returned error: 404
```
The raw github URL here has a …
=> CI: remove homebrew autoupdate deactivation from CircleCI

config/localTemplate.go, config/local_defaults.go, daemon/algod/api/server/lib/middlewares/cors.go, daemon/algod/api/server/lib/middlewares/cors_test.go, daemon/algod/api/server/router.go, daemon/kmd/api/api.go, daemon/kmd/api/cors.go, daemon/kmd/config/config.go, daemon/kmd/kmd.go, daemon/kmd/server/server.go, installer/config.json.example, test/e2e-go/cli/goal/expect/corsTest.exp, test/e2e-go/cli/goal/expect/goalExpectCommon.exp, test/testdata/configs/config-v34.json, test/testdata/nettemplates/TwoNodes50EachPNA.json
During development of Algorand smart contracts and platforms users will often run local environments consisting of algod, kmd, and indexer via sandbox or more recently algokit. By default all of these services are running on local/private network addresses (e.g. 127.0.0.1), however popular tools such as [DappFlow](https://app.dappflow.org/explorer) and [Lora](https://lora.algokit.io/localnet) are hosted on public network addresses and require the user to specify their local endpoints. Additionally some dapps allow their users to provide their own endpoints for a _more_ decentralised experience.
Schedule for [Google Chrome 130](https://developer.chrome.com/blog/private-network-access-update-2024-03) (although many users are already experiencing it), PNA protections will be enabled by …
=> api: Add support for Private Network Access header preflight requests

scripts/install_linux_deps.sh
I just setup a brand new Linux machine (Debian 12) and ran through the usual install steps. But upon doing `make` I hit the following.
```
...
./scripts/check_golang_version.sh build
mkdir -p crypto/copies/linux/arm64
cp -R crypto/libsodium-fork/. crypto/copies/linux/arm64/libsodium-fork
cd crypto/copies/linux/arm64/libsodium-fork && \
./autogen.sh --prefix /home/steve/go-algorand/crypto/libs/linux/arm64 && \
./configure --disable-shared --prefix="/home/steve/go-algorand/crypto/libs/linux/arm64"  && \
make && \
make install
automake is required, but wasn't found on this system
make: *** [Makefile:169: crypto/libs/linux/arm64/lib/libsodium.a] Error 1
```
As for arch it seems as though `jq` has its own dependency on `automake` and would be installed, but I'm not sure about Fedora.
=> build: Add automake to linux dependencies

scripts/build_packages.sh, scripts/release/mule/sign/sign.sh
Some parts of the release pipeline do not account for the change in naming for the universal darwin binary. This PR addresses this.
Note that we also copy the universal binary to arch-specific named files. This is for backwards compatibility with the update.sh script.
The signing script in particular should run across all installs, as it handles it from a single platform. This means the host identifier is incorrect in this invocation.
Tested by manually running parts of this; should verify with the next stable release if merged before then.
=> CI: updates to fix publishing universal darwin binaries

test/scripts/go-hanging-test.py
`go test -v` output parser that helps to determine which test hangs in a suite. Supports both test output log and stdin.
Usage:
```
go test ./data/ -run TestTxHandler -v --timeout 5s | python3 test/scripts/go-hanging-test.py -t 5 -
```
This is a test script. Checked locally while debugging some tests issues.
=> tests: go test RUN/PASS output parser

cmd/algod/main.go, config/consensus.go, config/consensus_test.go
For Devnet and Betanet explicitly, support overriding the ApprovedUpgrades delay in consensus parameters during startup. When merged, this shortens the wait time in pre-release testing processes.
Added new test in consensus.go exercising initializing consensus params across 4 of our supported networks. All existing tests need to pass as well.
=> Consensus: For Devnet and Betanet, support custom network upgrade delay

scripts/install_linux_deps.sh
Support for building source in OpenSUSE Tumbleweed
Built with my local machine.
=> Tools: add support for developing in OpenSUSE Tumbleweed

data/transactions/logic/assembler.go, data/transactions/logic/assembler_test.go
During disassembly, if a contract includes a `pushbytess` opcode after the `bytecblock`, it will no longer overwrite the bytec disassembleState. This resulted in incorrect or missing comments for disassembled `bytec` opcodes.
Of course, there is still the issue of someone using `bytecblock` multiple times, however that's easier to identify. This threw me for a while.
Test program:
```
cat test.teal                                                  
#pragma version 10
bytecblock 0x6869 0x414243 0x74657374 0x666f7572 0x6c617374
bytec_0
bytec_1
bytec_2
bytec_3
bytec 4
pushbytess 0x6576696c
bytec_0
bytec_1
bytec_2
bytec_3
bytec 4
```
Before:
```
goal clerk compile test.teal -o - | goal clerk compile -D - 
#pragma version 10
bytecblock 0x6869 0x414243 0x74657374 0x666f7572 0x6c617374
bytec_0 // …
```
=> AVM: Only update the bytec disassembleState for bytecblock opcodes

network/metrics.go, network/metrics_test.go, test/heapwatch/metrics_aggs.py, test/heapwatch/metrics_gra.py, test/heapwatch/metrics_lib.py
A script to import heapWatch's high frequency metrics into local Prometheus. Requires direct data directory access.
How to use:
```
python3 ./go-algorand/test/heapwatch/metrics_gra.py -d metrics/500x15/ -o prom-metrics.txt
METRICS=$(realpath prom-metrics.txt)
cd ./prometheus-2.54.1.linux-amd64 && ./promtool tsdb create-blocks-from openmetrics $METRICS)
```
Then that Prometheus can be added as a Grafana source or used directly:
| Grafana | Prometheus |
|--------|--------|
| <img width="1195" alt="image" src="https://github.com/user-attachments/assets/68417b60-612e-4bb3-98bb-8e161840c138"> | <img width="1162" alt="image" src="https://github.com/user-attachments/assets/4f907795-ffa6-4974-ac68-7652b14ab387"> | 
=> tools: heapWatch metrics imported into Prometheus/Grafana

README.md
Styling and formatting updates for the main README.
N/A
=> Docs: Update README.md to be more concise 

daemon/algod/api/server/v2/handlers.go
MaxTealSourceBytes to 1M 
Fixes #6031
Test plan not needed. Just increases one constant to little bigger number so that the teal compilation proceed.
=> API: MaxTealSourceBytes to 512 kb

ledger/eval_simple_test.go, ledger/ledger.go
@jannotti noticed that in #6159 the GetKnockOfflineCandidates function was not retrieving the current round's OnlineAccountData when `0 < rnd < 240` because it was still returning the genesis balances — this fixes that.
Updated TestDoubleLedgerGetKnockoffCandidates to change two balances in round 1 and assert it is returned afterwards for rounds < 240.
=> incentives: update GetKnockOfflineCandidates to return current OnlineAccountData when rnd < 240

config/localTemplate.go, config/local_defaults.go, data/txHandler.go, installer/config.json.example, test/testdata/configs/config-v35.json
Following on #6167 this provides a configuration option (default disabled) to feed messages dropped by ERL (EnableTxBacklogRateLimiting) into ARL (EnableTxBacklogAppRateLimiting), so that all TX messages are counted by ARL, not just the ones that made it past the first pass of ERL's rate limiter.
Merging into a testing feature branch — existing tests should pass.
=> testing: add config flag for ARL to count all messages

data/transactions/logic/eval.go, data/transactions/logic/evalStateful_test.go, ledger/apptxn_test.go, ledger/boxtxn_test.go
Disassembling failed app transactions looks too expensive. Disabled for now.
=> eval: do not disassemble failed app transaction

data/pools/transactionPool.go, data/transactions/logic/eval.go, data/transactions/logic/evalStateful_test.go, data/transactions/logic/mocktracer/tracer.go, data/transactions/logic/tracer.go, ledger/apptxn_test.go, ledger/boxtxn_test.go, ledger/simple_test.go, ledger/simulation/tracer.go
In #6170 and #6171 the EvalError details were removed to avoid unnecessary disassembly for error messages. This adds a method to the EvalTracer interface to allow certain use cases (unit tests, DeveloperAPI enabled) to request the additional detail.
Old versions of unit tests asserting specific opcodes in EvalError messages should work again in this PR.
=> eval: add DetailedEvalErrors method to EvalTracer interface

agreement/gossip/networkFull_test.go
#6171 decreased MaxConnectionsPerIP default value and it is not enough for agreement/gossip tests.
Here is a failure [example](https://app.circleci.com/pipelines/github/algorand/go-algorand/19397/workflows/1e7afa79-249c-414e-827e-68187e778241/jobs/282014) for reference.
agreement/gossip tests pass
=> tests: Fix MaxConnectionsPerIP setting in agreement/gossip tests

.github/workflows/reviewdog.yml, .golangci-warnings.yml, data/transactions/logic/assembler.go
Changes how the reviewdog warning linter is configured (to match flags used by the reviewdog errors linter); changes cache key for loading previous builds of golangci-lint; and updates the gosec exclude list.
Should reliably make reviewdog warnings report on all builds.
=> CI: update reviewdog warning linter job

rpcs/ledgerService.go, util/execpool/backlog.go
fix some problematic function names
No need.
=> chore: fix some problematic function names

ledger/apply/heartbeat.go, ledger/eval/eval.go, ledger/eval/eval_test.go, ledger/eval_simple_test.go, test/e2e-go/features/incentives/suspension_test.go
=> Eval: Make the absenteeism factor = 20 instead of 10

heartbeat/service.go, heartbeat/service_test.go
=> Only heartbeat with current VoterID

data/bookkeeping/block.go
Update ProposerPayout description in block header to reflect that payout is applied in this specific block (vs a future one).
N/A
=> Comment: Payout Comment Tweak

crypto/onetimesig.go, data/transactions/heartbeat.go, data/transactions/msgp_gen.go, data/transactions/stateproof.go, data/transactions/transaction.go, data/transactions/transaction_test.go, data/transactions/verify/txn.go, data/transactions/verify/txn_test.go, data/txntest/txn.go, heartbeat/service.go, ledger/acctonline_expired_test.go, ledger/apply/heartbeat_test.go, ledger/eval/eval.go, ledger/eval/prefetcher/prefetcher_alignment_test.go, ledger/ledger_perf_test.go, node/node.go, tools/x-repo-types/typeAnalyzer/typeAnalyzer.go, util/set.go
Use a pointer to HeartbeatTxnFields instead of embedded the entire, large structure.
=> Waste less space in the main Transaction type

.github/workflows/reviewdog.yml
Intended to fix this message:
```
reviewdog: -fail-on-error is deprecated. Use -fail-level=any, or -fail-level=error for github-[pr-]check reporter instead.
```
Re-run CI
=> CI: update reviewdog config for deprecated fail_on_error

data/transactions/logic/TEAL_opcodes_v11.md
=> Doc: voter balance version fix

data/transactions/logic/README.md, data/transactions/logic/TEAL_opcodes_v11.md, data/transactions/logic/fields.go
=> Spec: typos and a payout detail

daemon/algod/api/client/restClient.go, libgoal/transactions.go, test/e2e-go/features/incentives/challenge_test.go, test/e2e-go/features/incentives/payouts_test.go, test/e2e-go/features/incentives/suspension_test.go, test/e2e-go/features/incentives/whalejoin_test.go, test/framework/fixtures/restClientFixture.go
Allows for more consistent communication with nodes during tests
This allows tests to keep talking to the same node, so that when they wait for a round, their next api call is sure to go to the node that has committed that round.  It also simplifies a lot of code that otherwise needs a RestClientFixture and a libgoal.Client.
=> Testing: Move WaitForConfirmedTxn down into clients

cmd/catchpointdump/database.go, cmd/catchpointdump/file.go, cmd/catchpointdump/net.go, ledger/acctdeltas_test.go, ledger/acctonline_test.go, ledger/catchpointfilewriter.go, ledger/catchpointfilewriter_test.go, ledger/catchpointtracker.go, ledger/catchpointtracker_test.go, ledger/catchupaccessor.go, ledger/store/trackerdb/dualdriver/dualdriver.go, ledger/store/trackerdb/generickv/reader.go, ledger/store/trackerdb/sqlitedriver/accountsV2.go, ledger/store/trackerdb/sqlitedriver/kvsIter.go, ledger/store/trackerdb/sqlitedriver/sqlitedriver.go, ledger/store/trackerdb/store.go
Follow-on to #6177.
When writing catchpoint files, the `catchpointFileWriter` currently does not have any access to the consensus parameters, and so does not know if `EnableOnlineAccountCatchpoints` is set. This means catchpoints files may contain chunks with `OnlineAccountRecordV6` and `OnlineRoundParamsRecordV6` even when `EnableOnlineAccountCatchpoints` is not set. However these objects are ignored when calculating the label — the catchpoint label hash calculation is conditioned on `EnableOnlineAccountCatchpoints`.
This adds an argument to `makeCatchpointFileWriter` so that `catchpointFileWriter` knows what the current consensus version is.
This also adds support to `catchpointdump` for analyzing and dumping the onlineaccount and onlineroundparams records in catchpoint files, and …
=> catchpoints: more support for EnableOnlineAccountCatchpoints

scripts/configure_dev.sh
There seems to be an issue on some Mac platforms installing llvm, a dependency of lnav, with homebrew. Removing lnav (a useful but not essential log file viewer tool) from the list of Mac dependencies resolves the issue.
No code change besides this configure_dev.sh script change.
=> CI: Remove lnav mac dev dependency

scripts/configure_dev.sh
This cherry-pick of the lnav dev tool removal to the beta branch to unblock CI testing.
N/A Not a code change
=> Dev Tools: remove lnav dependency from beta branch

test/e2e-go/features/incentives/challenge_test.go
More places where `fixture` and a client might be out of sync.
=> Testing: Moar unflaky

.circleci/config.yml, Makefile
MacOS 12 reached end-of-life on 11/30/2024 and no longer receives security updates. This upgrades the minimum supported MacOS version for builds to MacOS 13 (following Xcode SDK support listed in [this doc](https://circleci.com/docs/using-macos/)).
Attempt Mac builds using new Xcode SDKs provided by CI.
=> build: upgrade minimum MacOS version to 13

scripts/algorand_node_log.json, scripts/configure_dev.sh
Follow-on to #6221, add back lnav installation and configuration when running outside of CI.
No code changes.
=> CI: install lnav outside of CI environments

test/e2e-go/features/incentives/challenge_test.go
I believe this fixes another flaky possibility. In case it doesn't, it also adds a bit more logging to further debug.
=> Testing: Don't fail for heartbeat in same block as proposal

ledger/store/trackerdb/sqlitedriver/sqlitedriver.go, util/db/dbutil.go
This implements some PR feedback from @gmalouf in https://github.com/algorand/go-algorand/pull/6190#discussion_r1871891845 to remove an unnecessary extra function wrapper when using db.AtomicContext function 
=> DB: Remove AtomicContextWithRetryClearFn, rename to AtomicContext

cmd/catchpointdump/commands.go, cmd/catchpointdump/info.go, cmd/catchpointdump/net.go, test/e2e-go/features/incentives/challenge_test.go
This adds a new `info` command to catchpointdump, and adds the `file` command's `-d` and `-o` flags to the `net` command (a small change because `net` already shares code with `file`).
Tools only change, existing tests should pass.
=> tools: add -d and -o args for catchpointdump net, like file, new info command

config/consensus.go, ledger/acctupdates.go, ledger/applications_test.go
Cleaning up two consensus flags that were used to control behavior related to catchpoint versioning:
- EnableOnlineAccountCatchpoints is not checked or referenced in the code anywhere, and may now be removed.
- EnableAccountDataResourceSeparation has a misleading name and is renamed here to reflect what it actually does.
No logical code changes, just renaming; existing tests should pass.
=> config: remove unused EnableOnlineAccountCatchpoints consensus flag, rename EnableAccountDataResourceSeparation

.github/workflows/build.yml, .github/workflows/reviewdog.yml
For unknown reasons the error `Error: Unable to resolve action actions/cache@v3.4.0, package version not found` is appearing despite following instructions on the actions/cache README to use v3.4.0 (or upgrade to v4). This upgrades the actions/cache version for these two jobs to v4.
reviewdog.yml and build.yml jobs should run successfully
=> CI: upgrade to actions/cache@v4

ledger/catchpointfilewriter_test.go, ledger/simple_test.go, test/e2e-go/upgrades/application_support_test.go
1. TestApplicationsUpgradeOverGossip was not waiting for initial account funding. Fixed.
2. TestCatchpointAfterStakeLookupTxns uses `newSimpleLedgerFull` helper to create on-disk ledger and ended up polluting local work dir with ledger db files.
These are test fixes
=> tests: fix flaky TestApplicationsUpgradeOverGossip

ledger/catchpointfilewriter.go, ledger/catchpointfilewriter_test.go, ledger/catchpointtracker.go, ledger/simple_test.go, test/e2e-go/upgrades/application_support_test.go
This release is a follow-up to [v4.0.1](https://github.com/algorand/go-algorand/releases/tag/v4.0.1-stable). It fixes an occasional issue with catchpoint file consistency. Additionally, a change to requesting block headers from the API was included, to fix issues generating downstream SDKs.
* Update to catchpoint generation
* Move block header requests to block endpoint and make cert and paysets optional
* Devmode: zero out ProposerPayout when Proposer not set
* Build: upgrade minimum MacOS version to 13 ([#6223](https://github.com/algorand/go-algorand/pull/6223))
* Catchpoints: log ledger download failures ([#6227](https://github.com/algorand/go-algorand/pull/6227))
* Comments: Correct deadline comment issue#6201 ([#6241](https://github.com/algorand/go-algorand/pull/6241))
* Db: Remove …
=> go-algorand 4.0.2-beta Release PR

test/e2e-go/upgrades/application_support_test.go
Fix TestApplicationsUpgradeOverREST similarly to https://github.com/algorand/go-algorand/pull/6251
This is a flaky test fix
=> tests: fix flaky TestApplicationsUpgradeOverREST

docker/README.md, docker/files/run/run.sh
This commit introduces the TELEMETRY_URL environment variable to specify a custom endpoint for telemetry reporting when TELEMETRY_NAME is set. The README has been updated with details, and the run.sh script now handles configuring the telemetry endpoint if the variable is provided.
Nodely now offers a telemetry service for node runners, but to use, you must change the telemetry endpoint.  This change adds a new env. val that can be set to override the telemetry endpoint without having to mount a custom logging.config. 
Setting both TELEMETRY_NAME and TELEMETRY_URL is necessary to enable.
=> Config: Add TELEMETRY_URL support for telemetry configuration

data/txHandler.go
The `(!isCMEnabled && congestedERL)` condition in [incomingMsgErlCheck](https://github.com/algorand/go-algorand/blob/master/data/txHandler.go#L642) added [at some point](https://github.com/algorand/go-algorand/pull/6171/files#diff-e99aa9ea7548f8d632bcd018217876927f23e40a31f9328f0681e74f967d0753R637) to relief the spam congestion has the following side effect when:
1. per-peer reserved queue in ERL get exhausted
2. ERL's congestion manager (`isCMEnabled`) not enabled yet (it will be after the current `ConsumeCapacity` invocation)
3. shared capacity in ConsumeCapacity was successfully consumed
In this case the condition `(!isCMEnabled && congestedERL)` triggers congestion control to be enabled and dropping this message. In the same time consecutive messages would come through because …
=> txHandler: do not drop accepted mgs

data/ledger_test.go
https://github.com/algorand/go-algorand/pull/6190 introduced retry callbacks and the `TestLedgerErrorValidate` test with its in-memory ledger was not quite ready for receiving such message that is normal/expected for that kind of concurrent test like this with in-memory ledger.
=> tests: fix flaky TestLedgerErrorValidate

.github/workflows/codegen_verification.yml
Bump codegen verification action to run on Ubuntu 22.04.
Build should successfully run with updated version.
=> Build: Bump Ubuntu version in codegen_verification job.

cmd/goal/messages.go, cmd/goal/wallet.go
Adds this option to `goal wallet new`:
> -n, --non-interactive
> Create the new wallet without prompting for password or displaying the seed phrase
Skipping the password prompt is useful in scripted KMD creation.
The password prompt method for `goal wallet new`, which hides the input from the console, doesn't work with piping (unlike `goal account import`, which accepts `echo apple apple apple ... | goal account import`)
=> goal: non-interactive wallet creation with "wallet new --unencrypted --no-display-seed" 

cmd/goal/clerk.go, test/e2e-go/cli/goal/expect/goalLogicSigTest.exp, test/scripts/e2e_subs/tealprogs/int1.teal
I was attempting to submit a payment transaction from an account that was rekeyed to a logic sig address, but I experienced two issues.
1. The logic sig address would constantly replace my sender address when I included the logic sig, despite supplying a specific sender address I wanted to use.
2. The signer address was being completely ignored.
This PR fixes those two points by firstly only setting the sender address as the logic sig address if a sender address hasn't been provided, then secondly setting the transactions AuthAddr if a signer is set.
I pieced together an expect test that simulates my scenario by first rekeying a normal account to a logic sig, then submitting a second transaction removing that rekey by including the logic sig and a signer on the transaction.
=> goal: Improve logicsig with signer support for clerk send

network/p2p/peerstore/peerstore.go
Fix for a race condition seen in [this test run](https://app.circleci.com/pipelines/github/algorand/go-algorand/19939/workflows/70017b37-4d60-4521-a953-18e6ff8b4a4f/jobs/287160?invite=true#step-114-122791_120)
peerstore's `GetConnectionWaitTime` gets a peerstore entry, calculates number of `recentConnectionTimes` to remove and then calls `popNElements` that also gets the same entry from peerstore and attempts to remove number of entries calculated on the first copy.
Fixed by removing the `addressData` mutex and adding it to `PeerStore` itself. Otherwise all these `PeerStore` methods are racy.
Existing tests
=> network: fix peerstore Get/Put races

catchup/catchpointService.go, cmd/catchpointdump/net.go
1. Allow `catchpointdump` utility to download catchpoint files from p2p archival nodes
2. Fixed a typo in `checkLedgerDownload`
=> catchpointdump: support p2p nodes

network/p2p/http.go
Catchpoint downloading uses `http.Client` with `http.Request`'s context with timeout set to `MaxCatchpointDownloadDuration=43200` seconds. If p2p nodes do not respond, this context never expires so that `http.Client` waits for `MaxCatchpointDownloadDuration`.
Fixed by copying `libp2phttp.streamRoundTripper.RoundTrip` but using sensible context with timeout on `NewStream` call.
Closes #6265
Tested manually with `catchpointdump` and `goal node catchup`:
* `catchpointdump` successfully exits when run agains a node that does not respond
* p2p-only `algod` was fully caught up in under 2h
=> p2p: fix http RoundTripper

Makefile, crypto/batchverifier.go, crypto/vrf.go
On Mac, some compiler versions warn about duplicate libraries with:
```
ld: warning: ignoring duplicate libraries: '/path/to/go-algorand/crypto/libs/darwin/arm64/lib/libsodium.a'
```
In #6074 there was a version check to set a flag to not warn about duplicate libraries, but this PR removes the duplicate library definitions altogether from the LDFLAGS used. Before, there were 3 places where platform-specific LDFLAGS-setting lines appeared:
```
$ git grep '#cgo darwin,amd64 LDFLAGS'
crypto/batchverifier.go:// #cgo darwin,amd64 LDFLAGS: ${SRCDIR}/libs/darwin/amd64/lib/libsodium.a
crypto/curve25519.go:// #cgo darwin,amd64 LDFLAGS: ${SRCDIR}/libs/darwin/amd64/lib/libsodium.a
crypto/vrf.go:// #cgo darwin,amd64 LDFLAGS: ${SRCDIR}/libs/darwin/amd64/lib/libsodium.a
```
After this PR, there is only …
=> build: stop duplicate library LDFLAGS warning

catchup/classBasedPeerSelector.go, catchup/classBasedPeerSelector_test.go, catchup/peerSelector.go, catchup/service.go, network/gossipNode.go
Per #6152 there was an issue with catchup on P2P networks that ended up to be a peer selector (`classBasedPeerSelector`) issue. Suppose there are only two Relays and no Archival nodes, and only one of the relays have all the blocks, and a node in question does not have DHT enabled. In this case it will only get `ConnectedOut` and `PhonebookRelay` peers (that are the same) and attempts to catchup from them. The following will happen:
1. A relay without old blocks will be randomly selected and after couple of failures gets down ranked below a relay with blocks ( exact rank number is 3 but it does not really matter)
2. Then the second relay get selected and about a hundred blocks get downloaded from it (exact number is 79 until its rank reaches 3, see below)
3. `peerSelector` has a special …
=> catchup: improve classBasedPeerSelector on small peer sets

ledger/catchpointfilewriter_test.go
I recently this test fail on an unrelated PR:
```
=== FAIL: ledger TestExactAccountChunk/future_SPstall300 (5.12s)
catchpointfilewriter_test.go:910: 
Error Trace:    /opt/cibuild/project/ledger/catchpointfilewriter_test.go:910
/opt/cibuild/project/ledger/catchpointfilewriter_test.go:872
Error:          Not equal: 
expected: 0x320
actual  : 0x31f
Test:           TestExactAccountChunk/future_SPstall300
```
It seems the issue is that in #6214, I added an assertion that the DoubleLedger's two ledgers had committed the same round (on the rnd returned by `testCatchpointFlushRound`) BEFORE the code added to address flakiness in #5993 and wait until the two ledgers were caught up and in sync. (It makes sense that this 300-round subtest is the one that failed, since there were more rounds waiting …
=> test: fix flaky TestExactAccountChunk again

daemon/kmd/wallet/driver/ledger_hid.go, go.mod, go.sum
Having been unable to use a Ledger device with `goal` on Mac for many months I finally tracked down the issue. The HID Path length specifically on _my_ Mac was too long, and as a result was being replaced with an empty string `""`. This meant my Ledger would never show in `goal wallet list`, despite working everywhere else.
It turns out https://github.com/karalabe/usb embeds an old version of the https://github.com/signal11/hidapi implementation that uses Apple's [io_string_t](https://developer.apple.com/documentation/kernel/io_string_t) type for the [path](https://github.com/karalabe/usb/blob/8627268f6b0ac462d2f78166262404901a2d36e0/hidapi/mac/hid.c#L437).
After reading similar [issues](https://github.com/signal11/hidapi/issues/301) in various repos, it seems …
=> kmd: upgrade karalabe/usb to karalabe/hid

Makefile, scripts/check_golang_version.sh, scripts/get_golang_version.sh
If you run `go mod tidy` with newer versions of golang, it will automatically change the minimum version field in `go.mod`. Before, this would be e.g. `1.23`, but after update, it will change this to `1.23.0`.
Our bash scripts needed to be updated to take this into account. The following changes were made:
- Removed third parameter from `./scripts/get_golang_version.sh all`. This was so `./scripts/check_golang_version.sh` could check for go module support, so I just moved the version information there
- Updated Makefile to reflect this
- Fixed conditionals in `check_golang_version.sh` to properly compare semantic versions
Set a custom version in check_golang_version.sh and verified:
- 1.2.0 reported error
- 1.12.0 reported warning for `./scripts/check_golang_version.sh dev`
- 1.12.0 …
=> DevOps: fix golang version handling in bash scripts

daemon/algod/api/server/router.go, test/scripts/e2e_subs/api-compression.sh
This summary is longer than the change.  It enables `middleware.Gzip`.
e2e test ensures that it content encodes to gzip.
Do we need any performance test? I think gzip is so fast that there's nothing worth testing.
=> API: Enable gzip middleware and test for it

test/scripts/e2e_subs/box-search.sh
=> Test: Wait for the box list to be for the commit round

ledger/catchpointtracker.go
Following #6177, #6214, #6240, and #6253, this provides correct handling for nodes that are stopped and restarted while writing out the large "first stage" catchpoint file DB dump to disk. During this time, the value `trackerdb.CatchpointStateWritingFirstStageInfo` is set to 1.
If a node is restarted while the first stage is still writing to disk, in loadFromDisk/recoverFromCrash algod sees this flag, and deletes the old DB file, intending to replace it with a new one by calling `finishFirstStage` again. However, if the node's onlineaccounts table has more than 320 rounds of history in it (because the state proof worker had not yet finished processing the latest state proof), the argument passed is not correct. This leads to the error 
`couldn't initialize the node: …
=> catchpoint: handle loadFromDisk/recoverFromCrash during first stage correctly

Makefile
Node exporter is provided to optionally expose metrics for algod. This PR updates the binary with algorand/node_exporter#9 changes. The binaries were collected from the Github Actions artifacts.
The Darwin binaries were lipoed into a universal binary. The Makefile was updated so that if built from a universal target (which would set CROSS_COMPILE_ARCH) it should use universal target. A regular `make` should use the arch-specific target.
Verified `make` pulled an arch-specific target, while `make universal` pulled the universal target.
=> Node Exporter: update dependencies and add darwin universal support

cmd/catchpointdump/file.go, cmd/catchpointdump/net.go
This adds a -raw flag to the catchpointdump net and file subcommands, so you don't have to import the file to a SQLite DB before printing it out. Instead it decodes the msgpack chunk data directly and writes it to a file.
=> tools: Add catchpointdump msgpack decode feature

network/p2p/dht/dht.go
There was observed behavior when p2p node sometimes cannot stop (`goal node stop`) properly. It ended up to be `p2pNetwork.Stop` waiting meshThread to finish but it cannot because it is deadlocked in `FindPeer`.
<details><summary>Relevant stack traces</summary>
<p>
<pre>
goroutine 1 [semacquire, 1006 minutes]:
sync.runtime_Semacquire(0x1037ae720?)
runtime/sema.go:71 +0x2c
sync.(*WaitGroup).Wait(0x140009bb508)
sync/waitgroup.go:118 +0x74
github.com/algorand/go-algorand/network.(*P2PNetwork).Stop(0x140009bb008)
github.com/algorand/go-algorand/network/p2pNetwork.go:401 +0x1ac
github.com/algorand/go-algorand/node.(*AlgorandFullNode).Stop(0x140004ce308)
github.com/algorand/go-algorand/node/node.go:461 +0x130
github.com/algorand/go-algorand/daemon/algod.(*Server).Stop(0x14000795900) …
=> p2p: fix DHT FindPeer internal buffer size

network/p2pNetwork_test.go
Fix for the following data race:
```
==================
WARNING: DATA RACE
Read at 0x00c0005202b8 by goroutine 737:
github.com/algorand/go-algorand/network.TestP2PRelay.TestP2PRelay.func3.func7()
/home/runner/work/go-algorand/go-algorand/network/p2pNetwork_test.go:907 +0xb4
github.com/algorand/go-algorand/network.ValidateHandleFunc.ValidateHandle()
/home/runner/work/go-algorand/go-algorand/network/gossipNode.go:237 +0x121
go:struct { github.com/algorand/go-algorand/network.ValidateHandleFunc }.ValidateHandle()
<autogenerated>:1 +0x2a
Previous write at 0x00c0005202b8 by goroutine 731:
github.com/algorand/go-algorand/network.TestP2PRelay.TestP2PRelay.func3.func7()
/home/runner/work/go-algorand/go-algorand/network/p2pNetwork_test.go:907 +0x16b …
```
=> tests: fix TestP2PRelay data race

network/p2pPeer.go
Out P2P implementation does not close p2p connections so it is possible non-performant peers still have open service streams (incl. DHT and pubsub).
Existing tests
=> network: close p2p conn in CloseWithoutFlush

network/p2p/p2p.go, network/p2pNetwork_test.go
After merging https://github.com/algorand/go-algorand/pull/6308 the TestP2PEnableGossipService_BothDisable test became [unstable](https://app.circleci.com/pipelines/github/algorand/go-algorand/20392/workflows/f2348903-d1cf-4ff7-9b12-96337a7c9eed/jobs/291102?invite=true#step-114-5272358_72) because of a race condition between the check in the test and closing connection in `CloseWithoutFlush`.
Fixed by manually subscribing to `Connected` notification to make sure connections were made but still no peers due to `EnableGossipService=false` option.
=> tests: fix TestP2PEnableGossipService_BothDisable

network/vpack/rapid_test.go, network/vpack/vpack_test.go, test/partitiontest/filtering.go
Fuzz tests run as regular go tests on seed values (from f.Add()), so this updates those tests so they are not run unnecessarily when parallelizing tests in CI. 
Existing tests should pass, test verification job not show a messages like `github.com/algorand/go-algorand/network/vpack FuzzMsgpVote/seed#22308 -- ran 32 times. (Can probably be fixed by adding "partitiontest.PartitionTest()")`
=> CI: use partitiontest for Fuzz tests

data/basics/teal.go, data/basics/teal_test.go
It was not used anywhere. Presumably, it was written thinking that a StateDelta would be check after making it. But instead, each step of creating the StateDelta is checked.
I guess if it compiles, I was right!
=> Testing: Remove sd.Valid()

network/wsPeer.go
`wsPeer.readLoop` increment traffic counters after decompression that makes impossible to observe wire traffic decrease. Fixed by moving the decompression after the counters.
Existing tests
=> network: count received traffic before decompression

network/p2pNetwork.go, network/p2pNetwork_test.go, network/wsNetwork_test.go
Now that #6276 and #6312 have been merged, the configuration to enable vote compression needs to be wired up to the P2PNetwork implementation, and this is the missing initialization to do so.
Network performance testing, plus new unit test TestP2PVoteCompression.
=> network: enable vote compression for P2PNetwork

network/p2pNetwork_test.go
Fix a race between making connections and propagating peer info into peer store in TestP2PMetainfoExchange
=> tests: fix a race in TestP2PMetainfoExchange

network/metrics.go, network/wsPeer.go
As discussed in #6330 this adds new metrics `algod_network_received_uncompressed_bytes_{TAG}` and `algod_network_p2p_received_uncompressed_bytes_{TAG}` for use by wsPeer when receiving data.
Can perform manual testing
=> network: add "uncompressed bytes by tag" metric

crypto/statetrie/nibbles/nibbles.go, network/limitlistener/rejectingLimitListener_test.go, tools/debug/carpenter/main.go, util/bloom/bloom.go, util/watchdogStreamReader.go
In Go 1.21, the standard library includes built-in [max/min](https://pkg.go.dev/builtin@go1.21.0#max) function, which can greatly simplify the code.
=> refactor: use the built-in max/min to simplify the code

test/e2e-go/features/stateproofs/stateproofs_test.go
#6306 has a [typo](https://github.com/algorand/go-algorand/pull/6306/files#diff-3dee67ca393e9c5a293c0f41e38f26bfa06a0bc3f5250b2a8b371c685884accaR647) that affected number of rounds to wait in SPF connfirmations counting
=> tests: fix TestStateProofRecovery

heartbeat/service_test.go
Besides being improperly synchronized, its design was flawed.  It waited for a channel to appear in `l.waiters`, but that channel didn't last long, and could be missed once synchronization was added.
Instead conservatively wait.
=> test: waitFor was badly broken

ledger/ledger_test.go, scripts/export_sdk_types.py
We used to test CurrentVersion, now we test an old version, current version, and vFuture, which is a better test as we make development changes.
This also eliminates a funny source of flakiness, because the test randomly selects a different version to tuck into the header to test that it is detected as wrong. But if that random version has different rules about branch512, then it was causing a different failure than expected.
New test added for branch512 correctness
=> Testing: test vFuture, so we are exercising branch512

.github/workflows/ci-nightly.yml, .github/workflows/ci-pr.yml, test/scripts/e2e.sh
Test data gets uploaded nightly for other integration testing. This PR fixes the condition for this upload.
After merging, verify the nightly build will upload testdata.
=> CICD: fix uploading testdata in nightlies

.github/workflows/ci-pr.yml
The flags to run short tests were not correct in the GitHub Actions conversion of PR tests. This fixes that.
Additionally, parallelism was not enabled, and seems to have a pretty good effect at 4, so this was added.
These changes have the benefit of reducing PR checks in GitHub Actions to around 22 minutes.
Ran through GitHub Actions PR Tests multiple times. Please verify these work correctly on this PR as well.
=> CICD: fix short test flag and up parallelism

config/config.go, config/config_test.go, config/localTemplate.go, go.mod, node/node.go, node/node_test.go
As a first step to enabling p2p and hybrid mode make sure having `EnableP2PHybridMode=true` does not abort node starting but logs error message instead periodically.
Added a unit test to make sure the new log message appears in a log.
=> node: fallback to ws or p2p on hybrid misconfiguration

agreement/cryptoVerifier_test.go, agreement/persistence_test.go, agreement/pseudonode_test.go, catchup/peerSelector_test.go, config/config_test.go, daemon/algod/api/server/v2/test/handlers_test.go, data/bookkeeping/block_test.go, data/transactions/logic/evalAppTxn_test.go, data/transactions/logic/eval_test.go, data/transactions/verify/txn_test.go, ledger/apply/challenge_test.go, ledger/apptxn_test.go, ledger/eval/eval_test.go, ledger/simulation/simulation_eval_test.go, network/p2p/dnsaddr/resolve_test.go, network/p2pNetwork_test.go, test/e2e-go/cli/goal/account_test.go, test/e2e-go/features/catchup/catchpointCatchup_test.go, test/e2e-go/kmd/e2e_kmd_server_client_test.go, test/e2e-go/kmd/e2e_kmd_sqlite_test.go, test/e2e-go/restAPI/other/misc_test.go, test/e2e-go/restAPI/restClient_test.go, tools/network/dnssec/trustedchain_test.go
Remove 'Fail*' part from go test name so that 'Fail' is quickly searchable in test results.
This is test files change
=> tests: remove "Fail" part from test test names

network/p2pNetwork.go
Prevent p2p from exposing own telemetry ids.
Existing tests
=> network: do not use telemetry id for p2p nets

Makefile
After #6378 the universal targets for darwin builds was broken, due to the GOBIN refactoring.
This PR cleans this up by explicitly copying the NONGO_BIN files. Additionally, the clean target was edited to remove the cross-compilation directories.
Ran the following targets locally, after removing $GOBIN, $GOBIN-darwin-arm64, and $GOBIN-darwin-amd64 directories.
- make
- make install
- make universal
- make ci-build-universal
=> Dev: fix darwin universal targets

cmd/algofix/typecheck.go
There is a [new function](https://pkg.go.dev/maps@go1.21.1#Copy) added in the go1.21 standard library, which can make the code more concise and easy to read.
=> refactor: use maps.Copy for cleaner map handling

cmd/algod/main.go, config/config.go, config/config_test.go, config/migrate.go, daemon/algod/server.go
Add info-level log messages to show when configuration defaults for old versions are upgraded to the default for the latest config version.
Updated TestLocal_ConfigMigrateFromDisk show the new messages (with go test -v). Manually ran using goal/algod as well.
=> logging: log configuration migration messages

.github/workflows/ci-pr.yml
We neglected to include running CI-PR tests on pull requests to release branches. This fixes that.
Verify that pull request GitHub Actions tests work on release PRs.
=> CI: run PR tests on release PRs

.github/workflows/ci-nightly.yml
In #6397 branch-aware Go mod and build caching was added, with fallback to cache on the master branch. However the nightly workflow wasn't saving the cache for the master branch, because it was not updated to set the cache key prefixes.  This allows PRs to pick up a Go cache from the master builds on the first commit of a new PR branch.
=> CI: build Go cache on master merges

test/e2e-go/features/stateproofs/stateproofs_test.go
`TestTotalWeightChanges` creates a large network. It is known if multi-node network startup is delayed consensus struggles to agree on the first round because at some point better proposal emerges but can't make it way in time.
Increases timeout from 60 to 120 seconds to give the network more chances to succeed.
=> tests: increase wait timeout in TestTotalWeightChanges

config/consensus.go, data/transactions/logic/langspec_v1.json, data/transactions/logic/langspec_v10.json, data/transactions/logic/langspec_v11.json, data/transactions/logic/langspec_v12.json, data/transactions/logic/langspec_v2.json, data/transactions/logic/langspec_v3.json, data/transactions/logic/langspec_v4.json, data/transactions/logic/langspec_v5.json, data/transactions/logic/langspec_v6.json, data/transactions/logic/langspec_v7.json, data/transactions/logic/langspec_v8.json, data/transactions/logic/langspec_v9.json, data/transactions/verify/txn_test.go, ledger/testing/consensusRange.go, protocol/consensus.go
Consensus version v41 upgrade.
Existing tests should pass!
=> Consensus: Consensus version v41 upgrade.

shared/pingpong/pingpong.go
Fixes a regression introduced in #6286 where `constructAppTxn` in the `pingpong` perf testing tool's code was refactored to use the new `RefBundle` structure for txn.Access, but forgot to set the `sender` output arg. This caused `constructAppTxn` to always return an empty string, leading to "no acct" errors for all app calls in pingpong and 0 TPS for `stateful_teal_*` performance tests.
The fix adds the missing sender assignments:
- Initialize sender = from at the beginning of the opt-in logic
- Update sender = from when the from address is changed to use an already opted-in account
Tested manually, "no acct" error no longer appears.
=> pingpong: fix regression when making app calls

.github/workflows/ci-nightly.yml
Set CI_E2E_TEST_FILENAME in nightly build.
Run nightlies manually against this branch - test data should publish with correct name.
=> Build: Nightly test file naming fix

agreement/fuzzer/tests_test.go, agreement/gossip/networkFull_test.go, agreement/player.go, agreement/router.go, catchup/catchpointService.go, catchup/service.go, cmd/catchpointdump/file.go, crypto/onetimesig.go, daemon/algod/api/server/v2/test/handlers_resources_test.go, data/transactions/logic/eval.go, data/transactions/verify/txn_test.go, data/txHandler_test.go, ledger/acctdeltas_test.go, ledger/catchpointtracker.go, ledger/catchpointtracker_test.go, ledger/catchupaccessor_test.go, ledger/store/trackerdb/pebbledbdriver/pebbledriver.go, ledger/txtail.go, netdeploy/remote/deployedNetwork.go, network/limited_reader_slurper.go, network/limited_reader_slurper_test.go, network/msgCompressor.go, network/wsNetwork.go, shared/pingpong/pingpong.go, stateproof/db_test.go
This runs the official golang tool [modernize](https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize) with the `minmax` fix.
=> lint: run modernize minmax

agreement/fuzzer/ledger_test.go, config/consensus.go, crypto/merkletrie/cache.go, data/account/registeryDbOps.go, data/basics/serr.go, data/pools/transactionPool.go, data/transactions/logic/mocktracer/scenarios.go, ledger/acctdeltas_test.go, ledger/acctonline_test.go, ledger/acctupdates_test.go, ledger/eval/eval_test.go, ledger/ledgercore/statedelta.go, network/multiplexer.go, network/wsNetwork.go, shared/pingpong/accounts.go, test/e2e-go/stress/transactions/createManyAndGoOnline_test.go
This runs the official golang tool [modernize](https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize) with the `mapsloop` fix.
=> lint: run modernize mapsloop

ledger/eval/appcow.go, ledger/eval/appcow_test.go
This change makes it clearer that there is no sharing among the storageDeltas. There was no sharing, because each pointed to object was freshly allocated, but using a pointer obscured that fact (and performed a wasted allocation.
This change will make it easier (or at least clearer) to make changes to `maxCounts` if we allow transactions that update an app's global schema.
=> Eval: Make counts and maxCounts simple values, not pointers

agreement/pseudonode.go
This fixes missing votes telemetry with the telemetry enabled but logging level set to less than info level.
Verified by building and running the node on the mainnet. BaseLoggerDebugLevel = 0, telemetry enabled, checked votes on the Nodely dashboard.
=> agreement: Fix for missing votes telemetry with logging level less than info

ledger/acctonline_expired_test.go, ledger/apptxn_test.go, ledger/boxtxn_test.go, ledger/double_test.go, ledger/eval/eval.go, ledger/eval/eval_test.go, ledger/eval_simple_test.go, ledger/simple_test.go, ledger/testing/testGenesis.go
This adds an extra call to WellFormed to transaction evaluation (already run as part of txn validation & signature checking).
Fixed broken tests that were making transactions that failed the WellFormed check.
=> eval: call WellFormed from eval.transaction
