- scripts/promote_stable.sh
There was an error in promote_stable.sh
Noticed this while running the script earlier, it worked.
> Fix error in promote_stable script.

- agreement/voteAggregator.go
- scripts/promote_stable.sh
- util/metrics/counter.go
Fix a nit and run make sanity.
No functional changes.
> Minor cleanup

- .github/ISSUE_TEMPLATE/question.md
> Changetemplate

- scripts/configure_dev-deps.sh
Displays status of go get while running scripts/configure_dev.sh
> Show go get status

- crypto/passphrase/passphrase.go
- crypto/passphrase/passphrase_test.go
> -- Fixes issue #120

- installer/rpm/algorand.spec
- scripts/build_deb.sh
- scripts/build_packages.sh
- scripts/build_release_centos_docker.sh
- scripts/build_release_ubuntu_test_docker.sh
make .rpm have all the same binaries as .deb
note for the future to keep the lists in sync
> GOAL2-830 fix binaries in rpm

- cmd/goal/account.go
- cmd/goal/clerk.go
Define shared functions that wait for transaction commit and that write
out a transaction into a file.
> goal: factor out common logic in txn creation

- cmd/goal/inspect.go
> Clean up unneeded code in inspect.go

- daemon/algod/api/server/lib/common.go
- daemon/algod/api/server/router.go
- daemon/algod/server.go
> remove unused static file dir in api server code

- util/db/dbutil_test.go
Use a channel instead of an atomic busy-wait to sync test thread starts.
Clean up sqlite db files. (repeated testing eventually failed due to out-of-disk error)
Ran the test repeatedly for a while, it used to hit the intermittent crash after a few minutes but now I haven't seen a crash in much longer.
`while go test -count=50 github.com/algorand/go-algorand/util/db; do date; done`
> fix TestDBConcurrencyRW

- README.md
- agreement/README.md
- docs/agreement_service.md
Several new users have expressed difficulty understanding (or finding) documentation. This is hopefully an incremental improvement as we continue to work towards improving documentation.
Click the links and make sure the markdown works :crossed_fingers:
> Cleanup some doc ambiguity and cross link documentation. Issue #183

- THANKS.md
(please do not squash this PR)
> Add thanks file; add lost authorship information to prior commit

- Makefile
- cmd/genesis/newgenesis.go
- gen/generate.go
- netdeploy/networkTemplate.go
- netdeploy/remote/deployedNetwork.go
Now the output of "make" can fit in a terminal window without scrolling
off the top.
> reduce verbose messages from devnet/testnet key generation

- daemon/kmd/wallet/driver/ledger.go
Adding multisignature signing from a ledger nano s.
Manually tested multisignature transaction signing using both authorized and unauthorized Ledger Nano S devices.
> Adding multisignature signing

- Makefile
- scripts/check_deps.sh
- scripts/dump_genesis.sh
Partially helps with issue #230
> support multi-element $GOPATH enough to run "make"

- test/netperf-go/testdata/fullDeployStatTest.json
Some private repos were merged, updating path in puppeteer script.
> Update puppeteer link to ansible-playbooks.

- README.md
In particular, mention where to find the genesis.json files
> Add to the README a note on making datadirs for other networks

- data/pools/feeTracker.go
This one actually got caught by our e2e tests running with race detection
enabled.
> avoid race conditions in the fee tracker

- daemon/algod/api/server/v1/handlers/errors.go
- daemon/algod/api/server/v1/handlers/handlers.go
- daemon/algod/api/server/v1/routes/routes.go
This PR add an end point for pending transaction by address
> -- Add API end point Pending by address

- crypto/vrf.go
- data/committee/credential.go
* fix coding style in credential.go
* fix typo in comments in vrf.go
> minor fixes

- ledger/error.go
Better printing protocol upgrade errors
> Better printing protocol upgrade errors

- cmd/updater/sendCmd.go
- docker/build/Dockerfile-deploy
- scripts/deploy_version.sh
- scripts/upload_config.sh
- scripts/upload_version.sh
Make S3_RELEASE_BUCKET specification explicit in build scripts.
> Revisit s3_release_bucket usage in build scripts

- scripts/travis/travis_wait.sh
Add missing ANSI_RED/ANSI_GREEN/ANSI_RESET variables to travis_wait.sh
> Add ansi colors to travis_wait.sh

- scripts/travis/external_build.sh
- scripts/travis/external_build_printlog.sh
- scripts/travis/release_packages.sh
In the previous PR, I broke the non-pull requests external builds as well as the release packages stage. This PR should fix these issues.
> Fix recently introduced compilation bugs.

- cmd/pingpong/runCmd.go
- shared/pingpong/config.go
- shared/pingpong/pingpong.go
Add `--tps` option to pingpong so that we can ask pingpong to send transactions at the exactly rate we want. 
No protocol changes. Tested locally.
> Pingpong firerate

- cmd/netgoal/generate.go
Add the ability to create non-participating nodes via 'netgoal' command.
Adds the -H option to allow specify the number of non-participating nodes that would get created.
I deployed a network with these changes, and it looks good.
> Add the ability to create non-participating nodes via 'netgoal' command.

- test/testdata/deployednettemplates/recipes/scenario1/Makefile
- test/testdata/deployednettemplates/recipes/scenario1/genesis.json
- test/testdata/deployednettemplates/recipes/scenario1/net.json
- test/testdata/deployednettemplates/recipes/scenario1/node.json
- test/testdata/deployednettemplates/recipes/scenario1/nonPartNode.json
- test/testdata/deployednettemplates/recipes/scenario1/relay.json
- test/testdata/deployednettemplates/recipes/scenario1/topology.json
Update scenario1 recipe:
8 relays
20 nodes hosts
100 node instances
100 voting accounts
5 non-participating accounts
> Update scenario1 recipe

- cmd/algons/dnsCmd.go
Existing logic was implemented in reverse. It might have been great for testing purposes, but quite pointless for any practical usage.
I tested this manually. It works as expected.
> Fix DNS deletion logic

- cmd/pingpong/runCmd.go
- config/config.go
- data/ledger_test.go
- data/pools/transactionPool.go
- data/pools/transactionPool_test.go
- data/txHandler_test.go
- node/node.go
Make fee increase factor customizable. This will help us in performance tests.
No protocol and changes on the default behavior.  Tested locally.
> Customizable fee increase factor

- data/transactions/asset.go
Even when an asset is frozen, we want to be able to close it out to the asset creator. This allows  the holder to lower their min balance if they accidentally end up with a frozen asset they don't want.
> Allow closing frozen assets to the creator

- ledger/archival_test.go
This PR adds a few more checks to the archival asset test. We now check for creating/deleting an asset in the same block.
> Improve asset archival test

- cmd/opdoc/opdoc.go
- data/transactions/logic/README.md
- data/transactions/logic/README_in.md
- data/transactions/logic/TEAL_opcodes.md
- data/transactions/logic/assembler.go
- data/transactions/logic/doc.go
- data/transactions/logic/doc_test.go
- data/transactions/logic/eval.go
- data/transactions/logic/eval_test.go
Also a bunch of misc docs tweaks that got caught up in fixing the docs for xferasset
> fix `txn XferAsset` type to be uint64

- cmd/goal/clerk.go
Restore ability to save transaction to a file that was missed
during LogicSig and Assets implementation
Manual test and goal cmd tests for Jenkins later
> Fix for goal clerk sign to a file

- test/testdata/deployednettemplates/recipes/scenario2/net.json
- test/testdata/deployednettemplates/recipes/scenario2/node.json
- test/testdata/deployednettemplates/recipes/scenario2/nonPartNode.json
- test/testdata/deployednettemplates/recipes/scenario2/relay.json
Adjust the scenario2 network transaction cost throttling so that we could achieve high tx volume without increasing the fees.
> Adjust scenario2 for high transaction volume

- cmd/goal/clerk.go
- data/transactions/logic/eval.go
- data/transactions/logic/eval_test.go
- ledger/eval.go
> remove unused EvalParams.Block field

- libgoal/transactions.go
Forgot to update the error messages yesterday
> Fix libgoal asset error messages

- data/transactions/logic/eval.go
- data/transactions/logic/eval_test.go
make `go test` super quiet when all OK
> make TestPanic quietly swallow panic logs when ok

- cmd/opdoc/opdoc.go
- data/pools/transactionPool_test.go
- data/transactions/logic/README.md
- data/transactions/logic/README_in.md
- data/transactions/logic/TEAL_opcodes.md
- data/transactions/logic/doc.go
- ledger/eval.go
close hole where FirstValidTime of the block currently being assembled is hard to pin down
> make `txn FirstValidTime` actually the time of FirstValid-1

- ledger/eval.go
> add some basic metrics for teal eval

- cmd/goal/clerk.go
- cmd/goal/commands.go
- test/scripts/e2e.sh
- test/scripts/e2e_teal.sh
exercises several cases of TLHC pattern with goal commands
> add e2e test for teal script

- data/pools/feeTracker.go
- node/node.go
Optimize low hanging fruits:
- reorder node and txpool OnNewBlock listeners.
- reduce the lock time of the node's OnNewBlock
node's OnNewBlock typically takes 30-60ms
txpool OnNewBlock typically takes 200-600ms
we don't want the txpool's test to get blocked by waiting for the OnNewBlock for too long.
Easy solution - swap the order of the two so we can get free 30-60ms gains.
also, some minor improvements on the node's OnNewBlock locking.
> Optimize OnNewBlock low hanging fruits

- .travis.yml
This should fix the nightly/beta builds.
> Allow Travis to build tagged commits.

- .travis.yml
These travis changes didn't work the way I had expected them to, rolling them back.
> revert travis tag changes

- data/transactions/logic/assembler.go
- data/transactions/logic/eval_test.go
- data/transactions/logic/tutorial.md
add regression test
random doc fix
> fix assembler type checking on bnz,load,store

- tools/teal/templates/atomic-swap.teal.tmpl
- tools/teal/templates/delegate-key-registration.teal.tmpl
- tools/teal/templates/dynamic-fee.teal.tmpl
- tools/teal/templates/limit-order.teal.tmpl
- tools/teal/templates/periodic-payment-escrow.teal.tmpl
- tools/teal/templates/split.teal.tmpl
- Consume stack eagerly
- Remove pop workaround
> Clean up contracts.

- test/e2e-go/features/transactions/asset_test.go
Added e2e test for asset create-wait-restart-delete
> Added e2e test  for  asset create-wait-restart-delete

- data/transactions/logic/TEAL_opcodes.md
- data/transactions/logic/assembler.go
- data/transactions/logic/doc.go
- data/transactions/logic/eval_test.go
e.g.
```
txn TypeEnum
int Payment
==
```
> assemble `int KeyRegistration` and other TypeEnum constant names

- test/e2e-go/features/transactions/group_test.go
Tests groups of varying known-good sizes
> Add another group e2e test

- test/e2e-go/features/transactions/asset_test.go
Asset clawback e2e tests
Asset clawback and freeze tests are already in.
Adding a few more cases:
An account with no algos should not be able to accept assets
Clawback assets to an account that hasn't opted in should fail
Opting in should be signed by the opting in account not sender
Should not be able to clawback more than is available
> Asset clawback test

- data/pools/transactionPool.go
> Add check for pending group transaction size during the Remember function

- test/e2e-go/features/transactions/asset_test.go
* Test uses SuggestedParams.LastRound for verification.
* FillUnsignedTxTemplate uses SuggestedParams.LastRound for calculation.
* If round change happens between these calls test fails.
* To prevent this test checks LastRound before and after FillUnsignedTxTemplate
and adjusts verification
> Fix race in asset_test between SuggestedParams and FillUnsignedTxTempate calls

- test/scripts/teal-split-test.sh
- tools/teal/examples/split.sh
- tools/teal/templates/limit-order-a.teal.tmpl
- tools/teal/templates/limit-order-b.teal.tmpl
- tools/teal/templates/split.teal.tmpl
add missing timeout check to limit-order-b asset closeout
comment and label clarity and typofixes in limit-order-* and split
> misc teal template cleanup

- docker/release/README.md
> minor formatting

- test/e2e-go/features/transactions/group_test.go
As it says, e2e test checking incomplete or overflown group
e2e group_test
> Test for incorrect number transactions in a group

- test/e2e-go/features/transactions/asset_test.go
* Group of create + send zero in the same block
* Group of create + destroy in the same block
* Asset ID is guessed: tx count + 1 for both tests
> Tests for grouped asset transactions

- docker/release/build_algod_docker.sh
- scripts/build_release.sh
- scripts/build_release_run_ubuntu_docker_build_test.sh
- scripts/build_release_setup.sh
- scripts/build_release_sign.sh
- scripts/build_release_upload.sh
Stability improvements and fixes in the build process.
> Build 201912

- cmd/goal/asset.go
- cmd/goal/clerk.go
Asset commands were missing lease support
> Add lease support to asset cmds

- tools/teal/dkey/dsign/main.go
dsign currently only works with signing txids and whole `LogicSig`s. this adds a mode that lets it sign arbitrary data given a key, the program bytes, and a data file.
it would be nice to make this a prettier program with cobra, I didn't do that because I wanted to get something working quickly for the hackathon
> Let dsign sign arbitrary bytes, not just txids

- daemon/kmd/wallet/driver/sqlite.go
- daemon/kmd/wallet/driver/sqlite_errors.go
> Improve missing msig preimage error message

- cmd/algocfg/setCommand.go
e.g.
`algocfg set -p EnableProcessBlockStats -v true`
> add bool support to algocfg

- test/scripts/e2e_subs/dynamic-fee-teal-test.sh
- test/scripts/e2e_subs/e2e_teal.sh
- test/scripts/e2e_subs/htlc-teal-test.sh
- test/scripts/e2e_subs/keyreg-teal-test.sh
- test/scripts/e2e_subs/limit-swap-test.sh
- test/scripts/e2e_subs/periodic-teal-test.sh
- test/scripts/e2e_subs/teal-split-test.sh
Tee the output of piped arguments so that we can examine it in case of a failure.
> Improve teal shell scripting output

- data/transactions/transaction.go
- node/indexer/db.go
- node/indexer/indexer_test.go
-- Adding receiver function to transaction that returns the receiver of a transaction
-- Fix indexer to show received transactions
> Merge Indexer shows received transactions 

- cmd/algod/main.go
- config/config.go
- config/local_defaults.go
- installer/config.json.example
- logging/log.go
- logging/telemetry.go
- logging/telemetryCommon.go
- test/testdata/configs/config-v5.json
logging.config:
{"Enable":false,"SendToLog":true}
OR:
config.json:
{"TelemetryToLog":true}
> telemetry recorded locally as info log

- network/wsNetwork_test.go
When running on arm64, the TestSlowHandlers is occasionally failing due to timeouts.
It seems that on arm64, using tight scheduling doesn't always work, as either context switching or go routine generation seems to be much slower.
I have modified the testing code to use exponential delay of up to 256ms instead of 10ms.
( i.e. 1,2,4,8..128 instead of 1,1,1,1,1...1 )
> Make network unit test TestSlowHandlers less restrictive

- cmd/goal/account.go
- cmd/goal/asset.go
- cmd/goal/clerk.go
- cmd/goal/commands.go
- cmd/goal/completion.go
- cmd/goal/kmd.go
- cmd/goal/ledger.go
- cmd/goal/logging.go
- cmd/goal/multisig.go
- cmd/goal/network.go
- cmd/goal/node.go
- cmd/goal/wallet.go
This PR proposes slight changes to the goal docs, mainly updates to the `Long:` form of each Cobra command. It also standardizes each `Long:` help hint to end in punctuation.
Docs-only change.
> Goal docs tweaks 

- scripts/check_deps.sh
> Fix checkdep message

- cmd/netgoal/generate.go
There is a small annoying round error in last wallet stake when run s3 test. This is quick fix for it.
* Use math.big.Rat rational numbers to get rid of summation error
* Root cause although in JSON serialization of float64 so that some values
are rounded and others are not. Correct fix seems in using
the same accuracy in distribution code and float64 marshaling.
```
pushd test/testdata/deployednettemplates/recipes/scenario3
GOPATH=$(go env GOPATH) make
echo $(jq '.Wallets[-1].Stake' genesis.json) '==' 0.005 | bc -l
```
> Fix equal stake distribution in generated networks

- cmd/netgoal/generate.go
- netdeploy/networkTemplate.go
- netdeploy/remote/nodeConfig.go
* Usage:
netgoal generate -n 1 -R 1 -w 10 -o mynettemplate.json -r . -t goalnet
goal network create -t mynettemplate.json -r mynet -n mynet
* Remove duplicate definitions from netdeploy/networkTemplate
> Implement local net template generation with netgoal

- util/process.go
* In case of large amount of data written to stdout/stderr
from the wrapped command the process is blocked until
stdout/stderr buffers cleared.
* Old implementation waited until cmd return and then read stdout/stderr.
* New implementation reads stdout/stderr pipes in goroutines.
> Make util.ExecAndCaptureOutput able to process large output

- logging/telemetryConfig.go
- logging/telemetryConfig_test.go
Add a comment about default telemetry configuration.
> Add comment about telemetry

- docker/releases/build_releases.sh
This allows for building a docker image for `mainnet` but calling it `stable` or `foo` or whatever.
In addition, instead of getting arguments by position, they are now given switches.
Lastly, if you don't want the script to automatically publish to docker hub, provide it with the `--no-publish` flag.
> Update docker build script to be more flexible with its naming

- tools/teal/templates/dynamic-fee.teal.tmpl
Fix the incorrect comments of `dynamic-fee.teal.tmpl`.
No code changes.
> fix incorrect comments

- tools/network/dnssec/dnssec_test.go
- tools/network/dnssec/resolver.go
Researched some well-known public DNS resolvers and updated defaults.
> Update list of DNSSEC-aware resolvers

- test/scripts/e2e_basic_start_stop.sh
- test/scripts/e2e_client_runner.py
more logging for travis debugging
> WIP: e2e_basic_start_stop debugging

- data/ledger.go
- data/transactions/common_test.go
- data/transactions/transaction.go
Remove unused parameter, and check additional address field.
> Improve MatchAddress

- data/transactions/transaction.go
> Use IsZero instead of comparing an empty struct in transaction.go

- daemon/algod/api/README.md
> Fix API README Typos

- test/e2e-go/cli/goal/expect/goal_expect_test.go
- test/e2e-go/features/partitionRecovery/partitionRecovery_test.go
- test/e2e-go/upgrades/send_receive_upgrade_test.go
test/e2e-go/cli/goal/expect/goal_expect_test.go 816
test/e2e-go/features/partitionRecovery/partitionRecovery_test.go 807
test/e2e-go/upgrades/send_receive_upgrade_test.go 815
> Unfiltering some tests filtered on darwin:

- test/scripts/e2e_subs/rekey.sh
Add automated test doing account re-keying using `goal` with an account on a small private network.
This _is_ a test.
> add e2e bash+goal test for rekeying

- .github/PULL_REQUEST_TEMPLATE.md
Use PR Summary for clean commit message (algorand/go-algorand-internal#487)
N/A
> Use PR Summary for clean commit message

- CONTRIBUTING.md
Update CONTRIBUTING.md to make more sense when cross linked from other projects.
> Update CONTRIBUTING.md to make more sense when cross linked from other projects.

- docker/build/docker.ubuntu.Dockerfile
- docker/build/mule.go.centos.Dockerfile
- package-deploy.yaml
- scripts/release/mule/Makefile.mule
- scripts/release/mule/deploy/deb/deploy.sh
- scripts/release/mule/deploy/generate_releases_page/deploy.sh
- scripts/release/mule/deploy/generate_releases_page/generate_releases_page
- scripts/release/mule/deploy/generate_releases_page/generate_releases_page.py
- scripts/release/mule/deploy/generate_releases_page/html.tpl
- scripts/release/mule/deploy/generate_releases_page/releases_page.css
- scripts/release/mule/deploy/rpm/deploy.sh
Add mule `deploy` task.
Run mule tasks in `package-deploy.yaml`.
> Added mule `deploy` task

- cmd/goal/node.go
Fix for #1133 
Spelling correction
Tag @ejbaran as reviewer
> fixup goal documentation

- cmd/dispenser/server.go
This feature will allow for a more seemless integrtion with Mobile Apps and Websties that use TestNet and BetaNet Dispensers
> Parameter support for dispenser

- scripts/release/build/stage/upload/run.sh
- scripts/release/prod/stage/snapshot.sh
- scripts/release/prod/stage/sync/run.sh
- scripts/release/test/stage/setup/run.sh
- scripts/release/test/stage/test/run.sh
Change the location of staging from `algorand-builds` to `algorand-staging` to be in sync with the new mule tasks.
n/a
> Change staging location to algorand-staging

- cmd/kmd/main.go
- data/committee/credential.go
- logging/telemetryConfig.go
- logging/telemetryConfig_test.go
- network/requestTracker_test.go
Run make fmt on the project.
N/A
> Run make fmt

- test/e2e-go/features/catchup/catchpointCatchup_test.go
Travis test failed with the following data race : 
```
==================
3937WARNING: DATA RACE
3938Write at 0x00c00012e751 by goroutine 60:
3939  testing.(*common).FailNow()
3940      /home/travis/.gimme/versions/go1.12.17.linux.amd64/src/testing/testing.go:608 +0x4c
3941  testing.(*T).FailNow()
3942      <autogenerated>:1 +0x43
3943  github.com/stretchr/testify/require.NoError()
3944      /home/travis/gopath/pkg/mod/github.com/stretchr/testify@v1.6.1/require/require.go:1038 +0x102
3945  github.com/stretchr/testify/require.(*Assertions).NoError()
3946      /home/travis/gopath/pkg/mod/github.com/stretchr/testify@v1.6.1/require/require_forward.go:813 +0xcf
3947  github.com/algorand/go-algorand/test/e2e-go/features/catchup.TestBasicCatchpointCatchup()
3948 …
```
> Fix e2e unit test data race

- cmd/goal/application.go
- test/scripts/e2e_subs/e2e-app-simple.sh
goal app info is like goal asset info, printing out properties describing an app.
e2e-app-simple was modified to test this command.
> Add goal app info for inspecting app properties.

- cmd/algorelay/relayCmd.go
The existing algorelay know only how to update SRV and DNS entries. It does not remove them.
This PR adds two-way checking to detect orphan entries that were left on the DNS system and do not corresponds to the provided relays json.
> Add orphan entries to the algorelay check command

- ledger/accountdb.go
- ledger/acctupdates.go
- ledger/acctupdates_test.go
Per past review comments (https://github.com/algorand/go-algorand/commit/76ac4f634fe4e14da5680709aac8d1daf4c4aae9), I'm adding some more in-code comments. 
N/A
> Add comments around the accounts database upgrade procedures

- cmd/goal/account.go
- test/e2e-go/cli/algoh/expect/algohExpectCommon.exp
- test/e2e-go/cli/goal/expect/goalAccountTest.exp
- test/e2e-go/cli/goal/expect/goalDryrunRestTest.exp
Test goal account dump produces JSON or msgpack blob, and errs on invalid input
This is a test
> Implement expect test for goal account dump

- cmd/goal/node.go
Quick spelling fixup identified in https://github.com/algorand/docs/pull/151
Docs are generated from source, so fixing here.
> fixup docs

- config/version.go
The next release will update the minor version number. This will move us from 2.0.x to 2.1.x.
Verify compute build number script bumps to 2.1.x:
```
./scripts/compute_build_number.sh -f
2.1.79815
```
> Update minor version number

- ledger/accountdb_test.go
- ledger/acctupdates_test.go
Two basic account tests TestAccountDBRound and TestAcctUpdates operate over AccountData with assets and applications
> Enable creatables in ledger tests

- config/consensus_test.go
Create a unit test to verify that the consensus upgrade window configuration is valid.
This is a unit test
> Add unit test TestConsensusUpgradeWindow

- ledger/ledger_test.go
Extend some base ledger unit tests to have asset config, asset transfer and app create txn types.
This is tests PR
> Add assets and apps to ledger txn validate tests

- crypto/merkletrie/cache.go
- crypto/merkletrie/cache_test.go
This PR adds another test to the merkletrie cache implementation to ensure correctness on random trie operations.
This is a unit test.
> Add a fuzzer to the merkletrie cache testing

- test/e2e-go/upgrades/application_support_test.go
- test/e2e-go/upgrades/rekey_support_test.go
e2e-go test for rekeying feature before and after upgrade
This is a test
> e2e test for rekeying before and after upgrade

- ledger/accountdb_test.go
Added random sampling for creatables, and compared them to the database image in every iteration.
> Unit test for accountsNewRound creatables parameter

- package-deploy.yaml
- package-sign.yaml
- package-test.yaml
- package.yaml
- scripts/release/mule/package/rpm/package.sh
There is a new `agents` top-level directive in `mule`.  This updates each file to the new syntax.
Run mule tasks in `package.yaml`.
> Update package*.yaml to reflect new syntax

- README.md
- test/README.md
Didn't see any documentation for this directory, so I wrote it while figuring things out.
> Add some minimal documentation for the test directory.

- test/scripts/e2e_subs/rest.sh
e2e script test to make sure the `/v2/applications` endpoint is working.
> REST API test script for /v2/applications

- ledger/accountdb_test.go
- ledger/acctupdates_test.go
* tests with all elements in cache, all synced to database, and combination of both
* tests the max results, max app index and max asset index
> Added TestListCreatables to test ListAssets and ListApplications

- config/config.go
Update CatchpointInterval config comment, per review request.
> Update CatchpointInterval config comment

- daemon/algod/api/server/v2/handlers.go
- test/scripts/e2e_subs/rest.sh
Add e2e tests for the `/v2/assets/{id}` endpoint
> Add tests for /v2/assets endpoint

- go.mod
- scripts/get_golang_version.sh
Golang 1.12 is deprecated, so update to the latest stable 1.14 version.
Standard test suite.
> Update golang version to latest 1.14.7

- installer/rpm/algorand.spec
- scripts/build_deb.sh
- scripts/build_package.sh
- scripts/release/mule/package/deb/package.sh
Add tealdbg to installation packages
No tests
> Add tealdbg to installation packages

- daemon/algod/api/server/lib/middlewares/auth.go
- daemon/algod/api/server/lib/middlewares/auth_test.go
- daemon/algod/api/server/router.go
- test/scripts/e2e_subs/rest.sh
Adds some tests to the auth middleware. The unit test for the pprof url auth isn't great, so there is also an e2e test for that case.
> Auth Middleware Tests

- daemon/algod/api/server/v2/test/handlers_test.go
- node/error.go
- node/node.go
Address nits from earlier PR.
No new functionality added.
> Minor catchpoint REST handler error code cleanup.

- ledger/accountdb_test.go
Improve BenchmarkWriteCatchpointStagingBalances benchmark - compared ordered/random insertions. Output:
```
goos: darwin
goarch: amd64
BenchmarkWriteCatchpointStagingBalances
BenchmarkWriteCatchpointStagingBalances/RandomInsertOrder-102400
BenchmarkWriteCatchpointStagingBalances/RandomInsertOrder-102400                  65536   (last 64k) 65506  ns/account       15265 accounts/sec
BenchmarkWriteCatchpointStagingBalances/RandomInsertOrder-102400                  db fragmentation   3.9%
BenchmarkWriteCatchpointStagingBalances/RandomInsertOrder-102400-8         	  102400	     56362 ns/op	     17771 accounts/sec
BenchmarkWriteCatchpointStagingBalances/RandomInsertOrder-204800
BenchmarkWriteCatchpointStagingBalances/RandomInsertOrder-204800 …
```
> Improve db insertion benchmark - add ordered insertions

- go.mod
- ledger/ledger_test.go
Tests added to cover:
ledger.GetLastCatchpointLabel
ledger.ledger.ListAssets
ledger.ListApplications
> Adding ledger tests

- ledger/catchupaccessor_test.go
This PR moves the preparation of the encoded accounts to be executed before the measuring starts.
This result in more accurate measurements of the actual time it takes to perform the writing.
In addition, it also ensures that the generated addresses are provided in increasing order ( which aligns with the catchpoint file accounts ordering )
output:
```
goos: darwin
goarch: amd64
BenchmarkRestoringFromCatchpointFile/Restore-102400-8         	  102400	     71381 ns/op	     82270 ns/last_64k_account
BenchmarkRestoringFromCatchpointFile/Restore-204800-8         	  204800	     79992 ns/op	     90898 ns/last_64k_account
BenchmarkRestoringFromCatchpointFile/Restore-409600-8         	  409600	     85741 ns/op	    106074 ns/last_64k_account
PASS
ok …
```
> Improve RestoringFromCatchpointFile benchmark precision

- daemon/algod/api/algod.oas2.json
- daemon/algod/api/algod.oas3.yml
Minor fixup based on https://github.com/algorand/docs/pull/127 from @fabrice102 
This change adds new line characters allowing proper MD formatting when docs are generated from this source file.
> Fixup API Docs

- daemon/algod/api/server/v1/handlers/handlers.go
Update documentation as requested
> REST docs update: /v1/account/{addr}/transactions

- test/e2e-go/cli/goal/expect/goalAppAccountAddressTest.exp
- test/e2e-go/cli/goal/expect/goalExpectCommon.exp
- test/e2e-go/cli/goal/expect/testInfraTest.exp
Added ::AlgorandGoal::CheckProcessReturnedCode to test process return code
Added a test to test CheckProcessReturnedCode
> Test for process return in expect tests

- package-deploy.yaml
- package-sign.yaml
- package-test.yaml
Remove commas from mule yaml files.  Their presence is causing errors.
`mule -f package-deploy.yaml package-deploy`
> Remove commas from mule yaml files

- cmd/pingpong/runCmd.go
- shared/pingpong/accounts.go
- shared/pingpong/config.go
- shared/pingpong/pingpong.go
- test/e2e-go/cli/goal/expect/goalExpectCommon.exp
- test/e2e-go/cli/goal/expect/pingpongTest.exp
Added support for testing TEAL app size in addition to operations
Created a new expect test to exercise various configurations of pingpong including app size and ops for TEAL app testing.  Ran `make test` and `make integration`.
> Updates to support testing TEAL application size

- util/db/dbutil_test.go
Test to see if sqlite blocks when we attempt to read while writing to a database table.
> Add concurrent read and write test from database table

- crypto/compactcert/builder.go
- crypto/compactcert/common.go
- crypto/compactcert/common_test.go
- crypto/compactcert/msgp_gen.go
- crypto/compactcert/msgp_gen_test.go
- crypto/compactcert/verifier.go
- protocol/hash.go
Leo's revised analysis suggests adding more inputs into hashCoin() for cleaner hygiene.
> add more inputs into hashCoin() for better hygiene

- go.mod
- ledger/accountdb.go
- ledger/acctupdates.go
- ledger/bulletin.go
- ledger/catchpointwriter.go
- ledger/catchupaccessor.go
- ledger/ledger.go
- ledger/notifier.go
Fixing various typos in the ledger package.
> Fix typos in ledger package

- go.mod
- ledger/acctupdates_test.go
Coverage tests for IsWritingCatchpointFile and GetCatchpointStream
> Coverage tests for ledger/acctupdates

- ledger/acctupdates.go
Avoid copying the array needlessly, and preallocate storage of array and map.
Use existing tests to cover the functionality.
> Optimize listCreatables implementation

- cmd/diagcfg/messages.go
- daemon/algod/api/server/v2/utils.go
- data/transactions/logic/debugger_test.go
- network/ping_test.go
This is just the formatting changes resulting from running `make sanity`
After this it should be safe for someone to run `make sanity` and not be burdened with irrelevant changes to their changes.
> make sanity

- .travis.yml
- Makefile
- scripts/configure_dev.sh
- scripts/ostype.sh
- scripts/travis/before_build.sh
- scripts/travis/build.sh
- scripts/travis/configure_dev.sh
- scripts/travis/test.sh
Modify codebase to support compiling under Windows.
No testing in this PR.
> Add support for Windows compilation on travis

- package-upload.yaml
Upload build assets to `algorand-staging` at any point in the build pipeline process.
`mule -f package-upload.yaml package-upload`
> Added `package-upload` mule task

- network/wsNetwork_test.go
The unit test was modifying the peer's `intermittentOutgoingMessageEnqueueTime` in order to emulate a stale message.
When this test was written, this was fine. However, since we added sending MOI when a connection is established, the writing of that message would clear the timeout setting we've placed in `intermittentOutgoingMessageEnqueueTime`, causing the unit test to randomly fail.
To correct this, I have cleared the `messagesOfInterest`, so that we won't be sending any initialization message.
> fix unreliable network unit test TestSlowPeerDisconnection

- cmd/tealdbg/cdt/proto.go
- cmd/tealdbg/cdtSession.go
- cmd/tealdbg/cdtState.go
- cmd/tealdbg/cdtdbg.go
- cmd/tealdbg/localLedger.go
- cmd/tealdbg/local_test.go
- cmd/tealdbg/server.go
- test/e2e-go/cli/tealdbg/cdtmock/main.go
- test/e2e-go/cli/tealdbg/expect/tealdbgTest.exp
- test/e2e-go/cli/tealdbg/expect/tealdbg_expect_test.go
Tealdbg test using CDT mock program instead of Google Chrome:
* Run debugger
* Run CDT simulator, connect to the debugger, send control messages
* Wait for termination, check output
This is a test
> Implement e2e test for tealdbg

- cmd/tealdbg/cdtSession.go
- cmd/tealdbg/cdtSession_test.go
- cmd/tealdbg/cdtState.go
- cmd/tealdbg/cdtdbg.go
- cmd/tealdbg/cdtdbg_test.go
- cmd/tealdbg/debugger.go
- cmd/tealdbg/debugger_test.go
- cmd/tealdbg/local.go
- cmd/tealdbg/localLedger.go
- cmd/tealdbg/main.go
- cmd/tealdbg/remote_test.go
- cmd/tealdbg/server.go
- cmd/tealdbg/server_test.go
- cmd/tealdbg/util_test.go
- cmd/tealdbg/webdbg.go
- cmd/tealdbg/webdbg_test.go
- data/transactions/logic/debugger.go
- test/e2e-go/cli/tealdbg/expect/tealdbg_expect_test.go
Add more tests for the debugger: coverage improved from 25 to 72.8 percent.
Most of the remaining code (websocket handlers, main) are covered by e2e test.
This is test PR
> tealdbg unit tests

- .github/ISSUE_TEMPLATE/algorand-engineering-team-issue-template.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
Adding a new template for the eng team
> Update issue templates

- scripts/release/mule/package/deb/package.sh
Added ARCH_TYPE to file name so they won't overwrite each other.
n/a
> Add ARCH_TYPE to build status file

- package-sign.yaml
- scripts/release/mule/sign/sign.sh
- scripts/release/mule/test/test.sh
- scripts/release/mule/test/tests/post/verify_package_binaries.sh
- scripts/release/mule/test/tests/pre/verify_control_files.sh
- fix status file name
- change name of image in mule yaml
- add vars to dynamically account for both algorand and algorand-devtools packages (all channels)
`VERSION=2.2.0 BRANCH=rel/beta CHANNEL=beta mule -f package-test.yaml package-test`
`VERSION=2.1.6 BRANCH=rel/stable CHANNEL=stable NETWORK=mainnet SHA=df65da2b mule -f package-test.yaml package-test`
> Fix bugs in mule test stage

- daemon/algod/api/client/restClient.go
- test/testdata/deployednettemplates/recipes/mainnet-model/Makefile
- test/testdata/deployednettemplates/recipes/mainnet-model/generated/net.json
- test/testdata/deployednettemplates/recipes/mainnet-model/generated/topology.json
- test/testdata/deployednettemplates/recipes/mainnet-model/network-tpl.json
Updates the mainnet-model for scale ( increasing the number of staked nodes from 25 to 50 ) and
redistribute the relays, staked nodes and non-staked nodes according to mainnet distribution.
> Update mainnet-model for scale and distribution

- scripts/release/mule/test/tests/pre/verify_signature.sh
Added a test to verify gpg signature of packages
From root of package:
`./scripts/release/mule/test/tests/pre/verify_signature.sh`
> Added package test to verify gpg signature

- shared/pingpong/accounts.go
- shared/pingpong/pingpong.go
Current asset allocation and distribution implementation leads to invalid asset transactions:
* opt-in (when `proto.MaxAssetsPerAccount` is exceeded)
* transfer (when transferring to/from non-opted in accounts)
The fix preserves unconditional assets creation by every account but also tracks opt ins and stops when `proto.MaxAssetsPerAccount` is reached. `OptIns map[Creatable][]Address` is used to select random sender/receiver for random asset ID.
Run e2e `pingpongText` with current settings and `--numasset=100 --numaccounts 10` to exceed limits.
> Fix opt-ins and timeouts in pingpong assets testing

- netdeploy/networkTemplate.go
The `createConfigFile` function was using hard-coded config file; this change is moving to using the config.Local data structure to correctly construct the file as need. It will allow changes in the data structure to be reflected in future versions, and will include the correct version number.
Verified manually and compared to previous config files - 
Before:
```
{ "GossipFanout": 1, "EndpointAddress": "127.0.0.1:0", "DNSBootstrapID": "", "EnableProfiler": true, "NetAddress": "127.0.0.1:0" }
```
After:
```
{
"Version": 13,
"GossipFanout": 1,
"NetAddress": "127.0.0.1:0",
"DNSBootstrapID": "",
"EnableProfiler": true
}
```
> Create configuration file using config.Local data structure

- logging/telemetryhook.go
This PR addresses several key locations which lacked error message printouts.
These changes were tested manually. Automating a test for these seems to be quite an intensive task, as it requires to emulate an elastic search server..
> Improve error logging of elastic search telemetry module

- tools/network/dnssec/config.go
- tools/network/dnssec/config_unix.go
- tools/network/dnssec/config_windows.go
- tools/network/dnssec/trustchain.go
* Fix comments for config
* Use struct embedding instead of aggregation
to get rid of useless explicit forwarding
> Code style fixes DNSSEC client

- test/testdata/deployednettemplates/recipes/scenario1/net.json
- test/testdata/deployednettemplates/recipes/scenario1/node.json
- test/testdata/deployednettemplates/recipes/scenario1/nonPartNode.json
- test/testdata/deployednettemplates/recipes/scenario2/net.json
- test/testdata/deployednettemplates/recipes/scenario2/node.json
- test/testdata/deployednettemplates/recipes/scenario2/nonPartNode.json
- test/testdata/deployednettemplates/recipes/scenario3/net.json
- test/testdata/deployednettemplates/recipes/scenario3/node.json
- test/testdata/deployednettemplates/recipes/scenario3/nonPartNode.json
Set CadaverSizeTarget to 0 so that we don't suffer huge performance losses in tests
> Set CadaverSizeTarget to 0 for Scenario testing

- Makefile
- scripts/check_golang_version.sh
- scripts/travis/build.sh
- scripts/travis/test.sh
Ensure go is 1.14+ prior the build
Closes #1690
> Check minimal go version 1.14 prior the build

- cmd/catchpointdump/net.go
Allow catchpointdump fetching a single catchpoint
No tests
> Allow catchpointdump downloading a single catchpoint from a specified relay

- network/wsPeer.go
This PR adds an explicit write error for disconnecting due to stale messages, which could now be distinguished from other write errors.
Tested against telemetry server.
> Add explicit error for stale network message writes

- catchup/service.go
- catchup/service_test.go
- config/config.go
Add the ability to disable catchup in config file.
> Add the ability to disable catchup in config file

- nodecontrol/algodControl.go
- nodecontrol/kmdControl.go
This PR addresses several different issues:
1. The clone functionality wasn't working ( and according to the code, it looks as it wasn't working for over a year.. ); The changes here would make it work again. The might be additional caveats around the current functionality, but that could be left for another PR.
2. The cleanUpZombieKMD function now reports back an error, if there is a meaningful error to report ( i.e. other than "file not found" ).
3. The algod/kmd start function checks the return code of the Close() function and return the result to the caller. This doesn't really expected to fail, but in case it does, it will be reported upstream.
> Fix return code testing & fix data directroy cloning

- nodecontrol/kmdControl.go
> Better kmd permission error message. Closes #1784

- ledger/accountdb_test.go
Add a benchmark to test the performance difference between writing to the accountbase table using the address as the primary key, versus using the rowid.
Benchmark results:
| Writing Method  | Database accounts number | Rate |
| ------------- | ------------- | ------------- |
| Using address  | 5,000,000 | 151,635 ns/acct_update |
| Using rowid  | 5,000,000 | 131,031 ns/acct_update |
| Using address  | 2,000,000 |  136,688 ns/acct_update |
| Using rowid  | 2,000,000 |  116,865 ns/acct_update |
| Using address  | 500,000 | 60,462 ns/acct_update |
| Using rowid  | 500,000 |  56,764 ns/acct_update |
Running parameters-
1. Insertions were made using prepared statements.
2. Random account data size on insertion was 200 bytes.
1. While the update speed itself seems to be variable with the …
> Add BenchmarkWritingRandomBalancesDisk

- test/scripts/e2e_subs/dex.sh
- test/scripts/e2e_subs/tealprogs/dex.teal
This is a test for indexer sync state applying issue from https://github.com/algorand/indexer/issues/226
> Indexer state test for keys creation/deletion

- test/scripts/e2e_subs/create_destroy_optin_optout.sh
Add a new e2e test script that creates and closes things. The main purpose here is to create some interesting state for Indexer tests.
> Add e2e test with some interesting state for Indexer tests.

- ledger/accountdb.go
- ledger/accountdb_test.go
- ledger/acctupdates.go
- ledger/acctupdates_test.go
- ledger/applications_test.go
- ledger/cow.go
- ledger/cow_test.go
- ledger/eval.go
- ledger/eval_test.go
- ledger/txtail_test.go
* accountDelta.old is not used anymore so accountDelta is redundant
Update existing tests
> Replace accountDelta by basics.AccountData in ledger

- test/muleCI/mule.yaml
Added env vars to `mule.yaml`.
Ran successive builds on travis.
> Fix rel/beta build

- daemon/algod/deadlock_test.go
Helps avoid recursive locking when the deadlock package tries to report
recursive locking and the error message goes through the logging layer.
> do not use deadlock.Mutex in logging

- catchup/fetcher.go
- catchup/ledgerFetcher.go
- network/phonebook.go
- network/phonebook_test.go
- network/ping_test.go
- network/requestLogger_test.go
- network/requestTracker_test.go
- network/wsNetwork.go
- network/wsNetwork_test.go
- rpcs/httpTxSync.go
Add archiver node support for SRV lookups and add these to the phonebook.
Updated & extended existing unit tests
> Add core networking support for archivers

- auction/tracker.go
- network/wsNetwork.go
- node/node.go
This PR addresses few minor log string formatting issues.
Changes are trivial.
> fix few minor log string formatting

- test/scripts/e2e_subs/asset-misc.sh
In development Indexer got stuck on mainnet data similar to this.
This is algod test code that should continue to pass.
> testing: put some unicode in an AsssetName to help test Indexer

- test/e2e-go/upgrades/application_support_test.go
Improve the reliability of the `TestApplicationsUpgradeOverGossip` e2e test by using a specific historical protocols and avoiding dynamically modifying current and/or future protocols.
This is an e2e test.
> testing: improve reliability of e2e upgrade tests

- test/muleCI/mule.yaml
Integrate package signing into CI pipeline. 
Tested using Jenkins CI Pipeline.
> Integrate package signing into CI pipeline

- daemon/kmd/lib/kmdapi/requests.go
See https://forum.algorand.org/t/php-algorand-sdk/2757/2?u=fabrice
Documentation improvement.
It is just a documentation update.
> Add details on format of Transaction for kmd

- cmd/dispenser/server.go
Add Appeal to kindness to dispenser HTML.
Expand the size of the address text field to 80 characters.
Tested in the browser.
> Add appeal to kindness to dispenser to help prevent abuse.

- ledger/ledgercore/persistedacctdata.go
- ledger/ledgercore/persistedacctdata_test.go
This PR implements `AssetsHoldingGroup` and tests.
Test for full coverage of `AssetsHoldingGroup` methods added.
> 1k+ assets (part 3)

- test/e2e-go/features/transactions/accountv2_test.go
Fix random failure in `TestAccountInformationV2` e2e test.
> Fix random e2e test failure in TestAccountInformationV2

- agreement/demux.go
Provide a fallback to use the default consensus parameters in case the agreement is running ahead of the ledger.
This use case was reported on the telemetry, and the fix is pretty straight forward.
```
[Stack] goroutine 128813 [running]:
runtime/debug.Stack(0xc000294690, 0xc00018e0b0, 0xc000163ce0)
runtime/debug/stack.go:24 +0x9f
github.com/algorand/go-algorand/logging.logger.Errorf(0xc000294690, 0xc00018e0b0, 0x12543a2, 0x33, 0xc007245e00, 0x2, 0x2)
github.com/algorand/go-algorand/logging/log.go:229 +0x4a
github.com/algorand/go-algorand/agreement.(*demux).next(0xc005ed7900, 0xc001168480, 0x55ae82600, 0x7a51ac1a8d, 0xbd1c82, 0x0, 0x0, 0xc00008e001)
github.com/algorand/go-algorand/agreement/demux.go:246 +0x1e6b
github.com/algorand/go-algorand/agreement.(*Service).demuxLoop(0xc001168480, …
```
> Improve ledger running behind the agreement

- ledger/accountdb.go
- ledger/accountdb_test.go
- ledger/acctupdates.go
- ledger/acctupdates_test.go
- scripts/dump_genesis.sh
`accountdb` changes to support `ExtendedAssetHolding`: a new accountext table, migrations, tests.
> 1k+ assets (part 4)

- util/metrics/tagcounter.go
- util/metrics/tagcounter_test.go
nil check fix
expand unit test
> nil check fix

- util/bloom/bloom.go
- util/bloom/bloom_test.go
Avoid allocation of memory in subsequent calls to Test, and Set. 
A memory utilization test was added.
> Optimize bloom filter memory allocations

- cmd/opdoc/opdoc.go
- daemon/kmd/lib/kmdapi/requests.go
- data/transactions/logic/TEAL_opcodes.md
- data/transactions/logic/assembler.go
- data/transactions/logic/assembler_test.go
- data/transactions/logic/doc.go
- data/transactions/logic/doc_test.go
- data/transactions/logic/eval.go
- data/transactions/logic/eval_test.go
- data/transactions/logic/fields.go
- data/transactions/logic/opcodes.go
- data/transactions/logic/opcodes_test.go
- ledger/applications.go
- test/e2e-go/features/catchup/basicCatchup_test.go
These are changes suggested on the TEAL3 code review.  They simplify and cleanup a few things, but should be very safe.  Mostly just changes in structure of assembler.
> Teal3 review

- ledger/apply/asset.go
- ledger/apply/asset_test.go
- network/limited_reader_slurper.go
before mem 1.83GB, allocs 1773556
after  mem 1.22GB, allocs 962952
Added a benchmark
> Improve memory allocations in cloneAssetHoldings and cloneAssetParams

- catchup/fetcher_test.go
- catchup/service_test.go
- Remove testing tools which are no longer used
- Add timeout to TestAbruptWrites to avoid occasional failures
No new code or functionality added. Existing test should be sufficient.
> clear unused test code

- scripts/release/mule/package/deb/package.sh
- test/muleCI/mule.yaml
If the channel is set, don't reset.
Tested with Jenkins pipeline
> Fix for wrong channel when packaging.

- txnsync/logger.go
Log messages for incoming/outgoing are flipped.
Tested manually by reviewing log files.
> txnsync: fix incoming/outgoing messages text.

- crypto/merkletrie/cache.go
- crypto/merkletrie/cache_test.go
- ledger/accountdb.go
- ledger/appcow.go
- ledger/applications_test.go
- ledger/apply/application.go
- ledger/apply/application_test.go
- ledger/ledgercore/error.go
- network/wsPeer.go
- network/wsPeer_test.go
- node/node.go
- test/scripts/e2e_subs/e2e-app-simple.sh
Merge master back into feature/txnsync
> merge master into feature/txnsync

- txnsync/incoming.go
Log error conditions of invalid incoming messages.
Changes are trivial.
> Log error conditions of invalid incoming messages

- catchup/catchpointService.go
When using the fast catchup, the block authenticity is verified against the catchpoint label. That method bypass the local genesis.json authentication since it's not required to establish secure catchup. From that point and on, the caught-up node would be able to proceed as usual. However, when the node is restarted, it compares the on-disk genesis.json to the first 320 rounds being loaded into memory. Failing with that comparison, the node would refuse to start up.
The solution here is to prevent the node from completing the fast catchup before testing that the genesis.json's hash matches the one on the first downloaded block. From there, it would be guaranteed to be identical due to the reverse hash check.
Manually tested against "corrupted" genesis.json file. Requires full catchup …
> catchup: cross verify genesis.json hash

- ledger/ledger_test.go
* go test -v ./ledger -run TestLedgerMemoryLeak
* The test creates 980 NFTs per acct during 10000 rounds,
creating new accounts when needed
* Every 1000 full asset blocks it saves memory profile
This is a test
> Unit test demonstrating high memory consumption

- cmd/tealdbg/dryrunRequest.go
- cmd/tealdbg/local.go
Better errors on txn and dryrun objects decoding.
> Print out intermediate decoding errors

- config/consensus.go
- ledger/appcow.go
- ledger/appcow_test.go
- ledger/applications_test.go
- protocol/consensus.go
Ensure local delta does not have entries with empty key-value stores
New test added
> ledger: avoid producing empty local delta

- ledger/accountdb.go
- ledger/acctupdates.go
Delete empty entries, update merkleTrie hashes.
Rely on existing tests
> DB data migration for empty accounts

- ledger/accountdb.go
- ledger/acctupdates.go
This PR addresses few late review feedback comments on #2093
Test manually against corrupted database.
> ledger: improve error testing on database migration 4

- ledger/acctupdates.go
- ledger/appcow.go
fix typos in comments
no test needed for fixing typos.
> fix typos in comments

- cmd/goal/clerk.go
Fix a bug in the previous merge from master.
> Fix merge conflict

- config/config.go
- config/local_defaults.go
- installer/config.json.example
- ledger/acctupdates.go
- logging/telemetryspec/metric.go
- test/testdata/configs/config-v17.json
- test/testdata/deployednettemplates/recipes/bootstrappedScenario/net.json
- test/testdata/deployednettemplates/recipes/bootstrappedScenario/node.json
- test/testdata/deployednettemplates/recipes/bootstrappedScenario/relay.json
- test/testdata/deployednettemplates/recipes/scenario1/node.json
- test/testdata/deployednettemplates/recipes/scenario1/relay.json
- test/testdata/deployednettemplates/recipes/scenario2/node.json
- test/testdata/deployednettemplates/recipes/scenario2/relay.json
- test/testdata/deployednettemplates/recipes/scenario3/node.json
- test/testdata/deployednettemplates/recipes/scenario3/relay.json
This PR enables metrics logging configurations for account updates' commitRound(...).
> Add performance metrics for account updates

- compactcert/builder.go
- ledger/compactcert.go
- ledger/compactcert_test.go
> Add tests for ledger/compactcert.go

- data/pools/transactionPool.go
- data/transactions/signedtxn.go
- ledger/cow_test.go
- ledger/eval_test.go
- ledger/perf_test.go
Test coverage for some functions in ledger/eval.go
This is tests!
> test coverage for ledger/eval.go funcs

- test/scripts/e2e_subs/sectok-app.sh
run some independent commands in parallel, total test 230s -> 170s
`20210526_115456 :179 finished e2e_subs/sectok-app.sh OK in 235.471021 seconds`
down to
`20210526_122739 :179 finished e2e_subs/sectok-app.sh OK in 169.771514 seconds`
This is a test, it still passes.
> sectok e2e faster

- debug/carpenter/main.go
This PR adds a timestamp to the carpenter output, allowing the user to correlate that timestamp with events in the event log, or other concurrent carpenter output.
> debug tools: improve carpenter by adding timestamp

- txnsync/txngroups_test.go
Ensure that we test the expected results rather than printing them.
> testing: ensure we test rather then log

- network/wsNetwork.go
- txnsync/mainloop.go
- txnsync/peer.go
Fix few bugs which prevented the non-fetching clients from working correctly, causing undesired load.
Tested manually, and appear to be working correctly.
> txnsync: fix few non-fetching clients bugs

- txnsync/mainloop.go
Update the message refresh rate when number of transaction rate drops. 
> txnsync: refresh message update rate

- data/ledger_test.go
The unit test had a corner case that would not ensure that all the rounds were flushed to disk.
Test using automated CI
> testing: fix random failure in TestConsensusVersion

- data/transactions/logic/TEAL_opcodes.md
Dumb single letter typo in docs.
> Forgot to run .md generation

- cmd/goal/application.go
- cmd/goal/asset.go
- cmd/goal/interact.go
This makes other txns accept explicitly low fees.  Sorry for the code
duplication, but I did not want to change libgoal's existing behavior
where it increases fee to minfee.
> Allow fee to be below minfee, if given explicitly.

- ledger/onlineacct.go
- ledger/onlineacct_test.go
- ledger/roundlru.go
- ledger/roundlru_test.go
- ledger/txtail_test.go
Add tests to increase coverage for onlineacct roundlru txtail
These are tests
> Add ledger coverage for onlineacct roundlru txtail

- ledger/blockqueue_test.go
Add tests to increase coverage for BlockQueue
These are tests
> testing: add unit tests for ledger BlockQueue

- scripts/travis/after_build.sh
- scripts/travis/run_tests.sh
Attempting to enable unit tests on the mac build scripts.
CI
> testing: enable unit tests on travis mac build

- test/e2e-go/cli/algod/expect/algod_expect_test.go
- test/e2e-go/cli/algoh/expect/algoh_expect_test.go
> fix double sharding

- .circleci/config.yml
This adds a hello world circleci yaml. This can be used to run circleci jobs on PRs until the pipeline is fully implemented.
> Implement hello circleci yaml

- .circleci/config.yml
- catchup/catchpointService.go
- catchup/service.go
- data/bookkeeping/genesis.go
- data/bookkeeping/msgp_gen.go
- data/pools/transactionPool.go
- data/transactions/logic/fields.go
- data/transactions/logic/fields_test.go
- gen/generate.go
- gen/walletData.go
- netdeploy/network.go
- node/node.go
- test/e2e-go/features/transactions/sendReceive_test.go
- test/testdata/nettemplates/DevModeNetwork.json
- util/timers/frozen.go
merge master into feature/txnsync branch
Use existing testing.
> txsync: merge master into feature/txnsync branch

- network/wsNetwork.go
- network/wsNetwork_test.go
- scripts/travis/build_test.sh
- scripts/travis/run_tests.sh
> keeping dilithium scheme int up-to-date

- protocol/codec_tester.go
This change is needed in order to support codec types such as the following:
```golang
//msgp:allocbound typeA 16
type typeA []typeB
```
since we want the codec object randomizer to recognize that `typeA` has a allocbound defined, and use that bound.
( this would be used in the feature/txnsync branch, but the change doesn't really related to any of the other changes in the feature/txnsync branch and would be a good change regardless )
> testing: improve testing of alloc bounded slices

- catchup/peerSelector_test.go
- protocol/codec_tester.go
merge changes from master into feature/txnsync branch
> txnsync: merge changes from master into feature/txnsync branch

- txnsync/bloomFilter.go
- txnsync/incoming.go
- txnsync/metrics.go
- txnsync/outgoing.go
- txnsync/peer.go
This PR adds few metrics to the txnsync. In the future, we might want to augment this further.
> txnsync: add metrics to txnsync

- txnsync/profiler.go
- txnsync/profiler_test.go
This PR adds unit tests to the profiler
Closes #2356 
> Added unit tests to profiler

- node/node.go
- txnsync/emulatorCore_test.go
- txnsync/service.go
- txnsync/service_test.go
Added unit tests and fixed some spelling errors
> Added Txnsync Service Unit Tests

- txnsync/bloomFilter.go
- txnsync/bloomFilter_test.go
- txnsync/peer.go
Added filterType field to bloomFilter struct
Added more tests to bloomFilter_test.go
This is a test PR.
> bloomFilter unit tests

- .github/ISSUE_TEMPLATE/algorand-engineering-team-issue-template.md
Updating Github engineering template for #2256
Previewed in Github
> 2256-Update Github engineering template

- data/transactions/logic/README.md
Fix auto-generated document that was missed on previous update.
Fix for auto-gen document.
> txnsync: fix auto-gen document

- data/transactions/transaction.go
- data/txHandler.go
- network/wsNetwork.go
- network/wsPeer.go
- node/txnSyncConn.go
- txnsync/bitmask.go
- txnsync/bloomFilter.go
- txnsync/bloomFilter_test.go
- txnsync/encodedgroupstypes.go
- txnsync/encodedgroupsunmarshalers.go
- txnsync/exchange.go
- txnsync/incoming.go
- txnsync/msgbuffers.go
- txnsync/peer.go
- txnsync/transactionCache.go
- txnsync/txngroups.go
- txnsync/txngroups_test.go
> txnsync: typos fix

- txnsync/incoming.go
- txnsync/incoming_test.go
- txnsync/msgorderingheap.go
- txnsync/service_test.go
This adds unit tests for incoming.go
This adds unit tests.
> txsync: incoming unit tests

- agreement/voteAggregator_test.go
While working on the agreement package, I noticed the wrong messageEvent type was being used in TestVoteAggregatorBundles (voteVerified instead of a bundleVerified). This leads voteAggregator to use filterVote instead of filterBundle, and read the empty `messageEvent.Input.Vote` value (with round/period/step of 0/0/0) rather than the value of `messageEvent.Input.Bundle` that has the correct RPS and bundle of votes. This leads the events to be thrown away as from an old round instead of being processed by dispatch.
This test didn't originally fail, I encountered the issue on a different branch where it was causing the test to crash — so I added an additional check to examine the output event returned by dispatch to make sure the votes were not being thrown away as too old.
> fix TestVoteAggregatorBundles and check router.dispatch() output

- txnsync/peer_test.go
Adds unit tests to the peer.go file
Resolves #2552
These are unit tests.
> Peer Unit Test

- test/heapwatch/metrics_delta.py
Add report line about txn pool fullness.
`txnpool({lowest reading}, {min(node mean txn pool size)}, {mean(node mean txnpool size)}, {max(node mean txnpool size)}, {highest reading})`
For a test running across 20 nodes, each node has a `node mean txn pool size` across a 20 minute test time. The above line reports the min/avg/max of those txn pool average sizes, and also the lowest and highest txn pool size seen at any moment.
This is a script used in development testing.
> report on txn pool fullness

- txnsync/msgorderingheap_test.go
Resolves #2550 
Adds unit tests to msgorderingheap.go
> Added msgorderingheap tests

- daemon/algod/api/server/router_test.go
Add partition to daemon/algod/api/server/router_test.go
Test on CircleCI via PR.
> partition router_test.go

- txnsync/txngroups.go
The `getMessageBuffer()` might return buffer that is bigger than what we need.
This doesn't present a problem on its own other than the fact that we were using that in order to detect the case where the compressed data consumes more space than the decompressed data.
For readability, I've renamed the `data` and `out` to `uncompressedData` and `compressedData` respectively.
> txnsync: fix compression

- txnsync/outgoing.go
- txnsync/outgoing_test.go
- txnsync/service_test.go
Adds unit tests to outgoing.go
Resolves #2551 
This is a unit test.
> Added outgoing unit tests

- txnsync/incoming.go
The evaluateIncomingMessage code was generating the following race condition:
```
algod(20395) : ==================
algod(20395) : WARNING: DATA RACE
algod(20395) : Read at 0x00c0062c0820 by goroutine 9:
algod(20395) :   github.com/algorand/go-algorand/txnsync.(*syncState).evaluateIncomingMessage()
algod(20395) :       github.com/algorand/go-algorand/txnsync/incoming.go:278 +0xa40
algod(20395) :   github.com/algorand/go-algorand/txnsync.(*syncState).mainloop()
algod(20395) :       github.com/algorand/go-algorand/txnsync/mainloop.go:194 +0x1770
algod(20395) : Previous write at 0x00c0062c0820 by goroutine 107:
algod(20395) :   github.com/algorand/go-algorand/data.(*TxHandler).processDecodedArray()
algod(20395) :       github.com/algorand/go-algorand/data/txHandler.go:392 +0x62e
algod(20395) …
```
> txnsync: avoid race condition in evaluateIncomingMessage

- .circleci/config.yml
- scripts/travis/build.sh
- scripts/travis/test.sh
Renamed no_gimme env var to skip_go_installation
Checking travis and circleci tests below
> Renamed no_gimme env var to skip_go_installation

- .circleci/config.yml
- .github/workflows/reviewdog.yml
- .golangci-warnings.yml
- Makefile
- cmd/partitiontest_linter/go.mod
- cmd/partitiontest_linter/linter_test.go
- cmd/partitiontest_linter/plugin/plugin.go
- config/consensus.go
- daemon/algod/api/client/restClient.go
- data/basics/overflow.go
- data/basics/units_test.go
- data/transactions/logic/README.md
- go.sum
- ledger/apply/application.go
- ledger/apply/application_test.go
- libgoal/libgoal.go
- logging/telemetryhook_test.go
- protocol/consensus.go
- scripts/travis/build.sh
- scripts/travis/test.sh
- shared/pingpong/accounts.go
- shared/pingpong/pingpong.go
- test/e2e-go/features/transactions/app_pages_test.go
- test/linttest/lintissues.go
merge master to txnsync branch
use existing unit tests.
>  txnsync: merge master to txnsync branch

- .circleci/config.yml
- .travis.yml
- config/config.go
- config/consensus.go
- config/version.go
- data/pools/transactionPool.go
- data/transactions/logic/backwardCompat_test.go
- data/transactions/logic/eval.go
- data/transactions/logic/eval_test.go
- scripts/travis/run_tests.sh
- test/e2e-go/upgrades/rekey_support_test.go
- test/scripts/e2e.sh
> txnsync: merge from master

- txnsync/msgbuffers_test.go
Added unit tests to msgbuffer in msgbuffers_test.go
Resolves #2459 
These are unit tests.
> testing: added MsgBuffer unit tests

- txnsync/bitmask.go
- txnsync/bitmask_test.go
- txnsync/encodedgroups_test.go
- txnsync/encodedgroupsunmarshalers.go
> txnsync: change iterate

- .travis.yml
- cmd/goal/account.go
- cmd/goal/accountsList.go
- cmd/goal/application.go
- cmd/netgoal/generate.go
- cmd/updater/update.sh
- netdeploy/remote/bootstrappedNetwork.go
- netdeploy/remote/deployedNetwork.go
- network/wsNetwork.go
- network/wsNetwork_test.go
- protocol/hash.go
- protocol/tags.go
- shared/pingpong/accounts.go
- shared/pingpong/pingpong.go
- test/e2e-go/cli/goal/expect/goalAccountInfoTest.exp
- test/e2e-go/cli/goal/expect/goalCmdFlagsTest.exp
- test/e2e-go/cli/goal/expect/goalExpectCommon.exp
- test/e2e-go/cli/goal/expect/goalNodeTest.exp
- test/e2e-go/cli/goal/expect/goal_expect_test.go
- test/e2e-go/cli/goal/expect/tealConsensusTest.exp
- test/framework/fixtures/expectFixture.go
- test/scripts/e2e.sh
- test/scripts/e2e_subs/e2e-app-extra-pages.sh
- test/testdata/deployednettemplates/recipes/bootstrappedScenario/Makefile
- test/testdata/deployednettemplates/recipes/bootstrappedScenario/boostrappedFile.json
- test/testdata/deployednettemplates/recipes/bootstrappedScenario/genesis.json
merge master into feature/txnsync branch
> txnsync: merge master into feature/txnsync branch

- txnsync/peerscheduler_test.go
- txnsync/service_test.go
Resolves #2462
Adds peer scheduler unit tests in peerscheduler_test.go
> Peer Scheduler Unit Tests

- data/basics/userBalance.go
- txnsync/bitmask.go
- txnsync/encodedgroups_test.go
- txnsync/encodedgroupsmarshalers.go
- txnsync/encodedgroupsunmarshalers.go
- txnsync/txngroups.go
- txnsync/txngroups_test.go
Address comments made by @tolikzinovyev regarding correctness and stylistic issues within the message encoding of the transaction sync.
> Fix bugs / refactor txnsync message encoding / decoding

- txnsync/bitmask.go
- txnsync/bitmask_test.go
Add an in-code comment.
in code comments do not require testing.
> Address pavel's comments on txnsync bitmasks

- compactcert/db.go
- compactcert/signer.go
- compactcert/worker_test.go
- crypto/compactcert/builder.go
- crypto/compactcert/builder_test.go
- crypto/compactcert/common_test.go
- crypto/compactcert/const.go
- crypto/compactcert/msgp_gen.go
- crypto/compactcert/structs.go
- crypto/compactcert/verifier.go
- data/account/participation.go
- data/accountManager.go
- gen/generate.go
- ledger/accountdb.go
- ledger/compactcert.go
- ledger/compactcert_test.go
- ledger/onlineacct.go
- ledger/voters.go
> Compact certificate code now uses the state proof.

- txnsync/emulatorCore_test.go
Improve the emulator setup of the transactions that would be exchanged.
> txnsync: improve emulator setup

- crypto/merklearray/layer.go
- crypto/merklearray/layer_test.go
> fix layer bug.

- data/basics/msgp_gen_test.go
- data/transactions/msgp_gen_test.go
The auto-generated msgp test files were not up-to-date.
This PR updates these.
> testing: fix auto-gen tests

- data/account/participation_test.go
> added benchmark to participation. refactored fillDB benchmark too.

- config/consensus.go
- crypto/hashes.go
- crypto/hashes_test.go
- crypto/merklearray/merkle_test.go
- crypto/util.go
- data/account/participation_test.go
- data/pools/transactionPool.go
- ledger/apply/keyreg_test.go
- test/e2e-go/upgrades/stateproof_test.go
> fixing comments and add PartitionTest

- crypto/hashes.go
- go.mod
- go.sum
> use updated version of sumhashfunction

- README.md
since we moved most of our builds to circleci i think it's time to update the status badges in the readme.md to reflect that
> Updating Readme.md with circleci status badges

- agreement/README.md
This PR fixes a link in a README.
I clicked on the new link.
> Fix algorand specs link

- cmd/partitiontest_linter/linter.go
The wording on this was tripping me, maybe I was having an off day. I think it would be slightly easier if the message were to tell exactly what you need to do (and not use the angle brackets).
> testing: reword partitiontest lint message.

- THANKS.md
> Add qkniep to THANKS.md

- cmd/tealdbg/localLedger.go
- daemon/algod/api/server/v2/dryrun.go
- ledger/catchpointtracker_test.go
- ledger/internal/cow_test.go
- ledger/internal/eval_test.go
Post merge fixes, have no idea where they went
> Post merge test compilation fixes

- cmd/catchpointdump/file.go
- ledger/accountdb.go
1. Generalized all accounts and resources reading from DB via callbacks
2. Use this new reading code in catchpointdump
This also requires changes from #3229
TODO
> ledger refactoring: catchpointdump support of new schema

- ledger/internal/eval.go
Should prevent unnecessary SQL queries for missing resources
> Ledger refactor: cache missing resources in roundCowBase

- ledger/accountdb.go
- ledger/accountdb_test.go
- ledger/acctupdates.go
- ledger/acctupdates_test.go
- ledger/catchpointtracker_test.go
- ledger/ledgercore/accountdata.go
- ledger/testing/randomAccounts.go
- ledger/tracker.go
- logging/telemetryspec/metric.go
Basic/initial draft implementation of resources writing to the disk
TODO:
1. Consider removing `rtype` and introducing rowid into `persistedResourcesData` 
2. Consider modifying data structures to minimize lookups like for addr to addrid resolution.
TODO:
1. Fix existing tests
2. Extend tests to check resources
> ledger refactoring: implement resources writing

- ledger/acctupdates_test.go
- ledger/catchpointtracker_test.go
After #2922 there is some leftover unused code for totals calculations. Turned this code into actual asserts.
This is tests update
> Add totals checks into acct updates tests

- ledger/accountdb.go
- ledger/acctupdates_test.go
Fix for deleted resources deltas + test
> Fix for deleted resources deltas + test

- network/wsNetwork.go
This PR deletes an unused constant.
None.
> Delete unused constant

- ledger/acctupdates_test.go
Fix TestCompactDeltasResources after #3348
> ledger refactoring: fix zero addrids in TestCompactDeltasResources

- netdeploy/network.go
> Fix typo Fulll to Full

- ledger/accountdb.go
- ledger/accountdb_test.go
- ledger/apply/application.go
- ledger/apply/application_test.go
- ledger/apply/asset.go
Few different changes in this PR:
1. make sure the stored UpdateRound in the resources base cache aligns with what we store on disk.
2. avoid some variable shadowing in apply package.
3. add some additional testing in the apply package, which should trigger in case the totals get out of sync with the resources.
Update unit tests.
> ledger refactoring: various touchups

- ledger/accountdb.go
small improvement for processAllResource, allowing to detect corrupted databases.
Use existing tests.
> ledger refactoring: small improvement for processAllResource

- ledger/accountdb.go
- ledger/accountdb_test.go
Added a test matrix for all possible resourceData and resourceDelta states
> ledger refactoring: resourceData tests

- ledger/accountdb.go
- ledger/accountdb_test.go
- ledger/acctupdates.go
set empty addrid for deleted resources in base case
> ledger refactoring: set empty addrid for deleted resources in base case

- ledger/accountdb.go
- ledger/applications_test.go
- ledger/catchpointtracker.go
Improve existing error messages, making them more informative.
> ledger refactoring: improve some of the error messages

- compactcert/worker_test.go
- crypto/compactcert/builder.go
- crypto/compactcert/builder_test.go
- crypto/compactcert/commitableSignatureSlot_test.go
- crypto/compactcert/verifier.go
- crypto/merklearray/proof.go
- crypto/merklearray/proof_test.go
- crypto/merklekeystore/committablePublicKeys_test.go
- crypto/merklekeystore/keystore.go
- crypto/merklekeystore/keystore_test.go
- ledger/ledgercore/votersForRound.go
- test/e2e-go/features/participation/onlineOfflineParticipation_test.go
> Integrate mss and vc

- ledger/accountdb_test.go
Improve TestAccountUnorderedUpdates: check all possible compact deltas orders
> Add compact deltas permutations into TestAccountUnorderedUpdates

- data/transactions/logic/README.md
- data/transactions/logic/TEAL_opcodes.md
- data/transactions/logic/assembler_test.go
- data/transactions/logic/doc.go
- data/transactions/logic/eval.go
- data/transactions/logic/evalStateful_test.go
- data/transactions/logic/eval_test.go
- data/transactions/logic/fields.go
- data/transactions/logic/fields_string.go
- data/transactions/logic/fields_test.go
Convenience to ease access to ABI return value
> txn LastLog

- ledger/evalindexer.go
- ledger/evalindexer_test.go
Indexer related changes.
None.
> ledger refactoring: Indexer related changes

- ledger/accountdb_test.go
> Test empty update entries for deleted accounts in accountsNewRound

- daemon/algod/api/server/v1/handlers/handlers.go
In #3330 the /v1/assets endpoint was modified to use LookupLatest just to fetch a single AssetParams object for a creator address, when it should just use LookupResource. This eliminates the unnecessary call to LookupLatest.
> ledger refactoring: get rid of LookupLatest from /v1/assets

- .circleci/config.yml
- crypto/merklearray/merkle_test.go
- ledger/acctupdates_test.go
- ledger/catchpointwriter_test.go
- test/e2e-go/features/transactions/proof_test.go
> fix memory consumption problem in testing

- agreement/pseudonode.go
- cmd/catchpointdump/database.go
- cmd/catchpointdump/file.go
- cmd/catchpointdump/net.go
- cmd/goal/common.go
- cmd/tealdbg/main.go
- cmd/util/cmd.go
- data/committee/sortition/sortition.go
- rpcs/txSyncer.go
- scripts/release/README.md
- scripts/release/test/util/test_package.sh
- test/packages/test_release.sh
- test/platform/test_linux_amd64_compatibility.sh
merge master into feature branch
use existing unit tests.
> ledger refactoring: merge master into feature branch

- ledger/accountdb.go
- ledger/acctupdates_test.go
Added a new function `loadFullAccount` that is a main workhorse for LoadAllFullAccounts,
and is also used in accountdb tests.
Added len vs Total checks in loadFullAccount.
catchpointdump utility was tested manually.
> Account sorting in catchpointdump printer

- crypto/merklearray/merkle.go
- crypto/merklearray/merkle_test.go
- crypto/merklearray/vectorCommitmentArray.go
A small fix to address PR comments from @tsachiherman and myself about wrapping errors in #2990.
Current tests should pass.
> Small fixes for go 1.13 style errors

- crypto/merklesignature/keysBuilder.go
This PR addresses the issues reported on the keyBuilder:
- replaces the `terminate` channel with an atomic variable ( which is safe to "close"/set from multiple go-routines )
- clean up some of the anonymous method parameters
- reduces the number of channel errors to 1
Use existing unit test
> address keybuilder issues

- THANKS.md
Following up on https://github.com/algorand/go-algorand/pull/3558, this PR update the THANKS.md file.
Not required for this change.
> update THANKS.md file

- cmd/goal/asset.go
closes #3591 
```sh
goal asset send --assetid 1 -f P75HT5DGUZ3TXI2TAESMJ2O7SMIC3WYFFQP5XARFTMAINI6OXOHANVMCOM -t P75HT5DGUZ3TXI2TAESMJ2O7SMIC3WYFFQP5XARFTMAINI6OXOHANVMCOM -a 100 -o tmp.txn --fee 0
goal clerk inspect tmp.txn # should have no fee set
```
> move txn template filler above fee setting

- compactcert/worker.go
- crypto/compactcert/builder_test.go
- crypto/compactcert/committableSignatureSlot_test.go
- crypto/merklesignature/committablePublicKeys.go
- crypto/merklesignature/keysBuilder_test.go
- data/basics/ccertpart.go
- ledger/apply/keyreg_test.go
- util/cmdUtils.go
Update import order
Not needed.
> update import order

- crypto/merklesignature/persistentMerkleSignatureScheme.go
- crypto/merklesignature/persistentMerkleSignatureScheme_test.go
- data/account/account.go
- data/account/participation.go
- data/account/participation_test.go
- node/node.go
- test/e2e-go/features/participation/participationExpiration_test.go
- test/e2e-go/upgrades/stateproof_test.go
* Bug Fixes
* add a fallback for missing state proof keys in participation file (#3619)
* testing: fix bug in TestParticipationAccountsExpirationFuture / TestParticipationAccountsExpirationNonFuture (#3616)
* testing: fix participation key expiration tests (#3621)
> go-algorand 3.4.0-beta 

- cmd/catchpointdump/file.go
- cmd/catchpointdump/net.go
New `--load` option forces catchpointdump to stop after loading catchpoint content
into ledger db without dumping  it as a text file.
> catchpointdump: load only option

- ledger/internal/eval.go
- ledger/internal/eval_blackbox_test.go
- ledger/internal/eval_test.go
* Minor linter fixes in internal package as well
> ledger: fix ledger.Eval code comments

- ledger/internal/appcow.go
- ledger/internal/assetcow.go
- ledger/internal/cow.go
- ledger/internal/eval_blackbox_test.go
- ledger/ledgercore/statedelta.go
Removed unused ModifiedAssetHoldings and ModifiedAppLocalStates
Updated tests where needed
> ledger refactoring: cleanup StateDelta

- data/basics/userBalance.go
- ledger/accountdb_test.go
- ledger/apply/application_test.go
- ledger/internal/appcow_test.go
- ledger/ledgercore/statedelta_test.go
Address CR comments from Idan and JJ.
> ledger refactoring: few CR fixes

- ledger/evalbench_test.go
- ledger/testing/testGenesis.go
Update the evaluator benchmark to cover application calls.
Note: the prefetcher changes would follow this one.
> ledger refactoring: update evaluator benchmarks

- .github/workflows/pr-type-category.yml
> CICD: Limit PR Type and Category check to master branch

- ledger/internal/eval_blackbox_test.go
Update tests per CR.
These are tests
> ledger refactoring: update tests

- ledger/internal/compactcert.go
- ledger/internal/compactcert_test.go
> Algod: compcert unit test error check fix

- crypto/merklesignature/kats_test.go
> add mss-kats generator

- cmd/opdoc/opdoc.go
- data/transactions/logic/langspec.json
Also pretty print langspec so that changes are easier to see.
> AVM: Add acct_params_get to langspec.json

- data/transactions/logic/eval.go
Moves `json_ref` expected type validation ahead of potentially expensive JSON processing.  
The PR is a small follow up stemming from https://github.com/algorand/go-algorand/pull/3857#discussion_r844133655.
> AVM:  Perform json_ref expected type validation before expensive JSON processing

- ledger/accountdb.go
- ledger/accountdb_test.go
- ledger/trackerdb.go
- ledger/txtail.go
- ledger/txtail_test.go
These are minor code style/naming fixes/leftovers after the https://github.com/algorand/go-algorand/pull/3748 merge
> 320 rounds: minor txTail fixes

- ledger/accountdb.go
- ledger/catchpointwriter_test.go
- ledger/trackerdb.go
It was a merge error with the older online accounts table in catchpoints definition
> 320 rounds: fix TestFullCatchpointWriter

- data/abi/abi_type.go
> ABI:  Fix typo in abi_type.go

- docker/build/cicd.ubuntu.Dockerfile
Git had a security patch that broke functionality. This is a temporary fix to restore the pipeline, but should be investigated more to implement a proper fix.
Verify that the pipeline completes successfully.
> Devops: Fix git safe directory handling

- test/scripts/e2e_subs/goal-partkey-commands.sh
There are multiple tests that create participation keys, so we need more lenient check relating to result ordering and numbers.
> tests: Fix flaky "goal-partkey-commands.sh" integration test.

- ledger/acctonline_test.go
This PR fixes the flaky TestAcctOnlineRoundParamsCache test. It was failing because it randomly increments rewards over 640 rounds and caused an overflow on the reward calculation. This pr fixes that by limiting the number of rounds run in the test to 200 by changing the maxBalLookback consensus param.
> 320 rounds: Fix flaky test

- ledger/ledger_test.go
- ledger/testing/randomAccounts.go
- ledger/txtail.go
Fixed `t.lowWatermark` value in `loadFromDisk` to match master as discovered by a test.
> TxTail reload test

- ledger/accountdb_test.go
Write tests for the setters and getters of baseOnlineAccountData
These are tests
> 320 rounds testing: test fields setters/getters for baseOnlineAccountData

- data/pools/transactionPool.go
- logging/telemetryspec/metric.go
Log state proof next round with AssembleBlock message when state proof is added to the block
> Log stateProof added to block

- ledger/ledger_test.go
Write a test that initialized ledger + db, pushes txns through the network, then restart ledger + migrate db. We want to ensure that all the online accounts data is correct after this process.
This is a test
> 320 rounds testing: migration and reload test

- ledger/ledger_test.go
The migration and reload test did not properly initialize the dbs. This pr fixes that
This is a test
> 320 rounds: Fix migration and reload test

- catchup/ledgerFetcher.go
- ledger/catchpointtracker.go
- ledger/tracker.go
Address Chris's feedback for two stage catchpoints PR #3928.
None.
> 320 rounds: feedback for two stage catchpoints

- test/e2e-go/features/catchup/catchpointCatchup_test.go
Test that catchpoint labels are generated (or not generated) under different local configurations.
This is a test
> 320 rounds testing: Catchpoint Label Test

- ledger/accountdb.go
- ledger/accountdb_test.go
- ledger/acctupdates.go
- ledger/acctupdates_test.go
- ledger/applications_test.go
- ledger/catchpointtracker.go
- ledger/catchpointtracker_test.go
- ledger/catchupaccessor.go
- ledger/trackerdb.go
- scripts/dump_genesis.sh
- util/db/interfaces.go
Based on #4043, reduced accountdb diff, merged feature/320-round
> 320 rounds: implement catchpoint persistence - enhancements

- go.mod
- go.sum
- ledger/catchpointtracker.go
- ledger/catchpointwriter.go
- ledger/catchpointwriter_test.go
Based on benchmarks of different algorithms (zstd, zlib.BestSpeed, snappy) by @algorandskiy 
> 320 rounds: use snappy for stage 1 compression

- stateproof/builder.go
- stateproof/msgp_gen.go
- stateproof/signer.go
> renamed SigFromAddr's fields

- ledger/accountdb.go
- ledger/catchpointtracker_test.go
Add various tests testing catchpoint tracker's persistence (crash handling).
These new tests pass. :)
> Catchpoint tracker persistence tests

- stateproof/abstractions.go
- stateproof/worker_test.go
Test the broadcast function to make sure each locally generated signature is broadcast twice per period, and each received message is broadcast once.
> Add test TestSigBroacastTwoPerSig

- data/transactions/transaction.go
- data/transactions/transaction_test.go
- stateproof/stateproofMessageGenerator_test.go
- stateproof/worker_test.go
added well-formed tests for stateproof-txn
> testing: Is stateproof tx well formed

- ledger/catchpointtracker_test.go
Small improvements in catchpoint tracker tests.
Tests pass.
> Small improvements in catchpoint tracker tests.

- ledger/onlineaccountscache_test.go
```
BenchmarkOnlineAccountsCacheRead320
BenchmarkOnlineAccountsCacheRead320-8    	     100	  10578548 ns/op
BenchmarkOnlineAccountsCacheRead2560
BenchmarkOnlineAccountsCacheRead2560-8   	     100	 295423639 ns/op
```
Closes https://github.com/algorand/go-algorand-internal/issues/2070.
Ran it.
> A benchmark for `onlineAccountsCache.read()`

- cmd/catchpointdump/net.go
Various fixes in the `catchpointdump` utility.
The bug I experienced is as follows. The watchdog stream reader errors because it is not reset soon enough (probably due to long disk flushes on my computer). Then `downloadCatchpoint()` attempts to return an error, but a defer statement overrides it with `nil`. As a result, the failure is ignored, and the next stage (loading into sqlite db) starts. Later on it fails.
I increased watchdog stream reader's time limit from 2s to 5s and fixed the bug from above as well as some other error handling issues. I actually don't really understand what benefit the watchdog provides, but false positives are clearly possible. Maybe we should not use it?
Ran the tool.
> catchpointdump: fixes

- ledger/acctonline_test.go
- removed `TestAcctOnlineTopSecondarySortOrder` since it was already been tested
- add db behind in-memory test
> add test for db  behind in-memory

- crypto/merklearray/merkle.go
- crypto/merklearray/proof.go
- crypto/merklearray/proof_test.go
- daemon/algod/api/client/restClient.go
- daemon/algod/api/server/v2/test/handlers_test.go
- libgoal/libgoal.go
- test/e2e-go/features/stateproofs/stateproofs_test.go
- test/e2e-go/features/transactions/proof_test.go
- test/framework/fixtures/libgoalFixture.go
> Block proof e2e

- ledger/accountdb.go
- ledger/accountdb_test.go
- ledger/acctupdates.go
- ledger/tracker.go
- ledger/txtail_test.go
Rename round -> rnd column in new table for consistency
> 320 rounds PR feedback

- ledger/accountdb.go
- ledger/accountdb_test.go
- ledger/acctonline.go
- ledger/acctupdates.go
- ledger/txtail.go
* seenAddr in onlineAccountsAll
* createNormalizedOnlineBalanceIndex
* comments
> 320 rounds: PR feedback fixes

- ledger/catchpointtracker_test.go
- test/e2e-go/features/catchup/catchpointCatchup_test.go
* Adjust config and proto
* Increase wait period for one catchpoint interval
to let the catchpoint second state complete
> tests: fixes to catchpoint e2e tests

- test/testdata/deployednettemplates/recipes/hello-world/genesis.json
- test/testdata/deployednettemplates/recipes/scenario1/genesis.json
- test/testdata/deployednettemplates/recipes/scenario2/genesis.json
- test/testdata/deployednettemplates/recipes/scenario3/genesis.json
Update scenario1, scenario2, scenario3, and hello world recipes to use protocol "alpha2".  
Tested
> DevOps: Updated alphanet algonet recipe genesis files to use alpha2 protocol.

- data/transactions/logic/README.md
- data/transactions/logic/TEAL_opcodes.md
- data/transactions/logic/assembler_test.go
- data/transactions/logic/box.go
- data/transactions/logic/box_test.go
- data/transactions/logic/doc.go
- data/transactions/logic/eval.go
- data/transactions/logic/evalStateful_test.go
- data/transactions/logic/export_test.go
- data/transactions/logic/langspec.json
- data/transactions/logic/ledger_test.go
- data/transactions/logic/opcodes.go
- data/transactions/logic/teal.tmLanguage.json
- ledger/internal/applications.go
New opcodes that are intended to make the simplest uses of boxes very easy.
> box_len, box_put, and box_get to streamline simple uses

- cmd/algod/main_test.go
- cmd/algokey/part.go
- cmd/updater/update.sh
- data/account/participationRegistry_test.go
- data/transactions/logic/README.md
- data/transactions/logic/TEAL_opcodes.md
- data/transactions/logic/fields.go
- gen/generate_test.go
- ledger/accountdb.go
- ledger/accountdb_test.go
- ledger/archival_test.go
- ledger/catchpointtracker_test.go
- ledger/catchpointwriter_test.go
- ledger/internal/prefetcher/prefetcher.go
- ledger/internal/prefetcher/prefetcher_alignment_test.go
- ledger/internal/prefetcher/prefetcher_test.go
- ledger/ledger_perf_test.go
- ledger/ledger_test.go
- ledger/ledgercore/accountdata.go
- logging/telemetryConfig_test.go
- logging/telemetryhook_test.go
- netdeploy/networkTemplates_test.go
- netdeploy/network_test.go
- node/node_test.go
- test/e2e-go/features/catchup/catchpointCatchup_test.go
- test/e2e-go/features/participation/accountParticipationTransitions_test.go
- test/e2e-go/features/transactions/onlineStatusChange_test.go
- test/framework/fixtures/expectFixture.go
- util/db/dbutil.go
- util/db/dbutil_test.go
> Merge master into stateproof

- crypto/stateproof/const.go
- crypto/stateproof/verifier.go
- crypto/stateproof/verifier_test.go
- data/bookkeeping/lightBlockHeader.go
- data/bookkeeping/msgp_gen.go
> StateProof verifier rejects long proofs

- data/account/participationRegistry_test.go
- test/e2e-go/features/stateproofs/stateproofs_test.go
- test/testdata/nettemplates/StateProofMultiWallets.json
> add multiaccount state proof tests

- ledger/acctonline.go
- ledger/ledger_test.go
- ledger/voters.go
- stateproof/worker_test.go
> BugFix VotersTracker loadFromDisk

- data/ledger_test.go
> Test: Fix typo in ledger_test.go

- data/bookkeeping/lightBlockHeader.go
- data/bookkeeping/lightBlockHeader_test.go
- data/bookkeeping/msgp_gen.go
> Msgp sort lightheader

- ledger/acctonline.go
- ledger/tracker.go
- ledger/txtail.go
Add logging statements to newly added areas of the ledger from the 320 rounds project. Added blanket logging to handle all errors that happen during commit round. Logging already exists for error handling within catchpoints and loading from disk.
Reran existing tests.
> 320 rounds: Add logging for new logic

- ledger/acctonline.go
Fix lock/unlock of accountsMu in a loop.
This crashed sometimes in a large cluster test before, but works now.
> ledger: fix accountsMu usage

- test/testdata/deployednettemplates/recipes/mmnet/Makefile
- test/testdata/deployednettemplates/recipes/mmnet/gen_topology.py
- test/testdata/deployednettemplates/recipes/mmnet/genesis.json
- test/testdata/deployednettemplates/recipes/mmnet/net.json
- test/testdata/deployednettemplates/recipes/mmnet/topology.json
- this updates the mmnet recipe to have 1 algod/wallet/node
- this also increases the number of participating and non-participating node to 16 and 130 base d on a similar distribution to mainnet
- performance pipeline
> cicd: update mmnet netgoal parameters

- test/e2e-go/features/stateproofs/stateproofs_test.go
Fix merge issue: StateProofIntervalLatestRound dropped
> fix test merge issue

- catchup/catchpointService.go
- components/mocks/mockParticipationRegistry.go
- config/consensus.go
- crypto/stateproof/builder.go
- crypto/stateproof/builder_test.go
- crypto/stateproof/weights.go
- daemon/algod/api/server/v2/test/helpers.go
- data/account/participationRegistry.go
- data/account/participationRegistry_test.go
- data/accountManager.go
- data/pools/transactionPool_test.go
- ledger/accountdb.go
- ledger/apply/apply.go
- ledger/apply/stateproof.go
- ledger/internal/eval_test.go
- ledger/ledger_test.go
- ledger/voters.go
- ledger/voters_test.go
- stateproof/abstractions.go
- stateproof/builder.go
- stateproof/recovery.go
- stateproof/stateproofMessageGenerator_test.go
- stateproof/verify/stateproof.go
- stateproof/verify/stateproof_test.go
- stateproof/worker_test.go
> Stateproofs: fix CR comments

- test/e2e-go/cli/goal/expect/goalExpectCommon.exp
Improve and fix debug logging in expect tests.
> tests: improve logging in expect tests

- ledger/accountdb_test.go
> Box Storage Performance Tests

- crypto/merklesignature/committablePublicKeys.go
This PR removes an extraneous space from a comment within the `crypto` package.
Only a comment was edited.
> Algod: Make small change to the simulate-endpoint feature branch to make it possible to open a draft PR

- config/consensus.go
Addresses https://github.com/algorand/go-algorand/pull/4149#discussion_r968599733.
> Refactor MaxBoxSize configuration definition

- config/localTemplate.go
- config/local_defaults.go
- installer/config.json.example
- test/testdata/configs/config-v24.json
Applies feedback from https://github.com/algorand/go-algorand/pull/4149#discussion_r968680487.
> Bump MaxAPIBoxPerApplication to 100,000

- cmd/goal/README.md
- cmd/goal/box.go
- cmd/goal/messages.go
- config/consensus.go
- data/transactions/application.go
- data/transactions/json_test.go
- data/transactions/logic/box.go
- data/transactions/logic/eval.go
- data/transactions/logic/evalStateful_test.go
- data/transactions/logic/eval_test.go
- data/transactions/logic/ledger_test.go
- ledger/acctupdates.go
- ledger/apptxn_test.go
- ledger/boxtxn_test.go
- ledger/catchpointwriter.go
- ledger/catchpointwriter_test.go
- ledger/msgp_gen.go
- libgoal/libgoal.go
- test/e2e-go/restAPI/restClient_test.go
- test/scripts/e2e_subs/box-search.sh
Child PR to #4149
Various fixes/improvements for the boxes branch, based on my review and other comments.
Unless otherwise noted, I believe most of these are straightforward improvements.
> Various improvements from my review

- cmd/catchpointdump/file.go
- cmd/goal/formatting.go
- data/transactions/logic/doc.go
- ledger/accountdb.go
- ledger/acctupdates.go
- ledger/catchpointtracker.go
- ledger/catchpointwriter_test.go
- ledger/tracker.go
Code review changes. Reviewers selected because they made the comments being addressed.
> Box codereview

- .circleci/config.yml
No changes, just moving commands after jobs due to hierarchy being workflow -> job -> command. (and added comments for clarify)
> CICD: Reordering circleci config

- cmd/opdoc/tmLanguage.go
- data/transactions/logic/README.md
- data/transactions/logic/README_in.md
- data/transactions/logic/TEAL_opcodes.md
- data/transactions/logic/box.go
- data/transactions/logic/box_test.go
- data/transactions/logic/doc.go
- data/transactions/logic/eval.go
- data/transactions/logic/evalStateful_test.go
- data/transactions/logic/eval_test.go
- data/transactions/logic/export_test.go
- data/transactions/logic/fields_test.go
- data/transactions/logic/langspec.json
- data/transactions/logic/ledger_test.go
- data/transactions/logic/pairing.go
- data/transactions/logic/teal.tmLanguage.json
- data/txntest/txn.go
- ledger/boxtxn_test.go
- ledger/internal/applications.go
Also, no boxes in ClearState.
Spec updates of various kinds
> New rule: write budget enforced continually

- SECURITY.md
> Docs: Update SECURITY.md

- cmd/tealdbg/localLedger.go
- crypto/msgp_gen.go
- daemon/algod/api/server/v2/dryrun.go
- ledger/accountdb.go
- ledger/acctupdates.go
- ledger/apply/apply.go
- ledger/apply/stateproof.go
- ledger/evalindexer.go
- ledger/internal/appcow_test.go
- ledger/internal/cow.go
- ledger/internal/cow_test.go
- ledger/internal/eval.go
- ledger/internal/eval_test.go
- ledger/internal/prefetcher/prefetcher_alignment_test.go
- ledger/ledger.go
- ledger/ledger_test.go
- ledger/ledgercore/msgp_gen.go
- ledger/ledgercore/msgp_gen_test.go
- ledger/ledgercore/stateproofverification.go
- ledger/stateproofverificationtracker.go
- ledger/stateproofverificationtracker_test.go
- ledger/tracker.go
- scripts/dump_genesis.sh
- stateproof/verify/stateproof.go
- stateproof/verify/stateproof_test.go
> StateProofs: Spv tracking cr fixes

- go.mod
- go.sum
Upgrade avm-abi from v0.1.0 to v0.1.1 to introduce new fixes
> Bug-Fix: upgrade avm-abi

- stateproof/builder.go
- stateproof/db.go
- stateproof/stateproofMessageGenerator_test.go
- stateproof/worker_test.go
> StateProofs: Sp recovery test refactor

- tools/network/resolver_test.go
Re-enables `TestResolverWithCloudflareDNSResolution` by using Cloudflare's secondary DNS.  Based on the successful CI build, it appears CircleCI is _not_ blocking access to 1.0.0.1.  
I'm presenting the PR under the assumption that we'd prefer to retain _some_ version of a test against Cloudflare.  If the assumption is false, then I'll close the PR.
> Tests: Re-enable TestResolverWithCloudflareDNSResolution in CircleCI

- cmd/tealdbg/localLedger.go
- daemon/algod/api/server/v2/dryrun.go
- ledger/acctupdates.go
- ledger/apply/apply.go
- ledger/apply/stateproof.go
- ledger/apply/stateproof_test.go
- ledger/catchpointtracker_test.go
- ledger/catchpointwriter.go
- ledger/catchupaccessor_test.go
- ledger/evalindexer.go
- ledger/internal/appcow_test.go
- ledger/internal/cow.go
- ledger/internal/cow_test.go
- ledger/internal/eval.go
- ledger/internal/eval_test.go
- ledger/internal/prefetcher/prefetcher_alignment_test.go
- ledger/ledger.go
- ledger/store/stateProofVerificationAccessor.go
- protocol/hash.go
- stateproof/abstractions.go
> StateProof Recoverability: Fix CR comments

- crypto/merklearray/merkle_test.go
- test/e2e-go/features/catchup/catchpointCatchup_test.go
- test/e2e-go/features/catchup/stateproofsCatchup_test.go
- test/e2e-go/features/stateproofs/stateproofs_test.go
> Increase stateproof interval in nightly e2e

- ledger/ledger_test.go
> Ledger Tests: fixed incorrect locking usage

- CONTRIBUTING.md
> docs: link to security doc, minor formatting

- test/e2e-go/features/stateproofs/stateproofs_test.go
> stateproof: e2e flakey-test AttestorsChange 

- ledger/README.md
- ledger/bulletin.go
- ledger/bulletin_test.go
- ledger/ledger.go
- ledger/ledger_test.go
- ledger/tracker.go
- ledger/voters.go
- stateproof/abstractions.go
- stateproof/builder.go
- stateproof/stateproofMessageGenerator_test.go
- stateproof/worker_test.go
Reverts algorand/go-algorand#5099
> Revert "ledger: eternalData trackers concept"

- ledger/ledger_test.go
TestMetricsReload fails if some ledger in other tests not closed. This is a fix for that.
This is fix in tests
> ledger: fix metrics test

- ledger/acctonline_test.go
- ledger/acctupdates_test.go
- ledger/catchpointtracker_test.go
Made sure that blocks are added to the mock ledger's stand in for blockq before scheduling their commits.
> Fix errors tests log

- cmd/catchpointdump/file.go
- ledger/catchpointtracker_test.go
- ledger/catchpointwriter.go
- ledger/catchupaccessor.go
- ledger/catchupaccessor_test.go
- ledger/ledgercore/votersForRound.go
- ledger/spverificationtracker.go
- ledger/store/spVerificationAccessor.go
- stateproof/builder.go
> StateProofRecoverability:  fix comments

- data/transactions/verify/streamverifier_test.go
TestStreamVerifierPoolShutdown tests the behavior of stream verifier when the execution pool shuts down.
Background:
The backlog has an inherent indeterminism: when it shuts down and the ctx is canceled, it returns an error only if the select picks the ctx check. To guarantee the ctx check selection, the channel must be full. 
The problem:
The test was not waiting for the shutdown to return. Since the shutdown was on a separate goroutine, occasionally the tasks were going into the pool, and getting lost there. The test gets stuck when this happens, waiting for an error.
Moreover, even after shutting down the backlog, the queue must be filled so that the select with pick the ctx and return an error. 
The fix:
The test now waits for the shutdown, then makes sure the queue is full.
> test: Fix TestStreamVerifierPoolShutdown

- cmd/algocfg/profileCommand.go
- cmd/algocfg/profileCommand_test.go
Provide list of valid profiles in order to help users correct the mistake if they provide an invalid profile.
Unit test.
> algocfg(profile): improve invalid profile error message.

- README.md
> docs: add titles of subsystems, minor md fixes

- .github/ISSUE_TEMPLATE/bug_report.md
> docs: Fix bug label

- stateproof/README.md
This PR adds some high level design of the state proof package
> Algod: Add README file to state proof package

- rpcs/blockService_test.go
> typo: Fix typo in blockService_test.go

- ledger/store/trackerdb/interface.go
- ledger/store/trackerdb/sqlitedriver/sql.go
- ledger/store/trackerdb/sqlitedriver/sql_test.go
> Chore: more deadcode

- tools/block-generator/README.md
- tools/block-generator/scenarios/benchmarks/organic.25000.yml
- tools/block-generator/scenarios/benchmarks/organic.50000.yml
- tools/block-generator/scenarios/benchmarks/payment.25000.yml
- tools/block-generator/scenarios/benchmarks/payment.50000.yml
- tools/block-generator/scenarios/benchmarks/stress.25000.yml
- tools/block-generator/scenarios/benchmarks/stress.50000.yml
New scenarios for Conduit performance benchmarks.
N/A
> block-generator: conduit performance benchmark scenarios.

- docs/follower_node.md
Fix broken markdown in documentation.
> docs: Fix broken markdown in follower documentation.

- ledger/acctupdates.go
- ledger/ledger.go
This adds timing counters (similar to others in the ledger) that measure how long we might be waiting in a round while accountsMu and trackerMu are locked. 
> metrics: add counters for ledger locks trackerMu and accountsMu

- agreement/actions.go
- agreement/player.go
- logging/telemetryspec/event.go
Adds voteValidatedAt to the BlockAcceptedEvent for telemetry, for #5654 
> agreement: add voteValidatedAt to telemetry for dynamic lambda

- ledger/store/trackerdb/generickv/accounts_ext_reader.go
- ledger/store/trackerdb/generickv/accounts_ext_writer.go
- ledger/store/trackerdb/generickv/accounts_reader.go
- ledger/store/trackerdb/generickv/accounts_writer.go
- ledger/store/trackerdb/generickv/migrations.go
- ledger/store/trackerdb/generickv/onlineaccounts_reader.go
- ledger/store/trackerdb/generickv/onlineaccounts_writer.go
- ledger/store/trackerdb/generickv/schema.go
- ledger/store/trackerdb/generickv/stateproof_reader.go
- ledger/store/trackerdb/generickv/stateproof_writer.go
- ledger/store/trackerdb/testsuite/onlineaccounts_kv_test.go
This addresses most of the comments left in #5488
Resolves https://github.com/algorand/go-algorand/issues/5538
> ledger: kv keys allocation optimizations

- agreement/player.go
- agreement/player_permutation_test.go
- agreement/proposalManager.go
> dynamic lambda: split proposalFresh and proposalUsedForCredentialHistory

- data/transactions/logic/assembler.go
I was working on something. It didn't work out, but might as well commit the comment fixes.
> Docs: No code change

- README.md
- data/transactions/logic/README.md
- data/transactions/logic/README_in.md
- data/transactions/logic/jsonspec.md
- docs/follower_node.md
- scripts/windows/instructions.md
> typo: fix typos in md files

- daemon/algod/server.go
- test/testdata/deployednettemplates/generate-recipe/generate_network.py
- test/testdata/deployednettemplates/recipes/custom/configs/node.json
For release debugging implement a memory limit to prevent OOM.
N/A
This is for testing.
> Debug: limit memory for testing

- .aptly.conf
- docker/build/aptly.Dockerfile
- docker/build/docker.ubuntu.Dockerfile
- package-deploy.yaml
- scripts/release/mule/deploy/deb/deploy.sh
Infrastructure changes needed some revisions to handle platform updates. This updates aptly repository management to use more modern software and simplify parts of the workflow.
Ran independently to verify it worked.
> CICD: fix aptly repo management

- SECURITY.md
Update SECURITY.md to reflect current reporting links. Closes #5892 
N/A
> Docs: Updates to SECURITY.md

- data/transactions/logic/eval.go
- data/transactions/logic/evalAppTxn_test.go
relstable3.22.1-remerge mergeback
> CICD: go-algorand relstable3.22.1-remerge mergeback

- ledger/ledger_test.go
> Tests: Fix `AccountsUpdateSchemaTest` ignoring error bug

- heartbeat/README.md
Heartbeat README tweaks from readers.
> README: Heartbeat README tweaks

- test/e2e-go/features/incentives/challenge_test.go
- util/set.go
> Testing: Correct an off by one, and retry instead of fail with bad accounts

- .gitignore
> Build: .gitignore .claude

- CONTRIBUTING.md
- cmd/util/datadir/datadir.go
> chore: remove redundant words

- README.md
Update the developer website url in the README to point to the new site
> readme: update developer portal url
